// GENERATED — do not hand-edit.
// Source of truth is Projects/SongGhost/Email Campaign/ in Drive; regenerate
// from campaign.md + html/NN.{html,txt} if the copy changes.
//
// `day` is days since the contact was tagged prompt-book. The day-0 delivery
// email is sent separately by api/ebook-signup.ts, so this sequence starts at
// day 1 and must never re-send the book.

export type NurtureEmail = {
  n: number;
  day: number;
  subject: string;
  preview: string;
  html: string;
  text: string;
};

export const NURTURE_EMAILS: NurtureEmail[] = [
  {
    "n": 1,
    "day": 1,
    "subject": "Don't read the whole thing",
    "preview": "One small thing beats 55 pages you never open.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>You grabbed the book yesterday. If it is still sitting in your downloads\nfolder, that is completely fine. I would rather you do one small thing than\nread fifty-five pages and do nothing.</p>\n  <p>So here is the one small thing.</p>\n  <p>Open SongGhost. Think of the song you want. Then, before you hit go, add one\ndetail you could not have looked up. A name. A street. A smell. The dumb\nobject you kept for no reason.</p>\n  <p>Not \"a song about my mom.\"</p>\n  <p>Try \"my mom Reyna cut hair in our kitchen for thirty years.\"</p>\n  <p>That is the whole assignment. One true thing.</p>\n  <p>Everything else in the book makes that better. Nothing in the book matters\nmore than that.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Open SongGhost</a>\n  </p>\n  <p>— Rudy</p>\n\n  <p style=\"font-size:14px;color:#666;border-top:1px solid #e6e0d4;padding-top:14px;margin-top:26px\">The reasoning is chapter two, <a href=\"https://songghost.com/the-prompt-book.pdf\">Why your first song came back flat</a>. Four pages. Read it after.</p>\n</div>",
    "text": "Hey {{contact.first_name}},\n\nYou grabbed the book yesterday. If it is still sitting in your downloads\nfolder, that is completely fine. I would rather you do one small thing than\nread fifty-five pages and do nothing.\n\nSo here is the one small thing.\n\nOpen SongGhost. Think of the song you want. Then, before you hit go, add one\ndetail you could not have looked up. A name. A street. A smell. The dumb\nobject you kept for no reason.\n\nNot \"a song about my mom.\"\n\nTry \"my mom Reyna cut hair in our kitchen for thirty years.\"\n\nThat is the whole assignment. One true thing.\n\nEverything else in the book makes that better. Nothing in the book matters\nmore than that.\n\nOpen SongGhost: https://songghost.com/app\n\n— Rudy\n\nP.S. The reasoning is chapter two, Why your first song came back flat. Four pages. Read it after."
  },
  {
    "n": 2,
    "day": 3,
    "subject": "The scissors in the glovebox",
    "preview": "Why one strange detail beats ten true feelings.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>Here is a real prompt someone could hand me:</p>\n  <p><em>My mom's name is Reyna. She cut hair in our kitchen for thirty years. The\nhouse always smelled like perm solution and coffee. She died in April. I keep\nher scissors in my glovebox and I don't know why.</em></p>\n  <p>Look at what that gives me. A name. A room. A smell. A month. And one strange,\nspecific, completely true thing that nobody else on earth would have handed me.</p>\n  <p>The scissors are the part that matters.</p>\n  <p>I do not need them explained. I do not need to know why they are in the\nglovebox — she does not know either, and she said so. That not-knowing is the\nsong. All I have to do is not get in the way of it.</p>\n  <p>Feelings are smooth. Things have edges. When you give me feelings, I write the\naverage version, because every grieving person feels roughly the same handful\nof things. When you give me the scissors, there is only one person that song\ncould belong to.</p>\n  <p>So: what is your scissors-in-the-glovebox? The thing you kept that makes no\nsense. Put that in.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Try it on one song</a>\n  </p>\n  <p>— Rudy</p>\n\n</div>",
    "text": "Hey {{contact.first_name}},\n\nHere is a real prompt someone could hand me:\n\nMy mom's name is Reyna. She cut hair in our kitchen for thirty years. The\nhouse always smelled like perm solution and coffee. She died in April. I keep\nher scissors in my glovebox and I don't know why.\n\nLook at what that gives me. A name. A room. A smell. A month. And one strange,\nspecific, completely true thing that nobody else on earth would have handed me.\n\nThe scissors are the part that matters.\n\nI do not need them explained. I do not need to know why they are in the\nglovebox — she does not know either, and she said so. That not-knowing is the\nsong. All I have to do is not get in the way of it.\n\nFeelings are smooth. Things have edges. When you give me feelings, I write the\naverage version, because every grieving person feels roughly the same handful\nof things. When you give me the scissors, there is only one person that song\ncould belong to.\n\nSo: what is your scissors-in-the-glovebox? The thing you kept that makes no\nsense. Put that in.\n\nTry it on one song: https://songghost.com/app\n\n— Rudy"
  },
  {
    "n": 3,
    "day": 5,
    "subject": "Nobody is home in your song",
    "preview": "Say who is talking, and who they are talking to.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>Most flat songs are flat for a boring reason. Nobody is home in them.</p>\n  <p>If I do not know who is speaking, I write a narrator with no face. A voice\nfrom nowhere, saying true things, to no one in particular. It scans fine. It\nlands on nobody.</p>\n  <p>The fix takes one line:</p>\n  <p><em>This is me talking to my brother, who is not speaking to me right now.</em></p>\n  <p>Read that and notice what it does. Every line now has somewhere to travel. The\nchorus cannot be a general statement about family any more — it has to be\nsomething you would actually say to <em>him</em>, knowing he might not pick up.</p>\n  <p>It changes what the song is even allowed to say.</p>\n  <p>Try it on something you already made. Same prompt, same everything, but add\none sentence saying who is talking and who they are talking to. Then read the\ntwo side by side.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Give it a direction</a>\n  </p>\n  <p>— Rudy</p>\n\n</div>",
    "text": "Hey {{contact.first_name}},\n\nMost flat songs are flat for a boring reason. Nobody is home in them.\n\nIf I do not know who is speaking, I write a narrator with no face. A voice\nfrom nowhere, saying true things, to no one in particular. It scans fine. It\nlands on nobody.\n\nThe fix takes one line:\n\nThis is me talking to my brother, who is not speaking to me right now.\n\nRead that and notice what it does. Every line now has somewhere to travel. The\nchorus cannot be a general statement about family any more — it has to be\nsomething you would actually say to him, knowing he might not pick up.\n\nIt changes what the song is even allowed to say.\n\nTry it on something you already made. Same prompt, same everything, but add\none sentence saying who is talking and who they are talking to. Then read the\ntwo side by side.\n\nGive it a direction: https://songghost.com/app\n\n— Rudy"
  },
  {
    "n": 4,
    "day": 8,
    "subject": "You are in the wrong room",
    "preview": "The easiest win in the whole book, and most people skip it.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>This is the one people skip, and it is the easiest win in the book.</p>\n  <p>Every genre has smaller rooms inside it.</p>\n  <p>Country has a honky-tonk bar and it has a stadium. Gospel has a full choir and\nit has one person at a piano. Same genre. Completely different songs. If you\nsay \"country\" and nothing else, you get whichever room I default to — and that\nmay not be the one you were picturing.</p>\n  <p>I decide by listening for particular words.</p>\n  <p>Say <strong>honky-tonk</strong> and you get the bar. Say <strong>arena</strong>\nand you get the stadium. Say <strong>front porch</strong> and you get one\nperson and an acoustic guitar.</p>\n  <p>They are not magic words and they are not secret. They are just the words I am\nlistening for. Your genre's page in the book lists them — a hundred and\neighty-three of them across thirteen genres, checked one by one against what I\nactually respond to.</p>\n  <p>Go to your genre. Steal one word. Put it in the box.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Pick your room</a>\n  </p>\n  <p>— Rudy</p>\n\n  <p style=\"font-size:14px;color:#666;border-top:1px solid #e6e0d4;padding-top:14px;margin-top:26px\">Thirteen genres, two pages each, in <a href=\"https://songghost.com/the-prompt-book.pdf\">the book</a>.</p>\n</div>",
    "text": "Hey {{contact.first_name}},\n\nThis is the one people skip, and it is the easiest win in the book.\n\nEvery genre has smaller rooms inside it.\n\nCountry has a honky-tonk bar and it has a stadium. Gospel has a full choir and\nit has one person at a piano. Same genre. Completely different songs. If you\nsay \"country\" and nothing else, you get whichever room I default to — and that\nmay not be the one you were picturing.\n\nI decide by listening for particular words.\n\nSay honky-tonk and you get the bar. Say arena\nand you get the stadium. Say front porch and you get one\nperson and an acoustic guitar.\n\nThey are not magic words and they are not secret. They are just the words I am\nlistening for. Your genre's page in the book lists them — a hundred and\neighty-three of them across thirteen genres, checked one by one against what I\nactually respond to.\n\nGo to your genre. Steal one word. Put it in the box.\n\nPick your room: https://songghost.com/app\n\n— Rudy\n\nP.S. Thirteen genres, two pages each, in the book."
  },
  {
    "n": 5,
    "day": 11,
    "subject": "Same app, same day, sixty seconds more typing",
    "preview": "I ran both prompts so you can see the difference.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>I did not want to just tell you this works. So I ran both prompts through\nSongGhost for real, on the same day, with the same settings. The only thing I\nchanged was the words in the box.</p>\n  <p><strong>The weak one:</strong> <em>a song about my grandma</em></p>\n  <p>It came back called \"Grandma's Song.\"</p>\n  <p><em>You always kept the porch light on<br>\nWaiting up for me to come home<br>\nWith cookies warm and open arms<br>\nA little laugh, your favorite song</em></p>\n  <p>That is not bad writing. It is just not about anyone. Porch light, cookies,\nopen arms — every line could belong to any grandmother who ever lived.</p>\n  <p><strong>The strong one</strong> named her, put her in a kitchen in Tucson, and\ngave me one line she always said.</p>\n  <p>It came back called \"Use Your Hands.\"</p>\n  <p><em>Sunday morning, Tucson sun<br>\nGrandma Rosa in the kitchen, flour on her thumbs<br>\nApron tied, she smiles at me<br>\n\"Mi niña, let's make memories\"</em></p>\n  <p>The title came out of the detail, not the topic. Tucson, the flour, the apron,\nthe wooden stool — nothing was wasted. And the chorus landed on her line,\nexactly where it was asked to.</p>\n  <p>Same app. Same day. Sixty seconds more typing.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Go write the strong one</a>\n  </p>\n  <p>— Rudy</p>\n\n  <p style=\"font-size:14px;color:#666;border-top:1px solid #e6e0d4;padding-top:14px;margin-top:26px\">Both songs are in <a href=\"https://songghost.com/the-prompt-book.pdf\">the book</a> in full, with the four things that actually changed.</p>\n</div>",
    "text": "Hey {{contact.first_name}},\n\nI did not want to just tell you this works. So I ran both prompts through\nSongGhost for real, on the same day, with the same settings. The only thing I\nchanged was the words in the box.\n\nThe weak one: a song about my grandma\n\nIt came back called \"Grandma's Song.\"\n\nYou always kept the porch light on\nWaiting up for me to come home\nWith cookies warm and open arms\nA little laugh, your favorite song\n\nThat is not bad writing. It is just not about anyone. Porch light, cookies,\nopen arms — every line could belong to any grandmother who ever lived.\n\nThe strong one named her, put her in a kitchen in Tucson, and\ngave me one line she always said.\n\nIt came back called \"Use Your Hands.\"\n\nSunday morning, Tucson sun\nGrandma Rosa in the kitchen, flour on her thumbs\nApron tied, she smiles at me\n\"Mi niña, let's make memories\"\n\nThe title came out of the detail, not the topic. Tucson, the flour, the apron,\nthe wooden stool — nothing was wasted. And the chorus landed on her line,\nexactly where it was asked to.\n\nSame app. Same day. Sixty seconds more typing.\n\nGo write the strong one: https://songghost.com/app\n\n— Rudy\n\nP.S. Both songs are in the book in full, with the four things that actually changed."
  },
  {
    "n": 6,
    "day": 14,
    "subject": "Nobody can hear their own song properly",
    "preview": "Including me. Especially at 2am.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>You cannot hear your own song. Nobody can.</p>\n  <p>You know what you meant, so you hear what you meant. Somebody who has never\nmet you hears only what is actually there. That gap is where every fixable\nproblem lives, and you will not find it by listening harder on your own.</p>\n  <p>So there is a group for it. Real people, real ears, and nobody there is\nprecious about it. You post the song, you ask what is not landing, and\nsomebody tells you the one thing you could not hear yourself.</p>\n  <p>It is the fastest way I know to get better.</p>\n  <p>One more thing, and I am not going to bury it: members of that group get\n<strong>100 song credits a month instead of 25</strong>, plus a standing\ndiscount on anything you buy. So it is genuinely the cheapest way to use\nSongGhost properly, and you get told the truth about your songs while you are\nat it.</p>\n  <p>Post the one you have been sitting on.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://www.facebook.com/groups/1059552496761019\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Join the Music Review group</a>\n  </p>\n  <p>— Rudy</p>\n\n</div>",
    "text": "Hey {{contact.first_name}},\n\nYou cannot hear your own song. Nobody can.\n\nYou know what you meant, so you hear what you meant. Somebody who has never\nmet you hears only what is actually there. That gap is where every fixable\nproblem lives, and you will not find it by listening harder on your own.\n\nSo there is a group for it. Real people, real ears, and nobody there is\nprecious about it. You post the song, you ask what is not landing, and\nsomebody tells you the one thing you could not hear yourself.\n\nIt is the fastest way I know to get better.\n\nOne more thing, and I am not going to bury it: members of that group get\n100 song credits a month instead of 25, plus a standing\ndiscount on anything you buy. So it is genuinely the cheapest way to use\nSongGhost properly, and you get told the truth about your songs while you are\nat it.\n\nPost the one you have been sitting on.\n\nJoin the Music Review group: https://www.facebook.com/groups/1059552496761019\n\n— Rudy"
  },
  {
    "n": 7,
    "day": 18,
    "subject": "It's fine. Just… fine.",
    "preview": "It's almost always the ending.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>Sometimes a song comes back and there is nothing wrong with it. It is just\nfine. You cannot point at the problem, and you never play it again.</p>\n  <p>It is almost always the ending.</p>\n  <p>Some songs stop. Good songs land. A song can be perfectly decent the whole way\nthrough and still feel forgettable if the last line simply runs out of road.</p>\n  <p>The fix is to tell me where to land.</p>\n  <p><em>End on the porch light.</em><br>\n<em>Last line should be her name.</em><br>\n<em>Finish on the thing he said in the car.</em></p>\n  <p>Give the ending a target and the whole song tightens up behind it — because\nnow every verse is walking somewhere instead of just walking.</p>\n  <p>Take the \"fine\" one. The one you were mildly disappointed by. Same prompt, one\nextra sentence telling me where to land. That is usually the entire fix.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Give it a landing</a>\n  </p>\n  <p>— Rudy</p>\n\n  <p style=\"font-size:14px;color:#666;border-top:1px solid #e6e0d4;padding-top:14px;margin-top:26px\">Six things that go wrong and the exact fix for each are in <a href=\"https://songghost.com/the-prompt-book.pdf\">chapter six</a>.</p>\n</div>",
    "text": "Hey {{contact.first_name}},\n\nSometimes a song comes back and there is nothing wrong with it. It is just\nfine. You cannot point at the problem, and you never play it again.\n\nIt is almost always the ending.\n\nSome songs stop. Good songs land. A song can be perfectly decent the whole way\nthrough and still feel forgettable if the last line simply runs out of road.\n\nThe fix is to tell me where to land.\n\nEnd on the porch light.\nLast line should be her name.\nFinish on the thing he said in the car.\n\nGive the ending a target and the whole song tightens up behind it — because\nnow every verse is walking somewhere instead of just walking.\n\nTake the \"fine\" one. The one you were mildly disappointed by. Same prompt, one\nextra sentence telling me where to land. That is usually the entire fix.\n\nGive it a landing: https://songghost.com/app\n\n— Rudy\n\nP.S. Six things that go wrong and the exact fix for each are in chapter six."
  },
  {
    "n": 8,
    "day": 22,
    "subject": "What 25 credits actually buys you",
    "preview": "An honest note about the free plan.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>Let me be straight with you about the free plan, because I would rather you\nhear it from me than hit the wall mid-song.</p>\n  <p>A free account gets <strong>25 credits a month</strong>, and holds 25 songs.\nCredits are what lyrics, revisions and cover art cost. That is a real amount —\nenough to find out whether any of this is for you.</p>\n  <p>Here is the part worth knowing.</p>\n  <p>The first version of a song is almost never the good one. The good one is\nusually the third: you read it back, you notice the chorus is summarising\ninstead of saying something, you change one line in the prompt, you run it\nagain. That loop is where songs actually get good. And that loop costs\ncredits.</p>\n  <p>So the thing 25 credits really limits is not how many songs you start. It is\nhow many you get to <em>finish</em>.</p>\n  <p>If you have hit that wall, that is what the paid plan is for. And if you would\nrather not pay yet, join the group — members get 100 a month, which is enough\nto run that loop properly.</p>\n  <p>Either way, do not let a half-finished song sit there because you ran out.</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">See the plans</a>\n  </p>\n  <p>— Rudy</p>\n\n  <p style=\"font-size:14px;color:#666;border-top:1px solid #e6e0d4;padding-top:14px;margin-top:26px\">The group is free: <a href=\"https://www.facebook.com/groups/1059552496761019\">Music Review group</a>.</p>\n</div>",
    "text": "Hey {{contact.first_name}},\n\nLet me be straight with you about the free plan, because I would rather you\nhear it from me than hit the wall mid-song.\n\nA free account gets 25 credits a month, and holds 25 songs.\nCredits are what lyrics, revisions and cover art cost. That is a real amount —\nenough to find out whether any of this is for you.\n\nHere is the part worth knowing.\n\nThe first version of a song is almost never the good one. The good one is\nusually the third: you read it back, you notice the chorus is summarising\ninstead of saying something, you change one line in the prompt, you run it\nagain. That loop is where songs actually get good. And that loop costs\ncredits.\n\nSo the thing 25 credits really limits is not how many songs you start. It is\nhow many you get to finish.\n\nIf you have hit that wall, that is what the paid plan is for. And if you would\nrather not pay yet, join the group — members get 100 a month, which is enough\nto run that loop properly.\n\nEither way, do not let a half-finished song sit there because you ran out.\n\nSee the plans: https://songghost.com/app\n\n— Rudy\n\nP.S. The group is free: Music Review group."
  },
  {
    "n": 9,
    "day": 26,
    "subject": "The one you haven't written yet",
    "preview": "Last note from me.",
    "html": "<div style=\"font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;font-size:16px;line-height:1.65;color:#1a1a1a;max-width:560px\">\n  <p>Hey {{contact.first_name}},</p>\n  <p>This is the last one from me for a while.</p>\n  <p>There is a song you have not written. You know the one. It is about someone\nspecific, and you have been circling it since before you found the book —\nbecause it matters, and the ones that matter are the ones you are most afraid\nof getting wrong.</p>\n  <p>You have everything you need now.</p>\n  <p>You know to hand me one true thing. You know to say who is talking and who\nthey are talking to. You know to pick the room instead of letting me pick it.\nYou know to tell me where to land.</p>\n  <p>That is the whole method. The rest is just doing it.</p>\n  <p>So do that one. Not the easy one — the one you have been putting off. Give me\nthe name, the room, the strange object, and the line you want it to end on.\nThen read what comes back.</p>\n  <p>It will not be perfect on the first pass. Run it again. That is the job.</p>\n  <p>I will be here.</p>\n  <p>— Rudy</p>\n\n  <p style=\"margin:26px 0\">\n    <a href=\"https://songghost.com/app\" style=\"display:inline-block;background:#2b5be0;color:#ffffff;text-decoration:none;padding:13px 24px;border-radius:999px;font-weight:700\">Go finish it</a>\n  </p>\n\n  <p style=\"font-size:14px;color:#666;border-top:1px solid #e6e0d4;padding-top:14px;margin-top:26px\">Everything in one place: <a href=\"https://songghost.com/app\">the web app</a>, <a href=\"https://apps.apple.com/us/app/id6789995320\">the iPhone app</a>, and <a href=\"https://www.facebook.com/groups/1059552496761019\">the group</a>.</p>\n</div>",
    "text": "Hey {{contact.first_name}},\n\nThis is the last one from me for a while.\n\nThere is a song you have not written. You know the one. It is about someone\nspecific, and you have been circling it since before you found the book —\nbecause it matters, and the ones that matter are the ones you are most afraid\nof getting wrong.\n\nYou have everything you need now.\n\nYou know to hand me one true thing. You know to say who is talking and who\nthey are talking to. You know to pick the room instead of letting me pick it.\nYou know to tell me where to land.\n\nThat is the whole method. The rest is just doing it.\n\nSo do that one. Not the easy one — the one you have been putting off. Give me\nthe name, the room, the strange object, and the line you want it to end on.\nThen read what comes back.\n\nIt will not be perfect on the first pass. Run it again. That is the job.\n\nI will be here.\n\n— Rudy\n\nGo finish it: https://songghost.com/app\n\nP.S. Everything in one place: the web app, the iPhone app, and the group."
  }
];

export const LAST_DAY = NURTURE_EMAILS[NURTURE_EMAILS.length - 1].day;

