import type { GenreGuide } from './types';

export const AFROBEATS_GUIDE: GenreGuide = {
  id: 'afrobeats',
  name: 'Afrobeats',
  language: 'English',

  sonicPalette: {
    overview: 'Vibrant, percussive, and irresistibly danceable. Afrobeats blends West African rhythmic traditions with global pop, hip-hop, and electronic influences. The sound is bright, warm, and body-moving — defined by layered percussion, infectious melodies, and log drum patterns.',
    timbre: [
      'Log drum (shaker-like percussive synth)',
      'Bright, layered percussion (shekere, congas, djembe)',
      'Warm synth pads and leads',
      'Clean electric guitar with palm muting',
      'Sub-bass or 808 bass',
      'Vocal harmonies and chants',
      'Steel drums and kalimba',
      'Brass stabs (trumpets, horns)',
    ],
    texture: 'Layered percussion creates a dense rhythmic bed while melodic elements float above. The mix is bright and percussive with warm low end. Multiple rhythmic patterns interlock to create the groove.',
    tonality: 'Major and minor keys with warm, bright tonality. Pentatonic melodies common. Some use of jazz-influenced extended chords. Bright, airy high end with warm bass.',
    signatureSounds: [
      'Log drum pattern (signature Afrobeats percussion)',
      'Shekere and percussion layers',
      'Guitar riffs with palm muting',
      'Call-and-response vocal patterns',
      'Brass stabs',
      'Talking drum accents',
      'Kalimba melodies',
    ],
  },

  rhythmAndGroove: {
    overview: 'The groove is the soul of Afrobeats — layered polyrhythmic patterns create an irresistible dance pulse. The rhythm draws from traditional West African patterns, adapted for contemporary pop consumption.',
    bpmRange: { min: 95, max: 120, sweet: 108 },
    feel: 'Bouncy, infectious, and body-moving. The groove should make you move involuntarily. Even mid-tempo Afrobeats has an undeniable physical pull.',
    swing: 'Inherent in the polyrhythmic layering — not swing in the jazz sense, but the interlocking of multiple rhythmic patterns creates a swinging, grooving feel.',
    syncopation: 'Heavy — Afrobeats is built on syncopation. The log drum pattern, guitar riffs, and vocal melodies all play off-beat patterns against the basic pulse.',
    grooveArchetype: 'Afrobeats bounce, Amapiano log drum, or highlife two-feel',
    rhythmicSignatures: [
      'Log drum pattern (syncopated percussion loop)',
      'Layered percussion (shekere, congas, hi-hats)',
      'Kick on beats 1 and 3 with syncopated snare',
      'Guitar palm-muted off-beat strumming',
      'Dancehall-influenced rhythm patterns',
      'Polyrhythmic interlocking patterns',
      'Clave-based patterns (3+2 or 2+3)',
    ],
  },

  harmonicLanguage: {
    overview: 'Simple but effective — Afrobeats harmony serves the groove and melody. Chord progressions are typically short loops (2-4 chords) that create a hypnotic foundation for melodic and rhythmic invention.',
    scales: ['Major', 'Minor', 'Pentatonic Major', 'Pentatonic Minor', 'Dorian'],
    chordProgressions: [
      'I – IV – V – I (basic Afrobeats)',
      'i – iv – bVII – bIII (minor loop)',
      'I – vi – IV – V (pop-Afrobeats)',
      'I – V – vi – IV',
      'i – bVI – bVII – i (minor ascension)',
      'Two-chord vamp (I – IV or i – iv)',
    ],
    harmonyNotes: 'Short chord loops repeated throughout. Guitar and keys provide harmonic color. Bass follows root movement. Extended chords occasional for sophistication. Simplicity serves the groove.',
    modality: 'Mix of major and minor. Major for celebratory tracks. Minor for more emotional or atmospheric songs. Pentatonic melodies are universal.',
  },

  songStructure: {
    overview: 'Groove-centered — Afrobeats songs establish the rhythm early and maintain it throughout. Structure serves the dance rather than dramatic narrative. Repetition creates hypnotic engagement.',
    form: 'Intro – Verse – Chorus/Hook – Verse – Chorus – Bridge/Breakdown – Chorus – Outro',
    sections: ['Intro (percussion build)', 'Verse 1', 'Chorus/Hook', 'Verse 2', 'Chorus', 'Bridge/Breakdown', 'Final Chorus', 'Outro'],
    arrangement: 'Percussive intro establishes the groove. Verses and choruses build on the rhythmic foundation. Breakdowns strip back for contrast. The groove never fully stops.',
    introOutro: 'Intros: percussion build, log drum pattern, or guitar riff establishing the groove. Outros: groove riding out, vocal ad-libs, or percussion fade.',
    barLengths: 'Verses: 8-16 bars. Chorus: 8 bars. Bridge: 4-8 bars. Total: 3-4 minutes.',
    hookPlacement: 'Chorus is the hook — infectious, singable, often in pidgin English or local language. The groove itself serves as a rhythmic hook. Vocal hooks are short and repetitive.',
  },

  vocalDelivery: {
    overview: 'Melodic, rhythmic, and emotionally expressive. Afrobeats vocals blend singing with toasting (rhythmic speaking), creating a unique delivery that sits between melody and rap. Nigerian Pidgin, Yoruba, and English blend naturally.',
    phrasing: 'Rhythmically intricate — vocal phrases interlock with the percussion patterns. Melodies are catchy and repetitive. Phrasing switches between singing and toasting mid-verse.',
    affect: 'Confident, celebratory, and expressive. Joy, love, and swagger are primary emotions. Vocal delivery conveys personality and charisma.',
    techniques: [
      'Melodic singing over percussion-heavy beats',
      'Toasting (rhythmic speaking/chanting)',
      'Call-and-response with backing vocals',
      'Pidgin English and local language mixing',
      'Vocal ad-libs and chants',
      'Falsetto for melodic peaks',
      'Talk-singing (patois-influenced)',
      'Layered vocal harmonies',
    ],
    adlibStyle: 'Essential — "eh!", "oh baby!", chants, vocal interjections, producer tags. Background vocal chants reinforce the rhythm. Vocal percussion sounds.',
    harmony: 'Background vocal harmonies support the lead. Chanted unison vocals. Call-and-response between lead and backing. Group vocal hooks.',
    grit: 'Minimal — Afrobeats vocals are generally clean and melodic. Some rasp for emphasis. The focus is on melody and rhythm, not roughness.',
  },

  lyricalConventions: {
    overview: 'Multilingual, celebratory, and lifestyle-focused. Afrobeats lyrics blend English, Pidgin, and local languages (Yoruba, Igbo, Twi) to tell stories of love, celebration, and African pride.',
    themes: [
      'Love and romance',
      'Celebration and partying',
      'African pride and identity',
      'Wealth and success',
      'Dance and movement',
      'Beautiful women',
      'Hustle and ambition',
      'Joy and gratitude',
    ],
    perspective: 'First person — personal expression of love, desire, celebration. Direct address to love interest. Celebratory communal "we."',
    figurativeLanguage: 'Direct and vivid. Dance as metaphor for attraction. Fire and heat for passion. Biblical and spiritual references. Cultural proverbs.',
    vocabulary: 'Multilingual — English, Pidgin English, Yoruba, Igbo, Twi, and other West African languages. Brand names and lifestyle references. Slang from Lagos, Accra, London.',
    storytellingApproach: 'Vibe-driven rather than narrative. Each verse explores a theme (love, partying, ambition) rather than telling a sequential story. The chorus is a universal statement.',
    cliches: [
      'My African queen/king',
      'Shaku shaku / zanku (dance references)',
      'No wahala (no worries)',
      'Body/waist/dance references',
      'Jollof and cultural food references',
      'Lagos/Accra city life',
    ],
  },

  productionFingerprint: {
    overview: 'Percussion-forward, bright, and danceable. Afrobeats production centers the groove — layered percussion patterns, infectious melodies, and clean mix aesthetics create music designed for global dance floors.',
    mixAesthetic: 'Bright and percussive. Log drum and percussion prominent. Vocals clear and present. Sub-bass controlled but felt. Clean, modern production with warm tonality.',
    era: 'Current era: global crossover (Wizkid, Burna Boy on international charts), genre fusion with pop/R&B/dancehall, Amapiano influence, streaming-driven.',
    signalChain: 'Beats: FL Studio or Logic → log drum samples → layered percussion → synth pads/leads → 808 bass → sidechain. Vocals: condenser mic → compression → EQ → delay/reverb sends.',
    modernTrends: 'Amapiano crossover. Afro-fusion with R&B and pop. UK Afroswing influence. Latin-Afrobeats fusion. Global streaming success. Increasingly sophisticated production.',
  },

  instrumentation: {
    coreInstruments: [
      'Log drum (synth percussion)',
      'Layered percussion (shekere, congas, djembe)',
      'Synth pads and leads',
      'Electric guitar (clean, palm-muted)',
      'Bass (808 or synth)',
      'Brass (horn stabs)',
      'Kalimba',
      'Programmed drums',
    ],
    signatureSounds: [
      'Log drum pattern',
      'Shekere rhythms',
      'Palm-muted guitar riffs',
      'Brass stabs',
      'Talking drum accents',
      'Kalimba melodies',
      'Vocal chant hooks',
    ],
    layering: 'Percussion is heavily layered — multiple rhythmic patterns interlock. Melodic elements are simpler. The groove is the priority. Don\'t overcrowd the mid-range.',
    avoidInstruments: [
      'Heavy distorted guitars',
      'Aggressive electronic sounds',
      'Classical orchestral arrangements',
      'Country instruments',
      'Harsh synths',
    ],
  },

  culturalContext: {
    overview: 'Afrobeats is the sound of modern Africa — a global cultural force representing African creativity, pride, and joy. Born in Nigeria and Ghana, it has become one of the most streamed genres worldwide.',
    origin: 'Nigeria (Lagos) and Ghana (Accra), emerging from the fusion of highlife, juju music, and hip-hop/R&B in the 2000s-2010s. Distinct from Fela Kuti\'s "Afrobeat" (one word, different genre).',
    identity: 'African pride, modern African identity, and global African diaspora connection. Afrobeats represents a new generation of African artists conquering the global music industry.',
    community: 'Pan-African and diasporic — connecting Africans worldwide. Lagos and Accra as creative hubs. London and Toronto as diaspora centers. Social media and streaming as distribution channels.',
    socialFunction: 'Celebration, dance, and cultural pride. Afrobeats is the soundtrack to parties, weddings, and gatherings across Africa and the diaspora. It brings people together through rhythm.',
    authenticityMarkers: [
      'African musical roots and rhythm patterns',
      'Multilingual lyrics (Pidgin, Yoruba, etc.)',
      'Connection to West African culture',
      'Danceable grooves',
      'Cultural pride without stereotyping',
      'Production quality matching global standards',
    ],
  },

  historicalLineage: {
    overview: 'From highlife and juju through Fela\'s Afrobeat to modern Afrobeats, the music represents Africa\'s evolving musical conversation with the world.',
    roots: ['Highlife', 'Juju Music', 'Fela Kuti\'s Afrobeat', 'Hip-Hop', 'R&B', 'Dancehall'],
    evolution: 'Highlife and juju (1950s-80s) → Fela\'s Afrobeat (1970s-80s) → Nigerian pop and hip-hop (1990s-2000s) → Afrobeats emergence (2010s) → Global domination (2020s).',
    keyEras: [
      '1950s-1970s: Highlife golden era',
      '1970s-1980s: Fela Kuti\'s Afrobeat revolution',
      '2000s: Nigerian hip-hop and pop foundation',
      '2010s: Afrobeats crystallizes (Wizkid, Davido, Burna Boy)',
      '2020s: Global mainstream crossover',
    ],
    influencedBy: ['Highlife', 'Juju', 'Afrobeat (Fela)', 'Hip-Hop', 'R&B', 'Dancehall', 'UK Grime'],
    influenced: ['Pop', 'R&B', 'Dancehall', 'Latin Music', 'UK Music', 'Global Pop'],
  },

  subGenres: [
    {
      name: 'Afro-Pop',
      description: 'Pop-accessible Afrobeats with mainstream appeal. Catchy melodies, polished production, and universal themes.',
      distinguishingFeatures: ['Pop accessibility', 'Catchy, radio-friendly hooks', 'Polished production', 'Global appeal', 'English-dominant lyrics'],
      bpmRange: { min: 100, max: 120 },
      keyArtists: ['Wizkid', 'Davido', 'Tiwa Savage', 'Yemi Alade', 'CKay'],
      productionNotes: 'Pop-level polish with Afrobeats groove. Catchy melodies. Clean production. Radio-ready mix.',
      lyricNotes: 'Love, celebration, lifestyle. Accessible, universal themes. More English, less Pidgin.',
      sunoPromptKeywords: ['Afro-pop', 'African pop', 'mainstream Afrobeats', 'catchy', 'radio-friendly', 'danceable'],
    },
    {
      name: 'Afro-Fusion',
      description: 'Genre-blending Afrobeats incorporating reggae, R&B, hip-hop, and rock elements. Artistic and experimental.',
      distinguishingFeatures: ['Genre-blending approach', 'Artistic ambition', 'Diverse influences', 'Burna Boy coined the term', 'Album-oriented artistry'],
      bpmRange: { min: 90, max: 125 },
      keyArtists: ['Burna Boy', 'Mr Eazi', 'Tems', 'Rema'],
      productionNotes: 'Blend Afrobeats rhythms with reggae, R&B, hip-hop, or rock elements. Genre-fluid production. Artistic experimentation.',
      lyricNotes: 'Deeper themes — African identity, social commentary, personal growth. More lyrical depth than standard Afro-pop.',
      sunoPromptKeywords: ['Afro-fusion', 'genre-blending African', 'Burna Boy style', 'eclectic Afrobeats', 'fusion'],
    },
    {
      name: 'Amapiano',
      description: 'South African house music fusion characterized by log drums, jazz-influenced piano, and deep bass. Has become a global phenomenon blending with Afrobeats.',
      distinguishingFeatures: ['Log drum patterns', 'Jazz-influenced piano melodies', 'Deep, bouncing bass', 'South African origin', 'Percussive and melodic'],
      bpmRange: { min: 110, max: 120 },
      keyArtists: ['Kabza De Small', 'DJ Maphorisa', 'Uncle Waffles', 'Focalistic', 'DBN Gogo'],
      productionNotes: 'Log drum is essential. Jazz-influenced piano. Deep, round bass. Layered percussion. South African production aesthetic.',
      lyricNotes: 'Zulu, Xhosa, or English lyrics. Dance-focused. Celebratory. Can be instrumental.',
      sunoPromptKeywords: ['Amapiano', 'South African house', 'log drum', 'piano house', 'deep house African', 'bouncy'],
    },
    {
      name: 'Alte',
      description: 'Alternative African music — experimental, genre-fluid, and artistically independent. Lagos\'s answer to indie culture.',
      distinguishingFeatures: ['Experimental and genre-fluid', 'Alternative aesthetic', 'DIY ethos', 'Anti-mainstream', 'Artistic independence'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Santi', 'Odunsi (The Engine)', 'Lady Donli', 'Amaarae'],
      productionNotes: 'Experimental production. Genre-blending (indie, R&B, electronic, Afrobeats). Lo-fi or polished. Artistic freedom.',
      lyricNotes: 'Personal, introspective, alternative. Identity, relationships, Lagos life. More poetic than mainstream.',
      sunoPromptKeywords: ['Alte', 'alternative African', 'Lagos indie', 'experimental Afrobeats', 'art Afrobeats'],
    },
    {
      name: 'Afro-Swing',
      description: 'UK-bred fusion of Afrobeats with grime, dancehall, and UK rap. The sound of British-African diaspora youth.',
      distinguishingFeatures: ['UK production aesthetic', 'Afrobeats meets grime/dancehall', 'British-African diaspora', 'London slang and culture', 'Uptempo energy'],
      bpmRange: { min: 95, max: 115 },
      keyArtists: ['J Hus', 'NSG', 'Kojo Funds', 'Yxng Bane', 'Not3s'],
      productionNotes: 'UK production values with Afrobeats rhythms. Grime and dancehall influence. London energy. Clean, commercial production.',
      lyricNotes: 'London life, love, hustle. UK slang with African references. Multilingual. British-African identity.',
      sunoPromptKeywords: ['Afro-swing', 'UK Afrobeats', 'British African', 'London Afrobeats', 'Afro-bashment'],
    },
    {
      name: 'Highlife-Influenced Afrobeats',
      description: 'Afrobeats drawing heavily from Ghanaian highlife tradition. Guitar-driven melodies, brass sections, and jazzy harmonies.',
      distinguishingFeatures: ['Highlife guitar melodies', 'Brass section', 'Jazzy harmonies', 'Ghanaian influence', 'Melodic focus'],
      bpmRange: { min: 95, max: 115 },
      keyArtists: ['Sarkodie', 'Shatta Wale', 'Stonebwoy', 'King Promise', 'KiDi'],
      productionNotes: 'Highlife guitar patterns. Brass stabs. More melodic than percussive. Ghanaian production aesthetic. Warm, melodic mix.',
      lyricNotes: 'Twi, Pidgin, and English mix. Love, celebration, Ghanaian culture. Highlife storytelling influence.',
      sunoPromptKeywords: ['highlife', 'Ghanaian Afrobeats', 'Afro-highlife', 'guitar-driven', 'melodic African'],
    },
    {
      name: 'Dancehall-Afrobeats',
      description: 'Fusion of Caribbean dancehall rhythms with Afrobeats production and melodies.',
      distinguishingFeatures: ['Dancehall rhythm influence', 'Caribbean-African fusion', 'Patois and Pidgin mix', 'High energy', 'Dance-oriented'],
      bpmRange: { min: 95, max: 115 },
      keyArtists: ['Patoranking', 'Timaya', 'Burna Boy (dancehall tracks)', 'Shenseea x African artists'],
      productionNotes: 'Blend dancehall riddim patterns with Afrobeats percussion. Caribbean-influenced bass. High energy production.',
      lyricNotes: 'Patois-Pidgin mix. Party, dance, romance. Caribbean-African cultural blend.',
      sunoPromptKeywords: ['Afro-dancehall', 'Caribbean Afrobeats', 'dancehall fusion', 'tropical Afro', 'island vibes'],
    },
    {
      name: 'Afro-House',
      description: 'Deep house and electronic dance music fused with African rhythmic patterns and vocals.',
      distinguishingFeatures: ['House four-on-the-floor with African percussion', 'Deep, driving bass', 'African vocal chants', 'Club-oriented', 'Electronic production with organic African elements'],
      bpmRange: { min: 118, max: 128 },
      keyArtists: ['Black Coffee', 'Culoe De Song', 'Da Capo', 'Shimza'],
      productionNotes: 'Deep house production with African percussion layers. Four-on-the-floor with African rhythmic overlay. Warm, deep bass. Atmospheric.',
      lyricNotes: 'Often instrumental or with vocal chants. When lyrics: spiritual, uplifting, communal. Zulu, Xhosa, or English.',
      sunoPromptKeywords: ['Afro-house', 'African house', 'deep house African', 'tribal house', 'South African house'],
    },
    {
      name: 'Nigerian Afrobeats',
      description: 'The core Lagos sound — the original and most commercially successful strain of Afrobeats.',
      distinguishingFeatures: ['Lagos-centered sound', 'Pidgin English and Yoruba', 'Commercial appeal', 'Log drum and percussion focus', 'Naija swagger'],
      bpmRange: { min: 100, max: 118 },
      keyArtists: ['Wizkid', 'Davido', 'Burna Boy', 'Asake', 'Fireboy DML'],
      productionNotes: 'The definitive Afrobeats sound. Log drum, percussion layers, clean guitar, synth pads. Lagos production style.',
      lyricNotes: 'Pidgin English, Yoruba, English mix. Love, party, hustle, swagger. Lagos lifestyle.',
      sunoPromptKeywords: ['Naija', 'Nigerian Afrobeats', 'Lagos sound', 'Wizkid type', 'Pidgin', 'West African pop'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Afrobeats has gone global — the audience spans the African continent, diaspora communities worldwide, and increasingly mainstream global listeners. The culture values joy, dance, and African pride.',
    fanExpectations: [
      'Infectious, danceable grooves',
      'Catchy melodic hooks',
      'Cultural authenticity',
      'High production quality',
      'Visual style and fashion',
      'Consistent release schedule',
    ],
    gatekeeping: 'Low — Afrobeats is welcoming and celebratory. Some debates about Western co-optation. Discussion about what counts as Afrobeats vs. Afro-pop. Genre name debates.',
    livePerformance: 'High-energy dance performances. Festival appearances growing globally. Club DJ sets. The audience dances — Afrobeats is body-moving music. Stage presence and charisma essential.',
    fashionAndAesthetic: 'Stylish, bold, and culturally proud. African fashion mixed with global luxury brands. Colorful, expressive, confident. Visual identity matters.',
    crossoverPotential: 'Maximum and accelerating — Afrobeats is penetrating mainstream pop globally. Collaborations with major pop and R&B artists. Grammy recognition. The genre is in its global ascendancy.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Afrobeats micro-timing is polyrhythmic at its core — multiple time signatures interlock to create patterns that don\'t map cleanly to Western quantization grids. This is the "African timing" concept: a feel born from layered cyclic patterns.',
    quantizationDeviation: 'Significant but structured. Each percussion layer follows its own internal logic, creating composite grooves that sound loose against a grid but are precisely interlocked with one another. The log drum pattern sits slightly off the downbeat, creating the signature bounce.',
    aheadBehindBeat: 'The shekere and hi-hat patterns often sit slightly ahead of the grid, pulling the track forward, while the kick and bass sit squarely or fractionally behind, creating a push-pull that makes the groove irresistible to the body.',
    humanizationMarkers: [
      'Log drum hits that land between grid points, creating the signature Afrobeats bounce',
      'Percussion layers that follow cyclic patterns independent of the main pulse',
      'Guitar palm-mute strums with micro-variations in attack and release',
      'Vocal delivery that weaves between rhythmic patterns rather than sitting on them',
      'Hi-hat patterns with velocity swells that breathe against the kick pattern',
    ],
    genreSpecificFeel: 'The Afrobeats feel emerges from the composite of individually simple patterns — each layer is straightforward, but their intersection creates a polyrhythmic web that feels buoyant and rolling. Quantizing any single layer to a grid collapses the entire groove.',
  },

  silenceAndSpace: {
    overview: 'Space between percussion hits is what creates the Afrobeats dance groove — the gaps between the log drum, shekere, and kick patterns are as choreographed as the hits themselves.',
    negativeSpaceRole: 'Essential for danceability. The spaces between percussion layers are where the body responds — each gap is an invitation to move. Overfilling the rhythmic grid destroys the bounce.',
    breathingPatterns: 'The groove breathes through the alternation of dense percussion sections and stripped-back vocal passages. Breakdowns that reduce to just log drum and voice create anticipation for the full groove\'s return.',
    dynamicContrast: 'Moderate — Afrobeats maintains a consistent energy level for the dance floor, but contrast comes from layering percussion in and out. A breakdown to just bass and log drum before the full beat drops creates physical impact.',
    whatIsDeliberatelyAbsent: [
      'Constant kick drum — the kick is placed sparingly, letting the log drum carry rhythmic weight',
      'Filled-in hi-hat patterns — the gaps between hi-hat hits create the bounce',
      'Heavy sub-bass between beats — bass is felt on the pulse, not between',
      'Wall-of-sound production — Afrobeats keeps the mid-range open for vocal clarity',
      'Sustained pad drones — harmonic elements are rhythmic stabs, not washes',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response is the structural backbone of Afrobeats, rooted in West African communal music-making where the boundary between performer and audience dissolves into shared rhythm.',
    vocalInstrumentalDialogue: 'The lead vocal calls and the percussion answers — vocal phrases are structured around the log drum pattern, with melodic lines landing in the spaces between percussion hits. The guitar riff often serves as an instrumental response to vocal phrases.',
    sectionInternal: 'Within the percussion section, call-and-response operates continuously — the shekere calls, the conga answers; the log drum states a pattern, the hi-hat responds with a complementary rhythm. Each layer is in dialogue with every other.',
    audienceParticipation: 'Designed into the music — chorus hooks are simple enough for crowd singing, and the dance groove demands physical participation. The chanted vocal hooks ("eh!", "oh!") are crowd-ready from conception.',
    patterns: [
      'Lead vocal phrase followed by group vocal chant response',
      'Percussion pattern stated by log drum, answered by shekere and hi-hat layers',
      'Verse-chorus as macro call-and-response — verse calls, chorus is communal answer',
      'Ad-lib vocal interjections that prompt audience echo in live settings',
      'Guitar riff responding to vocal melody in alternating phrases',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Afrobeats is defined by its multilingual fluidity — Nigerian Pidgin English, Yoruba, Igbo, and standard English code-switch within single verses, reflecting the linguistic reality of Lagos street life and pan-African identity.',
    phoneticMarkers: [
      'Nigerian Pidgin vowel elongation ("wey" for "which/that," "dey" for continuous tense)',
      'Yoruba tonal inflections carried into English phrases, creating melodic speech patterns',
      'Igbo consonant clusters and nasal vowels appearing in ad-libs and song titles',
      'Ghanaian Twi phrasing in Accra-originated Afrobeats productions',
      'London MLE (Multicultural London English) inflections in UK Afroswing',
    ],
    accentInfluence: 'The musicality of Yoruba as a tonal language directly shapes Afrobeats melody — vocal melodies often follow the natural tonal contours of Yoruba words, meaning the language itself generates the tune.',
    dialectVocabulary: [
      '"No wahala" — no problem/no trouble, ubiquitous expression of ease',
      '"Omo" — child/person, used as an exclamation of surprise or emphasis',
      '"Sapa" — financial struggle, broke (Lagos slang)',
      '"Japa" — to flee/emigrate, reflecting contemporary Nigerian diaspora discourse',
      '"E choke" — it\'s overwhelming/impressive, Davido-popularized exclamation',
    ],
    regionWithinCulture: 'Lagos (Mainland vs. Island divide reflecting class), Accra (highlife-rooted Ghanaian strain), London (diaspora Afroswing hybrid), Toronto (Caribbean-African fusion scene). Each city produces a distinct Afrobeats accent.',
  },

  performancePractice: {
    overview: 'In Afrobeats, the body IS the instrument — dance is inseparable from the music. Performance is a full-body experience where choreography, vocal delivery, and crowd energy form a unified expression.',
    improvisationConventions: 'Minimal instrumental improvisation — the groove is composed and replicated. Improvisation exists in vocal ad-libs, dance freestyle sections, and the energy exchange between performer and crowd. DJ set transitions are a form of improvisational art.',
    crowdInteraction: 'Constant and physical — call-and-response chants, instructing dance moves ("put your hands up," "wine your waist"), and gauging energy to decide which songs to extend or cut. The performer reads the dance floor like a conductor.',
    stagePresence: 'High-energy movement is mandatory. Afrobeats artists dance while performing — choreographed routines and freestyle movement are equally valued. Stationary performance reads as disengaged. Fashion and visual presentation are extensions of the performance.',
    livVsRecordedDifferences: 'Live performances extend songs with crowd interaction segments, DJ transitions, and medleys. The recorded version is a blueprint; the live version adds improvised energy, extended breakdowns, and audience-driven dynamics.',
    whatMakesAGoodShow: 'A crowd that never stops dancing, seamless transitions between songs that maintain the energy arc, visible joy from the performer, moments where the entire venue moves as one body, and the sense that the party could go on indefinitely.',
  },

  socioeconomicSubtext: {
    overview: 'Afrobeats carries the aspirational energy of Lagos hustle culture — a music born in a city where creativity and commerce merge out of necessity, reflecting post-colonial Africa\'s reclamation of global cultural power.',
    materialConditions: 'Lagos\'s generator-powered studios and self-funded music videos reflect an entrepreneurial DIY ecosystem. Afrobeats artists often self-finance early careers through side businesses. Streaming revenue and international touring have created new economic models.',
    classIdentity: 'Afrobeats straddles Lagos street culture and Afropolitan cosmopolitanism — lyrics reference both the struggle of Sapa (being broke) and the aspiration of private jets and designer labels. This duality is authentic to Lagos\'s extreme wealth inequality.',
    politicalUndercurrent: 'Post-EndSARS protest energy, references to "japa" (emigration), and pride in African identity despite systemic challenges. Afrobeats rarely engages in direct political commentary but encodes social realities in lifestyle narratives and cultural assertions.',
    implicitReferences: [
      '"Japa" discourse — mass emigration of young Nigerians reflected in lyrics about leaving and staying',
      'Generator culture — the constant hum of independent power supply as metaphor for self-reliance',
      'Afropolitan identity — navigating between African roots and global citizenship',
      'Post-colonial cultural reclamation — African artists dictating terms to Western industry',
      'Lagos-London-Toronto triangle — the diaspora network that distributes both music and economic opportunity',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Afrobeats is deeply self-referential within its own ecosystem while actively absorbing and transforming sounds from highlife, dancehall, hip-hop, and global pop into its rhythmic framework.',
    canonKnowledge: 'Awareness of Fela Kuti\'s Afrobeat (the ancestor genre), highlife guitar patterns, and the foundational Afrobeats tracks of the 2010s (Wizkid\'s "Ojuelegba," Burna Boy\'s "Ye") is expected. Producers reference classic riddim patterns and log drum templates.',
    samplingTradition: 'Direct sampling is less common than in hip-hop — instead, Afrobeats absorbs influences through production style. Highlife guitar patterns are recreated, not sampled. Amapiano log drum sounds are adopted and adapted rather than lifted.',
    quotationPractice: 'Artists reference each other through melodic callbacks, production style homage, and collaborative features rather than literal sampling. A producer using a specific log drum pattern associated with a hit track is a form of quotation.',
    expectedReferences: [
      'Fela Kuti\'s Afrobeat as the ancestral genre — horn patterns and polyrhythmic foundation',
      'Wizkid\'s melodic template established in "Ojuelegba" and "Come Closer"',
      'Burna Boy\'s Afro-fusion expansion of the genre\'s boundaries',
      'Amapiano log drum patterns originating from South African house music',
      'Highlife guitar melodies from the Ghanaian and Nigerian golden eras',
    ],
    lineageSignifiers: [
      'Using a shekere pattern signals connection to traditional West African percussion',
      'Pidgin English lyrics signal Lagos street authenticity',
      'Highlife-style guitar arpeggios signal Ghanaian roots or pan-African awareness',
      'Amapiano log drum integration signals contemporary cross-continental fluency',
      'Dancehall rhythm borrowings signal Caribbean-African diaspora connection',
      'Fela-style horn arrangements signal reverence for the Afrobeat ancestor genre',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Afrobeats performance foregrounds the dancing body as the primary expressive instrument, with dance styles and physical presentation operating as gendered vocabularies that are both codified and increasingly contested.',
    vocalGenderCodes: 'Male artists dominate commercial Afrobeats with melodic singing and toasting styles. Female artists like Tems, Tiwa Savage, and Ayra Starr have carved distinctive vocal spaces — often with softer, more R&B-inflected delivery that contrasts with male bravado without being subordinate to it.',
    physicalityInPerformance: 'Dance is non-negotiable in Afrobeats performance. Specific dance moves become viral trends (Zanku, Legwork, Palliative). The body\'s relationship to the beat — how waist movement, footwork, and shoulder rolls interact with percussion layers — is the genre\'s primary physical language.',
    genderNarratives: 'Male lyrics frequently celebrate women\'s beauty and desirability ("African Queen" trope). Female artists increasingly assert agency, desire, and independence. The "bad girl" and "boss lady" archetypes in female Afrobeats represent evolving gender narratives.',
    subversionExamples: [
      'Tems\'s global breakthrough asserting female artistic authority without conforming to male gaze',
      'Amaarae\'s Alte-influenced Afrobeats exploring fluid gender expression and queer-adjacent aesthetics',
      'Tiwa Savage\'s "49-99" centering working-class women\'s economic struggle',
      'Ayra Starr\'s "Rush" reframing romantic pursuit from a young woman\'s confident perspective',
      'Yemi Alade\'s "Johnny" using humor to critique male infidelity from a woman\'s viewpoint',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Afrobeats at 100-110 BPM feels languid and rolling, not slow — the tempo is calibrated for a specific body movement that would be impossible at faster or slower speeds.',
    psychologicalTempo: 'The perceived tempo of Afrobeats is faster than its BPM suggests because the polyrhythmic layers create multiple simultaneous pulse rates. The log drum pattern divides the beat into sub-pulses that accelerate the felt tempo without increasing the actual BPM.',
    weightAndMomentum: 'Afrobeats has a rolling, circular momentum — not the linear drive of rock or the four-on-the-floor push of house. The groove cycles and loops, creating a sensation of continuous motion rather than forward propulsion.',
    urgencyScale: 'Slow Afrobeats (95 BPM): sensual, waist-winding groove. Sweet spot (105-110 BPM): the ideal Afrobeats bounce, where all body movements synchronize naturally. Fast (115-120 BPM): higher energy, approaching Amapiano territory, footwork-oriented.',
    comparisonToSameBPM: 'A 108 BPM Afrobeats track feels completely different from 108 BPM hip-hop — the Afrobeats version rolls and bounces where the hip-hop version hits and pauses. The polyrhythmic layering makes Afrobeats feel simultaneously relaxed and energized.',
  },

  mistakeConventions: {
    overview: 'Afrobeats production values are high and polished — the genre\'s global ambitions demand radio-ready finish. But the groove must feel human, and overly clinical production strips the dance energy from the music.',
    toleratedImperfections: [
      'Yoruba tonal inflections bending pitch away from Western intervals — the melody follows speech, not the scale',
      'Percussion timing that follows the polyrhythmic feel rather than a click track — log drum slightly off-grid is the bounce',
      'Palm-muted guitar strums with uneven attack from right-hand dampening — the inconsistency drives the groove',
      'Background vocal chants slightly out of unison, creating the communal warmth of a Lagos street chorus',
      'Ad-libs ("omo!", "e choke!") that are slightly off-mic or rough in texture, adding street authenticity',
    ],
    celebratedFlaws: [
      'Wizkid\'s breathy, sometimes pitchy vocal delivery that prioritizes vibe over technique',
      'Lo-fi production on early Afrobeats hits that defined the genre\'s raw energy',
      'Fela Kuti\'s deliberately rough Afrobeat (the ancestor genre) recordings whose raw energy became a production reference for modern Afrobeats',
      'Live percussion recordings with room bleed that ground the electronic production',
      'Vocal takes where emotion overtakes technical control, adding urgency',
    ],
    overproductionRisks: [
      'Over-quantizing percussion layers kills the polyrhythmic interlock that creates the dance groove',
      'Excessive auto-tune removes the tonal qualities that connect Afrobeats vocals to Yoruba speech melody',
      'Too-clean mixes lose the warmth and density that make Afrobeats feel like a communal gathering',
      'Sterile electronic percussion replacing organic shekere and conga textures',
      'Western pop mastering that compresses the dynamic range needed for percussion clarity',
    ],
    authenticRoughness: 'The best Afrobeats production balances global polish with Lagos energy — the mix should feel like a party happening in a room full of people, not a sterile studio exercise. Some grit in the percussion and warmth in the low end signals authenticity.',
  },

  referenceTracks: [
    {
      title: 'Essence',
      artist: 'Wizkid ft. Tems',
      year: 2021,
      whyExemplary: 'The song that broke Afrobeats into the global mainstream. Tems\' verse rewrote the rules for female features — her vocal presence matched and arguably exceeded the lead artist.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Stripped production: log drum, light percussion, bass. Under 4 minutes. Wizkid and Tems trade sections rather than harmonizing.',
      craftHighlight: 'Minimalism as seduction — the production leaves so much space that every vocal inflection becomes magnified. The restraint IS the sensuality.',
    },
    {
      title: 'Love Nwantiti',
      artist: 'CKay',
      year: 2021,
      whyExemplary: 'Most-Shazamed song globally in 2021. The Igbo/English/pidgin code-switching made it a TikTok phenomenon — proved that African-language hooks are universally catchy.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Guitar-driven Afro-pop with light percussion. Simple arrangement that lets the hook carry everything. Under 3 minutes.',
      craftHighlight: 'Multilingual hook engineering — "love nwantiti" mixes English and Igbo into a phrase that\'s phonetically catchy regardless of whether you understand it.',
    },
    {
      title: 'Calm Down',
      artist: 'Rema',
      year: 2022,
      whyExemplary: 'Longest-charting African song on Billboard Hot 100. Rema\'s rave-influenced Afrobeats created a new sonic lane — youthful, energetic, and globally fluent.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Rave-influenced synths over Afrobeats percussion. The "calm down" hook is both a request and a contradiction (the music is anything but calm).',
      craftHighlight: 'Contradictory hook — telling someone to "calm down" over an energetic beat creates tension the listener feels physically. The instruction opposes the musical instruction.',
    },
    {
      title: 'Last Last',
      artist: 'Burna Boy',
      year: 2022,
      whyExemplary: 'Afro-fusion masterclass that samples Toni Braxton\'s "He Wasn\'t Man Enough" and transforms heartbreak into a party anthem. The emotional alchemy is uniquely Afrobeats.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Sample-driven production with Afrobeats percussion. The Toni Braxton interpolation appears in the chorus, creating nostalgic warmth.',
      craftHighlight: 'Emotional genre-bending — using a melancholy R&B sample as the foundation for a celebratory Afrobeats track. The contrast between source material and new context creates complex feeling.',
    },
    {
      title: 'Peru',
      artist: 'Fireboy DML',
      year: 2021,
      whyExemplary: 'Afro-pop that proved Nigerian artists could create global hits without compromising their sound. The Ed Sheeran remix expanded reach but the original stood alone.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Minimal production: guitar loop, light drums, bass. Fireboy\'s vocal melody carries the entire emotional weight. Under 3 minutes.',
      craftHighlight: 'Melodic simplicity hiding vocal sophistication — the written melody is simple but Fireboy\'s tonal inflections and ad-libs create a second layer of melodic content.',
    },
    {
      title: 'Loaded',
      artist: 'Tiwa Savage',
      year: 2021,
      whyExemplary: 'Dancehall-Afrobeats fusion from the "Queen of Afrobeats" — Tiwa\'s writing centers female desire and agency in a genre where male perspectives dominate.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Dancehall-influenced rhythm with Afrobeats production. Tiwa\'s vocal delivery shifts between singing and toasting across sections.',
      craftHighlight: 'Female agency in Afrobeats — Tiwa writes from the position of the woman who chooses, not the woman who is chosen. The reversal of traditional gender dynamics is the subversion.',
    },
    {
      title: 'Rush',
      artist: 'Ayra Starr',
      year: 2022,
      whyExemplary: 'Grammy-winning Afro-pop from a 20-year-old who became the voice of Gen-Z Afrobeats. The "e dey rush" hook became a cultural catchphrase across Africa.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Minimal production with amapiano influence. Ayra\'s vocal ad-libs and melodic variations carry the arrangement. Short and punchy.',
      craftHighlight: 'Pidgin as pop language — "e dey rush" (it\'s rushing/overwhelming) is Nigerian pidgin that communicates feeling through rhythm as much as meaning.',
    },
    {
      title: 'Unavailable',
      artist: 'Davido ft. Musa Keys',
      year: 2023,
      whyExemplary: 'Amapiano-Afrobeats fusion that became the template for the two genres merging. Davido\'s Nigerian energy over South African production created a Pan-African moment.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Amapiano log drum and bassline with Afrobeats vocal melody. Davido\'s ad-libs ("unavailable!") function as both hook and rhythmic element.',
      craftHighlight: 'Pan-African genre fusion — the production is South African, the vocals are Nigerian, and the result belongs to neither country alone. Musical Pan-Africanism in practice.',
    },
    {
      title: 'Water',
      artist: 'Tyla',
      year: 2023,
      whyExemplary: 'First Grammy for Best African Music Performance. Tyla\'s amapiano-pop introduced South African house rhythms to a global pop audience. The water metaphor is body-positive and sensual.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Amapiano bassline and log drum with pop vocal melody. The "make me sweat, make me hotter" hook is call-and-response ready.',
      craftHighlight: 'Body-as-water metaphor — "water" describes fluidity, sensuality, and movement simultaneously. The single word carries the entire physical vocabulary of the song.',
    },
    {
      title: 'Kilometer',
      artist: 'Burna Boy',
      year: 2021,
      whyExemplary: 'Afrobeats victory lap from Burna Boy\'s Grammy-winning era. The "kilometer" measurement metaphor extends through every bar — distance as achievement.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Afrobeats percussion with horn section. Up-tempo party track with Burna\'s signature gravel-voiced delivery.',
      craftHighlight: 'Extended measurement metaphor — "kilometer" measures success, distance from doubters, and the journey from Lagos to global stardom. One word, multiple scales.',
    },
    {
      title: 'Sability',
      artist: 'Ayra Starr',
      year: 2021,
      whyExemplary: 'Debut-era Afro-pop that established Ayra Starr\'s voice as the sound of young Lagos. "Sability" (stability) rendered in pidgin captures economic anxiety with a party beat.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Minimalist production with percussion and bass. Ayra\'s voice dominates the mix. Call-and-response chorus structure.',
      craftHighlight: 'Economic anxiety as dance music — "sability" (stability/financial security) is a serious topic delivered over a joyful beat. The tension between content and feel is quintessentially Afrobeats.',
    },
    {
      title: 'Bandana',
      artist: 'Fireboy DML ft. Asake',
      year: 2022,
      whyExemplary: 'Two of Afrobeats\' biggest voices on one track — Fireboy\'s melodic sophistication meets Asake\'s street-pop rawness. The contrast is the chemistry.',
      structuralNotes: 'Verse (Fireboy)-chorus-verse (Asake)-chorus-outro. The two artists bring completely different delivery styles. Production bridges both approaches with a mid-tempo groove.',
      craftHighlight: 'Contrast as collaboration — Fireboy\'s polish and Asake\'s grit represent two sides of Lagos. The song works because they don\'t try to sound alike.',
    },
    {
      title: 'Organise',
      artist: 'Asake',
      year: 2022,
      whyExemplary: 'Street-pop with Fuji music influence that made Asake a phenomenon. His vocal style — somewhere between singing, chanting, and preaching — created a new delivery mode.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Fuji-influenced percussion with modern Afrobeats production. Asake\'s chanting delivery blurs the line between verse and chorus.',
      craftHighlight: 'Fuji-pop fusion — Asake brought Fuji music\'s Yoruba spiritual chanting tradition into mainstream Afrobeats, creating a delivery style nobody else could replicate because it requires cultural fluency.',
    },
    {
      title: 'Higher',
      artist: 'Burna Boy',
      year: 2022,
      whyExemplary: 'Afro-fusion anthem from the "Love, Damini" album that shows Burna\'s ability to write for stadiums while maintaining Afrobeats groove. Global scale, Lagos soul.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Full arrangement: live drums, horns, synths, choir. Builds from intimate verse to anthemic chorus. Arena-ready dynamics.',
      craftHighlight: 'Scale escalation — each section gets bigger, mirroring Burna\'s career trajectory. The musical growth from verse to chorus IS the "higher" the title promises.',
    },
    {
      title: 'Electricity',
      artist: 'Pheelz ft. Davido',
      year: 2022,
      whyExemplary: 'Afro-pop hit built on a single metaphor — love as electricity. Pheelz\'s production and Davido\'s vocal charm made it an instant classic.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Bouncy Afrobeats production with minimal instrumentation. The "electricity" hook is catchy enough to carry the entire song.',
      craftHighlight: 'Electricity metaphor unpacked — current, spark, shock, power — each verse explores a different aspect of the central image. The metaphor generates content naturally.',
    },
    {
      title: 'Ku Lo Sa',
      artist: 'Oxlade',
      year: 2022,
      whyExemplary: 'Afro-pop ballad that showcases Oxlade\'s vulnerable falsetto. Proved Afrobeats could be soft and intimate, not just high-energy party music.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Acoustic-leaning production with gentle percussion. Oxlade\'s falsetto dominates. Slow tempo for Afrobeats — a deliberate choice.',
      craftHighlight: 'Vulnerability as range-expansion — in a genre associated with confidence and party energy, Oxlade\'s soft delivery opened space for emotional intimacy in Afrobeats.',
    },
    {
      title: 'Mnike',
      artist: 'Tyler ICU ft. Tumelo ZA, DJ Maphorisa & others',
      year: 2023,
      whyExemplary: 'Amapiano anthem that dominated African dancefloors. The collaborative production model (multiple artists, one groove) represents amapiano\'s communal creation process.',
      structuralNotes: 'Intro-verse-chorus-verse-chorus-extended groove section. Amapiano log drum and bassline foundation. Multiple vocalists enter and exit over the persistent groove.',
      craftHighlight: 'Communal composition — amapiano tracks are often built collectively in studio sessions. The groove is the composition, and individual contributions layer on top organically.',
    },
    {
      title: 'Feel',
      artist: 'Davido',
      year: 2023,
      whyExemplary: 'Timeless Afro-pop from Davido\'s comeback era — the title captures the genre\'s core value: above all else, the music must make you FEEL something.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Mid-tempo with rich production: keys, guitar, percussion. Davido\'s vocal warmth carries the emotional weight.',
      craftHighlight: 'One-word thesis — "feel" as title and hook captures Afrobeats\' entire artistic philosophy. The music prioritizes emotional response over intellectual analysis.',
    },
    {
      title: 'City Boys',
      artist: 'Burna Boy',
      year: 2022,
      whyExemplary: 'Highlife-Afrobeats fusion that connects contemporary Afrobeats to its highlife roots. Burna Boy\'s knowledge of genre history informs his innovation.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Highlife guitar patterns over modern Afrobeats percussion. Horn section adds warmth. Burna\'s delivery is relaxed and conversational.',
      craftHighlight: 'Historical continuity — the highlife guitar pattern explicitly connects this 2022 track to 1960s/70s West African music. Innovation through tradition, not despite it.',
    },
    {
      title: 'Hustlovic',
      artist: 'Shallipopi ft. Zlatan',
      year: 2023,
      whyExemplary: 'Street-pop that captures Lagos hustle culture in a portmanteau title. Shallipopi\'s slang-heavy writing documents the city\'s informal economy.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Street-pop production: heavy bass, minimal melody, rhythmic vocal delivery. Zlatan\'s verse adds veteran street-rap credibility.',
      craftHighlight: 'Slang as documentation — Shallipopi\'s lyrics are dense with Lagos street vocabulary that captures an economic reality mainstream media ignores. The song is an archive.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: ['Afrobeats', 'African', 'danceable', 'percussion', 'log drum', 'groovy', 'infectious'],
    avoidKeywords: ['heavy metal', 'country', 'folk', 'classical', 'grunge', 'industrial', 'harsh'],
    promptTemplate: '[sub-genre] Afrobeats, [tempo] BPM, [mood] mood, [percussion style], [vocal style], [language]',
    tips: [
      'Specify the sub-genre: Afro-pop, Amapiano, Afro-fusion, Alte',
      'Describe the percussion: log drum, shekere, layered',
      'Mention the language: English, Pidgin, Yoruba, or mixed',
      'Reference the mood: celebratory, romantic, energetic, smooth',
      'Include "danceable" and "groovy" as key descriptors',
      'Describe the energy: party, romantic, chill, high-energy',
    ],
  },
};
