import type { GenreGuide } from './types';

export const ARABIC_GUIDE: GenreGuide = {
  id: 'arabic',
  name: 'Arabic Music',
  language: 'Arabic',

  sonicPalette: {
    overview: 'Melodically ornate, emotionally intense, and rhythmically sophisticated. Arabic music is built on the maqam system — a framework of melodic modes that creates emotional colour unavailable in Western equal temperament. The oud, the human voice, and the tabla/darbuka are the trinity.',
    timbre: [
      'oud (fretless lute — the king of Arabic instruments)',
      'nay (end-blown flute)',
      'qanun (plucked zither)',
      'darbuka/tabla (goblet drum)',
      'riq (tambourine)',
      'violin (Arabic tuning, microtonal)',
    ],
    texture: 'Heterophonic — multiple instruments play the same melody with individual ornamentation, creating a shimmering unison that is richer than Western unison. Modern production adds electronic layers beneath this traditional texture.',
    tonality: 'Maqam-based — quarter-tones and microtonal intervals create emotional shades unavailable in Western tuning. Maqam Bayati (melancholic), Hijaz (exotic tension), Rast (bright openness) are foundational.',
    signatureSounds: [
      'oud taqsim (improvised solo)',
      'darbuka/tabla rhythmic pattern',
      'qanun cascading arpeggios',
      'nay breathy sustained notes',
      'vocal melisma with microtonal ornament',
    ],
  },

  rhythmAndGroove: {
    overview: 'Arabic rhythm (iqa\'at) is a sophisticated system of named patterns that underpin all traditional and modern music. These patterns combine bass (dum) and treble (tak) strokes in cycles of varying length.',
    bpmRange: { min: 60, max: 160, sweet: 95 },
    feel: 'Varies from the stately grandeur of tarab to the driving energy of dabke to the modern bounce of mahraganat. The rhythmic feel is always physically engaging.',
    swing: 'Not Western swing but a natural elasticity within iqa\'at patterns. Ornamental fills (takasim rhythmique) add rhythmic interest between structural strokes.',
    syncopation: 'High. Arabic rhythmic patterns are inherently asymmetric — the interplay of dum and tak strokes creates syncopation as a structural feature, not a decoration.',
    grooveArchetype: 'Maqsoum (4/4 with dum-tak-tak-dum-tak pattern), saidi (earthy, driving), malfuf (fast 2/4), ayoub (hypnotic 2/4).',
    rhythmicSignatures: [
      'maqsoum: dum-tak-tak-dum-tak (4/4, most common Arabic rhythm)',
      'baladi: dum-dum-tak-dum-tak (earthier maqsoum variant)',
      'saidi: dum-tak-dum-dum-tak (driving, Upper Egyptian)',
      'malfuf: dum-tak-tak (fast 2/4, dance)',
      'dabke: heavy 4/4 stomp rhythm',
    ],
  },

  harmonicLanguage: {
    overview: 'Arabic music is primarily melodic, not harmonic. The maqam system provides the melodic framework — each maqam is a scale with rules about which notes to emphasise, ornament, and resolve to. Harmony in the Western sense is a modern addition.',
    scales: [
      'maqam Bayati (melancholic, contemplative)',
      'maqam Hijaz (dramatic, exotic)',
      'maqam Rast (bright, open, festive)',
      'maqam Nahawand (similar to harmonic minor)',
      'maqam Kurd (similar to Phrygian)',
    ],
    chordProgressions: [
      'modal drone over single maqam (traditional)',
      'i – bII – i (Hijaz cadence)',
      'i – iv – V – i (Nahawand, minor-like)',
      'I – IV – V – I (modern Arabic pop)',
    ],
    harmonyNotes: 'Traditional Arabic music is monophonic or heterophonic — harmony is a Western import. Modern Arabic pop uses Western chord progressions beneath maqam-based melodies, creating a distinctive hybrid.',
    modality: 'Entirely modal. Maqam modulation (intiqal) — moving between maqamat within a performance — is a high art. The singer or instrumentalist\'s ability to navigate maqam transitions is a measure of mastery.',
  },

  songStructure: {
    overview: 'Traditional Arabic song forms are long and improvisatory. Tarab performances can last 45+ minutes. Modern Arabic pop adopts Western verse-chorus structure while retaining melodic elaboration.',
    form: 'Traditional: Taqsim (improv) – Muqaddima (intro) – Dawr/Qadd (composed sections) – Improvised sections. Modern: Intro – Verse – Chorus – Verse – Chorus – Bridge – Chorus.',
    sections: [
      'Taqsim (instrumental improvisation establishing maqam)',
      'Verse (melodic exposition, lower intensity)',
      'Chorus/Refrain (hookh, higher energy)',
      'Bridge (maqam modulation or spoken section)',
      'Tarab climax (emotional peak with audience interaction)',
    ],
    arrangement: 'Traditional: takht (small ensemble) builds intensity through the performance. Modern: Western pop arrangement with Arabic melodic content.',
    introOutro: 'Oud taqsim as intro is iconic. Modern intros use synth or orchestral hooks. Outros may fade on repeated chorus or end with instrumental maqam resolution.',
    barLengths: 'Modern pop: standard 8-bar sections. Traditional: phrases determined by maqam development and text, not bar lines.',
    hookPlacement: 'Modern Arabic pop places hooks early. Traditional tarab builds to emotional peaks organically — the "hook" is the moment of tarab (ecstasy) achieved through accumulated intensity.',
  },

  vocalDelivery: {
    overview: 'The Arabic voice is the supreme instrument. Tarab — the state of musical ecstasy — is the goal. Singers use microtonal ornament, melisma, and emotional intensity to transport the audience. The great voices (Umm Kulthum, Fairuz, Abdel Halim) are cultural monuments.',
    phrasing: 'Long, arcing phrases with extensive ornamental melisma. Arabic\'s guttural consonants and long vowels create naturally dramatic vocal lines. Phrases build in intensity toward emotional peaks.',
    affect: 'Intense emotional commitment. Tarab requires the singer to be emotionally present and transmit feeling directly to the audience. Longing (shawq), passion (hawa), and heartbreak (firaq) are primary registers.',
    techniques: [
      'melismatic ornament with microtonal intervals',
      'vocal tremolo (trilling between adjacent notes)',
      'chest voice power for dramatic climaxes',
      'mawwal (vocal improvisation establishing maqam)',
      'ululation (zaghroutah) for celebration',
    ],
    adlibStyle: 'Vocal improvisation is central, not an add-on. The mawwal (improvised vocal passage) is a required skill. Audience responses ("Allah!", "Ya salam!") are part of the performance.',
    harmony: 'Minimal — Arabic music is monophonic in tradition. Modern pop adds backing vocal layers. Heterophonic texture (instruments doubling the vocal melody with ornament) is characteristic.',
    grit: 'Variable. Tarab singers maintain vocal purity. Shaabi and mahraganat singers use raw, street-edged delivery. Modern pop ranges from smooth to raspy.',
  },

  lyricalConventions: {
    overview: 'Arabic lyrics inherit one of the world\'s great literary traditions — pre-Islamic poetry, Quranic prose, and centuries of court poetry shape the lyrical landscape. Even pop music is expected to have linguistic beauty.',
    themes: [
      'romantic love and longing (hubb, shawq)',
      'heartbreak and separation (firaq)',
      'the beloved\'s beauty (wasfal-mahbub)',
      'homeland and exile (watan, ghurba)',
      'spiritual devotion',
      'celebration and festivity (farah)',
    ],
    perspective: 'First-person address to the beloved is dominant. Second-person intimate address. Classical forms use the lover as metaphor for the divine.',
    figurativeLanguage: 'Elaborate metaphor inherited from classical Arabic poetry. The beloved as garden, moon, gazelle. Night as the space of longing. The desert as emotional landscape. Quranic and hadith references.',
    vocabulary: 'Modern Standard Arabic (fusha) for prestige. Dialectal Arabic (ammiya) for populist appeal — Egyptian, Levantine, Gulf, Maghrebi dialects each have distinct vocabulary.',
    storytellingApproach: 'Emotional elaboration over narrative. A single feeling is explored from multiple angles. The beauty of language is as important as the message. Classical poetry forms (qasida, ghazal) echo in modern lyrics.',
    cliches: [
      '"ya habibi" (my beloved) as universal address',
      'the eyes (uyun) as emotional metaphor',
      'the night (layl) as longing space',
      'fire of love (nar al-hubb)',
    ],
  },

  productionFingerprint: {
    overview: 'Arabic production spans traditional acoustic ensemble recording to hyper-modern electronic pop. Cairo, Beirut, and Riyadh are major production centres. The tension between preserving maqam authenticity and adopting global production techniques defines the modern sound.',
    mixAesthetic: 'Voice always forward and present — the singer is the star. Traditional: dry and intimate. Modern pop: polished and bass-forward. Mahraganat: compressed, loud, and deliberately rough.',
    era: 'Current era: streaming-driven Arabic pop, mahraganat (Egyptian street music) going global, Khaleeji pop sophistication, and ongoing reverence for golden-age tarab.',
    signalChain: 'Traditional: live ensemble (takht) recording. Modern: DAW-based with Arabic instrument samples/VSTs and Western production techniques. Vocal: large-diaphragm condenser, light compression, reverb.',
    modernTrends: 'Mahraganat\'s lo-fi electronic production going mainstream. Khaleeji pop incorporating EDM drops. Arabic trap and hip-hop. Netflix/streaming content driving Arabic pop exposure.',
  },

  instrumentation: {
    coreInstruments: [
      'oud (fretless lute)',
      'darbuka/tabla (goblet drum)',
      'nay (end-blown flute)',
      'qanun (plucked zither)',
      'violin (Arabic-tuned)',
      'riq (tambourine)',
    ],
    signatureSounds: [
      'oud taqsim improvisation',
      'darbuka maqsoum pattern',
      'qanun cascading runs',
      'nay breathy melody',
    ],
    layering: 'Traditional: heterophonic — instruments double the melody with individual ornament. Modern: Western layering with Arabic melodic content on top.',
    avoidInstruments: [
      'distorted rock guitar (unless fusion)',
      'country instruments',
      'Latin percussion',
      'East Asian traditional instruments',
    ],
  },

  culturalContext: {
    overview: 'Arabic music serves 400+ million Arabic speakers across 22 countries with enormous regional diversity. Music is central to celebration (weddings, festivals) and to the expression of pan-Arab cultural identity.',
    origin: 'Egypt (Cairo as historic centre — Umm Kulthum, golden age). Lebanon (Beirut as artistic centre — Fairuz). Gulf states (Khaleeji pop). North Africa (raï, Andalusian traditions). Levant (dabke, muwashshah).',
    identity: 'Arabic language unifies diverse regional traditions. Music carries the weight of Arab cultural pride and identity. The golden age of Arabic music (1940s-70s) remains a cultural reference point.',
    community: 'Pan-Arab through shared language. Regional pride in Egyptian, Lebanese, Gulf, Maghrebi, and Levantine traditions. Weddings are the primary communal music event.',
    socialFunction: 'Weddings and celebrations. Tarab as spiritual-aesthetic experience. Religious music (nasheed, Sufi). Political expression and national identity. Social commentary (mahraganat, shaabi).',
    authenticityMarkers: [
      'correct maqam usage',
      'Arabic lyrics with appropriate register',
      'authentic rhythmic patterns (iqa\'at)',
      'vocal ornament reflecting Arabic tradition',
      'cultural sensitivity to religious and social norms',
    ],
  },

  historicalLineage: {
    overview: 'From pre-Islamic poetry and the Abbasid golden age through Ottoman court music to the 20th-century Egyptian golden age and contemporary global Arabic pop.',
    roots: [
      'pre-Islamic Arabic poetry and song',
      'Abbasid-era court music (8th-13th century)',
      'Andalusian muwashshah tradition',
      'Ottoman classical music',
      'Egyptian 20th-century golden age',
    ],
    evolution: 'Classical maqam tradition → Cairo golden age (1940s-70s, Umm Kulthum, Abdel Halim) → Arabic pop modernization (1980s-90s) → diaspora and global fusion (2000s) → mahraganat and streaming era (2010s-present).',
    keyEras: [
      '8th-13th century: Abbasid musical golden age',
      '1940s-70s: Egyptian golden age (Umm Kulthum, Fairuz)',
      '1980s-90s: Arabic pop modernization',
      '2000s: Raï and world music crossover',
      '2010s-present: Mahraganat and digital era',
    ],
    influencedBy: [
      'Persian musical tradition',
      'Turkish/Ottoman court music',
      'Indian classical music (shared modal concepts)',
      'Western pop and electronic music',
    ],
    influenced: [
      'flamenco (via Al-Andalus)',
      'Turkish music',
      'North African music (Maghreb)',
      'global world music and fusion',
    ],
  },

  subGenres: [
    {
      name: 'Tarab',
      description: 'The classical art of musical ecstasy — long-form performances where the singer uses maqam mastery, vocal ornament, and emotional intensity to transport the audience into a state of tarab (ecstasy). Umm Kulthum and Abdel Halim defined the art.',
      distinguishingFeatures: ['maqam mastery', 'long-form performance', 'audience interaction', 'vocal melismatic virtuosity'],
      bpmRange: { min: 60, max: 90 },
      keyArtists: ['Umm Kulthum', 'Abdel Halim Hafez', 'Warda', 'Asmahan'],
      productionNotes: 'Live ensemble recording. Takht or full orchestra. Minimal studio processing. The performance IS the recording.',
      lyricNotes: 'Classical Arabic poetry — highest literary register. Extended metaphor, elaborate description of love and longing.',
      sunoPromptKeywords: ['tarab', 'Arabic classical', 'Umm Kulthum style', 'maqam', 'Egyptian golden age'],
    },
    {
      name: 'Khaleeji',
      description: 'Gulf Arabic pop — the music of Saudi Arabia, UAE, Kuwait, Qatar, Bahrain, and Oman. Distinct rhythmic patterns (khaleegy, samri), khaleeji vocal style, and increasingly lavish pop production.',
      distinguishingFeatures: ['khaleeji rhythmic patterns', 'Gulf Arabic dialect', 'oud-prominent', 'lavish modern production'],
      bpmRange: { min: 90, max: 130 },
      keyArtists: ['Mohammed Abdo', 'Abdul Majeed Abdullah', 'Rashed Al-Majed', 'Balqees'],
      productionNotes: 'Modern Gulf production: polished, sometimes EDM-influenced. Oud remains central. Electronic percussion blended with traditional rhythms.',
      lyricNotes: 'Gulf Arabic dialect. Romantic love, loyalty, national pride, Bedouin cultural references.',
      sunoPromptKeywords: ['Khaleeji', 'Gulf Arabic pop', 'Saudi pop', 'UAE music', 'Arabian pop'],
    },
    {
      name: 'Shaabi',
      description: 'Egyptian working-class popular music — raw, energetic, and street-authentic. Ahmad Adaweyya pioneered the genre in the 1970s. The voice of Cairo\'s popular neighborhoods.',
      distinguishingFeatures: ['raw vocal delivery', 'working-class themes', 'Egyptian Arabic (ammiya)', 'tabla-driven rhythm'],
      bpmRange: { min: 100, max: 130 },
      keyArtists: ['Ahmad Adaweyya', 'Hakim', 'Shaaban Abdel Rahim'],
      productionNotes: 'Raw, energetic production. Tabla prominent. Organ or keyboard. Vocal forward and unpolished.',
      lyricNotes: 'Working-class Cairo life, love, social commentary, humour. Colloquial Egyptian Arabic.',
      sunoPromptKeywords: ['shaabi', 'Egyptian street music', 'Cairo popular', 'Egyptian folk pop'],
    },
    {
      name: 'Mahraganat',
      description: 'Egyptian electronic street music born in Cairo\'s popular neighborhoods — auto-tuned vocals over frenetic electronic beats with synthesized tabla. The sound of 2010s-20s Egyptian youth.',
      distinguishingFeatures: ['electronic production with synth tabla', 'auto-tuned vocals', 'frenetic energy', 'youth street culture'],
      bpmRange: { min: 100, max: 140 },
      keyArtists: ['Hassan Shakosh', 'Wegz', 'Omar Kamal', 'Islam Chipsy'],
      productionNotes: 'FL Studio production. Synthesized tabla and percussion. Auto-tune on vocals. Compressed and loud. Lo-fi aesthetic is deliberate.',
      lyricNotes: 'Street life, youth swagger, love, partying. Colloquial Egyptian Arabic with heavy slang.',
      sunoPromptKeywords: ['mahraganat', 'Egyptian electro', 'Cairo street music', 'Egyptian trap', 'shaabi electronic'],
    },
    {
      name: 'Arabic Pop',
      description: 'Modern commercial Arabic pop — polished production, accessible melodies, and broad pan-Arab appeal. From Amr Diab\'s Mediterranean pop to Nancy Ajram\'s dance hits.',
      distinguishingFeatures: ['polished international production', 'Arabic melodies over Western pop beds', 'pan-Arab market appeal', 'music video culture'],
      bpmRange: { min: 90, max: 130 },
      keyArtists: ['Amr Diab', 'Nancy Ajram', 'Elissa', 'Tamer Hosny'],
      productionNotes: 'International pop production standards. Arabic instruments blended with Western synths and beats. Vocal pristine and forward.',
      lyricNotes: 'Romantic love, summer, dancing, celebration. Egyptian or Lebanese Arabic for broadest appeal.',
      sunoPromptKeywords: ['Arabic pop', 'Amr Diab style', 'Lebanese pop', 'Egyptian pop', 'modern Arabic'],
    },
    {
      name: 'Raï',
      description: 'Algerian popular music blending folk traditions with Western pop and rock. Born in Oran, Algeria — the music of youth rebellion against conservative society. Khaled and Cheb Mami brought it global.',
      distinguishingFeatures: ['Algerian Darja dialect', 'derbouka and gasba', 'blend of folk and pop/rock', 'youth rebellion themes'],
      bpmRange: { min: 90, max: 125 },
      keyArtists: ['Khaled', 'Cheb Mami', 'Rachid Taha', 'Cheb Hasni'],
      productionNotes: 'Hybrid production — derbouka and traditional instruments over pop/rock arrangements. Electric guitar prominent. Vocal forward with ornament.',
      lyricNotes: 'Love, rebellion, exile, social frustration. Algerian Darja. Emotional directness.',
      sunoPromptKeywords: ['raï', 'Algerian raï', 'Khaled style', 'North African pop', 'Oran music'],
    },
    {
      name: 'Dabke',
      description: 'Levantine line-dance music — the communal music of Syria, Lebanon, Palestine, and Jordan. Driving rhythm, melodic energy, and inseparable from the collective stomping dance.',
      distinguishingFeatures: ['driving 4/4 stomp rhythm', 'mijwiz or zurna melody', 'line dance tradition', 'Levantine Arabic'],
      bpmRange: { min: 120, max: 160 },
      keyArtists: ['Omar Souleyman', 'Nassif Zeytoun', 'traditional dabke ensembles'],
      productionNotes: 'Driving rhythm is essential. Mijwiz (double-pipe) or electronic equivalent for melody. Modern dabke adds synths and electronic drums.',
      lyricNotes: 'Celebration, community, love, homeland. Levantine Arabic dialect. Dance commands.',
      sunoPromptKeywords: ['dabke', 'Lebanese dabke', 'Levantine dance', 'Omar Souleyman style', 'Arabic dance music'],
    },
    {
      name: 'Arabic Hip-Hop',
      description: 'Hip-hop in Arabic — from Palestinian resistance rap to Egyptian street rap to Gulf trap. A growing force combining American hip-hop production with Arabic lyrical tradition.',
      distinguishingFeatures: ['Arabic-language rap flow', 'trap and boom-bap production', 'political and social themes', 'regional dialect diversity'],
      bpmRange: { min: 75, max: 95 },
      keyArtists: ['DAM', 'Wegz', 'Shabjdeed', 'El-Rass'],
      productionNotes: 'Standard hip-hop production adapted for Arabic flow. Trap 808s. Arabic instrument samples for identity. Vocal clarity essential.',
      lyricNotes: 'Political resistance, social commentary, street life, identity. Arabic wordplay. Regional dialects.',
      sunoPromptKeywords: ['Arabic hip-hop', 'Arabic rap', 'Palestinian rap', 'Egyptian rap', 'Arabic trap'],
    },
    {
      name: 'Andalusian Classical',
      description: 'The refined court music tradition of Muslim Andalusia (Al-Andalus), preserved in Morocco, Algeria, Tunisia, and Libya. Elaborate suite forms (nuba) with maqam-based melodies.',
      distinguishingFeatures: ['nuba suite form', 'Andalusian maqamat', 'refined ensemble performance', 'centuries-old repertoire'],
      bpmRange: { min: 60, max: 120 },
      keyArtists: ['Orchestre National de Barbès', 'El Hadj M\'Hamed El Anka', 'traditional Andalusian ensembles'],
      productionNotes: 'Live ensemble recording. Acoustic instruments: oud, rabab, violin, percussion. Minimal production processing.',
      lyricNotes: 'Classical Arabic and Andalusian poetry. Love, nature, divine contemplation. Highest literary register.',
      sunoPromptKeywords: ['Andalusian', 'Arabic classical', 'muwashshah', 'North African classical', 'Arabic court music'],
    },
    {
      name: 'Gulf Electronic',
      description: 'Modern electronic fusion from the Gulf states — combining khaleeji rhythms and Arabic melodies with EDM, house, and experimental electronic production.',
      distinguishingFeatures: ['EDM production with khaleeji elements', 'Gulf Arabic vocals', 'electronic reimagining of traditional rhythms', 'luxury aesthetic'],
      bpmRange: { min: 110, max: 140 },
      keyArtists: ['Cosmicat', 'Vinyl Mode', 'Bu Kolthoum'],
      productionNotes: 'International electronic production with Gulf rhythmic and melodic DNA. Arabic instrument samples processed electronically. Festival and club-ready.',
      lyricNotes: 'Minimal lyrics or Arabic vocal samples. Atmospheric and instrumental. When lyrics appear: Gulf Arabic.',
      sunoPromptKeywords: ['Gulf electronic', 'Arabian electronic', 'Middle Eastern EDM', 'Arabic house', 'khaleeji electronic'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Arabic music audiences span 22 countries with fierce regional pride. Egyptian and Lebanese pop have the broadest pan-Arab reach. Gulf music has growing influence through oil wealth and media investment.',
    fanExpectations: [
      'vocal quality and emotional delivery',
      'correct maqam usage in traditional contexts',
      'Arabic lyrics in appropriate dialect',
      'cultural sensitivity to religious norms',
      'production quality matching the sub-genre',
    ],
    gatekeeping: 'High in classical/tarab (maqam knowledge is non-negotiable). Moderate in pop (commercial success validates). Low in mahraganat (street authenticity over formal training).',
    livePerformance: 'Weddings are the primary live music context. Tarab concerts are hours-long communal experiences. Pop concerts are increasingly arena-scale. Dabke is communal dance.',
    fashionAndAesthetic: 'Gulf: luxury and traditional dress (thobe, abaya). Egyptian pop: glamorous and Western-influenced. Lebanese: fashion-forward and cosmopolitan. Traditional: formal and respectful.',
    crossoverPotential: 'Growing through streaming and diaspora. Raï achieved global crossover. Mahraganat reaching international audiences. Arabic pop increasingly visible on global platforms. Maqam-based music influences global world music.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Arabic music\'s timing operates outside the Western grid. Maqam-based music uses ornamental timing where melismatic phrases stretch and compress time organically. The concept of "tarab time" — where emotional intensity dictates duration — is fundamentally different from metronomic timekeeping.',
    quantizationDeviation: 'High in traditional and tarab music — Western quantization would destroy the ornamental timing essential to maqam performance. Moderate in modern Arabic pop (grid with ornamental vocal freedom). Low in mahraganat (electronic grid-locked).',
    aheadBehindBeat: 'Vocal phrases in tarab float above the rhythmic cycle (iqa\'a), landing where emotional expression demands. The darbuka player subtly adjusts to the singer. In modern pop, vocals sit more on-grid but retain ornamental freedom.',
    humanizationMarkers: [
      'vocal melisma stretching across multiple beats with microtonal ornament',
      'darbuka fills (takasim rhythmique) between structural beats adding human flourish',
      'oud taqsim rubato passages completely free of meter',
      'ensemble heterophonic timing — multiple instruments playing the same melody with individual ornament',
      'singer-controlled tempo in tarab — the ensemble follows the vocalist\'s emotional pacing',
    ],
    genreSpecificFeel: 'The Arabic feel defies Western timing analysis. Ornamental notes fall between grid positions; microtonal intervals fall between piano keys. The timing is not "loose" — it is precisely expressive within a system that prioritizes emotional truth over metronomic accuracy.',
  },

  silenceAndSpace: {
    overview: 'In Arabic music, silence is inhabited by anticipation. The pause before a singer begins a mawwal (vocal improvisation), the space between iqa\'at cycles, the audience\'s held breath before a vocal climax — silence is where tarab begins to build.',
    negativeSpaceRole: 'The taqsim (instrumental improvisation) uses silence between phrases to let notes decay and maqam colour register emotionally. In tarab performance, the singer\'s pause creates unbearable anticipation that the next phrase must resolve.',
    breathingPatterns: 'Traditional: the singer breathes where the Arabic text demands, and the ensemble breathes with them. Modern pop: more structured breathing aligned with the rhythmic grid. The nay (flute) makes breathing part of its timbre.',
    dynamicContrast: 'Enormous in tarab — Umm Kulthum could hold an audience silent with a whisper and then overwhelm with full-voice power. Mahraganat has low dynamic range (compressed and loud). Modern pop has moderate contrast.',
    whatIsDeliberatelyAbsent: [
      'Western functional harmony in traditional maqam music — the drone replaces chord changes',
      'percussion during taqsim improvisation — silence frames the solo instrument',
      'backing vocals in classical tarab — the solo voice is uncontested',
      'electronic elements in traditional ensemble settings',
      'rushed transitions — Arabic music takes the time emotion requires',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response is fundamental to Arabic music — from the audience\'s ecstatic responses during tarab ("Allah!", "Ya salam!") to the antiphonal relationship between singer and takht (ensemble) to dabke\'s communal dance-music dialogue.',
    vocalInstrumentalDialogue: 'The takht ensemble mirrors the singer\'s phrases (heterophony). The qanun responds to vocal lines with cascading runs. The oud answers the singer during pauses. This dialogue is not arranged — it emerges from ensemble intuition and maqam knowledge.',
    sectionInternal: 'Within a tarab performance, the singer phrases and the ensemble responds, then the ensemble plays and the singer ornaments. Each exchange raises the emotional intensity. In modern pop, this becomes structured verse-chorus contrast.',
    audienceParticipation: 'In tarab, the audience IS part of the performance — their exclamations ("Taani! Taani!" — again!) can cause the singer to repeat and intensify phrases. The audience\'s emotional response guides the performance\'s direction and duration.',
    patterns: [
      'audience exclamations ("Allah!", "Ya salam!", "Taani!") as emotional feedback',
      'takht ensemble heterophonic response to vocal phrases',
      'qanun cascading runs answering vocal cadences',
      'dabke line dance responding to the mizmar/mijwiz melody',
      'wedding zaghroutah (ululation) as communal celebration call',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Arabic dialect diversity is among the most consequential in world music. Egyptian, Levantine, Gulf, Maghrebi, and Iraqi Arabic are mutually challenging, and each carries a distinct musical tradition, vocal aesthetic, and cultural identity.',
    phoneticMarkers: [
      'Egyptian Arabic\'s "g" for qaf and distinctive "e" vowels — the most widely understood dialect',
      'Levantine Arabic\'s melodic intonation and "aa" vowels (Lebanese, Syrian, Palestinian)',
      'Gulf Arabic\'s deep guttural consonants and distinctive "ch" for kaf',
      'Maghrebi Arabic\'s French-influenced phonology and contracted vowels',
      'Iraqi Arabic\'s distinct maqam-influenced vocal ornamentation',
    ],
    accentInfluence: 'Egyptian Arabic dominates pan-Arab pop due to Egypt\'s film and music industry reach. Lebanese Arabic carries cosmopolitan sophistication. Gulf Arabic increasingly influences through oil-wealth-funded media. Each dialect shapes melodic contour differently.',
    dialectVocabulary: [
      '"habibi" (Egyptian/standard) vs "hayati" (Levantine) vs "roohi" (Gulf) for "my love"',
      'Egyptian colloquial (ammiya) slang in shaabi and mahraganat',
      'Levantine poetic vocabulary in Lebanese pop (Fairuz lineage)',
      'Gulf Bedouin vocabulary in khaleeji traditional songs',
      'Algerian Darja French-Arabic hybrid vocabulary in raï',
    ],
    regionWithinCulture: 'Egypt (Cairo) remains the historic cultural centre with broadest pop reach. Lebanon (Beirut) is the artistic and cosmopolitan centre. Gulf states invest heavily in production infrastructure. Morocco and Algeria have distinct Maghrebi traditions. Iraq has its own maqam school. Each region fiercely maintains its musical identity.',
  },

  performancePractice: {
    overview: 'Arabic performance practice ranges from the hours-long tarab concert — where singer and audience co-create the experience — to the modern pop concert and the communal dabke line dance.',
    improvisationConventions: 'Central in traditional music. The taqsim (instrumental improvisation) and mawwal (vocal improvisation) are required skills. The singer may repeat and extend sections based on audience response. Modern pop is more structured but retains ornamental freedom.',
    crowdInteraction: 'In tarab: audience and performer are in dialogue — exclamations guide the performance. In dabke: the music drives communal dance with the dabke leader (ras al-dabke) directing. In modern pop: concerts increasingly follow Western models.',
    stagePresence: 'Tarab: seated or standing still, all attention on the voice. The singer may close eyes, gesture with hands, sway. No choreography — the music IS the performance. Modern pop: increasingly visual with staging and production.',
    livVsRecordedDifferences: 'Traditional tarab recordings are live performances — the recording captures the specific audience-artist interaction of that night. Modern pop is studio-produced. Live concerts may extend songs dramatically beyond studio versions.',
    whatMakesAGoodShow: 'In tarab: achieving the state of tarab (ecstasy) — both singer and audience transported. Technical maqam mastery demonstrated through modulation. In pop: energy, production quality, hits. In dabke: keeping the line dancing all night.',
  },

  socioeconomicSubtext: {
    overview: 'Arabic music reflects the region\'s enormous economic disparities — from Gulf oil wealth funding lavish pop production to Cairo\'s working-class neighborhoods birthing shaabi and mahraganat to diaspora communities maintaining musical connections to homeland.',
    materialConditions: 'Gulf states fund high-production-value pop and music infrastructure. Egyptian music operates on lower budgets with higher creative output. Mahraganat emerged from Cairo neighborhoods with minimal resources and FL Studio. Diaspora markets drive streaming revenue.',
    classIdentity: 'Tarab carries cultural prestige associated with education and refined taste. Shaabi and mahraganat are explicitly working-class forms. Khaleeji pop reflects Gulf affluence. Raï emerged as working-class Algerian youth expression.',
    politicalUndercurrent: 'Arabic music carries political weight — Palestinian resistance songs, Lebanese civil war music, Egyptian revolutionary chants (2011), and Gulf national identity songs all demonstrate music\'s political function. Censorship varies dramatically by country.',
    implicitReferences: [
      'exile and displacement themes reflecting Palestinian and Syrian experiences',
      'Gulf modernization and tradition tension in khaleeji pop',
      'Egyptian economic frustration in mahraganat\'s street-level perspective',
      'Lebanese resilience narratives in Beirut\'s music scene',
      'pan-Arab unity aspirations in golden-age tarab\'s cross-regional appeal',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Arabic music\'s intertextual web is anchored by a sacred canon — Umm Kulthum, Fairuz, Abdel Halim Hafez, and Mohammed Abdel Wahab represent a cultural heritage as revered as classical literature.',
    canonKnowledge: 'Umm Kulthum is the undisputed center — her recordings are treated as sacred texts. Fairuz represents Lebanese refinement. Abdel Halim Hafez embodies Egyptian romantic cinema. Mohammed Abdel Wahab is the composer-innovator. These figures are not just musicians but cultural monuments.',
    samplingTradition: 'Direct sampling of golden-age recordings is sensitive — treated with reverence or controversy. Mahraganat producers sample local songs freely. Modern Arabic pop interpolates classic melodies. Maqam patterns are inherently shared vocabulary.',
    quotationPractice: 'Quoting Umm Kulthum melodic phrases signals respect and lineage. Fairuz songs are covered in Lebanese pop as cultural continuity. Maqam modulation patterns from canonical recordings are replicated as structural homage.',
    expectedReferences: [
      'Umm Kulthum\'s "Enta Omri" as the ultimate tarab reference',
      'Fairuz\'s "Li Beirut" as Lebanese cultural anthem',
      'Abdel Halim Hafez\'s romantic film songs as Egyptian pop touchstone',
      'Abdel Wahab\'s compositional innovations as modernization reference',
      'Sheikh Imam\'s protest songs as political music touchstone',
    ],
    lineageSignifiers: [
      'specific maqam modulation patterns traced to golden-age compositions',
      'takht ensemble instrumentation as classical tradition marker',
      'vocal ornament style referencing specific regional schools',
      'oud taqsim style as indicator of training lineage',
      'poetic meter and rhyme schemes inherited from classical Arabic poetry',
      'recording at specific Cairo studios as prestige signifier',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Gender conventions in Arabic music vary enormously across the region\'s 22 countries and multiple sub-genres. Historical figures like Umm Kulthum and Fairuz held positions of extraordinary cultural authority. Contemporary conventions reflect both tradition and rapid social change.',
    vocalGenderCodes: 'Female voices in tarab tradition command through power and ornamental mastery (Umm Kulthum\'s authority is unmatched in any genre). Male voices range from Mohammed Abdel Wahab\'s refined tenor to Abdel Halim\'s emotional romanticism. Gulf and Levantine pop have distinct male and female vocal aesthetics.',
    physicalityInPerformance: 'Traditional tarab performance is vocally centered — minimal movement, maximum vocal expression. Male and female performers in traditional contexts are distinguished by vocal approach rather than physical presentation. Modern pop increasingly follows global visual performance trends.',
    genderNarratives: 'Classical Arabic poetry addressed the beloved in gender-fluid terms. Modern Arabic pop has distinct male and female lyrical perspectives — men often express pursuit and devotion, women express longing and emotional power. Regional variation is significant.',
    subversionExamples: [
      'Umm Kulthum\'s unparalleled cultural authority in a patriarchal society through sheer artistic mastery',
      'Fairuz\'s persona transcending conventional gender roles through artistic gravitas',
      'mahraganat\'s inclusion of female DJs and producers in Cairo\'s street music scene',
      'Lebanese pop stars navigating between conservative expectations and cosmopolitan expression',
      'female raï singers (Cheba Zahouania, Rimitti) claiming space in male-dominated Algerian music',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Arabic music often operates outside fixed tempo — tarab performances accelerate and decelerate based on emotional intensity. Even when a tempo is established, the ornamental nature of the music makes BPM a poor descriptor of the felt experience.',
    psychologicalTempo: 'A tarab performance at 80 BPM can feel timeless — the long vocal phrases and ornamental passages create a sense of suspended time. Dabke at 140 BPM feels faster than Western pop at the same tempo due to the stomping physicality. Mahraganat at 120 BPM feels frenetic due to dense percussion.',
    weightAndMomentum: 'The emotional weight of Arabic music exceeds what its tempo suggests. A slow mawwal carries enormous gravity. The acceleration pattern in Sufi dhikr and hadra creates momentum that transcends tempo — the music feels like it is pulling the listener forward.',
    urgencyScale: 'Tarab creates urgency through emotional intensification, not tempo increase. Dabke is physically urgent. Mahraganat is energetically chaotic. Arabic ballads can create more urgency at 70 BPM than many genres achieve at 140.',
    comparisonToSameBPM: 'Arabic music at any given BPM feels entirely different from Western music at the same tempo because the ornamental timing, maqam-based melodic framework, and heterophonic texture create a temporal experience that the BPM number cannot capture.',
  },

  mistakeConventions: {
    overview: 'In traditional Arabic music, the concept of "mistake" is nuanced — a maqam modulation that loses the listener is a serious error, but ornamental variation that stretches timing is artistry. The distinction is between structural failure and expressive freedom.',
    toleratedImperfections: [
      'timing variation in ornamental passages — this is expression, not error',
      'microtonal intonation variation within maqam — this is personal style',
      'ensemble heterophonic timing differences — this creates the shimmering texture',
      'live recording ambient noise in golden-age tarab — audience sounds are part of the document',
    ],
    celebratedFlaws: [
      'mahraganat\'s deliberately rough, lo-fi production aesthetic',
      'shaabi vocal rawness as street authenticity',
      'tarab singer\'s emotional vocal break at moments of peak intensity',
      'raï\'s raw, unpolished vocal delivery as rebellion marker',
    ],
    overproductionRisks: [
      'auto-tuning vocals to equal temperament — destroying the maqam microtonal intervals',
      'quantizing traditional rhythmic patterns to a Western grid',
      'replacing heterophonic texture with Western-style harmony',
      'compressing the dynamic range that tarab performance requires',
      'electronic production obscuring the oud and voice\'s acoustic intimacy',
    ],
    authenticRoughness: 'Essential in shaabi, mahraganat, and raï — polish would strip these genres of their identity. Unacceptable in tarab (technical mastery is mandatory) and khaleeji pop (production quality reflects Gulf investment). The roughness question maps directly to class and region.',
  },

  referenceTracks: [
    {
      title: 'Bayen Habeit',
      artist: 'Amr Diab',
      year: 2022,
      whyExemplary: 'The godfather of Arabic pop continued to set the standard for polished Mediterranean-influenced Arab pop — his melodic instincts remain the benchmark for the entire region.',
      structuralNotes: 'Classic Amr Diab structure with a keyboard/guitar intro establishing the maqam, conversational verses, and a soaring chorus melody designed for stadium singalongs.',
      craftHighlight: 'The melody moves through Maqam Nahawand with chromatic passing tones borrowed from Western pop, creating a hybrid scale that sounds both authentically Arabic and internationally accessible.',
    },
    {
      title: 'Bint El Geran',
      artist: 'Amr Diab',
      year: 2021,
      whyExemplary: 'One of the most-streamed Arabic songs globally, proving that Amr Diab\'s formula of maqam-based pop melody over modern production remains commercially dominant after four decades.',
      structuralNotes: 'Tight pop structure under 4 minutes with an immediately recognizable intro hook, two verses, and a chorus that lifts the melody into a higher register. The bridge features an oud-influenced guitar solo.',
      craftHighlight: 'The chorus melody descends through a Hijaz-inflected scale over a major-key chord progression, creating the bittersweet emotional tension that defines Arabic pop at its best.',
    },
    {
      title: 'Hobak Saab',
      artist: 'Mohamed Hamaki',
      year: 2022,
      whyExemplary: 'Hamaki\'s emotional ballad demonstrated that the Egyptian romantic pop tradition — direct, passionate, orchestral — still commands massive audiences across the Arabic-speaking world.',
      structuralNotes: 'Orchestral ballad with a string-led intro, two narrative verses building emotional intensity, and a chorus that opens into a wide melodic interval expressing yearning.',
      craftHighlight: 'The vocal melody in the chorus spans nearly two octaves, using the extreme range to physically convey the emotional extremity of the lyrics — the voice strains because the heart strains.',
    },
    {
      title: 'Enta Eih',
      artist: 'Nancy Ajram',
      year: 2022,
      whyExemplary: 'Nancy Ajram\'s return to form blended her signature Lebanese pop clarity with updated production, maintaining her position as the leading female voice in commercial Arabic pop.',
      structuralNotes: 'Lebanese pop structure with a dramatic intro, verse-chorus alternation, and a mawal-influenced vocal improvisation section before the final chorus.',
      craftHighlight: 'The mawal section — semi-improvised vocal melisma over sustained chords — bridges classical Arabic vocal tradition and pop form, allowing the singer to demonstrate both technique and emotion.',
    },
    {
      title: 'Mesh Maakool',
      artist: 'Elissa',
      year: 2023,
      whyExemplary: 'Elissa\'s emotive power ballad showcased the Lebanese diva tradition — technically demanding vocal performance married to lush orchestral production and poetically dense lyrics.',
      structuralNotes: 'Slow-build ballad with an a cappella opening line, gradual orchestral accumulation through the verse, and a chorus that releases into full production with strings, oud, and percussion.',
      craftHighlight: 'The opening a cappella line establishes the maqam without any harmonic context, requiring the vocalist to define the tonal center through melody alone — a test of musical authority.',
    },
    {
      title: 'Salimuli Alayh',
      artist: 'Hussain Al Jassmi',
      year: 2022,
      whyExemplary: 'The Emirati superstar\'s khaleeji pop blended Gulf traditional melodic patterns with contemporary production, representing the Gulf\'s distinct contribution to Arabic pop.',
      structuralNotes: 'Khaleeji structure with a sawt-influenced rhythmic pattern, extended melodic phrases in the verse, and a chorus built around a call-and-response pattern.',
      craftHighlight: 'The rhythmic pattern references the traditional Gulf sawt genre while the production is unmistakably modern — cultural specificity encoded in rhythm rather than just melody.',
    },
    {
      title: 'Tab Leh',
      artist: 'Sherine Abdel-Wahab',
      year: 2022,
      whyExemplary: 'Sherine\'s vocal emotional intensity — the ability to sound like she\'s about to cry at any moment — represents the Egyptian tarab tradition adapted for pop consumption.',
      structuralNotes: 'Egyptian pop-ballad structure with a piano intro, two emotionally building verses, and a chorus that explodes into orchestral fullness. A spoken-word section adds dramatic weight.',
      craftHighlight: 'Sherine\'s vocal timbre naturally contains a quality Arabs call "shakwa" (complaint/lament) — the voice itself carries the emotion before the lyrics do, which is the essence of tarab.',
    },
    {
      title: 'Habibi',
      artist: 'Ramy Gamal',
      year: 2023,
      whyExemplary: 'Egypt\'s rising romantic voice delivered a modern take on the classic Arabic love song that found massive streaming success across the Gulf and North Africa.',
      structuralNotes: 'Clean, modern production with guitar-driven verses and a synth-enhanced chorus. The structure follows Western pop form but the melodic content is rooted in Maqam Bayati.',
      craftHighlight: 'The use of Maqam Bayati — with its characteristic half-flat second degree — gives the melody an emotional quality that Western major/minor scales cannot replicate.',
    },
    {
      title: 'Jaw',
      artist: 'Wegz',
      year: 2023,
      whyExemplary: 'Egypt\'s biggest rap star crossed mahraganat street energy with mainstream pop melody, creating a new hybrid that dominates Arabic streaming platforms.',
      structuralNotes: 'Trap-influenced production with an Arabic melodic hook over 808 bass. Short, punchy sections designed for TikTok virality while maintaining a complete narrative arc.',
      craftHighlight: 'The Egyptian Arabic dialect\'s natural rhythmic patterns — consonant clusters and glottal stops — create a percussive flow that is impossible to replicate in other Arabic dialects.',
    },
    {
      title: 'Hayda Haki',
      artist: 'Najwa Karam',
      year: 2022,
      whyExemplary: 'The "Sun of Song" demonstrated that the Lebanese dabke-pop tradition remains vital, delivering a dance track rooted in Levantine folk rhythm with modern production sheen.',
      structuralNotes: 'Dabke-influenced structure with a driving 6/8 rhythmic pattern, call-and-response verses, and a chorus designed for group dancing and collective vocal participation.',
      craftHighlight: 'The 6/8 dabke rhythm is maintained through electronic production without losing its organic, communal dance-floor feel — the groove is programmed but feels played.',
    },
    {
      title: 'Sah Sah',
      artist: 'Mohamed Ramadan',
      year: 2022,
      whyExemplary: 'Egypt\'s mahraganat-to-mainstream crossover star delivered a track that brought Cairo street music production into high-budget Arabic pop without sanitizing it.',
      structuralNotes: 'Mahraganat structure with a pulsing electronic beat, Auto-Tuned vocal hooks, and short verse sections. The energy is relentless with no ballad moments or dynamic valleys.',
      craftHighlight: 'The Auto-Tune is used not as pitch correction but as a timbral effect that connects to the mahraganat aesthetic — the digital artifact is the genre\'s sonic signature.',
    },
    {
      title: 'Leily Nahary',
      artist: 'Amr Diab',
      year: 2023,
      whyExemplary: 'Another Amr Diab entry because his consistency in crafting Arabic pop melodies across five decades is itself an exemplary achievement in the genre.',
      structuralNotes: 'Uptempo pop with a guitar-driven groove, verse-chorus-verse-chorus-bridge-chorus form. The bridge introduces a key change that lifts the final chorus emotionally.',
      craftHighlight: 'The key change in the bridge is a Western pop technique applied to a maqam-based melody — the modulation preserves the maqam\'s intervallic character in the new key center.',
    },
    {
      title: 'Ahwak',
      artist: 'Balqees',
      year: 2023,
      whyExemplary: 'The Emirati-Yemeni singer bridged Gulf and Levantine pop traditions, creating a pan-Arab sound that resonated across regional boundaries.',
      structuralNotes: 'Pop-ballad structure with a cinematic orchestral arrangement. The verse melody sits in a low, intimate register; the chorus opens into a wide, declarative range.',
      craftHighlight: 'Balqees\'s vocal ornamentation draws from Yemeni folk singing tradition — rapid melismatic turns that are distinct from Egyptian or Lebanese ornamental styles, adding regional specificity.',
    },
    {
      title: 'Moshta\'alak',
      artist: 'Majid Al Mohandis',
      year: 2022,
      whyExemplary: 'The Iraqi-Saudi crossover artist demonstrated the emotional depth of Iraqi maqam-influenced pop, a tradition distinct from both Egyptian and Lebanese mainstream.',
      structuralNotes: 'Iraqi pop structure with extended melodic phrases that resist the short-hook approach of Egyptian pop. Verses are longer and more melodically complex than choruses.',
      craftHighlight: 'The Iraqi vocal tradition of sustaining notes with a wide, slow vibrato creates a sense of emotional vastness that quick, ornamental styles cannot — space as an emotional device.',
    },
    {
      title: 'El Ghorba',
      artist: 'Saad Lamjarred',
      year: 2022,
      whyExemplary: 'Morocco\'s biggest pop export delivered a song about exile that connected Maghreb diaspora communities worldwide, using North African melodic patterns over global pop production.',
      structuralNotes: 'Maghreb pop structure with Gnawa-influenced bass patterns, chaabi rhythmic accents, and a chorus melody that blends Andalusian maqam patterns with French chanson phrasing.',
      craftHighlight: 'The lyrical theme of "ghorba" (exile/alienation) is a foundational Arabic literary concept, and the melody\'s unresolved phrases physically convey the emotional state of not-arriving.',
    },
    {
      title: 'Kan Lamma',
      artist: 'Assala Nasri',
      year: 2023,
      whyExemplary: 'The Syrian diva\'s powerful vocal instrument applied to a dramatic pop ballad reminded audiences that the Levantine vocal tradition carries unmatched emotional intensity.',
      structuralNotes: 'Power ballad structure with a quiet piano intro, building through strings and percussion to a climactic final chorus. The dynamic range is extreme — whisper to full-voiced belting.',
      craftHighlight: 'Assala\'s ability to shift from a whisper to a belt within a single phrase, without losing tonal quality, demonstrates the classical training foundation that separates Arabic pop divas from imitators.',
    },
    {
      title: 'Aleik Oyoun',
      artist: 'Nassif Zeytoun',
      year: 2023,
      whyExemplary: 'The Syrian-Lebanese artist\'s romantic track dominated streaming with a contemporary production style that modernized Levantine pop without stripping its melodic identity.',
      structuralNotes: 'Modern Levantine pop with electronic production, verse-chorus form, and a pre-chorus build that uses filtering and rhythmic anticipation to create tension before the chorus drop.',
      craftHighlight: 'The vocal melody in the chorus uses the augmented second interval characteristic of Maqam Hijaz, marking the song as specifically Arabic even within a globally-influenced production context.',
    },
    {
      title: 'Ya Leil',
      artist: 'Fadl Shaker',
      year: 2023,
      whyExemplary: 'Shaker\'s comeback demonstrated that the classic Lebanese romantic vocal style — rich, warm baritone with controlled ornamentation — still resonates with modern audiences.',
      structuralNotes: 'Classical Arabic pop form with an extended instrumental introduction establishing mood, two narrative verses, and a chorus that functions as an emotional declaration rather than a hook.',
      craftHighlight: 'Shaker\'s baritone occupies a rare register in Arabic pop — most male stars are tenors — and his lower vocal range creates an intimacy and warmth that higher voices cannot achieve.',
    },
    {
      title: 'Bent El Sultan',
      artist: 'Cairokee',
      year: 2022,
      whyExemplary: 'Egypt\'s leading rock band delivered politically charged lyrics over Arabic rock arrangements, maintaining the protest music tradition that defined post-2011 Egyptian culture.',
      structuralNotes: 'Rock structure with verse-chorus-bridge form, electric guitar riffs, and a collective chant chorus designed for crowd participation at concerts and protests.',
      craftHighlight: 'The lyrics use metaphor and allegory to convey political commentary — a necessity in Egyptian artistic expression — where "the sultan\'s daughter" stands for the unattainable promise of the state.',
    },
    {
      title: 'Hadal Ahbek',
      artist: 'Issam Alnajjar',
      year: 2021,
      whyExemplary: 'The Jordanian artist\'s TikTok-viral hit brought Arabic pop to a global Gen-Z audience, with a melody that crossed cultural barriers despite being entirely in Arabic.',
      structuralNotes: 'Short, loop-based pop structure optimized for streaming and social media. The chorus melody is the entire song — everything else exists to set it up and return to it.',
      craftHighlight: 'The melody\'s pentatonic backbone makes it singable for non-Arabic speakers, while the ornamental turns and quarter-tone inflections mark it as unmistakably Middle Eastern.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: [
      'Arabic', 'maqam', 'oud',
      'darbuka', 'Middle Eastern', 'tarab',
      'Arabic vocals', 'ornamental melody',
    ],
    avoidKeywords: [
      'country', 'bluegrass', 'K-Pop',
      'heavy metal', 'reggaeton', 'Celtic',
    ],
    promptTemplate: '[sub-genre] Arabic music, [BPM] BPM, [maqam if known], [mood], [key instruments], Arabic vocals, [regional reference]',
    tips: [
      'Specify the regional style: Egyptian, Lebanese, Gulf, Maghrebi — each sounds distinct.',
      'Name the maqam if possible: Bayati for melancholy, Hijaz for drama, Rast for brightness.',
      'Include "oud" and "darbuka" as foundational instruments.',
      'For mahraganat: "electronic", "auto-tune", "Cairo street", "frenetic energy".',
    ],
  },
};
