import type { GenreGuide } from './types';

export const BLUES_GUIDE: GenreGuide = {
  id: 'blues',
  name: 'Blues',
  language: 'English',

  sonicPalette: {
    overview: 'Raw, expressive, and deeply human. The blues is the root of nearly all American popular music. Built on simple structures played with maximum feeling — bent notes, rough tones, and the space between the notes define the sound.',
    timbre: [
      'Overdriven electric guitar with sustain and feedback',
      'Acoustic guitar (resonator, steel-string)',
      'Harmonica (diatonic, cross-harp technique)',
      'Hammond organ or piano',
      'Warm, round bass',
      'Shuffled drums with brushes or sticks',
      'Raw, emotive vocals',
      'Slide guitar (bottleneck)',
    ],
    texture: 'Sparse and open — the blues breathes. Space between notes is as important as the notes themselves. The texture is warm and organic, with natural room sound and analog warmth.',
    tonality: 'Blues tonality defies major/minor classification — the "blue notes" (flat 3rd, flat 5th, flat 7th) create the characteristic sound. Keys of E, A, G, D, and B are most common (guitar-friendly).',
    signatureSounds: [
      'Guitar string bends (half-step and full-step)',
      'Slide guitar glissando',
      'Harmonica wails and bends',
      'Turnaround lick at the end of a 12-bar cycle',
      'Tremolo and vibrato on sustained notes',
      'Call-and-response between voice and guitar',
      'Walking bass lines',
    ],
  },

  rhythmAndGroove: {
    overview: 'Shuffled, swinging, and deeply felt. The blues shuffle is one of the most recognizable rhythmic patterns in music — a swung triplet feel that gives the music its characteristic lilt and drive.',
    bpmRange: { min: 60, max: 140, sweet: 100 },
    feel: 'Swinging and laid-back — the groove should feel like it\'s carrying you along. Even uptempo blues maintains a relaxed confidence. Slow blues is heavy and deliberate.',
    swing: 'Heavy — the blues shuffle (swung 8th notes with triplet feel) is foundational. Straight 8ths used in some modern blues-rock but traditional blues always swings.',
    syncopation: 'Moderate — vocal phrases anticipate or lag behind the beat. Guitar fills play between vocal phrases. The bass walks steadily while everything else moves freely around it.',
    grooveArchetype: 'Shuffled 12-bar, slow blues drag, or boogie drive',
    rhythmicSignatures: [
      'Shuffle rhythm (swung 8th notes, triplet feel)',
      'Walking bass line (quarter notes ascending/descending)',
      'Brushed snare shuffles',
      'Boogie-woogie bass pattern (8th note ostinato)',
      'Slow blues with triplet fills',
      'Stop-time breaks (band drops out for vocal/guitar)',
      'Rumba blues feel (Latin-influenced)',
    ],
  },

  harmonicLanguage: {
    overview: 'The 12-bar blues is the foundation — I-IV-V in its most elemental form. But within this simple framework, the blues uses "blue notes" and chord substitutions to create infinite emotional variation.',
    scales: ['Blues Scale', 'Minor Pentatonic', 'Major Pentatonic', 'Mixolydian', 'Dorian'],
    chordProgressions: [
      'I7 – IV7 – I7 – I7 – IV7 – IV7 – I7 – I7 – V7 – IV7 – I7 – V7 (12-bar blues)',
      'I7 – IV7 – I7 – V7 (quick-change blues)',
      'i7 – iv7 – i7 – V7 (minor blues)',
      'I7 – I7 – IV7 – IV7 – I7 – V7 (8-bar blues)',
      'Jazz-blues with ii-V substitutions',
      'I7 – #IVdim7 – I7/V (chromatic passing)',
    ],
    harmonyNotes: 'Dominant 7th chords on every degree — the I7 chord defines the blues sound (mixing major and minor). The blue notes (b3, b5, b7) create tension and emotional color. 9th and 13th chords add sophistication.',
    modality: 'Simultaneously major and minor — the blue notes create an ambiguous tonality that expresses joy and sorrow at once. This tonal ambiguity IS the blues.',
  },

  songStructure: {
    overview: 'The 12-bar blues is the template — simple, cyclical, and endlessly adaptable. Each 12-bar cycle is a miniature emotional journey. Verse-based with instrumental breaks.',
    form: '12-bar blues cycles with vocal verses and instrumental solos',
    sections: ['Intro', 'Verse 1 (12 bars)', 'Verse 2 (12 bars)', 'Solo/Instrumental (12+ bars)', 'Verse 3', 'Solo', 'Final Verse', 'Outro/Turnaround'],
    arrangement: 'Cyclical — the 12-bar form repeats with different lyrics and solos. Energy builds through the song. Solos alternate with verses. The final verse is often the emotional climax.',
    introOutro: 'Intros: guitar riff, turnaround lick, or count-in. Outros: extended turnaround, final chord with vibrato, or fade on a repeated riff. The turnaround connects each cycle.',
    barLengths: '12 bars per verse/cycle (occasionally 8 or 16). Song length varies (3-7 minutes). Extended solos in live performance.',
    hookPlacement: 'The lyrical hook is the first line of each verse (repeated twice in AAB form). The turnaround guitar lick serves as an instrumental hook.',
  },

  vocalDelivery: {
    overview: 'The blues voice is the sound of lived experience — rough, honest, and unadorned. Blues vocal style prizes emotional truth over technical perfection. Every crack, moan, and growl tells the story.',
    phrasing: 'Behind the beat — phrases land late, creating a laid-back, world-weary feel. AAB lyric form: the first line is stated, repeated (with variation), and resolved with a contrasting third line.',
    affect: 'Deeply emotional — pain, longing, resignation, dark humor, defiance, and occasional joy. The blues communicates the full human emotional spectrum with unflinching honesty.',
    techniques: [
      'Growling and moaning',
      'Falsetto cries and whoops',
      'Melismatic bending of notes',
      'Spoken word passages',
      'Call-and-response with guitar',
      'Humming and wordless vocalizing',
      'Talk-singing (conversational delivery)',
      'Field holler (raw, unaccompanied crying out)',
    ],
    adlibStyle: 'Organic interjections — "well, well, well," "oh yeah," "Lord have mercy," "I said." Moans and hums between phrases. The guitar "answers" the voice.',
    harmony: 'Minimal — blues is typically solo voice. When harmony appears, it\'s unison or simple call-and-response. Gospel-influenced harmony in some styles. Backup singers rare in traditional blues.',
    grit: 'Maximum — the rougher, the more authentic. Blues vocals should sound lived-in, weathered, and real. Perfect pitch and smooth tone are not the goal. Character is everything.',
  },

  lyricalConventions: {
    overview: 'AAB form — state the problem, repeat it for emphasis, resolve or comment. Blues lyrics distill complex emotions into vivid, everyday language. Dark humor and double entendre are essential tools.',
    themes: [
      'Heartbreak and betrayal',
      'Hard times and poverty',
      'Travel and restlessness',
      'Desire and sexuality (often coded)',
      'Supernatural and hoodoo',
      'Drinking and self-destruction',
      'Defiance and resilience',
      'Loneliness and isolation',
    ],
    perspective: 'First person confessional — "I" telling my story. Direct, honest, autobiographical (or character-driven). The singer IS the narrator.',
    figurativeLanguage: 'Concrete, vivid, earthy. Double entendres (sexual/non-sexual meanings). Animal metaphors (black cat, mojo hand). Weather as emotional state. Train and road imagery for life\'s journey.',
    vocabulary: 'Vernacular, colloquial, Southern Black American English. Simple, powerful words. Slang and idiom. The vocabulary is specific to time and place.',
    storytellingApproach: 'AAB verse form — first line states the condition, second line repeats for emphasis, third line resolves or adds a twist. Each verse is self-contained but builds the emotional arc.',
    cliches: [
      'Woke up this morning',
      'My baby done left me',
      'Going down to the crossroads',
      'Got the blues so bad',
      'Mean old world',
      'Hellhound on my trail',
    ],
  },

  productionFingerprint: {
    overview: 'Raw and unprocessed — blues production captures the performance, not the production. The sound should feel live, present, and immediate. Minimal overdubbing and processing.',
    mixAesthetic: 'Live, room-filled sound. Vocal and guitar equally prominent. Natural reverb from the recording space. Warm, analog character. Not over-compressed. Dynamic range preserved.',
    era: 'Classic blues recording techniques (analog, live-to-tape) still define the ideal. Modern blues maintains this aesthetic while using contemporary recording technology.',
    signalChain: 'Guitar: guitar → tube amp (small Fender combo) → room mic. Vocals: dynamic mic, minimal processing. Drums: room mics, natural sound. Everything should sound like a great club gig.',
    modernTrends: 'Modern blues revival artists maintain vintage aesthetics. Blues-rock crossover with higher production values. Lo-fi blues recording. Digital recording mimicking analog warmth.',
  },

  instrumentation: {
    coreInstruments: [
      'Electric guitar (Stratocaster, Telecaster, Les Paul, ES-335)',
      'Acoustic guitar (steel-string, resonator)',
      'Harmonica (diatonic)',
      'Bass guitar or upright bass',
      'Drums (with brushes option)',
      'Piano or Hammond organ',
      'Vocals',
    ],
    signatureSounds: [
      'Strat neck pickup clean-to-overdrive',
      'Slide guitar (glass or metal bottleneck)',
      'Cross-harp harmonica bends',
      'Walking bass line',
      'Shuffled brush pattern',
      'Tremolo guitar effect',
      'Piano boogie patterns',
    ],
    layering: 'Minimal — blues arrangements are sparse. Guitar, bass, drums, and voice form the core. Add harmonica, organ, or piano for color. Never overcrowd the arrangement.',
    avoidInstruments: [
      'Synthesizers (traditional blues)',
      'Electronic drums',
      'Auto-Tune',
      'Orchestral arrangements',
      'Heavy effects processing',
    ],
  },

  culturalContext: {
    overview: 'The blues is the root of American popular music — the original voice of the African American experience. Born from slavery, segregation, and struggle, the blues turned pain into art and became the foundation for jazz, rock, R&B, hip-hop, and country.',
    origin: 'Mississippi Delta, late 19th century. Emerged from field hollers, work songs, spirituals, and African musical traditions. First recordings in the 1920s.',
    identity: 'African American cultural expression — the blues tells the story of Black life in America with unflinching honesty. The music is communal, cathartic, and deeply personal.',
    community: 'Juke joints, blues clubs, and festivals. The Chitlin\' Circuit. Regional scenes (Chicago, Mississippi Delta, Texas, Piedmont). Modern blues festival culture.',
    socialFunction: 'Emotional catharsis — turning suffering into art. Community bonding through shared experience. Dance music for juke joints. Storytelling tradition.',
    authenticityMarkers: [
      'Emotional honesty and lived experience',
      'Guitar and vocal mastery',
      'Connection to blues tradition',
      'Ability to play with feeling over technique',
      'Understanding of blues form and language',
    ],
  },

  historicalLineage: {
    overview: 'From cotton fields to Chicago clubs to global influence, the blues is the mother of modern popular music.',
    roots: ['African Music', 'Field Hollers', 'Work Songs', 'Spirituals', 'Folk'],
    evolution: 'Delta blues (1900s-1930s) → Country blues spread (30s-40s) → Electric Chicago blues (40s-50s) → Texas blues (50s-60s) → Blues-rock fusion (60s-70s) → Modern blues revival (2000s-present).',
    keyEras: [
      '1900-1930: Delta blues origins (Robert Johnson, Charlie Patton)',
      '1920-1940: Classic blues and country blues',
      '1940-1960: Electric Chicago blues (Muddy Waters, Howlin\' Wolf)',
      '1950-1970: Texas blues (T-Bone Walker, Albert King)',
      '1960-1975: British blues revival (influence on rock)',
      '2000-present: Modern blues revival and preservation',
    ],
    influencedBy: ['African Music', 'Spirituals', 'Work Songs', 'Folk'],
    influenced: ['Jazz', 'Rock and Roll', 'R&B', 'Soul', 'Funk', 'Country', 'Hip-Hop'],
  },

  subGenres: [
    {
      name: 'Delta Blues',
      description: 'The original — raw, acoustic blues from the Mississippi Delta. Solo voice and guitar in their most primal form.',
      distinguishingFeatures: ['Solo acoustic guitar and voice', 'Slide guitar technique', 'Raw, unpolished recording', 'Deeply personal expression', 'Rhythmic complexity from a single player'],
      bpmRange: { min: 60, max: 120 },
      keyArtists: ['Robert Johnson', 'Son House', 'Charlie Patton', 'Skip James', 'R.L. Burnside'],
      productionNotes: 'Minimal — solo voice and guitar. Lo-fi, raw recording aesthetic. Room sound. No overdubbing. Capture the performance.',
      lyricNotes: 'Personal struggle, supernatural themes, travel, love. AAB form. Deeply personal and metaphorical.',
      sunoPromptKeywords: ['Delta blues', 'acoustic blues', 'Mississippi blues', 'raw', 'slide guitar', 'solo blues', 'roots'],
    },
    {
      name: 'Chicago Blues',
      description: 'Electric, amplified blues from the South Side of Chicago. Full band with electric guitar, harmonica, bass, drums, and piano.',
      distinguishingFeatures: ['Electric guitar through tube amp', 'Full band arrangement', 'Amplified harmonica', 'Urban energy', 'Strong rhythm section'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Muddy Waters', 'Howlin\' Wolf', 'Buddy Guy', 'Little Walter', 'Willie Dixon'],
      productionNotes: 'Electric guitar through tube amp with overdrive. Amplified harmonica. Full rhythm section. Urban, energetic sound. Room ambience.',
      lyricNotes: 'Urban life, migration, love, drinking, trouble. Electrified emotion. Direct and powerful.',
      sunoPromptKeywords: ['Chicago blues', 'electric blues', 'urban blues', 'amplified', 'harmonica blues', 'club blues'],
    },
    {
      name: 'Texas Blues',
      description: 'Guitar-hero blues from Texas — cleaner tones, more swing, and jazzy sophistication. Emphasis on guitar virtuosity and showmanship.',
      distinguishingFeatures: ['Clean-to-overdrive guitar tone', 'Jazz-influenced phrasing', 'Horn section optional', 'Swing and shuffle feels', 'Guitar virtuosity'],
      bpmRange: { min: 80, max: 140 },
      keyArtists: ['Stevie Ray Vaughan', 'T-Bone Walker', 'Albert Collins', 'Freddie King', 'Johnny Winter'],
      productionNotes: 'Clean Fender tone with edge. Texas shuffle feel. Possible horn section. Jazzy sophistication. Guitar is the star.',
      lyricNotes: 'Texas pride, love, trouble, road life. Confident and swaggering delivery.',
      sunoPromptKeywords: ['Texas blues', 'Stevie Ray Vaughan', 'guitar blues', 'shuffle', 'Fender tone', 'blues guitar hero'],
    },
    {
      name: 'Electric Blues',
      description: 'Broad category encompassing all amplified, electric guitar-driven blues. The modernization of acoustic blues traditions.',
      distinguishingFeatures: ['Electric guitar as primary instrument', 'Full band arrangement', 'Amplified sound', 'Various regional styles', 'Modern blues vocabulary'],
      bpmRange: { min: 70, max: 140 },
      keyArtists: ['B.B. King', 'Albert King', 'Buddy Guy', 'John Lee Hooker', 'Albert Collins'],
      productionNotes: 'Electric guitar with character. Full rhythm section. Clean recording with warmth. Various production levels from raw to polished.',
      lyricNotes: 'Universal blues themes. Love, loss, trouble, celebration. Updated for contemporary audiences.',
      sunoPromptKeywords: ['electric blues', 'modern blues', 'blues band', 'guitar blues', 'amplified blues'],
    },
    {
      name: 'Blues Rock',
      description: 'The intersection of blues feeling with rock energy. Heavier distortion, louder dynamics, and rock song structures with blues soul.',
      distinguishingFeatures: ['Heavier guitar distortion', 'Rock energy and volume', 'Blues-based riffs and solos', 'Louder, more aggressive', 'Rock song structures with blues harmony'],
      bpmRange: { min: 100, max: 160 },
      keyArtists: ['Jimi Hendrix', 'Cream', 'Led Zeppelin', 'Gary Clark Jr.', 'The Black Keys'],
      productionNotes: 'Heavier distortion than traditional blues. Rock-level volume and energy. Blues riffs and scales over rock dynamics. Can be raw or polished.',
      lyricNotes: 'Blues themes with rock attitude. More abstract and poetic than traditional blues. Freedom, desire, rebellion.',
      sunoPromptKeywords: ['blues rock', 'heavy blues', 'rock blues', 'Hendrix', 'distorted blues', 'blues power'],
    },
    {
      name: 'Jump Blues',
      description: 'Uptempo, big-band-influenced blues designed for dancing. The bridge between swing jazz and rock and roll.',
      distinguishingFeatures: ['Uptempo, danceable rhythms', 'Horn section (saxophone prominent)', 'Boogie-woogie piano', 'Energetic, celebratory mood', 'Swing influence'],
      bpmRange: { min: 130, max: 180 },
      keyArtists: ['Louis Jordan', 'Big Joe Turner', 'Wynonie Harris', 'T-Bone Walker'],
      productionNotes: 'Uptempo swing/shuffle. Prominent saxophone and horns. Boogie-woogie piano. High energy. Dance-floor focus.',
      lyricNotes: 'Party, dancing, humor, good times. Light-hearted and fun. Double entendres and wit.',
      sunoPromptKeywords: ['jump blues', 'swing blues', 'boogie', 'uptempo blues', 'saxophone blues', 'danceable', 'jive'],
    },
    {
      name: 'Piedmont Blues',
      description: 'Fingerpicking acoustic blues from the Southeast US. Intricate guitar patterns combining bass line and melody simultaneously.',
      distinguishingFeatures: ['Fingerpicking technique', 'Alternating bass patterns', 'Ragtime influence', 'East Coast style', 'Melodic, intricate playing'],
      bpmRange: { min: 80, max: 120 },
      keyArtists: ['Blind Blake', 'Rev. Gary Davis', 'Elizabeth Cotten', 'Etta Baker'],
      productionNotes: 'Solo acoustic guitar. Fingerpicking clearly audible. Minimal accompaniment. Natural room sound. Precision in recording.',
      lyricNotes: 'East Coast perspective. Ragtime-influenced wit. Lighter themes alongside traditional blues subjects.',
      sunoPromptKeywords: ['Piedmont blues', 'fingerpicking blues', 'ragtime blues', 'acoustic', 'East Coast blues', 'intricate'],
    },
    {
      name: 'British Blues',
      description: 'Blues interpreted through British musicians who brought intensity and rock energy to the American tradition, sparking the global blues-rock revolution.',
      distinguishingFeatures: ['British interpretation of American blues', 'Rock influence and energy', 'Higher production values', 'Guitar hero culture', 'Blues revival energy'],
      bpmRange: { min: 80, max: 150 },
      keyArtists: ['Eric Clapton', 'John Mayall', 'Peter Green', 'Rory Gallagher', 'Jeff Beck'],
      productionNotes: 'Studio production values with blues feel. Marshall amp tones. Full band arrangements. Blues with rock energy and volume.',
      lyricNotes: 'American blues themes through British lens. Cover versions and original material. Respectful interpretation.',
      sunoPromptKeywords: ['British blues', 'blues revival', 'UK blues', 'Clapton', 'blues guitar', 'rock blues'],
    },
    {
      name: 'Modern Blues',
      description: 'Contemporary blues that maintains tradition while incorporating modern production and cross-genre influences.',
      distinguishingFeatures: ['Contemporary production values', 'Cross-genre influences (hip-hop, soul, rock)', 'Updated themes and perspectives', 'Diverse artists', 'Traditional meets modern'],
      bpmRange: { min: 60, max: 140 },
      keyArtists: ['Gary Clark Jr.', 'Fantastic Negrito', 'Christone "Kingfish" Ingram', 'Samantha Fish', 'Marcus King'],
      productionNotes: 'Modern production with blues authenticity. Can incorporate electronic elements, hip-hop influence, or rock energy. Contemporary sound with traditional roots.',
      lyricNotes: 'Updated blues themes for modern life. Social commentary. Personal struggle. Traditional form with contemporary perspective.',
      sunoPromptKeywords: ['modern blues', 'contemporary blues', 'new blues', 'blues revival', 'updated blues', 'fresh blues'],
    },
    {
      name: 'Acoustic Blues',
      description: 'Unplugged blues in all its forms — solo guitar, duos, and small acoustic ensembles. The most intimate and raw form of the blues.',
      distinguishingFeatures: ['Acoustic instruments only', 'Intimate, raw sound', 'Solo or small ensemble', 'Traditional techniques', 'Minimal production'],
      bpmRange: { min: 55, max: 120 },
      keyArtists: ['Robert Johnson', 'Mississippi John Hurt', 'Keb\' Mo\'', 'Taj Mahal', 'Eric Bibb'],
      productionNotes: 'Pure acoustic recording. Minimal processing. Intimate, close-miked sound. Natural room ambience. Let the performance speak.',
      lyricNotes: 'Intimate, personal, traditional. Storytelling in its purest form. The most direct connection between artist and listener.',
      sunoPromptKeywords: ['acoustic blues', 'unplugged blues', 'solo blues', 'folk blues', 'intimate', 'raw', 'stripped-down'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Blues audiences are knowledgeable, loyal, and deeply connected to the music\'s history and cultural significance. The scene values authenticity, live performance, and emotional honesty.',
    fanExpectations: [
      'Authentic feeling over technical showmanship',
      'Deep connection to blues tradition',
      'Live performance excellence',
      'Emotional honesty in singing and playing',
      'Knowledge of blues history',
      'Real instruments, real playing',
    ],
    gatekeeping: 'Moderate — respect for tradition expected. Debates about purity vs. evolution. Cultural ownership discussions. Live playing ability is the ultimate gatekeeper.',
    livePerformance: 'The blues is a live music form — clubs, juke joints, and festivals. Intimate venues where artist and audience connect directly. Extended solos and improvisation. Audience call-and-response.',
    fashionAndAesthetic: 'Understated — jeans, work clothes, or sharp suits. No costume needed. Authenticity over image. Guitar and voice are the stars.',
    crossoverPotential: 'Moderate — blues elements exist in all popular music. Blues-rock crosses over regularly. Pure blues remains niche but universally respected.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'The blues shuffle IS micro-timing — the entire genre is built on the swing between straight and triplet 8th notes. This shuffle feel, where the second 8th note is delayed toward the third triplet position, creates the loping, swinging gait that defines the blues. Every blues musician negotiates this swing differently, and that negotiation is their signature.',
    quantizationDeviation: 'Blues predates quantization and resists it fundamentally. The shuffle ratio varies continuously — a player may swing harder on emotional peaks and straighten out during conversational passages. B.B. King\'s guitar phrasing sits in a unique timing pocket that no grid can capture. The walking bass line\'s quarter notes are never mechanically even; they push and pull with the soloist.',
    aheadBehindBeat: 'Blues vocals sit behind the beat — the singer arrives late, dragging with the weight of the story being told. Guitar solos push ahead during climactic bends and fall behind during contemplative passages. The drummer\'s shuffle pattern is slightly behind the bass player\'s walking line, creating a "leaning back" feel that is quintessentially blues.',
    humanizationMarkers: [
      'Shuffle ratio varying between 55% and 70% within a single performance',
      'Guitar bends that arrive at pitch slowly, not snapping to the note',
      'Walking bass notes with varying sustain and attack',
      'Brush patterns on snare that shift weight between strokes',
      'Vocal phrases that start late and end early, leaving silence',
    ],
    genreSpecificFeel: 'Blues feel cannot be programmed because it is fundamentally relational — the guitarist responds to the singer\'s timing, the bassist follows the drummer\'s shuffle depth, and everyone adjusts in real time. The "feel" of a blues performance is a conversation about time. Delta blues has the most extreme timing freedom (solo performer, no grid at all), while Chicago blues locks tighter with the band but still swings freely.',
  },

  silenceAndSpace: {
    overview: 'The blues is defined as much by what is not played as by what is. B.B. King was the master of single-note economy — his solos contain more silence than sound. The space between guitar notes is where the emotion lives, where the listener\'s imagination fills in the feeling the musician is suggesting.',
    negativeSpaceRole: 'Space in blues is conversational pause — the speaker stops, lets the words land, then continues. A bent note followed by silence is more powerful than a flurry of notes. The 12-bar form itself creates structural space: the turnaround is a breath between cycles, a moment to gather emotional energy for the next statement.',
    breathingPatterns: 'Guitar phrases breathe like vocal phrases — inhale (rest), exhale (phrase), inhale (rest). The AAB lyric form has built-in breathing: first line (breathe), repeat (breathe), resolution (longer breath before next verse). Slow blues creates enormous space between each musical event, making every note precious.',
    dynamicContrast: 'Blues dynamics are organic and narrative — the performance starts quiet and builds, or hits hard and retreats. Stop-time breaks (band drops out completely for a vocal or guitar moment) create the most extreme dynamic contrast. The contrast between a whispered verse and a screamed chorus mirrors storytelling\'s emotional arc.',
    whatIsDeliberatelyAbsent: [
      'Constant soloing (space between phrases is as important as the phrases)',
      'Dense harmonic arrangements (the blues is harmonically sparse)',
      'Production effects that fill space (reverb is natural, not artificial)',
      'Consistent volume (dynamics follow the emotional story)',
      'Busy drumming (the shuffle is steady, not flashy)',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response in blues takes its most elemental form: the singer calls, the guitar answers. This voice-instrument dialogue is the blues\'s defining structural relationship — the guitar is the singer\'s other voice, saying what words cannot express. This pattern descends from West African musical tradition through field hollers and work songs.',
    vocalInstrumentalDialogue: 'The vocalist sings a line, then the guitar responds in the space before the next vocal line. B.B. King named his guitar "Lucille" — she was his conversation partner. Muddy Waters\'s slide guitar wailed the responses his voice set up. The harmonica serves the same dialogic function, answering and commenting on the vocal.',
    sectionInternal: 'Within the 12-bar form, call-and-response is structural: bars 1-2 are the vocal call, bars 3-4 are the instrumental response; bars 5-6 repeat the call, bars 7-8 respond; bars 9-10 resolve, bars 11-12 are the turnaround. This pattern is so fundamental it defines the genre\'s architecture.',
    audienceParticipation: 'Blues audience response is vocal and verbal — "Tell it!" "Play it!" "Lord have mercy!" The audience affirms the performer\'s emotional truth. In juke joints and small clubs, the boundary between performer and audience blurs — audience members shout requests, comment on solos, and physically respond to the music.',
    patterns: [
      'Vocal line → guitar fill in the response space',
      'Singer\'s AAB verse → guitar turnaround',
      'Guitar bend → audience vocal response ("yeah!")',
      'Harmonica wail → vocal imitation of the wail',
      'Stop-time vocal cry → band re-entry as response',
      'Slow build → audience clapping as participatory response',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Blues is the most regionally specific American genre — Delta, Chicago, Texas, Piedmont, West Coast, and other regional styles are distinct dialects of the same musical language. Each region\'s blues reflects the local Black community\'s history, migration patterns, and cultural environment.',
    phoneticMarkers: [
      'Mississippi Delta: deep Southern drawl, elongated vowels, field-holler influenced open-throat singing',
      'Chicago: urbanized Southern accent, harder consonants, louder projection for club performance',
      'Texas: slightly cleaner diction than Delta, swing-influenced phrasing',
      'Piedmont: East Coast inflection, lighter touch, ragtime-influenced precision',
      'Louisiana: Creole-influenced vowels, zydeco rhythmic patterns, French-English code-switching',
    ],
    accentInfluence: 'Delta blues vocal style — raw, open-throated, field-holler intensity — became the template that Chicago electrified. Texas blues maintained a smoother, jazzier vocal approach. Piedmont blues was lighter and more melodic. These vocal styles directly reflect the regional Black communities that created them, including their migration history from the rural South.',
    dialectVocabulary: [
      '"Mojo" (magical power/charm, hoodoo tradition)',
      '"Crossroads" (place of supernatural encounter, Delta mythology)',
      '"Hoochie coochie" (sexual dance/person, Chicago blues slang)',
      '"Boogie" (dance/rhythm, universal blues term)',
      '"Juke joint" (informal bar/dance hall, Southern term)',
      '"Dust my broom" (leave town, Delta blues expression)',
    ],
    regionWithinCulture: 'Each blues region maps to a chapter in Black American history: Delta blues is sharecropping and plantation life. Chicago blues is the Great Migration and urban industrialization. Texas blues is the Southwest\'s relative independence. Piedmont is the East Coast\'s older, more established Black communities. The music carries the geography of Black American life.',
  },

  performancePractice: {
    overview: 'Blues performance is intimate and raw — the ideal setting is a small club where the performer can make eye contact with every person in the room. The blues performer is a storyteller, and the live performance is about emotional truth communicated directly, without spectacle or production.',
    improvisationConventions: 'Improvisation is the blues\'s native language. Solos are never played the same way twice. Vocal phrasing varies with each performance. The 12-bar form is a framework for spontaneous composition, not a rigid structure. A blues musician who plays a solo identically to the recording is not trusted.',
    crowdInteraction: 'Direct and personal. Blues performers talk to the audience between songs, tell stories, crack jokes, and address individuals. The small-club format creates a conversation between performer and audience. Requests are taken and honored. The performer reads the room\'s mood and adjusts — more upbeat if the crowd is festive, deeper if they need catharsis.',
    stagePresence: 'Understated but magnetic. B.B. King barely moved but commanded every room. Buddy Guy walks into the audience with a 50-foot guitar cable. Howlin\' Wolf used his enormous physical presence to overwhelm. The blues performer doesn\'t need choreography — their face, their hands on the instrument, and their voice are the show.',
    livVsRecordedDifferences: 'Live blues is always superior to studio blues — the genre is a live art form first. Solos are longer, audience interaction adds energy, and the emotional stakes are higher. Studio recordings capture a moment; live performances create one. The best blues albums are live recordings (B.B. King "Live at the Regal," Albert King "Live Wire/Blues Power").',
    whatMakesAGoodShow: 'Emotional honesty and instrumental storytelling. The performer must communicate genuine feeling — you can hear a blues musician who is going through the motions versus one who means it. Pacing matters: start slow, build through the set, peak with the most intense material, cool down for the encore. The audience should feel like they shared something real.',
  },

  socioeconomicSubtext: {
    overview: 'The blues is inseparable from the socioeconomic conditions that created it — slavery, sharecropping, the Great Migration, urban poverty, and systemic racism. The music IS the documentation of Black American material life. Economic hardship is not the blues\'s subtext; it is the text, the context, and the reason the music exists.',
    materialConditions: 'Blues emerged from the cotton fields of the Mississippi Delta — sharecroppers who worked land they didn\'t own, earning pennies, living in shacks. The music was created with whatever was available: a cigar box guitar, a harmonica, the human voice. The Great Migration (1910-1970) moved the blues north to Chicago, where factory work and urban poverty created new material for the music.',
    classIdentity: 'Blues is working-class and poor people\'s music — there is no blues aristocracy. Blues musicians were laborers, field workers, juke joint entertainers, and street performers. Even successful blues artists maintained working-class identity. B.B. King toured relentlessly in a bus, playing 300+ nights a year, because that was the economic model. The music speaks from the bottom of the class hierarchy.',
    politicalUndercurrent: 'Blues politics are existential rather than programmatic — the music doesn\'t call for revolution; it testifies to the conditions that make revolution necessary. Billie Holiday\'s "Strange Fruit" is blues-adjacent protest. Most blues politics are coded in everyday language: "born under a bad sign" is about structural disadvantage, not astrology.',
    implicitReferences: [
      'Train imagery encoding the Great Migration and escape',
      'Crossroads mythology as metaphor for impossible choices under oppression',
      '"Woke up this morning" framing daily survival as noteworthy',
      'Highway and road imagery reflecting displacement and itinerant labor',
      'Drinking and self-medication as response to unaddressed trauma',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Blues intertextuality is the oldest form in American popular music — blues musicians have always borrowed, adapted, and reinterpreted each other\'s songs. The concept of a "standard" (a song everyone knows and plays their own way) is fundamental to blues practice. This tradition of communal composition predates copyright law.',
    canonKnowledge: 'Every blues musician must know the standards: "Sweet Home Chicago," "Stormy Monday," "The Thrill Is Gone," "Hoochie Coochie Man," "Crossroads," "Dust My Broom." These songs belong to the community, not individuals. Robert Johnson\'s compositions are the Old Testament; Chicago blues standards are the New.',
    samplingTradition: 'Blues sampling in hip-hop is foundational — Muddy Waters, Howlin\' Wolf, and B.B. King have been sampled thousands of times. Within blues itself, "sampling" is organic: a guitarist quotes a B.B. King lick, a singer phrases like Muddy Waters, a harmonica player channels Little Walter. This is not theft; it is tradition.',
    quotationPractice: 'Quoting is expected and celebrated — playing a recognizable lick from a master is an act of respect. Entire verses migrate between blues songs across decades. The AAB lyric form means that first lines are communal property ("I woke up this morning," "My baby done left me"). Blues composition is collaborative across time.',
    expectedReferences: [
      'Robert Johnson\'s Delta recordings as the creation myth',
      'Muddy Waters electrifying the Delta sound in Chicago',
      'B.B. King\'s single-note phrasing as vocabulary',
      'Albert King\'s string-bending intensity',
      'Howlin\' Wolf\'s vocal ferocity and physical presence',
    ],
    lineageSignifiers: [
      'Playing a master\'s signature lick as tribute within a solo',
      'Covering standards with personal interpretation',
      'Using gear associated with blues icons (Fender Strats, Gibson 335s)',
      'Performing at legacy venues (Chicago blues clubs, Delta juke joints)',
      'Mentorship relationships (sitting in with elder musicians)',
      'Song dedications to deceased blues masters',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Blues has historically centered male performers, but women — from Ma Rainey and Bessie Smith to Koko Taylor and Bonnie Raitt — have always been present and powerful. Gender in blues is expressed through vocal delivery, lyrical perspective, and the body\'s relationship to the instrument.',
    vocalGenderCodes: 'Male blues vocals range from Muddy Waters\'s deep, commanding growl to B.B. King\'s sweet, high tenor. Female blues vocals are powerful and unapologetic — Bessie Smith\'s authority, Etta James\'s raw intensity, Koko Taylor\'s growl. There is no "delicate" female blues vocal; the genre demands power and presence from all singers.',
    physicalityInPerformance: 'The male blues body relates to the guitar as an extension — the face grimaces with each bent note, the body sways with the groove. B.B. King\'s vibrato came from his left hand shaking the string, visible as physical effort. Female blues performers command through vocal and physical authority — Big Mama Thornton\'s stage presence was physically dominating.',
    genderNarratives: 'Classic blues women (Ma Rainey, Bessie Smith) sang openly about desire, infidelity, and independence decades before feminism entered the mainstream. Male blues narratives center heartbreak, rambling, and desire. The gender dynamic is more egalitarian in blues lyrics than in most genres — women in blues have agency, leave men, and express sexual desire directly.',
    subversionExamples: [
      'Ma Rainey\'s "Prove It on Me Blues" addressing lesbianism in 1928',
      'Bessie Smith\'s sexual frankness challenging Victorian-era gender norms',
      'Memphis Minnie outplaying male guitarists in cutting contests',
      'Sister Rosetta Tharpe\'s guitar virtuosity in a male-dominated instrument',
      'Bonnie Raitt\'s slide guitar mastery in a genre coded masculine',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Blues tempo is inseparable from the shuffle feel — the swing between the 8th notes creates a rocking motion that makes the BPM almost irrelevant. A slow blues at 60 BPM and a shuffle at 120 BPM both feel like the blues because the shuffle ratio, not the speed, defines the groove.',
    psychologicalTempo: 'Slow blues at 60 BPM feels agonizingly deliberate — each beat carries the weight of the story. A medium shuffle at 100 BPM feels like walking — comfortable, swinging, the natural blues tempo. Fast shuffle at 130 BPM feels celebratory and driving. Boogie at 150+ BPM feels like dancing. The shuffle feel makes all tempos feel slower than their BPM suggests.',
    weightAndMomentum: 'Blues weight comes from the shuffle\'s gravitational pull — the delayed second 8th note creates a "leaning" sensation, like the music is always slightly off-balance. The walking bass provides steady forward momentum while the shuffle creates lateral swing. Slow blues has maximum weight per beat; fast shuffle trades weight for momentum.',
    urgencyScale: '1-10 urgency: Slow blues ballad at 55 BPM = 2 (mournful), slow shuffle at 80 BPM = 3 (storytelling), medium shuffle at 100 BPM = 5 (grooving), Texas shuffle at 120 BPM = 6 (swaggering), uptempo shuffle at 140 BPM = 7 (driving), jump blues at 170 BPM = 9 (ecstatic), boogie-woogie at 180 BPM = 10 (frenetic).',
    comparisonToSameBPM: 'Blues at 100 BPM feels completely different from rock at 100 BPM. The blues version swings — the triplet-based shuffle creates a rocking, circular motion. Rock at 100 BPM drives straight ahead in linear 8ths. The blues feels like swaying; rock feels like marching. Same speed, fundamentally different relationship to time and gravity.',
  },

  mistakeConventions: {
    overview: 'In blues, there are no mistakes — only expressions. A "wrong" note bent into tune becomes a blue note. A cracked vocal becomes a cry. A missed beat becomes a dramatic pause. The blues was created by self-taught musicians who turned technical limitations into expressive vocabulary. Imperfection is not tolerated in blues; it is the point.',
    toleratedImperfections: [
      'Notes that don\'t resolve to standard pitch (blue notes)',
      'Rough vocal timbre and gravelly tone',
      'Guitar strings buzzing against frets',
      'Rhythmic looseness between ensemble members',
      'Amplifier feedback and distortion at high volume',
    ],
    celebratedFlaws: [
      'Robert Johnson\'s raw, distorted recordings as primal art',
      'Howlin\' Wolf\'s vocal growl — technically a damaged voice, artistically devastating',
      'John Lee Hooker\'s refusal to follow standard bar counts',
      'Hound Dog Taylor playing intentionally out-of-tune guitar',
      'Elmore James\'s amp distortion turning "mistakes" into the electric blues sound',
    ],
    overproductionRisks: [
      'Pitch-correcting blue notes into standard tuning (destroying the blues scale)',
      'Quantizing the shuffle into rigid triplets (killing the swing)',
      'Clean, distortion-free guitar tone (removing grit and character)',
      'Multi-track studio separation (losing the live room interaction)',
      'Polished vocal recording that removes rasp, breath, and growl',
    ],
    authenticRoughness: 'Blues roughness is the genre\'s founding principle. The music was born from people who had no formal training, no quality instruments, and no recording studios — they had feeling, and that was enough. Elmore James\'s distorted amplifier, Howlin\' Wolf\'s impossible vocal range, Robert Johnson\'s lo-fi recordings — these "flaws" became the genre\'s most copied features. Polished blues is an oxymoron.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['blues', 'shuffle', 'twelve-bar', 'guitar', 'soulful', 'raw', 'emotional'],
    avoidKeywords: ['electronic', 'synth', 'auto-tune', 'EDM', 'pop', 'bubblegum', 'polished'],
    promptTemplate: '[sub-genre] blues, [tempo] BPM, [feel] shuffle/straight, [guitar style], [vocal style], [mood]',
    tips: [
      'Specify the sub-genre: Delta, Chicago, Texas, blues-rock, etc.',
      'Describe the guitar tone: clean, overdriven, slide, acoustic',
      'Mention the feel: slow blues, shuffle, boogie, straight',
      'Reference the mood: melancholic, defiant, celebratory, raw',
      'Include "shuffle" for traditional blues feel',
      'Describe the arrangement: solo guitar, full band, harmonica',
    ],
  },
};
