import type { GenreGuide } from './types';

export const BRAZILIAN_GUIDE: GenreGuide = {
  id: 'brazilian',
  name: 'Brazilian Music',
  language: 'Portuguese',

  sonicPalette: {
    overview: 'Rhythmically sophisticated, harmonically lush, and emotionally warm. Brazilian music is defined by the interplay of African-rooted polyrhythm and Portuguese-derived melodic beauty — from the intimate whisper of bossa nova to the explosive energy of samba batucada.',
    timbre: [
      'nylon-string acoustic guitar (violão)',
      'cavaquinho (small 4-string guitar)',
      'surdo, tamborim, and pandeiro (samba percussion)',
      'cuíca (friction drum)',
      'berimbau (Afro-Brazilian bow)',
      'accordion (forró, baião)',
    ],
    texture: 'Rhythmically dense but harmonically spacious. The percussion section is complex and layered while melodic instruments breathe. Bossa nova is famously sparse; samba is poly-layered; sertanejo is warm and mid-heavy.',
    tonality: 'Rich extended harmony — major 7ths, 9ths, and altered dominants are standard. Bossa nova harmony rivals jazz in sophistication. Sertanejo and forró use simpler progressions with modal flavour.',
    signatureSounds: [
      'bossa nova guitar pattern (thumb-finger alternation)',
      'samba batucada percussion ensemble',
      'cuíca "crying" sound',
      'berimbau single-string drone',
      'baião triangle-zabumba-accordion trio',
    ],
  },

  rhythmAndGroove: {
    overview: 'Brazil\'s greatest musical contribution is rhythmic — samba\'s polyrhythmic layering, bossa nova\'s subtle syncopation, baião\'s driving bounce, and funk carioca\'s relentless pulse are all globally influential.',
    bpmRange: { min: 65, max: 150, sweet: 95 },
    feel: 'Inherently syncopated — the "ginga" (swing/sway) is the essential Brazilian rhythmic quality. Even at slow tempos, the groove has an irresistible forward motion.',
    swing: 'Not swing in the jazz sense but a distinctive Brazilian lilt. Samba has a slight shuffle between 16th notes. Bossa nova straightens this out while retaining syncopated accents.',
    syncopation: 'Extremely high. The surdo pattern in samba emphasizes beat 2. Bossa nova guitar anticipates beat 1. Brazilian rhythm consistently displaces expected accent patterns.',
    grooveArchetype: 'Samba partido-alto pattern, bossa nova two-bar guitar cycle, baião zabumba-triangle interlock, funk carioca "tamborzão" beat.',
    rhythmicSignatures: [
      'samba: surdo on beat 2, tamborim syncopated 16ths',
      'bossa nova: two-bar guitar pattern with anticipated bass',
      'baião: zabumba bass drum with triangle ostinato',
      'funk carioca: "tamborzão" electronic bass drum pattern',
      'maracatu: alfaia drums in interlocking pattern',
    ],
  },

  harmonicLanguage: {
    overview: 'Brazilian harmony — particularly bossa nova and MPB — is among the most sophisticated in popular music worldwide. Tom Jobim brought Debussy-influenced chromatic voice leading into popular song.',
    scales: [
      'major with chromatic extensions',
      'Dorian mode',
      'Lydian (bright, floating quality)',
      'Mixolydian (baião and northeastern modes)',
      'harmonic minor',
    ],
    chordProgressions: [
      'Imaj7 – IIm9 – V13 – Imaj7 (bossa nova jazz standard)',
      'I – IV – V – I (sertanejo and forró)',
      'i – bVII – bVI – V (MPB minor drama)',
      'Imaj7 – #IVm7b5 – IV6 – IVm6 (Jobim chromatic descent)',
    ],
    harmonyNotes: 'Extended chords are the norm, not the exception. Altered dominants (V7#9, V7b13) are standard vocabulary. Chromatic bass movement and inner voice leading distinguish Brazilian harmony from simpler pop.',
    modality: 'Freely modal. Northeastern Brazilian music (baião, forró) uses Mixolydian and Lydian naturally. Bossa nova and MPB are tonally fluid with frequent tonicizations.',
  },

  songStructure: {
    overview: 'Brazilian song structure varies widely — bossa nova favours compact AABA forms; samba can extend into extended roda (circle) jams; MPB experiments freely with form.',
    form: 'AABA (bossa nova), Verse-Chorus (samba-canção, sertanejo), Through-composed (experimental MPB)',
    sections: [
      'Intro (guitar or percussion pattern)',
      'Verse (melodic development)',
      'Chorus or B section (harmonic and melodic peak)',
      'Bridge (harmonic departure)',
      'Instrumental solo (guitar or horn)',
    ],
    arrangement: 'Bossa nova: minimalist — voice, guitar, light percussion. Samba: builds from solo voice to full batucada. MPB: orchestral and experimental arrangements.',
    introOutro: 'Guitar intros are iconic (bossa nova). Samba often starts with percussion call. Outros may fade on repeated chorus or end with percussion break.',
    barLengths: 'Variable — bossa nova: 32-bar standards. Samba: 16-bar verse-chorus cycles. MPB: irregular phrase lengths common.',
    hookPlacement: 'Melody is the hook — Brazilian music hooks are melodic rather than rhythmic or lyrical. The opening guitar riff or vocal phrase is the signature.',
  },

  vocalDelivery: {
    overview: 'Brazilian vocal delivery ranges from bossa nova\'s intimate whisper to samba\'s full-throated celebration. The Portuguese language\'s nasal vowels and flowing consonants create naturally musical vocal lines.',
    phrasing: 'Conversational and rhythmically fluid. Bossa nova: barely above a whisper, intimate. Samba: powerful and projected. MPB: expressive and free.',
    affect: 'Saudade (bittersweet longing) is the quintessential Brazilian emotional register. Joy (alegria) in samba. Passion (paixão) in sertanejo.',
    techniques: [
      'intimate close-mic whisper (bossa nova)',
      'powerful samba belt',
      'melismatic runs (MPB, gospel-influenced)',
      'vocal improvisation in roda de samba',
    ],
    adlibStyle: 'Call-and-response in samba. Vocal scatting in bossa nova. "Ê! Ô!" exclamations in carnival samba.',
    harmony: 'Close thirds in duo sertanejo. Unison and octave in samba escola. Jazz-influenced vocal harmony in MPB.',
    grit: 'Minimal in bossa nova — smooth is essential. Moderate rasp in samba for street authenticity. Full grit in funk carioca and some MPB.',
  },

  lyricalConventions: {
    overview: 'Brazilian lyrics carry a profound literary tradition — Vinícius de Moraes was a diplomat-poet, Caetano Veloso a intellectual provocateur, Chico Buarque a novelist-songwriter. Portuguese\'s musicality elevates even simple lyrics.',
    themes: [
      'saudade (bittersweet longing)',
      'romantic love and desire',
      'the sea, beach, and tropical nature',
      'Rio de Janeiro and urban life',
      'carnival and celebration',
      'social justice and inequality',
    ],
    perspective: 'First-person romantic confession dominant. Third-person storytelling in samba de roda. "We" in carnival and community songs.',
    figurativeLanguage: 'Ocean and wave metaphors for emotion. Sun and warmth for joy. Rain for melancholy. Nature imagery deeply Brazilian — palm trees, beaches, favelas, moonlight on the sea.',
    vocabulary: 'Brazilian Portuguese — distinct from European Portuguese. Rich in diminutives (inho/inha) conveying affection. Gíria (slang) in funk and hip-hop. Literary register in bossa nova and MPB.',
    storytellingApproach: 'Emotional impressionism — painting a feeling rather than telling a story. Bossa nova: a single mood sustained. Samba: narrative and celebratory. MPB: poetic and abstract.',
    cliches: [
      'garota de Ipanema imagery',
      '"saudade" as universal emotional shorthand',
      'carnival as metaphor for life',
      'the sea as emotional mirror',
    ],
  },

  productionFingerprint: {
    overview: 'Brazilian production ranges from the acoustic intimacy of bossa nova to the electronic maximalism of funk carioca. The best Brazilian production preserves rhythmic nuance and harmonic sophistication.',
    mixAesthetic: 'Bossa nova: intimate, dry, close. Samba: live and room-ambient. MPB: polished but organic. Funk carioca: bass-heavy, compressed, loud.',
    era: 'Current era spans sertanejo dominance in domestic market, funk carioca\'s global streaming success, and continued reverence for MPB legacy.',
    signalChain: 'Bossa nova: condenser mic, minimal processing. Samba: live ensemble recording. Funk carioca: FL Studio, heavy bass processing, compressed masters.',
    modernTrends: 'Funk carioca going global. Sertanejo pop-country fusion. Neo-MPB revival. Brazilian bass and electronic music scene. Anitta-led pop crossover.',
  },

  instrumentation: {
    coreInstruments: [
      'violão (nylon-string guitar)',
      'cavaquinho',
      'pandeiro (frame drum)',
      'surdo (bass drum)',
      'tamborim (small frame drum)',
      'accordion/sanfona (forró)',
    ],
    signatureSounds: [
      'bossa nova guitar pattern',
      'samba batucada full percussion',
      'cuíca friction-drum cry',
      'berimbau metallic drone',
    ],
    layering: 'Samba: percussion layers built from surdo up through tamborim and agogô. Bossa nova: guitar carries harmony and rhythm simultaneously. MPB: orchestral layers over acoustic foundation.',
    avoidInstruments: [
      'heavy rock guitar distortion',
      'country steel guitar',
      'Scottish bagpipes',
      'harsh industrial synths',
    ],
  },

  culturalContext: {
    overview: 'Brazilian music reflects the country\'s African, European, and indigenous heritage — a cultural melting pot expressed through rhythm, melody, and dance. Music is central to Brazilian identity and social life.',
    origin: 'Rio de Janeiro (bossa nova, samba, funk carioca). Bahia (axé, samba de roda). Pernambuco (frevo, maracatu). Northeast (forró, baião). São Paulo (sertanejo, rap). The geography of Brazil maps onto its musical diversity.',
    identity: 'Brazilian Portuguese is non-negotiable. Music is tied to racial identity — samba\'s Afro-Brazilian roots, bossa nova\'s middle-class refinement, sertanejo\'s rural interior culture.',
    community: 'Carnival is the supreme community music event. Blocos (street bands) and escolas de samba organize neighborhoods. Rodas de samba (samba circles) are intimate community gatherings.',
    socialFunction: 'Carnival: national celebration and release. Samba: community bonding and Afro-Brazilian cultural preservation. Forró: courtship dance. Funk: favela youth identity and expression.',
    authenticityMarkers: [
      'Brazilian Portuguese lyrics',
      'correct rhythmic feel (ginga)',
      'appropriate harmonic sophistication for the sub-genre',
      'cultural specificity — regional Brazilian references',
      'understanding of samba\'s Afro-Brazilian roots',
    ],
  },

  historicalLineage: {
    overview: 'From African-derived samba through bossa nova\'s revolution to Tropicália\'s cultural explosion and contemporary funk carioca\'s global reach.',
    roots: [
      'African rhythmic traditions (Yoruba, Bantu)',
      'Portuguese colonial melodic heritage',
      'choro (instrumental precursor to samba, 1870s)',
      'samba de roda (Bahian circle samba)',
      'maxixe (early urban dance music)',
    ],
    evolution: 'Samba emergence (1910s-20s) → golden age of radio samba (1930s-40s) → bossa nova revolution (1958) → Tropicália (1967-68) → MPB golden era (1970s) → sertanejo and axé boom (1990s) → funk carioca and Brazilian bass (2010s-present).',
    keyEras: [
      '1920s-30s: Samba establishment in Rio',
      '1958-1964: Bossa nova revolution',
      '1967-68: Tropicália (Caetano, Gil, Os Mutantes)',
      '1970s: MPB golden era under dictatorship',
      '2010s-present: Funk carioca global breakout',
    ],
    influencedBy: [
      'West African rhythmic traditions',
      'Portuguese fado and folk',
      'American jazz (on bossa nova)',
      'rock and psychedelia (on Tropicália)',
    ],
    influenced: [
      'jazz worldwide (bossa nova influence)',
      'global pop (Brazilian rhythms)',
      'electronic music (Brazilian bass)',
      'Latin American music broadly',
    ],
  },

  subGenres: [
    {
      name: 'Bossa Nova',
      description: 'The intimate, harmonically sophisticated revolution of 1958 — João Gilberto\'s whispered vocals and complex guitar over Tom Jobim\'s Debussy-meets-samba compositions. Changed global popular music.',
      distinguishingFeatures: ['intimate whispered vocal', 'sophisticated jazz harmony', 'distinctive two-bar guitar pattern', 'minimal percussion'],
      bpmRange: { min: 65, max: 90 },
      keyArtists: ['Tom Jobim', 'João Gilberto', 'Astrud Gilberto', 'Stan Getz'],
      productionNotes: 'Intimate and dry. Close-mic\'d voice and guitar. Minimal reverb. The space between notes is as important as the notes.',
      lyricNotes: 'Romantic, poetic, understated. Vinícius de Moraes\' poetry. Sea, sun, love, saudade. Portuguese at its most musical.',
      sunoPromptKeywords: ['bossa nova', 'Brazilian jazz', 'João Gilberto style', 'intimate Brazilian', 'cool Brazilian'],
    },
    {
      name: 'Samba',
      description: 'The rhythmic heart of Brazil — polyrhythmic, celebratory, and deeply rooted in Afro-Brazilian culture. From carnival batucada to intimate pagode, samba is Brazil\'s national music.',
      distinguishingFeatures: ['surdo-anchored polyrhythmic percussion', 'syncopated 2/4 feel', 'cavaquinho strumming', 'call-and-response vocals'],
      bpmRange: { min: 100, max: 150 },
      keyArtists: ['Cartola', 'Beth Carvalho', 'Zeca Pagodinho', 'Clara Nunes'],
      productionNotes: 'Live ensemble. Percussion must be layered and interlocking. Cavaquinho and guitar provide harmonic bed. Vocals projected and joyful.',
      lyricNotes: 'Community, love, Rio life, carnival, social commentary. Malandragem (street wisdom) as a theme.',
      sunoPromptKeywords: ['samba', 'Brazilian samba', 'carnival music', 'batucada', 'Rio samba'],
    },
    {
      name: 'MPB',
      description: 'Música Popular Brasileira — the art-song tradition encompassing everything from Tropicália\'s psychedelic experimentation to sophisticated pop-jazz. Brazil\'s most intellectually prestigious music.',
      distinguishingFeatures: ['harmonic sophistication', 'poetic lyrics', 'genre eclecticism', 'artistic experimentation'],
      bpmRange: { min: 70, max: 130 },
      keyArtists: ['Caetano Veloso', 'Gilberto Gil', 'Chico Buarque', 'Milton Nascimento'],
      productionNotes: 'Varies enormously — acoustic to orchestral to electronic. Quality and artistic vision are paramount. No formula.',
      lyricNotes: 'Literary, poetic, politically engaged. Portuguese at its most expressive. Social commentary under dictatorship was coded and profound.',
      sunoPromptKeywords: ['MPB', 'Brazilian art pop', 'Caetano Veloso style', 'Tropicália', 'sophisticated Brazilian'],
    },
    {
      name: 'Funk Carioca',
      description: 'Rio de Janeiro\'s bass-heavy electronic dance music born in favela baile funk parties. The "tamborzão" beat drives relentless, sexually charged, and massively popular dance music.',
      distinguishingFeatures: ['tamborzão bass pattern', 'hypersexual or party lyrics', 'MC vocal delivery', 'bass-heavy production'],
      bpmRange: { min: 125, max: 145 },
      keyArtists: ['MC Kevin o Chris', 'Anitta', 'Ludmilla', 'DJ Marlboro'],
      productionNotes: 'FL Studio dominant. Heavy bass. Tamborzão pattern non-negotiable. Compressed and loud. MC vocals up front.',
      lyricNotes: 'Party, sexuality, favela life, empowerment. Brazilian Portuguese slang. Direct and explicit.',
      sunoPromptKeywords: ['funk carioca', 'baile funk', 'Brazilian bass', 'Rio funk', 'tamborzão'],
    },
    {
      name: 'Sertanejo',
      description: 'Brazilian country music — the dominant domestic genre. Sertanejo universitário (pop-country) dominates streaming. Vocal duos, romantic themes, and accessible production.',
      distinguishingFeatures: ['vocal duo harmony (thirds)', 'acoustic and electric guitar', 'romantic balladry', 'pop-country production'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Marília Mendonça', 'Jorge & Mateus', 'Henrique & Juliano', 'Gusttavo Lima'],
      productionNotes: 'Polished pop production. Acoustic guitar foundation. Electric guitar leads. Vocal clarity essential. Nashville-influenced but distinctly Brazilian.',
      lyricNotes: 'Romantic heartbreak, drinking, rural nostalgia, party anthems. Accessible Brazilian Portuguese.',
      sunoPromptKeywords: ['sertanejo', 'Brazilian country', 'sertanejo universitário', 'Brazilian romantic pop'],
    },
    {
      name: 'Forró',
      description: 'Northeastern Brazilian dance music — accordion, triangle, and zabumba drum create an irresistible groove for couple dancing. From traditional pé-de-serra to electronic forró.',
      distinguishingFeatures: ['accordion-triangle-zabumba trio', 'baião rhythm', 'couple dance orientation', 'northeastern identity'],
      bpmRange: { min: 100, max: 140 },
      keyArtists: ['Luiz Gonzaga', 'Dominguinhos', 'Alceu Valença', 'Falamansa'],
      productionNotes: 'Accordion must be prominent and expressive. Triangle provides constant rhythmic pulse. Zabumba anchors the groove. Live feel essential.',
      lyricNotes: 'Rural life, drought, migration, romance, dance. Northeastern Portuguese dialect and references.',
      sunoPromptKeywords: ['forró', 'Brazilian forró', 'baião', 'northeastern Brazilian', 'accordion Brazilian'],
    },
    {
      name: 'Axé',
      description: 'Salvador da Bahia\'s carnival pop — high-energy, percussive, and built for massive street-party dancing. Blends Afro-Bahian drumming with pop production.',
      distinguishingFeatures: ['Afro-Bahian percussion (ilê, olodum)', 'high-energy pop production', 'carnival orientation', 'call-and-response'],
      bpmRange: { min: 110, max: 140 },
      keyArtists: ['Ivete Sangalo', 'Daniela Mercury', 'Olodum', 'Chiclete com Banana'],
      productionNotes: 'Big, bright production. Percussion section prominent. Horns for energy. Vocals powerful and celebratory.',
      lyricNotes: 'Carnival celebration, dance commands, Bahian pride, Afro-Brazilian identity. Direct and joyful.',
      sunoPromptKeywords: ['axé', 'Bahia carnival', 'Salvador music', 'Afro-Brazilian pop', 'carnival dance'],
    },
    {
      name: 'Pagode',
      description: 'Intimate, acoustic samba style born from roda de samba gatherings. Softer and more romantic than carnival samba, with emphasis on vocal harmony and banjo/tantã percussion.',
      distinguishingFeatures: ['softer acoustic samba', 'tantã and banjo (Brazilian)', 'romantic vocal harmonies', 'roda de samba intimacy'],
      bpmRange: { min: 85, max: 115 },
      keyArtists: ['Zeca Pagodinho', 'Grupo Revelação', 'Thiaguinho', 'Sorriso Maroto'],
      productionNotes: 'Acoustic warmth. Live feel. Close vocal recording. Tantã and pandeiro prominent. Guitar and cavaquinho interplay.',
      lyricNotes: 'Romantic love, friendship, community, beer and good times. Warm, conversational Portuguese.',
      sunoPromptKeywords: ['pagode', 'Brazilian pagode', 'romantic samba', 'roda de samba', 'acoustic Brazilian'],
    },
    {
      name: 'Tropicália',
      description: 'The psychedelic-revolutionary movement of 1967-68 — Caetano Veloso and Gilberto Gil mixed Brazilian music with rock, pop art, and political provocation. Brief but permanently transformative.',
      distinguishingFeatures: ['psychedelic rock meets Brazilian rhythm', 'avant-garde experimentation', 'political provocation', 'genre collage'],
      bpmRange: { min: 80, max: 140 },
      keyArtists: ['Caetano Veloso', 'Gilberto Gil', 'Os Mutantes', 'Tom Zé'],
      productionNotes: 'Experimental. Electric guitars with effects over traditional percussion. Studio manipulation. Collage aesthetics. Rules are made to be broken.',
      lyricNotes: 'Political, surreal, poetic, provocative. Critiquing Brazilian society through absurdist imagery.',
      sunoPromptKeywords: ['Tropicália', 'Brazilian psychedelic', 'Os Mutantes style', 'experimental Brazilian'],
    },
    {
      name: 'Brazilian Bass',
      description: 'Contemporary electronic music from Brazil\'s club scene — heavy bass, Brazilian rhythmic elements, and EDM production techniques. Brazil\'s contribution to global electronic dance music.',
      distinguishingFeatures: ['heavy bass drops', 'Brazilian rhythm samples', 'EDM production framework', 'festival-ready energy'],
      bpmRange: { min: 125, max: 150 },
      keyArtists: ['Alok', 'Vintage Culture', 'Cat Dealers', 'KVSH'],
      productionNotes: 'EDM production with Brazilian percussion samples. Heavy sidechain. Bass-forward mix. Festival-optimized mastering.',
      lyricNotes: 'Minimal lyrics — vocal samples and hooks. Party energy. Portuguese and English.',
      sunoPromptKeywords: ['Brazilian bass', 'Brazil EDM', 'Alok style', 'Brazilian electronic', 'bass house Brazil'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Brazilian music audiences are diverse, passionate, and deeply connected to regional identity. Sertanejo dominates domestic streaming; funk carioca is the sound of urban youth; MPB carries intellectual prestige.',
    fanExpectations: [
      'Brazilian Portuguese lyrics',
      'authentic rhythmic feel (ginga)',
      'regional cultural specificity',
      'emotional warmth and sincerity',
      'danceable grooves',
    ],
    gatekeeping: 'Low for sertanejo and funk (populist). High for samba and MPB (traditionalists guard authenticity). Bossa nova purists are exacting about harmonic and rhythmic authenticity.',
    livePerformance: 'Carnival is the supreme live event. Samba schools rehearse year-round. Forró is inseparable from couple dancing. Funk bailes are massive favela parties.',
    fashionAndAesthetic: 'Carnival: elaborate costumes and minimal clothing. Sertanejo: cowboy hats and rural chic. Funk: favela streetwear and bold colour. MPB: intellectual casual.',
    crossoverPotential: 'Growing via Anitta and funk carioca. Bossa nova has permanent global status. Brazilian bass reaches international EDM festivals. Sertanejo remains primarily domestic.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Samba\'s ginga (swing/sway) is the defining Brazilian micro-timing quality — a characteristic lilt that is neither straight nor swung in the Western sense. It is its own rhythmic universe, felt in the body before it is understood by the mind.',
    quantizationDeviation: 'Extremely high in samba where every instrument occupies a slightly different micro-time position. Moderate in bossa nova where the guitar anticipates beats with precision. Low in funk carioca where the tamborzão is machine-locked.',
    aheadBehindBeat: 'Bossa nova guitar consistently anticipates beat 1 — the famous "lazy" anticipation that creates its floating quality. Samba surdo sits on beat 2 with gravitational weight. Pagode sits slightly behind everything, creating its relaxed warmth.',
    humanizationMarkers: [
      'tamborim player\'s micro-rush on syncopated 16th notes creating samba drive',
      'bossa nova guitar anticipation of beat 1 by a 16th note',
      'surdo\'s deep beat-2 emphasis pulling the groove into sway',
      'pandeiro\'s thumb-roll subtly ahead of the beat creating forward lean',
      'cavaquinho strumming with slight swing between 16th notes',
    ],
    genreSpecificFeel: 'The ginga cannot be programmed — it is the result of multiple instruments each occupying slightly different positions around the beat, creating a web of micro-tensions that makes the body sway involuntarily. This is Brazil\'s rhythmic gift to the world.',
  },

  silenceAndSpace: {
    overview: 'Brazilian music spans extremes of density and space — bossa nova is among the sparsest popular music ever created, while samba batucada is among the most rhythmically saturated. Both use space with intention.',
    negativeSpaceRole: 'In bossa nova, the space between guitar notes is where the music lives — the silence is as composed as the sound. In samba, brief collective breaks (paradas) create dramatic punctuation in the wall of percussion.',
    breathingPatterns: 'João Gilberto\'s almost-whispered delivery makes breath audible and intimate — the breathing IS part of the musical expression. Samba singers project powerfully, and breath is taken strategically between syncopated phrases.',
    dynamicContrast: 'Minimal in bossa nova (everything stays intimate). Extreme in samba escola (full batucada eruptions after quiet passages). Moderate in MPB (dynamic range serves artistic expression). Compressed in funk carioca (everything is loud).',
    whatIsDeliberatelyAbsent: [
      'percussion in bossa nova to let guitar and voice exist in pure space',
      'harmony instruments during batucada breaks to expose raw percussion',
      'bass during pandeiro solos in pagode to feature the instrument\'s range',
      'all instruments during the "parada" (stop) in samba for dramatic silence',
      'electronic elements in acoustic MPB to preserve organic warmth',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response is deep in Brazilian music through its Afro-Brazilian roots — batucada (drum circle) traditions, samba de roda circle singing, and capoeira\'s collective vocal engagement all depend on communal musical dialogue.',
    vocalInstrumentalDialogue: 'In samba, the cavaquinho "speaks" between vocal phrases, commenting on what the singer says. The cuíca\'s crying sound dialogues with the melody. In bossa nova, the guitar is both accompanist and conversational partner.',
    sectionInternal: 'Samba de roda features a soloist who sings a verse and the circle responds with the chorus — this is the foundational form. In pagode, instruments take turns responding to the vocal line.',
    audienceParticipation: 'Brazilian audiences are inseparable from the music. In carnival, hundreds of thousands sing the samba-enredo in unison. In roda de samba, anyone in the circle can become the lead singer. "Ê! Ô!" exclamations are collective vocal participation.',
    patterns: [
      'puxador (lead singer) calls the samba-enredo, thousands respond with the chorus',
      'capoeira soloist sings the ladainha, circle responds with the corrido',
      'roda de samba singer improvises verse, circle sings the refrain',
      'batucada mestre (master) plays pattern, percussion section responds',
      'MC calls out to the baile, crowd responds with movement and voice (funk)',
      'forró singer calls, accordion answers with melodic phrase',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Brazilian Portuguese differs dramatically from European Portuguese — it sounds like a different language. Within Brazil, Carioca (Rio), Nordestino (Northeast), Paulista (São Paulo), Mineiro (Minas Gerais), and Gaúcho (South) accents create distinct musical flavors.',
    phoneticMarkers: [
      'Carioca: palatalized "t" and "d" before "i" (sounds like "tchi" and "dji"), open vowels',
      'Nordestino: open vowels, rolled "r", strong rhythmic cadence in speech',
      'Paulista: retrofllex "r" (almost like American English "r"), nasal vowels',
      'Mineiro: swallowed syllables, soft "r", musical intonation with rising patterns',
      'Gaúcho: clear final vowels, Spanish-influenced "rr", measured cadence',
    ],
    accentInfluence: 'Carioca Portuguese shapes samba and bossa nova with its flowing, melodic quality. Nordestino accent gives forró and baião their distinctive rhythmic vocal delivery. Paulista accent is neutral for sertanejo\'s broad appeal. Baiano (Bahian) Portuguese adds Afro-Brazilian inflections to axé.',
    dialectVocabulary: [
      'Carioca: "mano" (bro), "responsa" (cool), "sinistro" (awesome), "vacilão" (unreliable)',
      'Nordestino: "vixe" (exclamation), "arretado" (amazing), "oxente" (wow), "cabra" (dude)',
      'Paulista: "mano" (bro), "firmeza" (solid), "da hora" (cool), "trampo" (work)',
      'Baiano: "ôxe" (exclamation), "massa" (great), "painho/mainha" (dad/mom)',
      'Funk slang: "bonde" (crew), "baile" (party), "pancadão" (heavy bass), "cria" (local kid)',
    ],
    regionWithinCulture: 'Rio de Janeiro owns samba, bossa nova, and funk carioca. Bahia owns axé and samba de roda. Pernambuco owns frevo and maracatu. The Northeast owns forró and baião. São Paulo and the interior own sertanejo. Each region defends its genres with fierce pride.',
  },

  performancePractice: {
    overview: 'Brazilian music performance is inseparable from the body — samba has specific footwork (passistas), forró is couple dancing, capoeira is martial-art-dance-music, and funk carioca is defined by its dance styles. Music without movement is incomplete.',
    improvisationConventions: 'Samba de roda and pagode are inherently improvisational — the roda (circle) format invites spontaneous vocal and instrumental solos. Bossa nova musicians improvise harmonically within the song\'s framework. MPB artists may radically reinterpret their own compositions live.',
    crowdInteraction: 'Brazilian audiences dance, sing, and become part of the performance. Carnival is the ultimate expression — millions of people ARE the show. Roda de samba erases the performer-audience boundary entirely. Funk bailes are collective energy events.',
    stagePresence: 'Physically engaged and rhythmically connected. Samba performers dance while playing. Forró artists move with the groove. Even bossa nova\'s intimacy requires physical connection to the rhythm — João Gilberto\'s foot tap was essential to his performance.',
    livVsRecordedDifferences: 'Samba live is longer, louder, and more percussively intense than studio recordings. Bossa nova live may be even more stripped back — just voice and guitar in a small room. MPB live performances can be radically different arrangements from studio versions.',
    whatMakesAGoodShow: 'Everyone is moving — the musicians, the audience, the energy in the room. The ginga is felt collectively. In samba: the batucada makes your chest vibrate. In bossa nova: the intimacy makes you hold your breath. In funk: the bass makes the floor shake.',
  },

  socioeconomicSubtext: {
    overview: 'Brazilian music is stratified by class and race with unusual transparency. Samba was born from Afro-Brazilian working-class communities in Rio\'s morros (hills). Bossa nova was its middle-class Zona Sul refinement. Funk carioca is favela youth culture. Sertanejo is rural interior identity. MPB is educated middle-class sophistication.',
    materialConditions: 'Funk carioca emerged from favela baile funk parties where DJs with borrowed equipment created entertainment for communities excluded from mainstream venues. Samba schools are community organizations in working-class neighborhoods. Bossa nova thrived in Copacabana apartments.',
    classIdentity: 'Samba carries Afro-Brazilian working-class pride — the morro (hillside favela) is the spiritual home. Bossa nova is middle-class Zona Sul sophistication. MPB is intellectual bourgeois culture. Sertanejo is proudly rural. Funk is favela identity reclaimed from stigma.',
    politicalUndercurrent: 'Tropicália was explicitly political resistance against military dictatorship. Chico Buarque wrote coded protest songs that passed censorship. Funk carioca addresses police violence in favelas. Samba has always been a space for Afro-Brazilian political expression and cultural survival.',
    implicitReferences: [
      'the morro (hill/favela) as origin and identity in samba and funk',
      'the asfalto (paved city) vs. morro (favela) as class geography',
      'brand references and luxury aspirations in funk as class mobility fantasy',
      'saudade as emotional response to displacement and migration',
      'carnival as temporary suspension of social hierarchy',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Brazilian music has a dense web of internal references — every MPB artist is in conversation with Tom Jobim, every samba references Cartola, and the bossa nova harmonic language has become a global musical lingua franca sampled by artists worldwide.',
    canonKnowledge: 'Tom Jobim and Vinícius de Moraes are the foundational partnership. João Gilberto invented bossa nova\'s guitar style. Caetano and Gil transformed everything with Tropicália. Cartola is the patron saint of samba. These are not optional knowledge — they are the language itself.',
    samplingTradition: 'Bossa nova has been sampled more than almost any other genre worldwide — "The Girl from Ipanema" is the second-most-recorded song in history. Funk carioca samples Miami bass, global pop, and other funk tracks freely. MPB artists reinterpret each other\'s catalogs.',
    quotationPractice: 'Covering classic MPB and bossa nova songs is a standard practice that demonstrates cultural literacy. Reharmonizing Jobim is a rite of passage. Samba composers quote melodic phrases from predecessors as homage.',
    expectedReferences: [
      'Tom Jobim\'s harmonic language as the foundation of Brazilian sophistication',
      'João Gilberto\'s guitar style as the bossa nova template',
      'Caetano Veloso as the intellectual conscience of Brazilian music',
      'Cartola as the poetic soul of samba',
      'Gilberto Gil as the bridge between tradition and experiment',
    ],
    lineageSignifiers: [
      'bossa nova guitar pattern immediately signaling Brazilian identity',
      'batucada percussion declaring samba affiliation',
      'Tropicália-style genre collage referencing the 1968 revolution',
      'Nordestino accordion connecting to Luiz Gonzaga\'s baião legacy',
      'tamborzão beat identifying funk carioca instantly',
      'chromatic bass descents channeling Jobim\'s harmonic sophistication',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Brazilian music has gendered performance traditions shaped by Afro-Brazilian culture and Catholic-colonial history — the passista (female samba dancer), the malandro (male street-wise samba figure), and the sensual dynamics of forró couple dancing each carry specific body codes.',
    vocalGenderCodes: 'Male bossa nova singers whisper with cool detachment. Male samba singers project with rhythmic power. Female MPB singers (Elis Regina, Gal Costa, Maria Bethânia) claim the full emotional range — from whisper to cry. Female funk MCs assert aggressive sexual agency.',
    physicalityInPerformance: 'The female body in carnival is both celebrated and debated — passistas and rainhas de bateria (drum queens) embody samba\'s physicality. Male sambistas dance with swagger and precision. Forró demands intimate couple contact. Funk carioca dance styles are explicitly sexual for all genders.',
    genderNarratives: 'Traditional samba romanticizes the malandro (street-smart rogue) and the mulata (mixed-race woman) as archetypes. Bossa nova\'s gaze is male — "The Girl from Ipanema" watches a woman walk by. Contemporary artists like Elza Soares, Ludmilla, and Anitta have claimed female authorship of their own narratives.',
    subversionExamples: [
      'Elza Soares transforming from samba object to empowered elder voice',
      'Liniker\'s trans identity expanding MPB\'s gender vocabulary',
      'Ludmilla claiming space as a Black queer woman in funk and pop',
      'Anitta controlling her own sexual narrative rather than being its object',
      'Criolo addressing masculinity and violence in rap-samba fusion',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Brazilian music\'s relationship to tempo is uniquely complex because the ginga creates a perceived swing that exists outside Western straight/swung binaries. A samba at 100 BPM feels fundamentally different from any other music at 100 BPM.',
    psychologicalTempo: 'Bossa nova at 70 BPM feels suspended in time — the anticipations and syncopations create a floating quality that transcends tempo. Samba at 120 BPM feels joyously propulsive because the polyrhythmic layers create an irresistible momentum. Funk carioca at 130 BPM feels relentless because the tamborzão allows no rhythmic escape.',
    weightAndMomentum: 'Bossa nova is weightless — it floats above the beat. Samba has celebratory momentum — it pulls you forward into the dance. Forró has earthy weight — the zabumba grounds everything. Funk carioca has mechanical momentum — the bass hits your body like a physical force.',
    urgencyScale: 'Low urgency in bossa nova (contemplative floating), moderate in pagode (relaxed socializing), high in samba de enredo (carnival energy), extreme in funk carioca (baile intensity), transcendent in batucada (collective rhythmic ecstasy).',
    comparisonToSameBPM: 'Samba at 110 BPM feels completely unlike American pop at 110 BPM — the ginga creates a rhythmic complexity that makes the music feel simultaneously faster and more relaxed. Bossa nova at 75 BPM feels more spacious than jazz at 75 BPM because the guitar anticipations stretch perceived time.',
  },

  mistakeConventions: {
    overview: 'In Brazilian music, the ginga itself is a "mistake" by Western quantization standards — the micro-timing deviations that create samba\'s swing would be "corrected" by a drum machine, and the music would die. The imperfection IS the art.',
    toleratedImperfections: [
      'pitch variation in samba when rhythmic delivery and emotional commitment are strong',
      'ensemble timing drift in batucada that creates organic polyrhythmic texture',
      'vocal roughness in pagode as marker of informal, authentic roda atmosphere',
      'slightly out-of-tune cavaquinho in samba as street-level authenticity',
      'audible finger noise on violão in bossa nova as intimate acoustic signature',
    ],
    celebratedFlaws: [
      'João Gilberto\'s seemingly "wrong" guitar anticipations that defined bossa nova',
      'Cartola\'s weathered, imperfect voice as the soul of samba',
      'Tom Zé\'s deliberately "ugly" sonic experiments as Tropicália genius',
      'Elis Regina\'s emotional vocal breaks that made audiences weep',
    ],
    overproductionRisks: [
      'quantizing samba percussion to a grid and killing the ginga',
      'pitch-correcting the micro-tonal variations that give Brazilian vocals character',
      'replacing live batucada with drum samples and losing the polyrhythmic interaction',
      'compressing bossa nova\'s intimate dynamic range into flat loudness',
      'straightening bossa nova\'s guitar anticipations into metronomic time',
    ],
    authenticRoughness: 'The most authentic Brazilian music sounds like human bodies creating rhythm together — the slight imperfections in timing between players are what create the ginga, and the ginga is what makes Brazilian music Brazilian. Remove the imperfection and you remove the soul.',
  },

  referenceTracks: [
    {
      title: 'Envolver',
      artist: 'Anitta',
      year: 2022,
      whyExemplary: 'First solo Latin artist to reach #1 on Spotify global — funk carioca rhythm exported worldwide without diluting its Rio favela DNA. Proved Brazilian pop could lead, not follow.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Funk carioca beat (batidão) drives everything. Short verses, hypnotic chorus repetition. Under 3 minutes — built for streaming and dancefloor.',
      craftHighlight: 'Rhythmic seduction — the batidão pattern does the emotional work. Lyrics are direct and physical; the groove carries the sensuality more than the words.',
    },
    {
      title: 'Baby 95',
      artist: 'Liniker',
      year: 2021,
      whyExemplary: 'Latin Grammy-winning MPB reinvention from a trans artist who brought queer Black Brazilian identity to the mainstream without compromise. Liniker\'s voice is a national treasure.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Soul/MPB hybrid arrangement: bass-driven groove, horns, keys. Liniker\'s vocal transitions between falsetto and chest voice across sections.',
      craftHighlight: 'Body as instrument — Liniker\'s vocal grain and timbral shifts carry emotional information that transcends the lyrics. The voice IS the composition.',
    },
    {
      title: 'Caju',
      artist: 'Liniker',
      year: 2023,
      whyExemplary: 'Latin Grammy Album of the Year track that uses the cashew fruit as metaphor for Bahian identity — sweet, complex, and deeply rooted. MPB\'s tradition of nature-as-self renewed.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-outro. Acoustic MPB arrangement with Bahian percussion. Mid-tempo groove with space for vocal expression.',
      craftHighlight: 'Fruit-as-identity metaphor following the MPB tradition (Caetano\'s "Sampa," Gil\'s "Toda Menina Baiana") — the cashew\'s characteristics map onto cultural identity without forcing the parallel.',
    },
    {
      title: 'Mal de Amor',
      artist: 'Marília Mendonça',
      year: 2021,
      whyExemplary: 'Posthumous release from the queen of feminejo who transformed sertanejo by centering women\'s heartbreak with raw honesty instead of romantic fantasy.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Sertanejo arrangement: acoustic guitar, accordion, viola caipira. Mendonça\'s voice carries the storytelling over minimal production.',
      craftHighlight: 'Feminine reclamation of sertanejo heartbreak — instead of the traditional male lament, Mendonça writes from the woman who left, not the one left behind.',
    },
    {
      title: 'Batom de Cereja',
      artist: 'Israel & Rodolffo',
      year: 2021,
      whyExemplary: 'Sertanejo universitário hit that captured post-pandemic party energy. The cherry lipstick image anchors an entire narrative of desire in a single sensory detail.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Up-tempo sertanejo with pop production. Duo harmonies on chorus. Designed for live performance singalong.',
      craftHighlight: 'Sensory specificity — "batom de cereja" (cherry lipstick) is a single concrete image that carries the whole song. You can see, smell, and taste the moment.',
    },
    {
      title: 'Idiota',
      artist: 'Jão',
      year: 2021,
      whyExemplary: 'Brazilian pop breakthrough that brought vulnerability to male pop vocals. Jão\'s confessional writing opened space for emotional honesty in Brazilian mainstream.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Pop-rock arrangement with synths and guitars. Builds from intimate verse to anthemic chorus.',
      craftHighlight: 'Self-deprecation as honesty — calling yourself "idiota" for still loving someone is a vulnerability move that Brazilian male pop rarely makes. The self-awareness IS the hook.',
    },
    {
      title: 'Proibido o Carnaval',
      artist: 'Caetano Veloso',
      year: 2021,
      whyExemplary: 'MPB master reflecting on pandemic-era Carnival prohibition — the absence of Brazil\'s greatest celebration as existential crisis. Only Caetano could make this political AND beautiful.',
      structuralNotes: 'Through-composed with recurring melodic motif. Acoustic guitar and voice — classic Caetano format. Sections flow without traditional pop structure.',
      craftHighlight: 'Absence as subject — a song about what ISN\'T happening (Carnival) creates presence through negation. The silence where the drums should be is the emotional core.',
    },
    {
      title: 'Aquariana',
      artist: 'Djavan',
      year: 2022,
      whyExemplary: 'Late-career masterwork from one of MPB\'s greatest melodists — proves that Djavan\'s harmonic sophistication remains unmatched in Brazilian popular music.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-instrumental-chorus. Jazz-MPB arrangement with sophisticated chord voicings. Djavan\'s guitar and vocal carry the melody over lush production.',
      craftHighlight: 'Harmonic richness — Djavan\'s chord progressions are the most jazz-influenced in MPB, creating melodic movement that surprises without disorienting. Each chord change tells a story.',
    },
    {
      title: 'No Chão Não',
      artist: 'MC Rebecca',
      year: 2022,
      whyExemplary: 'Funk carioca empowerment anthem that reclaims the genre\'s body-positive tradition. Rebecca\'s writing centers female pleasure in a genre often dominated by male perspective.',
      structuralNotes: 'Intro-verse-chorus-verse-chorus-outro. Funk carioca batidão with heavy bass. Call-and-response structure between Rebecca and backing vocals. Under 3 minutes.',
      craftHighlight: 'Feminine agency in funk — the dance commands ("no chão não" = not on the floor) assert physical autonomy. The woman directs the movement, not the man.',
    },
    {
      title: 'Mil Veces',
      artist: 'Anitta',
      year: 2023,
      whyExemplary: 'Brazilian pop in Spanish that proved Anitta\'s multilingual versatility. Merges Brazilian rhythmic DNA with Latin pop melody writing.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Latin pop production with Brazilian percussion undertones. Bilingual sections (Portuguese/Spanish) within single verses.',
      craftHighlight: 'Code-switching as identity — singing in both Portuguese and Spanish reflects the real linguistic experience of Latin America\'s borders. The language shifts follow emotional logic.',
    },
    {
      title: 'São Amores',
      artist: 'Pabllo Vittar',
      year: 2023,
      whyExemplary: 'Forró-pop fusion from the world\'s most-followed drag queen. Vittar brought northeastern Brazilian tradition to global pop audiences with queer joy.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Forró rhythm (zabumba, triangle, accordion) with pop production overlay. Dancefloor-ready BPM.',
      craftHighlight: 'Regional rhythm as pop foundation — the forró groove isn\'t decoration, it\'s the engine. Vittar proves northeastern Brazilian rhythms are inherently pop-ready.',
    },
    {
      title: 'Bandido',
      artist: 'Zé Felipe & MC Mari',
      year: 2021,
      whyExemplary: 'Sertanejo-funk fusion that captured the genre-blurring moment in Brazilian music. Two traditions that shouldn\'t mix on paper became the biggest hit of the year.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Sertanejo melody over funk carioca beat. Male/female vocal trade mirrors the lyric\'s romantic tension.',
      craftHighlight: 'Genre fusion as cultural document — the sertanejo (rural) and funk (urban) merger reflects real demographic shifts in Brazil. The music follows where the people already are.',
    },
    {
      title: 'Escravos de Jó',
      artist: 'Emicida ft. Majur & Pabllo Vittar',
      year: 2021,
      whyExemplary: 'Hip-hop/MPB fusion that transforms a children\'s game song into a meditation on systemic racism. Emicida\'s writing finds political depth in folk tradition.',
      structuralNotes: 'Intro (children\'s melody)-verse-chorus-verse-chorus-bridge-chorus. The familiar melody is deconstructed and rebuilt with new meaning. Three vocalists represent different perspectives.',
      craftHighlight: 'Folk-song subversion — taking "Escravos de Jó" (a song about slavery that children sing unknowingly) and making its origins visible. The familiar melody carries uncomfortable truth.',
    },
    {
      title: 'Balança',
      artist: 'Ivete Sangalo',
      year: 2023,
      whyExemplary: 'Axé queen delivering a Carnival anthem that proves the form\'s continued vitality. Sangalo\'s voice and energy make the formula feel fresh rather than recycled.',
      structuralNotes: 'Intro-verse-chorus-verse-chorus-bridge-vamp. Axé arrangement: horn section, percussion ensemble, call-and-response. Built for live performance with crowd participation sections.',
      craftHighlight: 'Carnival engineering — the song is designed for a specific physical context (street Carnival) with specific functions (move, respond, celebrate). Form follows function.',
    },
    {
      title: 'Me Leva Pra Casa',
      artist: 'Péricles',
      year: 2022,
      whyExemplary: 'Pagode at its most romantic and sophisticated — Péricles\' voice turns a simple request ("take me home") into an entire emotional landscape.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Pagode arrangement: cavaquinho, tan-tan, surdo, acoustic guitar. Péricles\' vocal ad-libs weave through the arrangement.',
      craftHighlight: 'Vocal interpretation as composition — the written melody is simple but Péricles\' phrasing, ad-libs, and emotional inflections create a second, unwritten melody on top.',
    },
    {
      title: 'Ouro Marrom',
      artist: 'Alcione',
      year: 2022,
      whyExemplary: 'Samba veteran celebrating Black beauty with the metaphor "brown gold" — a declaration of value that\'s political, personal, and musical simultaneously.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Classic samba arrangement: cavaquinho, surdo, tamborim, brass. Alcione\'s voice dominates the mix with samba phrasing.',
      craftHighlight: 'Metaphor as reclamation — "ouro marrom" (brown gold) inverts colonial extraction (gold from Brazil) to declare Black Brazilian beauty as the real treasure.',
    },
    {
      title: 'Acalanto',
      artist: 'Adriana Calcanhotto',
      year: 2022,
      whyExemplary: 'Bossa nova revival from a master interpreter — Calcanhotto\'s whispered delivery and nylon guitar prove the form\'s intimacy remains unmatched.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Classic bossa nova format: nylon guitar, light percussion, voice. Minimal arrangement. The silences are as composed as the notes.',
      craftHighlight: 'Bossa nova\'s "less is more" principle at its purest — every note earns its place. The whispered vocal creates intimacy that louder delivery would destroy.',
    },
    {
      title: 'Deus Me Proteja',
      artist: 'Chico César & Xamã',
      year: 2023,
      whyExemplary: 'MPB master meets hip-hop MC — generational and genre crossover that proves Brazilian music\'s traditions can absorb any influence and remain themselves.',
      structuralNotes: 'Verse (César)-verse (Xamã)-chorus-verse-verse-chorus-bridge. Each artist brings their genre\'s delivery style over a hybrid arrangement. The chorus is where they meet.',
      craftHighlight: 'Generational dialogue as composition — the contrast between César\'s MPB phrasing and Xamã\'s rap flow creates meaning beyond what either could achieve alone.',
    },
    {
      title: 'Tudo Sobre Nada',
      artist: 'Tom Zé',
      year: 2022,
      whyExemplary: 'Tropicália pioneer in his 80s still experimenting — proves that Brazilian music\'s avant-garde tradition remains its most vital creative engine.',
      structuralNotes: 'Non-standard: collage of spoken word, sung fragments, found sound, and instrumental passages. No traditional verse-chorus. Each section follows its own logic.',
      craftHighlight: 'Anti-structure as Brazilian tradition — Tropicália\'s legacy of eating and transforming foreign influences is enacted in the song\'s refusal to follow any single genre\'s rules.',
    },
    {
      title: 'Cachimbo da Paz',
      artist: 'Gabriel O Pensador ft. Lulu Santos',
      year: 2023,
      whyExemplary: 'Pop-rock collaboration between rap veteran and rock legend — the "peace pipe" metaphor bridges generational and genre divides in Brazilian music.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Pop-rock arrangement with rap verses and sung choruses. Gabriel raps, Lulu sings — their styles alternate rather than blend.',
      craftHighlight: 'Collaboration as metaphor — two artists from different traditions sharing a "peace pipe" enacts the unity the song describes. The medium is the message.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: [
      'Brazilian', 'bossa nova', 'samba',
      'Portuguese vocals', 'nylon guitar', 'percussion',
      'tropical', 'Rio de Janeiro',
    ],
    avoidKeywords: [
      'mariachi', 'flamenco', 'country twang',
      'heavy metal', 'Celtic', 'Japanese',
    ],
    promptTemplate: '[sub-genre] Brazilian music, [BPM] BPM, [mood], [key instruments], Portuguese vocals, [regional reference]',
    tips: [
      'Always specify the sub-genre — bossa nova and funk carioca are completely different worlds.',
      'For bossa nova: "intimate", "nylon guitar", "whispered vocal", "jazz harmony".',
      'For samba: "batucada percussion", "cavaquinho", "syncopated 2/4".',
      'For funk carioca: "tamborzão beat", "heavy bass", "MC vocals", "baile funk".',
    ],
  },
};
