import type { GenreGuide } from './types';

export const COUNTRY_GUIDE: GenreGuide = {
  id: 'country',
  name: 'Country',
  language: 'English',

  sonicPalette: {
    overview: 'Warm, organic, and storytelling-driven. Country music centers on acoustic and steel guitars, fiddle, and clear vocals telling stories of love, loss, and small-town life. The sound is earthy and honest — instruments sound like themselves, not processed beyond recognition.',
    timbre: [
      'Bright acoustic guitar (dreadnought strumming or fingerpicking)',
      'Pedal steel guitar (crying, sliding tones)',
      'Fiddle/violin with country bowing technique',
      'Twangy electric guitar (Telecaster through clean amp)',
      'Warm, clear vocals with natural tone',
      'Upright or electric bass with round tone',
      'Banjo (clawhammer or three-finger picking)',
      'Dobro/resonator guitar',
    ],
    texture: 'Clean and transparent — every instrument is clearly audible and occupies its own space. Minimal processing. The arrangement serves the story. Acoustic instruments provide warmth while electric instruments add color.',
    tonality: 'Major keys dominate (G, C, D, A, E — guitar-friendly open keys). Minor keys for sadder material. Bright, clear tonality. The major pentatonic scale gives country its optimistic character.',
    signatureSounds: [
      'Pedal steel bends and swells',
      'Telecaster chicken-picking',
      'Fiddle double-stops',
      'Banjo rolls',
      'Acoustic guitar boom-chuck pattern',
      'Harmonica fills',
      'Train rhythm patterns',
    ],
  },

  rhythmAndGroove: {
    overview: 'Steady, driving, and danceable. Country rhythm comes from the "boom-chuck" pattern — bass note on beats 1 and 3, chord strum on 2 and 4. This creates a natural, swaying groove that supports storytelling.',
    bpmRange: { min: 80, max: 160, sweet: 120 },
    feel: 'Steady and grounded. Even uptempo country maintains a relaxed, unhurried quality. The groove should feel like a pickup truck on a back road — moving forward with purpose but not in a rush.',
    swing: 'Moderate shuffle swing in traditional and honky-tonk. Straight 8ths in modern country-pop. Train beat (driving shuffle) is a classic country feel.',
    syncopation: 'Minimal — country rhythm is straightforward and predictable by design. Some syncopation in vocal melodies. Chicken-picking guitar creates subtle rhythmic interest.',
    grooveArchetype: 'Boom-chuck waltz or two-step, train beat shuffle, or modern country-rock drive',
    rhythmicSignatures: [
      'Boom-chuck bass/strum pattern',
      'Train beat (driving snare shuffle)',
      '3/4 waltz time for ballads',
      'Two-step dance rhythm',
      'Brushed snare in ballads',
      'Bass walks between chord changes',
      'Kick-snare pattern with cross-stick',
    ],
  },

  harmonicLanguage: {
    overview: 'Simple, direct, and emotionally effective. Country harmony uses basic major and minor chords in predictable but satisfying progressions. The I-IV-V framework is the foundation — variations add emotion without complexity.',
    scales: ['Major (Ionian)', 'Mixolydian', 'Pentatonic Major', 'Natural Minor', 'Blues Scale'],
    chordProgressions: [
      'I – IV – V – I (classic country)',
      'I – V – I – IV (verse pattern)',
      'I – vi – IV – V (country-pop)',
      'I – IV – I – V (simple two-chord feel)',
      'ii – V – I (turnaround)',
      'I – I7 – IV – iv – I (country blues)',
      'I – bVII – IV – I (country-rock)',
    ],
    harmonyNotes: 'Open chord voicings with ringing strings. Suspended chords for emotional tension. Walk-up and walk-down bass lines connect chords. The IV-I plagal cadence is a country staple. Seventh chords add blues flavor.',
    modality: 'Primarily major. Mixolydian (major with flat 7th) creates the classic country-rock sound. Minor for heartbreak songs. The major pentatonic scale defines the optimistic country melody.',
  },

  songStructure: {
    overview: 'Story-driven structure — country songs are built around narrative. Verses tell the story, choruses deliver the emotional thesis, and bridges provide a twist or revelation. The song must serve the lyric.',
    form: 'Verse – Chorus – Verse – Chorus – Bridge – Chorus (with instrumental interludes)',
    sections: ['Intro', 'Verse 1', 'Chorus', 'Verse 2', 'Chorus', 'Bridge/Instrumental Solo', 'Final Chorus', 'Outro/Tag'],
    arrangement: 'Builds gradually — verse starts with fewer instruments, chorus adds fullness. Instrumental solos (fiddle, steel guitar, electric guitar) between sections. The arrangement never overwhelms the vocal.',
    introOutro: 'Intros: often the signature riff (guitar or fiddle), or stripped acoustic opening. Outros: tag the chorus hook, fade out, or end with a final lyrical punch.',
    barLengths: 'Verses: 8-16 bars. Chorus: 8 bars. Bridge: 4-8 bars. Solo: 8 bars. Total: 3-4 minutes.',
    hookPlacement: 'Title phrase in the chorus (usually first or last line). Some country songs use the title as the last line of each verse instead (AAA form). The lyrical hook is paramount.',
  },

  vocalDelivery: {
    overview: 'Clear, honest, and emotionally direct. Country vocals tell stories — clarity of diction is essential. A slight Southern accent or twang is authentic but should feel natural, not affected. The voice conveys sincerity above all.',
    phrasing: 'Conversational and natural — phrasing follows speech patterns. Stories unfold naturally across verses. The melody serves the lyric, not the other way around. Breathing between phrases feels natural.',
    affect: 'Sincere, heartfelt, and emotionally present. Country singers communicate genuine feeling — joy, heartache, pride, nostalgia. The emotion should feel lived-in, not performed.',
    techniques: [
      'Natural twang (slight nasal resonance)',
      'Clear diction for storytelling',
      'Yodeling or vocal breaks (traditional)',
      'Cry in the voice (emotional break)',
      'Belt singing in choruses',
      'Talk-singing in verses (spoken word phrasing)',
      'Vocal slides between notes',
      'Harmony singing (high lonesome or close harmony)',
    ],
    adlibStyle: 'Minimal — country values restraint. "Yeah," "mm-hmm," and spoken asides. Some yeehaw or whoop exclamations in uptempo songs. Gospel-influenced "oh Lord" in emotional moments.',
    harmony: 'Tight two-part and three-part harmonies — often in 3rds. The "high lonesome sound" (high tenor harmony). Male-female duet harmonies. Background vocals are supportive, not showy.',
    grit: 'Moderate — some natural rasp is authentic (Johnny Cash, Chris Stapleton). Too much polish feels inauthentic. Too much grit crosses into rock. The sweet spot is a lived-in voice with character.',
  },

  lyricalConventions: {
    overview: 'Country is the great storytelling genre. Lyrics paint vivid pictures of real life — specific details, honest emotions, and relatable situations. A great country lyric tells a story so specific it becomes universal.',
    themes: [
      'Small-town life and rural imagery',
      'Love and heartbreak',
      'Family and home',
      'Drinking (beer, whiskey, honky-tonks)',
      'Faith and God',
      'Trucks, roads, and travel',
      'Working-class pride',
      'Nostalgia and memory',
      'Loss and grief',
      'American identity and patriotism',
    ],
    perspective: 'First person storytelling or first person address to a lover. Some third-person character studies. The narrator\'s voice is authentic and specific.',
    figurativeLanguage: 'Concrete, vivid imagery — dirt roads, Friday nights, porch swings, old trucks. Nature metaphors (rivers, mountains, storms). Similes more common than abstract metaphors. The imagery should be cinematic and specific.',
    vocabulary: 'Conversational, colloquial, regional. Contractions and informal speech patterns. Rural and agricultural vocabulary. Brand names (Chevy, Wrangler, Bud Light). Simple words expressing deep emotions.',
    storytellingApproach: 'Narrative-driven — many country songs tell a complete story with characters, setting, conflict, and resolution. Each verse advances the plot. The chorus is the emotional thesis. The bridge provides a twist.',
    cliches: [
      'Cold beer on a Friday night',
      'Dirt roads and back roads',
      'Tailgate of a pickup truck',
      'Small town Saturday night',
      'Mama\'s prayers',
      'She left me for somebody else',
      'Boots, jeans, and cowboy hats',
    ],
  },

  productionFingerprint: {
    overview: 'Clean, warm, and organic. Country production serves the song and the story. Instruments should sound natural and present. Modern country has incorporated pop and rock production techniques while maintaining acoustic foundations.',
    mixAesthetic: 'Vocal-forward — the story must be clearly heard. Acoustic instruments with natural room sound. Clean, transparent mix. Bass and drums provide foundation without dominating. Steel guitar and fiddle add color.',
    era: 'Current era: country-pop crossover, stadium country, bro-country influence fading, return to traditional sounds (Americana movement), Morgan Wallen/Luke Combs blue-collar revival.',
    signalChain: 'Vocals: large-diaphragm condenser → warm preamp → gentle compression → minimal EQ. Acoustic guitar: small-diaphragm condenser. Electric: Telecaster → clean Fender amp. Drums: natural room sound, not over-compressed.',
    modernTrends: 'Genre-blending (country-rap, country-pop, country-rock). Production polish approaching pop. Drum loops and programmed beats in modern country. Arena-ready mixes. Americana as alternative to Nashville mainstream.',
  },

  instrumentation: {
    coreInstruments: [
      'Acoustic guitar (dreadnought)',
      'Electric guitar (Fender Telecaster)',
      'Pedal steel guitar',
      'Fiddle/violin',
      'Bass (upright or electric)',
      'Drums / brushed percussion',
      'Banjo',
      'Dobro/resonator guitar',
    ],
    signatureSounds: [
      'Telecaster chicken-picking',
      'Pedal steel crying bends',
      'Fiddle fills and solos',
      'Banjo three-finger rolls',
      'Acoustic guitar boom-chuck',
      'Harmonica fills',
      'Mandolin tremolo',
    ],
    layering: 'Transparent — each instrument is clearly heard. Acoustic guitar provides the rhythmic foundation. Electric guitar adds fills and solos. Steel guitar and fiddle provide color and emotion. Less is more.',
    avoidInstruments: [
      'Heavy synthesizers (unless modern country-pop)',
      'Heavily distorted guitars',
      'Electronic drum machines (traditional)',
      'Auto-Tune (breaks authenticity)',
      'Orchestral arrangements (unless crossover)',
    ],
  },

  culturalContext: {
    overview: 'Country music is rooted in rural American identity — working-class values, family, faith, and the land. It represents a specific cultural tradition while evolving to include diverse voices and modern themes.',
    origin: 'Appalachian folk traditions, African American blues, and gospel music converging in the American South and West. Commercialized from the 1920s through radio and Nashville.',
    identity: 'Working-class, rural, American. Country represents heartland values — authenticity, hard work, faith, family. The genre has historically been white-dominated but is diversifying.',
    community: 'Country music fans are loyal and community-oriented. Country radio is still influential. Live music culture (honky-tonks, festivals, county fairs). Nashville as the industry hub.',
    socialFunction: 'Soundtrack to rural and small-town American life. Wedding songs, funeral songs, drinking songs. Country tells the stories of everyday people. Communal experience at concerts and festivals.',
    authenticityMarkers: [
      'Genuine connection to rural/small-town life',
      'Honest songwriting from personal experience',
      'Natural vocal delivery without excessive processing',
      'Respect for country music traditions',
      'Live musicianship and real instruments',
      'Storytelling ability',
    ],
  },

  historicalLineage: {
    overview: 'From Appalachian folk to Nashville Sound to modern stadium country, the genre has evolved while maintaining its storytelling soul.',
    roots: ['Appalachian Folk', 'Blues', 'Gospel', 'Western Swing', 'Honky-Tonk'],
    evolution: 'Hillbilly music (1920s-30s) → Honky-tonk and Western swing (40s-50s) → Nashville Sound (60s) → Outlaw country (70s) → New Traditionalism (80s) → Hat acts and country-pop (90s) → Bro-country and stadium country (2010s) → Genre-fluid modern country (2020s).',
    keyEras: [
      '1920s-30s: Jimmie Rodgers, Carter Family',
      '1950s: Hank Williams, honky-tonk golden age',
      '1960s: Nashville Sound (Patsy Cline, Jim Reeves)',
      '1970s: Outlaw country (Willie, Waylon, Merle)',
      '1990s: Garth Brooks and new country explosion',
      '2010s-present: Bro-country, Americana, modern crossover',
    ],
    influencedBy: ['Folk', 'Blues', 'Gospel', 'Western Swing', 'Rock and Roll'],
    influenced: ['Rock', 'Americana', 'Pop-Country', 'Country-Rap', 'Alt-Country'],
  },

  subGenres: [
    {
      name: 'Traditional Country',
      description: 'The classic sound — acoustic instruments, honest storytelling, and simple arrangements. Fiddle, steel guitar, and clear vocals over boom-chuck rhythms.',
      distinguishingFeatures: ['Acoustic instrument focus', 'Clear storytelling lyrics', 'Fiddle and steel guitar', 'Simple arrangements', 'Natural vocal delivery'],
      bpmRange: { min: 90, max: 130 },
      keyArtists: ['George Jones', 'Merle Haggard', 'Alan Jackson', 'George Strait', 'Randy Travis'],
      productionNotes: 'Clean, transparent production. Real instruments. Vocal-forward mix. Traditional boom-chuck rhythm. Fiddle and steel guitar fills. No electronic elements.',
      lyricNotes: 'Classic country storytelling — heartbreak, drinking, working-class life. Specific imagery. Sincere emotional delivery.',
      sunoPromptKeywords: ['traditional country', 'classic country', 'honky-tonk', 'fiddle', 'steel guitar', 'twangy', 'country ballad'],
    },
    {
      name: 'Outlaw Country',
      description: 'Rebellious country that rejects Nashville polish for raw, rock-influenced authenticity. Rough edges, attitude, and artistic independence.',
      distinguishingFeatures: ['Rock-influenced edge', 'Anti-Nashville establishment', 'Rough vocal delivery', 'Simplified arrangements', 'Outlaw persona and lyrics'],
      bpmRange: { min: 90, max: 140 },
      keyArtists: ['Willie Nelson', 'Waylon Jennings', 'Merle Haggard', 'Chris Stapleton', 'Sturgill Simpson'],
      productionNotes: 'Raw, unpolished sound. Rock-influenced guitar tone. Simple, driving arrangements. Less fiddle and steel, more electric guitar. Live feel.',
      lyricNotes: 'Freedom, rebellion, road life, drinking, defiance. Anti-authority. Rough-hewn poetry. Character-driven.',
      sunoPromptKeywords: ['outlaw country', 'country rock', 'rebel country', 'raw country', 'whiskey country', 'gritty'],
      embodiedDelta: {
        socioeconomicSubtext: {
          materialConditions: 'Road life economics — touring musicians living in vans, rejection of Nashville wealth and corporate music machinery',
          classIdentity: 'Working-class rebellion against Music Row elites — the outlaw stance is anti-corporate, not anti-mainstream',
          politicalUndercurrent: 'Libertarian individualism — "don\'t tell me what to do" applies to Nashville executives and government alike',
        },
        mistakeConventions: {
          authenticRoughness: 'Rough vocal delivery is the credential — too-clean singing signals Nashville compliance',
          toleratedImperfections: ['Gravelly voice from hard living', 'Slightly out-of-tune guitar', 'Loose ensemble timing'],
          overproductionRisks: ['Nashville string sections', 'Auto-tuned vocals', 'Click-track precision', 'Pop-style backing vocals'],
        },
        performancePractice: {
          crowdInteraction: 'Irreverent — storytelling between songs, whiskey on stage, anti-professionalism as brand',
          improvisationConventions: 'Extended jam endings and guitar solos common; the live show is rawer and longer than the record',
        },
      },
    },
    {
      name: 'Country Pop',
      description: 'Country music with pop production values and crossover appeal. Polished, radio-friendly, and accessible to mainstream audiences.',
      distinguishingFeatures: ['Pop production techniques', 'Crossover appeal', 'Polished vocals', 'Radio-friendly hooks', 'Blended acoustic/electronic elements'],
      bpmRange: { min: 100, max: 135 },
      keyArtists: ['Taylor Swift (early)', 'Shania Twain', 'Carrie Underwood', 'Keith Urban', 'Kacey Musgraves'],
      productionNotes: 'Pop-level polish with country instruments. Big choruses. Production can include electronic elements. Hook-driven songwriting. Arena-ready mix.',
      lyricNotes: 'Relatable, universally appealing themes. Love and empowerment. Less drinking/truck clichés, more emotional accessibility.',
      sunoPromptKeywords: ['country pop', 'modern country', 'crossover country', 'Nashville pop', 'radio country', 'polished'],
    },
    {
      name: 'Bro-Country',
      description: 'Party-oriented country celebrating trucks, beer, dirt roads, and summer nights. Uptempo, rock-influenced, and designed for tailgating.',
      distinguishingFeatures: ['Party anthems', 'Truck/beer/girl lyrical formula', 'Rock-influenced production', 'Hip-hop rhythmic influence', 'Summer/outdoor themes'],
      bpmRange: { min: 120, max: 145 },
      keyArtists: ['Luke Bryan', 'Florida Georgia Line', 'Jason Aldean', 'Thomas Rhett', 'Sam Hunt'],
      productionNotes: 'Rock-influenced drums and guitars. Hip-hop rhythmic patterns sometimes. Big, loud, arena-ready. Pop hooks with country instrumentation.',
      lyricNotes: 'Party lifestyle — trucks, cold beer, dirt roads, pretty girls, summer nights. Celebratory and carefree.',
      sunoPromptKeywords: ['bro-country', 'country party', 'tailgate anthem', 'truck song', 'summer country', 'uptempo country'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Hip-hop rhythmic influence — programmed drums and beat-forward production replace organic country shuffle',
          humanizationMarkers: ['Snare-forward mix borrowed from pop/hip-hop', 'Programmed hi-hat patterns', 'Beat drops between sections'],
        },
        socioeconomicSubtext: {
          classIdentity: 'Suburban/fraternity culture cosplaying rural — trucks as lifestyle accessories, not work vehicles',
          materialConditions: 'Material abundance on display — the opposite of traditional country\'s hardship narratives',
        },
        mistakeConventions: {
          overproductionRisks: ['Overproduction is embraced — arena-ready polish is the goal, not a risk'],
          authenticRoughness: 'Roughness is minimal — the aesthetic is polished party energy, not lived-in grit',
        },
        intertextualityAndSampling: {
          lineageSignifiers: ['Florida Georgia Line pop-country crossover', 'Sam Hunt\'s hip-hop cadence', 'Arena rock chorus structures'],
          canonKnowledge: 'References are to lifestyle (tailgating, small towns) not to country music history — knowing Hank Williams is optional',
        },
      },
    },
    {
      name: 'Americana',
      description: 'Roots-oriented music blending country, folk, blues, and rock into a cohesive Americana sound. Values authenticity and artistic depth over commercial appeal.',
      distinguishingFeatures: ['Roots music blend (country/folk/blues/rock)', 'Artistic depth and authenticity', 'Alternative to mainstream Nashville', 'Literary lyrics', 'Organic production'],
      bpmRange: { min: 70, max: 130 },
      keyArtists: ['Jason Isbell', 'Brandi Carlile', 'Tyler Childers', 'Sturgill Simpson', 'The Avett Brothers'],
      productionNotes: 'Organic, live-feeling production. Real instruments. Room sound. Warm, analog aesthetic. Prioritize feel over polish.',
      lyricNotes: 'Literary, introspective, socially aware. Small-town realism. Working-class stories. Nuanced emotional complexity. Poetic.',
      sunoPromptKeywords: ['Americana', 'roots music', 'folk country', 'rootsy', 'alt-country', 'folk rock', 'authentic'],
      embodiedDelta: {
        intertextualityAndSampling: {
          canonKnowledge: 'Deep roots knowledge required — Woody Guthrie, Townes Van Zandt, Emmylou Harris; the tradition is the credential',
          lineageSignifiers: ['Woody Guthrie protest lineage', 'Gram Parsons cosmic American music', 'Emmylou Harris vocal tradition', 'Appalachian folk roots'],
          quotationPractice: 'Covering traditional songs signals connection to the lineage; original songs must feel like they could be traditional',
        },
        mistakeConventions: {
          authenticRoughness: 'Warm analog imperfection — the recording should sound like a room, not a studio; tape hiss is welcome',
          overproductionRisks: ['Digital precision', 'Pop-level compression', 'Synthetic elements', 'Quantized drums'],
          celebratedFlaws: ['Finger squeaks on guitar strings', 'Breath sounds', 'Slight vocal pitch drift on long notes'],
        },
        socioeconomicSubtext: {
          classIdentity: 'Working-class storytelling without romanticization — the poverty is real, not aesthetic; opioid crisis, factory closures, economic abandonment',
          materialConditions: 'Small-town economic decline as lyrical landscape; the music carries the weight of places left behind',
        },
      },
    },
    {
      name: 'Bluegrass',
      description: 'Fast, virtuosic acoustic string music rooted in Appalachian tradition. Banjo, fiddle, mandolin, and guitar in intricate interplay.',
      distinguishingFeatures: ['All-acoustic instrumentation', 'Virtuosic picking and bowing', 'High lonesome vocal harmonies', 'Fast tempos', 'String band ensemble'],
      bpmRange: { min: 120, max: 200 },
      keyArtists: ['Bill Monroe', 'Earl Scruggs', 'Alison Krauss', 'Chris Thile', 'Billy Strings'],
      productionNotes: 'Pure acoustic recording. Minimal processing. Natural room sound. Each instrument clearly audible. Live feel with ensemble interplay.',
      lyricNotes: 'Mountain life, faith, love, tragedy. Traditional storytelling. High lonesome emotional intensity. Murder ballads and gospel songs.',
      sunoPromptKeywords: ['bluegrass', 'acoustic', 'banjo', 'mandolin', 'fiddle', 'fast picking', 'string band', 'Appalachian'],
    },
    {
      name: 'Country Rock',
      description: 'Rock energy and electric instruments married with country songwriting and twang. The bridge between Nashville and rock and roll.',
      distinguishingFeatures: ['Electric guitar with country licks', 'Rock energy with country songs', 'Driving drums', 'Southern rock influence', 'Electric and acoustic blend'],
      bpmRange: { min: 110, max: 150 },
      keyArtists: ['Eagles', 'Gram Parsons', 'Lynyrd Skynyrd', 'Marshall Tucker Band', 'Midland'],
      productionNotes: 'Rock-level energy with country instruments. Electric guitar with twang. Driving drums. Steel guitar optional. Full band sound.',
      lyricNotes: 'Country themes with rock attitude. Freedom, road life, love. Less sentimental than traditional country.',
      sunoPromptKeywords: ['country rock', 'Southern rock', 'rock country', 'electric country', 'outlaw rock', 'driving'],
    },
    {
      name: 'Red Dirt',
      description: 'Independent country from Texas and Oklahoma — rawer and more rock-influenced than Nashville, with strong regional identity.',
      distinguishingFeatures: ['Texas/Oklahoma regional identity', 'Independent from Nashville mainstream', 'Rock and blues influence', 'Live music culture', 'Dancehall traditions'],
      bpmRange: { min: 100, max: 140 },
      keyArtists: ['Turnpike Troubadours', 'Cross Canadian Ragweed', 'Stoney LaRue', 'Cody Jinks', 'Cody Johnson'],
      productionNotes: 'Live-sounding, raw production. Real instruments. Texas-influenced guitar tones. Dancehall-friendly grooves. Authentic and unpolished.',
      lyricNotes: 'Texas/Oklahoma life, working class, love, drinking, independence. Regional pride. Honest and unvarnished.',
      sunoPromptKeywords: ['Red Dirt country', 'Texas country', 'Oklahoma country', 'independent country', 'dancehall country'],
    },
    {
      name: 'Alt-Country',
      description: 'Alternative approach to country blending punk attitude, indie sensibility, and roots authenticity. Rebels against Nashville commercialism.',
      distinguishingFeatures: ['Punk/indie influence on country', 'Anti-Nashville ethos', 'Raw, honest songwriting', 'Eclectic instrumentation', 'Artistic experimentation'],
      bpmRange: { min: 80, max: 150 },
      keyArtists: ['Uncle Tupelo', 'Wilco', 'Drive-By Truckers', 'Lucinda Williams', 'Ryan Adams'],
      productionNotes: 'Raw or experimental production. Mix of acoustic and electric. Punk energy with country instruments. No rules — whatever serves the song.',
      lyricNotes: 'Literary, unflinching, emotional. Darker themes than mainstream country. Working-class realism without sentimentality. Punk directness.',
      sunoPromptKeywords: ['alt-country', 'alternative country', 'insurgent country', 'roots punk', 'country punk', 'lo-fi country'],
    },
    {
      name: 'Honky-Tonk',
      description: 'Bar-room country music — meant for dancing, drinking, and heartbreak. Piano, fiddle, and steel guitar over shuffled rhythms.',
      distinguishingFeatures: ['Shuffled dance rhythms', 'Honky-tonk piano', 'Steel guitar and fiddle', 'Drinking and heartbreak lyrics', 'Dance-floor energy'],
      bpmRange: { min: 120, max: 160 },
      keyArtists: ['Hank Williams', 'Ernest Tubb', 'Dwight Yoakam', 'Dale Watson', 'Charley Crockett'],
      productionNotes: 'Shuffled rhythm. Prominent piano (honky-tonk style). Fiddle and steel guitar fills. Live, danceable energy. Simple arrangements.',
      lyricNotes: 'Drinking, dancing, heartbreak, cheating. Bar-room stories. Working-class Friday night. Humor and sadness in equal measure.',
      sunoPromptKeywords: ['honky-tonk', 'country shuffle', 'barroom country', 'dancehall', 'country swing', 'two-step'],
      embodiedDelta: {
        regionalDialectSpecificity: {
          accentInfluence: 'Texas/Bakersfield twang is the honky-tonk accent — nasal delivery, hard consonants, vowel bending',
          dialectVocabulary: ['honky-tonk', 'jukebox', 'sawdust floor', 'last call', 'two-step'],
          phoneticMarkers: ['Hard nasal twang', 'Elongated vowels on emotional words', 'Yodeling breaks'],
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Country shuffle — the tripleted swing feel driving two-step dancing; the groove is for feet, not headphones',
          aheadBehindBeat: 'Piano and drums push slightly ahead, steel guitar drags behind — creates a rolling, danceable tension',
        },
        performancePractice: {
          crowdInteraction: 'Bar-room intimacy — the performer is on a small stage, audience is dancing; requests are shouted and honored',
          whatMakesAGoodShow: 'When the dance floor stays full and the bartender stays busy — success is measured by movement and joy',
        },
        instrumentation: {
          coreInstruments: ['Honky-tonk piano (slightly out of tune preferred)', 'Pedal steel guitar', 'Fiddle', 'Standup bass', 'Simple drum kit'],
          signatureSounds: ['Bar-room piano rolls', 'Steel guitar crying', 'Fiddle fills between vocal lines'],
        },
      },
    },
    {
      name: 'Western Swing',
      description: 'Jazz-influenced country dance music — swing rhythms with country instrumentation. A unique fusion of big band jazz and Texas country.',
      distinguishingFeatures: ['Swing rhythms', 'Jazz-influenced harmonies', 'Fiddle and steel guitar solos', 'Dance-oriented', 'Big band country'],
      bpmRange: { min: 120, max: 180 },
      keyArtists: ['Bob Wills', 'Asleep at the Wheel', 'Ray Benson', 'Hot Club of Cowtown'],
      productionNotes: 'Swing feel. Jazz-influenced chord progressions. Fiddle and steel guitar trading solos. Full band with possible horns. Dance-floor energy.',
      lyricNotes: 'Dancing, love, good times. Light-hearted and celebratory. Swing-era sensibility with country flavor.',
      sunoPromptKeywords: ['Western swing', 'country swing', 'Texas swing', 'jazz country', 'swing band', 'danceable country'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Country fans are among the most loyal in music. The audience is predominantly American, spans rural and suburban demographics, and values authenticity and tradition while embracing evolution.',
    fanExpectations: [
      'Authentic storytelling',
      'Real instruments and musicianship',
      'Relatable, everyday themes',
      'Strong live performances',
      'Connection to country traditions',
      'Singable melodies and memorable hooks',
    ],
    gatekeeping: 'Significant — debates about "real country" vs. "country-pop" are central to the culture. Traditional vs. modern. Nashville insiders vs. independents. Recent inclusion debates around race and identity.',
    livePerformance: 'Festivals (CMA Fest, Stagecoach), stadium tours, honky-tonks, and county fairs. Line dancing, singalongs, and tailgating are part of the experience. Acoustic sets and intimate venues valued too.',
    fashionAndAesthetic: 'Boots, hats, jeans, belt buckles — the cowboy aesthetic. Ranges from working rancher authentic to glamorous Nashville. Modern country fashion blends with mainstream American casual.',
    crossoverPotential: 'Growing — country-pop crossover (Taylor Swift), country-rap (Lil Nas X, Jelly Roll), and Americana blur genre lines. Country elements increasingly appear in pop and hip-hop.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Country micro-timing is defined by the shuffle and the train beat — rhythmic patterns that sound simple but require deep feel to execute. The bass walks between chord changes with a slight swing, the snare has a brushed looseness, and the whole band breathes together around the vocal.',
    quantizationDeviation: 'Moderate — country rhythm has a human looseness that gives it warmth. The boom-chuck pattern swings slightly but never rigidly. Traditional country sits further from the grid than modern Nashville pop-country, which is more quantized.',
    aheadBehindBeat: 'Country generally sits right on or slightly behind the beat — the groove has an unhurried confidence. Uptempo honky-tonk pushes ahead with energy. Ballads lay back, letting the story breathe. The train beat drives forward but with a relaxed inevitability, like a freight train at cruising speed.',
    humanizationMarkers: [
      'Bass walks between chord changes with slight rhythmic freedom',
      'Brushed snare drags microscopically behind the kick',
      'Fiddle entrances that slide into pitch rather than hitting it dead-on',
      'Pedal steel bends that take their time arriving at the target note',
      'Acoustic guitar boom-chuck pattern with natural velocity variation',
    ],
    genreSpecificFeel: 'The "train beat" — a driving shuffle on the snare that evokes a locomotive rolling down the tracks (Johnny Cash\'s "Folsom Prison Blues"). The "Texas shuffle" — a relaxed, swinging groove with the drums slightly behind. Modern Nashville has tightened timing significantly, which traditional fans hear as losing the soul.',
  },

  silenceAndSpace: {
    overview: 'Country music is defined by what you leave out. Every note must earn its place. Sparse arrangements where a single pedal steel cry rings across empty bars are more powerful than any wall of sound. Space is where the story lives — the listener fills silence with their own emotion.',
    negativeSpaceRole: 'Essential — country arrangements are transparent precisely because space allows each instrument and each word to be clearly heard. The vocal sits in open air, not competing with dense instrumentation. A fiddle fill works because there is room for it.',
    breathingPatterns: 'Verse: minimal accompaniment with space for the story. Chorus: fuller but still transparent. Instrumental break: one instrument steps forward while others drop back. The arrangement breathes with the narrative pacing.',
    dynamicContrast: 'Understated but effective — country uses dynamic contrast through arrangement density rather than volume. A verse with just guitar and voice, then a chorus adding steel, fiddle, and harmony vocals creates contrast without loudness wars.',
    whatIsDeliberatelyAbsent: [
      'Drums dropping to brushes or disappearing entirely in ballad verses',
      'Electric instruments pulling back to let acoustic guitar and voice stand alone',
      'Silence between the last verse line and the chorus — letting the lyric land',
      'Fiddle or steel playing single sustained notes instead of fills',
      'The tag ending where everything drops except voice and one instrument',
    ],
  },

  callAndResponse: {
    overview: 'Country call-and-response is rooted in the interplay between vocalist and instrument — the singer delivers a line, and the fiddle or steel guitar responds with a cry, a bend, or a fill. This dialogue gives country its conversational warmth.',
    vocalInstrumentalDialogue: 'The pedal steel or fiddle "answers" the vocal line — filling the space between sung phrases with melodic commentary. This is the defining texture of country: voice speaks, instrument responds with wordless emotion. The guitar does this too, with chicken-picked fills.',
    sectionInternal: 'Within verses, instruments trade fills: fiddle answers line one, steel answers line two, electric guitar answers line three. This rotation keeps the arrangement alive without overcrowding. Each instrument waits its turn.',
    audienceParticipation: 'Singalong choruses at concerts. "Yeehaw" and whistling from the crowd. Line dancing as physical call-and-response to the groove. Crowd singing the hook during instrumental breaks. Country concerts are participatory by nature.',
    patterns: [
      'Vocal line → pedal steel cry in the gap between phrases',
      'Verse vocal → fiddle fill at the end of each couplet',
      'Singer delivers punchline → crowd cheers or laughs (story songs)',
      'Male lead vocal → female harmony response (duet tradition)',
      'Acoustic guitar verse → full band chorus as ensemble response',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Regional dialect is CENTRAL to country music — it is arguably the most dialect-specific genre in American popular music. Southern US phonetics, Appalachian vocabulary, and Texas drawl are not affectations but core identity markers. How you talk is who you are in country.',
    phoneticMarkers: [
      'Southern drawl: elongated vowels ("tah-own" for "town"), dropped final g\'s ("runnin\'")',
      'Appalachian speech: "holler" for hollow, "might could" as double modal',
      'Texas twang: nasal resonance, clipped consonants, "fixin\' to" as future tense',
      'Nashville standard: smoothed Southern that reads as "country" without strong regional specificity',
      'Outlaw drawl: deeper, rougher, more deliberately working-class pronunciation',
    ],
    accentInfluence: 'The country vocal accent is inseparable from the genre — singing without it reads as pop or rock, not country. Even non-Southern artists adopt some twang. The degree of accent signals sub-genre: heavy twang for traditional, lighter for crossover. Fake accent is instantly detected and rejected by core fans.',
    dialectVocabulary: [
      '"Y\'all," "reckon," "fixing to" — Southern grammar as lyrical texture',
      '"Holler," "crick," "yonder" — Appalachian landscape vocabulary',
      '"Honky-tonk," "two-step," "juke joint" — country social vocabulary',
      '"Pickup truck," "back road," "dirt road" — rural transportation lexicon',
      '"Mama," "daddy," "home place" — family vocabulary with specific Southern resonance',
    ],
    regionWithinCulture: 'Nashville is the industry capital but not the only country sound. Texas country (Red Dirt) has its own identity — rawer, more rock-influenced, fiercely independent. Appalachian country is older, darker, more acoustic. Bakersfield (California) country has a harder, electric edge. Each region produces distinctly different music under the country umbrella.',
  },

  performancePractice: {
    overview: 'Country performance ranges from intimate honky-tonk bars to massive stadium tours, but the core is always the same: the song and the story come first. A great country performer makes every person in the audience feel like they are being told a story directly.',
    improvisationConventions: 'Instrumental solos (fiddle, steel, guitar) are the primary improvisation space, though within structured forms. Banter and storytelling between songs is a crucial performance skill — connecting with the audience through spoken stories is as valued as singing.',
    crowdInteraction: 'Conversational and warm — the performer talks to the audience like neighbors. Dedicating songs to specific people. Telling the story behind the song. Audience requests are honored. The relationship is personal, not adversarial.',
    stagePresence: 'Authentic and unpretentious — cowboy hat, boots, guitar. The performer is "one of us," not above the audience. Standing at the mic with a guitar is sufficient. Excessive theatrics feel false. Emotional sincerity is the ultimate stage presence.',
    livVsRecordedDifferences: 'Live country often includes extended storytelling intros, improvised instrumental solos, and audience interaction. Songs may be slower or faster based on the room. The recording is polished Nashville; the live show is rawer and more personal.',
    whatMakesAGoodShow: 'A mix of uptempo and ballads. Stories between songs that make the audience laugh or cry. A singalong moment where the whole crowd knows every word. Genuine connection — the feeling that the performer means every word. An encore that leaves them wanting more.',
  },

  socioeconomicSubtext: {
    overview: 'Country music is the soundtrack of rural and working-class white America — its themes of land, labor, faith, and family reflect specific material conditions. The genre has always grappled with poverty, economic hardship, and the dignity of manual work.',
    materialConditions: 'Country music emerged from agricultural poverty — sharecroppers, coal miners, railroad workers. Modern country reflects blue-collar and service-industry realities: factory closures, small-town economic decline, the opioid crisis. The music gives voice to communities that mainstream culture often ignores.',
    classIdentity: 'Working-class pride is explicit in country — "I\'m proud of where I come from" is a core lyrical stance. The genre celebrates manual labor, rural self-sufficiency, and making do with less. Class mobility is a theme (rising from poverty), but staying true to roots is valued more than leaving them behind.',
    politicalUndercurrent: 'Country carries both populist and conservative undercurrents. Outlaw country has an anti-establishment streak (Willie Nelson, Merle Haggard). Mainstream country often aligns with patriotic and traditional values. Americana occupies a progressive space. The genre contains multitudes politically.',
    implicitReferences: [
      'Farm foreclosures and rural economic decline as backdrop for loss narratives',
      'Military service as working-class path — country has strong veteran and military themes',
      'Small-town decline: "everybody left" as a recurring setting for songs',
      'Truck ownership as economic identity — the vehicle you drive signals class',
      'Church community as social safety net when economic systems fail',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Country is deeply self-referential — artists constantly reference the canon, cover classics, and position themselves within a lineage. Hank Williams, Johnny Cash, Merle Haggard, and Dolly Parton are touchstones that every country artist is expected to know and revere.',
    canonKnowledge: 'Deep knowledge of the country canon is an authenticity requirement. Name-dropping Hank, Merle, Waylon, or Dolly in songs is common. Covering classic country songs is both homage and credential. New artists are judged partly by how well they understand the tradition.',
    samplingTradition: 'Country rarely samples in the hip-hop sense — it\'s a live-instrument tradition. The equivalent is the cover song: performing a classic demonstrates lineage. Standards like "He Stopped Loving Her Today" or "Crazy" are expected in every country musician\'s repertoire.',
    quotationPractice: 'Musical quotation through steel guitar licks, fiddle phrases, and guitar runs that reference classic recordings. Lyrical references to older songs and artists. Tribute albums and duets with legends. The tradition is oral and performative rather than sample-based.',
    expectedReferences: [
      'Hank Williams as the founding father — referenced in lyrics, style, and attitude',
      'Johnny Cash\'s boom-chicka-boom rhythm as foundational groove',
      'Merle Haggard\'s working-class storytelling as lyrical model',
      'Dolly Parton\'s songwriting craft as aspirational standard',
      'George Jones\' vocal delivery as the benchmark for emotional singing',
    ],
    lineageSignifiers: [
      'Telecaster tone = traditional country credibility',
      'Pedal steel presence = commitment to the country sound',
      'Acoustic guitar intro = singer-songwriter tradition within country',
      'Train beat = direct link to Johnny Cash and early country',
      'Fiddle prominence = traditional over modern Nashville pop',
      'Outlaw wardrobe (black, no rhinestones) = anti-Nashville statement',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Country has historically maintained distinct male and female performance traditions — the male outlaw/cowboy and the female singer-songwriter/torch singer. These conventions are both deeply rooted and actively being expanded by contemporary artists.',
    vocalGenderCodes: 'Male country voice: baritone or low tenor, slight rasp, conversational delivery (Merle, Cash, Stapleton). Female country voice: clear, strong, higher register with controlled twang (Patsy Cline, Dolly, Carrie Underwood). Duets pair these voices as complement. The "cry" in the voice crosses gender lines.',
    physicalityInPerformance: 'Male: guitar in hand, standing at the mic, cowboy hat, boots — the body is still and grounded. Female: more varied — from standing with guitar (Dolly) to dynamic stage movement (Shania, Carrie). Both genders use minimal choreography compared to pop; authenticity is in stillness and vocal delivery.',
    genderNarratives: 'Male narratives: working-man stories, drinking, trucks, romantic pursuit, fatherhood. Female narratives: heartbreak from a woman\'s perspective, independence, motherhood, "done wrong" revenge songs. The "murder ballad" tradition casts women in both victim and avenger roles.',
    subversionExamples: [
      'Dolly Parton subverting the "dumb blonde" stereotype while wielding it strategically',
      'k.d. lang bringing openly queer identity into country performance',
      'Kacey Musgraves rejecting Nashville gender norms in both lyric and persona',
      'Lil Nas X challenging racial and gender expectations simultaneously',
      'Mickey Guyton and Rissi Palmer expanding who gets to tell country stories',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Country tempo is deceptive — a shuffle at 120 BPM feels completely different from a straight-8ths country-rock song at 120 BPM. The subdivisions, the swing, and the rhythmic density change the experience entirely. A waltz at 90 BPM feels faster than a ballad at 90 BPM because of the triple-time meter.',
    psychologicalTempo: 'The train beat creates a sense of relentless forward motion even at moderate tempos. A slow waltz feels intimate and swaying. A two-step at 130 BPM feels danceable and light, not fast. The shuffle swing adds a sense of ease that makes medium tempos feel relaxed rather than driving.',
    weightAndMomentum: 'Country momentum is lighter than rock — the groove propels rather than pushes. Acoustic instruments create less sonic weight than distorted electric guitars. Even heavy country-rock has a buoyancy that pure rock lacks. The weight comes from the bass and kick, but the top end stays bright and open.',
    urgencyScale: '1 (weeping ballad) through 5 (mid-tempo story song) to 10 (honky-tonk barnburner). Most country lives at 4-6: comfortable groove territory for storytelling. Bluegrass pushes to 8-9 with virtuosic speed. Ballads sit at 2-3 where every word has time to land.',
    comparisonToSameBPM: 'Country at 120 BPM feels easy and relaxed — the shuffle adds swing and the acoustic instruments keep it light. Rock at 120 BPM feels heavier and more driving. Pop at 120 BPM feels more energetic due to electronic production. Country\'s acoustic palette and rhythmic looseness make the same tempo feel slower and warmer.',
  },

  mistakeConventions: {
    overview: 'Country values a "lived-in" sound — not mistakes per se, but the patina of imperfection that comes from real musicians playing together in a room. Overly polished, pitch-perfect recordings feel false to traditional country ears. The voice should sound like it has lived the song.',
    toleratedImperfections: [
      'Slight vocal pitch variations that convey emotion over perfection',
      'Fiddle intonation that wavers at the top of a passionate phrase',
      'Bass walks that land a hair early or late, adding human feel',
      'Guitar string buzz on acoustic instruments played hard',
      'Audible breaths between vocal phrases showing physical effort',
    ],
    celebratedFlaws: [
      'Hank Williams\' raw, nasal vocal that no trained singer would emulate — yet it defined the genre',
      'Johnny Cash\'s imperfect bass-baritone and minimal vocal range celebrated as ultimate authenticity',
      'Willie Nelson\'s behind-the-beat guitar phrasing that defies conventional timing',
      'Townes Van Zandt\'s fragile, breaking voice as the sound of genuine suffering',
      'Chris Stapleton\'s ragged, blown-out vocal as proof of emotional investment',
    ],
    overproductionRisks: [
      'Auto-Tune on country vocals — perceived as the ultimate betrayal of authenticity',
      'Programmed drums replacing a real drummer\'s feel and groove',
      'Pitch-perfect vocals that sound robotic rather than human',
      'Removing the room sound from acoustic instruments, making them sterile',
      'Overly compressed mastering that flattens the dynamics of a ballad',
    ],
    authenticRoughness: 'The difference between "authentic rough" and "bad" in country is sincerity. If the roughness serves the emotion — a voice cracking during a sad song, a guitar played hard enough to buzz — it is valued. If it is sloppiness from lack of care, it is not. The audience can tell whether imperfection comes from passion or indifference.',
  },

  referenceTracks: [
    {
      title: 'Starting Over',
      artist: 'Chris Stapleton',
      year: 2021,
      whyExemplary: 'CMA Song of the Year that distills country\'s core promise — reinvention and resilience — into a deceptively simple acoustic arrangement with soul-drenched vocals.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Acoustic guitar drives the arrangement. Verses build narrative, chorus delivers the universal hook. Bridge lifts key and intensity.',
      craftHighlight: 'The chorus lyric works as both literal (starting a journey) and emotional (starting over after loss). Stapleton\'s blues phrasing turns country structure into something timeless.',
    },
    {
      title: 'Fancy Like',
      artist: 'Walker Hayes',
      year: 2021,
      whyExemplary: 'Country-pop crossover that proved specificity wins — naming Applebee\'s and Natty Light instead of generic "good times" made it feel more real, not less.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Talk-singing verses, melodic chorus. Minimal production — acoustic guitar, light percussion, handclaps.',
      craftHighlight: 'Brand-name specificity as authenticity tool. Every detail is concrete (Oreo shake, Wendy\'s parking lot) which paradoxically makes it more universal than abstract romance.',
    },
    {
      title: 'Buy Dirt',
      artist: 'Jordan Davis ft. Luke Bryan',
      year: 2021,
      whyExemplary: 'Values anthem that avoids preaching by grounding life philosophy in tangible imagery — land, family, faith rendered as things you can touch.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Duet structure with Bryan on second verse. Builds from intimate acoustic to full band on final chorus.',
      craftHighlight: 'The metaphor "buy dirt" carries triple meaning: invest in land, put down roots, get your hands dirty with real work. Each verse develops a different facet.',
    },
    {
      title: 'You Should Probably Leave',
      artist: 'Chris Stapleton',
      year: 2021,
      whyExemplary: 'Blues-rock country that captures the tension between desire and better judgment. The title is both invitation and warning simultaneously.',
      structuralNotes: 'Verse-chorus-verse-chorus-solo-chorus. Electric guitar-driven. Verses are conversational, chorus is the repeated title as mantra. Guitar solo replaces bridge.',
      craftHighlight: 'Dramatic irony — the speaker says "leave" but every vocal inflection begs "stay." The gap between words and delivery is where the song lives.',
    },
    {
      title: 'Thought You Should Know',
      artist: 'Morgan Wallen',
      year: 2023,
      whyExemplary: 'Confessional letter-to-mama that earned critical respect for raw vulnerability. No posturing — just a son trying to make his mother proud.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Stripped arrangement builds: piano and voice open, full band enters gradually. Bridge is the emotional peak.',
      craftHighlight: 'Epistolary framing (letter to his mother) creates intimacy. The listener overhears something private, which makes the emotion hit harder than direct address.',
    },
    {
      title: 'Fast Car',
      artist: 'Luke Combs',
      year: 2023,
      whyExemplary: 'Cover that introduced Tracy Chapman\'s masterpiece to a new generation and proved great country songwriting transcends era and genre boundaries.',
      structuralNotes: 'Faithful to original structure: verse-chorus-verse-chorus-verse-chorus. Combs adds subtle country production (steel guitar hints) while respecting the folk bones.',
      craftHighlight: 'Demonstrates how a perfectly written song needs no structural changes across decades — the narrative arc (hope, struggle, resignation, resolve) is timeless.',
    },
    {
      title: 'The Painter',
      artist: 'Cody Johnson',
      year: 2023,
      whyExemplary: 'Traditional country ballad that uses extended metaphor (life as painting) without ever feeling forced. Bobby Pinson\'s songwriting at its finest.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Traditional Nashville structure. Fiddle and steel guitar prominent. The bridge pivots from regret to hope.',
      craftHighlight: 'Sustained metaphor mastery — every line extends the painting conceit (colors for emotions, brushstrokes for choices) without breaking the frame or becoming precious.',
    },
    {
      title: 'Burn It Down',
      artist: 'Parker McCollum',
      year: 2023,
      whyExemplary: 'Texas/neo-traditional country that balances bar-band energy with lyrical precision. McCollum bridges Strait-era traditionalism with modern urgency.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Up-tempo with driving rhythm section. Electric guitar leads. Chorus is a singalong anthem hook.',
      craftHighlight: 'The title phrase works as both destructive and romantic — burning down walls, burning down inhibitions. Texas two-step energy in the rhythm section.',
    },
    {
      title: 'Save Me',
      artist: 'Jelly Roll',
      year: 2023,
      whyExemplary: 'Country-rock confessional from a hip-hop artist that proved authenticity isn\'t about pedigree — it\'s about lived truth. CMA breakthrough.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Rock dynamics — quiet verses build to powerful chorus. Bridge is near-breakdown vocal moment.',
      craftHighlight: 'Recovery narrative without euphemism. Names the struggle (addiction, self-destruction) directly. The rock arrangement mirrors the emotional turbulence.',
    },
    {
      title: 'White Horse',
      artist: 'Chris Stapleton',
      year: 2024,
      whyExemplary: 'Country blues that subverts the fairy-tale rescue trope. The white horse isn\'t coming — you save yourself. Grammy-nominated songwriting.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Blues-rock arrangement with country vocal phrasing. Builds from acoustic to electric across the song.',
      craftHighlight: 'Fairy-tale deconstruction through country realism. Each verse dismantles a romantic myth with working-class truth. The imagery is specific enough to be universal.',
    },
    {
      title: 'I Remember Everything',
      artist: 'Zach Bryan ft. Kacey Musgraves',
      year: 2023,
      whyExemplary: 'Americana duet that captures the ache of memory after a relationship ends. Two voices that never harmonize — they take turns, like people who can\'t be in the same room.',
      structuralNotes: 'Verse (him)-verse (her)-chorus-verse (him)-verse (her)-chorus-outro. No bridge — the structure mirrors two people telling the same story separately.',
      craftHighlight: 'The vocal arrangement IS the story — they never sing together, only in sequence. Memory rendered as parallel monologues. Devastating in its restraint.',
    },
    {
      title: 'Something in the Orange',
      artist: 'Zach Bryan',
      year: 2022,
      whyExemplary: 'Americana/folk breakthrough that proved raw iPhone-recorded demos could become platinum hits. Emotional authenticity over production polish.',
      structuralNotes: 'Verse-chorus-verse-chorus-chorus. Simple structure, no bridge. Acoustic guitar and voice carry everything. The double chorus at the end is the cathartic release.',
      craftHighlight: 'Synesthesia as emotional language — "something in the orange" describes a feeling through color rather than naming it. The vagueness is precisely the point.',
    },
    {
      title: 'Watermelon Moonshine',
      artist: 'Lainey Wilson',
      year: 2023,
      whyExemplary: 'Bell-bottom country that blends 70s country-rock swagger with modern female perspective. CMA Female Vocalist of the Year energy.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Mid-tempo groove with country-rock rhythm section. Fiddle and electric guitar trade licks.',
      craftHighlight: 'The compound image "watermelon moonshine" fuses innocence (watermelon, summer) with danger (moonshine, intoxication) — the whole song lives in that tension.',
    },
    {
      title: 'Religiously',
      artist: 'Bailey Zimmerman',
      year: 2023,
      whyExemplary: 'Modern country-pop that turns devotion vocabulary into heartbreak language. Massive streaming hit that resonated with younger audiences.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Pop-influenced dynamics with country instrumentation. Pre-chorus creates lift into the hook.',
      craftHighlight: 'Sacred/secular vocabulary swap — "religiously" applied to romantic obsession. Every church metaphor (worship, pray, Sunday) recontextualized as love language.',
    },
    {
      title: 'Dirt Cheap',
      artist: 'Cody Johnson',
      year: 2024,
      whyExemplary: 'Traditional values anthem that follows "Buy Dirt" territory but with Johnson\'s honky-tonk delivery. Country radio staple.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Traditional arrangement: steel guitar, fiddle, acoustic guitar, upright bass. Walking tempo.',
      craftHighlight: 'Economic metaphor extended: everything meaningful in life is "dirt cheap" — free but invaluable. Working-class pride expressed through inversion of commercial value.',
    },
    {
      title: 'If We Were Vampires',
      artist: 'Jason Isbell and the 400 Unit',
      year: 2021,
      whyExemplary: 'Americana masterclass — a love song built on mortality. Grammy-winning songwriting that redefines what country storytelling can be.',
      structuralNotes: 'Verse-chorus-verse-chorus-verse-chorus. Waltz time (3/4). Acoustic guitar and voice dominate. No bridge — the structure mirrors the inevitability the lyrics describe.',
      craftHighlight: 'The premise (immortality would cheapen love) is philosophically rigorous AND emotionally devastating. Every verse adds a concrete detail that makes mortality feel present.',
    },
    {
      title: 'Half Drunk on a Full Moon',
      artist: 'Turnpike Troubadours',
      year: 2022,
      whyExemplary: 'Red Dirt/Texas country comeback that reminded everyone what bar-band storytelling sounds like. Evan Felker\'s literary lyricism at its peak.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Fiddle-driven arrangement with honky-tonk piano. Up-tempo two-step feel.',
      craftHighlight: 'The title is a perfect country image — "half drunk on a full moon" compresses an entire night, mood, and setting into six words. Felker\'s Oklahoma dialect is the instrument.',
    },
    {
      title: 'Remember Her Name',
      artist: 'Mickey Guyton',
      year: 2021,
      whyExemplary: 'Country anthem that confronts the genre\'s racial gatekeeping head-on. Grammy-nominated — expanded who country music speaks for.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Builds from intimate to anthemic. Full Nashville production with strings on the final chorus.',
      craftHighlight: 'Third person framing ("remember HER name") creates both distance and universality — it\'s about Guyton but also every woman erased from country\'s story.',
    },
    {
      title: 'In Your Love',
      artist: 'Tyler Childers',
      year: 2023,
      whyExemplary: 'Appalachian country that places a queer love story in the mountains. Expanded country\'s narrative range while honoring its geographic roots.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Acoustic-driven with Appalachian fiddle. Childers\' nasal Appalachian delivery grounds it in place.',
      craftHighlight: 'The radical act is the normalcy — the love story uses the same country vocabulary (porch, mountain, home) applied to a same-sex couple. No special pleading, just truth.',
    },
    {
      title: 'Next Thing You Know',
      artist: 'Jordan Davis',
      year: 2022,
      whyExemplary: 'Country-pop storytelling that compresses an entire relationship into a time-lapse. Master class in narrative pacing within pop structure.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Each verse covers a different life stage. Chorus repeats but gains meaning as context shifts. Pop production with country bones.',
      craftHighlight: 'Time-compression storytelling — each verse jumps years forward while the chorus stays the same, showing how life speeds up while the feeling stays constant.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: ['country', 'acoustic guitar', 'twang', 'storytelling', 'Nashville', 'pedal steel', 'fiddle'],
    avoidKeywords: ['electronic', 'synth', 'auto-tune', 'industrial', 'dubstep', 'aggressive bass', 'EDM'],
    promptTemplate: '[sub-genre] country, [tempo] BPM, [mood] mood, [instruments], [vocal style] vocals, [story theme]',
    tips: [
      'Specify the sub-genre: traditional, outlaw, country-pop, Americana, bluegrass',
      'Describe the instruments: acoustic guitar, pedal steel, fiddle, banjo',
      'Mention the story or theme: heartbreak, small-town life, drinking, love',
      'Reference the era: classic 60s, outlaw 70s, 90s country, modern',
      'Describe the vocal style: twangy, smooth, raw, female/male',
      'Include tempo context: slow ballad, mid-tempo, uptempo two-step',
    ],
  },
};
