import type { GenreGuide } from './types';

export const EDM_GUIDE: GenreGuide = {
  id: 'edm',
  name: 'Electronic Dance Music',
  language: 'English',

  sonicPalette: {
    overview: 'Synthesizer-driven, bass-heavy, and designed for physical movement. EDM exists in the space between technology and human emotion — synthetic sounds engineered to create euphoria, energy, and transcendence on the dance floor.',
    timbre: [
      'Analog and digital synthesizers (leads, pads, basses)',
      'Processed and layered drum samples',
      'Sub-bass frequencies (20-60 Hz)',
      'Supersaw leads and stabs',
      'Vocoder and processed vocal samples',
      'White noise risers and sweeps',
      'Sidechain-compressed pads',
      'Resampled and granular textures',
    ],
    texture: 'Dense and layered in build sections, stripped-back in breaks. EDM uses frequency layering — each synth occupies a specific range. Sidechain compression creates the characteristic "pumping" effect. The mix is designed for large sound systems.',
    tonality: 'Minor keys dominate for emotional impact (Am, Cm, Dm). Major keys for euphoric, uplifting tracks. Simple tonal centers — the harmonic language is minimal, letting production carry the emotion.',
    signatureSounds: [
      'Sidechain pumping on pads and bass',
      'White noise risers and sweeps',
      'Snare/clap build-ups',
      'Euphoric supersaw chords',
      'Sub-bass drops',
      'Vocal chops and pitched samples',
      'Impact hits and reverse crashes',
    ],
  },

  rhythmAndGroove: {
    overview: 'The beat is the entire foundation — EDM is music engineered for dancing. From the steady four-on-the-floor of house to the broken beats of drum and bass, rhythm drives everything.',
    bpmRange: { min: 100, max: 180, sweet: 128 },
    feel: 'Physical and hypnotic. The groove should induce movement without conscious thought. Four-on-the-floor creates a trance-like pulse. Breakbeats create energetic complexity.',
    swing: 'Varies by sub-genre — house uses subtle swing, techno is rigid and machine-like, garage has heavy swing, drum and bass is syncopated. Many sub-genres are intentionally straight-quantized.',
    syncopation: 'Moderate to heavy in hi-hats and percussion. The kick is typically on the beat while everything else provides rhythmic interest. Off-beat bass lines are common in house.',
    grooveArchetype: 'Four-on-the-floor pulse, broken beat, half-time drop, or rolling breakbeat',
    rhythmicSignatures: [
      'Four-on-the-floor kick drum (house, techno, trance)',
      'Clap/snare on beats 2 and 4',
      'Off-beat hi-hats (house groove)',
      'Breakbeat patterns (drum and bass, breaks)',
      'Half-time snare in drops (dubstep)',
      'Build-up snare rolls accelerating to drop',
      'Syncopated percussion layers',
    ],
  },

  harmonicLanguage: {
    overview: 'EDM harmony is functional — it serves emotional impact over intellectual complexity. Simple chord progressions repeated in loops create hypnotic effect. The emotional power comes from timbre and production rather than harmonic sophistication.',
    scales: ['Natural Minor', 'Minor Pentatonic', 'Major', 'Phrygian', 'Mixolydian'],
    chordProgressions: [
      'i – bVI – bVII – i (EDM minor loop)',
      'i – bVI – bIII – bVII (euphoric minor)',
      'I – V – vi – IV (pop-EDM)',
      'i – iv – bVII – bIII (dark progressive)',
      'i – i – bVI – bVII (two-chord loop)',
      'I – I – IV – IV (simple trance)',
    ],
    harmonyNotes: 'Chords are often sustained pads rather than rhythmic strums. Inversions and voice leading create smooth movement. The bass note is separated from the chord voicing. Supersaw stacks create massive chord sounds.',
    modality: 'Minor for dark and driving energy. Major for euphoric and uplifting. Phrygian for dark, exotic textures. The choice of mode defines the emotional character of the track.',
  },

  songStructure: {
    overview: 'EDM structure is designed for DJ mixing — long intros and outros with gradual element introduction. The build-drop dynamic is the defining structural element. Energy management across 5-7 minutes is the art.',
    form: 'Intro – Build 1 – Drop 1 – Break – Build 2 – Drop 2 – Outro (DJ-friendly)',
    sections: ['Intro (16-32 bars)', 'Build-up', 'Drop/Main Section', 'Breakdown', 'Build-up 2', 'Drop 2 (bigger)', 'Outro (16-32 bars)'],
    arrangement: 'Additive construction — elements are introduced one at a time during intros and builds. The drop hits with full energy. Breakdowns strip back to create contrast. Each drop should feel bigger than the last.',
    introOutro: 'Long intros and outros (16-32 bars) with just kick and minimal elements for DJ mixing. Gradual element introduction. The intro establishes the groove and mood before any melodic elements arrive.',
    barLengths: 'Intro: 16-32 bars. Build: 8-16 bars. Drop: 16-32 bars. Breakdown: 8-16 bars. Outro: 16-32 bars. Total: 4-7 minutes (radio edits: 3-4 minutes).',
    hookPlacement: 'The drop IS the hook — the melodic/rhythmic payoff after the build. Vocal hooks in the breakdown or pre-drop build. Synth melodies in the drop section. Repetition of the hook across multiple drops.',
  },

  vocalDelivery: {
    overview: 'Vocals in EDM serve as another instrument — often heavily processed, chopped, pitched, and effected. When present, vocals provide the emotional anchor for the production. Many EDM tracks are purely instrumental.',
    phrasing: 'Simple, repetitive phrases designed for processing and looping. Vocal hooks are short and memorable. Phrasing serves the rhythm of the track rather than conversational flow.',
    affect: 'Euphoric, yearning, empowering, or hypnotic — the vocal conveys a single, powerful emotion. Specificity is less important than emotional impact.',
    techniques: [
      'Heavy pitch correction and Auto-Tune',
      'Vocal chopping and rearrangement',
      'Vocoder and talkbox effects',
      'Pitched-up or down vocal samples',
      'Reverb-drenched ethereal delivery',
      'Whispered or spoken word passages',
      'Robotic/processed vocal textures',
      'Layered vocal harmonies',
    ],
    adlibStyle: 'Processed vocal shots — "hey!", "yeah!", "one more time!" Chopped vocal samples as rhythmic elements. DJ drops and shoutouts. Less spontaneous than hip-hop ad-libs — more designed and placed.',
    harmony: 'Layered, processed vocal stacks. Wide stereo vocal arrangements. Harmonized vocal samples. Vocoder chords using the voice. Often heavily processed beyond recognition.',
    grit: 'Minimal — EDM vocals are typically clean and heavily processed. Some genres (bass music, dubstep) use more raw or distorted vocal styles. The processing IS the texture.',
  },

  lyricalConventions: {
    overview: 'EDM lyrics are functional — they provide emotional anchoring for the production. When present, lyrics are simple, universal, and designed for crowd singalongs and emotional peaks.',
    themes: [
      'Euphoria and transcendence',
      'Love and desire',
      'Unity and togetherness',
      'Escape and freedom',
      'The night and nightlife',
      'Self-empowerment',
      'Letting go',
    ],
    perspective: 'First person or universal "we" — inclusive and communal. The lyrics should make every person on the dance floor feel included.',
    figurativeLanguage: 'Simple and direct — light for happiness, darkness for longing, fire for passion, flying for freedom. No complex literary devices needed.',
    vocabulary: 'Simple, universal, singable. Short words, easy phrases. No complex vocabulary or cultural specificity. The lyrics must work across languages and cultures.',
    storytellingApproach: 'Minimal narrative — EDM lyrics capture a single feeling or moment. The entire lyric may be 4-8 lines repeated. The production tells the story.',
    cliches: [
      'Hands up / hands in the air',
      'Feel the music / feel the beat',
      'Tonight we are alive',
      'We are one',
      'Let the bass drop',
      'Never stop dancing',
    ],
  },

  productionFingerprint: {
    overview: 'Production IS the art form in EDM. Sound design, mixing, and arrangement are the primary creative acts. Every sound is crafted, layered, and processed to create maximum impact on large sound systems.',
    mixAesthetic: 'Loud, wide, and frequency-balanced for club systems. Sub-bass must translate to large speakers. Stereo width maximized in drops, narrowed in breakdowns. Heavy sidechain compression. Aggressive limiting.',
    era: 'Current era: genre fusion, hyperpop influence, melodic bass music, tech house mainstream crossover, return to underground sounds.',
    signalChain: 'Synths: Serum, Massive, Sylenth1, Omnisphere → layering → EQ → compression → distortion/saturation → sidechain → reverb/delay sends. Master: multiband compression → stereo widening → limiting.',
    modernTrends: 'Genre-blending (pop-EDM, Latin-EDM, hip-hop-EDM). Organic instrument integration. Hyperpop influence. Lo-fi electronic aesthetics. AI-assisted sound design. Spatial audio and immersive formats.',
  },

  instrumentation: {
    coreInstruments: [
      'Synthesizers (analog and digital)',
      'Drum machines and samplers',
      'DAW (Ableton Live, FL Studio)',
      'MIDI controllers',
      'Audio effects processors',
      'DJ equipment (CDJs, mixers)',
    ],
    signatureSounds: [
      'Supersaw lead stacks',
      'Sub-bass sine waves',
      'White noise risers',
      'Sidechain-pumped pads',
      'Reese bass (detuned saw waves)',
      'Vocal chop melodies',
      'Impact/hit effects',
    ],
    layering: 'Extremely layered — a single "synth" sound may be 5-10 layers of different synthesizers, each handling a specific frequency range. Drums are heavily layered (kick = sub + punch + click). Everything is sidechained to the kick.',
    avoidInstruments: [
      'Unprocessed acoustic instruments (feel out of place)',
      'Classical orchestral arrangements (unless orchestral EDM)',
      'Country instruments (banjo, steel guitar)',
      'Raw, unprocessed vocals',
      'Heavy distorted rock guitars (unless crossover)',
    ],
  },

  culturalContext: {
    overview: 'EDM culture is rooted in communal dance experiences — clubs, raves, and festivals where music creates collective euphoria. Born from Black and queer communities in Chicago, Detroit, and New York, it has become a global phenomenon.',
    origin: 'House music in Chicago (Frankie Knuckles, 1980s), techno in Detroit (Juan Atkins, Derrick May, Kevin Saunderson), and UK rave culture. Evolved from disco, synth-pop, and electronic experimentation.',
    identity: 'Community and inclusivity — "one nation under a groove." PLUR (Peace, Love, Unity, Respect). The DJ as artist and guide. Technology as creative tool. Club culture as safe space for marginalized communities.',
    community: 'Festival culture (Tomorrowland, Ultra, EDC). Club scenes (Berlin, Ibiza, NYC). Online producer communities. DJ culture and mix sharing. Genre-specific scenes with distinct identities.',
    socialFunction: 'Communal dance experience — collective euphoria through music. Escape from daily life. Safe space for self-expression. Physical and emotional release through dance.',
    authenticityMarkers: [
      'Production skill and sound design',
      'DJ ability and track selection',
      'Connection to dance floor culture',
      'Originality of sound',
      'Genre knowledge and respect for history',
      'Live performance energy',
    ],
  },

  historicalLineage: {
    overview: 'From underground clubs to global festivals, EDM has evolved from marginalized dance music to the world\'s biggest live music genre while maintaining its roots in electronic innovation and communal dance.',
    roots: ['Disco', 'Synth-Pop', 'Kraftwerk/Electronic Pioneers', 'Dub/Reggae', 'Funk'],
    evolution: 'Chicago house and Detroit techno (80s) → UK rave and acid house (late 80s) → Trance and progressive (90s) → Dubstep and bass music (2000s) → EDM mainstream explosion (2010s) → Genre-fluid electronic (2020s).',
    keyEras: [
      '1985-1990: House and techno origins',
      '1988-1992: UK rave and acid house explosion',
      '1993-2000: Trance, jungle, and UK garage',
      '2000-2010: Dubstep, electro-house, minimal',
      '2010-2015: EDM mainstream explosion (festivals)',
      '2015-present: Bass music, future bass, genre fusion',
    ],
    influencedBy: ['Disco', 'Funk', 'Synth-Pop', 'Dub Reggae', 'Hip-Hop', 'Industrial'],
    influenced: ['Pop', 'Hip-Hop', 'R&B', 'Rock', 'Latin', 'Global pop'],
  },

  subGenres: [
    {
      name: 'House',
      description: 'The foundation — four-on-the-floor kick, off-beat hi-hats, soulful vocal samples, and warm bass. Designed to make people dance all night.',
      distinguishingFeatures: ['Four-on-the-floor kick drum', 'Off-beat hi-hats', 'Warm, soulful vocals', 'Groovy bass lines', 'Disco and soul samples'],
      bpmRange: { min: 118, max: 132 },
      keyArtists: ['Frankie Knuckles', 'Disclosure', 'Fisher', 'Chris Lake', 'MK'],
      productionNotes: 'Groove is king. Four-on-the-floor with off-beat hi-hats. Warm, round bass. Soulful vocal samples or full vocals. Keep it groovy and danceble.',
      lyricNotes: 'Soulful, uplifting, dance-focused. Love, freedom, unity. Often uses sampled vocals from disco and soul records.',
      sunoPromptKeywords: ['house music', 'four-on-the-floor', 'groovy', 'dance', 'club', 'disco house', 'soulful house'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Behind-beat soulful drag — the groove leans back with Chicago funk warmth; hi-hats swing slightly',
          aheadBehindBeat: 'Kick on grid, everything else slightly behind — creates a laid-back dancefloor sway',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Relaxed cruising — 124 BPM feels comfortable and sustainable for hours; sidechain pump creates gentle sway not urgency',
          weightAndMomentum: 'Moderate weight, high momentum — the four-on-the-floor propels without exhausting',
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Disco and soul sampling is DNA — knowing Chic, Donna Summer, and Patrick Adams is foundational',
          samplingTradition: 'Vocal chops from soul/disco records are the genre\'s defining texture; original vocals also welcome',
          lineageSignifiers: ['909 drum machine patterns', 'Disco string stabs', 'Soulful diva vocal samples', 'Chicago warehouse energy'],
        },
        socioeconomicSubtext: {
          classIdentity: 'Black and Latino queer club origins — house was born in marginalized communities finding freedom through dance',
          materialConditions: 'Warehouse parties and underground clubs; the music of communities locked out of mainstream nightlife',
        },
      },
    },
    {
      name: 'Techno',
      description: 'Mechanical, repetitive, and hypnotic. Techno strips dance music to its essentials — relentless rhythm, minimal melody, and industrial textures.',
      distinguishingFeatures: ['Mechanical, repetitive rhythm', 'Minimal melodic elements', 'Industrial and metallic textures', 'Hypnotic, loop-based structure', 'Dark atmosphere'],
      bpmRange: { min: 125, max: 150 },
      keyArtists: ['Juan Atkins', 'Amelie Lens', 'Charlotte de Witte', 'Adam Beyer', 'Jeff Mills'],
      productionNotes: 'Minimal, hypnotic loops. Industrial textures. Dark atmosphere. Repetition as a tool for trance states. Subtle variation over time. Machine-like precision.',
      lyricNotes: 'Rarely features lyrics. When present, minimal and abstract. Industrial or dystopian themes.',
      sunoPromptKeywords: ['techno', 'dark techno', 'industrial techno', 'minimal', 'hypnotic', 'driving', 'Berlin techno'],
      embodiedDelta: {
        microTimingAndFeel: {
          quantizationDeviation: 'Zero — grid-as-philosophy; the machine precision IS the aesthetic, not a limitation',
          genreSpecificFeel: 'Mechanical repetition inducing trance states — the unchanging grid becomes hypnotic over time',
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Minimalism as music — stripping elements away is the primary compositional technique; a single hi-hat removal is an event',
          dynamicContrast: 'Gradual — contrast builds over 8-16 bar arcs through additive/subtractive layering, not sudden drops',
        },
        performancePractice: {
          stagePresence: 'Anti-spectacle — Berlin DJs face the wall or stand behind minimal setups; the focus is sound, not personality',
          crowdInteraction: 'Trance-like collective experience — 8+ hour sets where the crowd enters a shared altered state through repetition',
          improvisationConventions: 'DJ mixing is the improvisation — track selection, EQ, and transitions are the creative performance',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Sustained mechanical urgency — 130-140 BPM feels relentless but sustainable; the repetition normalizes the speed',
          urgencyScale: '6-8/10 — driving but not frantic; urgency is sustained, not peaked',
        },
      },
    },
    {
      name: 'Trance',
      description: 'Euphoric, melodic, and uplifting. Trance uses repeating melodic phrases, sustained pads, and building energy to create transcendent emotional experiences.',
      distinguishingFeatures: ['Euphoric melodies and breakdowns', 'Long build-ups to emotional peaks', 'Arpeggiated synth patterns', 'Lush pads and supersaw leads', 'Emotional, anthemic quality'],
      bpmRange: { min: 130, max: 150 },
      keyArtists: ['Armin van Buuren', 'Above & Beyond', 'Paul van Dyk', 'Tiësto (classic)', 'Ferry Corsten'],
      productionNotes: 'Euphoric supersaw melodies. Long builds to emotional drops. Lush reverb pads. Arpeggiated sequences. Emotional breakdowns with piano or vocal.',
      lyricNotes: 'Emotional, uplifting, transcendent. Love, unity, hope. Simple but powerful emotional messages.',
      sunoPromptKeywords: ['trance', 'uplifting trance', 'euphoric', 'melodic trance', 'epic', 'emotional EDM', 'anthem'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Metronomic precision as hypnotic tool — the unwavering grid induces trance states; subtle pitch modulation on leads provides movement, not timing variation',
          quantizationDeviation: 'Near zero — absolute rhythmic consistency is required for the hypnotic effect; any timing drift breaks the spell',
        },
        silenceAndSpace: {
          negativeSpaceRole: 'The breakdown is sacred — stripping to a lone piano or vocal for 16-32 bars creates the emotional void that the supersaw return fills with euphoria',
          dynamicContrast: 'Among the most extreme in EDM — whisper-quiet breakdowns to wall-of-sound drops; the emotional arc depends on this contrast',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: '138 BPM feels like sustained flight — the tempo is fast enough to energize but steady enough to sustain for hours; urgency resolves into euphoria rather than exhaustion',
          weightAndMomentum: 'Maximum momentum, moderate weight — the relentless four-on-the-floor propels forward while supersaw pads float above; the feeling is of being carried upward',
        },
        callAndResponse: {
          vocalInstrumentalDialogue: 'Vocal breakdown calls out emotionally, supersaw drop responds with sonic catharsis — the voice asks a human question, the synths answer with transcendence',
          audienceParticipation: 'Arms-raised collective euphoria — trance crowds sing along to melodic hooks and raise hands in synchronized waves during builds; ASOT (A State of Trance) ritual unity',
        },
        performancePractice: {
          crowdInteraction: 'Spiritual collective experience — the DJ guides a journey from darkness to light over 2+ hours; the crowd surrenders to the arc',
          whatMakesAGoodShow: 'The "hands in the air" moment when breakdown resolves to drop and the entire crowd lifts together — this is the genre\'s raison d\'etre',
        },
      },
    },
    {
      name: 'Dubstep',
      description: 'Heavy, bass-focused electronic music characterized by sub-bass, half-time beats, and aggressive sound design. Ranges from dark and minimal to maximalist "brostep."',
      distinguishingFeatures: ['Heavy sub-bass wobbles', 'Half-time drum patterns', 'Aggressive sound design', 'Bass drops', 'Dark, heavy atmosphere'],
      bpmRange: { min: 138, max: 142 },
      keyArtists: ['Skrillex', 'Excision', 'Burial', 'Skream', 'Subtronics'],
      productionNotes: 'Heavy bass design — wobbles, growls, screeches. Half-time snare pattern. Sub-bass that shakes the room. Sound design is the focus. Dark and heavy atmosphere.',
      lyricNotes: 'Minimal lyrics. When present: dark, aggressive, or hypnotic. Often uses pitched-down vocal samples.',
      sunoPromptKeywords: ['dubstep', 'bass drop', 'wobble bass', 'heavy bass', 'brostep', 'bass music', 'filthy'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Heavy behind-beat half-time drag — the snare on 3 creates a lumbering, head-nodding weight',
          aheadBehindBeat: 'Behind — everything drags with gravitational pull; the space between beats is stretched',
        },
        silenceAndSpace: {
          negativeSpaceRole: 'UK dubstep: negative space is sacred — bass emerges from silence. Brostep: maximalist wall of sound fills every gap',
          dynamicContrast: 'Extreme — the build-to-drop is the largest dynamic shift in all electronic music',
          whatIsDeliberatelyAbsent: ['Melody (in heavier variants)', 'Warmth', 'Organic textures', 'Comfort'],
        },
        tempoFeelVsNumber: {
          psychologicalTempo: '140 BPM feels like 70 — the half-time snare halves the perceived tempo; maximum weight, minimum perceived speed',
          weightAndMomentum: 'Maximum weight — the bass is physical, felt in the chest; momentum comes from bass rhythm, not tempo',
        },
        regionalDialectSpecificity: {
          accentInfluence: 'UK origins (Croydon/South London) — MC culture carries London accent; US brostep removed the vocal element entirely',
          regionWithinCulture: 'UK vs US split defines the genre: UK = space, restraint, bass weight; US = maximalism, aggression, spectacle',
        },
      },
    },
    {
      name: 'Drum and Bass',
      description: 'Fast, breakbeat-driven electronic music with heavy bass and intricate drum programming. High energy and technically demanding.',
      distinguishingFeatures: ['Fast tempo (170+ BPM)', 'Breakbeat drum patterns', 'Heavy bass lines (Reese bass)', 'Chopped break samples', 'MC culture (UK)'],
      bpmRange: { min: 160, max: 180 },
      keyArtists: ['Andy C', 'Sub Focus', 'Chase & Status', 'Goldie', 'Pendulum'],
      productionNotes: 'Fast, syncopated breakbeats. Heavy Reese bass or sub-bass. Chopped break samples. High energy. MC vocals optional. Technically demanding production.',
      lyricNotes: 'MC-driven when vocals present. Energy, bass culture, nightlife. UK slang and culture. Often instrumental.',
      sunoPromptKeywords: ['drum and bass', 'DnB', 'jungle', 'breakbeat', 'fast', 'bass heavy', '170 BPM', 'liquid'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Breakbeat syncopation — chopped and rearranged break samples create unpredictable rhythmic complexity within the fast tempo',
          humanizationMarkers: ['Chopped Amen break variations', 'Ghost snares from original break recordings', 'Swing inherited from sampled funk/soul breaks'],
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Dual-tempo perception — 170+ BPM drums feel frantic while half-time bass feels slow and heavy; the listener lives in both tempos simultaneously',
          weightAndMomentum: 'Maximum forward drive — the breakbeats propel relentlessly; liquid DnB is smoother but still carries the speed',
          urgencyScale: '9/10 — among the most urgent-feeling electronic genres',
        },
        regionalDialectSpecificity: {
          accentInfluence: 'London/Bristol MC culture — when MCs are present, South London or Bristol accent is the default; UK-Caribbean patois influence',
          phoneticMarkers: ['UK MC rapid-fire delivery', 'Patois-influenced slang', 'Rewind/reload call-outs'],
          regionWithinCulture: 'UK-born from jungle and breakbeat hardcore; Bristol, London, and Leeds each contributed distinct sub-styles',
        },
        intertextualityAndSampling: {
          canonKnowledge: 'The Amen break is the foundation — knowing its history from The Winstons through jungle to modern DnB is essential',
          samplingTradition: 'Breakbeat sampling is the origin technique; modern production often recreates rather than samples, but the chopped-break aesthetic remains',
          lineageSignifiers: ['Amen break', 'Think break', 'Reese bass', 'Jungle vocal chops'],
        },
      },
    },
    {
      name: 'Future Bass',
      description: 'Colorful, melodic electronic music with lush chords, pitched vocal chops, and heavy use of supersaws. Emotional and euphoric.',
      distinguishingFeatures: ['Lush supersaw chords', 'Pitched vocal chops', 'Bright, colorful sound palette', 'Emotional chord progressions', 'Half-time and syncopated beats'],
      bpmRange: { min: 140, max: 160 },
      keyArtists: ['Flume', 'San Holo', 'Marshmello', 'Said the Sky', 'Illenium'],
      productionNotes: 'Bright supersaw chords with sidechain. Vocal chops as melodic elements. Emotional builds and drops. Half-time sections. Bright, colorful sound design.',
      lyricNotes: 'Emotional, uplifting, bittersweet. Love, loss, hope. Simple emotional messages. Vocal chops carry melodic content.',
      sunoPromptKeywords: ['future bass', 'melodic bass', 'bright', 'emotional EDM', 'supersaw', 'colorful', 'festival'],
    },
    {
      name: 'Progressive House',
      description: 'Long-form, building house music that evolves gradually over time. Hypnotic melodies and pads that create a journey-like listening experience.',
      distinguishingFeatures: ['Gradual evolution and building', 'Long song structures (6-10 min)', 'Hypnotic melodies', 'Atmospheric pads', 'DJ-friendly structure'],
      bpmRange: { min: 122, max: 130 },
      keyArtists: ['Deadmau5', 'Eric Prydz', 'Lane 8', 'Yotto', 'Sasha'],
      productionNotes: 'Gradual element introduction. Long builds. Atmospheric pads and textures. Subtle melodic development. DJ-friendly intros and outros. Hypnotic repetition with variation.',
      lyricNotes: 'Often instrumental. When present: atmospheric, floating vocals. Minimal words, maximum emotion.',
      sunoPromptKeywords: ['progressive house', 'progressive', 'atmospheric', 'building', 'hypnotic', 'deep', 'melodic house'],
    },
    {
      name: 'Deep House',
      description: 'Warm, soulful, and atmospheric house music. Deeper grooves, jazzy elements, and a more sophisticated, underground aesthetic than mainstream house.',
      distinguishingFeatures: ['Warm, deep bass lines', 'Jazz and soul influences', 'Atmospheric, moody textures', 'Minimal but groovy', 'Underground aesthetic'],
      bpmRange: { min: 118, max: 125 },
      keyArtists: ['Larry Heard', 'Kerri Chandler', 'Jayda G', 'Maya Jane Coles', 'Black Coffee'],
      productionNotes: 'Warm, round bass. Jazz-influenced chords (7ths, 9ths). Atmospheric reverb. Subtle, groovy drums. Soulful vocal samples. Less is more.',
      lyricNotes: 'Soulful, atmospheric. When vocals present: warm, deep, soulful. Love and introspection.',
      sunoPromptKeywords: ['deep house', 'warm', 'soulful house', 'underground', 'jazzy house', 'atmospheric', 'deep'],
    },
    {
      name: 'Electro House',
      description: 'High-energy, aggressive house music with distorted bass, big builds, and festival-ready drops. The big-room sound.',
      distinguishingFeatures: ['Aggressive, distorted bass', 'Big build-ups and drops', 'Festival-ready energy', 'Saw-wave leads', 'Heavy sidechain compression'],
      bpmRange: { min: 125, max: 132 },
      keyArtists: ['Deadmau5', 'Wolfgang Gartner', 'Feed Me', 'Knife Party', 'Zedd'],
      productionNotes: 'Aggressive sound design. Big builds and drops. Distorted saw-wave bass. Heavy compression. Festival-volume mix. Maximum energy.',
      lyricNotes: 'Minimal. Shout hooks and vocal shots. Energy and hype. Party-focused.',
      sunoPromptKeywords: ['electro house', 'big room', 'festival', 'aggressive', 'drop', 'heavy house', 'main stage'],
    },
    {
      name: 'Tropical House',
      description: 'Laid-back, warm, summer-vibes electronic music. Soft synths, steel drum sounds, and gentle grooves designed for beach bars and sunset sessions.',
      distinguishingFeatures: ['Steel drum / marimba plucks', 'Laid-back, sunny vibe', 'Soft synth sounds', 'Mid-tempo grooves', 'Summer/beach aesthetic'],
      bpmRange: { min: 100, max: 115 },
      keyArtists: ['Kygo', 'Thomas Jack', 'Sam Feldt', 'Robin Schulz'],
      productionNotes: 'Steel drum and marimba pluck synths. Soft, warm pads. Gentle four-on-the-floor or half-time beats. Acoustic guitar samples. Warm, sunny mix.',
      lyricNotes: 'Summer, travel, love, freedom. Carefree and uplifting. Beach and vacation imagery.',
      sunoPromptKeywords: ['tropical house', 'summer', 'beach', 'chill', 'warm', 'sunset', 'tropical vibes'],
    },
    {
      name: 'Hardstyle',
      description: 'High-energy, aggressive electronic music characterized by distorted kick drums, euphoric melodies, and extreme tempo. Festival anthems.',
      distinguishingFeatures: ['Distorted, punchy kick drums', 'Reverse bass lines', 'Euphoric melodies', 'High tempo (150+ BPM)', 'Aggressive energy'],
      bpmRange: { min: 150, max: 160 },
      keyArtists: ['Headhunterz', 'Brennan Heart', 'D-Block & S-te-Fan', 'Sound Rush'],
      productionNotes: 'Distorted, punchy kick drums are essential. Reverse bass technique. Euphoric supersaw melodies. High energy throughout. Festival-ready production.',
      lyricNotes: 'Euphoric, anthemic. Unity, strength, freedom. Simple, powerful messages for crowd singalongs.',
      sunoPromptKeywords: ['hardstyle', 'hard dance', 'distorted kicks', 'euphoric hardstyle', 'festival', 'aggressive EDM', 'hard'],
    },
    {
      name: 'UK Garage',
      description: 'Swung, bass-heavy dance music from the UK. Syncopated rhythms, chopped vocal samples, and a distinctive bouncing groove that influenced dubstep and grime.',
      distinguishingFeatures: ['Syncopated, shuffled beats', 'Chopped vocal samples', 'Two-step rhythm pattern', 'Warm bass lines', 'UK club culture'],
      bpmRange: { min: 130, max: 140 },
      keyArtists: ['MJ Cole', 'DJ EZ', 'Todd Edwards', 'Conducta', 'Interplanetary Criminal'],
      productionNotes: 'Two-step/shuffled kick-snare pattern. Chopped vocal samples. Warm, round bass. Swung hi-hats. UK garage groove is distinctive — not four-on-the-floor.',
      lyricNotes: 'Love, nightlife, desire. UK slang and culture. Soulful R&B influence. MC culture.',
      sunoPromptKeywords: ['UK garage', 'UKG', 'two-step', 'garage', 'shuffled beats', 'London', 'speed garage'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'EDM audiences range from underground club-goers to massive festival attendees. The culture values shared experience, community, and losing yourself in music.',
    fanExpectations: [
      'Production quality and sound design',
      'DJ mixing skill',
      'Energy management on the dance floor',
      'Innovation in sound',
      'Festival-worthy live sets',
      'Community and inclusivity',
    ],
    gatekeeping: 'Significant — underground vs. mainstream tensions. Genre purists vs. crossover fans. Debates about "real" electronic music. Knowledge of history and scene values.',
    livePerformance: 'DJ sets are the primary format — mixing tracks seamlessly for hours. Live electronic performances growing. Festival spectacles with massive production (visuals, pyro, staging). Underground clubs value intimacy and sound quality.',
    fashionAndAesthetic: 'Festival fashion: neon, kandi bracelets, expressive outfits. Underground: dark, minimal, functional (Berlin techno). Rave culture aesthetics. Varied by sub-genre.',
    crossoverPotential: 'Maximum — EDM production techniques are in every pop song. Hip-hop uses EDM elements. Latin-EDM is huge. The production language of EDM is the production language of modern music.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'EDM micro-timing is RIGIDLY quantized — that IS the aesthetic. Every kick, snare, and hi-hat sits exactly on the grid because the music is produced in a DAW, not performed by humans. The "feel" of EDM comes from what happens AROUND the quantized grid: sidechain pumping, swing percentages, and humanization applied deliberately as a production choice.',
    quantizationDeviation: 'Near zero — EDM is built on the grid. Kick drums are sample-accurate. Hi-hats may have swing applied (a deliberate percentage, not natural variation). Any deviation from the grid is a conscious production decision, not a human performance artifact. This mathematical precision is what makes EDM function on massive sound systems.',
    aheadBehindBeat: 'EDM does not sit ahead or behind — it IS the beat. The quantized grid defines the beat, and everything is placed relative to it with sample-level precision. When swing is applied (house, garage), it is a mathematical ratio (e.g., 54% swing), not a human feel. The machine IS the musician.',
    humanizationMarkers: [
      'Swing percentage applied to hi-hats (house, garage — typically 54-58%)',
      'Velocity variation programmed into hi-hats and percussion (Roland TR-909 pattern emulation with accent steps)',
      'Subtle timing offsets on layered claps/snares (±5-10ms between layers) to create stereo width on festival systems',
      'Micro-pitch drift on analog synth emulations for warmth',
      'Ghost notes programmed with lower velocity to add texture between main hits',
    ],
    genreSpecificFeel: 'House has subtle swing on hi-hats that creates a human groove within the machine grid. Techno is deliberately rigid — the machine-like repetition IS the aesthetic. UK garage has heavy swing, the most "human" feel in EDM. Drum and bass has intricate programmed breakbeats that emulate (but exceed) human drumming. Trance is metronomic by design — the hypnotic state requires absolute consistency.',
  },

  silenceAndSpace: {
    overview: 'The build-drop dynamic is entirely about tension and release through presence and absence. The breakdown strips everything away — silence, a single vocal, a lone pad — creating a vacuum. The drop fills that vacuum with maximum sonic density. This architecture of absence-to-presence is EDM\'s most powerful structural device.',
    negativeSpaceRole: 'Structural — silence and space are engineered tools in EDM. The breakdown exists to create absence so the drop has maximum impact. A kick drum removed for 16 bars creates anticipation that its return satisfies explosively. Every element removed during a breakdown is calculated to amplify the drop.',
    breathingPatterns: 'Intro: sparse, building. Build: adding layers, increasing density. Pre-drop: maximum tension, often with a moment of silence. Drop: full frequency occupation. Breakdown: strip back to minimal elements. Build 2: repeat with higher stakes. Drop 2: bigger. Outro: gradual removal.',
    dynamicContrast: 'Extreme and engineered — the loudness difference between a breakdown and a drop is massive. White noise risers, snare rolls, and filter sweeps physically build anticipation. The silence before the drop is the most powerful moment in EDM — tens of thousands of people holding their breath simultaneously.',
    whatIsDeliberatelyAbsent: [
      'The kick drum removed during breakdowns — its absence creates longing for its return',
      'Bass frequencies pulled during builds, making the drop\'s sub-bass feel like a physical force',
      'All rhythm stripped to a single vocal or pad during the breakdown',
      'The "fake drop" — a moment of silence where the drop is expected but delayed',
      'Melody removed during verse sections so its return in the drop feels earned',
    ],
  },

  callAndResponse: {
    overview: 'EDM call-and-response is between the DJ/producer and the crowd — the build "calls" and the drop "responds." The audience raises hands during builds and explodes into dancing when the drop hits. This is a dialogue between sound system and bodies, mediated by the DJ.',
    vocalInstrumentalDialogue: 'When vocals are present, they call out during breakdowns and the synth/bass drop responds. Vocal chops in the drop serve as melodic responses to the sung phrases in the breakdown. The relationship is between human voice (emotional call) and synthetic sound (physical response).',
    sectionInternal: 'Build-to-drop is the primary call-and-response: tension calls for release. Within drops, synth stabs and bass hits alternate in rhythmic dialogue. Filter sweeps call for resolution. The entire track is an architecture of questions (builds) and answers (drops).',
    audienceParticipation: 'Massive and synchronized — thousands of people respond to the same build-drop cue simultaneously. Hands up during builds. Dancing during drops. The crowd becomes a single organism responding to the DJ\'s sonic commands. LED shows and visuals synchronize to reinforce the collective experience.',
    patterns: [
      'Build (rising energy) → Drop (explosive release) — the fundamental EDM call-and-response',
      'DJ shouts "Are you ready?" → crowd roars → drop hits',
      'Vocal hook in breakdown → synth melody answers in drop',
      'Filter sweep opening → full-frequency payoff',
      'Snare roll accelerating → silence → massive bass return',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'EDM regional identity is strong despite being a "global" genre — Detroit techno sounds different from Berlin techno, UK garage sounds nothing like American house, and Dutch hardstyle is unmistakably European. The "language" is production technique rather than spoken dialect.',
    phoneticMarkers: [
      'UK garage and grime: London slang in MC vocals ("mandem," "sick," "wagwan")',
      'French house: filtered disco samples with a distinctly Parisian warmth (Daft Punk aesthetic)',
      'Dutch hardstyle: anthemic vocal samples often in English but with European cadence',
      'Detroit techno: minimal, industrial, reflecting the city\'s post-industrial landscape in sound',
      'Ibiza/Mediterranean: balearic warmth, sunset-paced, drawing from Mediterranean musical traditions',
    ],
    accentInfluence: 'When EDM has vocals, accent matters — UK garage MCs sound distinctly London, French touch producers sample French-language vocals, and Latin EDM incorporates Spanish or Portuguese. The DJ\'s stage patter may carry regional accent. But in instrumental EDM, "accent" is expressed through production choices and sound selection rather than speech.',
    dialectVocabulary: [
      '"Drop," "build," "breakdown" — universal EDM structural vocabulary',
      '"Banger," "tune," "riddim" — UK electronic music slang',
      '"Filthy," "heavy," "disgusting" — bass music compliments that sound like insults',
      '"Peak time," "warm-up," "closing set" — DJ culture vocabulary',
      '"PLUR" (Peace, Love, Unity, Respect) — rave culture\'s defining ethos',
    ],
    regionWithinCulture: 'Berlin techno is darker, more minimal, and tied to club culture (Berghain). UK electronic music fragments into garage, grime, dubstep, DnB — all distinctly British. Dutch/Belgian hardstyle is its own world. Chicago house has soul and gospel DNA. Each city\'s electronic scene reflects its clubs, its nightlife laws, and its cultural history.',
  },

  performancePractice: {
    overview: 'EDM performance is the DJ set — not a band show. The DJ selects, sequences, and mixes pre-produced tracks to create a journey over 1-4 hours. The performance is curatorial and responsive: reading the crowd, building energy, and managing the emotional arc of the night.',
    improvisationConventions: 'Track selection is the primary improvisation — the DJ reads the room and adapts in real time. Some producers perform live sets with hardware (synths, drum machines, controllers), improvising arrangements. But the standard DJ set is about mixing existing tracks seamlessly, not creating new music on stage.',
    crowdInteraction: 'Physical and energetic but indirect — the DJ communicates through sound, not words. Raising hands, pointing, occasionally shouting over the mic. The LED show and visuals respond to the music. The crowd gives feedback through their energy level, and the DJ adjusts accordingly.',
    stagePresence: 'Behind the decks — the DJ is partially hidden by equipment. Festival DJs may stand on raised platforms with dramatic lighting. The "press play" controversy questions whether DJs are performing or just playing tracks. Authentic DJ performance involves visible mixing, track selection, and crowd reading.',
    livVsRecordedDifferences: 'A DJ set IS the live performance — it creates an unrepeatable sequence of tracks, transitions, and energy management. Studio productions are individual tracks; the live set weaves them into a continuous experience. Live electronic acts (Bonobo, Four Tet) use hardware to recreate and reinterpret studio tracks in real time.',
    whatMakesAGoodShow: 'Energy management — building from an opening warm-up to peak-time intensity to a satisfying close. Seamless mixing with creative transitions. Reading the crowd and adapting. A journey with peaks and valleys. Sound quality — EDM demands excellent sound systems. The moment when the entire crowd moves as one organism.',
  },

  socioeconomicSubtext: {
    overview: 'EDM emerged from marginalized communities — Black and queer communities in Chicago, Detroit, and New York — and has been repeatedly co-opted by mainstream commercial culture. The tension between underground authenticity and mainstream commercialization defines EDM\'s socioeconomic landscape.',
    materialConditions: 'House music was born in Black and Latino gay clubs in Chicago. Detroit techno emerged from post-industrial decline — the music of a city abandoned by the auto industry. UK rave culture arose partly from Thatcher-era youth unemployment. EDM\'s origins are consistently in communities under economic pressure.',
    classIdentity: 'Underground EDM culture is egalitarian — the dance floor is democratic, identity dissolves in collective movement. Mainstream EDM (festivals, VIP sections) has introduced class stratification. The underground-vs-commercial tension is partly about who can afford access and who is priced out.',
    politicalUndercurrent: 'PLUR (Peace, Love, Unity, Respect) is a political statement dressed as a party ethos. Rave culture was explicitly countercultural — the UK Criminal Justice Act of 1994 literally banned "repetitive beats" in public gatherings. EDM festivals operate in the tension between utopian vision and corporate sponsorship.',
    implicitReferences: [
      'The club as safe space for queer communities when public spaces were hostile',
      'Detroit techno\'s soundscape reflecting post-industrial urban decay',
      'Rave as escape from economic precarity — temporary utopia on a warehouse floor',
      'Festival ticket prices as gatekeeping mechanism contradicting PLUR values',
      'Bedroom producers circumventing the traditional music industry economic structure',
    ],
  },

  intertextualityAndSampling: {
    overview: 'EDM has a rich sampling tradition — house music was built on disco samples, early techno referenced Kraftwerk, and UK garage sampled R&B. The genre also has deep internal referentiality, with producers remixing, bootlegging, and referencing each other\'s tracks constantly.',
    canonKnowledge: 'Significant — knowing the seminal tracks, labels, and producers of each sub-genre is cultural capital. Recognizing samples and their sources is valued. Understanding lineages (Chicago house → UK house → tech house) demonstrates membership in the community.',
    samplingTradition: 'Central to EDM\'s DNA — house music was literally built on sampled disco loops. Jungle/DnB relies on chopped breakbeats (the "Amen break" is the most sampled loop in history). Modern EDM samples less due to copyright but still resamples, chops, and references.',
    quotationPractice: 'Remixes are the primary form of quotation — officially remixing another producer\'s track is both homage and collaboration. Bootleg remixes demonstrate skill and taste. DJ sets quote tracks by playing them — track selection IS quotation. "Edit" culture reworks classic tracks for modern floors.',
    expectedReferences: [
      'The "Amen break" — the drum break that built jungle, DnB, and influenced all electronic music',
      'Daft Punk\'s sampling of disco and funk as the template for French house',
      'The Roland TR-808 and TR-909 as foundational sound sources referenced in every sub-genre',
      'Frankie Knuckles and Larry Heard as the originators that all house music descends from',
      'Kraftwerk as the proto-electronic reference point for techno and synth-based EDM',
    ],
    lineageSignifiers: [
      'Sound selection: 909 kick = house/techno lineage, 808 hat = hip-hop crossover',
      'Mix style: long blends = deep house tradition, quick cuts = UK style',
      'Label affiliation signals sub-genre allegiance (Drumcode = techno, Hospital = liquid DnB)',
      'Software choice as identity: Ableton = modern production, hardware = purist credibility',
      'Remix credits demonstrate network position within the producer community',
      'Residency at a specific club = cultural positioning (Berghain, Fabric, Warehouse Project)',
    ],
  },

  genderAndBodyConventions: {
    overview: 'EDM originated in queer and Black communities where gender expression was fluid and the dance floor was a space for bodily liberation. Mainstream EDM festivals have introduced more conventional gender dynamics, but the underground maintains its tradition of gender fluidity and bodily freedom.',
    vocalGenderCodes: 'Female vocals dominate EDM features — the "EDM diva" tradition uses powerful female singers for emotional hooks over male-produced tracks. Male vocals appear in rap-influenced EDM and some house. Vocoder and processing can render the voice gender-ambiguous, which some producers use deliberately.',
    physicalityInPerformance: 'The dance floor is the performance space — everyone\'s body is performing. Dancing is the primary physical expression, and dance styles vary by sub-genre: two-step for house, headbanging for dubstep, shuffling for Melbourne bounce. The DJ\'s physicality is limited (behind decks), shifting the body-focus to the crowd.',
    genderNarratives: 'EDM lyrics, when present, tend toward universal themes (love, freedom, unity) that transcend gender specificity. Underground electronic music often abstracts the body entirely — instrumental techno has no gendered narrative at all. When EDM lyrics do address gender, they tend toward empowerment and desire.',
    subversionExamples: [
      'Honey Dijon and The Blessed Madonna centering queer and trans identity in DJ culture',
      'Peggy Gou and TOKiMONSTA achieving global DJ success on their own terms',
      'Vogue culture and ballroom influencing house music production and performance',
      'Sophie (hyperpop/electronic) using synthetic sound to explore gender fluidity',
      'Non-binary and gender-fluid DJs like Eris Drew creating spaces that reject binary categorization',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'In EDM, BPM is precise, measurable, and genre-defining — BUT the same BPM feels radically different across sub-genres. 128 BPM house feels groovy and relaxed. 128 BPM dubstep (half-time) feels heavy and sluggish. 140 BPM techno feels relentless. The subdivision and energy context transform the number.',
    psychologicalTempo: 'House at 124 BPM feels chill and groovy. Techno at 135 BPM feels driving and industrial. Trance at 138 BPM feels euphoric and building. DnB at 174 BPM feels energetic but not "fast" because the breakbeat has a half-time feel underneath. Dubstep at 140 BPM feels slow and heavy because the snare is half-time.',
    weightAndMomentum: 'Weight in EDM comes from sub-bass frequencies and sidechain compression — the "pumping" sensation. Momentum comes from relentless four-on-the-floor kicks or driving breakbeats. Dubstep has maximum weight and minimum momentum. Trance has maximum momentum and moderate weight. Deep house balances both.',
    urgencyScale: '1 (ambient chill) through 5 (deep house groove) to 10 (hardcore/gabber). House lives at 4-6: danceable without demanding. Techno lives at 6-8: driving and insistent. DnB lives at 7-9: fast and exciting. Dubstep lives at 4-5 despite high BPM: the half-time feel slows perceived urgency.',
    comparisonToSameBPM: 'EDM at 128 BPM is the global standard — four-on-the-floor house groove that millions of people dance to. Rock at 128 BPM feels fast and driving. Hip-hop at 128 BPM feels frenetic. Pop at 128 BPM feels energetic. EDM\'s synthesized palette and sidechain pumping create a unique physical sensation that other genres cannot replicate at the same tempo.',
  },

  mistakeConventions: {
    overview: 'EDM has NO tolerance for accidental mistakes — every sound is placed deliberately. Glitches, distortion, and artifacts ARE used, but they are designed, not accidental. A "mistake" in EDM is a production error that survived the final bounce, and it marks amateur work.',
    toleratedImperfections: [
      'Slight timing variations in live DJ mixing (beat-matching is a skill, not perfection)',
      'Analog synth drift that adds warmth and organic character',
      'Vinyl crackle and noise sampled for lo-fi aesthetic',
      'Slight reverb tail overlap between sections (can add continuity)',
      'Human-played elements (live percussion, guitar samples) retaining natural timing',
    ],
    celebratedFlaws: [
      'Glitch music\'s entire aesthetic — turning digital errors into deliberate musical material',
      'Lo-fi house using degraded samples and tape saturation as texture',
      'Acid house\'s "accidental" discovery: the TB-303\'s squelchy sound was a mistake that became a genre',
      'Burial\'s vinyl-crackle aesthetic — intentionally degraded sound as emotional texture',
      'Circuit-bent instruments producing unpredictable sounds embraced as creative tools',
    ],
    overproductionRisks: [
      'Over-compressed masters that cause listener fatigue on club systems',
      'Too many layers creating muddy, undefined frequency buildup',
      'Sidechain pumping so aggressive it sounds like the track is breaking',
      'Preset synth sounds that mark the producer as generic and uninspired',
      'Mix so "perfect" and clinical that it lacks the warmth needed for a sweaty dance floor',
    ],
    authenticRoughness: 'In EDM, "roughness" is a deliberate production choice, never an accident. Lo-fi house intentionally degrades sound quality. Distortion on bass is carefully designed. Noise and artifacts are selected and placed. The difference between a "rough" EDM track and a "bad" one is that the rough track sounds intentionally imperfect — every flaw is a feature. Accidental roughness is simply an unfinished production.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['EDM', 'electronic', 'dance', 'synthesizer', 'bass', 'beat', 'drop'],
    avoidKeywords: ['acoustic only', 'folk', 'country', 'classical', 'unplugged', 'organic only', 'lo-fi recording'],
    promptTemplate: '[sub-genre] electronic, [tempo] BPM, [mood] mood, [bass style], [lead style], [energy level]',
    tips: [
      'Specify the exact sub-genre: house, techno, trance, dubstep, DnB, etc.',
      'Describe the energy: dark, euphoric, chill, aggressive, hypnotic',
      'Mention specific production elements: supersaw, wobble bass, four-on-the-floor',
      'Reference the context: club, festival, chill, driving',
      'Describe the bass: sub-bass, wobble, Reese, deep, distorted',
      'Include BPM for precision — it matters in EDM more than any other genre',
    ],
  },
};
