import type { GenreGuide } from './types';

export const FOLK_GUIDE: GenreGuide = {
  id: 'folk',
  name: 'Folk',
  language: 'English',

  sonicPalette: {
    overview: 'Organic, acoustic, and human-centered. Folk music strips away production artifice to reveal the essential connection between voice, instrument, and story. The sound is warm, intimate, and unadorned.',
    timbre: [
      'Steel-string acoustic guitar (fingerpicked or strummed)',
      'Warm, natural vocal tone',
      'Fiddle/violin with folk bowing',
      'Banjo (clawhammer or three-finger)',
      'Mandolin with tremolo',
      'Harmonica (diatonic)',
      'Upright bass or acoustic bass',
      'Accordion/concertina',
    ],
    texture: 'Transparent and intimate — every instrument is clearly heard. The texture is sparse enough to highlight the vocal and lyric. Instruments complement rather than compete.',
    tonality: 'Natural and earthy — open guitar tunings (DADGAD, open D, open G). Standard keys: G, C, D, A, E. Modal flavors (Dorian, Mixolydian) for Celtic and traditional influences.',
    signatureSounds: [
      'Fingerpicked acoustic guitar patterns',
      'Fiddle drones and double-stops',
      'Banjo rolls and clawhammer',
      'Harmonica fills between vocal phrases',
      'Mandolin chop chords',
      'Open guitar tuning resonance',
      'Vocal harmony (close, tight)',
    ],
  },

  rhythmAndGroove: {
    overview: 'Organic and human — folk rhythm follows the song\'s emotional needs rather than a rigid grid. The groove is gentle, unforced, and breathes with the lyric.',
    bpmRange: { min: 60, max: 160, sweet: 110 },
    feel: 'Natural and unhurried. The rhythm serves the story. Even uptempo folk maintains an organic, human quality. Tempo can flex with emotional moments.',
    swing: 'Varies — Celtic folk uses jig and reel rhythms (compound time). American folk tends toward straight feel. Some shuffle influence from blues and country.',
    syncopation: 'Minimal — folk rhythm is straightforward and supportive. Fingerpicking patterns create gentle rhythmic interest. The vocal has freedom to phrase naturally.',
    grooveArchetype: 'Fingerpicked ballad, strummed campfire rhythm, Celtic jig/reel, or folk-rock drive',
    rhythmicSignatures: [
      'Fingerpicking patterns (Travis picking, arpeggios)',
      'Simple strumming (down-up patterns)',
      'Waltz time (3/4) for ballads',
      'Jig (6/8) and reel (4/4) for Celtic',
      'Boom-chuck bass-strum pattern',
      'Handclaps and foot stomps',
      'Brushed or light percussion',
    ],
  },

  harmonicLanguage: {
    overview: 'Simple and modal — folk harmony uses basic chords in distinctive ways. Open voicings, drone strings, and modal flavors create the folk sound. Simplicity serves the song.',
    scales: ['Major (Ionian)', 'Dorian', 'Mixolydian', 'Aeolian', 'Pentatonic'],
    chordProgressions: [
      'I – IV – V – I (basic folk)',
      'I – V – I – IV (verse pattern)',
      'i – bVII – bVI – V (minor folk)',
      'I – IV – I – V (campfire pattern)',
      'i – iv – bVII – bIII (modal folk)',
      'I – bVII – IV – I (Mixolydian folk)',
    ],
    harmonyNotes: 'Open voicings with ringing strings. Suspended chords (sus2, sus4) for modal color. Drone strings on guitar and banjo. Parallel movement instead of functional harmony. Keep it simple.',
    modality: 'Modal — Dorian, Mixolydian, and Aeolian modes are more common than strict major/minor. Celtic folk is deeply modal. American folk is more major-key focused.',
  },

  songStructure: {
    overview: 'Story-first structure — the song form serves the narrative. Verses carry the story, choruses provide emotional anchors, and the structure can be as free as the story demands.',
    form: 'Verse – Chorus – Verse – Chorus – Verse – Chorus (or through-composed ballad)',
    sections: ['Intro', 'Verse 1', 'Chorus', 'Verse 2', 'Chorus', 'Verse 3', 'Bridge (optional)', 'Chorus', 'Outro'],
    arrangement: 'Minimal and supportive. Start with voice and guitar, add instruments gradually. Keep the arrangement subservient to the lyric. Less is more.',
    introOutro: 'Intros: guitar riff, instrumental verse, or a cappella opening. Outros: instrumental tag, final vocal phrase, or fade on the riff. Some songs start without intro — straight into the first verse.',
    barLengths: 'Verses: 8-16 bars (flexible — odd-length verses are acceptable). Chorus: 4-8 bars. Through-composed ballads: variable. Total: 3-6 minutes.',
    hookPlacement: 'Chorus is the hook — a memorable, singable refrain. Some folk songs are verse-only with no chorus (through-composed). The lyrical hook may be a repeated line at the end of each verse.',
  },

  vocalDelivery: {
    overview: 'Natural, unprocessed, and storytelling-focused. Folk vocals prioritize clarity of lyric and sincerity of emotion. The voice should sound like a real person telling you a story.',
    phrasing: 'Conversational and story-driven — phrasing follows natural speech patterns. The singer tells the story; the melody carries the emotion. Breathing between phrases is natural.',
    affect: 'Sincere, intimate, and honest. Folk vocal delivery values authenticity over vocal pyrotechnics. The emotion is subtle but genuine.',
    techniques: [
      'Natural, unprocessed tone',
      'Clear diction for storytelling',
      'Tight harmony singing (close intervals)',
      'A cappella passages',
      'Drone singing (Celtic tradition)',
      'Nasal resonance (traditional folk tone)',
      'Call-and-response (work song tradition)',
      'Vocal ornamentation (Celtic/traditional)',
    ],
    adlibStyle: 'Minimal — folk is composed, not improvised vocally. Some "hey" and "ho" refrains. Wordless humming between verses. Traditional "mouth music" in Celtic traditions.',
    harmony: 'Close, tight harmonies — often in 3rds or unison. Two-part and three-part harmony in choruses. A cappella harmony sections. Family-style close harmony (Carter Family, Everly Brothers influence).',
    grit: 'Natural — some character in the voice is valued (Bob Dylan, Joni Mitchell). Perfect pitch is less important than storytelling ability. The voice should sound human and honest.',
  },

  lyricalConventions: {
    overview: 'Folk is the great storytelling genre — lyrics are the heart of the music. Folk lyrics tell stories, paint pictures, make arguments, and preserve traditions. The lyric IS the song.',
    themes: [
      'Love and heartbreak',
      'Social justice and protest',
      'Nature and the land',
      'Working-class life',
      'Travel and wandering',
      'Historical events and figures',
      'Death and loss',
      'Community and belonging',
      'Personal reflection',
    ],
    perspective: 'First person narrative, third person storytelling, or communal "we." Folk songs can adopt characters and tell stories from multiple perspectives.',
    figurativeLanguage: 'Nature imagery — rivers, mountains, seasons, weather. Journey metaphors. Specific, concrete details that ground abstract emotions. Traditional imagery (roses, ships, roads).',
    vocabulary: 'Simple, poetic, and accessible. Regional dialect acceptable. Traditional language and phrasing. No jargon or pretension. Words chosen for sound and meaning.',
    storytellingApproach: 'Narrative-driven — many folk songs tell complete stories with beginning, middle, and end. Each verse advances the plot. Ballad form allows extended narratives. Topical songs address current issues.',
    cliches: [
      'Rolling hills and winding roads',
      'The times they are a-changin\'',
      'Blowin\' in the wind',
      'This land is your land',
      'Down by the river/sea',
      'Leaving home/coming home',
    ],
  },

  productionFingerprint: {
    overview: 'Minimal and organic — folk production captures the natural sound of acoustic instruments and voice. The production should be invisible, serving the song without calling attention to itself.',
    mixAesthetic: 'Intimate, warm, and natural. Voice clearly in front. Instruments surround and support. Minimal effects. Natural room sound. The listener should feel present in the room with the performer.',
    era: 'Folk recording spans from raw field recordings to polished studio work. The aesthetic always prioritizes natural sound and performance.',
    signalChain: 'Acoustic guitar: small-diaphragm condenser at 12th fret + room mic. Vocals: large-diaphragm condenser, minimal processing. Minimal overdubbing. Natural reverb preferred.',
    modernTrends: 'Indie folk with fuller production. Chamber folk incorporating orchestral elements. Electronic folk (folk-tronica). Lo-fi folk aesthetics. Folk-pop crossover.',
  },

  instrumentation: {
    coreInstruments: [
      'Acoustic guitar (steel-string or nylon)',
      'Vocals',
      'Fiddle/violin',
      'Banjo',
      'Mandolin',
      'Harmonica',
      'Upright bass',
      'Accordion',
    ],
    signatureSounds: [
      'Fingerpicked acoustic guitar',
      'Fiddle drones',
      'Banjo rolls',
      'Mandolin tremolo',
      'Harmonica bends',
      'Open tuning resonance',
      'Tin whistle (Celtic)',
    ],
    layering: 'Minimal — each instrument has a clear role. Guitar provides rhythm and harmony. Fiddle and mandolin add melody. Bass provides foundation. Don\'t overcrowd.',
    avoidInstruments: [
      'Electric distortion',
      'Drum machines',
      'Synthesizers (traditional folk)',
      'Auto-Tune',
      'Heavy production effects',
    ],
  },

  culturalContext: {
    overview: 'Folk music belongs to the people — it\'s the music of communities, traditions, and shared stories. Folk exists in every culture; in the Anglophone tradition, it represents democratic, populist musical expression.',
    origin: 'Ancient oral tradition — folk songs have been passed down for centuries. The modern folk movement crystallized in the early 20th century with collectors like Alan Lomax and performers like Woody Guthrie.',
    identity: 'Democratic and populist — folk music belongs to everyone. Anti-commercial, community-oriented. Connected to social justice movements. Values authenticity and tradition.',
    community: 'Folk festivals, coffee houses, open mics, and house concerts. Song circles and jam sessions. Online folk communities. Strong tradition of mentorship and song sharing.',
    socialFunction: 'Preserving cultural heritage, social protest, community bonding, and personal storytelling. Folk music has been the voice of social movements from labor rights to civil rights to environmental justice.',
    authenticityMarkers: [
      'Songwriting ability and storytelling skill',
      'Acoustic musicianship',
      'Connection to folk traditions',
      'Social consciousness',
      'Genuine, unpretentious presentation',
      'Community engagement',
    ],
  },

  historicalLineage: {
    overview: 'From ancient ballads to modern singer-songwriters, folk music represents the oldest and most enduring form of musical expression — people sharing stories through song.',
    roots: ['Traditional Ballads', 'Work Songs', 'Protest Songs', 'Celtic Music', 'Appalachian Music'],
    evolution: 'Traditional folk songs (centuries old) → Folk collecting and preservation (early 1900s) → Woody Guthrie and protest folk (1940s) → Folk revival (1950s-60s) → Singer-songwriter movement (1970s) → Indie folk (2000s-present).',
    keyEras: [
      'Pre-1900: Traditional ballads and oral tradition',
      '1940s: Woody Guthrie and Pete Seeger',
      '1960s: Folk revival (Bob Dylan, Joan Baez)',
      '1970s: Singer-songwriter era (Joni Mitchell, James Taylor)',
      '2000s-present: Indie folk revival (Iron & Wine, Fleet Foxes, Bon Iver)',
    ],
    influencedBy: ['Traditional Music', 'Blues', 'Country', 'Celtic Music', 'Gospel'],
    influenced: ['Rock', 'Country', 'Singer-Songwriter', 'Indie', 'Americana'],
  },

  subGenres: [
    {
      name: 'Traditional Folk',
      description: 'Songs from the oral tradition — ballads, sea shanties, work songs, and traditional melodies passed down through generations.',
      distinguishingFeatures: ['Traditional melodies and lyrics', 'Oral tradition origin', 'Simple accompaniment', 'Story-ballad form', 'Regional variations'],
      keyArtists: ['Woody Guthrie', 'Pete Seeger', 'The Weavers', 'Jean Ritchie', 'A.L. Lloyd'],
      productionNotes: 'Minimal production. Acoustic instruments only. Natural sound. Capture the tradition authentically.',
      lyricNotes: 'Traditional stories, ballads, work songs. Historical events. Community songs for singing together.',
      sunoPromptKeywords: ['traditional folk', 'folk ballad', 'acoustic', 'traditional', 'folk song', 'heritage'],
    },
    {
      name: 'Contemporary Folk',
      description: 'Modern singer-songwriter folk with personal lyrics, acoustic instrumentation, and storytelling craft.',
      distinguishingFeatures: ['Personal songwriting', 'Acoustic instrumentation', 'Modern themes', 'Studio production quality', 'Singer-songwriter tradition'],
      keyArtists: ['Joni Mitchell', 'James Taylor', 'Nick Drake', 'Iron & Wine', 'Phoebe Bridgers'],
      productionNotes: 'Clean, warm recording. Acoustic instruments with possible light production. Vocal-forward. Intimate and personal.',
      lyricNotes: 'Personal, introspective, poetic. Modern life and relationships. Literary craft. Emotional depth.',
      sunoPromptKeywords: ['contemporary folk', 'singer-songwriter', 'acoustic', 'intimate', 'personal', 'modern folk'],
    },
    {
      name: 'Folk Rock',
      description: 'Folk songwriting with rock instrumentation — electric guitars, drums, and full band arrangements serving folk melodies and lyrics.',
      distinguishingFeatures: ['Electric instruments with folk songs', 'Full band arrangement', 'Rock energy with folk sensibility', 'Dylan-influenced', 'Socially conscious lyrics'],
      bpmRange: { min: 100, max: 150 },
      keyArtists: ['Bob Dylan (electric)', 'The Byrds', 'Fairport Convention', 'Mumford & Sons', 'The Lumineers'],
      productionNotes: 'Full band with acoustic and electric guitars. Driving drums. Folk melodies with rock energy. Can be raw or polished.',
      lyricNotes: 'Folk storytelling with rock attitude. Social commentary. Personal and political. Singable choruses.',
      sunoPromptKeywords: ['folk rock', 'electric folk', 'roots rock', 'Americana rock', 'Dylan', 'jangly folk'],
    },
    {
      name: 'Indie Folk',
      description: 'DIY-ethos folk with indie rock sensibility — intimate, quirky, and artistically independent.',
      distinguishingFeatures: ['Indie aesthetic with folk instruments', 'Lo-fi or bedroom production', 'Quirky, personal songwriting', 'Artistic independence', 'Gentle, intimate delivery'],
      bpmRange: { min: 70, max: 130 },
      keyArtists: ['Bon Iver', 'Fleet Foxes', 'Sufjan Stevens', 'Big Thief', 'Adrianne Lenker'],
      productionNotes: 'Intimate, sometimes lo-fi production. Layered acoustic instruments. Reverb and atmospheric touches. Can be sparse or lush.',
      lyricNotes: 'Personal, literary, abstract. Nature imagery. Emotional vulnerability. Poetic and unconventional.',
      sunoPromptKeywords: ['indie folk', 'chamber folk', 'intimate', 'lo-fi folk', 'ethereal folk', 'gentle', 'atmospheric'],
    },
    {
      name: 'Celtic Folk',
      description: 'Traditional and contemporary music from Ireland, Scotland, Wales, and Brittany. Modal melodies, complex rhythms, and distinctive instruments.',
      distinguishingFeatures: ['Modal melodies (Dorian, Mixolydian)', 'Celtic instruments (tin whistle, uilleann pipes, bodhrán)', 'Jig and reel rhythms', 'Ornamental vocal style', 'Irish/Scottish tradition'],
      bpmRange: { min: 80, max: 160 },
      keyArtists: ['The Chieftains', 'Planxty', 'Loreena McKennitt', 'The Pogues', 'Lankum'],
      productionNotes: 'Traditional instruments recorded naturally. Jig and reel rhythms. Modal harmonies. Can be traditional or contemporary fusion.',
      lyricNotes: 'Traditional ballads, love songs, drinking songs. Irish/Scottish themes. Gaelic language optional. Nature and history.',
      sunoPromptKeywords: ['Celtic folk', 'Irish folk', 'Celtic', 'jig', 'reel', 'tin whistle', 'bodhrán', 'traditional Irish'],
    },
    {
      name: 'Appalachian Folk',
      description: 'Music from the Appalachian mountain region — old-time string band music, murder ballads, and mountain traditions.',
      distinguishingFeatures: ['Old-time string band instrumentation', 'Clawhammer banjo', 'Mountain fiddle', 'Murder ballads and traditional songs', 'High lonesome vocal style'],
      bpmRange: { min: 80, max: 140 },
      keyArtists: ['Doc Watson', 'Ralph Stanley', 'Gillian Welch', 'Old Crow Medicine Show', 'Rhiannon Giddens'],
      productionNotes: 'Raw, acoustic recording. Old-time instruments. Natural sound. Mountain music authenticity.',
      lyricNotes: 'Mountain life, death, murder ballads, faith, love. Traditional storytelling. Dark and beautiful.',
      sunoPromptKeywords: ['Appalachian', 'old-time', 'mountain music', 'clawhammer banjo', 'mountain folk', 'string band'],
    },
    {
      name: 'Anti-Folk',
      description: 'Deliberately rough, humorous, and anti-establishment folk. Rejects folk purity in favor of punk energy and ironic sensibility.',
      distinguishingFeatures: ['Deliberately rough performance', 'Humor and irony', 'Punk energy', 'Anti-establishment attitude', 'DIY aesthetic'],
      bpmRange: { min: 80, max: 160 },
      keyArtists: ['The Moldy Peaches', 'Kimya Dawson', 'Jeffrey Lewis', 'Beck (early)'],
      productionNotes: 'Lo-fi, rough recording. Embrace imperfection. Punk energy with folk instruments. DIY production.',
      lyricNotes: 'Ironic, humorous, absurdist. Anti-folk conventions. Personal and weird. Stream of consciousness.',
      sunoPromptKeywords: ['anti-folk', 'lo-fi folk', 'punk folk', 'quirky', 'rough', 'DIY', 'ironic folk'],
    },
    {
      name: 'Neofolk',
      description: 'Dark, atmospheric folk drawing from European pagan and martial traditions. Acoustic instruments with dark, apocalyptic themes.',
      distinguishingFeatures: ['Dark, atmospheric mood', 'European pagan/martial themes', 'Acoustic instruments', 'Apocalyptic or historical themes', 'Industrial-adjacent aesthetic'],
      bpmRange: { min: 60, max: 120 },
      keyArtists: ['Death in June', 'Current 93', 'Wardruna', 'Heilung'],
      productionNotes: 'Dark, atmospheric production. Acoustic instruments with processing. Drones and chanting. Cinematic quality.',
      lyricNotes: 'Pagan, mythological, apocalyptic. European history and mythology. Dark poetry. Archaic language.',
      sunoPromptKeywords: ['neofolk', 'dark folk', 'pagan folk', 'atmospheric', 'Norse', 'Viking folk', 'ritual'],
    },
    {
      name: 'Freak Folk',
      description: 'Psychedelic, experimental folk pushing boundaries with unconventional structures, effects, and avant-garde approaches.',
      distinguishingFeatures: ['Psychedelic influence', 'Experimental structures', 'Unconventional vocal styles', 'Acoustic and electronic blend', 'Avant-garde approach'],
      bpmRange: { min: 50, max: 140 },
      keyArtists: ['Devendra Banhart', 'Joanna Newsom', 'Animal Collective (early)', 'CocoRosie'],
      productionNotes: 'Experimental production with folk instruments. Psychedelic effects. Unconventional recording techniques. Embrace the weird.',
      lyricNotes: 'Abstract, surreal, childlike. Fantasy and imagination. Stream of consciousness. Unconventional poetry.',
      sunoPromptKeywords: ['freak folk', 'psychedelic folk', 'experimental folk', 'weird folk', 'avant-folk', 'trippy acoustic'],
    },
    {
      name: 'Folk Punk',
      description: 'Punk energy and attitude with folk instrumentation. Fast, aggressive acoustic performances with political and personal lyrics.',
      distinguishingFeatures: ['Punk energy with acoustic instruments', 'Fast, aggressive playing', 'Political lyrics', 'DIY ethos', 'Raw, live feel'],
      bpmRange: { min: 140, max: 200 },
      keyArtists: ['The Pogues', 'Dropkick Murphys', 'Against Me!', 'Frank Turner', 'Days N\' Daze'],
      productionNotes: 'Raw, energetic recording. Fast acoustic strumming. Full band with punk energy. Celtic influence common. Live, aggressive sound.',
      lyricNotes: 'Political, personal, rebellious. Working-class themes. Drinking and defiance. Punk directness with folk storytelling.',
      sunoPromptKeywords: ['folk punk', 'Celtic punk', 'acoustic punk', 'fast folk', 'rebellious', 'energetic folk', 'raw'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Folk audiences value songwriting, authenticity, and community. The scene is inclusive, community-oriented, and values the song above all else.',
    fanExpectations: [
      'Strong songwriting and storytelling',
      'Authentic, genuine presentation',
      'Acoustic musicianship',
      'Social consciousness',
      'Community engagement',
      'Singable songs for group participation',
    ],
    gatekeeping: 'Low to moderate — folk is generally welcoming. Some traditional purists. Debates about folk-pop crossover. The emphasis is on shared experience rather than exclusion.',
    livePerformance: 'Intimate venues — coffee houses, small theaters, festivals, house concerts. Audience listens and sings along. Storytelling between songs. Acoustic, intimate settings.',
    fashionAndAesthetic: 'Casual, earthy, unpretentious. Flannel, denim, wool. No costume needed. The focus is on the music, not the image.',
    crossoverPotential: 'Moderate — indie folk and folk-pop cross over regularly (Mumford & Sons, The Lumineers). Pure folk remains niche but beloved.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Folk micro-timing is organic and breath-driven — the tempo follows the singer\'s phrasing, not a click track. The guitarist adjusts to the vocal, the fiddle adjusts to the guitarist, and everything breathes together like a conversation rather than a machine.',
    quantizationDeviation: 'High — folk is deliberately unquantized. Tempo may drift between verses as emotional intensity shifts. A song might slow down for a poignant line and speed up for a joyful one. This temporal freedom IS folk music\'s relationship to time.',
    aheadBehindBeat: 'Folk sits where the song needs it — there is no fixed grid to be ahead or behind. Fingerpicking patterns have their own internal rhythm that may drift from strict tempo. Ensemble folk (string bands, Celtic sessions) locks together through listening rather than to a metronome.',
    humanizationMarkers: [
      'Tempo rubato around emotionally important lyrics',
      'Fingerpicking patterns that subtly accelerate during exciting verses',
      'Foot-tapping and body movement audible in the recording',
      'Fiddle bowing that phrases ahead of the guitar rhythm for urgency',
      'Collective breathing in ensemble playing — the group speeds up and slows down together',
    ],
    genreSpecificFeel: 'Celtic jigs and reels have a specific "lift" — the emphasis within 6/8 time that makes it dance-able vs. merely metered. Appalachian old-time has a "round" feel where the banjo clawhammer and fiddle interlock into a single pulsing texture. Singer-songwriter folk follows the voice — the instrument accompanies the speaker, not the other way around.',
  },

  silenceAndSpace: {
    overview: 'Folk music is built on space — the genre strips away everything unnecessary until only the voice, the story, and one or two instruments remain. Space is not emptiness; it is the room in which the listener\'s imagination operates. A folk song with too many instruments has betrayed its form.',
    negativeSpaceRole: 'Fundamental — negative space in folk is where the listener enters the song. Between vocal phrases, the listener processes the story. Between instrumental fills, the voice regains primacy. The transparency of the arrangement is a form of generosity toward the audience.',
    breathingPatterns: 'Single instrument and voice for verses — the most stripped arrangement. Harmony vocals may enter on choruses. Additional instruments appear and disappear as the narrative demands. Some songs are entirely voice and single guitar for the full duration.',
    dynamicContrast: 'Subtle — folk dynamic contrast comes from arrangement density and vocal intensity, not volume. Adding a fiddle to a guitar-and-voice verse creates expansion. Dropping to a cappella creates stark intimacy. The dynamic range is narrow compared to rock but deeply felt.',
    whatIsDeliberatelyAbsent: [
      'Drums and percussion — many folk songs have none at all',
      'Electric instruments in traditional folk (their absence defines the genre)',
      'Production effects — no reverb, compression, or processing announcing themselves',
      'Harmonic complexity — simple chords leave room for the lyric to work',
      'Vocal melisma — folk singing is direct, one note per syllable, leaving interpretive space',
    ],
  },

  callAndResponse: {
    overview: 'Folk call-and-response is ancient and communal — rooted in work songs, sea shanties, and protest chants where a leader sings a line and the group answers. This is folk\'s deepest participatory tradition, designed for group singing, not solo performance.',
    vocalInstrumentalDialogue: 'The instrument accompanies the voice — guitar or banjo provides harmonic and rhythmic support while the voice carries the story. Instrumental interludes between verses serve as "response" sections where the melody is restated without words.',
    sectionInternal: 'In traditional folk, each verse often ends with a repeated refrain line that the audience can join. The verse tells the story (call), the refrain provides the communal emotional anchor (response). This structure invites participation by design.',
    audienceParticipation: 'Central to folk\'s identity — folk music is meant to be sung together. Audiences join on choruses, refrains, and known songs. Song circles where everyone takes turns leading. The boundary between performer and audience is deliberately thin.',
    patterns: [
      'Leader sings verse → group sings refrain (sea shanty and work song tradition)',
      'One voice starts → others join in harmony (the "swell" of communal singing)',
      'Spoken introduction → sung song (the story behind the song as call, the song as response)',
      'Solo verse → full ensemble chorus (building community within the song)',
      'Question lyric in verse → answer lyric in refrain (classic folk dialectic structure)',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Folk music IS regional dialect made musical — every folk tradition carries the accent, vocabulary, and speech patterns of its place. Appalachian folk sounds like the mountains, Celtic folk sounds like the coast, and protest folk carries the urban cadences of labor halls and picket lines.',
    phoneticMarkers: [
      'Appalachian folk: "hit" for "it," "a-going" prefix, archaic Elizabethan vowel sounds preserved in mountain speech',
      'Celtic/Irish folk: rolled r\'s, Gaelic phonetic influence even in English-language songs',
      'English folk: regional accents preserved — Yorkshire, West Country, Northumbrian dialect in song',
      'American protest folk: Woody Guthrie\'s Oklahoma drawl, Dylan\'s Minnesota nasality',
      'Maritime/sea shanty: clipped, rhythmic diction shaped by call-and-response at sea',
    ],
    accentInfluence: 'Folk singers are expected to sing in their natural accent — affectation is antithetical to the genre. Bob Dylan\'s nasal Minnesota voice, Woody Guthrie\'s Oklahoma dust-bowl drawl, and Dick Gaughan\'s broad Scots are not obstacles to overcome but essential to the music\'s authenticity.',
    dialectVocabulary: [
      '"Holler," "yonder," "over the mountain" — Appalachian landscape vocabulary',
      '"Bonnie," "loch," "brae" — Scottish folk vocabulary that persists in English-language songs',
      '"Solidarity," "union," "brothers and sisters" — labor movement folk vocabulary',
      '"Fallow," "harvest," "tillage" — agricultural vocabulary reflecting rural life',
      '"Farewell," "journey," "wander" — folk travel vocabulary with archaic roots',
    ],
    regionWithinCulture: 'Appalachian folk and Ozark folk share instruments but differ in repertoire and vocal style. Irish and Scottish folk are closely related but distinct in ornamentation and rhythm. English folk has its own tradition separate from Celtic. Each region produces songs that could only come from that specific place.',
  },

  performancePractice: {
    overview: 'Folk performance is intimate, communal, and focused on the song rather than the performer. The ideal folk performance creates a circle of shared attention — the performer is a conduit for the song, not a star above the audience.',
    improvisationConventions: 'Minimal in terms of composition — folk songs are fixed texts, often traditional. But interpretation is everything: phrasing, ornamentation, tempo, and emotional emphasis are the performer\'s creative contribution. Celtic musicians improvise ornamentation within rigid melodic frameworks.',
    crowdInteraction: 'Intimate and conversational — storytelling between songs, explaining the song\'s origin and meaning. Making eye contact with the audience. Inviting the audience to sing along. Creating a temporary community in the room.',
    stagePresence: 'Understated — the performer sits or stands with instrument, no theatrics. The focus is entirely on voice, lyric, and music. A stool, a microphone, and a guitar is sufficient. Sincerity is the stage presence.',
    livVsRecordedDifferences: 'Live folk adds spoken introductions, audience interaction, and communal singing. Songs may be performed differently each time — varied tempo, added verses, adapted lyrics. The live setting is folk\'s natural habitat; recordings are documentations of what is essentially a live art form.',
    whatMakesAGoodShow: 'A mix of known songs and deep cuts. Stories between songs that give context and build connection. A moment where the entire audience sings together. Emotional honesty — the performer visibly moved by their own material. The feeling of being gathered around a fire, even in a theater.',
  },

  socioeconomicSubtext: {
    overview: 'Folk is the music of the working class, the dispossessed, and the community. Its protest tradition directly addresses labor conditions, poverty, and systemic injustice. Folk emerged from people who had no other platform — the song was both entertainment and political statement.',
    materialConditions: 'Folk music emerges from material hardship — agricultural labor, factory work, mining, fishing. Songs describe specific working conditions because they were sung BY workers. The union organizing tradition produced folk songs as tools of solidarity and resistance.',
    classIdentity: 'Folk identifies with working-class and rural communities. The "folk" in folk music means "the common people." Academic and middle-class folk revivalists (1950s-60s) sometimes romanticized working-class experience, creating tension between authentic and performed folk identity.',
    politicalUndercurrent: 'Explicit — folk is the most politically engaged genre in popular music. Woody Guthrie\'s guitar read "This machine kills fascists." Pete Seeger sang at labor rallies. Bob Dylan wrote civil rights anthems. Phil Ochs covered Vietnam. Folk does not hide its politics.',
    implicitReferences: [
      'Coal mining disasters and dangerous labor conditions (folk songs as workplace safety advocacy)',
      'Land dispossession — songs about being driven from home by landlords or economic forces',
      'Migration and displacement — dust bowl, industrial migration, immigration',
      'Union organizing as community survival strategy',
      'The commons — shared land, shared water, shared songs as resistance to privatization',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Folk is the most deeply intertextual genre — songs are passed down, modified, covered, and reimagined across centuries and continents. The folk canon is a living body of songs that every participant is expected to know, contribute to, and pass along.',
    canonKnowledge: 'Extensive — a folk musician is expected to know traditional songs, Child Ballads, protest standards, and the repertoire of major figures (Guthrie, Dylan, Joni Mitchell). Performing a traditional song is not just covering it — it\'s joining a chain of transmission.',
    samplingTradition: 'Folk\'s "sampling" is the traditional song itself — melodies and lyrics are borrowed, adapted, and recombined freely. Dylan\'s "Blowin\' in the Wind" melody comes from a spiritual. "Scarborough Fair" has dozens of variants. This is not plagiarism but participation in a shared tradition.',
    quotationPractice: 'Direct quotation of traditional songs, melodies, and lyrics is standard practice. Writing new words to old tunes is a venerable folk technique (contrafactum). Referencing traditional songs in new compositions signals membership in the tradition.',
    expectedReferences: [
      'Child Ballads (the core English-language folk canon)',
      'Woody Guthrie\'s songs as American folk foundation',
      'Bob Dylan\'s electric transition as a defining folk moment',
      '"We Shall Overcome" and the civil rights folk tradition',
      'Traditional melodies that reappear in dozens of different songs with different lyrics',
    ],
    lineageSignifiers: [
      'Performing traditional songs demonstrates knowledge and respect for the canon',
      'Guitar style (fingerpicking patterns) references specific folk traditions',
      'Instrument choice signals lineage: banjo = Appalachian, bodhrán = Celtic, harmonica = blues-folk',
      'Naming influences in liner notes and stage banter is expected and valued',
      'Protest songwriting positions artist within the Guthrie-Seeger-Dylan lineage',
      'Cover songs are not "unoriginal" — they are active participation in oral tradition',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Folk has a more egalitarian gender tradition than many genres — women have been central to folk music as performers, songwriters, and tradition-bearers since before recorded music. Joan Baez, Joni Mitchell, and Peggy Seeger are as canonical as their male counterparts.',
    vocalGenderCodes: 'Folk vocal conventions are relatively open — women and men sing in their natural voices without genre-imposed modifications. The "folk voice" prioritizes clarity and storytelling ability over gendered vocal qualities. High male voices (falsetto), low female voices, and everything between are accepted.',
    physicalityInPerformance: 'Minimal and non-gendered — the performer sits or stands with an instrument. Physical display is not part of folk performance convention. The body is present as a voice-producing instrument, not as a spectacle. This creates an inherently more gender-equal performance space.',
    genderNarratives: 'Women in folk songs occupy the full range of roles: lovers, mothers, workers, warriors, murder victims, and murderers. Traditional ballads often center women\'s experiences. The singer-songwriter tradition gave women equal narrative authority. Protest folk addresses gender oppression directly.',
    subversionExamples: [
      'Peggy Seeger\'s "I\'m Gonna Be an Engineer" — feminist folk songwriting from 1970',
      'Joni Mitchell redefining what confessional songwriting could be for any gender',
      'Ani DiFranco building an independent folk career outside major-label gender expectations',
      'Traditional ballads where women take agency (e.g., "Tam Lin," "The Female Highwayman")',
      'Rhiannon Giddens centering Black women\'s stories in the folk/Americana tradition',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Folk tempo is fluid and story-driven — the same song might be performed at 90 BPM or 120 BPM depending on the performer\'s interpretation and the room\'s energy. The tempo serves the narrative pacing, not the other way around. Rubato is natural, not exceptional.',
    psychologicalTempo: 'A fast Celtic reel at 160 BPM feels joyful and dance-driven. A ballad at 70 BPM feels contemplative and weighty. A protest march song at 100 BPM feels determined and collective. The emotional content determines how the tempo is experienced more than the number itself.',
    weightAndMomentum: 'Folk has very little weight compared to rock or metal — acoustic instruments are inherently lighter. Momentum in folk comes from rhythmic patterns (fingerpicking, strumming, reels) rather than volume or distortion. A driving folk song has momentum without heaviness.',
    urgencyScale: '1 (slow unaccompanied ballad) through 5 (mid-tempo fingerpicked song) to 10 (breakneck reel or punk-folk). Most folk lives at 3-6: conversational and unhurried. Celtic dance tunes push to 8-9. Lullabies and laments sit at 1-2.',
    comparisonToSameBPM: 'Folk at 120 BPM feels easy and organic — the acoustic palette and human timing make it feel slower than it is. Rock at 120 BPM feels more driven. Pop at 120 BPM feels more energetic. Folk\'s natural timing variations and transparent arrangements make the same tempo feel more spacious and relaxed.',
  },

  mistakeConventions: {
    overview: 'Folk celebrates rawness and imperfection as virtues — a rough voice, loose timing, and simple technique are valued over polish. The folk aesthetic holds that the song matters more than the performance, and that "perfection" is a commercial imposition antithetical to folk\'s democratic values.',
    toleratedImperfections: [
      'Off-pitch singing that conveys emotional truth over vocal precision',
      'Loose timing between instruments in ensemble playing',
      'Guitar buzzing and string noise from hand-played instruments',
      'Forgotten lyrics recovered with grace or humor',
      'Audience noise, coughing, and ambient sound in recordings',
    ],
    celebratedFlaws: [
      'Bob Dylan\'s nasal, untrained voice — arguably the most influential vocal in folk history',
      'Woody Guthrie\'s rough recordings that prioritize message over fidelity',
      'Field recordings with ambient noise as authentic documentation',
      'The Anthology of American Folk Music\'s crackly, lo-fi recordings as sacred texts',
      'Intentionally "unprofessional" anti-folk (Moldy Peaches, Jeffrey Lewis)',
    ],
    overproductionRisks: [
      'Pitch correction that removes the human character of the voice',
      'Adding drums or electric instruments that overwhelm the acoustic intimacy',
      'Studio reverb that creates artificial space instead of real-room sound',
      'Quantized timing that removes the natural tempo flexibility of folk performance',
      'Multi-tracking and layering that turn a solo performer into a "band" sound',
    ],
    authenticRoughness: 'In folk, roughness is not a failure of technique — it is a statement of values. Singing "perfectly" implies prioritizing performance over communication. A cracked voice on an emotional line is worth more than a polished one. The tradition holds that if you have something to say, the way you say it matters less than the saying.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['folk', 'acoustic', 'storytelling', 'fingerpicking', 'organic', 'singer-songwriter', 'intimate'],
    avoidKeywords: ['electronic', 'bass drop', 'auto-tune', 'industrial', 'heavy metal', 'club', 'trap'],
    promptTemplate: '[sub-genre] folk, [tempo] BPM, [mood] mood, [instruments], [vocal style], [theme]',
    tips: [
      'Specify the sub-genre: traditional, indie, Celtic, folk-rock',
      'Describe the instruments: acoustic guitar, fiddle, banjo, mandolin',
      'Mention the story or theme: nature, love, social justice, travel',
      'Reference the mood: intimate, rousing, melancholic, celebratory',
      'Include "acoustic" and "organic" for authentic folk sound',
      'Describe the vocal style: natural, harmonized, narrative',
    ],
  },
};
