import type { GenreGuide } from './types';

export const FRENCH_GUIDE: GenreGuide = {
  id: 'french',
  name: 'French Chanson & Variété',
  language: 'French',

  sonicPalette: {
    overview: 'Warm, intimate, and literary — French popular music prizes melodic elegance and textural restraint over bombast. The sonic world shifts from acoustic café warmth to sleek electronic sheen depending on era and sub-genre.',
    timbre: [
      'breathy, close-mic\'d vocals',
      'nylon-string acoustic guitar',
      'upright bass',
      'accordion',
      'muted trumpet',
      'clean electric guitar (Yéyé era)',
    ],
    texture: 'Sparse and conversational in classic chanson; lush string arrangements in variété; crisp and punchy in modern rap and électro-pop.',
    tonality: 'Often minor or modal with chromatic colour chords; major-key pop adopts bright, open voicings.',
    signatureSounds: [
      'musette accordion wheeze',
      'walking upright bass',
      'orchestral string swells',
      'vocoded or filtered voice (French Touch)',
      'snap-and-clap groove (Rap FR)',
    ],
  },

  rhythmAndGroove: {
    overview: 'Rhythm serves the lyric in chanson — the groove is subtle and conversational. Rap FR brings aggressive, syncopated rhythms; French Touch delivers hypnotic four-on-the-floor grooves.',
    bpmRange: { min: 60, max: 140, sweet: 88 },
    feel: 'Loose and breathing in chanson; tight and metronomic in électro and rap.',
    swing: 'Light shuffle in jazz-influenced chanson; straight 16ths in electronic and rap sub-genres.',
    syncopation: 'Moderate — vocal phrasing provides rhythmic interest over a steady pulse.',
    grooveArchetype: 'Waltz (3/4 musette), slow ballad (4/4 chanson), boom-bap (Rap FR), four-on-the-floor (French Touch).',
    rhythmicSignatures: [
      'musette waltz 3/4 feel',
      'bossa-influenced 2/4 lilt',
      'straight-eighth boom-bap',
      'filtered house kick pattern',
    ],
  },

  harmonicLanguage: {
    overview: 'Rich in borrowed chords, minor-to-relative-major pivots, and jazz-influenced ii–V motion. Melodies are strongly shaped by harmonic color rather than pure modal simplicity.',
    scales: [
      'natural minor',
      'harmonic minor',
      'major with chromatic passing tones',
      'Dorian',
      'pentatonic (pop and rap)',
    ],
    chordProgressions: [
      'i – VI – III – VII (minor chanson)',
      'ii7 – V7 – Imaj7 (jazz variété)',
      'I – IV – V – IV (Yéyé pop)',
      'i – iv – VII – III (réaliste ballad)',
    ],
    harmonyNotes: 'Extended chords (7ths, 9ths) are common even in mid-tempo pop. Parallel motion and chromatic descents lend a wistful quality.',
    modality: 'Frequently mingles major and minor; unexpected mode mixture signals emotional depth.',
  },

  songStructure: {
    overview: 'Classic chanson favours through-composed or loose verse-chorus arcs that follow the narrative. Modern pop and rap adopt tighter, hook-driven commercial structures.',
    form: 'Verse–Refrain (chanson), Verse–Chorus–Bridge (variété/pop), Hook–Verse–Hook (rap).',
    sections: [
      'Intro (instrumental or spoken)',
      'Couplet (verse)',
      'Refrain / Chorus',
      'Pont (bridge)',
      'Outro / Fade',
    ],
    arrangement: 'Gradual addition of instruments across verses; strings often enter at the second chorus for emotional uplift.',
    introOutro: 'Short acoustic or solo-instrument intro; outros frequently fade on a repeated refrain.',
    barLengths: 'Irregular phrase lengths (5 or 7 bars) common in chanson; 8-bar sections standard in pop.',
    hookPlacement: 'Refrain lands after the first full couplet; modern tracks often open with a hook snippet.',
  },

  vocalDelivery: {
    overview: 'Diction and emotional authenticity are paramount. The French language\'s nasal vowels and liaisons shape phrasing; singers lean into the poetry rather than vocal acrobatics.',
    phrasing: 'Conversational and speech-rhythmed; syllables rarely stretched beyond natural language stress.',
    affect: 'Melancholic intimacy in chanson; defiant swagger in Rap FR; dreamy detachment in French Touch.',
    techniques: [
      'parlé-chanté (speech-song)',
      'soupir (breathy sigh) ornaments',
      'vibrato on held notes',
      'rap flow with hard final consonants',
    ],
    adlibStyle: 'Rare in chanson; counter-melodic humming; rap uses short interjected phrases.',
    harmony: 'Sparse — occasional thirds doubling in variété; lush backing vocals in zouk.',
    grit: 'Minimal grit in classic style; raw edge in réaliste and rap.',
  },

  lyricalConventions: {
    overview: 'French chanson is inseparable from its literature tradition — lyrics are expected to be poetic, precise, and emotionally honest. Wordplay and double-meaning are celebrated.',
    themes: [
      'amour and loss',
      'Paris and everyday city life',
      'social injustice and working-class struggle',
      'nostalgia and memory',
      'identity and immigration',
      'rebellion and youth',
    ],
    perspective: 'First-person confessional is dominant; second-person addresses the beloved.',
    figurativeLanguage: 'Metaphor and allegory drawn from nature, seasons, and Parisian geography; irony is cherished.',
    vocabulary: 'Cultivated but not archaic; argot and verlan appear in rap; classical literary references in chanson.',
    storytellingApproach: 'Narrative arc with a reveal or twist; emotional payoff arrives in the final refrain.',
    cliches: [
      'la pluie sur Paris',
      'les yeux de quelqu\'un',
      'partir sans se retourner',
      'le temps qui passe',
    ],
  },

  productionFingerprint: {
    overview: 'Production ranges from stripped-back acoustic recording to immaculate studio-orchestral to cutting-edge electronic. Each era has a distinct sonic signature but values clarity of vocal.',
    mixAesthetic: 'Vocals always front and centre; instruments support rather than compete. Wide dynamic range in chanson; compressed and loud in rap and électro.',
    era: 'Golden age 1950s–70s (analog warmth); Variété 1980s (lush synths + strings); French Touch 1990s–2000s (filtered house); contemporary (hybrid analog/digital).',
    signalChain: 'Ribbon or large-diaphragm condenser mic; minimal outboard in classic recordings; sidechain compression and heavy filtering in electronic sub-genres.',
    modernTrends: 'Lo-fi cassette warmth revival; bedroom pop production aesthetics; 808 bass in Rap FR; plugin emulations of vintage Neve or API consoles.',
  },

  instrumentation: {
    coreInstruments: [
      'acoustic guitar (nylon or steel-string)',
      'accordion',
      'upright bass or electric bass',
      'piano or Rhodes',
      'orchestral strings (chamber or full)',
      'drum kit or programmed beats',
    ],
    signatureSounds: [
      'musette accordion',
      'bowed saw / ondes Martenot (vintage chanson)',
      'filtered Moog bass (French Touch)',
      'Roland TR-808 (Rap FR)',
    ],
    layering: 'Solo guitar plus voice as foundation; strings and brass added for emotional peaks; synth pads fill harmonic space in modern production.',
    avoidInstruments: [
      'heavy distorted electric guitar (unless rock fusion)',
      'steel pedal guitar',
      'bluegrass banjo',
    ],
  },

  culturalContext: {
    overview: 'French popular song is a cultural institution, protected and promoted by the state (quotas on radio, Prix de la SACEM). It carries the weight of national identity and literary prestige.',
    origin: 'Paris cabarets and music halls of the late 19th century; popularised through radio and cinéma in the 1930s–50s.',
    identity: 'Tied to French language pride; lyrics in English are rare and often controversial in mainstream chanson.',
    community: 'Cross-generational — classic chanson bridges grandparents and grandchildren; Rap FR speaks primarily to banlieue youth and second-generation immigrants.',
    socialFunction: 'Chanson as collective memory; rap as social critique and testimony.',
    authenticityMarkers: [
      'singing in French with correct prosody',
      'literary or poetic lyric quality',
      'acknowledgement of chanson lineage',
      'regional or immigrant cultural references',
    ],
  },

  historicalLineage: {
    overview: 'From 19th-century cabaret and café-concert through the golden age of Brel, Brassens, and Piaf, to Yéyé pop, prog, world-inflected variété, and contemporary rap and électro.',
    roots: [
      'Paris café-concert (1880s–1910s)',
      'musette dance halls',
      'American jazz and swing influence (1930s)',
      'post-war existentialist Left Bank scene',
    ],
    evolution: 'Each decade layered new sounds onto the chanson core: orchestral strings in the 1950s, electric pop in the 1960s, singer-songwriter folk in the 1970s, synth-pop in the 1980s, house in the 1990s, and global fusion today.',
    keyEras: [
      '1930s–40s: Réaliste and wartime chanson',
      '1950s–60s: Golden Age (Brel, Brassens, Piaf, Aznavour)',
      '1960s: Yéyé (Gainsbourg, Hardy, Vartan)',
      '1990s: French Touch (Daft Punk, Air, Cassius)',
      '2000s–present: Rap FR mainstream (Booba, PNL, Aya Nakamura)',
    ],
    influencedBy: [
      'American jazz and blues',
      'Bel canto opera',
      'Iberian and Latin music',
      'Algerian raï',
      'Antillean zouk and biguine',
    ],
    influenced: [
      'Belgian chanson (Brel)',
      'Québécois chanson',
      'Lusophone fado and MPB',
      'global electro-house',
    ],
  },

  subGenres: [
    {
      name: 'Classic Chanson',
      description: 'The literary heart of French song — poetic lyrics over acoustic guitar or piano with orchestral accompaniment. Brel, Brassens, and Ferré defined the form in the 1950s–70s. Emotional directness and verbal craftsmanship are non-negotiable.',
      distinguishingFeatures: [
        'through-composed narrative lyrics',
        'orchestral string arrangements',
        'minimal percussion',
        'parlé-chanté vocal style',
      ],
      bpmRange: { min: 60, max: 100 },
      keyArtists: ['Jacques Brel', 'Georges Brassens', 'Léo Ferré', 'Charles Aznavour'],
      productionNotes: 'Mono or early stereo recording aesthetic; room ambience; no click track feel.',
      lyricNotes: 'Elevated vocabulary, rhyming couplets, narrative arc with dramatic finale.',
      sunoPromptKeywords: ['French chanson', 'acoustic guitar', 'orchestral strings', 'poetic', 'melancholic', 'intimate'],
    },
    {
      name: 'Nouvelle Chanson',
      description: 'Contemporary singer-songwriters who update the chanson tradition with modern arrangements and personal lyric voices. Artists like Benjamin Biolay, Vincent Delerm, and Camille blend indie sensibility with literary depth.',
      distinguishingFeatures: [
        'understated indie production',
        'confessional personal lyrics',
        'acoustic and electronic hybrid',
        'wry irony and urban imagery',
      ],
      bpmRange: { min: 70, max: 110 },
      keyArtists: ['Benjamin Biolay', 'Vincent Delerm', 'Camille', 'Aldebert'],
      productionNotes: 'Clean but warm; layered acoustic textures; subtle electronic elements.',
      lyricNotes: 'Personal and literary; everyday Parisian life rendered poetic.',
      sunoPromptKeywords: ['nouvelle chanson', 'indie folk', 'warm acoustic', 'literary French', 'bittersweet'],
    },
    {
      name: 'French Pop',
      description: 'Commercial variété française from the 1980s onward — polished, melodic, radio-friendly. Mylene Farmer, Zazie, and Alizée represent glossy, production-forward pop with French language charm.',
      distinguishingFeatures: [
        'bright, compressed production',
        'strong melodic chorus hooks',
        'synthesizer pads and programmed drums',
        'danceable mid-tempo grooves',
      ],
      bpmRange: { min: 90, max: 130 },
      keyArtists: ['Mylene Farmer', 'Zazie', 'Alizée', 'Christophe Maé'],
      productionNotes: 'Major-label polish; layered synths; pitch-corrected but expressive vocals.',
      lyricNotes: 'Accessible vocabulary; love and empowerment themes; catchy refrains.',
      sunoPromptKeywords: ['French pop', 'variété', 'catchy hook', 'polished production', 'radio-friendly'],
    },
    {
      name: 'French Hip-Hop / Rap FR',
      description: 'Born in the banlieues of Paris in the late 1980s, Rap FR became the dominant youth genre of France by the 2010s. Hard-hitting flows, social commentary, and heavy 808 bass define the sound.',
      distinguishingFeatures: [
        '808 bass and trap hi-hats',
        'rapid-fire syllabic rap flows',
        'verlan and argot slang',
        'hard-edged social commentary',
      ],
      bpmRange: { min: 75, max: 145 },
      keyArtists: ['Booba', 'PNL', 'Nekfeu', 'Jul', 'Aya Nakamura'],
      productionNotes: 'Heavy low-end; sidechain compression; minimalist melancholic melody loops.',
      lyricNotes: 'Street realism; identity and race; verlan vocabulary; internal rhyme density.',
      sunoPromptKeywords: ['Rap FR', 'trap', '808 bass', 'French rap', 'banlieue', 'hard-hitting'],
    },
    {
      name: 'Électro-Pop',
      description: 'Synth-driven French pop that fuses dance-floor energy with chanson melody sensibility. Indochine, Yelle, and Christine and the Queens lead a scene that prizes aesthetic maximalism.',
      distinguishingFeatures: [
        'dominant synthesizers and drum machines',
        'dance-floor four-on-the-floor rhythm',
        'melodic vocals over electronic beds',
        'visual and theatrical aesthetic',
      ],
      bpmRange: { min: 110, max: 135 },
      keyArtists: ['Indochine', 'Yelle', 'Christine and the Queens', 'Paradis'],
      productionNotes: 'Bright, saturated synth tones; sidechained pads; danceable groove.',
      lyricNotes: 'Body, identity, freedom; playful wordplay; emotional vulnerability.',
      sunoPromptKeywords: ['electro-pop', 'synth-pop', 'dance', 'French electronic', 'melodic'],
    },
    {
      name: 'Chanson Réaliste',
      description: 'The gritty, fatalistic street songs of early 20th-century Paris — Édith Piaf\'s domain. Stories of prostitutes, criminals, and working-class tragedy delivered with operatic emotional intensity.',
      distinguishingFeatures: [
        'dramatic minor-key melodies',
        'theatrical vocal delivery',
        'accordion and orchestral strings',
        'tragic narrative arc',
      ],
      bpmRange: { min: 55, max: 90 },
      keyArtists: ['Édith Piaf', 'Fréhel', 'Damia', 'Marie Dubas'],
      productionNotes: 'Vintage mono warmth; minimal production; voice and emotion above all.',
      lyricNotes: 'Third-person tragedy or first-person confessional; argot of 1930s Paris.',
      sunoPromptKeywords: ['chanson réaliste', 'Piaf style', 'accordion', 'tragic', 'vintage French', 'dramatic'],
    },
    {
      name: 'Yéyé',
      description: 'France\'s answer to the British Invasion — bright, joyful, guitar-driven pop of the 1960s sung by photogenic young artists. Serge Gainsbourg wrote hits; Françoise Hardy gave it depth.',
      distinguishingFeatures: [
        'clean electric guitar riffs',
        'simple I-IV-V-IV progressions',
        'light drum kit swing',
        'naive, optimistic lyrics',
      ],
      bpmRange: { min: 100, max: 140 },
      keyArtists: ['Françoise Hardy', 'Sylvie Vartan', 'France Gall', 'Claude François'],
      productionNotes: '1960s studio sound; mono or early stereo; handclaps and tambourine.',
      lyricNotes: 'Teen romance, dancing, summer; simple rhyme schemes; joyful energy.',
      sunoPromptKeywords: ['yéyé', '1960s French pop', 'retro', 'clean guitar', 'upbeat', 'vintage'],
    },
    {
      name: 'French Touch',
      description: 'The late-1990s house and electronic scene centred on Daft Punk, Air, and Cassius. Filtered disco loops, vocoder vocals, and lush cinematic arrangements gave France global electronic credibility.',
      distinguishingFeatures: [
        'heavily filtered and chopped samples',
        'vocoder or talk-box vocals',
        'four-on-the-floor house kick',
        'cinematic sweep and build',
      ],
      bpmRange: { min: 120, max: 130 },
      keyArtists: ['Daft Punk', 'Air', 'Cassius', 'Étienne de Crécy', 'Modjo'],
      productionNotes: 'Warm vinyl saturation; resonant filter sweeps; punchy sidechain.',
      lyricNotes: 'Minimal English or French; vocoded phrases; emotional abstraction.',
      sunoPromptKeywords: ['French Touch', 'filtered house', 'vocoder', 'Daft Punk style', 'disco sample', 'electronic'],
    },
    {
      name: 'Zouk / Antillais',
      description: 'Originating in the French Antilles (Martinique, Guadeloupe), zouk is sensual, groove-heavy Caribbean pop that became hugely popular in metropolitan France. Kassav\' and their descendants define the sound.',
      distinguishingFeatures: [
        'syncopated Caribbean rhythm patterns',
        'lush backing vocal harmonies',
        'romantic French Creole and French lyrics',
        'warm acoustic and electric guitar blend',
      ],
      bpmRange: { min: 55, max: 130 },
      keyArtists: ['Kassav\'', 'Zouk Machine', 'Jacob Desvarieux', 'Goulding'],
      productionNotes: 'Rich production; warm Caribbean percussion; lush reverb on vocals.',
      lyricNotes: 'Love, desire, the islands; French and Creole mix; smooth phrasing.',
      sunoPromptKeywords: ['zouk', 'Antillais', 'Caribbean French', 'sensual', 'groove', 'Martinique'],
    },
    {
      name: 'Raï Franco-Arabe',
      description: 'The French evolution of Algerian raï, blending North African pentatonic melodies with French pop production. Artists like Khaled and Faudel brought this to mainstream French audiences in the 1990s.',
      distinguishingFeatures: [
        'North African pentatonic melodies',
        'darbuka and frame drum percussion',
        'French and Darija Arabic bilingual lyrics',
        'emotional, melismatic vocal runs',
      ],
      bpmRange: { min: 80, max: 120 },
      keyArtists: ['Khaled', 'Faudel', 'Rachid Taha', 'Carte de Séjour'],
      productionNotes: 'Hybrid Western pop and North African acoustic instruments; modern studio sheen.',
      lyricNotes: 'Love, exile, immigration, nostalgia; bilingual or code-switched French/Arabic.',
      sunoPromptKeywords: ['raï', 'Franco-Arabe', 'North African French', 'darbuka', 'melismatic', 'world music'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'French music audiences are broadly literate and opinionated. Chanson fans value verbal craft above all; rap audiences prize authenticity and street credibility; electronic fans celebrate sonic innovation.',
    fanExpectations: [
      'correct and expressive French pronunciation',
      'lyrical quality and depth',
      'stylistic coherence within the chosen sub-genre',
      'emotional truth in performance',
    ],
    gatekeeping: 'Language is the primary gate — singing in French is expected and respected. Chanson purists are sceptical of excessive commercial polish; rap fans demand genuine lived experience.',
    livePerformance: 'Chanson traditionally performed in seated intimacy (salle de concert, cabaret). Rap and électro bring festival energy and crowd participation. Zouk thrives in dance hall settings.',
    fashionAndAesthetic: 'Classic chanson: understated Parisian elegance. Yéyé: retro 1960s mod. Rap FR: streetwear and luxury brand flex. French Touch: sleek futurist minimalism.',
    crossoverPotential: 'French Touch crossed globally via electronic music. Rap FR has influenced Belgian, Swiss, and Québécois rap. Zouk spread throughout the Francophone world. Classic chanson remains beloved in Japan.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Chanson has a rubato, speech-rhythm quality — the vocal sits on top of the beat, not locked inside it. The band follows the singer\'s breath, not the metronome. Rap FR snaps to grid with hard syllabic precision.',
    quantizationDeviation: 'High in chanson where vocal phrasing dictates tempo. Low in French Touch where metronomic precision is the aesthetic. Rap FR is tight to grid but vocal flow creates rhythmic interest against it.',
    aheadBehindBeat: 'Chanson vocals sit behind the beat, luxuriating in each syllable. Rap FR pushes ahead with aggressive momentum. French Touch locks exactly to the kick, creating hypnotic regularity.',
    humanizationMarkers: [
      'vocal phrasing that ignores the bar line in classic chanson',
      'breath-driven rubato in Brel\'s dramatic accelerations',
      'deliberate rhythmic looseness in musette accordion playing',
      'swing feel inherited from jazz in variété arrangements',
      'speech-rhythm irregularity in parlé-chanté delivery',
    ],
    genreSpecificFeel: 'The chanson tradition treats rhythm as servant to text — the words dictate where beats fall, not the reverse. This creates a conversational feel that sounds effortless but is carefully crafted. French Touch inverts this: the machine groove is sacred, and vocals are texture.',
  },

  silenceAndSpace: {
    overview: 'French music uses silence as a literary device — Gainsbourg\'s pauses are as famous as his words. The space between phrases carries meaning, creating tension and innuendo.',
    negativeSpaceRole: 'Silence functions as punctuation — a comma, a period, an ellipsis. In chanson, what is left unsaid in the pause between verses is as important as what is sung.',
    breathingPatterns: 'Breathy delivery in chanson makes the intake of air audible and intimate, as if the singer is confiding directly into the listener\'s ear. The breath is part of the instrument.',
    dynamicContrast: 'Moderate in chanson (intimate throughout) but extreme in réaliste (Piaf moves from whisper to full operatic cry). French Touch uses sidechain pumping as a form of rhythmic breathing.',
    whatIsDeliberatelyAbsent: [
      'percussion in chanson verses to expose the naked voice and guitar',
      'bass during Gainsbourg-style spoken passages for maximal intimacy',
      'reverb in close-mic\'d recordings to create claustrophobic closeness',
      'vocal harmony to preserve the solitary, confessional character',
      'melodic instruments during rap verses to let the flow carry alone',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response in French music is literary rather than communal — the singer poses a question, the arrangement provides the emotional answer. Audience sing-back is less central than in other traditions.',
    vocalInstrumentalDialogue: 'In chanson, the accordion or guitar answers the vocal phrase with a melodic commentary. Brel\'s orchestral arrangements swell in response to his vocal declarations like a Greek chorus.',
    sectionInternal: 'Couplet phrases end with instrumental breaths — a piano fill, an accordion sigh, a string figure. The instrument acknowledges what the voice has just said.',
    audienceParticipation: 'French audiences sing refrains at concerts but the tradition is less call-and-response than collective murmuring of shared cultural memory. Rap FR concerts are more participatory, with crowd chanting hooks.',
    patterns: [
      'singer states a poetic image, orchestra swells in emotional response',
      'spoken verse answered by sung refrain as emotional release',
      'accordion phrase completing the vocal line in musette style',
      'Rap FR hook chanted by crowd between verses',
      'Gainsbourg-style male-female vocal dialogue as seduction narrative',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'The French music world spans metropolitan French, Francophone African French, Québécois French, Antillean Creole, and North African Darija-French mixing — each with distinct phonetics, slang, and musical associations.',
    phoneticMarkers: [
      'Parisian French with precise liaison and nasal vowels as the chanson standard',
      'banlieue French with Arabic-influenced guttural consonants and verlan inversion',
      'Québécois joual with diphthongized vowels and archaic French forms',
      'Antillean French Creole with Caribbean rhythm in speech patterns',
      'Franco-African French with West African tonal inflections and vocabulary',
    ],
    accentInfluence: 'Parisian French shapes the chanson tradition with its clipped precision. Banlieue accent gives Rap FR its rhythmic aggression and cultural authenticity. Antillean French lends zouk its sensual, flowing vocal quality.',
    dialectVocabulary: [
      'verlan: "meuf" (femme), "keuf" (flic), "relou" (lourd), "chanmé" (méchant)',
      'banlieue argot: "wesh" (hey), "kiffer" (to love), "sah" (serious), "bail" (thing)',
      'Québécois: "char" (car), "blonde" (girlfriend), "tabarnac" (exclamation)',
      'Antillean Creole: "zouk" (party), "doudou" (darling), "ka" (drum)',
      'Franco-Arabic: "wallah" (I swear), "haram" (forbidden), "bled" (homeland)',
    ],
    regionWithinCulture: 'Metropolitan Parisian French dominates chanson and variété. The banlieues (93, Marseille, Lyon) drive Rap FR. The French Antilles power zouk. Québec maintains a parallel chanson tradition. Francophone Africa increasingly influences contemporary French pop.',
  },

  performancePractice: {
    overview: 'French performance traditions range from the seated, smoky intimacy of cabaret chanson to the explosive energy of Rap FR stadium shows. The common thread is that performance serves the text.',
    improvisationConventions: 'Minimal in chanson — the song is a fixed literary work. Moderate in jazz-inflected variété. Rap FR freestyles are an important credential but live shows typically follow written verses with improvised crowd interaction.',
    crowdInteraction: 'Chanson audiences listen with reverent attention — interrupting is poor form. Rap FR concerts demand active crowd participation: jumping, chanting hooks, call-and-response. Zouk concerts require dancing.',
    stagePresence: 'Chanson: stationary, intense, eyes closed or fixed on middle distance — the body disappears and only the voice exists. Rap FR: physical dominance of the stage, aggressive posturing, crew presence. French Touch DJs cultivate cool detachment.',
    livVsRecordedDifferences: 'Chanson live shows may strip arrangements to voice and guitar, emphasizing intimacy. Rap FR live shows add energy and crowd noise that transforms the experience. French Touch sets are continuous DJ mixes, not song-by-song performance.',
    whatMakesAGoodShow: 'In chanson: the audience forgets where they are and enters the emotional world of the song. In Rap FR: collective physical energy that makes the venue shake. In French Touch: a seamless sonic journey that makes people dance without thinking.',
  },

  socioeconomicSubtext: {
    overview: 'French music maps onto the country\'s class geography with unusual precision. Chanson is bourgeois-intellectual, Rap FR is banlieue-immigrant, variété is middle-class mainstream, and French Touch is cosmopolitan-creative class.',
    materialConditions: 'Rap FR emerged from the HLM (public housing) towers of the banlieues — the material reality of tower-block living, unemployment, and racial discrimination is the genre\'s foundation. Chanson thrived in Left Bank cafés supported by intellectual patronage.',
    classIdentity: 'Chanson carries literary-intellectual prestige. Variété is unapologetically populaire (working and middle class). Rap FR articulates banlieue identity with pride and defiance. French Touch emerged from Parisian creative-class nightlife.',
    politicalUndercurrent: 'French music is politicized by tradition — from réaliste songs about working-class women to Rap FR addressing police violence and racism. The French state\'s radio quotas for French-language music are themselves political. Chanson engagée is a recognized category.',
    implicitReferences: [
      'the banlieue as both geographic reality and identity marker in Rap FR',
      'the "quartier" (neighborhood) as tribal belonging in rap lyrics',
      'references to the Métro system mapping Paris\'s class geography',
      'immigrant parent narratives connecting to colonial and post-colonial history',
      'luxury brand references as class aspiration and defiance in rap',
    ],
  },

  intertextualityAndSampling: {
    overview: 'French music has an unusually deep intertextual tradition — Piaf, Brel, Brassens, and Gainsbourg are a shared canon that every artist is in dialogue with, whether through reverence or rebellion.',
    canonKnowledge: 'Knowledge of the chanson canon is a baseline expectation for any serious French artist. Referencing Brel\'s theatrical intensity, Brassens\' anarchic wit, Piaf\'s tragic power, or Gainsbourg\'s provocative cool positions an artist within a lineage.',
    samplingTradition: 'Rap FR samples classic chanson liberally — a Gainsbourg melody under a trap beat is a common and respected move. French Touch built itself on sampled and filtered disco loops. The tradition treats sampling as cultural conversation.',
    quotationPractice: 'Lyrical quotation of famous chansons is recognized and appreciated by French audiences. Melodic allusion to Brel or Piaf in new compositions is a form of homage that demonstrates cultural belonging.',
    expectedReferences: [
      'Piaf\'s "Non, je ne regrette rien" as emotional benchmark',
      'Brel\'s dramatic intensity and Flemish-French identity',
      'Gainsbourg\'s provocative wit and scandalous persona',
      'Brassens\' anarchist poetry and acoustic guitar simplicity',
      'Daft Punk\'s electronic revolution as French Touch touchstone',
    ],
    lineageSignifiers: [
      'covering a Brel or Brassens song at Olympia as artistic rite of passage',
      'filtered disco samples connecting to French Touch heritage',
      'accordion sounds invoking musette and Piaf-era Paris',
      'spoken-word passages referencing Gainsbourg\'s parlé-chanté',
      'literary lyrical quality connecting to chanson poétique tradition',
      'Antillean rhythms connecting to the Francophone diaspora',
    ],
  },

  genderAndBodyConventions: {
    overview: 'French music maintains distinct gendered archetypes — the male auteur (Gainsbourg, Brel) as intellectual provocateur and the female chanteuse (Piaf, Hardy) as embodied emotional vessel — that contemporary artists are actively complicating.',
    vocalGenderCodes: 'Male chanson singers favor a conversational, sometimes rough baritone that prioritizes text. Female chanteuses range from Piaf\'s devastating power to Hardy\'s cool whisper. In Rap FR, male vocal aggression dominates, though female MCs like Diam\'s and Aya Nakamura have redefined what female French vocals can be.',
    physicalityInPerformance: 'Male chansonniers historically performed stationary, letting the voice carry everything. Female performers have navigated between Piaf\'s motionless intensity and Yéyé\'s playful physicality. Rap FR brings athletic stage movement regardless of gender.',
    genderNarratives: 'Traditional chanson casts the male as philosophical observer and the female as subject of desire or tragedy. Gainsbourg\'s collaborations with female singers (Birkin, Bardot) created controversial male-gaze dynamics. Contemporary artists like Christine and the Queens and Aya Nakamura assert female and non-binary authorship.',
    subversionExamples: [
      'Christine and the Queens dissolving gender boundaries in French pop',
      'Aya Nakamura redefining French pop success from Franco-Malian perspective',
      'Stromae (Belgian-Francophone) exploring masculine vulnerability',
      'Hoshi confronting homophobia through chanson tradition',
      'Pomme bringing queer intimacy to nouvelle chanson',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'French music often feels slower than its BPM suggests because speech-rhythm vocal phrasing and sparse arrangements create a sense of unhurried intimacy, even at moderate tempos.',
    psychologicalTempo: 'Chanson at 90 BPM feels meditative because the vocal sits behind the beat and the arrangement breathes. French Touch at 120 BPM feels hypnotic rather than driving because the filtered repetition induces trance. Rap FR at 90 BPM can feel aggressive due to syllabic density.',
    weightAndMomentum: 'Chanson has emotional weight that slows perceived tempo — each word carries significance. French Touch has mechanical momentum that makes 120 BPM feel effortless. Réaliste carries tragic gravity that makes even uptempo songs feel heavy.',
    urgencyScale: 'Low urgency in classic chanson (contemplative), moderate in variété (emotionally engaged), high in Rap FR (aggressive or confessional), hypnotic in French Touch (trance-like momentum).',
    comparisonToSameBPM: 'A chanson at 100 BPM feels more spacious than a British pop song at the same tempo because the vocal phrasing is speech-driven rather than rhythmically locked. French Touch at 125 BPM feels cooler and more detached than American house at the same tempo because the filtered textures create emotional distance.',
  },

  mistakeConventions: {
    overview: 'French music prizes authenticity of expression over technical perfection. A voice that cracks with emotion in chanson is moving; a rapper who stumbles but recovers with wit is admired. Overproduction is the real mistake.',
    toleratedImperfections: [
      'vocal roughness and cigarette-damaged timbre as markers of lived experience',
      'slight pitch variation in chanson when the emotional delivery compensates',
      'rhythmic looseness in acoustic performances that preserves conversational feel',
      'imperfect French pronunciation by immigrant-origin artists as authentic identity',
      'audible room sound and ambient noise in intimate recordings',
    ],
    celebratedFlaws: [
      'Gainsbourg\'s deliberately lazy, half-spoken vocal delivery as cool affect',
      'Brassens\' limited vocal range elevated by perfect diction and wit',
      'Piaf\'s raw, uncontrolled emotional outbursts as the definition of chanson réaliste',
      'Jacques Dutronc\'s ironic, almost disinterested vocal style as anti-establishment cool',
    ],
    overproductionRisks: [
      'Auto-Tune that strips the conversational grain from a chanson voice',
      'excessive reverb that distances the intimate, confessional quality',
      'drum machine perfection that kills the breathing, human feel of musette',
      'over-compressed dynamics that flatten the dramatic whisper-to-cry arc',
      'polished backing vocals that undermine the solitary chansonnier aesthetic',
    ],
    authenticRoughness: 'The French aesthetic values the sound of a voice that has lived — smoked, loved, suffered, and thought. Technical perfection is for opera; chanson demands the grain of authentic human experience in every syllable.',
  },

  referenceTracks: [
    {
      title: 'Jefe',
      artist: 'Ninho',
      year: 2023,
      whyExemplary: 'France\'s most-streamed rapper delivering melodic trap with lyrical density. Ninho\'s writing balances street credibility with pop-level hooks.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Trap production with melodic French rap delivery. Ninho\'s flow switches between rapid-fire and melodic across sections.',
      craftHighlight: 'French-language melodic trap — the nasal vowels and liaison patterns of French create a unique rhythmic texture over trap beats that English-language trap can\'t replicate.',
    },
    {
      title: 'Pas trop tard',
      artist: 'Pomme',
      year: 2023,
      whyExemplary: 'Nouvelle chanson from a Victoires de la Musique winner — Pomme\'s writing continues the French tradition of intimate, literary pop with feminist consciousness.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-outro. Acoustic arrangement: guitar, strings, piano. Pomme\'s whispered vocal delivery creates confessional intimacy.',
      craftHighlight: 'Chanson intimacy — the French tradition of treating a pop song like a private conversation. Pomme\'s vocal placement feels like she\'s speaking to one person.',
    },
    {
      title: 'Makeba',
      artist: 'Jain',
      year: 2022,
      whyExemplary: 'Afro-French pop that honors Miriam Makeba while creating something new. Jain\'s production fuses French pop, African rhythm, and electronic elements.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Afropop-influenced production with electronic French pop. Call-and-response chorus. Danceable and melodic.',
      craftHighlight: 'Tribute as creation — naming and honoring Makeba gives the song historical depth while the Afro-French production creates a new Pan-African pop language.',
    },
    {
      title: 'L\'Enfer',
      artist: 'Stromae',
      year: 2022,
      whyExemplary: 'Electronic chanson masterpiece about depression and suicidal ideation — Stromae made mental health discourse in French pop with the same courage he brought to AIDS ("Papaoutai").',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Electronic production that builds from sparse to overwhelming, mirroring the mental state. Single-take live debut on French TV was a cultural moment.',
      craftHighlight: 'Production as psychology — the electronic sounds compress and intensify as the song progresses, sonically recreating the experience of spiraling anxiety. You feel what Stromae describes.',
    },
    {
      title: 'La Faille',
      artist: 'Stromae',
      year: 2022,
      whyExemplary: 'Electronic chanson that uses "la faille" (the fault/crack) as metaphor for personal and structural failures. Stromae\'s wordplay makes French pop intellectually rigorous.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Synth-driven with African rhythm influence. Stromae\'s vocal delivery shifts between singing and rhythmic speaking.',
      craftHighlight: 'Double-meaning mastery — "faille" means both geological fault and personal flaw. Every line works on both registers simultaneously. French\'s homophone richness exploited masterfully.',
    },
    {
      title: 'Bande organisée',
      artist: 'Jul ft. SCH, Naps, Kofs, Elams, Solda, Houari',
      year: 2021,
      whyExemplary: 'Marseille rap posse cut that became France\'s most-viewed YouTube premiere. Seven MCs from the same city proving regional identity is creative fuel.',
      structuralNotes: 'Seven verses with shared chorus. Each MC gets 16 bars over the same beat. The structure is a showcase — a cypherin song form. No bridges or breaks.',
      craftHighlight: 'Regional solidarity as form — the Marseille accent, slang, and references create a unified identity across seven different artists. The city IS the artistic concept.',
    },
    {
      title: 'Libre',
      artist: 'Aya Nakamura',
      year: 2023,
      whyExemplary: 'Franco-Afropop from the most-streamed French-speaking artist globally. Nakamura\'s writing blends French, Bambara, and African-French slang into a new pop language.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Afropop-influenced production with French pop melody. Nakamura\'s vocal delivery blends singing and rhythmic speech.',
      craftHighlight: 'Multilingual pop creation — Nakamura doesn\'t code-switch between languages, she fuses them into a single linguistic flow that native speakers of any one language only partially understand.',
    },
    {
      title: 'Malavida',
      artist: 'Zaho de Sagazan',
      year: 2023,
      whyExemplary: 'Neo-chanson breakthrough — Victoires de la Musique winner who brought the literary chanson tradition into Gen-Z consciousness with electronic production and raw vocals.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-outro. Electronic production with acoustic guitar moments. Zaho\'s vocal delivery ranges from spoken word to full belt.',
      craftHighlight: 'Chanson tradition renewed — literary, philosophical lyrics delivered over electronic beats. The intellectual depth of Brel/Brassens meets the sonic palette of 2023.',
    },
    {
      title: 'La Symphonie des éclairs',
      artist: 'Zaho de Sagazan',
      year: 2023,
      whyExemplary: 'Album title track that positions lightning as metaphor for creative inspiration — French pop\'s tradition of treating art-making as a worthy subject.',
      structuralNotes: 'Through-composed with recurring chorus motif. Dynamic shifts between whispered verse and explosive chorus. Orchestral and electronic elements merge.',
      craftHighlight: 'Meta-art — a song about the creative process that IS the creative process happening in real time. French chanson has always been comfortable being self-referential.',
    },
    {
      title: 'Évidemment',
      artist: 'Angèle',
      year: 2022,
      whyExemplary: 'Electro-pop ballad from Belgium\'s biggest French-language export. "Obviously" as a title captures the French aesthetic of philosophical simplicity.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Synth-pop production with emotional vocal. Builds from intimate to anthemic.',
      craftHighlight: 'The single word "évidemment" carries enormous weight — it implies everything that doesn\'t need to be said. French pop\'s love of implication over declaration.',
    },
    {
      title: 'Bruxelles je t\'aime',
      artist: 'Angèle',
      year: 2021,
      whyExemplary: 'Love letter to Brussels in the French chanson tradition of city-songs (Paris, etc.). Angèle claims Brussels as worthy of the same romantic treatment.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Synth-pop with chanson melody. Nostalgic production evoking French pop of the 80s.',
      craftHighlight: 'City-as-lover — the French tradition of personifying cities reaches beyond Paris. Angèle\'s Brussels love letter asserts Belgian French-language pop\'s own identity.',
    },
    {
      title: 'Grand Soleil',
      artist: 'Vianney',
      year: 2024,
      whyExemplary: 'Chanson-pop that captures summer joy with melodic craft. Vianney\'s singer-songwriter approach brings acoustic intimacy to mainstream French pop.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Acoustic guitar-driven with light production. Vianney\'s warm vocal delivery and French chanson phrasing.',
      craftHighlight: 'Simplicity as French pop virtue — "grand soleil" (bright sunshine) needs nothing more than a beautiful melody and an honest voice to communicate perfectly.',
    },
    {
      title: 'Sunset',
      artist: 'SCH',
      year: 2022,
      whyExemplary: 'Cinematic Marseille rap that treats the city\'s sunsets as both beautiful and ominous — visual storytelling meets street narrative in French rap\'s most literary voice.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-outro. Dark, atmospheric production with orchestral elements. SCH\'s deep voice carries weight and menace.',
      craftHighlight: 'Visual writing — SCH describes scenes cinematically, using light, color, and movement. Each verse is a tracking shot through Marseille\'s streets at golden hour.',
    },
    {
      title: 'Otto',
      artist: 'SCH',
      year: 2023,
      whyExemplary: 'Art rap that uses alter ego "Otto" as narrative device. SCH\'s most conceptually ambitious work — a character study told through French rap\'s street vocabulary.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Cinematic production with strings and dark synths. Extended verses with dense lyrical content.',
      craftHighlight: 'Character creation in rap — "Otto" is a fictional persona that allows SCH to explore themes he couldn\'t in first person. French literature\'s narrative tradition meets rap.',
    },
    {
      title: 'Clic clic pan pan',
      artist: 'Gazo & Tiakola',
      year: 2022,
      whyExemplary: 'Drill meets Franco-African melodic pop — onomatopoeia title captures the genre fusion\'s energy. Two voices from different musical worlds creating a new French sound.',
      structuralNotes: 'Verse (Gazo drill)-chorus (Tiakola melodic)-verse-chorus-outro. The genre shifts between sections — drill aggression and Malian-influenced melody alternate.',
      craftHighlight: 'Onomatopoeia as genre statement — "clic clic pan pan" is the sound of the street rendered as pop hook. The violence is abstracted into rhythm.',
    },
    {
      title: 'Mélo',
      artist: 'Tiakola',
      year: 2023,
      whyExemplary: 'Franco-Malian melodic rap that bridges African vocal tradition with French rap. Tiakola\'s singing voice carries Mandinka melodic DNA into Parisian street music.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Afropop-rap hybrid production. Tiakola\'s vocal delivery blends rap, singing, and West African melodic ornaments.',
      craftHighlight: 'Diasporic melody — Tiakola\'s Malian heritage manifests in melodic ornaments and vocal runs that are foreign to French pop tradition but feel completely natural.',
    },
    {
      title: 'Fade',
      artist: 'Lewis OfMan',
      year: 2021,
      whyExemplary: 'Bedroom electro-pop that captures French indie\'s lo-fi charm. Lewis OfMan\'s production is deliberately small and intimate — anti-maximalism.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Minimal electronic production: synths, drum machine, reverbed vocals. Short and dreamy. Under 3 minutes.',
      craftHighlight: 'Lo-fi as French aesthetic — the deliberately imperfect, bedroom-quality production signals authenticity in a tradition that values sincerity over polish.',
    },
    {
      title: 'Comme d\'habitude',
      artist: 'Pierre de Maere',
      year: 2023,
      whyExemplary: 'New wave pop revival from a Belgian artist. The title echoes the Brel/Sinatra standard — claiming the French pop tradition\'s biggest phrase with Gen-Z confidence.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. 80s new wave production: synths, drum machines, processed vocals. Retro-futurist aesthetic.',
      craftHighlight: 'Title as lineage claim — sharing a title with one of the most famous French songs ever written is either audacious or essential. De Maere makes it feel natural.',
    },
    {
      title: 'Pas me quitter',
      artist: 'Lous and the Yakuza',
      year: 2021,
      whyExemplary: 'Franco-African electronic pop that references Brel\'s "Ne me quitte pas" while creating something entirely new. Congolese-Belgian identity expressed through French pop vocabulary.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Electronic production with African percussion elements. Lous\'s vocal shifts between French singing and Congolese-influenced phrasing.',
      craftHighlight: 'Rewriting canon — referencing Brel\'s most famous song while changing the grammar ("pas" instead of "ne...pas") subverts the master. The grammatical "mistake" is the point.',
    },
    {
      title: 'Juste pour me souvenir',
      artist: 'Juliette Armanet',
      year: 2022,
      whyExemplary: 'Nouvelle chanson-pop that channels the French tradition of love songs as philosophical investigations. Armanet\'s writing treats memory as an act of will.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-outro. Piano-driven pop with orchestral swells. Armanet\'s vocal delivery is theatrical and intimate simultaneously.',
      craftHighlight: 'Memory as action — "just to remember" positions remembering as a deliberate choice, not passive experience. French existentialist philosophy embedded in a pop love song.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: [
      'French chanson',
      'variété française',
      'accordion',
      'poetic French lyrics',
      'intimate vocal',
      'orchestral strings',
      'Parisian',
    ],
    avoidKeywords: [
      'country twang',
      'bluegrass',
      'heavy metal distortion',
      'English-language pop',
      'reggaeton',
    ],
    promptTemplate: '[sub-genre], [tempo feel], [key instruments], [mood/theme], French lyrics, [era reference if relevant]',
    tips: [
      'Specify the sub-genre clearly — "French chanson" and "Rap FR" need very different prompts.',
      'Name an era or key artist as a stylistic anchor (e.g., "in the style of Brel" or "French Touch 1998").',
      'Mention accordion for classic/réaliste chanson, filtered house sounds for French Touch, darbuka for raï.',
      'Request "poetic French lyrics" to encourage literary quality over generic pop phrasing.',
    ],
  },
};
