import type { GenreGuide } from './types';

export const GOSPEL_GUIDE: GenreGuide = {
  id: 'gospel',
  name: 'Gospel',
  language: 'English',

  sonicPalette: {
    overview: 'Powerful, uplifting, and spirit-driven. Gospel music is the sound of devotion — choir voices soaring over Hammond organ, piano, and a tight rhythm section. The sound can be intimate and prayerful or explosive and celebratory.',
    timbre: [
      'Powerful choir voices in unison and harmony',
      'Hammond B3 organ with Leslie speaker',
      'Gospel piano (acoustic grand with percussive attack)',
      'Electric bass with warm, round tone',
      'Drums with gospel pocket (behind the beat)',
      'Electric guitar (clean to slightly overdriven)',
      'Tambourine and handclaps',
      'Synthesizer pads (contemporary gospel)',
    ],
    texture: 'Full and powerful — the choir creates a wall of vocal sound. Organ and piano provide harmonic bed. Rhythm section locks in the groove. Dynamics range from whispered prayer to explosive praise.',
    tonality: 'Major keys for praise and celebration. Minor keys for sorrow and supplication. Flat keys (Eb, Ab, Bb, Db) are gospel standards. Rich, extended harmonies.',
    signatureSounds: [
      'Hammond organ swells and runs',
      'Gospel piano runs (scalar flourishes)',
      'Choir responses to lead vocalist',
      'Tambourine on off-beats',
      'Congregational handclaps',
      'Vocal melisma and runs',
      'Key changes (modulation up) for climactic moments',
    ],
  },

  rhythmAndGroove: {
    overview: 'Behind-the-beat groove that creates a deep, church-rocking feel. Gospel rhythm is laid-back but powerful — the rhythm section plays in the pocket while leaving room for the Spirit to move.',
    bpmRange: { min: 60, max: 140, sweet: 100 },
    feel: 'Deep and soulful. The groove sits behind the beat, creating a weighty, spiritual feel. Uptempo praise songs have a driving energy. Slow worship songs are meditative and spacious.',
    swing: 'Moderate to heavy — gospel inherited swing from jazz and R&B. Hi-hats and ghost notes create a swinging, organic feel. The groove should make you sway and clap.',
    syncopation: 'Moderate — bass and piano create syncopated patterns. The choir and lead vocalist add rhythmic complexity. Handclaps provide the backbeat anchor.',
    grooveArchetype: 'Church groove (deep pocket), praise shout (driving), or worship ballad (spacious)',
    rhythmicSignatures: [
      'Gospel pocket (deep, behind-the-beat groove)',
      'Handclaps on 2 and 4',
      'Tambourine shaking and accents',
      'Walking bass patterns',
      'Piano rhythmic comping',
      'Organ pedal sustain',
      'Driving 16th-note hi-hat (contemporary)',
    ],
  },

  harmonicLanguage: {
    overview: 'Gospel harmony is the foundation of American popular music\'s harmonic language. Rich, emotional chord progressions with extended voicings, chromatic movement, and the distinctive gospel "turns" and "shouts."',
    scales: ['Major', 'Pentatonic Major', 'Blues Scale', 'Mixolydian', 'Dorian'],
    chordProgressions: [
      'I – IV – I – V (basic gospel)',
      'I – I7 – IV – iv – I (gospel turn — the signature move)',
      'I – iii – IV – iv – I (ascending with minor IV)',
      'I – vi – ii – V (turnaround)',
      'I – IV – V – IV – I (praise pattern)',
      'bVI – bVII – I (gospel shout — ascending resolution)',
      'IV – V – iii – vi (worship vamp)',
    ],
    harmonyNotes: 'The IV to iv movement (major IV to minor iv) is the most important gospel harmony. Extended chords (7ths, 9ths, 11ths) on every degree. Chromatic passing chords. Key changes (modulation up a half-step or whole step) for emotional escalation.',
    modality: 'Primarily major — gospel is the music of hope and joy. Minor moments create contrast (sorrow before redemption). The movement from minor to major mirrors the salvation narrative.',
  },

  songStructure: {
    overview: 'Spirit-led structure — gospel songs build toward a spiritual climax. The structure allows for extended worship, spontaneous praise, and the lead singer to "take the song to church."',
    form: 'Intro – Verse – Chorus – Verse – Chorus – Vamp/Praise Break – Tag',
    sections: ['Intro (musical)', 'Verse 1', 'Chorus', 'Verse 2', 'Chorus', 'Bridge/Vamp', 'Praise Break', 'Chorus (modulated up)', 'Tag/Outro'],
    arrangement: 'Builds progressively toward the praise break — the emotional and spiritual climax. Instruments and voices are added. Key changes modulate upward. The final section is the most powerful.',
    introOutro: 'Intros: organ or piano setting the mood, or choir humming. Outros: extended vamp with improvised praise, repeated chorus tag, or gradual wind-down. The outro can be the longest section.',
    barLengths: 'Verses: 8-16 bars. Chorus: 8-16 bars. Vamp/praise break: open-ended (as long as the Spirit moves). Total: 4-8+ minutes.',
    hookPlacement: 'Chorus is the hook — simple, repetitive, singable by the congregation. Praise break phrases become hooks through repetition. The most memorable line is often a simple declaration of faith.',
  },

  vocalDelivery: {
    overview: 'The pinnacle of vocal expression — gospel vocals combine technical mastery with spiritual ecstasy. The lead singer channels divine inspiration while the choir provides the communal response. This is where pop, R&B, and soul vocal technique originates.',
    phrasing: 'Emotionally driven — phrasing responds to the spiritual moment. The singer may start restrained and build to ecstatic release. Rubato passages for dramatic effect. Call-and-response with the choir.',
    affect: 'Deeply spiritual — joy, devotion, anguish, ecstasy, triumph. The singer is not performing; they are testifying. The emotion must be genuine and transcendent.',
    techniques: [
      'Powerful belt singing (chest voice)',
      'Melismatic runs (multiple notes per syllable)',
      'Falsetto cries and whoops',
      'Scream-singing at emotional peaks',
      'Call-and-response with choir/congregation',
      'Speaking in between singing (testimony)',
      'Vocal growl and grit from intensity',
      'Dynamic control (whisper to scream)',
      'Key change modulation for climax',
    ],
    adlibStyle: 'Essential — "Thank you Jesus!", "Hallelujah!", "Yes Lord!", "Glory!", "Have mercy!", "Come on!", "Somebody praise Him!" Ad-libs intensify through the song toward the praise break.',
    harmony: 'Rich choir harmonies — 4-part SATB standard. Unison singing for power. Divisi (splitting into more parts) for climactic moments. Call-and-response between lead and choir. Background humming and sustained tones.',
    grit: 'Natural and intense — grit comes from emotional/spiritual intensity. The voice breaking with emotion is celebrated, not avoided. Raw vocal power over polished perfection.',
  },

  lyricalConventions: {
    overview: 'Gospel lyrics express faith, praise, testimony, and spiritual struggle. The language draws from scripture, hymnody, and personal spiritual experience. Simple words carry profound spiritual weight.',
    themes: [
      'Praise and worship',
      'Faith and trust in God',
      'Salvation and redemption',
      'Overcoming trials and tribulation',
      'Grace and mercy',
      'Testimony (personal faith journey)',
      'Hope and encouragement',
      'Love of God',
      'Spiritual warfare',
    ],
    perspective: 'First person testimony ("I" and my relationship with God). Direct address to God ("You are worthy"). Communal "we" for congregational singing.',
    figurativeLanguage: 'Biblical imagery — blood, fire, water, light, darkness, mountains, valleys. Salvation metaphors. Journey and deliverance imagery. Simple but powerful.',
    vocabulary: 'Biblical, devotional, simple but profound. "Jesus," "Lord," "Savior," "praise," "glory," "mercy," "grace." Accessible to all levels of education.',
    storytellingApproach: 'Testimony — personal stories of faith, struggle, and deliverance. Declarative praise statements. Scripture paraphrase. The story always leads to triumph through faith.',
    cliches: [
      'God is good (all the time)',
      'Won\'t He do it',
      'I need You/I love You Lord',
      'He brought me through',
      'I\'m blessed and highly favored',
      'I surrender all',
    ],
  },

  productionFingerprint: {
    overview: 'Live, powerful, and communal. Gospel production should capture the energy of a church service — the interaction between musicians, choir, and congregation. Contemporary gospel adds modern production while maintaining spiritual authenticity.',
    mixAesthetic: 'Vocals dominate — lead and choir must be powerful and clear. Organ and piano fill the harmonic space. Rhythm section provides foundation. Room sound adds live church feel. Dynamic range is wide.',
    era: 'Current era: contemporary gospel blends traditional church sound with pop/R&B production. Urban contemporary gospel uses hip-hop and R&B elements. Traditional gospel maintains classic church sound.',
    signalChain: 'Lead vocals: large-diaphragm condenser or handheld dynamic. Choir: overhead condensers for blend. Organ: direct or amped Leslie mic. Piano: close-miked grand. Live recording captures church energy.',
    modernTrends: 'Worship music crossover (Hillsong, Elevation). Urban contemporary gospel with R&B/hip-hop production. Live worship albums recorded in church. Gospel trap and hip-hop fusion.',
  },

  instrumentation: {
    coreInstruments: [
      'Vocals (lead, choir, congregation)',
      'Hammond B3 organ',
      'Piano (acoustic grand)',
      'Electric bass',
      'Drums',
      'Electric guitar',
      'Tambourine',
      'Synthesizer (contemporary)',
    ],
    signatureSounds: [
      'Hammond organ with Leslie speaker',
      'Gospel piano runs and fills',
      'Congregational handclaps',
      'Tambourine shaking',
      'Choir unison and harmony',
      'Bass guitar gospel runs',
      'Guitar fills (clean tone)',
    ],
    layering: 'Full but clear — organ and piano share harmonic duties. Bass and drums lock the groove. Guitar adds color. Choir voices layer in harmony. Everything builds toward the climax.',
    avoidInstruments: [
      'Heavy distortion',
      'Electronic drums (traditional)',
      'Harsh synthesizers',
      'Auto-Tune (breaks authenticity)',
      'Non-acoustic sounds (traditional)',
    ],
  },

  culturalContext: {
    overview: 'Gospel is the musical foundation of Black American church culture — the sound of worship, testimony, and community. It has shaped every form of American popular music through its vocal techniques, harmonic language, and emotional intensity.',
    origin: 'African American church tradition, emerging from spirituals, hymns, and the Black church experience in the early 20th century. Thomas A. Dorsey is considered the father of modern gospel.',
    identity: 'Sacred music of the Black church — deeply connected to faith, community, and cultural identity. Gospel is both worship and artistic expression.',
    community: 'The church is the community — choir rehearsals, Sunday services, revivals, and church conventions. Gospel music ministries. National conventions (COGIC, National Baptist). Award shows (Stellar, Dove).',
    socialFunction: 'Worship and spiritual edification. Community bonding. Cultural preservation. Emotional healing and catharsis. Gospel concerts are communal spiritual experiences.',
    authenticityMarkers: [
      'Genuine faith and spiritual conviction',
      'Vocal power and anointing',
      'Church roots and community connection',
      'Musical skill (especially keyboard and vocal)',
      'Ability to "take a song to church"',
      'Congregational response and connection',
    ],
  },

  historicalLineage: {
    overview: 'From slave spirituals to megachurch worship, gospel music represents the continuous thread of Black American sacred musical expression.',
    roots: ['Spirituals', 'Hymns', 'Blues', 'African Musical Traditions'],
    evolution: 'Spirituals (slavery era) → Gospel hymns (early 1900s) → Golden Age gospel (1930s-60s) → Soul-gospel fusion (1960s-70s) → Contemporary gospel (1980s-90s) → Worship/urban contemporary (2000s-present).',
    keyEras: [
      'Pre-1900: Spirituals and jubilee songs',
      '1930-1960: Golden Age (Thomas Dorsey, Mahalia Jackson)',
      '1960-1980: Soul-gospel fusion (Edwin Hawkins, Andrae Crouch)',
      '1980-2000: Contemporary gospel (Kirk Franklin, Fred Hammond)',
      '2000-present: Worship movement, urban gospel, gospel hip-hop',
    ],
    influencedBy: ['Spirituals', 'Hymns', 'Blues', 'Jazz', 'African Music'],
    influenced: ['Soul', 'R&B', 'Rock and Roll', 'Pop', 'Hip-Hop', 'Country'],
  },

  subGenres: [
    {
      name: 'Traditional Gospel',
      description: 'Classic church gospel — choir voices, Hammond organ, and powerful lead singers delivering songs of praise and testimony.',
      distinguishingFeatures: ['Classic church sound', 'Choir-driven', 'Hammond organ and piano', 'Powerful lead vocals', 'Traditional hymns and praise songs'],
      bpmRange: { min: 60, max: 120 },
      keyArtists: ['Mahalia Jackson', 'The Clark Sisters', 'Shirley Caesar', 'Walter Hawkins', 'The Winans'],
      productionNotes: 'Live church feel. Hammond organ. Full choir. Acoustic instruments. Minimal electronic elements. Capture the anointing.',
      lyricNotes: 'Traditional praise, worship, testimony. Scripture-based. Simple, powerful declarations of faith.',
      sunoPromptKeywords: ['traditional gospel', 'church gospel', 'choir', 'Hammond organ', 'praise', 'worship', 'classic gospel'],
    },
    {
      name: 'Contemporary Gospel',
      description: 'Modern gospel blending traditional church roots with pop, R&B, and hip-hop production. Accessible to mainstream audiences while maintaining spiritual message.',
      distinguishingFeatures: ['Modern production values', 'Pop/R&B influence', 'Accessible hooks', 'Contemporary instrumentation', 'Urban appeal'],
      bpmRange: { min: 70, max: 130 },
      keyArtists: ['Kirk Franklin', 'Fred Hammond', 'Tasha Cobbs Leonard', 'Jonathan McReynolds', 'Maverick City Music'],
      productionNotes: 'Modern R&B/pop production with gospel elements. Synthesizers and programmed drums alongside live instruments. Radio-friendly hooks with church energy.',
      lyricNotes: 'Faith in modern context. Personal testimony. Accessible spiritual messages. Relatable and contemporary.',
      sunoPromptKeywords: ['contemporary gospel', 'modern gospel', 'gospel R&B', 'urban gospel', 'worship pop', 'Kirk Franklin'],
    },
    {
      name: 'Gospel Choir',
      description: 'Mass choir gospel — large ensembles creating walls of vocal harmony. The full power of 50-200 voices singing in unity.',
      distinguishingFeatures: ['Large choir ensembles', 'Massive vocal harmonies', 'Director-led spontaneity', 'Full SATB arrangements', 'Communal power'],
      bpmRange: { min: 70, max: 130 },
      keyArtists: ['Brooklyn Tabernacle Choir', 'Mississippi Mass Choir', 'Hezekiah Walker & LFCC', 'West Angeles COGIC'],
      productionNotes: 'Capture the choir\'s power. Wide stereo spread. Natural room reverb. Balance lead vocal with choir. Multiple overhead mics.',
      lyricNotes: 'Praise anthems, worship declarations. Simple, singable by large groups. Repetitive choruses for mass participation.',
      sunoPromptKeywords: ['gospel choir', 'mass choir', 'choir gospel', 'large ensemble', 'choral gospel', 'congregational'],
    },
    {
      name: 'Southern Gospel',
      description: 'White Southern gospel tradition — quartet harmonies, piano-driven arrangements, and testimonial lyrics with country influence.',
      distinguishingFeatures: ['Quartet vocal harmony', 'Piano-driven arrangements', 'Southern accent and style', 'Country/bluegrass influence', 'Testimony-focused lyrics'],
      bpmRange: { min: 70, max: 130 },
      keyArtists: ['The Gaithers', 'The Oak Ridge Boys', 'The Cathedrals', 'Greater Vision'],
      productionNotes: 'Piano-driven with close vocal harmonies. Country-influenced instrumentation. Clean production. Quartet format.',
      lyricNotes: 'Testimony, heaven, grace, salvation. Southern religious tradition. Sentimental and emotional.',
      sunoPromptKeywords: ['Southern gospel', 'quartet gospel', 'country gospel', 'Gaither', 'piano gospel', 'Southern hymn'],
    },
    {
      name: 'Urban Contemporary Gospel',
      description: 'Gospel infused with urban R&B, hip-hop, and pop production. The sound of modern Black church worship.',
      distinguishingFeatures: ['R&B and hip-hop production', 'Urban contemporary sound', 'Modern worship style', 'Young audience appeal', 'Genre-blending'],
      bpmRange: { min: 70, max: 135 },
      keyArtists: ['Kirk Franklin', 'Mary Mary', 'Tye Tribbett', 'Lecrae (worship tracks)', 'Todd Dulaney'],
      productionNotes: 'Urban R&B production values. Programmed drums, synths, and samples. Live instruments blended with electronic elements. Radio-ready.',
      lyricNotes: 'Urban life and faith. Contemporary language and themes. Accessible spirituality. Youth-oriented.',
      sunoPromptKeywords: ['urban gospel', 'gospel R&B', 'modern church', 'hip-hop gospel', 'urban worship', 'young gospel'],
    },
    {
      name: 'Praise & Worship',
      description: 'Congregational worship music designed for church singing. Simple melodies, repetitive structures, and intimate devotional lyrics.',
      distinguishingFeatures: ['Congregational singing focus', 'Simple, repetitive melodies', 'Intimate, devotional lyrics', 'Build-and-release dynamics', 'Modern worship aesthetic'],
      bpmRange: { min: 60, max: 120 },
      keyArtists: ['Hillsong', 'Elevation Worship', 'Bethel Music', 'Maverick City Music', 'Chris Tomlin'],
      productionNotes: 'Modern production with atmospheric textures. Electric guitars with delay. Ambient pads. Dynamic builds. Congregational-friendly keys and melodies.',
      lyricNotes: 'Direct address to God. Intimate worship. Simple, repetitive phrases. Designed for congregational singing.',
      sunoPromptKeywords: ['praise and worship', 'worship music', 'church worship', 'Hillsong', 'devotional', 'intimate worship'],
    },
    {
      name: 'CCM (Contemporary Christian Music)',
      description: 'Pop and rock music with Christian lyrics. Radio-friendly, accessible, and designed for mainstream Christian audiences.',
      distinguishingFeatures: ['Pop/rock production', 'Christian lyrics', 'Radio-friendly format', 'Mainstream accessibility', 'Various rock and pop sub-genres'],
      bpmRange: { min: 80, max: 140 },
      keyArtists: ['TobyMac', 'Lauren Daigle', 'for KING & COUNTRY', 'Casting Crowns', 'Switchfoot'],
      productionNotes: 'Pop/rock production values. Modern, polished sound. Electric guitars, drums, synths. Radio-ready mix. No different from secular pop/rock production.',
      lyricNotes: 'Faith, hope, encouragement. Christian themes in accessible language. Positive, uplifting messages. Sometimes indistinguishable from secular pop lyrics.',
      sunoPromptKeywords: ['CCM', 'contemporary Christian', 'Christian pop', 'Christian rock', 'faith music', 'inspirational'],
    },
    {
      name: 'Gospel Blues',
      description: 'The intersection of blues feeling and gospel faith. Raw, bluesy musical expression with sacred themes.',
      distinguishingFeatures: ['Blues musical structure with gospel lyrics', 'Raw, emotional delivery', 'Guitar-driven', 'Spiritual struggle themes', 'Blues-gospel fusion'],
      bpmRange: { min: 60, max: 110 },
      keyArtists: ['Blind Willie Johnson', 'Sister Rosetta Tharpe', 'Rev. Gary Davis', 'Mavis Staples'],
      productionNotes: 'Blues instrumentation and feel. Gospel lyrics and spirit. Raw, live recording. Guitar and voice as primary instruments.',
      lyricNotes: 'Spiritual struggle, faith, redemption. Blues emotional honesty with gospel hope. Scripture and personal testimony.',
      sunoPromptKeywords: ['gospel blues', 'spiritual blues', 'sacred blues', 'church blues', 'bluesy gospel', 'raw spiritual'],
    },
    {
      name: 'Holy Hip-Hop',
      description: 'Christian hip-hop — rap and hip-hop production with gospel messages. Reaching youth through urban music culture.',
      distinguishingFeatures: ['Hip-hop production and flow', 'Christian/gospel message', 'Urban culture connection', 'Rap delivery', 'Youth-oriented ministry'],
      bpmRange: { min: 70, max: 150 },
      keyArtists: ['Lecrae', 'KB', 'Andy Mineo', 'Trip Lee', 'NF'],
      productionNotes: 'Full hip-hop production — 808s, trap drums, modern beats. Gospel samples and references. Same quality as secular hip-hop production.',
      lyricNotes: 'Faith, testimony, social issues through Christian lens. Rap lyricism with spiritual depth. Urban life and spirituality.',
      sunoPromptKeywords: ['Christian hip-hop', 'holy hip-hop', 'gospel rap', 'faith rap', 'Christian trap', 'ministry rap'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Gospel audiences are faith communities — the music serves worship and spiritual edification. The audience is deeply engaged, participatory, and evaluates music by its spiritual impact.',
    fanExpectations: [
      'Genuine spiritual conviction',
      'Vocal power and anointing',
      'Musical excellence in service of worship',
      'Community and congregational connection',
      'Uplifting, faith-building content',
      'Live church energy',
    ],
    gatekeeping: 'Moderate — gospel has its own industry (Stellar Awards, Gospel charts). Debates about secular influence. Traditional vs. contemporary worship. The church community is the primary gatekeeper.',
    livePerformance: 'Church services, concerts, revivals, and festivals. The live experience is communal and participatory. Audience sings, claps, dances, and worships. The music is a vehicle for spiritual encounter.',
    fashionAndAesthetic: 'Church attire — ranges from Sunday best to contemporary casual. Choir robes for traditional. Contemporary gospel artists dress like R&B/pop artists. The aesthetic reflects the sub-genre.',
    crossoverPotential: 'Moderate — gospel vocal technique permeates all popular music. Worship music crosses into mainstream pop. Gospel artists occasionally cross over (Kirk Franklin, Chance the Rapper gospel influence).',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Gospel micro-timing is the source code for soul, R&B, and hip-hop feel. The gospel "pocket" sits behind the beat with a deep, weighty groove that makes the body sway. The pianist and organist characteristically rush slightly ahead, pulling the congregation forward, while the drummer sits back — this push-pull tension IS the gospel feel.',
    quantizationDeviation: 'Gospel is played live, never quantized. The musician/congregation relationship creates a fluid time feel that accelerates during praise breaks and slows during meditative worship. The organist\'s left hand often anticipates chord changes by a fraction of a beat, creating forward pull. The bass guitar locks with the kick drum but plays off the piano\'s slightly ahead timing.',
    aheadBehindBeat: 'The pianist and organist play slightly ahead of the beat — this is the gospel signature, creating an excited, Spirit-driven forward pull. The drummer sits behind, anchoring. The lead vocalist floats freely above this tension, sometimes rushing toward ecstatic peaks, sometimes pulling back into contemplative space. The choir\'s massive body naturally drags slightly behind, creating gravitational weight.',
    humanizationMarkers: [
      'Pianist rushing scalar runs ahead of the beat with excitement',
      'Organist\'s left hand anticipating chord changes',
      'Choir\'s collective timing arriving a fraction late (mass inertia)',
      'Drummer\'s hi-hat intensifying (moving from 8ths to 16ths) during praise breaks',
      'Tambourine player locking with congregational clapping (rarely perfectly synced)',
    ],
    genreSpecificFeel: 'The gospel feel is the foundation that all Black American popular music builds upon. When a hip-hop producer samples a gospel choir, they\'re capturing this micro-timing DNA. When an R&B singer sits behind the beat, they\'re channeling church. The push-pull between excited musicians (ahead) and the grounded congregation (behind) creates a groove that is simultaneously urgent and settled — the sound of fervent faith.',
  },

  silenceAndSpace: {
    overview: 'Gospel uses silence for spiritual drama — the moment before the praise break erupts, the pause after a devastating testimony, the held breath before the choir enters. These silences are not empty; they are full of anticipation, the congregation leaning forward into what comes next.',
    negativeSpaceRole: 'Silence in gospel is the moment between prayer and answer. The lead vocalist stops singing, the band drops to a murmur, and the church waits — this is the altar call, the invitation. Space is also practical: the lead singer needs room to testify (speak between singing), and the arrangement must accommodate spontaneous verbal ministry.',
    breathingPatterns: 'Gospel songs breathe in worship cycles: build from quiet devotion to ecstatic praise, then return to quiet. The praise break is an extended exhalation of spiritual energy. After the climax, the arrangement thins back to organ and voice for the wind-down. The congregation\'s collective breath (audible gasps, sighs, amens) is part of the sonic texture.',
    dynamicContrast: 'The most extreme in any genre. Gospel moves from a single whispered voice to a 200-person choir at full volume, from solo piano meditation to full band with organ, drums, and stomping. The praise break contrast — building from almost nothing to maximum spiritual intensity — is gospel\'s defining dynamic gesture. Key changes (modulation up) amplify this further.',
    whatIsDeliberatelyAbsent: [
      'Continuous loud volume (dynamics mirror the spiritual journey)',
      'Complex production effects (authenticity requires rawness)',
      'Melodic busyness during testimony/spoken word passages',
      'Rhythmic activity during prayer moments (space for God)',
      'Harmonic resolution during tension-building sections (anticipation is spiritual)',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response IS gospel. The genre was born from it — the preacher calls, the congregation responds; the lead singer calls, the choir responds; the choir calls, the Holy Spirit responds. This is not a technique; it is the theological structure of Black worship made musical. Every gospel performance is a three-way conversation between performer, congregation, and the divine.',
    vocalInstrumentalDialogue: 'The organ "talks" to the preacher — during spoken word passages, the organist provides melodic commentary (runs, chords, swells) that responds to the emotional content of the sermon. The piano punctuates key words with stabs. The drums accent "amen" moments. The musicians are not accompanying; they are participating in the spiritual conversation.',
    sectionInternal: 'The lead singer states a phrase, the choir repeats, embellishes, or affirms it. This can continue for minutes in a vamp — the lead pushes further emotionally, the choir urges them on ("Sing!" "Yes!" "Take your time!"). The backgrounds are not decoration; they are the congregation\'s representative voice, drawing the lead singer deeper into spiritual expression.',
    audienceParticipation: 'The congregation IS the performance. Handclapping on 2 and 4 is mandatory. Verbal responses ("Amen!" "Hallelujah!" "Preach!" "Yes Lord!") are expected and necessary. Standing, swaying, lifting hands, dancing, shouting — physical worship is participation. A silent gospel audience means the performance has failed. The energy is circular: performer feeds congregation feeds performer.',
    patterns: [
      'Lead vocalist sings phrase → choir repeats with harmony',
      'Preacher speaks → organist provides musical commentary',
      'Soloist builds intensity → congregation rises to feet',
      'Choir sings hook → congregation joins in singing',
      'Praise break builds → congregational shouting erupts',
      'Testimony spoken → musicians provide emotional underscore',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Gospel regional variation maps directly to Black church denomination and geography. COGIC (Church of God in Christ) gospel from Memphis sounds different from Black Baptist gospel in Chicago, which sounds different from AME (African Methodist Episcopal) worship in Philadelphia. Denomination shapes musical style as much as geography.',
    phoneticMarkers: [
      'Southern Black Baptist: elongated vowels, preacher\'s rhythmic cadence, "well" as discourse marker',
      'COGIC/Pentecostal: glossolalia-influenced vocal patterns, percussive syllabic delivery',
      'Northern urban gospel: cleaner diction influenced by R&B crossover, more melodic phrasing',
      'Caribbean-influenced gospel: patois inflections, syncopated speech rhythms',
      'West African-influenced (diaspora): call-patterns with tonal language remnants',
    ],
    accentInfluence: 'Southern gospel accents carry the weight of the original tradition — the preaching cadence of Southern Black Baptist and Pentecostal worship defines how gospel melody is shaped. Northern urban gospel (Chicago, Detroit, NYC) is influenced by R&B polish. Caribbean and African diaspora gospel communities bring distinct rhythmic speech patterns that create different melodic contours.',
    dialectVocabulary: [
      '"Anointed/anointing" (spiritually empowered performance)',
      '"Tarry" (wait in prayer, Pentecostal tradition)',
      '"Praise break" (ecstatic climactic worship moment)',
      '"Take it to church" (reach peak spiritual intensity)',
      '"Ministry in song" (singing as spiritual service, not entertainment)',
    ],
    regionWithinCulture: 'The Black church is the most important cultural institution in Black America, and gospel music is its sonic identity. Regional church traditions create distinct musical dialects: Memphis COGIC gospel is rhythmically intense and drum-heavy. Chicago Baptist gospel is choir-driven and harmonically sophisticated. Atlanta megachurch gospel blends contemporary production with traditional fervor. Each tradition reflects its community\'s worship culture.',
  },

  performancePractice: {
    overview: 'Gospel performance is worship, not entertainment. The distinction is fundamental: the performer is a vessel, not the source. The goal is not to impress the audience but to facilitate a spiritual encounter. The best gospel performances are moments where the performer, musicians, and congregation collectively transcend — when "the Spirit takes over."',
    improvisationConventions: 'Improvisation is not just permitted; it is expected as evidence of spiritual authenticity. A gospel singer who performs a song identically each time is considered uninspired — the Spirit should lead to new expressions each performance. The praise break is entirely improvised: the lead singer, choir, and musicians follow spiritual momentum without a plan. The organist and pianist improvise constantly.',
    crowdInteraction: 'There is no separation between performer and audience in gospel — the congregation is co-creating the worship experience. The lead singer may stop singing to testify (speak about personal faith). The minister of music may direct the congregation to sing specific parts. Individual congregants may stand and shout, and the music accommodates their expression.',
    stagePresence: 'Spiritual authority, not theatrical charisma. The gospel performer must project genuine faith and anointing. Physical expression ranges from restrained (hymn singing) to athletic (COGIC praise dancing, holy ghost running). Church mothers may wave handkerchiefs. The choir director conducts with full-body energy. Sweat and tears are marks of genuine spiritual engagement.',
    livVsRecordedDifferences: 'Live gospel is exponentially more powerful than recorded gospel — the communal spiritual energy cannot be captured in a studio. Live gospel albums (Kirk Franklin\'s "Live," Walter Hawkins\'s "Love Alive") are the genre\'s most important recordings precisely because they capture the church experience. Songs may run 10-15 minutes live versus 5 minutes on record.',
    whatMakesAGoodShow: 'A gospel performance succeeds when the congregation encounters God — technical excellence is secondary to spiritual impact. The musicians must be skilled enough to follow spontaneous direction. The lead singer must be spiritually authentic, not just vocally gifted. The praise break must feel genuine, not manufactured. People should leave transformed, not merely entertained.',
  },

  socioeconomicSubtext: {
    overview: 'Gospel music is the sound of a community that created beauty and meaning from the most oppressive material conditions in American history. The Black church was born because enslaved people were excluded from white worship spaces; gospel music emerged as that community\'s highest artistic expression. The music\'s triumphant spirit exists in direct tension with the economic and social conditions of its creators.',
    materialConditions: 'Gospel emerged from communities with limited material resources — the church building, the piano (often out of tune), the choir robes (sewn by church mothers), and the voices (free and abundant). Gospel\'s emphasis on vocal and spiritual resources over material ones reflects communities where music was created from what was available. Contemporary megachurch gospel reflects changed economic conditions.',
    classIdentity: 'The Black church historically served all class levels: working poor, middle class, and (later) professional class. Gospel music bridges these — the deacon who works in a factory and the doctor who sits in the same pew sing the same songs. Gospel\'s class identity is communal rather than individual. Economic success is framed as "blessing," not personal achievement.',
    politicalUndercurrent: 'The Black church was the organizing center of the Civil Rights Movement, and gospel provided its soundtrack. "We Shall Overcome," "This Little Light of Mine," and "Oh Freedom" are gospel songs repurposed as protest anthems. The political dimension is inseparable from the spiritual: liberation theology teaches that God sides with the oppressed. Contemporary gospel continues to address social justice through spiritual framing.',
    implicitReferences: [
      'Deliverance narratives paralleling the Exodus story and emancipation',
      '"Trouble don\'t last always" encoding survival under systemic oppression',
      'Tithes and offering as community mutual aid economics',
      'Church building fund drives as collective wealth-building',
      '"He brought me through" framing survival of hardship as divine intervention',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Gospel\'s intertextuality is scriptural and communal. Songs quote scripture directly, reference hymns, and build on each other across decades. The tradition of "lining out" hymns (a leader singing a line, the congregation repeating it) is itself an intertextual practice — each congregation adds its own interpretation to shared material.',
    canonKnowledge: 'Gospel musicians must know the standards: "Amazing Grace," "His Eye Is on the Sparrow," "Oh Happy Day," "Total Praise," "Stomp." Scripture knowledge is expected — musical references to Psalms, the Gospels, and Paul\'s letters are understood by the congregation. Thomas Dorsey\'s compositions ("Precious Lord, Take My Hand") are canonical. Andrae Crouch and the Hawkins family are foundational.',
    samplingTradition: 'Gospel sampling in hip-hop and R&B has created recursive loops of influence. Kanye West\'s gospel samples brought church into secular music. Kirk Franklin sampled hip-hop beats for gospel. The sampling flows both directions — gospel is both source material and recipient. Within gospel itself, songs are "covered" and reinterpreted endlessly, each version adding to the tradition.',
    quotationPractice: 'Scripture quotation in gospel is constant — lyrics paraphrase, quote, and reference biblical text. Musically, gospel songs quote hymns, other gospel songs, and common chord progressions that carry spiritual meaning (the IV-iv "gospel turn" is itself a quotation). Vocally, singers quote specific performances by gospel legends — a particular run or shout that references a known recording.',
    expectedReferences: [
      'Thomas Dorsey\'s compositions as modern gospel foundation',
      'Mahalia Jackson\'s vocal authority as the benchmark',
      'The Edwin Hawkins Singers\' "Oh Happy Day" as crossover template',
      'Andrae Crouch\'s songwriting as contemporary gospel\'s ancestor',
      'The Clark Sisters\' vocal technique as female gospel standard',
    ],
    lineageSignifiers: [
      'Vocal runs that reference specific gospel legends\' signature phrases',
      'Hammond organ playing style that quotes specific church traditions',
      'Choir arrangements that reference classic gospel recordings',
      'Testimony narratives that follow established spiritual storytelling patterns',
      'Key changes that reference the "traditional" modulation-up structure',
      'Praise break patterns that follow COGIC or Baptist worship conventions',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Gospel encodes specific gender roles rooted in Black church tradition: the male pastor/preacher figure, the female "mother of the church," the choir director (male or female), and the choir (predominantly female). These roles translate directly into musical performance conventions that shape vocal style, physical expression, and spiritual authority.',
    vocalGenderCodes: 'Male gospel vocals emphasize pastoral authority: deep, commanding chest voice for worship leading, with falsetto reserved for moments of spiritual ecstasy (not vulnerability, as in R&B). Female gospel vocals carry the choir tradition: powerful, church-trained belting that embodies the "church mother" archetype. Female soloists (Shirley Caesar, CeCe Winans) wield vocal authority equal to or exceeding male counterparts.',
    physicalityInPerformance: 'Physical worship expression is gendered by church tradition. Male performers: pacing, pulpit-style gesturing, controlled shout. Female performers: hands raised, swaying, holy dance. COGIC tradition permits more ecstatic physical expression across genders (running, falling, speaking in tongues). The body in gospel is a vessel for the Spirit, not a display for the audience.',
    genderNarratives: 'Gospel lyrics address God, not romantic partners, so gendered narratives are less prominent than in secular music. However, testimony often divides along gendered lines: men testify about overcoming worldly temptation and providing for family; women testify about faith through domestic trials and raising children. Contemporary gospel is expanding these narratives.',
    subversionExamples: [
      'Tonéx/B. Slade coming out as queer while maintaining gospel career',
      'Kirk Franklin incorporating hip-hop masculine energy into worship leadership',
      'The Clark Sisters\' musical innovation challenging male-dominated gospel production',
      'Marvin Sapp\'s emotional vulnerability challenging stoic pastoral masculinity',
      'Tasha Cobbs Leonard\'s worship leadership challenging male pastoral authority norms',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Gospel tempo is Spirit-led and fluid — the same song can be performed at 80 BPM in a meditative setting and 120 BPM during a praise break. Tempo in gospel is responsive, not fixed. The worship leader may speed up or slow down based on congregational energy, making BPM a suggestion rather than a rule.',
    psychologicalTempo: 'Slow worship at 65 BPM feels suspended and intimate — time expands in devotional space. Medium praise at 100 BPM feels grounded and communal — the sweet spot for congregational singing. Fast praise at 130 BPM feels ecstatic and driving — the praise break tempo. The psychological tempo increases as spiritual intensity rises, regardless of actual BPM change.',
    weightAndMomentum: 'Gospel weight comes from collective sound — 200 voices, organ, piano, bass, drums all creating a wall of worship. Momentum builds through the service: slow devotional → medium praise → fast praise break. The key change (modulating up a half-step or whole step) adds psychological momentum without changing tempo. The congregation standing to their feet adds perceived weight.',
    urgencyScale: '1-10 urgency: Devotional hymn at 60 BPM = 2 (meditative), pastoral prayer underscore at 70 BPM = 3, worship ballad at 85 BPM = 4, congregational praise at 100 BPM = 6, uptempo praise at 120 BPM = 8, praise break at 130 BPM = 10 (ecstatic), shout music at 140 BPM = 10+ (transcendent).',
    comparisonToSameBPM: 'Gospel at 100 BPM feels completely different from pop at 100 BPM. The gospel version has gravitational weight from collective vocal mass, behind-the-beat groove depth, and spiritual intensity that makes the music feel larger than its tempo. Pop at 100 BPM is light and driving. Gospel at the same tempo is massive and settled — a congregation planted in praise.',
  },

  mistakeConventions: {
    overview: 'In gospel, "mistakes" during worship are often interpreted as the Spirit moving — a cracked note means the singer was overwhelmed by emotion, a forgotten lyric means they were caught up in worship, an unplanned key change means the Spirit led them higher. The framework of spiritual authenticity transforms technical imperfection into evidence of genuine encounter.',
    toleratedImperfections: [
      'Forgotten lyrics during spontaneous worship (Spirit-led, not rehearsal failure)',
      'Choir members singing slightly different rhythmic interpretations',
      'Organist hitting adjacent notes during fast runs',
      'Congregational singing that\'s enthusiastic but pitchy',
      'Tempo fluctuations as the worship leader follows spiritual momentum',
    ],
    celebratedFlaws: [
      'Vocal cracks during emotional peaks (evidence of genuine spiritual feeling)',
      'Spontaneous key changes that aren\'t "correct" but feel right',
      'Lead singer breaking into speech/testimony mid-song (Spirit taking over)',
      'Extended praise breaks that abandon song structure entirely',
      'Raw, uncontrolled vocal screams/shouts at moments of spiritual ecstasy',
    ],
    overproductionRisks: [
      'Auto-Tuning worship vocals (breaks spiritual authenticity)',
      'Over-rehearsed performances that feel scripted rather than Spirit-led',
      'Studio polish that removes the live church energy',
      'Click tracks that prevent tempo flexibility during worship',
      'Mixing out congregational noise (amens, shouts, clapping) that IS the worship',
    ],
    authenticRoughness: 'Gospel\'s roughness is theological — the belief that God uses imperfect vessels is enacted musically. A technically perfect but spiritually cold performance is worse than a technically imperfect but spiritually genuine one. The congregation doesn\'t evaluate pitch accuracy; they evaluate anointing. When Mahalia Jackson\'s voice cracked, the church didn\'t hear a mistake — they heard a woman overcome by the Spirit. That framework transforms imperfection into the highest form of authenticity.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['gospel', 'worship', 'choir', 'praise', 'spiritual', 'church', 'inspirational'],
    avoidKeywords: ['secular', 'profanity', 'explicit', 'dark', 'satanic', 'nihilistic', 'aggressive'],
    promptTemplate: '[sub-genre] gospel, [tempo] BPM, [mood] mood, [instruments], [vocal style], [worship style]',
    tips: [
      'Specify the sub-genre: traditional, contemporary, worship, Southern, urban',
      'Describe the vocal style: powerful choir, lead vocalist, congregational',
      'Mention key instruments: Hammond organ, piano, tambourine',
      'Reference the worship atmosphere: intimate, celebratory, testimonial',
      'Include "choir" for ensemble sound, "solo" for lead vocalist focus',
      'Describe the energy: building to praise break, meditative worship, joyful celebration',
    ],
  },
};
