import type { GenreGuide } from './types';

export const HINDI_GUIDE: GenreGuide = {
  id: 'hindi',
  name: 'Hindi & Bollywood Music',
  language: 'Hindi',

  sonicPalette: {
    overview: 'Maximalist, melodically rich, and emotionally heightened. Bollywood music is the world\'s largest film music industry — songs are composed for narrative contexts and carry the emotional weight of entire storylines. The palette fuses Indian classical elements with global pop, electronic, and hip-hop production.',
    timbre: [
      'sitar and veena (plucked strings)',
      'tabla (paired hand drums)',
      'dholak and dhol (double-headed drums)',
      'shehnai (double-reed wind instrument)',
      'harmonium (pump organ)',
      'sarangi (bowed string)',
    ],
    texture: 'Dense and layered — Bollywood production fills every frequency range. Orchestral strings, electronic beats, Indian percussion, and synths coexist. Intimate acoustic textures for ghazal and devotional.',
    tonality: 'Raga-based melodies over Western harmonic structures. Minor keys and modal tonalities dominate emotional songs. Major keys for celebration. Indian classical ragas provide melodic vocabulary.',
    signatureSounds: [
      'tabla rhythmic pattern (theka)',
      'sitar melody line',
      'dhol-driven dance beat',
      'shehnai wedding melody',
      'Bollywood string section sweep',
    ],
  },

  rhythmAndGroove: {
    overview: 'Bollywood rhythm combines Indian tala (rhythmic cycles) with Western and global dance patterns. The tabla theka provides rhythmic identity while kick-snare patterns add modern punch.',
    bpmRange: { min: 60, max: 160, sweet: 110 },
    feel: 'Dance-driven in item numbers. Gentle and flowing in romantic ballads. Devotional music follows raga tempo conventions. Modern Bollywood incorporates EDM, trap, and hip-hop feels.',
    swing: 'Tabla patterns have inherent swing derived from tala tradition. Western-influenced tracks are generally straight. Qawwali has a distinctive accelerating rhythmic feel.',
    syncopation: 'High in tabla-driven music — tala patterns are inherently complex. Modern Bollywood dance tracks use syncopated hi-hats and vocal rhythms.',
    grooveArchetype: 'Keherwa tala (8-beat cycle), dadra (6-beat), tintal (16-beat), four-on-the-floor dance, dhol-driven bhangra beat.',
    rhythmicSignatures: [
      'keherwa: dha-ge-na-ti-na-ka-dhi-na (8-beat, most common)',
      'tintal: 16-beat cycle for classical-influenced pieces',
      'dhol pattern: heavy bass with high stick accents (Punjabi)',
      'four-on-the-floor with tabla layered on top (modern)',
    ],
  },

  harmonicLanguage: {
    overview: 'Bollywood harmony blends raga-based melodic thinking with Western chord progressions. Melodies follow raga rules; harmony provides Western pop structure beneath. The tension between these systems creates Bollywood\'s distinctive sound.',
    scales: [
      'raga-derived scales (Bhairavi, Yaman, Khamaj)',
      'natural minor (Aeolian)',
      'harmonic minor',
      'major (Ionian)',
      'pentatonic (simplified raga patterns)',
    ],
    chordProgressions: [
      'i – bVII – bVI – V (minor Bollywood standard)',
      'I – IV – V – I (celebratory)',
      'i – iv – i – V (romantic minor)',
      'I – V – vi – IV (modern pop-influenced)',
    ],
    harmonyNotes: 'Raga melodies don\'t always align with Western chord function — this deliberate tension is part of the Bollywood sound. Drone (tanpura) harmony is fundamental in classical-influenced contexts.',
    modality: 'Strongly modal — raga-based melodies create modal flavours even over Western progressions. Each raga carries specific emotional associations (Bhairavi for devotion, Yaman for romance at dusk).',
  },

  songStructure: {
    overview: 'Bollywood song structure is driven by film narrative — songs serve specific story functions (romance, celebration, heartbreak, item number). The mukhda (opening melodic phrase) is the hook.',
    form: 'Mukhda (hook/refrain) – Antara 1 (verse) – Mukhda – Antara 2 – Mukhda – Interlude – Final Mukhda',
    sections: [
      'Music intro (establishing mood and instrumentation)',
      'Mukhda (refrain — the main hook, returns multiple times)',
      'Antara (verse — develops the melody and lyrics)',
      'Interlude (instrumental, often showcasing Indian instruments)',
      'Bridge (modern addition, Western influence)',
    ],
    arrangement: 'Builds from the mukhda hook. Each antara develops melodically. Interludes showcase instrumental virtuosity. The final mukhda is the emotional climax.',
    introOutro: 'Music intros establish the raga and mood — can be orchestral, electronic, or acoustic. Outros often fade on the mukhda melody or end with a dramatic instrumental flourish.',
    barLengths: 'Mukhda: 4-8 bars. Antara: 8-16 bars. Interlude: 8-16 bars. Total: 4-6 minutes (film songs are rarely short).',
    hookPlacement: 'The mukhda IS the hook — it opens the song and returns between every section. Bollywood songs are identified by their mukhda.',
  },

  vocalDelivery: {
    overview: 'Bollywood vocal delivery inherits from Indian classical music — ornamental, technically demanding, and emotionally intense. Playback singers (Lata Mangeshkar, Kishore Kumar, Arijit Singh) are cultural icons whose voices define eras.',
    phrasing: 'Ornamental and melismatic. Phrases follow raga conventions — ascending and descending patterns with prescribed ornament (gamak, meend). Hindi\'s flowing syllable structure enables long melodic lines.',
    affect: 'Maximum emotional commitment. Bollywood demands that the voice carry the full emotional weight of a film scene. Joy, heartbreak, devotion, desire — all delivered at full intensity.',
    techniques: [
      'gamak (vocal oscillation/ornament)',
      'meend (gliding between notes)',
      'taan (rapid scalar passage)',
      'falsetto for emotional vulnerability',
      'powerful chest voice belt',
    ],
    adlibStyle: 'Vocal ornaments serve as ad-libs. "Aa" and "oh" interjections. Sargam passages (singing scale syllables: sa, re, ga, ma). Humming as emotional texture.',
    harmony: 'Minimal — Indian vocal tradition is monophonic. Modern Bollywood adds backing vocal layers. Qawwali uses group unison and call-and-response.',
    grit: 'Variable — Kishore Kumar brought playful roughness. Classical-influenced singers maintain purity. Modern hip-hop influenced artists add edge.',
  },

  lyricalConventions: {
    overview: 'Bollywood lyrics blend Hindi, Urdu, and Punjabi to create a poetic language uniquely suited to musical expression. The Urdu ghazal tradition infuses Bollywood with literary sophistication — couplet structure, metaphor, and the art of the sher (verse).',
    themes: [
      'romantic love (ishq, mohabbat, pyaar)',
      'heartbreak and separation (judai, dard)',
      'celebration and festivity (shaadi, tyohaar)',
      'devotion to God (bhakti, ibaadat)',
      'patriotism (desh bhakti)',
      'modern youth life and aspiration',
    ],
    perspective: 'First-person romantic address dominant. The beloved is addressed directly. Devotional songs address God. Patriotic songs use "we" perspective.',
    figurativeLanguage: 'Elaborate Urdu-Hindi poetic metaphor: the beloved as moon (chaand), eyes as intoxication (nashe), love as fire (aag), heart as vessel (dil). Seasons carry emotional weight (monsoon for romance, spring for new love).',
    vocabulary: 'Hindustani — a blend of Hindi and Urdu. Sanskrit-derived words for classical gravitas. Urdu-Persian vocabulary for romantic poetry. Punjabi for celebratory energy. English phrases in modern tracks.',
    storytellingApproach: 'Film-narrative driven — the song serves a specific story moment. Romantic songs paint emotional atmosphere. Item numbers are pure energy. Devotional songs create spiritual transcendence.',
    cliches: [
      '"dil" (heart) in every other line',
      '"tere bina" (without you) as separation hook',
      'monsoon rain as romantic metaphor',
      '"ishq" vs "pyaar" as love register choices',
    ],
  },

  productionFingerprint: {
    overview: 'Bollywood production is among the most elaborate in global pop — large orchestras, electronic production, Indian classical instruments, and world-class studios combine to create maximalist soundscapes.',
    mixAesthetic: 'Dense, bright, and full-spectrum. Vocal always prominent. Bass punchy for dance tracks. Orchestral warmth for romantic ballads. Modern EDM influence on club tracks.',
    era: 'Current era: Arijit Singh dominance. Indie music (non-film) growing. Punjabi pop crossover. Electronic and hip-hop influence. Streaming changing the film-centric model.',
    signalChain: 'Major Mumbai studios (Yash Raj Films, T-Series). Full orchestras recorded. Vocal: high-end condenser → compression → reverb. Electronic elements: DAW-based with Indian instrument VSTs.',
    modernTrends: 'Punjabi pop-Bollywood fusion. EDM drops in dance numbers. Indian hip-hop breakthrough. Lo-fi and bedroom indie in Hindi. Remake culture (re-recording classic songs with modern production).',
  },

  instrumentation: {
    coreInstruments: [
      'tabla (paired hand drums)',
      'sitar (plucked string)',
      'harmonium (pump organ)',
      'dholak/dhol (double-headed drums)',
      'sarangi (bowed string)',
      'orchestral strings and brass',
    ],
    signatureSounds: [
      'tabla theka rhythmic pattern',
      'sitar melodic phrase',
      'shehnai wedding call',
      'dhol dance beat',
    ],
    layering: 'Extremely dense in dance numbers. Acoustic and intimate in ghazals. Orchestral layering rivalling film scores. Modern tracks blend electronic and acoustic.',
    avoidInstruments: [
      'country instruments (banjo, steel guitar)',
      'African percussion',
      'Japanese instruments',
      'heavy rock distortion (unless rock fusion)',
    ],
  },

  culturalContext: {
    overview: 'Bollywood music is inseparable from Indian cinema — the world\'s largest film industry by output. Songs are composed for films and carry the emotional weight of the narrative. Music is central to Indian social life, from weddings to religious festivals.',
    origin: 'Mumbai (Bollywood film industry). The playback singing system — where singers record songs that actors lip-sync on screen — was established in the 1940s and remains the dominant model.',
    identity: 'Hindi-Urdu is the primary language. Bollywood music represents a pan-Indian cultural identity that transcends regional language barriers. The playback singer is often more famous than the film actor.',
    community: '1.4 billion potential Indian listeners plus massive diaspora. Music is communal — wedding sangeets, festival celebrations, and family gatherings are scored by Bollywood. T-Series (India\'s largest music label) is the most-subscribed YouTube channel globally.',
    socialFunction: 'Wedding celebrations (sangeet, mehendi). Religious festivals (Holi, Diwali, Navratri). Film entertainment. Emotional processing. Youth identity expression. National pride (patriotic songs).',
    authenticityMarkers: [
      'Hindi/Urdu lyrics with correct register',
      'appropriate raga usage in melodies',
      'tabla and Indian percussion correctly employed',
      'emotional authenticity in vocal delivery',
      'understanding of film-song narrative function',
    ],
  },

  historicalLineage: {
    overview: 'From 1930s talkies through the golden age of Lata and Kishore to A.R. Rahman\'s global breakthrough and today\'s streaming-era diversity.',
    roots: [
      'Indian classical music (Hindustani raga tradition)',
      'Urdu ghazal and nazm poetry',
      'folk traditions across India\'s regions',
      'early Hindi cinema (1930s talkies)',
      'Western orchestral film scoring',
    ],
    evolution: 'Early talkies (1930s) → golden age: Lata Mangeshkar, Mohammed Rafi, Kishore Kumar (1950s-70s) → disco-era Bollywood (1980s) → A.R. Rahman revolution (1990s) → globalized Bollywood pop (2000s) → streaming and indie era (2010s-present).',
    keyEras: [
      '1950s-70s: Golden age (Lata, Rafi, Kishore, S.D. Burman)',
      '1980s: Bappi Lahiri disco-Bollywood',
      '1990s: A.R. Rahman revolution (Roja, Dil Se)',
      '2000s: Globalized Bollywood (Shankar-Ehsaan-Loy, Vishal-Shekhar)',
      '2010s-present: Arijit Singh era, indie Hindi music',
    ],
    influencedBy: [
      'Indian classical music (Hindustani)',
      'Urdu poetry tradition',
      'Western film scoring',
      'disco and electronic music',
      'hip-hop and R&B',
    ],
    influenced: [
      'Pakistani pop and film music',
      'Bangladeshi music',
      'Southeast Asian pop',
      'global film music scoring',
      'British Asian music scene',
    ],
  },

  subGenres: [
    {
      name: 'Bollywood Dance',
      description: 'High-energy film dance numbers — the sonic backbone of Indian cinema. Designed for choreographed sequences, wedding parties, and massive cultural celebration.',
      distinguishingFeatures: ['high energy production', 'dhol/electronic beat fusion', 'call-and-response hooks', 'choreography-optimized'],
      bpmRange: { min: 110, max: 160 },
      keyArtists: ['Vishal-Shekhar', 'Pritam', 'Badshah', 'Yo Yo Honey Singh'],
      productionNotes: 'Maximalist — electronic beats, dhol, orchestral hits, everything. Bass punchy. Hook must be instantly catchy. Wedding-DJ ready.',
      lyricNotes: 'Celebration, attraction, party energy. Hindi with Punjabi phrases. Dance commands. Simple, catchy hooks.',
      sunoPromptKeywords: ['Bollywood dance', 'item number', 'Indian party song', 'dhol beat', 'wedding dance Hindi'],
    },
    {
      name: 'Bollywood Ballad',
      description: 'Romantic film ballads — the emotional heart of Hindi cinema. From Lata Mangeshkar\'s crystalline purity to Arijit Singh\'s contemporary ache. The mukhda hook defines the film\'s emotional identity.',
      distinguishingFeatures: ['melodically rich vocal performance', 'orchestral/acoustic arrangement', 'raga-influenced melody', 'film narrative function'],
      bpmRange: { min: 60, max: 90 },
      keyArtists: ['Arijit Singh', 'Lata Mangeshkar', 'Shreya Ghoshal', 'Sonu Nigam'],
      productionNotes: 'Vocal is everything. Acoustic guitar or piano foundation. Strings build emotion. Tabla provides gentle rhythmic pulse. Space for vocal ornament.',
      lyricNotes: 'Romantic love, heartbreak, longing. Hindi-Urdu poetic language. Gulzar and Javed Akhtar as lyric gold standards.',
      sunoPromptKeywords: ['Bollywood ballad', 'Hindi romantic', 'Arijit Singh style', 'Indian love song', 'filmi ballad'],
    },
    {
      name: 'Qawwali',
      description: 'Sufi devotional music — ecstatic, rhythmically intensifying, and spiritually transcendent. Nusrat Fateh Ali Khan defined the art for global audiences. Group performance with clapping and call-and-response.',
      distinguishingFeatures: ['group vocal performance', 'rhythmic acceleration', 'Sufi devotional lyrics', 'call-and-response structure'],
      bpmRange: { min: 80, max: 140 },
      keyArtists: ['Nusrat Fateh Ali Khan', 'Sabri Brothers', 'Rahat Fateh Ali Khan', 'Abida Parveen'],
      productionNotes: 'Live group recording. Harmonium drone foundation. Tabla rhythm. Group clapping (taali). Vocal must be powerful and ornamental.',
      lyricNotes: 'Sufi devotional — love as metaphor for divine union. Urdu and Persian. Mystical poetry of Rumi, Amir Khusrau, Bulleh Shah.',
      sunoPromptKeywords: ['qawwali', 'Sufi music', 'Nusrat style', 'devotional Indian', 'mystical qawwali'],
    },
    {
      name: 'Ghazal',
      description: 'The Urdu poetic song form — intimate, literary, and emotionally refined. Couplet-based structure where each sher (couplet) is a self-contained poem. The pinnacle of Urdu literary-musical culture.',
      distinguishingFeatures: ['couplet (sher) structure', 'Urdu poetic language', 'intimate performance', 'harmonium-tabla accompaniment'],
      bpmRange: { min: 60, max: 80 },
      keyArtists: ['Mehdi Hassan', 'Jagjit Singh', 'Ghulam Ali', 'Begum Akhtar'],
      productionNotes: 'Intimate acoustic recording. Harmonium, tabla, sarangi. Minimal processing. Vocal clarity paramount. The words must be heard perfectly.',
      lyricNotes: 'Highest Urdu literary register. Each sher is self-contained. Love, loss, wine, the beloved\'s cruelty. Rhyme and meter (beher) are strict.',
      sunoPromptKeywords: ['ghazal', 'Urdu ghazal', 'Jagjit Singh style', 'Indian classical vocal', 'romantic Urdu'],
    },
    {
      name: 'Indi-Pop',
      description: 'Non-film Hindi pop music — independent of Bollywood. Growing rapidly through streaming, offering artistic freedom from film narrative constraints.',
      distinguishingFeatures: ['non-film independent release', 'artist-driven (not composer-driven)', 'diverse production styles', 'streaming-first distribution'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Prateek Kuhad', 'Anuv Jain', 'The Local Train', 'When Chai Met Toast'],
      productionNotes: 'Varies — indie rock, lo-fi, acoustic, electronic. Generally more stripped-back than Bollywood. Artistic vision over commercial formula.',
      lyricNotes: 'Personal, introspective, poetic. Hindi with English mixing. Less formulaic than film songs. Contemporary urban themes.',
      sunoPromptKeywords: ['Hindi indie', 'Indi-pop', 'Indian indie', 'Prateek Kuhad style', 'non-film Hindi'],
    },
    {
      name: 'Indian Hip-Hop',
      description: 'Hindi-language hip-hop — from Mumbai gully rap to mainstream crossover. Gully Boy (2019) brought Indian hip-hop to national consciousness. Street credibility and lyrical skill valued.',
      distinguishingFeatures: ['Hindi/Bambaiya rap flow', 'trap and boom-bap production', 'street and social themes', 'Mumbai underground origins'],
      bpmRange: { min: 75, max: 95 },
      keyArtists: ['DIVINE', 'Naezy', 'Emiway Bantai', 'Raftaar', 'MC Stan'],
      productionNotes: 'Trap 808s and boom-bap adapted for Hindi flow. Indian instrument samples for identity. Bass-heavy. Vocal clarity for rapid Hindi.',
      lyricNotes: 'Street life, social inequality, hustle, Mumbai geography. Hindi with Bambaiya slang. Wordplay and flow complexity valued.',
      sunoPromptKeywords: ['Indian hip-hop', 'gully rap', 'Hindi rap', 'Mumbai rap', 'DIVINE style'],
    },
    {
      name: 'Sufi Pop',
      description: 'Bollywood\'s incorporation of Sufi musical elements — mystical devotion repackaged as mainstream pop. A.R. Rahman pioneered this fusion, creating songs of spiritual intensity within commercial film contexts.',
      distinguishingFeatures: ['Sufi lyrical themes in pop framework', 'qawwali-influenced arrangements', 'spiritual intensity', 'A.R. Rahman pioneering'],
      bpmRange: { min: 80, max: 120 },
      keyArtists: ['A.R. Rahman', 'Kailash Kher', 'Rabbi Shergill', 'Abida Parveen (crossover)'],
      productionNotes: 'Blend of Sufi instruments (harmonium, dholak) with pop production. Building intensity. Vocal must convey devotional fervour.',
      lyricNotes: 'Sufi mystical poetry in accessible form. Divine love metaphors. "Khwaja", "Maula", "Piya" as spiritual address.',
      sunoPromptKeywords: ['Sufi pop', 'Bollywood Sufi', 'A.R. Rahman Sufi', 'mystical Hindi pop', 'spiritual Bollywood'],
    },
    {
      name: 'Punjabi Pop',
      description: 'Punjabi-language pop from India and diaspora — bhangra beats, dhol-driven energy, and massive crossover into Bollywood and global markets. The party music of South Asian communities worldwide.',
      distinguishingFeatures: ['dhol-driven beat', 'Punjabi language', 'bhangra rhythm influence', 'celebratory energy'],
      bpmRange: { min: 90, max: 140 },
      keyArtists: ['Diljit Dosanjh', 'AP Dhillon', 'Sidhu Moose Wala', 'Guru Randhawa'],
      productionNotes: 'Dhol is essential — live or sampled. Modern production blends trap, EDM, and bhangra. Bass-heavy. Party-ready mastering.',
      lyricNotes: 'Love, celebration, Punjabi pride, party energy. Punjabi with Hindi phrases. Rural-urban blend.',
      sunoPromptKeywords: ['Punjabi pop', 'bhangra', 'dhol beat', 'Diljit Dosanjh style', 'Punjabi dance'],
    },
    {
      name: 'Bollywood EDM',
      description: 'Electronic dance music integrated into Bollywood film songs — EDM drops, builds, and festival-ready production within the Hindi film song framework.',
      distinguishingFeatures: ['EDM drops and builds', 'Bollywood vocal hooks', 'festival-ready energy', 'film song structure'],
      bpmRange: { min: 125, max: 140 },
      keyArtists: ['Nucleya', 'KSHMR', 'Lost Stories', 'Ritviz'],
      productionNotes: 'Standard EDM production with Indian elements — tabla samples, sitar riffs, Indian vocal hooks over electronic builds and drops.',
      lyricNotes: 'Simple, hook-driven. Party and energy themes. Hindi with English. Dance commands.',
      sunoPromptKeywords: ['Bollywood EDM', 'Indian EDM', 'Nucleya style', 'bass Indian', 'electronic Hindi'],
    },
    {
      name: 'Devotional/Bhajan',
      description: 'Hindu devotional songs — aarti, bhajan, kirtan. From ancient temple music tradition to modern recorded devotional pop. Spiritual function is primary.',
      distinguishingFeatures: ['devotional spiritual lyrics', 'traditional instruments', 'raga-based melodies', 'temple and ritual function'],
      bpmRange: { min: 60, max: 100 },
      keyArtists: ['Anup Jalota', 'Anuradha Paudwal', 'Lata Mangeshkar (devotional)', 'Shankar Mahadevan'],
      productionNotes: 'Acoustic and reverent. Harmonium, tabla, manjira (cymbals). Vocal pure and devotional. Simple arrangements serving the prayer.',
      lyricNotes: 'Sanskrit and Hindi devotional lyrics. Praise of deities (Ram, Krishna, Shiva, Durga). Mantras and prayers.',
      sunoPromptKeywords: ['bhajan', 'Hindu devotional', 'Indian spiritual', 'aarti', 'kirtan'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'The Hindi music audience is the world\'s largest single-language music market. Bollywood songs are woven into daily life — weddings, festivals, auto-rickshaw radios, and family gatherings.',
    fanExpectations: [
      'memorable mukhda hooks',
      'emotional vocal delivery',
      'Hindi/Urdu lyrics with poetic quality',
      'production quality befitting the sub-genre',
      'dance-floor readiness for party tracks',
    ],
    gatekeeping: 'Low in Bollywood mainstream — commercial success is the ultimate validator. Higher in classical and ghazal (training and lineage matter). Hip-hop values street credibility.',
    livePerformance: 'Film music concerts are massive events. Wedding sangeets are the primary participatory music experience. Qawwali performances create communal spiritual ecstasy. Indie scene has growing live venue culture.',
    fashionAndAesthetic: 'Bollywood: glamorous, designer-driven, film-star fashion. Punjabi: bold and colourful. Hip-hop: international streetwear with desi elements. Devotional: traditional and modest.',
    crossoverPotential: 'Massive diaspora market (UK, US, Canada, Middle East). A.R. Rahman achieved global recognition. Punjabi pop crosses over via bhangra. Hindi music rarely crosses the language barrier to Western mainstream but dominates South Asian global communities.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Hindi/Bollywood music operates within the tala system — rhythmic cycles of specific beat counts that create timing frameworks fundamentally different from Western 4/4. Tabla rhythmic patterns (thekas) introduce swing, syncopation, and micro-timing variation that cannot be captured by a Western grid.',
    quantizationDeviation: 'High in classical-influenced and ghazal tracks — tabla timing follows tala cycles with inherent micro-timing variation. Moderate in Bollywood pop (modern grid with tabla layered). Low in EDM-influenced dance numbers.',
    aheadBehindBeat: 'Tabla sits in a complex relationship with the beat — specific strokes (dha, dhin, na, tin) have prescribed timing relationships within the tala cycle. Vocals in classical-influenced music follow raga phrasing rather than the rhythmic grid.',
    humanizationMarkers: [
      'tabla theka patterns with inherent tala-based micro-timing',
      'vocal gamak (oscillation) creating timing ambiguity around target notes',
      'meend (gliding between notes) stretching across beats',
      'live dholak playing with natural hand-drum timing variation',
      'rubato in ghazal vocal delivery following poetic meter rather than musical meter',
    ],
    genreSpecificFeel: 'The Bollywood feel is paradoxically both ancient and modern — tabla cycles inherited from centuries of classical tradition sit beneath contemporary production. The tala creates a circular sense of time distinct from Western linear beat counting.',
  },

  silenceAndSpace: {
    overview: 'Bollywood uses silence to frame the mukhda hook and to create space for vocal ornament. The pause before a vocalist begins an alaap (slow melodic exposition) is charged with anticipation — the audience knows the raga is about to unfold.',
    negativeSpaceRole: 'The mukhda\'s impact depends on the space around it — the instrumental intro builds expectation, and the vocal entry fills a void the listener has been anticipating. Interludes between antaras provide breathing room for the emotional arc.',
    breathingPatterns: 'Classical-influenced delivery uses breath as structural marker — phrases end where the singer breathes, and these pauses are part of the composition. Modern pop uses more standard breathing. Qawwali builds intensity by shortening breath pauses.',
    dynamicContrast: 'Significant between verse and mukhda. Dance numbers are uniformly loud. Ghazals have enormous dynamic range — the sher (couplet) delivered in near-whisper can be followed by full-voiced passion. A.R. Rahman pioneered dynamic contrast in Bollywood scoring.',
    whatIsDeliberatelyAbsent: [
      'harmony in classical-influenced passages — melody and drone only',
      'percussion during alaap (slow melodic introduction) — rhythm enters later',
      'Western chord changes during tanpura drone sections',
      'electronic elements in devotional/bhajan contexts',
      'vocal backing during ghazal sher delivery — the voice stands alone',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response is structural in Hindi music — qawwali is built entirely on it, Bollywood dance numbers use it for crowd participation, and the antara-mukhda relationship is itself a form of call-and-response.',
    vocalInstrumentalDialogue: 'The sitar or shehnai responds to the vocalist\'s phrases. Tabla engages in sawaal-jawaab (question-answer) with the melody. Instrumental interludes "answer" the vocal sections. The tanpura drone provides a constant harmonic "ground" against which voice and instruments converse.',
    sectionInternal: 'In qawwali, the lead singer phrases and the group responds in unison — this exchange accelerates as ecstasy builds. In Bollywood songs, the mukhda is the "answer" that the antara "calls" for.',
    audienceParticipation: 'Qawwali audiences respond with devotional exclamations. Concert audiences sing mukhda hooks. Wedding sangeet performances are inherently participatory — everyone dances and sings. Bollywood film songs are designed for group sing-along.',
    patterns: [
      'qawwali lead singer call with group unison response',
      'wedding sangeet audience dancing and singing the hook',
      'concert crowds completing the mukhda when the singer holds the mic out',
      'tabla sawaal-jawaab (question-answer) exchange with melody instrument',
      'devotional bhajan congregation singing the refrain after the lead singer',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'The Hindi-Urdu linguistic spectrum and India\'s massive multilingual reality create a complex dialect landscape. Bollywood Hindi, literary Urdu, Punjabi, and regional languages each carry distinct musical traditions and cultural identities.',
    phoneticMarkers: [
      'Bollywood Hindi\'s standardized pronunciation — clear and universally intelligible',
      'Urdu\'s Persian-influenced phonology in ghazal delivery (retroflex consonants, aspirated stops)',
      'Punjabi\'s tonal quality and energetic consonant clusters in bhangra pop',
      'Mumbai Bambaiya street Hindi in hip-hop (tapori slang)',
      'classical Sanskrit pronunciation in devotional bhajan',
    ],
    accentInfluence: 'Standard Hindi dominates Bollywood, but Urdu provides the prestigious poetic register for romantic songs. Punjabi has exploded as a commercial force. Regional film industries (Tamil, Telugu, Bengali) have distinct musical traditions that occasionally cross over.',
    dialectVocabulary: [
      '"ishq" (Urdu/Persian) vs "pyaar" (Hindi) vs "prem" (Sanskrit) — three registers for "love"',
      'Punjabi celebration vocabulary ("balle balle", "nachdi") in dance tracks',
      'Bambaiya slang ("bhai", "tera", "apna") in Mumbai hip-hop',
      'Urdu-Persian poetic vocabulary ("ghazal", "sher", "mehfil") in classical-influenced songs',
      'Sanskrit devotional vocabulary ("om", "bhagwan", "deva") in bhajans',
    ],
    regionWithinCulture: 'Mumbai is the Bollywood centre. Punjab is the bhangra and Punjabi pop powerhouse. Lucknow and Hyderabad represent Urdu ghazal tradition. Chennai, Hyderabad, and Kolkata have independent film music industries. Delhi\'s hip-hop scene is distinct from Mumbai\'s.',
  },

  performancePractice: {
    overview: 'Hindi music performance is defined by the playback singing tradition — where studio singers record songs that actors lip-sync on screen — and by the communal experiences of wedding sangeets, devotional gatherings, and concert spectacles.',
    improvisationConventions: 'Classical music demands improvisation (alaap, taan, sawaal-jawaab). Ghazal performances include improvised ornament. Bollywood concerts reproduce studio recordings closely. Qawwali is extensively improvised within the structure.',
    crowdInteraction: 'Concert audiences sing along to mukhda hooks. Qawwali audiences respond with devotional exclamations and requests for repetition. Wedding sangeets are fully participatory — guests dance and sing. Film screenings historically included audience singing along.',
    stagePresence: 'Playback singers traditionally performed seated or standing still — the voice was everything. Modern concert artists use staging, screens, and movement. Qawwali groups sit in a semicircle facing the audience. Bollywood dance performance involves full choreography.',
    livVsRecordedDifferences: 'The playback tradition means the "live" version exists in the film — the studio recording IS the definitive performance. Concert performances of film songs must match what audiences know from the film. Non-film (indie) artists have more live freedom.',
    whatMakesAGoodShow: 'For playback singers: vocal reproduction matching the beloved recordings, plus emotional connection through MC segments sharing stories behind the songs. For concerts: massive production, film clips, guest appearances. For qawwali: achieving collective spiritual ecstasy.',
  },

  socioeconomicSubtext: {
    overview: 'Bollywood music reflects India\'s vast economic spectrum — from lavish wedding celebrations showcased in film songs to the street-level reality of gully rap. The playback singing system itself carries class implications as a path to fame for vocally talented individuals regardless of appearance.',
    materialConditions: 'T-Series (India\'s largest music label, most-subscribed YouTube channel) dominates distribution. Film music revenue comes from satellite and streaming rights. Live concerts are growing. Wedding performance fees are significant for established artists.',
    classIdentity: 'Bollywood songs for film depict aspiration and romance across class lines — the "rich girl, poor boy" narrative is foundational. Gully rap explicitly addresses economic inequality. Ghazal carries mehfil (gathering) culture associated with educated, culturally refined audiences.',
    politicalUndercurrent: 'Patriotic songs (desh bhakti) are a significant Bollywood category. Social commentary appears in specific films. Hindi hip-hop addresses caste, poverty, and religious tension. Bollywood generally avoids direct political controversy to maintain mass appeal.',
    implicitReferences: [
      'wedding extravagance in dance numbers reflecting aspiration and social status display',
      'Mumbai street life and chawl (tenement) references in gully rap',
      'caste and economic inequality addressed obliquely in film narratives',
      'diaspora identity negotiation in songs about leaving India',
      'item numbers reflecting the entertainment industry\'s relationship with spectacle and commerce',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Bollywood\'s intertextual tradition is massive — classic film songs are cultural scripture, and the remake/remix tradition explicitly reconnects new productions to the golden-age canon. R.D. Burman and A.R. Rahman are the twin poles of compositional reference.',
    canonKnowledge: 'Lata Mangeshkar and Mohammed Rafi defined the golden-age vocal standard. Kishore Kumar added playful versatility. R.D. Burman (Pancham) revolutionized Bollywood scoring with Western and funk influences. A.R. Rahman brought electronic sophistication and global recognition.',
    samplingTradition: 'Bollywood has a robust remake culture — classic songs are re-recorded with modern production for new films. This is both commercially driven and culturally connective. Direct sampling is less common than full reinterpretation.',
    quotationPractice: 'Quoting classic mukhda melodies is common and immediately recognized. Melodic references to R.D. Burman or S.D. Burman signal sophistication. Reality TV singing competitions center on performing canonical film songs.',
    expectedReferences: [
      'R.D. Burman\'s innovative arrangements as composition benchmark',
      'A.R. Rahman\'s "Jai Ho" as the global Bollywood crossover moment',
      'Lata Mangeshkar\'s "Lag Ja Gale" and similar classics as emotional touchstones',
      'Kishore Kumar\'s versatile vocal delivery as male vocal reference',
      'S.D. Burman\'s melodic inventiveness as golden-age compositional standard',
    ],
    lineageSignifiers: [
      'mukhda-antara structure as inherited Bollywood song form',
      'raga-based melodic vocabulary as classical music lineage',
      'playback singing tradition as industry structural inheritance',
      'the key-change final mukhda as emotional arc convention',
      'ghazal sher (couplet) structure as Urdu literary lineage in lyrics',
      'tabla theka patterns as rhythmic DNA connecting film music to classical tradition',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Hindi/Bollywood music has specific gender-coded song types — the heroine\'s romantic number, the hero\'s declaration, the item number, and the devotional — each carrying distinct performance conventions developed over decades of film music tradition.',
    vocalGenderCodes: 'Lata Mangeshkar\'s high, pure soprano defined the female Bollywood vocal ideal for decades. Male vocals range from Mohammed Rafi\'s versatile power to Kishore Kumar\'s playful baritone to Arijit Singh\'s contemporary ache. The playback system means vocal identity is separate from visual presentation.',
    physicalityInPerformance: 'Film choreography follows song type — romantic duets involve synchronized couple movement, item numbers feature dynamic group choreography, devotional songs use minimal movement. The playback system means the singer\'s body is absent from the visual performance.',
    genderNarratives: 'The heroine song (expressing longing, devotion, or joy) and the hero song (expressing determination, romantic pursuit, or heartbreak) are established categories. Item numbers are high-energy performance pieces historically centered on a female dancer. Male romantic ballads express devotion and loss.',
    subversionExamples: [
      'Asha Bhosle\'s sensual vocal delivery challenging Lata Mangeshkar\'s pure-voice standard',
      'female rappers in Hindi hip-hop (Raja Kumari, Dee MC, Hard Kaur) entering male-dominated space',
      'A.R. Rahman\'s compositions giving female characters complex emotional arcs beyond romance',
      'indie Hindi music moving beyond Bollywood\'s gender-typed song categories',
      'male playback singers expressing vulnerability and emotional fragility in contemporary ballads',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Bollywood tempo is profoundly influenced by the tala system — a song in keherwa tala (8-beat cycle) at 100 BPM feels completely different from a Western 4/4 song at 100 BPM because the rhythmic emphasis patterns create different temporal experiences.',
    psychologicalTempo: 'A Bollywood ballad at 80 BPM with sparse tabla and sustained vocal phrases feels nearly motionless. A dance number at the same 80 BPM with dhol and full percussion feels energetic. The tala cycle and percussion density determine perceived tempo more than the BPM number.',
    weightAndMomentum: 'Dhol-driven tracks carry enormous physical weight — the drum\'s bass and treble interaction creates momentum independent of tempo. Qawwali builds momentum through acceleration — the music literally gets faster as devotional intensity increases.',
    urgencyScale: 'Qawwali creates maximum urgency through rhythmic acceleration and vocal intensification. Item numbers create dance urgency through dense percussion. Ghazal creates emotional urgency at minimal tempo through poetic and vocal intensity.',
    comparisonToSameBPM: 'Bollywood at 110 BPM is denser, more melodically complex, and more emotionally loaded than Western pop at 110 BPM. The tala framework, raga-based melody, and film-narrative emotional context create a listening experience that transcends tempo comparison.',
  },

  mistakeConventions: {
    overview: 'Bollywood\'s playback tradition demands technical perfection from vocalists — the recording must be flawless because actors will lip-sync to it in perpetuity. But within classical and devotional contexts, emotional authenticity can transcend technical precision.',
    toleratedImperfections: [
      'vocal emotion causing slight pitch variation at climactic moments',
      'tabla improvisational timing variation within tala framework',
      'live concert vocal strain during demanding passages (shows dedication)',
      'natural harmonium bellows breathing affecting sustain',
    ],
    celebratedFlaws: [
      'Kishore Kumar\'s playful vocal quirks becoming signature style',
      'gully rap\'s raw, unpolished delivery as street authenticity',
      'qawwali vocalist\'s voice breaking at the peak of devotional ecstasy',
      'indie Hindi music\'s deliberately lo-fi production as anti-Bollywood statement',
    ],
    overproductionRisks: [
      'auto-tuning a classical-influenced vocal losing its raga ornament character',
      'quantizing tabla patterns to a Western grid destroying tala feel',
      'modern remix of classic song losing the original\'s emotional DNA',
      'EDM production overwhelming the melody that makes a Bollywood song memorable',
      'electronic replacement of live instruments removing the organic texture',
    ],
    authenticRoughness: 'Acceptable in gully rap, indie music, and folk-influenced tracks. Unacceptable in mainstream Bollywood playback — the recording must be pristine. Classical and ghazal demand technical mastery but value emotional truth over cold perfection.',
  },

  referenceTracks: [
    {
      title: 'Kesariya',
      artist: 'Arijit Singh',
      year: 2022,
      whyExemplary: 'The biggest Bollywood love anthem of the decade — Pritam\'s melody and Arijit\'s delivery created a song that transcended the film to become a cultural moment across South Asia.',
      structuralNotes: 'Extended intro with a soft acoustic guitar establishing the raga-inflected melody before full orchestration enters. Verse-chorus form with an interlude that functions as a second mukhda.',
      craftHighlight: 'The melody moves in stepwise motion through a raga-adjacent scale, making it feel both classically rooted and immediately accessible — the Bollywood sweet spot.',
    },
    {
      title: 'Pasoori',
      artist: 'Ali Sethi & Shae Gill (Coke Studio)',
      year: 2022,
      whyExemplary: 'The most globally streamed South Asian song ever — a Pakistan-India cultural bridge that proved subcontinental pop could dominate global playlists.',
      structuralNotes: 'Hypnotic loop-based structure with a bass groove that never changes. The melody builds through layering — each section adds a new vocal layer over the same harmonic foundation.',
      craftHighlight: 'The bassline functions as a drone in the Indian classical tradition but grooves like a modern pop production — ancient and contemporary simultaneously.',
    },
    {
      title: 'Apna Bana Le',
      artist: 'Arijit Singh',
      year: 2023,
      whyExemplary: 'Arijit\'s emotional range — from whispered vulnerability to soaring belting — demonstrated why he dominates Bollywood playback, delivering a modern love ballad with classical depth.',
      structuralNotes: 'Slow-build ballad with piano intro, adding strings and percussion layer by layer. The antara (verse) is conversational; the mukhda (chorus) opens into a wide melodic landscape.',
      craftHighlight: 'The transition from chest voice to head voice in the chorus mirrors the lyrical shift from personal confession to universal declaration — vocal technique serving emotional architecture.',
    },
    {
      title: 'Jhoome Jo Pathaan',
      artist: 'Arijit Singh & Sukriti Kakar',
      year: 2023,
      whyExemplary: 'Vishal-Shekhar\'s high-energy dance track for the biggest Bollywood blockbuster of its era, proving that Bollywood party songs can have melodic sophistication.',
      structuralNotes: 'Dance-pop structure with a drop-style chorus influenced by EDM. Short verses, extended pre-chorus build, and a chorus designed for stadium-scale choreography.',
      craftHighlight: 'The Arabic melodic inflections in the chorus melody nod to the film\'s setting while grounding the song in a specific sonic geography beyond generic Bollywood pop.',
    },
    {
      title: 'Gehraiyaan Title Track',
      artist: 'OAFF & Savera',
      year: 2022,
      whyExemplary: 'A landmark for Indian indie music crossing into Bollywood — electronic, brooding, and emotionally complex, it signaled a new direction for Hindi film music.',
      structuralNotes: 'Minimalist electronic structure with ambient textures, spoken-word passages, and a chorus that emerges gradually from the sonic landscape rather than arriving as a distinct section.',
      craftHighlight: 'The production uses negative space as the primary emotional tool — what\'s absent (big orchestration, dramatic crescendos) speaks louder than what\'s present.',
    },
    {
      title: 'Besharam Rang',
      artist: 'Shilpa Rao & Caralisa Monteiro',
      year: 2022,
      whyExemplary: 'Vishal-Shekhar\'s dance number pushed Bollywood\'s sonic palette with electronic production while keeping the playback singing tradition\'s melodic demands intact.',
      structuralNotes: 'Latin-EDM influenced dance structure with a reggaeton-adjacent rhythm section. The melody rides above the groove with a distinctly Indian melodic sensibility despite the global production style.',
      craftHighlight: 'The vocal harmonization in the chorus blends Western pop harmony with Indian unison-octave doubling, creating a hybrid texture that sounds natural rather than forced.',
    },
    {
      title: 'Tum Kya Mile',
      artist: 'Arijit Singh & Shreya Ghoshal',
      year: 2023,
      whyExemplary: 'The pairing of Bollywood\'s two most dominant voices created a duet that showcased how Indian playback singing evolves — two generational styles meeting in the middle.',
      structuralNotes: 'Traditional Bollywood duet structure with alternating solo verses and a shared chorus. An instrumental interlude features tanpura and flute before the final combined section.',
      craftHighlight: 'Arijit\'s breathy, mic-intimate delivery against Shreya\'s classically projected voice creates a textural contrast that mirrors the male-female emotional dynamic of the lyrics.',
    },
    {
      title: 'Bijlee Bijlee',
      artist: 'Harrdy Sandhu',
      year: 2021,
      whyExemplary: 'A Punjabi-Hindi crossover hit that dominated across language lines, demonstrating the increasing fluidity between Bollywood and Punjabi pop markets.',
      structuralNotes: 'Bhangra-pop structure with a four-on-the-floor kick under dhol patterns. Short, repetitive sections designed for viral choreography, with the hook landing in the first 15 seconds.',
      craftHighlight: 'The dhol pattern is programmed with intentional swing that mimics live dhol playing rather than quantized electronic percussion — bridging traditional and modern production.',
    },
    {
      title: 'Raatan Lambiyan',
      artist: 'Jubin Nautiyal & Asees Kaur',
      year: 2021,
      whyExemplary: 'Tanishk Bagchi\'s biggest original composition (not a remake) became the decade\'s wedding anthem, proving that Bollywood\'s romantic ballad tradition still resonates massively.',
      structuralNotes: 'Acoustic guitar-driven ballad with a slow build into full orchestration. The mukhda melody is deliberately simple — singable in one listen — while the antara adds melodic complexity.',
      craftHighlight: 'The melody\'s narrow range (less than an octave in the chorus) ensures universal singability while the ornamental turns in the verse distinguish the playback version from the audience version.',
    },
    {
      title: '52 Gaj Ka Daman',
      artist: 'Renuka Panwar',
      year: 2021,
      whyExemplary: 'A Haryanvi folk-pop track that became one of YouTube India\'s most-viewed songs, demonstrating the commercial power of regional language music in the Hindi-speaking market.',
      structuralNotes: 'Folk song structure with a repeating mukhda and new verses added in the antara position. The arrangement layers electronic bass under traditional instruments.',
      craftHighlight: 'The regional Haryanvi dialect creates a sonic texture distinct from standard Hindi — the vowel sounds and rhythmic speech patterns shape the melody in ways Hindi cannot replicate.',
    },
    {
      title: 'Excuses',
      artist: 'AP Dhillon & Gurinder Gill',
      year: 2021,
      whyExemplary: 'The Canadian-Punjabi artist\'s global viral hit redefined what South Asian pop could sound like — minimalist, moody, and defiantly non-Bollywood.',
      structuralNotes: 'Ultra-minimal production — bass, kick, and voice occupy the entire mix. No traditional instruments, no Bollywood orchestration. Verse-chorus form with the chorus reduced to a single repeated phrase.',
      craftHighlight: 'The deliberate emptiness of the production forces the vocal melody to carry everything, proving that a strong enough melodic idea needs no ornamental support.',
    },
    {
      title: 'Maan Meri Jaan',
      artist: 'King',
      year: 2022,
      whyExemplary: 'An independent Hindi pop release that rivaled Bollywood numbers on streaming — proof that the Indian indie scene can produce mainstream hits without film industry backing.',
      structuralNotes: 'Western pop structure with verse-pre-chorus-chorus form. Clean, minimalist production with acoustic guitar and programmed beats. Under 3 minutes with no wasted bars.',
      craftHighlight: 'The Hindi lyrics use everyday conversational language rather than the poetic register typical of film songs, creating an intimate, direct emotional connection that Bollywood formality cannot achieve.',
    },
    {
      title: 'Husn',
      artist: 'Anuv Jain',
      year: 2023,
      whyExemplary: 'India\'s indie folk sensation created a Hindi ballad that spread entirely through social media — no film, no label push — rewriting the rules of Hindi music distribution.',
      structuralNotes: 'Intimate singer-songwriter structure with acoustic guitar and soft percussion. The arrangement never gets bigger than the voice, maintaining coffeehouse intimacy at streaming scale.',
      craftHighlight: 'Anuv\'s half-whispered vocal delivery breaks completely from the Bollywood playback tradition of projected singing, creating a new vocal aesthetic for Hindi pop.',
    },
    {
      title: 'Kho Gaye Hum Kahan',
      artist: 'Jasleen Royal, Prateek Kuhad & OAFF',
      year: 2023,
      whyExemplary: 'The title track of India\'s first major Zoya Akhtar Netflix film, bridging indie and mainstream with an alternative pop sound that felt neither Bollywood nor Western.',
      structuralNotes: 'Layered electronic pop with three distinct vocal textures woven through a continuous build. No clear verse-chorus division — the song evolves through gradual textural addition.',
      craftHighlight: 'Three vocalists with distinctly different timbres are mixed to create a collective voice that represents the film\'s ensemble — the production mirrors the narrative theme.',
    },
    {
      title: 'Arjan Vailly',
      artist: 'Bhupinder Babbal',
      year: 2023,
      whyExemplary: 'The "Animal" opening track brought raw Punjabi folk energy into a Bollywood blockbuster at maximum volume — uncompromising intensity that matched the film\'s tone.',
      structuralNotes: 'Folk-chant structure with a building, almost martial rhythm. No traditional verse-chorus — the song escalates through intensifying vocal delivery and additive percussion layers.',
      craftHighlight: 'The vocal delivery borrows from Sufi qawwali tradition — the building ecstatic intensity, the group vocals entering in waves — applied to a secular, aggressive context.',
    },
    {
      title: 'Satranga',
      artist: 'Arijit Singh',
      year: 2023,
      whyExemplary: 'Arijit\'s most emotionally devastating performance from "Animal" — a ballad that strips away production excess to foreground the voice\'s ability to convey complex heartbreak.',
      structuralNotes: 'Piano-and-voice core with orchestral swells that enter and retreat. The structure follows the emotional narrative rather than a fixed form — sections expand and contract organically.',
      craftHighlight: 'Arijit\'s use of vocal fry and breath as expressive tools — deliberately audible inhales, cracked notes left unedited — creates intimacy that polished playback singing cannot achieve.',
    },
    {
      title: 'Tere Vaaste',
      artist: 'Varun Jain & Sachin-Jigar',
      year: 2023,
      whyExemplary: 'A Bollywood romantic track that achieved massive streaming success by balancing traditional melodic sensibility with contemporary production minimalism.',
      structuralNotes: 'Guitar-driven ballad with a simple verse-chorus structure. The chorus melody is built on a pentatonic scale, making it accessible across regional language lines.',
      craftHighlight: 'The pentatonic melody avoids the chromatic complexity of classical raga influence, creating a pan-Indian accessibility that explains its cross-regional streaming success.',
    },
    {
      title: 'Naiyo Lagda',
      artist: 'Arijit Singh',
      year: 2023,
      whyExemplary: 'Arijit\'s versatility displayed in a romantic track that blends Sufi melodic phrasing with contemporary pop production for the "Kisi Ka Bhai Kisi Ki Jaan" soundtrack.',
      structuralNotes: 'Traditional Bollywood romantic structure with a prelude section, two verse-chorus cycles, and an instrumental bridge featuring Sufi-influenced vocal improvisation.',
      craftHighlight: 'The Sufi vocal improvisation section in the bridge allows Arijit to demonstrate classical training within a pop framework — spontaneity contained by structure.',
    },
    {
      title: 'O Bedardeya',
      artist: 'Arijit Singh',
      year: 2023,
      whyExemplary: 'Pritam\'s composition paired with Arijit\'s delivery created a devotional love song that functions equally as a filmi number and a standalone streaming hit.',
      structuralNotes: 'Ascending melodic structure where each section sits higher in the vocal range than the last, creating a physical sense of emotional escalation through pitch.',
      craftHighlight: 'The ascending key structure forces the vocalist into increasingly intense vocal registers, using the physics of the voice — the strain of high notes — as an emotional tool.',
    },
    {
      title: 'Appetite',
      artist: 'Seedhe Maut',
      year: 2023,
      whyExemplary: 'India\'s most respected rap duo delivered a track that proved Hindi hip-hop had matured beyond novelty into a legitimate art form with technical depth.',
      structuralNotes: 'Extended verse format with minimal hooks — the structural interest comes from flow switches and tempo changes within continuous bars. No traditional chorus.',
      craftHighlight: 'The bilingual Hindi-English flow switches mid-bar without losing rhythmic momentum, and the internal rhyme schemes in Hindi demonstrate the language\'s underexplored potential for rap.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: [
      'Bollywood', 'Hindi', 'Indian',
      'tabla', 'sitar', 'filmi',
      'romantic Hindi', 'desi', 'raga',
    ],
    avoidKeywords: [
      'country', 'bluegrass', 'K-Pop',
      'Celtic', 'reggaeton', 'jazz fusion',
    ],
    promptTemplate: '[sub-genre] Hindi/Bollywood music, [BPM] BPM, [mood], [key instruments], Hindi vocals, [film/non-film context]',
    tips: [
      'Specify Bollywood vs. indie — production approaches are completely different.',
      'For dance numbers: "dhol", "high energy", "wedding party", "celebration".',
      'For ballads: "Arijit Singh style", "romantic", "orchestral strings", "intimate".',
      'For qawwali: "Sufi", "group vocals", "harmonium", "accelerating rhythm".',
    ],
  },
};
