import type { GenreGuide } from './types';

export const HIP_HOP_GUIDE: GenreGuide = {
  id: 'hip-hop',
  name: 'Hip-Hop',
  language: 'English',

  sonicPalette: {
    overview: 'Bass-heavy, rhythmically complex, and sample-driven. Hip-hop production ranges from gritty boom-bap to ethereal cloud rap, but always centers the voice as the primary instrument. Low frequencies dominate — 808s, sub-bass, and kick drums shake speakers while crisp hi-hats and snares provide rhythmic definition.',
    timbre: [
      'Deep, sustained 808 bass (sine wave with distortion)',
      'Crisp, snappy snares and claps',
      'Rapid-fire hi-hat patterns (trap influence)',
      'Pitched-down vocal samples and tags',
      'Dark, moody pads and atmospheric textures',
      'Chopped soul/jazz/funk samples',
      'Lo-fi vinyl crackle and tape hiss (boom bap)',
      'Distorted 808s with harmonic saturation',
    ],
    texture: 'Sparse but heavy. Hip-hop production uses negative space strategically — the beat often breathes around the vocal. Contrast between minimal verse beats and fuller hook sections. Bass frequencies fill the low end while mid-range stays open for the voice.',
    tonality: 'Minor keys dominate (Am, Cm, Dm, Em). Dark, moody tonalities. Some sub-genres (jazz rap, conscious) use brighter major keys. Chromatic movement and dissonance are common in modern trap.',
    signatureSounds: [
      'Roland TR-808 kick and 808 bass',
      'Chopped vocal samples pitched up or down',
      'Producer tags and drops',
      'Vinyl scratching and DJ effects',
      'Gun cocking/reload sound effects',
      'Ambient reverb pads',
      'Distorted bass slides (808 glides)',
    ],
  },

  rhythmAndGroove: {
    overview: 'The beat is sacred in hip-hop. From the head-nodding swing of boom bap to the rolling hi-hats of trap, rhythm drives everything. The groove must make you move — whether nodding your head, bouncing, or leaning back.',
    bpmRange: { min: 65, max: 170, sweet: 140 },
    feel: 'Trap: heavy, bouncing, aggressive. Boom Bap: swinging, head-nodding, grooving. Drill: dark, sliding, menacing. Lo-fi: laid-back, hazy, contemplative.',
    swing: 'Boom bap: heavy swing on hi-hats and snares (MPC quantize). Trap: straight 16ths/32nds with occasional shuffle. Drill: minimal swing, sliding 808s provide movement.',
    syncopation: 'Essential — the MC\'s flow creates complex polyrhythmic interplay with the beat. Kick patterns often syncopate against the snare. Hi-hat patterns create micro-rhythmic tension.',
    grooveArchetype: 'Trap bounce (half-time snare with rolling hi-hats), boom-bap swing (chopped break loop), or drill slide (sparse kick patterns with sustained 808 bass)',
    rhythmicSignatures: [
      'Half-time snare on beat 3 (trap/drill)',
      'Boom-bap break loops (Funky Drummer, Amen Break)',
      'Trap hi-hat rolls: 16ths, 32nds, triplets with open/closed variation',
      'Kick drum patterns that lock with 808 bass',
      '808 bass slides (glissando between notes)',
      'Sparse, minimal drum patterns with heavy bass emphasis',
      'Double-time flows over half-time beats',
    ],
  },

  harmonicLanguage: {
    overview: 'Hip-hop harmony is often minimal but atmospheric. Many beats use just 2-3 chords or a single looped sample. The harmonic content comes from melodic samples, synth pads, or piano loops rather than traditional chord progressions.',
    scales: ['Natural Minor', 'Pentatonic Minor', 'Blues Scale', 'Phrygian', 'Harmonic Minor', 'Dorian'],
    chordProgressions: [
      'i – iv (two-chord minor loop)',
      'i – bVII – bVI – V (Andalusian cadence)',
      'i – bVI – bVII (minor rock progression)',
      'i – iv – bVII – bIII (minor circle)',
      'Single chord drone with melodic movement on top',
      'Sample-based (inherits harmony from source)',
      'i – V/i – iv – bVI (cinematic)',
    ],
    harmonyNotes: 'Harmony is often implied rather than explicit — a bass note and a melodic fragment suggest the chord. Minor 7th and minor 9th chords add jazzy sophistication. Diminished and augmented chords create tension in darker sub-genres.',
    modality: 'Predominantly minor. Natural minor and Phrygian for dark moods. Dorian for jazzy warmth. Major keys appear in pop-rap and conscious hip-hop for uplifting messages.',
  },

  songStructure: {
    overview: 'Verse-hook-verse is the backbone, but hip-hop has unique structural elements: the intro ad-lib, the beat switch, the freestyle section, and the outro. Modern hip-hop is increasingly free-form, with some tracks abandoning traditional structure entirely.',
    form: 'Intro – Verse 1 – Hook/Chorus – Verse 2 – Hook – Verse 3/Bridge – Hook – Outro',
    sections: ['Intro/Producer Tag', 'Verse 1', 'Hook/Chorus', 'Verse 2', 'Hook', 'Bridge/Beat Switch', 'Verse 3', 'Hook', 'Outro'],
    arrangement: 'Beat often starts sparse and adds elements. Beat switches mid-song are increasingly common. Verses may have different energy levels. The hook is usually shorter and more melodic than verses.',
    introOutro: 'Intros: producer tag, ad-lib, or atmospheric buildup. Outros: ad-libs fading out, beat riding, or spoken word. Some tracks start with the hook or a cappella bars.',
    barLengths: 'Verses: 16 bars (classic) or 12-24 bars. Hooks: 4-8 bars. Bridge: 4-8 bars. Modern tracks trend shorter (2-3 minutes for streaming).',
    hookPlacement: 'Hook appears after verse 1 (within first 30-45 seconds). Repetitive and melodic. May be sung or chanted rather than rapped. Ad-libs and vocal tags reinforce the hook.',
  },

  vocalDelivery: {
    overview: 'The MC is the star. Hip-hop vocal delivery encompasses an enormous range — from rapid-fire technical rapping to melodic singing, from aggressive bark to laid-back flow. "Flow" (the rhythmic pattern of the delivery against the beat) is the defining element.',
    phrasing: 'Rhythmically complex — phrases overlap bar lines, use internal rhyme schemes, and create polyrhythmic tension with the beat. Enjambment across bars. Triplet flows, double-time, half-time, and switching between them.',
    affect: 'Confident and assertive. Emotional range from braggadocio to vulnerability, aggression to introspection. Authenticity of expression is paramount.',
    techniques: [
      'Rapid-fire multi-syllabic rhyming',
      'Melodic rap (singing while rapping)',
      'Auto-Tune as stylistic tool (T-Pain, Future, Travis Scott)',
      'Aggressive bark/yelling delivery',
      'Laid-back mumble flow',
      'Triplet flow (Migos style)',
      'Staccato punch-in delivery',
      'Double and triple-time flows',
      'Breath control for long phrases',
    ],
    adlibStyle: 'Essential to hip-hop: "yeah!", "uh!", "skrrt!", "brr!", "let\'s go!", "what!", ad-libs run parallel to main vocals, filling gaps and adding energy. Producer and artist-specific tags. Background "yeah" and "uh-huh" affirmations.',
    harmony: 'Minimal in verses — the rapper\'s voice is usually solo. Hooks may feature melodic singing with harmony stacks. Background vocals mainly for ad-libs and emphasis. Some artists layer multiple vocal tracks for thickness.',
    grit: 'Varies widely — from clean and smooth (Drake, J. Cole) to extremely raspy and aggressive (DMX, Pop Smoke). Vocal distortion and processing used stylistically. Rawness is valued over perfection in many sub-genres.',
  },

  lyricalConventions: {
    overview: 'Hip-hop is the most lyrically dense genre in music. Wordplay, metaphor, storytelling, and rhyme complexity are core values. Lyrics range from braggadocio and party anthems to profound social commentary and confessional storytelling.',
    themes: [
      'Street life and survival',
      'Wealth, success, and materialism',
      'Social injustice and systemic racism',
      'Personal struggle and come-up stories',
      'Romantic relationships and heartbreak',
      'Party, drugs, and nightlife',
      'Self-reflection and mental health',
      'Competition and lyrical superiority',
      'Community and cultural pride',
    ],
    perspective: 'First person dominant. Autobiographical or character-based storytelling. Second person for confrontational tracks (diss, bravado). Third person for narrative storytelling.',
    figurativeLanguage: 'Rich and essential — extended metaphors, similes, double and triple entendres, punchlines, wordplay, allusions to pop culture, sports, and history. The cleverness of figurative language is a measure of MC skill.',
    vocabulary: 'Street vernacular, slang (era and region-specific), brand names, cultural references. Vocabulary ranges from academic (conscious rap) to raw street language (gangsta/drill). Code-switching between registers is a skill.',
    storytellingApproach: 'Can be cinematic and narrative (Kendrick, Nas) or impressionistic and vibe-based (Travis Scott, Playboi Carti). Battle rap prioritizes punchlines over narrative. Concept albums tell overarching stories.',
    cliches: [
      'Started from the bottom',
      'Real recognize real',
      'They don\'t want to see me win',
      'Money, power, respect',
      'Day ones / ride or die',
      'Drip/sauce/flex metaphors',
      'Coming for the throne/crown',
    ],
  },

  productionFingerprint: {
    overview: 'Producer-driven genre where the beatmaker is as important as the MC. Hip-hop production has evolved from sampling breaks on turntables to sophisticated DAW-based sound design, but the ethos remains: create a groove that demands movement.',
    mixAesthetic: 'Vocal-forward with heavy low end. The 808/bass should be felt physically. Crisp highs on hi-hats and snares. Vocals compressed and present, sitting on top of the beat. Aggressive limiting for loudness.',
    era: 'Current era: melodic rap dominance, trap production as default template, genre-blending (rage beats, pluggnb, Detroit type), shorter songs, beat switches.',
    signalChain: 'Beats: FL Studio or Ableton → Omnisphere/ElectraX/Kontakt for melodics → 808s from kits → drum programming → sidechain → master chain. Vocals: dynamic mic (SM7B) or condenser → preamp → compression → Auto-Tune → EQ → delay/reverb sends.',
    modernTrends: 'Pluggnb (plug + R&B), rage beats (hyperpop-influenced trap), Detroit/Flint type beats, sample drill, melodic drill, Afro-drill fusion. Increasing use of live instrumentation layered with electronic production.',
  },

  instrumentation: {
    coreInstruments: [
      '808 bass / sub-bass synthesizer',
      'Drum machine (TR-808, TR-909, MPC)',
      'Sampler (Akai MPC, SP-404)',
      'Synthesizer (Omnisphere, ElectraX, Nexus)',
      'Piano / Rhodes (sampled or live)',
      'Turntables / DJ controller',
    ],
    signatureSounds: [
      'Roland TR-808 cowbell',
      'Vinyl scratching',
      'Producer tags ("Metro Boomin want some more")',
      'Pitched soul vocal samples',
      'Orchestral hits',
      'Glass breaking / gun sounds (drill)',
      'Flute melodies (trap)',
    ],
    layering: 'Minimal — hip-hop beats typically use 4-8 elements. Space is left for the vocal. Melodic layers are usually a single loop or sample. Drums are the most layered element (kick + sub, snare + clap, multiple hi-hat patterns).',
    avoidInstruments: [
      'Excessive live band instrumentation (unless jazz rap)',
      'Classical orchestral arrangements (unless cinematic hip-hop)',
      'Bright acoustic guitars (too folk/country)',
      'Cheesy synth presets',
      'Overly clean, sterile sounds',
    ],
  },

  culturalContext: {
    overview: 'Hip-hop is a culture, not just a genre. It encompasses four elements: MCing, DJing, breakdancing, and graffiti. Born from Black and Latino communities in the Bronx, it has become the most consumed genre globally while remaining rooted in the struggle and creativity of marginalized communities.',
    origin: 'South Bronx, New York City, early 1970s. DJ Kool Herc\'s block parties, extending the break sections of funk and soul records for dancers. Afrika Bambaataa codified the four elements.',
    identity: 'Hip-hop is inseparable from Black American culture, representing both survival and celebration. Regional identity (East Coast, West Coast, South, Midwest) has historically defined sounds and rivalries.',
    community: 'Deeply community-oriented — local scenes, cyphers, open mics, and block parties. Modern community exists on social media, streaming platforms, and hip-hop media (Complex, XXL, Worldstar). Collaboration is central.',
    socialFunction: 'Voice of the voiceless — hip-hop articulates experiences of poverty, racism, violence, and aspiration. Also functions as party music, competitive sport, and cultural commentary. Defines youth culture globally.',
    authenticityMarkers: [
      'Keeping it real — lived experience matching lyrical content',
      'Respect for hip-hop history and pioneers',
      'Lyrical skill and flow mastery',
      'Street credibility (varies by sub-genre)',
      'Originality of style and sound',
      'Community reciprocity',
    ],
  },

  historicalLineage: {
    overview: 'From block parties to billion-stream releases, hip-hop has evolved from a local New York phenomenon to the dominant global genre in under 50 years.',
    roots: ['Funk', 'Soul', 'Disco', 'Jamaican Sound System culture', 'Spoken Word/Poetry', 'The Blues'],
    evolution: 'From turntablism and party raps (70s) to golden age lyricism (80s-90s) to regional diversification (2000s) to the streaming-era dominance of trap and melodic rap (2010s-present).',
    keyEras: [
      '1973-1979: Block party origins and early recordings',
      '1980-1984: Old school — Run-DMC, Grandmaster Flash',
      '1986-1996: Golden Age — Rakim, Nas, Wu-Tang, Biggie, Pac',
      '1997-2004: Shiny suit era and regional explosion',
      '2005-2012: Ringtone era, blog rap, and Kanye revolution',
      '2013-present: Trap dominance, SoundCloud rap, streaming era',
    ],
    influencedBy: ['Funk', 'Soul', 'Jazz', 'Reggae/Dancehall', 'Rock', 'Electronic Music'],
    influenced: ['Pop', 'R&B', 'EDM', 'Rock', 'Country (trap country)', 'Latin (Latin trap)', 'Global music'],
  },

  subGenres: [
    {
      name: 'Trap',
      description: 'Hard-hitting, bass-heavy hip-hop defined by rolling hi-hats, deep 808s, and dark atmospheric melodies. Originated in Atlanta\'s drug culture and became the dominant hip-hop sound globally.',
      distinguishingFeatures: ['Rolling hi-hat patterns (16th/32nd notes, triplets)', 'Deep 808 bass with glide/slides', 'Dark, minor-key melodies', 'Half-time snare on beat 3', 'Ad-lib heavy vocals'],
      bpmRange: { min: 130, max: 170 },
      keyArtists: ['Future', 'Young Thug', 'Gucci Mane', 'Migos', 'Travis Scott', '21 Savage'],
      productionNotes: 'Layer hi-hats with varying velocities and patterns. 808 bass should be distorted and prominent. Use dark pads and atmospheric synths. Sparse arrangements with heavy low end.',
      lyricNotes: 'Street life, hustle, drugs, money, violence, flexing. Melodic hooks. Heavy use of ad-libs and vocal effects.',
      sunoPromptKeywords: ['trap', 'Atlanta trap', '808 bass', 'rolling hi-hats', 'dark trap', 'hard trap', 'trap beat'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Rigid hi-hat grid with human vocal float — the beat is machine-precise while the rapper rides loosely on top',
          aheadBehindBeat: 'Half-time snare on 3 creates illusion of half-tempo swagger; hi-hats race at double time above',
          humanizationMarkers: ['Hi-hat velocity variations creating rolls', '808 glide/slide between notes', 'Triplet hi-hat patterns as signature rhythmic device'],
        },
        regionalDialectSpecificity: {
          accentInfluence: 'Atlanta drawl is the default trap accent — elongated vowels, melodic speech patterns, Southern laziness',
          phoneticMarkers: ['Elongated vowels ("way-uh" for "way")', 'Dropped final consonants', 'Melodic vocal runs replacing clear diction'],
          dialectVocabulary: ['drip', 'cap/no cap', 'slatt', 'it\'s lit', 'bussin', 'ice'],
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Half-time illusion — 140 BPM hi-hats feel like 70 BPM due to the snare landing on beat 3; the body nods at half the speed',
          weightAndMomentum: 'Maximum 808 weight — the bass is physical, felt in the chest and car subwoofers; momentum is heavy and gravitational',
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Sustained 808 tails fill the low end continuously — silence exists only in the high frequencies between hi-hat patterns',
          whatIsDeliberatelyAbsent: ['Acoustic instruments', 'Complex chord progressions', 'Silence in the low end', 'Vintage warmth'],
        },
      },
    },
    {
      name: 'Boom Bap',
      description: 'The classic hip-hop sound — sample-based beats with prominent kick and snare patterns, jazzy/soulful samples, and emphasis on lyrical skill. The heartbeat of Golden Age hip-hop.',
      distinguishingFeatures: ['Sampled drum breaks with swing', 'Chopped soul/jazz/funk samples', 'Prominent boom-bap kick-snare pattern', 'Vinyl crackle and lo-fi texture', 'Emphasis on bars and lyricism'],
      bpmRange: { min: 85, max: 100 },
      keyArtists: ['Nas', 'Wu-Tang Clan', 'MF DOOM', 'Joey Bada$$', 'Rapsody', 'Griselda'],
      productionNotes: 'Sample-based production — chop soul, jazz, and funk records. MPC-style drum programming with swing. Add vinyl noise and lo-fi texture. Keep it raw and unpolished.',
      lyricNotes: 'Lyrical complexity is king — wordplay, metaphors, storytelling, punchlines. Social commentary, battle bars, street narratives. Dense rhyme schemes.',
      sunoPromptKeywords: ['boom bap', '90s hip-hop', 'classic hip-hop', 'jazzy samples', 'golden age', 'lyrical rap', 'old school'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'MPC swing — the unquantized, humanized groove of sampling on hardware; J Dilla\'s drunk-feel timing is the holy grail',
          quantizationDeviation: 'High — the swing and timing imprecision from MPC programming is the soul of the sound',
          humanizationMarkers: ['MPC pad velocity variations', 'Chopped sample timing drift', 'Kick-snare swing creating head-nod groove'],
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Crate-digging culture — knowing the original soul, jazz, and funk records being sampled is essential cultural currency',
          samplingTradition: 'Sample-based production is foundational — the art is in selection, chopping, and recontextualizing source material',
          expectedReferences: ['Golden Age producers (Premier, Pete Rock, RZA)', 'James Brown breaks', 'Jazz and soul sample sources'],
          lineageSignifiers: ['SP-1200 crunch', 'MPC swing', 'Vinyl crackle as warmth', 'Head-nod groove'],
        },
        mistakeConventions: {
          authenticRoughness: 'Lo-fi IS the aesthetic — vinyl noise, tape hiss, and low-bitrate sampling are features, not limitations',
          overproductionRisks: ['Crystal-clear digital production', 'Auto-tune', 'Trap hi-hats', 'Modern 808 bass (wrong era)'],
          celebratedFlaws: ['Vinyl pops and crackle', 'Sample artifacts from chopping', 'Off-grid drum hits from MPC performance'],
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Silence between kick and snare hits IS the groove — boom (space) bap (space); the air between hits matters',
          dynamicContrast: 'Moderate — the beat knocks hard but leaves room for the MC to fill with dense bars',
        },
      },
    },
    {
      name: 'Drill',
      description: 'Dark, aggressive, and minimalist. Originated in Chicago, evolved in the UK and Brooklyn. Characterized by sliding 808s, sparse drums, and unflinching street narratives.',
      distinguishingFeatures: ['Sliding/gliding 808 bass patterns', 'Sparse, menacing drum patterns', 'Dark orchestral or piano melodies', 'Aggressive, conversational delivery', 'UK drill uses distinctive snare patterns'],
      bpmRange: { min: 135, max: 145 },
      keyArtists: ['Chief Keef', 'Pop Smoke', 'Fivio Foreign', 'Central Cee', 'Headie One'],
      productionNotes: 'Sliding 808s are essential. Dark piano or string melodies. Sparse drums — kick and snare with minimal hi-hat. UK drill uses a distinctive bouncing snare pattern.',
      lyricNotes: 'Raw street narratives, violence, territorial pride. Direct and conversational delivery. UK drill uses distinct British slang and references.',
      sunoPromptKeywords: ['drill', 'UK drill', 'Chicago drill', 'sliding 808s', 'dark drill', 'aggressive', 'street rap'],
      embodiedDelta: {
        regionalDialectSpecificity: {
          accentInfluence: 'Three distinct dialects: Chicago (flat Midwest aggression), UK (London multicultural English), Brooklyn (NYC grit) — each is a different genre',
          phoneticMarkers: ['Chicago: flat vowels, clipped delivery', 'UK: London MLE accent, Jamaican patois influence', 'Brooklyn: NYC rapid-fire, Pop Smoke\'s gravelly rasp'],
          dialectVocabulary: ['opps', 'lacking', 'scoring', 'woi (UK)', 'ting (UK)', 'on timing'],
          regionWithinCulture: 'Hyper-territorial — specific neighborhoods, blocks, and postcodes define identity; music from the wrong area is rejected',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Menacing mid-tempo — 140 BPM feels slow and threatening due to sparse drum placement and sliding 808s',
          weightAndMomentum: 'Heavy and lurching — the sliding 808s create a stalking, predatory momentum',
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Sparse and quantized — drums are deliberately minimal; the sliding 808 bass does the rhythmic work',
          aheadBehindBeat: 'UK drill: bouncing snare pattern pushes forward; Chicago drill: everything sits on or behind the beat',
        },
        performancePractice: {
          crowdInteraction: 'Territorial and masked — performers often wear balaclavas; crowd energy is aggressive and tribal',
          stagePresence: 'Group performance with crew — multiple MCs trading bars, collective presence signals strength in numbers',
        },
      },
    },
    {
      name: 'Lo-Fi Hip-Hop',
      description: 'Chill, atmospheric, and nostalgic. Instrumental-focused hip-hop designed for studying, relaxing, and vibing. Characterized by degraded audio quality, jazz samples, and mellow grooves.',
      distinguishingFeatures: ['Intentionally degraded audio quality', 'Jazz piano and guitar samples', 'Mellow, swung drum patterns', 'Vinyl crackle and tape hiss', 'Rain/nature ambient sounds'],
      bpmRange: { min: 70, max: 90 },
      keyArtists: ['Nujabes', 'J Dilla', 'Knxwledge', 'Tomppabeats', 'idealism'],
      productionNotes: 'Chop jazz samples with swing. Add vinyl noise, tape wobble, bitcrushing. Mellow drums with heavy swing. Sidechain the sample to the kick. Ambient textures in the background.',
      lyricNotes: 'Often instrumental. When vocals present: introspective, philosophical, mellow. Sampled spoken word or movie dialogue clips.',
      sunoPromptKeywords: ['lo-fi hip-hop', 'chill beats', 'study music', 'jazzy lo-fi', 'boom bap lo-fi', 'relaxing', 'mellow'],
      embodiedDelta: {
        mistakeConventions: {
          authenticRoughness: 'Degradation IS the entire aesthetic — tape wobble, bitcrushing, vinyl noise, and low sample rates are the production palette',
          toleratedImperfections: ['Pitch drift from tape emulation', 'Bitcrushed artifacts', 'Sample timing wandering', 'Room noise and ambient bleed'],
          celebratedFlaws: ['Vinyl surface noise as warmth', 'Tape hiss as atmosphere', 'Off-grid timing as chill factor', 'Low-bitrate crunch as character'],
          overproductionRisks: ['Crystal-clear digital quality', 'Perfect timing', 'High-fidelity anything', 'Aggressive mixing or mastering'],
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Space is the primary instrument — room between notes creates the chill factor; density kills the mood',
          dynamicContrast: 'Very low — everything sits in a warm, even, comfortable dynamic range; no surprises',
          whatIsDeliberatelyAbsent: ['Aggressive energy', 'Loud dynamics', 'Complex arrangements', 'Vocal presence (usually)'],
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Dilla-influenced haze — timing wanders intentionally, creating a drowsy, dream-like groove',
          quantizationDeviation: 'Maximum — the unquantized feel is the genre\'s signature; grid-aligned lo-fi is a contradiction',
        },
        callAndResponse: {
          vocalInstrumentalDialogue: 'No MC dialogue — the beat talks to itself; sampled vocal snippets respond to instrumental phrases',
          patterns: ['Piano sample responds to drum pattern', 'Rain/ambient sounds fill vocal space', 'Movie dialogue samples as emotional punctuation'],
        },
      },
    },
    {
      name: 'Cloud Rap',
      description: 'Ethereal, atmospheric, and hazy. Characterized by reverb-drenched beats, dreamy synths, and laid-back vocals. The aesthetic is spacey and detached.',
      distinguishingFeatures: ['Heavy reverb and delay on everything', 'Dreamy, spacious synth pads', 'Slow, hazey tempo', 'Detached, mumbled vocal delivery', 'Pastel/vaporwave aesthetic'],
      bpmRange: { min: 60, max: 80 },
      keyArtists: ['Lil B', 'A$AP Rocky', 'Yung Lean', 'Bladee', 'Clams Casino'],
      productionNotes: 'Reverb everything. Spacious, ambient pads. Slow tempo. Pitched vocal samples. Glitchy effects. Keep it dreamy and ethereal.',
      lyricNotes: 'Stream of consciousness, abstract, detached. Materialism mixed with melancholy. Internet culture references.',
      sunoPromptKeywords: ['cloud rap', 'atmospheric rap', 'dreamy hip-hop', 'ethereal trap', 'spacey', 'hazy', 'reverb-heavy'],
    },
    {
      name: 'Conscious Hip-Hop',
      description: 'Socially and politically aware hip-hop that addresses systemic issues, Black identity, spirituality, and community empowerment. Prioritizes message and lyricism.',
      distinguishingFeatures: ['Socially conscious messaging', 'Complex lyricism and wordplay', 'Jazz and soul-influenced production', 'Live instrumentation', 'Concept-driven albums'],
      bpmRange: { min: 80, max: 110 },
      keyArtists: ['Kendrick Lamar', 'J. Cole', 'Common', 'Talib Kweli', 'Noname', 'Black Thought'],
      productionNotes: 'Soulful, jazz-influenced beats. Live instruments blended with electronic production. Warm, organic sound. Production serves the message.',
      lyricNotes: 'Social commentary, racial justice, personal growth, spirituality, community. Complex rhyme schemes and extended metaphors. Storytelling and concept tracks.',
      sunoPromptKeywords: ['conscious hip-hop', 'woke rap', 'lyrical rap', 'soulful hip-hop', 'jazz rap', 'intelligent rap', 'message rap'],
      embodiedDelta: {
        socioeconomicSubtext: {
          materialConditions: 'Explicit political text — systemic racism, mass incarceration, police violence, economic inequality are addressed directly',
          classIdentity: 'Black intellectual tradition — connecting street experience to broader political analysis',
          politicalUndercurrent: 'The political IS the surface text — not subtext but direct engagement with power structures',
          implicitReferences: ['W.E.B. Du Bois', 'Malcolm X', 'James Baldwin', 'Angela Davis', 'Black Panthers'],
        },
        genderAndBodyConventions: {
          genderNarratives: 'Expanded masculinity — vulnerability, fatherhood, emotional complexity alongside strength; rejecting one-dimensional hardness',
          subversionExamples: ['Kendrick Lamar\'s vulnerability on "u"', 'J. Cole as thoughtful masculinity', 'Noname centering Black feminism in hip-hop spaces'],
        },
        performancePractice: {
          crowdInteraction: 'Pedagogical — the performer educates and elevates; call-and-response used to build collective consciousness',
          whatMakesAGoodShow: 'When the audience leaves thinking differently — entertainment serves transformation',
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Literary and political canon alongside musical — James Baldwin, Toni Morrison, and Malcolm X are as important as Rakim and KRS-One',
          lineageSignifiers: ['Last Poets spoken word tradition', 'Gil Scott-Heron proto-rap', 'Public Enemy militancy', 'Kendrick Lamar\'s TPAB as modern benchmark'],
        },
      },
    },
    {
      name: 'Gangsta Rap',
      description: 'Raw, unfiltered narratives of street life, violence, and survival. Hard-hitting beats with aggressive delivery. A founding pillar of hip-hop culture.',
      distinguishingFeatures: ['Aggressive, confrontational delivery', 'G-funk synthesizers (West Coast)', 'Hard-hitting drum patterns', 'Street narrative storytelling', 'Explicit content'],
      bpmRange: { min: 85, max: 105 },
      keyArtists: ['N.W.A', 'Tupac', 'Notorious B.I.G.', 'Snoop Dogg', 'Ice Cube', '50 Cent'],
      productionNotes: 'West Coast: G-funk synths, whine leads, deep bass. East Coast: hard drums, dark samples. Both: heavy bass, prominent drums, cinematic production.',
      lyricNotes: 'Street life, violence, hustling, loyalty, betrayal, survival. Autobiographical or character-driven storytelling. Raw and unfiltered.',
      sunoPromptKeywords: ['gangsta rap', 'g-funk', 'west coast', 'hardcore rap', 'street rap', 'gangster', 'thug'],
    },
    {
      name: 'Jazz Rap',
      description: 'Hip-hop infused with jazz harmonies, instrumentation, and improvisation. Sophisticated production with complex chord changes and live musicianship.',
      distinguishingFeatures: ['Jazz samples or live jazz instrumentation', 'Complex chord progressions', 'Upright bass and jazz drums', 'Sophisticated, literary lyricism', 'Improvisational elements'],
      bpmRange: { min: 80, max: 105 },
      keyArtists: ['A Tribe Called Quest', 'The Roots', 'Robert Glasper', 'Anderson .Paak', 'Guru'],
      productionNotes: 'Real jazz instruments or high-quality jazz samples. Complex harmonies (7ths, 9ths, 13ths). Swung drums with brush or ride cymbal. Upright bass. Keep it warm and organic.',
      lyricNotes: 'Intellectual, poetic, philosophical. Cultural commentary. Positive messaging. Complex vocabulary and literary references.',
      sunoPromptKeywords: ['jazz rap', 'jazz hip-hop', 'jazzy beats', 'live instruments', 'sophisticated', 'neo-soul hip-hop'],
    },
    {
      name: 'Phonk',
      description: 'Dark, Memphis-influenced hip-hop built on chopped vocals, heavy bass, and horror movie aesthetics. Combines 90s Memphis rap with modern production and drift culture.',
      distinguishingFeatures: ['Chopped and screwed vocal samples', 'Heavy distorted bass', 'Cowbell patterns', 'Horror/occult aesthetic', 'Drift racing culture connection'],
      bpmRange: { min: 130, max: 160 },
      keyArtists: ['DJ Smokey', 'Kordhell', 'PHONK WALKER', 'Freddie Dredd', 'Ghostface Playa'],
      productionNotes: 'Chop Memphis rap vocal samples. Heavy distorted 808s. Cowbell and crash patterns. Dark, horror-movie atmospherics. Lo-fi distortion throughout.',
      lyricNotes: 'Dark themes — horror, occult, violence, nihilism. Memphis rap influences. Often instrumental or using chopped vocal samples.',
      sunoPromptKeywords: ['phonk', 'Memphis phonk', 'drift phonk', 'dark phonk', 'cowbell', 'chopped vocals', 'aggressive bass'],
      embodiedDelta: {
        intertextualityAndSampling: {
          canonKnowledge: 'Memphis cassette tape canon — Three 6 Mafia, DJ Screw, Tommy Wright III are sacred source material',
          samplingTradition: 'Chopping and screwing 90s Memphis rap vocals is the primary technique; the sample IS the genre',
          lineageSignifiers: ['Three 6 Mafia vocal chops', 'DJ Screw slowed-down technique', 'Memphis horrorcore aesthetic', 'Cowbell as Memphis signifier'],
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Cowbell-driven mechanical pulse — the persistent cowbell pattern creates a driving, automotive urgency',
          aheadBehindBeat: 'On the grid — phonk is machine-precise; the mechanical feel is intentional, not a limitation',
        },
        mistakeConventions: {
          authenticRoughness: 'Cassette tape degradation is essential — the lo-fi quality of Memphis tapes being dubbed and re-dubbed is the sonic identity',
          celebratedFlaws: ['Tape saturation and distortion', 'Low-bitrate vocal samples', 'Clipping bass', 'Audible tape hiss'],
          overproductionRisks: ['Clean, hi-fi production', 'Modern vocal clarity', 'Polished mastering', 'Removing the grit'],
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Forward-driving momentum — 140+ BPM with cowbell creates automotive energy; the music is designed for speed and aggression',
          urgencyScale: '8/10 — relentless forward drive, the cowbell never stops pushing',
        },
      },
    },
    {
      name: 'Emo Rap',
      description: 'Emotionally vulnerable hip-hop blending rap with emo, punk, and rock elements. Characterized by confessional lyrics about depression, heartbreak, and substance abuse.',
      distinguishingFeatures: ['Emo/punk guitar melodies', 'Singing-rapping hybrid delivery', 'Confessional, vulnerable lyrics', 'Lo-fi or grunge-influenced production', 'SoundCloud era aesthetic'],
      bpmRange: { min: 75, max: 170 },
      keyArtists: ['Juice WRLD', 'Lil Peep', 'XXXTentacion', 'nothing,nowhere.', 'Trippie Redd'],
      productionNotes: 'Blend guitar melodies (clean or distorted) with trap drums. Emotional piano or guitar leads. 808 bass with rock energy. Vocals with reverb and light distortion.',
      lyricNotes: 'Mental health, heartbreak, substance abuse, alienation, loneliness. Confessional and vulnerable. Raw emotional honesty over technical complexity.',
      sunoPromptKeywords: ['emo rap', 'sad rap', 'emotional hip-hop', 'emo trap', 'SoundCloud rap', 'melodic emo', 'rap rock'],
    },
    {
      name: 'Crunk',
      description: 'High-energy, aggressive Southern hip-hop designed for clubs and parties. Characterized by heavy bass, call-and-response chants, and raw energy.',
      distinguishingFeatures: ['Heavy, distorted bass drops', 'Call-and-response chants', 'Aggressive energy', 'Simple, repetitive hooks', 'Club-oriented production'],
      bpmRange: { min: 75, max: 85 },
      keyArtists: ['Lil Jon', 'Three 6 Mafia', 'Ying Yang Twins', 'Crime Mob'],
      productionNotes: 'Heavy bass with distortion. Simple, aggressive drum patterns. Synth stabs. Crowd chant vocals. High energy throughout. Minimal melodic elements.',
      lyricNotes: 'Party, clubs, getting hyped. Simple, chant-based hooks. Call-and-response dynamics. Aggressive energy over lyrical complexity.',
      sunoPromptKeywords: ['crunk', 'club rap', 'southern hip-hop', 'hype', 'bass heavy', 'party rap', 'aggressive club'],
    },
    {
      name: 'Mumble Rap',
      description: 'Melodic, vibe-driven hip-hop where vocal melody and flow take precedence over lyrical clarity. Characterized by Auto-Tune, repetitive hooks, and atmospheric production.',
      distinguishingFeatures: ['Heavy Auto-Tune processing', 'Melodic, sung delivery', 'Repetitive, catchy hooks', 'Vibe over lyrical content', 'Trap production foundation'],
      bpmRange: { min: 130, max: 160 },
      keyArtists: ['Playboi Carti', 'Lil Uzi Vert', 'Young Thug', 'Gunna', 'Lil Baby'],
      productionNotes: 'Atmospheric trap beats. Heavy Auto-Tune on vocals. Spacious, reverb-heavy production. Melodic synth loops. 808s as the primary melodic bass element.',
      lyricNotes: 'Vibe-focused — lyrics serve the melody and flow rather than conveying complex messages. Flexing, lifestyle, relationships. Repetitive hooks.',
      sunoPromptKeywords: ['melodic rap', 'Auto-Tune rap', 'mumble rap', 'vibe rap', 'melodic trap', 'catchy rap', 'sing-rap'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Hip-hop is the most consumed genre in the world. Its audience spans every demographic, though its core remains young (16-34), urban, and culturally engaged. Hip-hop culture extends far beyond music into fashion, language, art, and politics.',
    fanExpectations: [
      'Authenticity — keeping it real',
      'Lyrical skill and clever wordplay',
      'Hard-hitting production and bass',
      'Cultural relevance and trendsetting',
      'Visual identity (music videos, fashion)',
      'Consistent output and presence',
      'Collaboration with respected peers',
    ],
    gatekeeping: 'Moderate to high — debates about "real hip-hop" are constant. Lyrical purists vs. vibe/melody fans. Generational divides (boom bap vs. trap). Cultural appropriation debates. Regional loyalty.',
    livePerformance: 'High energy — crowd participation, call-and-response, mosh pits (rage culture). DJ sets, hype men, and backing tracks are standard. Freestyle and cypher culture. Festival headlining is the pinnacle.',
    fashionAndAesthetic: 'Hip-hop defines streetwear and luxury fashion. Sneaker culture, designer brands, jewelry (chains, grills). Regional variations: Southern oversized fits, NYC streetwear, LA casual luxury.',
    crossoverPotential: 'Maximum — hip-hop has become the default foundation for pop, blending with every genre from country (Lil Nas X) to rock (Post Malone) to Latin (Bad Bunny) to EDM.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Micro-timing is hip-hop\'s secret weapon. From J Dilla\'s "drunk drums" that land fractionally off-grid to the metronomic precision of trap hi-hats, the genre uses time manipulation as an expressive tool. The MC\'s flow — how syllables land against the beat — is the most analyzed micro-timing relationship in any music.',
    quantizationDeviation: 'Boom bap: heavy MPC swing (55-70% shuffle), drums intentionally off-grid. Trap: hi-hats are rigidly quantized to 32nd-note grid but velocity creates micro-dynamics. Dilla-style: each drum hit placed individually, no two bars identical, creating a "breathing" beat.',
    aheadBehindBeat: 'Vocal flow is the primary micro-timing expression. Behind-the-beat flow (Snoop Dogg, 21 Savage) creates a laid-back, effortless cool. On-the-beat flow (Eminem, Busta Rhymes) creates urgency and technical precision. Trap flows sit slightly ahead of the snare for aggressive forward momentum.',
    humanizationMarkers: [
      'MPC finger-drummed patterns with velocity variation',
      'SP-404 chops with slightly misaligned start points',
      'Dilla-style unquantized kick placement',
      'Vocal breath timing between bars',
      'Subtle tempo drift in sampled loops from vinyl source',
    ],
    genreSpecificFeel: 'The concept of "pocket" in hip-hop is different from jazz or funk — it\'s about the relationship between the rapper\'s syllable placement and the snare/kick pattern. A great MC rides the beat like a surfer, sometimes catching the wave early, sometimes trailing behind it. The best producers leave deliberate space in the beat for this interplay.',
  },

  silenceAndSpace: {
    overview: 'Hip-hop production is fundamentally about what you leave out. The sparse, bass-heavy aesthetic relies on negative space to give weight to each element. The beat breathes around the vocal, and silence between bars creates anticipation.',
    negativeSpaceRole: 'Space is structural — boom bap beats use silence between drum hits to create head-nod groove. Trap uses sparse melodic loops with vast open space filled only by 808 bass. The emptiness gives each element room to impact physically. Producers like Metro Boomin and Madlib are masters of leaving space.',
    breathingPatterns: 'Bars breathe in 4- or 8-bar cycles. The beat often drops elements during verses to leave room for the MC, then fills out during hooks. Beat drops (complete silence before a bass hit) are moments of maximum impact. The breath between an MC\'s bars is rhythmically significant.',
    dynamicContrast: 'Extreme — hip-hop has the widest dynamic range in popular music between sparse verse beats and maximalist hooks. The bass drop from silence to full 808 is a defining dynamic gesture. Some producers (Kanye, Tyler) use complete silence for 1-2 beats as dramatic effect.',
    whatIsDeliberatelyAbsent: [
      'Sustained harmonic pads in verse sections',
      'Continuous melodic movement (loops are short and repetitive)',
      'Drum fills and transitions (beats often cut rather than transition)',
      'Bass activity during vocal-heavy passages',
      'Reverb tails (kept short to maintain punch)',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response in hip-hop descends from African and African American oral traditions but has evolved into unique forms: MC-and-crowd, MC-and-DJ, verse-and-ad-lib, and the conversational back-and-forth of rap battles and cyphers.',
    vocalInstrumentalDialogue: 'The MC and the beat are in constant dialogue — vocal phrases fill spaces between drum hits, and drum patterns punctuate vocal lines. The scratch DJ responds to the MC\'s bars. In sample-based production, the chopped vocal sample "speaks" to the rapper.',
    sectionInternal: 'Ad-libs function as a second voice responding to the primary flow — "yeah," "uh," "skrrt" affirm and punctuate bars. Hype men (Flavor Flav, DJ Khaled) provide live call-and-response. Double-tracked vocals on punchlines create self-response.',
    audienceParticipation: 'Central to live hip-hop. "When I say __, you say __" is a structural element. Crowd participation in hooks. Mosh pits triggered by specific sonic cues (bass drops, "let\'s go"). The cypher format is pure call-and-response, each MC responding to the last.',
    patterns: [
      'MC delivers bar, ad-lib responds ("bars!" "sheesh!" "facts!")',
      'Hook call-and-response with crowd participation',
      'DJ scratch responding to vocal phrase',
      'Beat drop after vocal buildup',
      'Verse-chorus as extended call-and-response',
      'Battle rap: bar-for-bar exchange',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Hip-hop is the most regionally specific genre in contemporary music. Dialect, slang, and accent are identity markers — you can locate an MC\'s origin within one verse. Regional sound and language are inseparable from regional production style.',
    phoneticMarkers: [
      'New York: clipped consonants, hard "r" dropping, nasal vowels ("deadass," "brick")',
      'Atlanta: Southern drawl, elongated vowels, melodic phrasing ("cap," "bussin")',
      'Chicago: Midwest flat vowels, drill-specific terminology ("on gang," "smoking on")',
      'LA: West Coast casual cadence, Chicano English influence ("cuh," "on Crip")',
      'Houston: chopped-and-screwed slow drawl, "nawmsayin"',
    ],
    accentInfluence: 'Accent defines flow. Southern drawl naturally lends itself to melodic, behind-the-beat delivery. New York\'s percussive consonants suit aggressive, on-beat boom bap. UK drill\'s London accent creates a completely distinct rhythmic feel from Chicago drill over similar production.',
    dialectVocabulary: [
      '"Jawn" (Philadelphia — any noun)',
      '"Brick" (NYC — very cold)',
      '"Finna" (Southern/Midwest — about to)',
      '"Hella" (Bay Area — very)',
      '"No cap" (Atlanta — no lie)',
      '"Aye" (Chicago — hey/attention marker)',
    ],
    regionWithinCulture: 'Regional identity is a core axis of hip-hop authenticity. Repping your city/block/set is expected. Regional beefs (East/West, regional sound rivalries) have shaped the genre\'s history. Even as the internet homogenizes sound, regional slang and production preferences persist.',
  },

  performancePractice: {
    overview: 'Hip-hop live performance is a distinct art form — part concert, part athletic event, part communal ritual. The MC commands the stage with physicality, crowd control, and charisma. The live experience is about energy transfer between performer and audience.',
    improvisationConventions: 'Freestyling (improvised rapping) is the genre\'s ultimate demonstration of skill. Cyphers — circles of MCs trading improvised verses — are hip-hop\'s jam sessions. Battle rap is structured improvised competition. Live shows may include freestyle sections, but most performances are rehearsed delivery of recorded material.',
    crowdInteraction: 'The MC is a crowd conductor — directing mosh pits, call-and-response chants, phone lights, and singalongs. "Make some noise!" is a structural element. Crowd energy is reciprocal — a dead crowd kills the performance. Stage diving, crowd surfing, and "rage" culture are contemporary norms.',
    stagePresence: 'Commanding, confident, larger-than-life. The MC must own the stage. Physical movement ranges from pacing and gesturing (lyrical MCs) to full athletic performance (Travis Scott, Playboi Carti). A hype man or DJ flanks the MC. Chains, fashion, and visual swagger are part of the performance.',
    livVsRecordedDifferences: 'Significant — recorded hip-hop is studio-crafted with layers, effects, and precision. Live hip-hop strips this back: backing tracks provide the beat, the MC performs vocals live (sometimes with backing track vocals). Energy replaces polish. The crowd becomes an instrument.',
    whatMakesAGoodShow: 'Energy and crowd control. The MC must read the room and adjust — hype the crowd, slow it down, create moments of collective euphoria. Setlist flow matters (build energy, peak, cool down). The best shows feel like a shared experience, not a one-way performance.',
  },

  socioeconomicSubtext: {
    overview: 'Hip-hop was born from economic deprivation in the South Bronx — poverty, disinvestment, and systemic racism created the conditions for the genre\'s emergence. Socioeconomic reality is not subtext in hip-hop; it is the text. The music is an ongoing dialogue about material conditions in Black and brown America.',
    materialConditions: 'From Grandmaster Flash\'s "The Message" to Kendrick\'s "HUMBLE," hip-hop chronicles life under economic pressure: project housing, food insecurity, lack of healthcare, underfunded schools. Trap music narrates the street economy as rational response to joblessness. Wealth display (flex culture) represents escape from poverty, not ignorance of it.',
    classIdentity: 'Hip-hop\'s relationship to class is complex — artists move from poverty to wealth while maintaining street credibility. The "come-up" narrative (rags to riches) is central. Conspicuous consumption is both celebration and critique. Working-class identity coexists with aspirational luxury.',
    politicalUndercurrent: 'Ranges from explicitly political (Public Enemy, Kendrick Lamar, Killer Mike) to implicitly political (the very existence of successful Black artists from poverty is political). Police brutality, mass incarceration, redlining, and educational inequality are recurring themes. Even apolitical party rap exists within a political context.',
    implicitReferences: [
      'Trap houses as markers of the informal economy',
      'Designer brands as class mobility symbols',
      'Geographic references (projects, blocks) as socioeconomic shorthand',
      'Gun references reflecting real community violence',
      '"Started from the bottom" narratives as class consciousness',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Sampling IS hip-hop\'s founding artistic principle. DJs looping breaks from funk and soul records created the genre. This practice of building new art from existing art is hip-hop\'s most distinctive creative act — a postmodern collage tradition with roots in African American musical recycling and signifying.',
    canonKnowledge: 'Deep familiarity with the sample canon is expected: James Brown breaks, Parliament-Funkadelic bass lines, Isaac Hayes orchestration, Motown vocals. Producers are judged on their "crate-digging" — unearthing obscure records. MCs reference previous rappers, lyrics, and flows as homage and competition.',
    samplingTradition: 'From Marley Marl discovering sampling to Kanye\'s chipmunk soul to Madlib\'s abstract collages, sampling is hip-hop\'s primary compositional method. Legal clearance issues have pushed producers toward original composition, but the aesthetic of sampling (chopping, looping, flipping) persists even in original production.',
    quotationPractice: 'Lyrical quotation is constant — rappers reference famous lines, flip classic hooks, and interpolate melodies. This is "signifying" — a Black literary tradition of referencing and revising predecessors. Ghostface quoting Raekwon, Kendrick channeling 2Pac, Drake singing Aaliyah — all are intertextual acts.',
    expectedReferences: [
      'James Brown "Funky Drummer" and "The Big Payback"',
      'Notorious B.I.G. and 2Pac as foundational texts',
      'Wu-Tang Clan\'s impact on East Coast lyricism',
      'Kanye West\'s production innovations',
      'The Isley Brothers, Curtis Mayfield, and Stevie Wonder as sample sources',
    ],
    lineageSignifiers: [
      'Producer tags that reference mentors ("Metro Boomin want some more")',
      'Sample flips that pay homage to the source',
      'Name-dropping respected MCs in lyrics',
      'Rapping over classic beats as tribute',
      'Album skits referencing hip-hop history',
      'Cover art homaging iconic album designs',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Hip-hop encodes specific gender expectations in vocal delivery, physical performance, and lyrical content. These conventions have shifted substantially over the genre\'s history, with recent decades seeing expanded expression — though traditional frameworks remain influential.',
    vocalGenderCodes: 'Male vocal norms range from deep, aggressive bark (DMX, Pop Smoke) to melodic crooning (Drake, Post Malone). Female MCs navigate between matching masculine aggression (Foxy Brown, Megan Thee Stallion) and distinctly feminine delivery (Lauryn Hill, Nicki Minaj\'s alter egos). Auto-Tune has blurred gendered vocal expectations.',
    physicalityInPerformance: 'Male performance emphasizes dominance — chest-out posture, aggressive gesturing, crowd commanding. Female performance navigates between masculine energy and choreographed sensuality. Body language communicates authenticity and confidence. Physical swagger is a core performance element regardless of gender.',
    genderNarratives: 'Traditional hip-hop narratives center masculine experience: street survival, competition, conquest. Female MCs historically carved space by either matching masculine energy or reframing from feminine perspective. Recent trends (vulnerability, emotional openness from male artists) have expanded lyrical gender expression.',
    subversionExamples: [
      'Young Thug wearing dresses on album covers while maintaining street credibility',
      'Lil Nas X\'s open queerness within hip-hop',
      'Nicki Minaj alternating between hyperfeminine and aggressive personas',
      'Kid Cudi and Kanye normalizing discussions of mental health and crying',
      'Tyler, the Creator\'s evolving expression of sexuality',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Hip-hop\'s tempo is one of the most deceptive in music. A trap song at 140 BPM feels slow because the snare hits on beat 3 (half-time), while a boom-bap track at 90 BPM feels faster because the snare hits on 2 and 4. The felt tempo is defined by the snare placement, not the metronome.',
    psychologicalTempo: 'Trap at 140 BPM feels like 70 BPM (half-time snare). Boom bap at 90 BPM feels like 90 BPM (full-time snare). Drill at 140 BPM feels menacing and mid-tempo because of sliding 808s. The hi-hat speed creates energy independent of the felt pulse — 32nd-note hi-hats over a half-time snare create urgency within a slow pocket.',
    weightAndMomentum: 'Hip-hop\'s weight comes from the 808 bass and kick, not tempo. A slow, heavy 808 hit carries more momentum than a fast light beat. The weight is gravitational — it pulls the body down. Trap music is among the "heaviest" music despite moderate tempos because of sustained sub-bass pressure.',
    urgencyScale: '1-10 urgency independent of BPM: Cloud rap at 60 BPM = 2, boom bap at 90 BPM = 5, conscious hip-hop at 95 BPM = 4, trap at 140 BPM = 6, drill at 140 BPM = 8, crunk at 75 BPM = 9 (raw energy), Busta Rhymes double-time at 90 BPM = 10.',
    comparisonToSameBPM: 'A trap beat at 140 BPM feels nothing like a pop song at 140 BPM. The trap version is half-time, bass-heavy, and menacing. Pop at 140 is four-on-the-floor and driving. Same BPM, completely different physical experience — the difference is groove architecture.',
  },

  mistakeConventions: {
    overview: 'Hip-hop has a complex relationship with imperfection. Boom bap and lo-fi sub-genres celebrate rawness — vinyl crackle, off-grid drums, imperfect samples. Trap values precision in production but rawness in vocal delivery. The genre\'s relationship to "mistakes" is sub-genre dependent.',
    toleratedImperfections: [
      'Slightly off-beat vocal delivery (adds swag and personality)',
      'Vocal pops and mouth sounds (authenticity markers)',
      'Background noise in vocal recordings (especially in drill and street rap)',
      'Imperfect sample loops with audible edit points',
      'Pitch imperfections in melodic rap (before Auto-Tune correction)',
    ],
    celebratedFlaws: [
      'J Dilla\'s deliberately unquantized drum programming',
      'Lo-fi vinyl noise and tape hiss as sonic character',
      'Raw, punch-in vocal recordings with audible gaps',
      'Sample chopping that cuts words and phrases mid-syllable',
      'Distorted, clipping 808 bass as deliberate aesthetic choice',
    ],
    overproductionRisks: [
      'Over-quantized drums losing groove (too "perfect")',
      'Excessive vocal tuning removing character and personality',
      'Too many production layers obscuring the beat\'s core impact',
      'Studio-polished mixing that removes rawness and street feel',
      'Overly complex arrangements that leave no space for the MC',
    ],
    authenticRoughness: 'In hip-hop, roughness is often a deliberate aesthetic choice, not an accident. Griselda\'s lo-fi production, drill\'s raw vocal recordings, and boom bap\'s sampled crackle are all intentional. The "mistake" is over-producing — removing the grit that connects the music to its street origins.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['hip-hop', 'rap', 'beats', '808', 'flow', 'bars', 'trap', 'boom bap'],
    avoidKeywords: ['folk', 'acoustic only', 'classical', 'country twang', 'polka', 'easy listening'],
    promptTemplate: '[sub-genre] hip-hop, [tempo] BPM, [mood] mood, [vocal style] delivery, [production style] beat, [key instruments]',
    tips: [
      'Specify sub-genre precisely: trap, boom bap, drill, lo-fi, etc.',
      'Describe the 808: deep, distorted, sliding, sustained',
      'Mention vocal style: aggressive, melodic, Auto-Tune, lyrical',
      'Reference regional sound: Atlanta, NYC, UK, Chicago',
      'Describe the mood: dark, hype, chill, introspective, aggressive',
      'For instrumental beats, specify "instrumental" and describe the sample type',
    ],
  },
};
