import type { GenreGuide } from './types';

export const JAZZ_GUIDE: GenreGuide = {
  id: 'jazz',
  name: 'Jazz',
  language: 'English',

  sonicPalette: {
    overview: 'Sophisticated, improvisational, and harmonically rich. Jazz is America\'s classical music — built on complex harmony, rhythmic swing, and the art of spontaneous composition. The sound is warm, acoustic, and alive with the interplay of master musicians.',
    timbre: [
      'Warm, breathy saxophone (alto, tenor, soprano)',
      'Brass (trumpet with mutes, trombone)',
      'Acoustic piano with rich harmonic voicings',
      'Upright bass (pizzicato and arco)',
      'Ride cymbal and brush patterns on drums',
      'Vibraphone with motor tremolo',
      'Guitar (archtop, clean tone)',
      'Clarinet (traditional jazz)',
    ],
    texture: 'Conversational — instruments interact and respond to each other in real time. The texture shifts constantly as musicians trade solos and comping patterns. Space and dynamics create a living, breathing sound.',
    tonality: 'Complex and chromatic — jazz uses the full chromatic spectrum. Extended chords (7ths, 9ths, 11ths, 13ths), altered tensions, and chromatic voice leading define the harmonic landscape. All 12 keys used.',
    signatureSounds: [
      'Walking bass line',
      'Ride cymbal swing pattern',
      'Piano comping (rhythmic chord punctuation)',
      'Saxophone vibrato and bends',
      'Trumpet with Harmon mute',
      'Brush patterns on snare',
      'Guitar comping with complex voicings',
    ],
  },

  rhythmAndGroove: {
    overview: 'Swing is the heartbeat of jazz — a lilting, propulsive feel that makes the music dance. The ride cymbal pattern provides the rhythmic foundation while bass walks and drums converse.',
    bpmRange: { min: 60, max: 300, sweet: 140 },
    feel: 'Swinging, conversational, and dynamic. The groove is elastic — speeding up and slowing down with the energy of the performance. Even at extreme tempos, jazz maintains a relaxed, effortless quality.',
    swing: 'Essential — the swing feel (long-short interpretation of 8th notes) is what makes jazz swing. The degree varies from gentle lilt to hard-driving bounce.',
    syncopation: 'Constant — jazz lives on syncopation. Soloists place notes unpredictably against the beat. Comping instruments accent off-beats. The bass walks straight while everything else syncopates.',
    grooveArchetype: 'Medium swing, ballad rubato, Latin groove (bossa, samba), or hard-driving bebop',
    rhythmicSignatures: [
      'Ride cymbal pattern (ding-ding-a-ding)',
      'Walking bass (quarter notes through chord changes)',
      'Hi-hat on 2 and 4 (foot pattern)',
      'Comping syncopation on piano/guitar',
      'Brush circles on snare for ballads',
      'Latin clave patterns (bossa nova, Afro-Cuban)',
      'Trading fours (soloists alternating 4-bar phrases)',
    ],
  },

  harmonicLanguage: {
    overview: 'Jazz has the most sophisticated harmonic language in popular music. Extended chords, substitutions, altered tensions, and chromatic movement create a rich, complex harmonic landscape. Chord symbols are a language unto themselves.',
    scales: ['Major (Ionian)', 'Dorian', 'Mixolydian', 'Lydian', 'Altered (Super Locrian)', 'Whole Tone', 'Diminished (Half-Whole)', 'Melodic Minor', 'Bebop Scales', 'Pentatonic'],
    chordProgressions: [
      'ii7 – V7 – IΔ7 (the fundamental jazz progression)',
      'I – vi – ii – V (rhythm changes turnaround)',
      'iii – VI – ii – V – I (extended turnaround)',
      'Coltrane changes (Giant Steps)',
      'Blues changes with substitutions',
      'Modal vamp (one chord for extended periods)',
      'Chromatic ii-V chains',
    ],
    harmonyNotes: 'Every chord is extended — minimum 7th, commonly 9th, 11th, 13th. Tritone substitution is standard. Altered dominant chords (b9, #9, b13, #11) add color. Voice leading between chords should be smooth. Rootless voicings on piano.',
    modality: 'Chromatic and modal — jazz moves freely between keys, modes, and tonal centers. Modal jazz stays on one chord/mode for extended exploration. Bebop is highly chromatic. The full harmonic spectrum is available.',
  },

  songStructure: {
    overview: 'Head-solo-head — state the melody (head), improvise over the changes (solos), restate the melody. Jazz song form is a framework for improvisation. Standard forms (AABA, ABAB) provide the harmonic roadmap.',
    form: 'Head (melody) – Solo Choruses – Trading – Head Out',
    sections: ['Intro', 'Head In (melody statement)', 'Solo 1', 'Solo 2', 'Solo 3', 'Trading Fours/Eights', 'Head Out', 'Coda/Tag'],
    arrangement: 'The arrangement provides the framework for improvisation. Horn arrangements, backgrounds behind solos, and rhythmic hits are composed. Everything else is spontaneous.',
    introOutro: 'Intros: rubato piano, bass note, or count-off. Outros (codas): repeated tag, ritardando, or the classic "button" ending. Some standards have composed intros and codas.',
    barLengths: 'Standards: 32 bars (AABA: 8+8+8+8 or ABAB). Blues: 12 bars. Each solo "chorus" is one pass through the full form. Multiple choruses per soloist.',
    hookPlacement: 'The melody (head) IS the hook — a memorable composed melody that the soloists then depart from. The most memorable standards have unforgettable melodies.',
  },

  vocalDelivery: {
    overview: 'Jazz vocal delivery is an art of interpretation — taking a composed melody and making it personal through phrasing, timing, and emotional nuance. The voice is treated as an instrument, equal to any horn or piano.',
    phrasing: 'Behind and ahead of the beat — never on it. Phrases stretch and compress with emotional intent. Rubato passages for dramatic effect. Each performance of a standard is a unique interpretation.',
    affect: 'Sophisticated, intimate, world-wise. Jazz vocals convey the full range of human emotion with subtlety and nuance. The delivery is conversational, as if sharing a secret.',
    techniques: [
      'Scat singing (improvised syllables)',
      'Rubato phrasing',
      'Breathy, intimate tone',
      'Blues inflections and bends',
      'Vibrato control',
      'Dynamic nuance (micro-dynamics)',
      'Vocal improvisation over changes',
      'Interpretive melody alteration',
    ],
    adlibStyle: 'Scat syllables — "doo-bah-dee-dah," "shoo-bee-doo." Vocal improvisation using syllables as instrumental sounds. Spoken asides. Less exclamatory, more musical.',
    harmony: 'Vocal harmony in ensemble settings (vocal jazz groups). Harmonized unison in big band arrangements. Solo voice with instrumental harmony.',
    grit: 'Subtle — some warmth and character in the voice is valued. Billie Holiday\'s fragile tone, Louis Armstrong\'s rasp, Tom Waits\' gravel. Cleanliness of tone varies by style.',
  },

  lyricalConventions: {
    overview: 'Jazz lyrics (from the Great American Songbook) are sophisticated, witty, and emotionally nuanced. The best jazz lyrics are literary — clever wordplay, sophisticated imagery, and emotional depth.',
    themes: [
      'Romantic love (idealized and real)',
      'Night and city life',
      'Loneliness and longing',
      'Sophistication and worldliness',
      'Wit and wordplay',
      'Nostalgia and memory',
      'Nature and seasons',
      'Existential reflection',
    ],
    perspective: 'First person intimate. The singer as character — world-weary, romantic, sophisticated. The perspective is personal but universally relatable.',
    figurativeLanguage: 'Sophisticated and literary — extended metaphors, clever similes, wordplay, and double meanings. Cole Porter, Lorenz Hart, and Ira Gershwin set the standard for lyrical wit.',
    vocabulary: 'Elevated, literary, conversational sophistication. Larger vocabulary than pop. Cultural references (cities, drinks, fashion). Mid-20th century American English.',
    storytellingApproach: 'Character sketches, emotional portraits, and clever observations. Each standard tells a complete emotional story in 32 bars. The lyric and melody are inseparable.',
    cliches: [
      'Blue skies/blue moon',
      'Night and day',
      'Stars and moonlight',
      'Dancing cheek to cheek',
      'Autumn leaves falling',
      'Rainy days',
    ],
  },

  productionFingerprint: {
    overview: 'Capture the performance — jazz production serves the musicians, not the other way around. The recording should feel like being in the room with the band. Natural sound, minimal processing, and respect for the acoustic instruments.',
    mixAesthetic: 'Natural, warm, and spacious. Each instrument clearly positioned in the stereo field. Room ambience is essential. Minimal compression. Dynamic range preserved. The mix should breathe.',
    era: 'Classic jazz recording (Rudy Van Gelder, Blue Note) remains the gold standard. Modern jazz recording maintains these principles with contemporary technology.',
    signalChain: 'Ribbon and condenser microphones. Minimal processing. Room acoustics are crucial. Direct-to-stereo or minimal multitrack. Analog warmth (tape saturation). No digital artifacts.',
    modernTrends: 'High-resolution digital recording maintaining analog aesthetics. Live-to-two-track recording revival. Electronic jazz fusion. Lo-fi jazz aesthetics (lo-fi hip-hop adjacent). Ambient jazz.',
  },

  instrumentation: {
    coreInstruments: [
      'Saxophone (alto, tenor, soprano, baritone)',
      'Trumpet (with various mutes)',
      'Piano (acoustic grand)',
      'Upright bass',
      'Drum kit (ride, hi-hat, brushes)',
      'Trombone',
      'Guitar (archtop, clean)',
      'Vibraphone',
    ],
    signatureSounds: [
      'Ride cymbal swing pattern',
      'Walking upright bass',
      'Piano rootless voicings',
      'Harmon mute trumpet (Miles Davis sound)',
      'Tenor sax with warm, breathy tone',
      'Vibraphone with tremolo',
      'Archtop guitar comping',
    ],
    layering: 'Ensemble interplay — not layered in the pop/rock sense. Musicians play together, listening and responding. Horn sections play arranged parts. Rhythm section provides the foundation.',
    avoidInstruments: [
      'Distorted electric guitar (unless fusion)',
      'Electronic drums (unless fusion/nu-jazz)',
      'Auto-Tune',
      'Pop synths',
      'Heavy production effects',
    ],
  },

  culturalContext: {
    overview: 'Jazz is America\'s art form — born from Black American creativity, it represents the highest expression of musical democracy. Every performance is a conversation between musicians, traditions, and the moment.',
    origin: 'New Orleans, early 1900s. Fusion of African rhythmic traditions, blues, ragtime, marching band music, and European harmony. Spread through migration to Chicago, New York, and the world.',
    identity: 'Black American creative genius — jazz represents intellectual and artistic achievement against the backdrop of oppression. It\'s simultaneously popular and highbrow, accessible and complex.',
    community: 'Jazz clubs, conservatories, jam sessions. Strong educational tradition. International jazz festivals. Recording as art (Blue Note, Verve, ECM). Respect for lineage and mentorship.',
    socialFunction: 'Artistic expression at its highest level. Cultural diplomacy (jazz ambassadors). Education and mentorship. Community through live performance. Intellectual and emotional enrichment.',
    authenticityMarkers: [
      'Instrumental mastery and technique',
      'Improvisational ability',
      'Harmonic knowledge and sophistication',
      'Respect for jazz history and lineage',
      'Live performance excellence',
      'Listening skills and ensemble interaction',
    ],
  },

  historicalLineage: {
    overview: 'From New Orleans funerals to Carnegie Hall, jazz has evolved through constant innovation while honoring its roots in blues and African American musical tradition.',
    roots: ['Blues', 'Ragtime', 'African Rhythmic Traditions', 'Marching Band', 'Gospel', 'European Harmony'],
    evolution: 'New Orleans jazz (1900s-1920s) → Swing era (1930s-40s) → Bebop revolution (1940s-50s) → Cool jazz and hard bop (1950s-60s) → Free jazz and fusion (1960s-70s) → Neo-traditionalism (1980s-90s) → Modern jazz pluralism (2000s-present).',
    keyEras: [
      '1900-1920: New Orleans origins (Louis Armstrong)',
      '1930-1945: Swing era (Duke Ellington, Count Basie)',
      '1945-1960: Bebop revolution (Charlie Parker, Dizzy Gillespie)',
      '1955-1965: Cool jazz, hard bop, modal jazz (Miles Davis, Coltrane)',
      '1965-1975: Free jazz and fusion (Ornette Coleman, Weather Report)',
      '1980-present: Neo-traditionalism and modern pluralism',
    ],
    influencedBy: ['Blues', 'Ragtime', 'African Music', 'European Classical', 'Gospel'],
    influenced: ['R&B', 'Rock', 'Hip-Hop (sampling)', 'Bossa Nova', 'Funk', 'Pop', 'Electronic Music'],
  },

  subGenres: [
    {
      name: 'Bebop',
      description: 'Fast, complex, and virtuosic. Bebop revolutionized jazz with rapid tempos, complex chord changes, and instrumental virtuosity. Art music for listening, not dancing.',
      distinguishingFeatures: ['Fast tempos', 'Complex chord progressions', 'Virtuosic improvisation', 'Angular melodies', 'Small combo format'],
      bpmRange: { min: 160, max: 300 },
      keyArtists: ['Charlie Parker', 'Dizzy Gillespie', 'Thelonious Monk', 'Bud Powell', 'Max Roach'],
      productionNotes: 'Capture the energy and speed. Clear, present recording. Small combo. Natural room sound. Every note must be audible at fast tempos.',
      lyricNotes: 'Primarily instrumental. When lyrics present: hip, witty, bebop slang. Vocal scatting mirrors instrumental lines.',
      sunoPromptKeywords: ['bebop', 'bop', 'fast jazz', 'virtuoso', 'Charlie Parker', 'complex', 'small combo'],
      embodiedDelta: {
        microTimingAndFeel: {
          aheadBehindBeat: 'Soloists push ahead of the beat — driving, urgent phrasing that creates forward momentum at extreme tempos',
          genreSpecificFeel: 'Flattened swing ratio at speed (closer to straight 8ths above 240 BPM); rhythmic groupings in odd note clusters',
          quantizationDeviation: 'Maximum deviation — every phrase is rhythmically unique, no two choruses identical',
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Minimal — bebop fills space with rapid-fire lines; space exists only as breath marks between phrases',
          breathingPatterns: 'Breath-limited phrase lengths (horn players); piano/guitar can sustain longer unbroken runs',
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Parker vocabulary is prerequisite — quoting Bird licks is identity signaling, not mere reference',
          quotationPractice: 'Dense quotation of popular melodies within solos (inserting fragments of standards as inside jokes)',
          expectedReferences: ['Charlie Parker head melodies', 'Dizzy Gillespie harmonic devices', 'Thelonious Monk angular motifs'],
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Controlled freefall — extreme BPM feels exhilarating rather than frantic when played with authority',
          urgencyScale: '9/10 — maximum forward drive, every beat propels',
        },
        performancePractice: {
          improvisationConventions: 'Extended virtuosic solos through rapid chord changes — soloist must demonstrate complete harmonic mastery at speed',
          crowdInteraction: 'Listening music, not dancing — the audience sits and absorbs; bebop deliberately moved jazz off the dance floor',
        },
        harmonicLanguage: {
          chordProgressions: ['Rapid ii-V chains through distant keys', 'Contrafacts over rhythm changes and blues', 'Chromatic approach patterns over every chord'],
          harmonyNotes: 'Chord changes fly by at one or two per beat — soloists must navigate complex substitutions at breakneck speed with no harmonic ambiguity',
        },
      },
    },
    {
      name: 'Cool Jazz',
      description: 'Relaxed, understated, and refined. Cool jazz reacted against bebop\'s intensity with a more restrained, lyrical approach.',
      distinguishingFeatures: ['Restrained, lyrical approach', 'Lighter tone', 'West Coast association', 'Softer dynamics', 'Arrangement-focused'],
      bpmRange: { min: 80, max: 160 },
      keyArtists: ['Miles Davis (Birth of the Cool)', 'Chet Baker', 'Dave Brubeck', 'Gerry Mulligan', 'Stan Getz'],
      productionNotes: 'Cool, restrained sound. Lighter touch on instruments. Space and air in the mix. Lyrical solos. Subtle dynamics.',
      lyricNotes: 'When vocal: intimate, breathy, understated. Chet Baker style — fragile and beautiful.',
      sunoPromptKeywords: ['cool jazz', 'West Coast jazz', 'lyrical', 'restrained', 'mellow jazz', 'smooth', 'intimate'],
    },
    {
      name: 'Hard Bop',
      description: 'Bebop with more blues and gospel feeling — harder swinging, more soulful, and more emotionally direct than cool jazz.',
      distinguishingFeatures: ['Blues and gospel influence', 'Hard-swinging rhythm', 'Soulful melodies', 'Strong groove', 'Emotional directness'],
      bpmRange: { min: 100, max: 250 },
      keyArtists: ['Art Blakey', 'Horace Silver', 'Cannonball Adderley', 'Lee Morgan', 'Freddie Hubbard'],
      productionNotes: 'Hard-swinging rhythm section. Soulful, bluesy melodies. Clear, present recording (Blue Note aesthetic). Strong bass and drums.',
      lyricNotes: 'Primarily instrumental. Blues and gospel feeling in the music itself.',
      sunoPromptKeywords: ['hard bop', 'Blue Note jazz', 'soulful jazz', 'swinging', 'bluesy jazz', 'funky jazz', 'groove'],
    },
    {
      name: 'Modal Jazz',
      description: 'Jazz based on modes rather than chord progressions — fewer chord changes, more exploration of a single scale or mode.',
      distinguishingFeatures: ['Minimal chord changes', 'Scale/mode-based improvisation', 'Spacious, meditative quality', 'Extended exploration', 'Fewer harmonic restrictions'],
      bpmRange: { min: 70, max: 180 },
      keyArtists: ['Miles Davis (Kind of Blue)', 'John Coltrane', 'McCoy Tyner', 'Herbie Hancock', 'Wayne Shorter'],
      productionNotes: 'Spacious, atmospheric recording. Room for exploration. Each instrument clearly heard. Natural reverb. Meditative quality in the mix.',
      lyricNotes: 'Instrumental. The music speaks through improvisation over modal spaces.',
      sunoPromptKeywords: ['modal jazz', 'Kind of Blue', 'spacious', 'meditative', 'atmospheric jazz', 'Coltrane', 'Miles'],
    },
    {
      name: 'Free Jazz',
      description: 'Complete freedom from traditional harmony, melody, and rhythm. Free jazz explores the outer limits of musical expression through collective improvisation.',
      distinguishingFeatures: ['No predetermined harmony or form', 'Collective improvisation', 'Extreme extended techniques', 'Noise and texture exploration', 'Avant-garde aesthetic'],
      bpmRange: { min: 0, max: 300 },
      keyArtists: ['Ornette Coleman', 'Cecil Taylor', 'Sun Ra', 'Albert Ayler', 'Peter Brötzmann'],
      productionNotes: 'Capture the energy and chaos. Full dynamic range. Multiple instruments interacting. Accept and feature "noise" and unconventional sounds.',
      lyricNotes: 'When vocal: avant-garde, stream-of-consciousness, spoken word. Conventional lyrics rare.',
      sunoPromptKeywords: ['free jazz', 'avant-garde jazz', 'experimental', 'free improvisation', 'noise jazz', 'abstract'],
      embodiedDelta: {
        silenceAndSpace: {
          negativeSpaceRole: 'Confrontational — silence can be weaponized, and density can become a wall of sound; both are valid',
          dynamicContrast: 'Maximally extreme — whisper to scream with no preparation; dynamic range is the widest in all jazz',
        },
        callAndResponse: {
          vocalInstrumentalDialogue: 'Simultaneous collective improvisation replaces traditional dialogue — everyone speaks at once',
          sectionInternal: 'No sections; continuous textural evolution where musicians react to group energy',
          audienceParticipation: 'Polarized — audiences either sit in reverent focus or walk out; no casual middle ground',
          patterns: ['Collective free blowing', 'Textural crescendo/decrescendo waves', 'One player drops out, others respond to the gap'],
        },
        mistakeConventions: {
          toleratedImperfections: ['All sounds are valid', 'Instrument abuse is technique', 'Silence mid-phrase is compositional'],
          celebratedFlaws: ['Cracked notes as emotional expression', 'Overblowing as timbral choice', 'Rhythmic chaos as collective organism'],
          overproductionRisks: ['Any editing or post-production manipulation', 'Smoothing out dynamic extremes', 'Adding reverb to natural raw sound'],
          authenticRoughness: 'Roughness IS the aesthetic — the distinction between mistake and intention is philosophically rejected',
        },
        performancePractice: {
          improvisationConventions: 'Total freedom — no predetermined harmony, melody, rhythm, or form; collective risk is the goal',
          crowdInteraction: 'Audience confrontation rather than entertainment — demanding active listening or accepting walkouts',
        },
        harmonicLanguage: {
          harmonyNotes: 'Tonality is abandoned — atonality, microtonality, and noise are equal to conventional pitch; harmonic "correctness" is irrelevant',
          modality: 'Post-tonal — no key centers, no functional harmony; sound itself replaces harmonic motion as the organizing principle',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Tempo is fluid or absent — pulse may emerge and dissolve; clock time is replaced by event-driven time',
          weightAndMomentum: 'Variable between weightless suspension and crushing density — momentum comes from collective energy, not rhythmic regularity',
        },
      },
    },
    {
      name: 'Fusion',
      description: 'Jazz meets rock and electronic music — electric instruments, rock rhythms, and jazz improvisation over amplified, energetic arrangements.',
      distinguishingFeatures: ['Electric instruments (guitar, bass, keys)', 'Rock-influenced rhythms', 'Jazz improvisation over rock/funk grooves', 'Amplified sound', 'Studio experimentation'],
      bpmRange: { min: 80, max: 180 },
      keyArtists: ['Miles Davis (Bitches Brew)', 'Weather Report', 'Herbie Hancock (Head Hunters)', 'Return to Forever', 'Snarky Puppy'],
      productionNotes: 'Electric instruments with effects. Rock/funk rhythms. Studio production techniques. Multiple keyboards. Powerful rhythm section.',
      lyricNotes: 'Primarily instrumental. When present: abstract or funk-influenced. Music-driven.',
      sunoPromptKeywords: ['jazz fusion', 'fusion', 'electric jazz', 'jazz-rock', 'funk jazz', 'progressive jazz'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Straight eighths replace swing — funk grid precision with jazz harmonic complexity layered on top',
          aheadBehindBeat: 'Locked to grid — tight rhythmic unison between bass and drums, closer to rock/funk pocket than jazz float',
          humanizationMarkers: ['Tight rhythmic unison between electric bass and drums', 'Guitar wah-pedal as rhythmic accent', 'Keyboard ostinatos with funk precision'],
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Filled — ambient washes, sustained keyboard pads, and effects replace acoustic silence',
          dynamicContrast: 'Compressed compared to acoustic jazz — electric amplification narrows the dynamic band',
        },
        performancePractice: {
          stagePresence: 'Rock staging — standing, amplified, effects pedals visible; closer to rock concert than jazz club',
          livVsRecordedDifferences: 'Studio versions often heavily produced with overdubs; live versions rawer and more improvisatory',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Rock/funk weight — same BPM feels heavier and more grounded than swing jazz due to straight-eighth grid',
          weightAndMomentum: 'Heavy and propulsive — electric instruments add physical weight that acoustic jazz lacks',
        },
        instrumentation: {
          coreInstruments: ['Electric guitar (with effects)', 'Electric bass', 'Synthesizers and electric piano (Rhodes, Clavinet)', 'Drum kit with rock/funk patterns'],
          signatureSounds: ['Distorted guitar through wah pedal', 'Rhodes electric piano with phaser', 'Moog synthesizer leads', 'Slap bass'],
          avoidInstruments: ['Upright bass (replaced by electric)', 'Brushes on drums (replaced by sticks and power)'],
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Must know both jazz and rock/funk canons — Miles\'s electric period, Hendrix, James Brown, and Stevie Wonder are all reference points',
          expectedReferences: ['Miles Davis electric era (Bitches Brew, On the Corner)', 'Herbie Hancock\'s Head Hunters', 'Weather Report\'s Birdland', 'Mahavishnu Orchestra intensity'],
        },
      },
    },
    {
      name: 'Smooth Jazz',
      description: 'Accessible, polished, and melodic jazz designed for easy listening. Clean tones, simple harmonies, and background-friendly arrangements.',
      distinguishingFeatures: ['Polished, accessible sound', 'Melodic improvisation', 'Clean, processed tones', 'R&B/pop influence', 'Background-friendly'],
      bpmRange: { min: 80, max: 120 },
      keyArtists: ['Kenny G', 'Grover Washington Jr.', 'George Benson', 'David Sanborn', 'Boney James'],
      productionNotes: 'Clean, polished production. Reverb-heavy. Processed tones. Pop/R&B production values. Melodic, accessible solos.',
      lyricNotes: 'Often instrumental. When vocal: romantic, smooth. Pop-accessible.',
      sunoPromptKeywords: ['smooth jazz', 'easy listening jazz', 'polished', 'melodic', 'relaxing jazz', 'saxophone jazz'],
      embodiedDelta: {
        silenceAndSpace: {
          negativeSpaceRole: 'Filled — synth pads, reverb tails, and layered production leave no empty space; background-music density',
          dynamicContrast: 'Narrow — everything sits in a comfortable, even dynamic band; no sudden loud or quiet moments',
        },
        mistakeConventions: {
          toleratedImperfections: ['Pitch must be exact', 'Timing must be tight', 'Tone must be clean'],
          celebratedFlaws: [],
          overproductionRisks: ['Overproduction is embraced, not a risk — polish IS the aesthetic'],
          authenticRoughness: 'Roughness is avoided — the smoothness is the point; any grit feels like a mistake',
        },
        performancePractice: {
          crowdInteraction: 'Pop-show interaction — smiling, audience banter, accessible and non-confrontational',
          improvisationConventions: 'Melodic variation within safe harmonic boundaries — no outside playing or dissonance',
        },
        socioeconomicSubtext: {
          classIdentity: 'Aspirational upper-middle-class — wine bars, luxury hotels, adult contemporary radio',
          materialConditions: 'Commercial viability prioritized; jazz credibility consciously traded for accessibility',
        },
        harmonicLanguage: {
          harmonyNotes: 'Dramatically simplified — major 7ths and minor 7ths without altered tensions; functional pop harmony with a jazz veneer',
          modality: 'Diatonic and consonant — avoids chromaticism, tritone subs, and dissonance; stays in comfortable harmonic territory',
        },
        instrumentation: {
          coreInstruments: ['Soprano or alto saxophone (clean, processed tone)', 'Electric bass', 'Drum machine or programmed drums', 'Synthesizer pads and electric piano'],
          avoidInstruments: ['Upright bass (too raw)', 'Acoustic drums with brushes (too organic)', 'Muted trumpet (too edgy)'],
        },
      },
    },
    {
      name: 'Vocal Jazz',
      description: 'Jazz centered on the voice as the primary instrument. Standards interpretation, scat singing, and the art of jazz phrasing.',
      distinguishingFeatures: ['Voice as primary instrument', 'Great American Songbook repertoire', 'Scat singing', 'Interpretive phrasing', 'Intimate presentation'],
      bpmRange: { min: 60, max: 200 },
      keyArtists: ['Ella Fitzgerald', 'Billie Holiday', 'Sarah Vaughan', 'Frank Sinatra', 'Cécile McLorin Salvant'],
      productionNotes: 'Vocal-forward recording. Intimate, close-miked voice. Piano trio or small combo accompaniment. Natural room sound. Clear diction.',
      lyricNotes: 'Great American Songbook standards. Sophisticated, witty, romantic lyrics by Cole Porter, Gershwin, Rodgers & Hart, etc.',
      sunoPromptKeywords: ['vocal jazz', 'jazz singing', 'standards', 'torch song', 'crooner', 'jazz vocals', 'swing vocal'],
      embodiedDelta: {
        callAndResponse: {
          vocalInstrumentalDialogue: 'Voice leads — the band responds to the vocalist; pianist completes vocal phrases with harmonic fills',
          patterns: ['Singer phrases, piano answers', 'Scat trading with horn', 'Band drops to spotlight vocal rubato'],
        },
        genderAndBodyConventions: {
          vocalGenderCodes: 'Pronounced gender divide — female torch singer vs male crooner carry different emotional traditions',
          physicalityInPerformance: 'Voice-as-instrument physicality — breath control, posture, microphone technique are visible craft',
          genderNarratives: 'Standards carry gendered lyric assumptions (he/she pronoun assignments); modern vocalists often subvert these',
        },
        performancePractice: {
          stagePresence: 'Center stage — vocalist stands while band sits; spotlight and direct audience eye contact',
          crowdInteraction: 'Intimate rapport — storytelling between songs, song dedications, reading the room for ballad vs uptempo',
        },
        microTimingAndFeel: {
          aheadBehindBeat: 'Exaggerated behind-beat phrasing — vocalists stretch time more than instrumentalists, creating emotional tension',
          genreSpecificFeel: 'Rubato tradition stronger than in instrumental jazz; vocalist bends tempo while rhythm section holds steady',
        },
      },
    },
    {
      name: 'Latin Jazz',
      description: 'Jazz fused with Latin American rhythms — Afro-Cuban, Brazilian, and other Latin traditions. Complex polyrhythms meet jazz harmony.',
      distinguishingFeatures: ['Latin percussion (congas, bongos, timbales)', 'Afro-Cuban or Brazilian rhythms', 'Jazz harmony with Latin groove', 'Polyrhythmic complexity', 'Danceable energy'],
      bpmRange: { min: 100, max: 200 },
      keyArtists: ['Tito Puente', 'Mongo Santamaria', 'Chick Corea', 'Antonio Carlos Jobim', 'Michel Camilo'],
      productionNotes: 'Latin percussion prominent. Polyrhythmic layers. Jazz harmony over Latin grooves. Energetic, danceable. Acoustic or electric.',
      lyricNotes: 'Spanish or Portuguese when vocal. Romantic, passionate. Bossa nova: intimate. Salsa-jazz: energetic.',
      sunoPromptKeywords: ['Latin jazz', 'Afro-Cuban jazz', 'bossa nova jazz', 'salsa jazz', 'tropical jazz', 'percussion'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Clave replaces swing as the organizing principle — all phrasing relates to the 2-3 or 3-2 clave pattern',
          aheadBehindBeat: 'Tight to clave — soloists must align with the rhythmic matrix rather than floating over swing',
          humanizationMarkers: ['Interlocking polyrhythmic layers between congas/bongos/timbales', 'Piano montuno as rhythmic engine', 'Bass tumbao locking with clave'],
        },
        regionalDialectSpecificity: {
          accentInfluence: 'Cuban Spanish cadence shapes melodic phrasing; Brazilian Portuguese nasality influences bossa nova vocals',
          phoneticMarkers: ['Cuban rhythmic speech patterns in montuno chants', 'Brazilian "saudade" emotional color', 'Nuyorican English-Spanish code-switching'],
          regionWithinCulture: 'Havana vs New York vs São Paulo — each city has distinct rhythmic dialects and instrumentation preferences',
        },
        callAndResponse: {
          vocalInstrumentalDialogue: 'Sonero/coro structure — lead singer improvises while chorus responds with fixed refrain (montuno section)',
          patterns: ['Sonero call / coro response', 'Percussion conversations between conga and timbale', 'Piano montuno answering horn lines'],
          audienceParticipation: 'Active — dancing is expected; audience becomes part of the rhythmic fabric',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Circular momentum — polyrhythmic density makes the perceived tempo feel faster than the actual BPM',
          weightAndMomentum: 'Buoyant and propulsive — the music lifts rather than drives; momentum comes from interlocking patterns not brute force',
        },
      },
    },
    {
      name: 'Acid Jazz',
      description: 'Jazz meets funk, hip-hop, and electronic dance music. Groovy, club-oriented jazz with modern production.',
      distinguishingFeatures: ['Funk/hip-hop influence', 'Club-oriented grooves', 'Electronic production elements', 'DJ culture integration', 'Danceable beats'],
      bpmRange: { min: 90, max: 130 },
      keyArtists: ['Jamiroquai', 'Brand New Heavies', 'US3', 'Incognito', 'Guru\'s Jazzmatazz'],
      productionNotes: 'Funky grooves with jazz improvisation. Electronic production elements. Danceable beats. Modern studio techniques. Live and programmed elements.',
      lyricNotes: 'Funk-influenced lyrics. Social commentary. Dance and groove themes. Positive energy.',
      sunoPromptKeywords: ['acid jazz', 'funky jazz', 'groove jazz', 'club jazz', 'jazz funk', 'dance jazz'],
    },
    {
      name: 'Nu-Jazz',
      description: 'Contemporary electronic jazz blending traditional jazz elements with electronic production, ambient textures, and modern beats.',
      distinguishingFeatures: ['Electronic production with jazz', 'Ambient and atmospheric textures', 'Modern beats (broken beat, house)', 'Genre-blending approach', 'Digital meets acoustic'],
      bpmRange: { min: 70, max: 140 },
      keyArtists: ['GoGo Penguin', 'Robert Glasper', 'Kamasi Washington', 'Yussef Dayes', 'Nubya Garcia'],
      productionNotes: 'Blend acoustic jazz instruments with electronic production. Modern beats and textures. Atmospheric. Genre-fluid. High production values.',
      lyricNotes: 'Often instrumental. When present: modern, conscious, poetic. Hip-hop influenced.',
      sunoPromptKeywords: ['nu-jazz', 'modern jazz', 'electronic jazz', 'broken beat jazz', 'contemporary jazz', 'future jazz'],
    },
    {
      name: 'Swing / Big Band',
      description: 'Large ensemble jazz from the swing era — dance-oriented, arranged, and featuring the sound of 15+ musicians playing together.',
      distinguishingFeatures: ['Large ensemble (15+ musicians)', 'Written arrangements with solo sections', 'Dance-oriented swing rhythm', 'Section playing (brass, reeds, rhythm)', 'Energetic, joyful energy'],
      bpmRange: { min: 120, max: 220 },
      keyArtists: ['Duke Ellington', 'Count Basie', 'Benny Goodman', 'Glenn Miller', 'Gordon Goodwin'],
      productionNotes: 'Full big band sound. Section balancing is critical. Powerful brass. Swinging rhythm section. Dynamic range from quiet to explosive.',
      lyricNotes: 'When vocal: swing-era lyrics, romantic, fun, witty. Dance and celebration themes.',
      sunoPromptKeywords: ['big band', 'swing', 'jazz orchestra', 'brass section', 'swing era', 'dance band', 'arrangement'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Heavy, emphatic swing with the whole band locking into a unified groove — section rhythms are tighter and more regimented than small-combo jazz',
          aheadBehindBeat: 'On top of the beat — the brass section drives forward while the rhythm section anchors, creating a buoyant, danceable lift',
        },
        callAndResponse: {
          vocalInstrumentalDialogue: 'Arranged call-and-response between brass and reed sections replaces spontaneous conversational interplay',
          patterns: ['Brass shout chorus answered by reed section', 'Soloist over background riffs from ensemble', 'Rhythm section hits punctuating horn figures'],
          audienceParticipation: 'Dance floor is the primary audience response — the music succeeds when bodies move; applause for soloists is secondary to the collective groove',
        },
        performancePractice: {
          improvisationConventions: 'Arranged frameworks with designated solo windows — improvisation happens within composed structures, not as the primary activity',
          stagePresence: 'Bandleader as showman (Basie\'s understated cool, Ellington\'s elegance, Goodman\'s precision) — the ensemble is a visual spectacle of coordinated musicians',
          crowdInteraction: 'Entertainment-forward — dancers on the floor, emcee announcements, the band as social event rather than listening experience',
        },
        tempoFeelVsNumber: {
          weightAndMomentum: 'Massive ensemble weight — 15+ musicians create a wall of swing that small combos cannot replicate; momentum is orchestral rather than conversational',
          urgencyScale: '7/10 — propulsive and joyful rather than frantic; the groove invites movement, not cerebral attention',
        },
        socioeconomicSubtext: {
          classIdentity: 'Populist entertainment — swing was America\'s pop music before rock and roll; dance halls and ballrooms were cross-class social spaces',
          politicalUndercurrent: 'Integration through the dance floor — Benny Goodman\'s integrated bands and the shared dance space quietly challenged segregation norms',
        },
      },
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Jazz audiences are typically educated, musically knowledgeable, and deeply appreciative of musicianship and improvisation. The audience ranges from casual listeners to devoted aficionados.',
    fanExpectations: [
      'Instrumental mastery',
      'Improvisational creativity',
      'Harmonic sophistication',
      'Respect for jazz tradition',
      'Live performance excellence',
      'Artistic ambition and originality',
    ],
    gatekeeping: 'High — jazz has strong opinions about what constitutes "real jazz." Purists vs. fusionists. Smooth jazz controversies. Academic vs. street jazz. Knowledge of history expected.',
    livePerformance: 'The essential jazz experience — intimate clubs, concert halls, and festivals. Improvisation makes every show unique. Audience listens attentively. Standing ovations for exceptional solos.',
    fashionAndAesthetic: 'Sharp and sophisticated — suits, elegant casual. Musicians dress with intention. The aesthetic reflects the music\'s sophistication. Varies by sub-genre and era.',
    crossoverPotential: 'Moderate — jazz harmony and technique influence every genre. Jazz-adjacent genres (acid jazz, nu-jazz) cross over more easily. Pure jazz remains niche but deeply respected.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Swing is the DNA of jazz micro-timing — the feel lives "in the cracks" between straight and swung eighth notes, a placement that defies notation and must be absorbed through immersion.',
    quantizationDeviation: 'Enormous. Jazz is unquantized by nature. The ride cymbal pattern floats around the grid, bass walks with slight push-pull against the drums, and soloists deliberately place notes early or late for expressive effect.',
    aheadBehindBeat: 'Both, strategically. Hard bop drummers like Art Blakey push on top of the beat for urgency. Miles Davis famously played behind the beat, creating suspended tension. The rhythm section negotiates these pulls in real time.',
    humanizationMarkers: [
      'Ride cymbal that breathes and varies stroke weight on every beat',
      'Walking bass lines with micro-rushes into chord changes',
      'Comping that anticipates or delays chord stabs conversationally',
      'Brush patterns that drift organically across the snare head',
      'Solo phrases that stretch across bar lines, ignoring downbeats',
    ],
    genreSpecificFeel: 'The swing ratio (how uneven the long-short eighth notes are) shifts with tempo — gentle lilt at slow tempos, nearly even at fast bebop speeds. This is never calculated, only felt. A jazz musician\'s time is their fingerprint.',
  },

  silenceAndSpace: {
    overview: 'In jazz, what you don\'t play defines you as much as what you do. Miles Davis made silence a compositional element — his rests created anticipation and weight that no cascade of notes could match.',
    negativeSpaceRole: 'Central and philosophical. Space allows the listener to lean in, creates dramatic tension, and gives other musicians room to respond. A crowded jazz performance signals immaturity.',
    breathingPatterns: 'Phrasing follows vocal breath patterns even in instrumental playing — short bursts with rests, long arcs with pauses for dramatic effect. The ensemble breathes together.',
    dynamicContrast: 'Extreme — from barely audible brushes-and-bass intimacy to full-band fortissimo in a single tune. A jazz trio can go from a whisper to a shout and back within 8 bars.',
    whatIsDeliberatelyAbsent: [
      'The root of the chord in piano voicings (left for the bass)',
      'Kick drum on beat 1 in many swing patterns',
      'Filled-in melodic passages — jazz melodies leave gaps for rhythmic tension',
      'Constant harmonic rhythm — letting a chord ring while time moves',
      'Steady-state dynamics — jazz rejects sustaining one volume level',
    ],
  },

  callAndResponse: {
    overview: 'Jazz is fundamentally a conversation. Trading fours, comping as dialogue, and the interplay between soloist and rhythm section represent the deepest form of musical call-and-response in Western music.',
    vocalInstrumentalDialogue: 'The vocalist and pianist converse — the piano answers vocal phrases with fills, the singer responds to harmonic suggestions. Ella Fitzgerald and her pianists exemplified this symbiosis.',
    sectionInternal: 'Within the rhythm section, every gesture is a micro-conversation. The drummer responds to the bassist\'s note choices, the pianist reacts to the drummer\'s accents, and the bass adjusts to the piano\'s harmonic implications.',
    audienceParticipation: 'Subtle but real — jazz audiences signal approval through verbal affirmations ("yeah!", finger-snapping) and attentive silence. The audience\'s energy palpably affects the musicians\' risk-taking.',
    patterns: [
      'Trading fours — soloists alternate 4-bar improvisations, creating point-counterpoint dialogue',
      'Comping as response — the pianist places chords in direct reaction to the soloist\'s phrasing',
      'Bass walking patterns that answer melodic contours of the soloist',
      'Drum fills that punctuate the ends of solo phrases like exclamation marks',
      'Head arrangement call-and-response between horn sections',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Jazz emerged from African American Vernacular English and carries the cadences, inflections, and storytelling traditions of Black American speech across regional dialects from New Orleans to Harlem.',
    phoneticMarkers: [
      'Southern drawl influence in New Orleans jazz vocals',
      'Harlem hipster slang cadences in bebop-era scat singing',
      'Cool, clipped West Coast diction in California cool jazz',
      'Blues-inflected vowel bending from Mississippi Delta roots',
      'Cosmopolitan mid-Atlantic phrasing in Great American Songbook interpretation',
    ],
    accentInfluence: 'The rhythmic cadence of African American speech patterns directly shaped jazz phrasing — the way a Harlem storyteller drops syllables mirrors bebop rhythmic displacement. Southern preacher delivery maps onto gospel-jazz intensity.',
    dialectVocabulary: [
      '"Hip," "cool," "dig," "cat" — bebop-era slang that entered mainstream English',
      '"Woodshed" — to practice intensely in private',
      '"Blow" — to play or improvise, not just for wind instruments',
      '"Changes" — chord progression, but also life transitions',
      '"Shed" — short for woodshed, to practice deeply',
    ],
    regionWithinCulture: 'New Orleans (birthplace, second-line parades), Kansas City (jam session culture, territory bands), Chicago (Great Migration sound), Harlem (bebop revolution, Cotton Club), West Coast (cool school), Philadelphia (hard bop soul).',
  },

  performancePractice: {
    overview: 'Improvisation IS the performance in jazz — the set is never played the same way twice. The live experience is the art form\'s primary medium, and a recording is merely a snapshot of one evening\'s possibilities.',
    improvisationConventions: 'Solo order is loosely established (horn players first, then piano, then trades with drums), but spontaneous deviation is celebrated. The length and intensity of solos respond to room energy. Quoting other tunes mid-solo demonstrates mastery.',
    crowdInteraction: 'Intimate and respectful — musicians acknowledge applause with nods, dedicate tunes, tell stories between songs. The audience\'s silence during solos and eruptions after them create the performance dynamic.',
    stagePresence: 'Ranges from Miles Davis turning his back to the audience (cool detachment) to Thelonious Monk dancing at the piano (eccentric joy). Authenticity over choreography. The instrument is the focus, not showmanship.',
    livVsRecordedDifferences: 'Massive. Live jazz stretches tunes from 3-minute recordings to 15-minute explorations. Solos are longer, risks are greater, and interaction is deeper. Many jazz fans consider studio recordings secondary to live performance.',
    whatMakesAGoodShow: 'Telepathic ensemble communication, risk-taking solos that build arcs of tension and release, moments of collective spontaneity that surprise even the musicians, and the feeling that this music will never happen exactly this way again.',
  },

  socioeconomicSubtext: {
    overview: 'Jazz emerged from the intersection of African American creativity and systemic exclusion — the music carries the economic realities, aspirations, and resistance of Black communities from New Orleans to the global stage.',
    materialConditions: 'Jazz musicians historically navigated exploitative club owners, segregated venues, and record label contracts that stripped rights. The chitlin\' circuit provided performance opportunities but at subsistence wages. Today, jazz sustains through teaching, festivals, and grants more than recording.',
    classIdentity: 'Jazz occupies a dual position — born in working-class Black neighborhoods but adopted by intellectual and upper-class audiences. Bebop deliberately moved jazz from dance halls to listening rooms, asserting it as art rather than entertainment.',
    politicalUndercurrent: 'From Billie Holiday\'s "Strange Fruit" to Max Roach\'s "We Insist!" to Kamasi Washington\'s "The Epic," jazz has served as a vehicle for protest and Black consciousness. The music\'s complexity itself is a political statement about Black intellectual capacity.',
    implicitReferences: [
      'The Great Migration — jazz geography follows Black population movement northward',
      'Jim Crow segregation — reflected in the existence of separate musicians\' unions and venues',
      'Civil Rights movement — "A Love Supreme" as spiritual and political statement',
      'Economic precarity — the jazz musician\'s hustle between gigs, teaching, and sessions',
      'Gentrification of jazz spaces — clubs closing as neighborhoods change',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Jazz is the most self-referential genre in music — knowing the canon is mandatory, quoting other solos mid-improvisation is expected, and every performance is a conversation with the entire history of the form.',
    canonKnowledge: 'A jazz musician must know the standards (at minimum 200+ tunes), the classic solos (Parker on "Ko-Ko," Coltrane on "Giant Steps," Miles on "So What"), and the theoretical innovations of each era. This knowledge is demonstrated through performance, not discussion.',
    samplingTradition: 'Jazz doesn\'t sample in the hip-hop sense — it quotes. A saxophonist might insert four bars of a Parker solo into their own improvisation, or a pianist might reference a Monk voicing. These quotations are recognized and appreciated by knowledgeable listeners.',
    quotationPractice: 'Quoting is witty commentary — inserting "Pop Goes the Weasel" during an avant-garde solo is humor; quoting Coltrane\'s licks during a modal exploration is homage. The context and timing of quotation reveals musical intelligence.',
    expectedReferences: [
      'Charlie Parker\'s bebop vocabulary — the foundation of modern jazz language',
      'John Coltrane\'s "sheets of sound" and "Giant Steps" patterns',
      'Miles Davis\'s phrasing economy and melodic choices',
      'Thelonious Monk\'s angular intervals and rhythmic displacement',
      'The Great American Songbook — standards by Gershwin, Porter, Rodgers & Hart',
    ],
    lineageSignifiers: [
      'Playing "Rhythm Changes" signals bebop fluency',
      'Using Coltrane substitutions signals advanced harmonic knowledge',
      'Performing Monk compositions signals respect for jazz iconoclasm',
      'Choosing obscure standards signals deep repertoire knowledge',
      'Incorporating blues vocabulary signals connection to jazz\'s roots',
      'Quoting "Lester Leaps In" signals awareness of swing-era foundations',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Jazz has historically centered male instrumentalists while assigning women primarily vocal roles — a division that persists in representation even as it is increasingly challenged by contemporary musicians.',
    vocalGenderCodes: 'Female jazz singers (Ella, Billie, Sarah) occupy the genre\'s most commercially visible roles. Male vocalists (Sinatra, Nat King Cole, Chet Baker) are fewer and often double as instrumentalists. Scat singing has been one space where vocalists demonstrate instrumental-level virtuosity.',
    physicalityInPerformance: 'Jazz performance is physically grounded in breath control (horns, voice), hand independence (piano, drums), and postural endurance (bassists standing for hours). The body\'s relationship to the instrument shapes phrasing — a drummer\'s reach determines cymbal choices.',
    genderNarratives: 'The Great American Songbook often frames women as objects of romantic longing and men as world-weary wanderers. Contemporary jazz lyricists and vocalists like Cécile McLorin Salvant actively recontextualize these narratives.',
    subversionExamples: [
      'Mary Lou Williams composing and arranging for major big bands in the 1940s',
      'Alice Coltrane\'s spiritual harp and keyboard innovations in the late 1960s',
      'Esperanza Spalding winning Grammy Album of the Year as a bassist-vocalist-composer',
      'Terri Lyne Carrington leading ensembles and winning Grammys as a drummer-producer',
      'Matana Roberts\'s avant-garde multi-genre "Coin Coin" project reframing jazz narrative',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'A 120 BPM swing tune feels completely different from 120 BPM in any other genre — it bounces, breathes, and stretches time. Jazz tempo is psychological, not mechanical.',
    psychologicalTempo: 'Jazz tempo perception is shaped by the swing ratio, the density of harmonic rhythm, and the soloist\'s note choices. A sparse Miles Davis solo over fast changes feels meditative; a dense Coltrane solo over a slow vamp feels urgent.',
    weightAndMomentum: 'Swing gives jazz a forward-leaning momentum that makes medium tempos feel propulsive. The walking bass pulls the music forward while the laid-back soloist creates a stretching tension — the music exists in this push-pull.',
    urgencyScale: 'Ballad (60-80 BPM): contemplative, heavy, each note weighted. Medium swing (120-160 BPM): conversational, buoyant, the sweet spot. Up-tempo (200-300 BPM): exhilarating, virtuosic, where technique meets adrenaline.',
    comparisonToSameBPM: 'A jazz tune at 140 BPM swings and breathes where a rock tune at 140 BPM drives and pounds. The same numerical tempo in jazz has more vertical bounce and horizontal elasticity — the time is alive, not metronomic.',
  },

  mistakeConventions: {
    overview: '"There are no wrong notes in jazz, only notes that are one fret away from the right one" — this philosophy means jazz celebrates recovery, recontextualization, and the discovery that emerges from unexpected choices.',
    toleratedImperfections: [
      'Cracked notes on trumpet or saxophone — the effort is audible and human',
      'Tempo fluctuations during collective improvisation — breathing together isn\'t mechanical',
      'Wrong chord in a comping pattern — instantly reharmonized as a substitution',
      'Memory slips on a standard\'s bridge — covered by confident harmonic navigation',
      'Squeaks and overtones — acoustic instruments are allowed to sound physical',
    ],
    celebratedFlaws: [
      'Miles Davis\'s "wrong" notes that became signature melodic choices',
      'Thelonious Monk\'s deliberate dissonances and rhythmic stumbles that defined his style',
      'Chet Baker\'s fragile, imperfect tone that conveyed vulnerability',
      'Billie Holiday\'s limited range and declining voice that deepened emotional impact',
      'Charles Mingus\'s raw, aggressive bass tone that prioritized expression over polish',
    ],
    overproductionRisks: [
      'Pitch correction destroys the micro-tuning that gives jazz its emotional color',
      'Grid quantization kills the swing feel entirely',
      'Excessive reverb obscures the intimate, present quality of jazz recording',
      'Overdub-heavy sessions lose the conversational spontaneity between musicians',
      'Slick mixing flattens the dynamic range that gives jazz its drama',
    ],
    authenticRoughness: 'The Rudy Van Gelder Blue Note sound IS jazz recording — slightly hot levels, room bleed between instruments, and the audible mechanics of performance. Jazz recordings that sound too clean feel sterile and lifeless.',
  },

  referenceTracks: [
    {
      title: 'Tight',
      artist: 'Esperanza Spalding',
      year: 2021,
      whyExemplary: 'Jazz/funk/R&B fusion from Songwrights Apothecary Lab — Spalding treats composition as medicine, each song designed for specific emotional/physical healing.',
      structuralNotes: 'Through-composed with recurring motifs rather than standard head-solo-head. Bass and voice intertwine as equal melodic partners. Rhythmic feel shifts between funk pocket and free time.',
      craftHighlight: 'The compositional framework (songs as prescriptions) gives creative constraints that produce focused, intentional writing — every note serves the therapeutic intent.',
    },
    {
      title: 'Unerased',
      artist: 'Ambrose Akinmusire',
      year: 2021,
      whyExemplary: 'Post-bop trumpet composition that confronts erasure of Black history through musical architecture — the form itself embodies resistance.',
      structuralNotes: 'Episodic structure: composed sections alternate with guided improvisation. Trumpet states themes that the ensemble develops. Dynamic range from whisper to full cry.',
      craftHighlight: 'Thematic development as storytelling — melodic fragments introduced early return transformed, mirroring how history resurfaces in altered forms.',
    },
    {
      title: 'Alive',
      artist: 'Jon Batiste',
      year: 2022,
      whyExemplary: 'Grammy Album of the Year track that channels New Orleans second-line energy into a studio recording without losing the street-parade spontaneity.',
      structuralNotes: 'Head-verse-chorus structure unusual for jazz — marries pop accessibility with jazz harmony. Horn section arrangement evokes brass band tradition. Call-and-response chorus.',
      craftHighlight: 'Genre fluency as compositional tool — Batiste moves between jazz, gospel, funk, and pop within a single song without any transition feeling forced.',
    },
    {
      title: 'Saudade',
      artist: 'Brandee Younger',
      year: 2021,
      whyExemplary: 'Harp-led jazz that reimagines the instrument\'s role from orchestral color to lead voice. The composition makes space for the harp\'s unique timbral qualities.',
      structuralNotes: 'Through-composed with improvised sections. Harp states melody, rhythm section provides harmonic cushion. Extended harmonic palette with Brazilian bossa influence.',
      craftHighlight: 'Instrument-specific writing — the composition exploits what only a harp can do (glissandi, pedal changes, overtone cascades) rather than treating it as a piano substitute.',
    },
    {
      title: 'The Garden',
      artist: 'Shabaka',
      year: 2024,
      whyExemplary: 'Spiritual jazz reimagined through shakuhachi and clarinet — Shabaka Hutchings\' solo project strips jazz to its meditative essence.',
      structuralNotes: 'Minimal structure — long-form breath-driven phrases over drone or silence. No traditional rhythm section. Sections defined by breath cycles rather than bar counts.',
      craftHighlight: 'Breath as structural element — the physical act of breathing determines phrase length and silence placement, making the body the compositional framework.',
    },
    {
      title: 'Libations',
      artist: 'Immanuel Wilkins',
      year: 2022,
      whyExemplary: 'Contemporary alto saxophone composition from one of jazz\'s brightest young voices — spiritual depth with modern harmonic language.',
      structuralNotes: 'Head-solo-head with extended collective improvisation sections. Alto sax leads a piano-less quartet. Rhythmic feel alternates between straight 8ths and swing.',
      craftHighlight: 'Spiritual jazz vocabulary updated for the 2020s — ancestral invocation through modern harmonic language. The quartet format forces intimate musical conversation.',
    },
    {
      title: 'New York Is Killing Me',
      artist: 'Samara Joy',
      year: 2022,
      whyExemplary: 'Grammy Best New Artist\'s vocal jazz interpretation that channels classic Sarah Vaughan-era phrasing with genuine generational freshness.',
      structuralNotes: 'Standard vocal jazz form: intro-head-solo section-head-outro. Trio accompaniment (piano, bass, drums). Joy\'s voice replaces the horn as lead instrument.',
      craftHighlight: 'Phrasing as composition — Joy\'s rhythmic placement behind and ahead of the beat creates melodic variations that make the standard feel newly written.',
    },
    {
      title: 'Canopy',
      artist: 'Mary Halvorson',
      year: 2023,
      whyExemplary: 'Avant-garde guitar composition for large ensemble that won a MacArthur "Genius Grant" — pushes jazz writing into orchestral territory.',
      structuralNotes: 'Through-composed for 18-piece ensemble with improvised solo sections. Complex time signatures and layered counterpoint. Sections overlap rather than alternate cleanly.',
      craftHighlight: 'Orchestration as composition — the arrangement IS the piece. Halvorson writes for specific musicians\' improvisational tendencies, building their likely choices into the structure.',
    },
    {
      title: 'Sankofa',
      artist: 'Christian Scott aTunde Adjuah',
      year: 2023,
      whyExemplary: 'Stretch music that fuses jazz trumpet tradition with West African rhythmic concepts — the Sankofa principle (reaching back to move forward) as compositional method.',
      structuralNotes: 'Layered rhythmic cycles that phase in and out of alignment. Trumpet melody floats over polyrhythmic foundation. Form emerges from rhythmic convergence points.',
      craftHighlight: 'African rhythmic philosophy applied to jazz form — instead of Western harmonic progression driving the structure, interlocking rhythmic patterns create the architecture.',
    },
    {
      title: 'Is It Real',
      artist: 'Kurt Rosenwinkel',
      year: 2022,
      whyExemplary: 'Jazz guitar harmony at its most sophisticated — chord voicings that sound like no other instrument could produce them, with melodic lines woven through.',
      structuralNotes: 'Head-solo-head with reharmonized final head. Guitar-led quartet. Extended chord voicings create orchestral fullness from four musicians.',
      craftHighlight: 'Guitar-specific harmonic writing — exploits open strings, unusual voicings, and the instrument\'s sustain characteristics to create harmonies impossible on piano.',
    },
    {
      title: 'Sun Song',
      artist: 'Nubya Garcia',
      year: 2024,
      whyExemplary: 'UK jazz/dub/spiritual fusion from the London scene\'s leading tenor saxophonist — brings dub production aesthetics into acoustic jazz composition.',
      structuralNotes: 'Extended form with dub-influenced production breaks. Saxophone melody over shifting rhythmic feels — from straight-ahead swing to dub reggae to Afrobeat.',
      craftHighlight: 'Production as composition — dub delay and reverb effects become structural elements rather than decoration, creating new melodic content from the original statement.',
    },
    {
      title: 'Senses of Soul',
      artist: 'Makaya McCraven',
      year: 2023,
      whyExemplary: 'Beat-science meets orchestral jazz — McCraven\'s approach of recording live musicians then editing/layering the results creates compositions that couldn\'t exist in real-time.',
      structuralNotes: 'Collaged from live recordings — the "composition" happens in post-production. Orchestral strings meet hip-hop-influenced drum patterns. Form is non-repeating.',
      craftHighlight: 'Post-production as compositional tool — the arrangement emerges from editing live improvisations together, creating structures that transcend what any single performance could achieve.',
    },
    {
      title: 'All Blues',
      artist: 'Cécile McLorin Salvant',
      year: 2022,
      whyExemplary: 'Reimagined Miles Davis standard that transforms a modal jazz cornerstone into a theatrical vocal performance — recomposition through interpretation.',
      structuralNotes: 'Takes the 12-bar blues form and stretches it through tempo changes, rubato sections, and dramatic pauses. Voice-piano duo format.',
      craftHighlight: 'Reinterpretation as original composition — Salvant\'s rhythmic and dynamic choices are so radical they create a new piece from familiar material.',
    },
    {
      title: 'Pluto',
      artist: 'Flying Lotus ft. Brandon Coleman',
      year: 2023,
      whyExemplary: 'Nu-jazz/electronic fusion that brings jazz improvisation into beat-driven electronic production without either element compromising.',
      structuralNotes: 'Beat-driven structure with improvised keyboard solos over evolving electronic textures. Form follows the beat\'s evolution rather than traditional jazz sections.',
      craftHighlight: 'Electronic production and jazz improvisation as equal partners — neither is decoration for the other. The beat breathes and shifts like a jazz rhythm section.',
    },
    {
      title: 'Retrospection',
      artist: 'Joel Ross',
      year: 2022,
      whyExemplary: 'Vibraphone-led composition that revives the instrument\'s centrality in jazz while pushing its harmonic language forward.',
      structuralNotes: 'Head-solo-head with extended vibraphone improvisation. Quintet format with vibes as lead voice. Complex written melodies that sound improvised.',
      craftHighlight: 'Instrument revival through modern writing — the vibraphone gets compositions worthy of its unique sustain and shimmer, not warmed-over Milt Jackson charts.',
    },
    {
      title: 'Reflections',
      artist: 'GoGo Penguin',
      year: 2022,
      whyExemplary: 'Piano trio composition that bridges jazz, electronic, and post-rock — the Manchester trio\'s writing treats acoustic instruments as a synthesizer ensemble.',
      structuralNotes: 'Build-based structure more akin to electronic music: intro-build-peak-release. Piano provides melodic and rhythmic elements simultaneously. Drums play electronic-influenced patterns.',
      craftHighlight: 'Acoustic instruments performing electronic music\'s structural logic — repetition, layering, and gradual transformation replace jazz\'s solo-based architecture.',
    },
    {
      title: 'Siembra',
      artist: 'Miguel Zenón',
      year: 2024,
      whyExemplary: 'Latin jazz composition integrating Puerto Rican plena and bomba rhythms with modern jazz harmony — cultural specificity as compositional rigor.',
      structuralNotes: 'Alternates between plena/bomba rhythmic sections and modern jazz harmony. Alto saxophone melody incorporates folk song contours. Ensemble passages written in tight unison.',
      craftHighlight: 'Ethnomusicological depth as creative fuel — Zenón\'s research into specific Puerto Rican rhythmic traditions produces compositions that no amount of generic "Latin jazz" could achieve.',
    },
    {
      title: 'Culling',
      artist: 'James Brandon Lewis',
      year: 2022,
      whyExemplary: 'Spiritual/free jazz saxophone composition that channels collective trauma into structured catharsis. Raw power with compositional discipline.',
      structuralNotes: 'Through-composed with sections of guided collective improvisation. Tenor saxophone leads with authority. Dynamic arc builds from contemplative to ecstatic.',
      craftHighlight: 'Controlled intensity — the composition provides a framework for emotional release without descending into chaos. Structure and freedom in productive tension.',
    },
    {
      title: 'Promises (Movement 6)',
      artist: 'Floating Points, Pharoah Sanders & London Symphony Orchestra',
      year: 2021,
      whyExemplary: 'Ambient/spiritual jazz masterwork — a single 46-minute composition that gives the legendary Pharoah Sanders space to play over glacial orchestral movement.',
      structuralNotes: 'Nine movements built on a single repeating harpsichord motif. Sanders\' saxophone enters and exits freely. Orchestral swells provide harmonic context. Form unfolds over 46 minutes.',
      craftHighlight: 'Patience as compositional virtue — the piece gives each element vast space. Sanders\' few notes carry enormous weight because the composition earns every one of them.',
    },
    {
      title: 'The Code',
      artist: 'Terri Lyne Carrington',
      year: 2022,
      whyExemplary: 'Progressive jazz drumming composition from the first woman to win Grammy for Best Jazz Instrumental Album — reshapes who writes jazz canon.',
      structuralNotes: 'Suite-like structure with movements connected by drum transitions. Ensemble writing features shifting lead voices. Complex odd-meter grooves feel natural.',
      craftHighlight: 'Drummer-as-composer perspective — the rhythmic structure IS the composition rather than support for melody. Groove patterns generate harmonic and melodic content.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: ['jazz', 'swing', 'improvisation', 'saxophone', 'piano trio', 'walking bass', 'sophisticated'],
    avoidKeywords: ['EDM', 'heavy metal', 'auto-tune', 'pop production', 'distorted', 'trap beats'],
    promptTemplate: '[sub-genre] jazz, [tempo] BPM, [instrumentation], [mood], [feel: swing/Latin/straight]',
    tips: [
      'Specify the sub-genre: bebop, cool, hard bop, fusion, smooth, etc.',
      'Describe the instrumentation: piano trio, quartet with sax, big band',
      'Mention the feel: swinging, ballad, Latin, fusion groove',
      'Reference a mood: sophisticated, melancholic, energetic, intimate',
      'Include "improvisation" if you want solo sections',
      'Describe the harmonic complexity: simple, complex, modal, chromatic',
    ],
  },
};
