import type { GenreGuide } from './types';

export const METAL_GUIDE: GenreGuide = {
  id: 'metal',
  name: 'Metal',
  language: 'English',

  sonicPalette: {
    overview: 'Heavy, aggressive, and powerful. Metal is defined by distorted guitars, thunderous drums, and intense vocal delivery. The sound is designed to be overwhelming — walls of guitar distortion, double bass drumming, and bass frequencies that shake the floor.',
    timbre: [
      'Heavily distorted electric guitars (high gain)',
      'Double bass kick drums',
      'Aggressive snare with ring',
      'Growling, screaming, or powerful clean vocals',
      'Deep, distorted bass guitar',
      'Cymbal crashes and china cymbals',
      'Palm-muted guitar chugging',
      'Harmonized guitar leads',
    ],
    texture: 'Dense and aggressive — multiple guitar tracks create a wall of sound. The low end is massive (bass guitar + kick drums). Mid-range is dominated by distorted guitars. Vocal cuts through with intensity.',
    tonality: 'Minor keys and chromatic movement. Drop tunings (Drop D, Drop C, Drop B) for heavier sound. Diminished and tritone intervals create darkness and tension. Power chords dominate.',
    signatureSounds: [
      'Palm-muted guitar chug',
      'Pinch harmonics (squeals)',
      'Double bass drum barrage',
      'Guitar harmonies in 3rds',
      'Wah-wah solos',
      'Blast beats',
      'Breakdown riffs with open string chugs',
    ],
  },

  rhythmAndGroove: {
    overview: 'Aggressive, precise, and physically demanding. Metal drumming is among the most technical in all music. The rhythm drives intensity through speed, power, and complexity.',
    bpmRange: { min: 80, max: 250, sweet: 140 },
    feel: 'Powerful and relentless. The groove can be headbanging mid-tempo, thrashing speed, or crushing slow doom. Precision is valued — tight playing between all instruments.',
    swing: 'None — metal is deliberately straight and aggressive. Any looseness is intentional groove, not swing. Machine-like precision is valued.',
    syncopation: 'Complex — metal uses odd time signatures, polyrhythmic patterns, and syncopated riffs. The interplay between guitar riffs and drums creates intricate rhythmic patterns.',
    grooveArchetype: 'Headbanging stomp, thrash gallop, blast beat assault, or doom crawl',
    rhythmicSignatures: [
      'Double bass drumming (continuous 16th notes)',
      'Blast beats (snare and kick alternating at extreme speed)',
      'Galloping rhythm (triplet feel — Iron Maiden)',
      'Breakdown: half-time open-note chugs',
      'Odd time signatures (7/8, 5/4, 11/8)',
      'Palm-muted staccato riffs',
      'Groove metal bounce (Pantera-style)',
    ],
  },

  harmonicLanguage: {
    overview: 'Dark, dissonant, and powerful. Metal harmony draws from minor scales, diminished intervals, and chromatic movement to create tension and aggression. Power chords and riff-based writing dominate.',
    scales: ['Natural Minor', 'Harmonic Minor', 'Phrygian', 'Locrian', 'Chromatic', 'Blues Scale', 'Diminished'],
    chordProgressions: [
      'i – bII (Phrygian movement)',
      'i – bVI – bVII – i (minor rock)',
      'Power chord riffs (non-functional harmony)',
      'Chromatic descent',
      'Tritone-based riffs (diminished 5th)',
      'Pedal point with chromatic upper movement',
      'i – iv – bVI – V (harmonic minor cadence)',
    ],
    harmonyNotes: 'Power chords (root + 5th) are the foundation — no major or minor quality allows tonal ambiguity. Drop tunings extend the range downward. Harmonized guitar solos in 3rds and 5ths. Tritone (the "devil\'s interval") is a metal staple.',
    modality: 'Predominantly minor. Phrygian and Locrian for extreme darkness. Harmonic minor for neoclassical elements. The tritone and diminished intervals define metal\'s dark character.',
  },

  songStructure: {
    overview: 'Riff-driven structure — metal songs are built around guitar riffs that define each section. The riff is king, and song structure serves the riffs. Complex structures in progressive metal, simple in thrash.',
    form: 'Intro Riff – Verse – Pre-Chorus – Chorus – Verse – Chorus – Solo – Bridge/Breakdown – Chorus – Outro',
    sections: ['Intro Riff', 'Verse', 'Pre-Chorus', 'Chorus', 'Interlude', 'Guitar Solo', 'Breakdown', 'Final Chorus', 'Outro'],
    arrangement: 'Riff changes define sections. Intensity builds through the song. Breakdowns provide crushing contrast. Guitar solos are showcase moments. The arrangement rewards repeated listening.',
    introOutro: 'Intros: clean guitar building to distortion, dramatic riff statement, or atmospheric build. Outros: extended riff, feedback, or dramatic final note. Some start at full intensity.',
    barLengths: 'Verses: 8-16 bars. Chorus: 8 bars. Solo: 8-32 bars. Breakdown: 4-8 bars. Total: 3-7 minutes (doom: 8-15+, prog: 5-20+).',
    hookPlacement: 'The main riff IS the hook — it\'s what people remember. Chorus melodies serve as vocal hooks. Guitar solo as a memorable compositional element.',
  },

  vocalDelivery: {
    overview: 'Extreme and varied — metal vocals span from operatic clean singing to guttural death growls. The voice is used as an instrument of intensity, matching the aggression of the instruments.',
    phrasing: 'Rhythmically locked to the riff. Aggressive, staccato phrasing in verses. More sustained, melodic phrasing in choruses (when clean). Growls and screams follow rhythmic patterns.',
    affect: 'Intense — anger, power, darkness, anguish, triumph. Metal vocals convey extreme emotions. Even melodic metal singing has an edge of intensity.',
    techniques: [
      'Death growl (guttural low vocal)',
      'Black metal shriek (high-pitched rasp)',
      'Screaming (hardcore/metalcore)',
      'Operatic clean singing (power metal)',
      'Aggressive belt/shout',
      'Clean-to-scream transitions',
      'Pig squeal (grindcore)',
      'Vocal fry and grit',
    ],
    adlibStyle: 'Minimal — metal is composed, not improvised. Battle cries, crowd commands ("Are you ready?!", "Scream!"), and wordless screams. Less ad-lib, more composed vocal lines.',
    harmony: 'Harmonized clean vocals (power metal, symphonic). Layered growls and screams for thickness. Gang shout choruses. Operatic vocal arrangements in symphonic metal.',
    grit: 'Maximum — grit, distortion, and aggression are the default. Clean vocals in metal still carry edge and power. The voice should match the intensity of the instrumentation.',
  },

  lyricalConventions: {
    overview: 'Metal lyrics explore extreme themes — darkness, mythology, social criticism, war, fantasy, and existential horror. The lyrical content is ambitious, often literary, and unafraid of taboo subjects.',
    themes: [
      'War and battle',
      'Death, mortality, and the occult',
      'Fantasy and mythology',
      'Social injustice and political rage',
      'Inner demons and personal struggle',
      'Horror and the supernatural',
      'Nature and cosmic forces',
      'Rebellion and defiance',
      'Philosophy and existentialism',
    ],
    perspective: 'First person or omniscient narrator. Character-driven narratives. Some sub-genres use concept albums with overarching stories. Second person for confrontational tracks.',
    figurativeLanguage: 'Epic and literary — extended metaphors, mythological allusions, apocalyptic imagery. Nature as destructive force. War and battle metaphors for personal struggle. Dark, vivid imagery.',
    vocabulary: 'Elevated and dramatic — archaic language, literary references, mythological terms. Technical vocabulary in progressive metal. Deliberately provocative in extreme sub-genres.',
    storytellingApproach: 'Narrative and conceptual — metal excels at epic storytelling, concept albums, and character-driven narratives. Each song may be a chapter in a larger story.',
    cliches: [
      'Riding into battle',
      'Darkness/flames/hellfire',
      'Rise from the ashes',
      'The beast within',
      'Apocalypse/end of days',
      'Chains and bondage (metaphorical)',
      'Ancient gods and warriors',
    ],
  },

  productionFingerprint: {
    overview: 'Precise, powerful, and heavy. Metal production balances aggression with clarity — every riff and drum hit must be heard despite the density. Modern metal production is extremely precise, with tight editing and heavy processing.',
    mixAesthetic: 'Dense but clear. Guitars wall the stereo field (hard L/R). Bass and kick share the low end. Vocals cut through the center. Drums are punchy and present. The master is loud and compressed.',
    era: 'Current era: djent influence, progressive complexity, genre-blending (metalcore + electronics), production precision approaching clinical, mix loudness competition.',
    signalChain: 'Guitar: guitar → high-gain amp (Mesa, 5150, Archon) or amp sim → SM57 → EQ → compression. Drums: triggered/replaced kick and snare samples + overheads. Bass: DI + distortion. Vocals: dynamic mic → heavy compression.',
    modernTrends: 'Amp simulation replacing real amps. Drum triggering and sample replacement. Guitar tone matching technology. Increasingly precise editing. Electronic integration (Bring Me the Horizon). Genre fusion.',
  },

  instrumentation: {
    coreInstruments: [
      'Electric guitar (high gain, often 7-8 string)',
      'Bass guitar (often distorted)',
      'Drum kit (double bass pedals essential)',
      'Vocals (clean, growl, scream)',
    ],
    signatureSounds: [
      'High-gain guitar distortion',
      'Double bass kick drum barrage',
      'Pinch harmonics',
      'Down-tuned power chords',
      'Blast beats',
      'Harmonized guitar leads',
      'Breakdown chugs',
    ],
    layering: 'Rhythm guitars: doubled and quad-tracked, panned hard L/R. Lead guitar: center or slightly off-center. Bass: follows guitar or provides counterpoint. Drums: heavily processed with samples layered on acoustic hits.',
    avoidInstruments: [
      'Acoustic instruments as primary (unless acoustic section)',
      'Pop synths and electronic beats (unless industrial/electronic metal)',
      'Smooth jazz instruments',
      'Country instruments',
      'Light, airy sounds',
    ],
  },

  culturalContext: {
    overview: 'Metal is a tribe — one of the most dedicated and loyal fan communities in music. Metal culture values musicianship, authenticity, community, and artistic extremity. The culture has evolved from outsider rebellion to a global brotherhood.',
    origin: 'Late 1960s Birmingham, England — Black Sabbath is widely considered the first metal band. Evolved from blues-rock and psychedelic rock by pushing distortion, heaviness, and dark themes.',
    identity: 'Outsider identity — metal has always been for those who don\'t fit mainstream culture. The community embraces the "other" and provides belonging. Technical musicianship is deeply valued.',
    community: 'Extremely loyal and global. Festival culture (Wacken, Download, Hellfest). Underground scenes in every city. Metal journalism and media. Online communities and forums. Band merch as identity marker.',
    socialFunction: 'Catharsis — metal provides an outlet for aggression, frustration, and dark emotions through music. Community belonging for outsiders. Live shows as collective emotional release.',
    authenticityMarkers: [
      'Technical musicianship',
      'Genuine passion and dedication to the genre',
      'Support for the underground scene',
      'Knowledge of metal history and sub-genres',
      'Live performance intensity',
      'Artistic integrity over commercial appeal',
    ],
  },

  historicalLineage: {
    overview: 'From Black Sabbath\'s first chord to modern djent, metal has continuously pushed the boundaries of heaviness, speed, technicality, and extremity while maintaining its community values.',
    roots: ['Blues Rock', 'Psychedelic Rock', 'Hard Rock', 'Classical Music'],
    evolution: 'Proto-metal and heavy rock (late 60s) → NWOBHM (early 80s) → Thrash (mid 80s) → Death and black metal (late 80s-90s) → Nu-metal (late 90s) → Metalcore and djent (2000s-2010s) → Modern genre fusion (2020s).',
    keyEras: [
      '1968-1975: Proto-metal (Black Sabbath, Deep Purple)',
      '1979-1984: NWOBHM (Iron Maiden, Judas Priest)',
      '1983-1991: Thrash (Metallica, Slayer, Megadeth, Anthrax)',
      '1988-1995: Death metal and black metal explosion',
      '1997-2004: Nu-metal mainstream (Korn, Slipknot)',
      '2005-present: Metalcore, djent, progressive, genre fusion',
    ],
    influencedBy: ['Blues', 'Classical', 'Punk', 'Progressive Rock', 'Jazz (fusion)'],
    influenced: ['Hardcore Punk', 'Grunge', 'Industrial', 'Nu-Metal', 'Metalcore', 'Post-Metal'],
  },

  subGenres: [
    {
      name: 'Heavy Metal',
      description: 'The original — powerful riffs, soaring vocals, and anthemic choruses. The foundation everything else is built on.',
      distinguishingFeatures: ['Powerful, melodic vocals', 'Memorable riffs', 'Guitar solos', 'Anthemic choruses', 'Classic distortion tones'],
      bpmRange: { min: 100, max: 160 },
      keyArtists: ['Iron Maiden', 'Judas Priest', 'Black Sabbath', 'Dio', 'Ozzy Osbourne'],
      productionNotes: 'Classic distortion tones. Prominent vocals. Melodic guitar solos. Driving rhythm section. Not too heavy, not too polished.',
      lyricNotes: 'Epic themes — war, mythology, darkness, triumph. Anthemic and powerful. Storytelling and imagery.',
      sunoPromptKeywords: ['heavy metal', 'classic metal', 'NWOBHM', 'metal anthem', 'power riffs', 'soaring vocals'],
    },
    {
      name: 'Thrash Metal',
      description: 'Fast, aggressive, and technically demanding. Thrash combines metal heaviness with punk speed and attitude.',
      distinguishingFeatures: ['Fast tempo', 'Aggressive riffing', 'Political/social lyrics', 'Technical guitar work', 'Shouted vocals'],
      bpmRange: { min: 150, max: 220 },
      keyArtists: ['Metallica', 'Slayer', 'Megadeth', 'Anthrax', 'Exodus'],
      productionNotes: 'Fast, tight performances. Aggressive guitar tone. Driving double bass. Raw energy. Mix should be powerful but not overly polished.',
      lyricNotes: 'War, social injustice, corruption, violence, death. Political and confrontational. Technical wordplay.',
      sunoPromptKeywords: ['thrash metal', 'thrash', 'speed metal', 'aggressive', 'fast metal', 'Bay Area thrash'],
    },
    {
      name: 'Death Metal',
      description: 'Extreme metal with guttural vocals, blast beats, and complex, dissonant riffing. Pushes heaviness and technicality to extremes.',
      distinguishingFeatures: ['Guttural growl vocals', 'Blast beats', 'Extremely heavy and technical', 'Dissonant, chromatic riffs', 'Complex song structures'],
      bpmRange: { min: 120, max: 250 },
      keyArtists: ['Death', 'Cannibal Corpse', 'Morbid Angel', 'Opeth', 'Gojira'],
      productionNotes: 'Extreme low tuning. Blast beats and double bass. Guttural vocal recording. Dense, heavy mix. Technical precision in editing.',
      lyricNotes: 'Death, gore, horror, philosophy, existentialism. Can be gratuitous or intellectual. Often abstract and metaphorical.',
      sunoPromptKeywords: ['death metal', 'brutal', 'guttural', 'blast beats', 'extreme metal', 'technical death metal'],
    },
    {
      name: 'Black Metal',
      description: 'Raw, atmospheric, and deliberately lo-fi. Black metal creates a cold, hypnotic atmosphere through tremolo picking, blast beats, and shrieked vocals.',
      distinguishingFeatures: ['Shrieked/raspy vocals', 'Tremolo-picked guitar riffs', 'Lo-fi production aesthetic', 'Blast beats', 'Cold, atmospheric mood'],
      bpmRange: { min: 130, max: 200 },
      keyArtists: ['Mayhem', 'Burzum', 'Emperor', 'Darkthrone', 'Deafheaven'],
      productionNotes: 'Deliberately raw production. Tremolo-picked guitars. Cold, thin guitar tone. Blast beats. Atmospheric keyboards optional. Lo-fi aesthetic is intentional.',
      lyricNotes: 'Nature, darkness, anti-religion, misanthropy, Norse mythology. Atmospheric and evocative. Philosophical or nihilistic.',
      sunoPromptKeywords: ['black metal', 'raw black metal', 'atmospheric', 'cold', 'tremolo picking', 'lo-fi metal', 'Nordic'],
    },
    {
      name: 'Power Metal',
      description: 'Melodic, uplifting, and epic. Power metal combines fast tempos with soaring clean vocals, symphonic elements, and fantasy themes.',
      distinguishingFeatures: ['Soaring clean vocals', 'Fast, melodic guitar work', 'Symphonic and orchestral elements', 'Epic, uplifting mood', 'Fantasy/heroic themes'],
      bpmRange: { min: 140, max: 180 },
      keyArtists: ['Helloween', 'Blind Guardian', 'DragonForce', 'Sabaton', 'Stratovarius'],
      productionNotes: 'Bright, melodic guitar tones. Keyboard/orchestral layers. Fast double bass. Soaring vocal production. Epic, cinematic sound.',
      lyricNotes: 'Fantasy, heroism, battle, quests, mythology. Uplifting and anthemic. Tolkien-esque world-building.',
      sunoPromptKeywords: ['power metal', 'epic metal', 'symphonic', 'fantasy metal', 'melodic metal', 'soaring vocals', 'fast'],
    },
    {
      name: 'Doom Metal',
      description: 'Slow, heavy, and crushingly dark. Doom metal slows everything down — massive riffs, funereal tempos, and an atmosphere of despair.',
      distinguishingFeatures: ['Extremely slow tempo', 'Massive, heavy riffs', 'Dark, despairing atmosphere', 'Extended song lengths', 'Clean or growled vocals'],
      bpmRange: { min: 40, max: 80 },
      keyArtists: ['Black Sabbath', 'Electric Wizard', 'Candlemass', 'Sleep', 'Bell Witch'],
      productionNotes: 'Massive, down-tuned guitar tone. Slow, crushing riffs. Heavy reverb and sustain. Sparse arrangements. Let the heaviness breathe.',
      lyricNotes: 'Despair, doom, death, occult, existential dread. Slow, deliberate lyrical delivery. Dark poetry.',
      sunoPromptKeywords: ['doom metal', 'slow metal', 'heavy', 'crushing', 'sludge', 'stoner doom', 'funereal'],
    },
    {
      name: 'Metalcore',
      description: 'Fusion of metal and hardcore punk — aggressive breakdowns, screamed and clean vocal alternation, and technical guitar work.',
      distinguishingFeatures: ['Clean/scream vocal alternation', 'Heavy breakdowns', 'Hardcore punk influence', 'Technical guitar work', 'Emotional, confessional lyrics'],
      bpmRange: { min: 100, max: 180 },
      keyArtists: ['Killswitch Engage', 'Parkway Drive', 'August Burns Red', 'Architects', 'Bring Me the Horizon'],
      productionNotes: 'Tight, precise production. Heavy breakdowns with palm-muted chugs. Clean and screamed vocal layers. Electronic elements in modern metalcore. Loud, compressed master.',
      lyricNotes: 'Personal struggle, emotional catharsis, social issues. Confessional and intense. Empowerment through adversity.',
      sunoPromptKeywords: ['metalcore', 'hardcore metal', 'breakdown', 'scream', 'clean vocals', 'heavy', 'aggressive'],
    },
    {
      name: 'Nu-Metal',
      description: 'Metal fused with hip-hop, electronic, and alternative influences. Downtuned guitars, DJ scratching, rapped and screamed vocals.',
      distinguishingFeatures: ['Hip-hop rhythmic influence', 'DJ/turntable elements', 'Rap-metal vocal style', 'Downtuned, bouncy riffs', '90s/2000s aesthetic'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Korn', 'Linkin Park', 'Slipknot', 'Deftones', 'System of a Down'],
      productionNotes: 'Downtuned, bouncy guitar riffs. DJ scratching and samples. Blend rap and scream vocals. Electronic elements. Hip-hop drum patterns mixed with metal.',
      lyricNotes: 'Inner pain, alienation, anger, abuse. Emotionally raw and confessional. Teenage angst and social frustration.',
      sunoPromptKeywords: ['nu-metal', 'rap metal', 'alternative metal', 'downtuned', 'DJ metal', 'heavy alternative'],
    },
    {
      name: 'Progressive Metal',
      description: 'Technically complex metal with progressive rock influences — odd time signatures, extended compositions, and virtuoso musicianship.',
      distinguishingFeatures: ['Complex time signatures', 'Virtuoso musicianship', 'Extended compositions', 'Progressive song structures', 'Technical precision'],
      bpmRange: { min: 80, max: 200 },
      keyArtists: ['Dream Theater', 'Tool', 'Opeth', 'Meshuggah', 'Between the Buried and Me'],
      productionNotes: 'Clean, precise production. Every note must be audible. Complex arrangements require careful mixing. Dynamic range important. Technical playing demands clarity.',
      lyricNotes: 'Conceptual, philosophical, introspective. Concept albums. Science, spirituality, consciousness. Literary and complex.',
      sunoPromptKeywords: ['progressive metal', 'prog metal', 'technical', 'complex', 'odd time', 'virtuoso', 'epic'],
    },
    {
      name: 'Symphonic Metal',
      description: 'Metal with orchestral arrangements, operatic vocals, and cinematic production. Combines the power of metal with the grandeur of classical music.',
      distinguishingFeatures: ['Full orchestral arrangements', 'Operatic female vocals', 'Cinematic, epic production', 'Classical music influence', 'Dramatic dynamics'],
      bpmRange: { min: 100, max: 160 },
      keyArtists: ['Nightwish', 'Epica', 'Within Temptation', 'Therion', 'Kamelot'],
      productionNotes: 'Blend metal instruments with orchestral samples/recordings. Operatic vocal production. Cinematic mixing. Grand, sweeping arrangements. Balance metal and classical elements.',
      lyricNotes: 'Epic, dramatic, operatic. Fantasy, mythology, nature, romance. Theatrical and grand. Poetic and archaic language.',
      sunoPromptKeywords: ['symphonic metal', 'orchestral metal', 'operatic', 'epic', 'cinematic metal', 'gothic metal'],
    },
    {
      name: 'Djent',
      description: 'Modern progressive metal characterized by heavily palm-muted, rhythmically complex guitar patterns, polyrhythmic grooves, and clean production.',
      distinguishingFeatures: ['Rhythmically complex palm-muted riffs', 'Polyrhythmic patterns', 'Extended range guitars (7-8 string)', 'Clean, precise production', 'Blend of heavy and atmospheric'],
      bpmRange: { min: 90, max: 160 },
      keyArtists: ['Meshuggah', 'Periphery', 'Animals as Leaders', 'TesseracT', 'Polyphia'],
      productionNotes: 'Precise, clinical production. Extended range guitars. Polyrhythmic drum programming. Clean and heavy sections alternate. Modern amp simulation tones.',
      lyricNotes: 'Introspective, philosophical, abstract. Consciousness and perception. Modern existentialism. Can be instrumental.',
      sunoPromptKeywords: ['djent', 'progressive metal', 'polyrhythmic', '8-string guitar', 'modern metal', 'technical', 'groovy'],
    },
    {
      name: 'Groove Metal',
      description: 'Mid-tempo, riff-heavy metal built on headbanging grooves. Combines thrash aggression with a slower, more deliberate rhythmic approach.',
      distinguishingFeatures: ['Mid-tempo headbanging grooves', 'Heavy, bouncy riffs', 'Aggressive vocals', 'Groove-focused rather than speed-focused', 'Powerful rhythm section'],
      bpmRange: { min: 90, max: 140 },
      keyArtists: ['Pantera', 'Lamb of God', 'Sepultura', 'Machine Head', 'DevilDriver'],
      productionNotes: 'Heavy, punchy guitar tone. Groove-focused drum patterns. Powerful bass presence. Tight, aggressive mix. The riff groove is everything.',
      lyricNotes: 'Aggression, power, defiance. Personal strength. Anti-authority. Confrontational and intense.',
      sunoPromptKeywords: ['groove metal', 'heavy groove', 'headbanging', 'mid-tempo metal', 'powerful riffs', 'aggressive'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Metal fans are among the most dedicated in music — loyal, knowledgeable, and community-driven. The culture values musicianship, authenticity, and commitment to the genre.',
    fanExpectations: [
      'Technical musicianship and skill',
      'Authentic intensity and dedication',
      'Powerful live performances',
      'Knowledge and respect for the genre',
      'Artistic integrity',
      'Physical heaviness and energy',
    ],
    gatekeeping: 'High — metal has extensive sub-genre taxonomy and strong opinions about "real" metal. Elitism exists but so does welcoming community. Band knowledge is valued.',
    livePerformance: 'Intense — mosh pits, headbanging, crowd surfing, wall of death. The live show is the ultimate metal experience. Sound quality and volume matter. Festival culture is strong.',
    fashionAndAesthetic: 'Black clothing, band t-shirts, battle vests (denim with patches), leather, boots. Long hair. Band merch as identity. Each sub-genre has aesthetic variations.',
    crossoverPotential: 'Limited but growing — metalcore/post-metal crosses into mainstream. Nu-metal had massive crossover. Traditional metal remains niche but passionately supported.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Metal micro-timing is about machine-tight precision — every palm-muted chug, every double-bass hit, every blast beat must lock together with mechanical accuracy. The "feel" of metal IS tightness. When the guitarist and drummer are perfectly synchronized on a syncopated riff, it creates a physical impact that looser playing cannot achieve.',
    quantizationDeviation: 'Minimal — modern metal is often edited to near-grid perfection. Drums may be sample-replaced and tightened. Guitar tracks are comp-edited to eliminate timing variation. In extreme sub-genres (death metal, djent), timing precision IS the aesthetic. Doom metal is the exception: tempo flexibility creates its crushing weight.',
    aheadBehindBeat: 'Metal sits directly on the beat with aggressive attack — hitting the beat hard, not laying back. Thrash pushes slightly ahead, creating urgency. Doom sits behind, creating heaviness. Groove metal has a deliberate, locked-in pocket. The precision of the beat placement is what makes metal feel "heavy" rather than merely "loud."',
    humanizationMarkers: [
      'Double bass drum patterns with metronomic consistency as a technical display',
      'Synchronized palm-muting between rhythm guitars and bass as a single rhythmic unit',
      'Blast beats where snare and kick alternate with drum-machine accuracy',
      'Pinch harmonics that land on exact rhythmic subdivisions',
      'Breakdowns where the entire band hits the same rhythmic accents in unison',
    ],
    genreSpecificFeel: 'The "Meshuggah feel" — polyrhythmic guitar patterns against a steady pulse, creating disorientation that resolves. The "Pantera groove" — mid-tempo riffs with a headbanging bounce that locks the whole body. The "blast beat wall" — so fast it becomes textural rather than rhythmic. Each sub-genre\'s timing precision serves a different physical response.',
  },

  silenceAndSpace: {
    overview: 'Metal is wall-of-sound — but the breakdown uses silence as a weapon. The moment before a breakdown hits, when everything stops and a single palm-muted chug rings out, is one of the most powerful uses of silence in any genre. Metal earns its density by deploying absence at strategic moments.',
    negativeSpaceRole: 'Devastating when used — metal\'s density makes silence feel like a vacuum. A full stop before a riff re-entry creates physical anticipation. The breakdown relies on space between chugs for its crushing impact. Doom metal uses extended space between riffs to let the heaviness resonate.',
    breathingPatterns: 'Clean arpeggiated interludes or atmospheric passages provide the only genuine breathing room — the contrast makes the return to distortion devastating. Pre-chorus builds stack palm-muted chugs and double bass into the full-band assault. Breakdowns strip to staccato single-note chugs with silence between each hit, using rhythmic breathing rather than dynamic breathing. Without these clean or breakdown contrasts, the wall of distortion becomes fatiguing instead of powerful.',
    dynamicContrast: 'Extreme when done well — clean arpeggios to full distortion, whispered vocals to death growl, single note to wall of guitars. The contrast ratio in metal is among the highest in any genre. The quiet moment exists solely to make the heavy moment heavier.',
    whatIsDeliberatelyAbsent: [
      'Everything stopping before a breakdown — the crowd holds its breath',
      'Clean guitar arpeggios before the distortion kicks back in',
      'A single drum hit in silence, then another, building the re-entry',
      'Vocal-only passages before the full band crashes back',
      'The deliberate pause after the final note — letting the last chord ring and decay',
    ],
  },

  callAndResponse: {
    overview: 'Metal call-and-response is physical and ritualistic — the band issues commands through riffs and the audience responds with mosh pits, headbanging, and crowd chants. Live metal is a feedback loop between stage aggression and pit energy.',
    vocalInstrumentalDialogue: 'Vocal and riff interlock rhythmically rather than conversing freely — the growl or scream punches through gaps in the palm-muted chug pattern, creating a composed interlocking texture rather than blues-style call-and-response. During guitar solos, harmonized lead lines (Iron Maiden tradition) or shred passages take over the melodic narrative while rhythm guitars and bass maintain the riff foundation beneath.',
    sectionInternal: 'Breakdown call-and-response: the band hits a chug, pauses, hits again. This stuttering pattern is designed for crowd participation — each pause is filled with the audience\'s physical response. Verse-to-chorus is escalation rather than conversation.',
    audienceParticipation: 'Extremely physical — mosh pits, circle pits, wall of death, crowd surfing, headbanging in unison. The band initiates, the crowd responds with movement. Scream-along sections. The relationship between band and audience is physically intense and mutually dependent.',
    patterns: [
      'Band stops → crowd chants the riff melody back',
      'Vocalist commands "Jump!" or "Scream!" → crowd obeys collectively',
      'Breakdown chug → mosh pit erupts (riff as physical instruction)',
      'Guitar harmony call → second guitar answers in harmony (Iron Maiden tradition)',
      'Clean vocal chorus → audience singalong → scream vocal verse returns',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Metal accent is surprisingly varied — Scandinavian black metal has a distinct vocal and lyrical approach, British NWOBHM sounds different from American thrash, and Brazilian thrash has its own identity. The genre is global, and regional specificity emerges in vocal delivery, lyrical concerns, and production aesthetics.',
    phoneticMarkers: [
      'Scandinavian black metal: cold, precise diction influenced by Nordic languages, shrieked vocals with specific throat technique',
      'British NWOBHM: operatic, clear enunciation with British accent preserved (Dickinson, Halford)',
      'American thrash: aggressive, shouted, flat American accent with rapid-fire delivery',
      'German metal: precise, guttural, influenced by German phonetic patterns (Rammstein\'s deliberate German-language metal)',
      'Latin American metal: Spanish-language death and thrash with distinct rhythmic vocal patterns',
    ],
    accentInfluence: 'Metal vocals transcend regional accent more than most genres — growls and screams obscure nationality. But clean vocals reveal origin clearly. The choice to sing in one\'s native language vs. English is itself a statement about global vs. local metal identity.',
    dialectVocabulary: [
      'Norse mythology terminology in Scandinavian metal: "Valhalla," "Ragnarok," "fjord"',
      'Occult and Latin vocabulary across all regions: "daemon," "nocturne," "inferno"',
      'Japanese metal: mixing Japanese and English lyrics, honorific structures in fan interaction',
      'German industrial metal: mechanical and industrial vocabulary drawn from German engineering culture',
      'English-language metal\'s elevated, archaic vocabulary: "wield," "smite," "asunder," "dominion"',
    ],
    regionWithinCulture: 'Scandinavian metal (Norwegian black metal, Swedish death metal, Finnish doom) is a distinct cultural phenomenon. The Bay Area thrash scene produced a different sound from the Teutonic thrash of Germany. UK metal (NWOBHM) has a melodic, operatic tradition distinct from American aggression. Each region\'s metal reflects local climate, mythology, and industrial history.',
  },

  performancePractice: {
    overview: 'Metal performance is ritualistic, physically demanding, and built on mutual intensity between band and audience. The mosh pit, headbanging, and crowd surfs are not side effects — they are essential components of the metal live experience. The show is a controlled release of collective aggression.',
    improvisationConventions: 'Minimal — metal songs are played as composed, with precision. Guitar solos may be extended or varied but follow the composed structure. The emphasis is on flawless execution of complex material. Jam sections are rare outside of doom and stoner metal.',
    crowdInteraction: 'Physical and intense — the vocalist commands the pit ("Open it up!", "Circle pit!"). Wall of death on command. Crowd surfers caught and passed forward. The energy exchange between stage and pit is metal\'s core live dynamic. Respect within the chaos — fallen mosher gets picked up.',
    stagePresence: 'Powerful and commanding — headbanging in unison with the audience, guitar windmills, aggressive mic stand technique. Corpse paint (black metal). Battle vests and spikes. The physical performance matches the music\'s intensity. Drummers are visible athletes behind the kit.',
    livVsRecordedDifferences: 'Live metal is louder, more aggressive, and more visceral than recordings. The physical vibration of bass frequencies in a venue cannot be replicated. Songs may be tuned lower or played faster. The mosh pit adds a dimension that does not exist on record — metal is a participatory sport.',
    whatMakesAGoodShow: 'Sound quality that lets you feel the double bass in your chest. A pit that is aggressive but respectful. Precision — the band plays the complex parts flawlessly. Genuine intensity from the performers. The feeling of collective catharsis — leaving the venue physically exhausted and emotionally purged.',
  },

  socioeconomicSubtext: {
    overview: 'Metal draws from outsider identity — its fans and creators are often those who do not fit mainstream social expectations. The genre provides community for the alienated, the angry, and the intellectually restless. Metal\'s class base is broad, spanning working-class to suburban middle-class.',
    materialConditions: 'Metal emerged from the post-industrial decline of Birmingham, England — Black Sabbath literally wrote about the factories closing. Scandinavian black metal emerged from isolated, rural Nordic communities. American thrash came from the economic anxiety of 1980s Reagan-era working class.',
    classIdentity: 'Metal spans class lines more than many genres — working-class fans identify with the aggression, middle-class fans with the technical complexity and intellectual themes. The genre provides a classless community united by intensity. Elitism exists but is based on knowledge and dedication, not economic status.',
    politicalUndercurrent: 'Metal\'s politics are diverse: thrash is explicitly anti-war and anti-corruption (Metallica, Megadeth). Black metal has nationalist fringes alongside anti-authoritarian majorities. Punk-influenced metalcore is often progressive. The dominant political stance is anti-conformity rather than aligned with any party.',
    implicitReferences: [
      'Factory closures and industrial decline in Black Sabbath\'s Birmingham imagery',
      'Military-industrial complex as target in thrash metal lyrical tradition',
      'Social isolation and alienation as the condition that brings fans to metal',
      'DIY underground scenes operating outside major-label economics',
      'The metal festival as temporary autonomous zone — a weekend outside normal social rules',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Metal is deeply referential within its own canon — riff homages, production style lineages, and sub-genre conventions form a dense web of mutual influence. Metal musicians are expected to know the history and to position their work within it.',
    canonKnowledge: 'Exhaustive — metal fans have encyclopedic sub-genre knowledge. Knowing the difference between Swedish death metal and Florida death metal is baseline. Tracing the lineage from Black Sabbath through every sub-genre fork is a community pastime.',
    samplingTradition: 'Rare — metal is a live-instrument tradition that values original riff-writing. When electronic elements are used (industrial metal, nu-metal), they are created rather than sampled. The exception is intro samples from films, speeches, or sound effects for atmospheric framing.',
    quotationPractice: 'Riff homages are common and debated — when does influence become copying? Cover songs at live shows demonstrate lineage. Musical quotation (a brief reference to another band\'s riff) is a form of tribute. Producing a "signature sound" that echoes a classic tone is conscious lineage-building.',
    expectedReferences: [
      'Black Sabbath\'s tritone riff as the foundational metal text',
      'Iron Maiden\'s galloping rhythm and harmonized leads as NWOBHM template',
      'Metallica\'s "Master of Puppets" as thrash benchmark',
      'Slayer\'s aggression and speed as extremity reference point',
      'Meshuggah\'s polyrhythmic approach as modern prog-metal foundation',
    ],
    lineageSignifiers: [
      'Guitar tuning signals sub-genre: standard = classic, drop D = heavy, drop B = modern extreme',
      'Drum sound: natural = old school, triggered/replaced = modern metal',
      'Vocal style traces direct lineage: Dickinson → power metal, Chuck Schuldiner → death metal',
      'Production aesthetic: raw = black metal authenticity, polished = modern metal professionalism',
      'Band logo font: illegible = extreme metal, readable = mainstream metal',
      'Album artwork style signals sub-genre allegiance (Dan Seagrave = death metal, Kristian Wahlin = melodic)',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Metal has specific and often exaggerated gender conventions — the genre has historically centered aggressive, masculine performance while producing notable subversions. Women in metal navigate a space with explicit conventions around vocal style, performance, and visual presentation.',
    vocalGenderCodes: 'Male vocals dominate most sub-genres: growls, screams, and aggressive cleans are coded masculine. Female vocals appear prominently in symphonic metal (operatic soprano) and gothic metal (beauty-and-the-beast duets with male growler). Female vocalists in extreme metal who growl or scream deliberately transgress gendered vocal expectations.',
    physicalityInPerformance: 'Metal performance is intensely physical and historically masculine-coded: headbanging, power stance, aggressive stage movement. Mosh pits are physical spaces where bodies collide. The metal body is strong, enduring, and willing to absorb impact. These conventions apply regardless of gender for participants.',
    genderNarratives: 'Male narratives dominate: warriors, demons, conquerors, the isolated outsider. When women appear in metal lyrics, they range from mythological figures to objects of desire to powerful protagonists. Symphonic and gothic metal give women more narrative complexity. Extreme metal often abstracts gender entirely in favor of cosmic or philosophical themes.',
    subversionExamples: [
      'Angela Gossow (Arch Enemy) performing death growls at the highest level, proving vocal extremity is not gendered',
      'Myrkur bringing black metal\'s intensity with traditionally feminine vocal approaches',
      'Jinjer\'s Tatiana Shmayluk seamlessly switching between clean vocals and death growls',
      'Lzzy Hale (Halestorm) occupying the frontman role with full rock-star physicality',
      'Babymetal merging J-pop presentation with extreme metal performance, destabilizing both genre\'s gender codes',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Metal demonstrates the extreme range of tempo-feel disconnect — a doom song at 50 BPM feels crushingly heavy, while a blast-beat section at 220 BPM feels like a wall of noise rather than a "fast" rhythm. The note density, subdivision, and attack character transform BPM into radically different physical experiences.',
    psychologicalTempo: 'Blast beats at 200+ BPM are so fast they become textural — the individual beats merge into a roar, and the psychological tempo is actually slower (the riff changes, not the beats, define perceived speed). Doom at 50 BPM feels slower than its number because the sustain between attacks stretches time. Groove metal at 120 BPM feels perfectly "speed" for headbanging.',
    weightAndMomentum: 'Weight in metal comes from low tuning, massive distortion, and slow attack rates. A single sustained power chord at 50 BPM has enormous weight. Momentum comes from relentless double bass and palm-muted chugging. The heaviest metal is often the slowest — weight and speed are inversely related.',
    urgencyScale: '1 (funeral doom crawl) through 5 (groove metal stomp) to 10 (grindcore blast). Thrash lives at 7-9: fast enough to demand physical response. Death metal lives at 6-8, depending on riff speed vs. blast speed. Doom lives at 1-3. The headbanging "sweet spot" is around 4-6.',
    comparisonToSameBPM: 'Metal at 140 BPM feels aggressive and driving — the distortion, double bass, and aggressive vocal make it physically intense. Pop at 140 BPM feels upbeat and danceable. EDM at 140 BPM feels hypnotic and repetitive. Metal\'s attack transients and harmonic density make the same tempo feel like a different physical force.',
  },

  mistakeConventions: {
    overview: 'Metal has low tolerance for mistakes — the genre\'s emphasis on technical precision means sloppy playing is not charming, it is disqualifying. However, certain types of rawness are valued, particularly in black metal and early thrash, where lo-fi production and rough performance signify authenticity.',
    toleratedImperfections: [
      'Double bass drum patterns that drift slightly from metronomic lockstep during live blast-beat passages',
      'Palm-muted chugs with uneven pick attack adding percussive aggression to breakdown riffs',
      'Vocal strain and cord shredding during sustained death growls or black metal shrieks showing physical extremity',
      'Pick scrapes, string noise, and pinch harmonic squeals bleeding between riff sections',
      'Snare hits that flam slightly against the kick during high-speed thrash passages, adding urgency',
    ],
    celebratedFlaws: [
      'Black metal\'s deliberately lo-fi production: Darkthrone\'s "Transilvanian Hunger" sounds like it was recorded in a cave — this is the point',
      'Early thrash recordings with raw, under-produced sound that captured live energy',
      'Feedback and noise as texture in sludge and drone metal',
      'Tom Araya\'s vocal strain on Slayer tracks as evidence of genuine aggression',
      'The "garage" sound of early death metal demos that fans value over remastered versions',
    ],
    overproductionRisks: [
      'Drum triggering so perfect it sounds robotic and lifeless',
      'Guitar tones so processed they lose organic bite and character',
      'Vocal pitch correction that removes the raw edge of metal singing',
      'Amp simulation that sounds "too perfect" compared to a real cabinet moving air',
      'Mix so compressed and loud it becomes fatiguing and loses dynamic impact',
      'Editing so tight that human energy and excitement are removed',
    ],
    authenticRoughness: 'Black metal has turned lo-fi rawness into an ideology — overproduction is seen as a betrayal of the genre\'s anti-commercial, anti-mainstream values. But in most metal, "rough" means "captured with energy" not "played sloppily." The line is between passionate imprecision and careless inaccuracy. A drummer who speeds up during an exciting fill is human; one who can\'t keep time is not metal.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['metal', 'heavy', 'distorted guitars', 'aggressive', 'powerful', 'intense', 'dark'],
    avoidKeywords: ['smooth', 'gentle', 'acoustic only', 'pop', 'light', 'soft', 'mellow', 'tropical'],
    promptTemplate: '[sub-genre] metal, [tempo] BPM, [mood] mood, [vocal style] vocals, [guitar style], [intensity level]',
    tips: [
      'Specify sub-genre precisely — metal has many distinct sub-genres',
      'Describe vocal style: growl, scream, clean, operatic, shouted',
      'Mention the guitar tuning if relevant: standard, drop D, drop C',
      'Describe the intensity: crushing, aggressive, epic, dark, brutal',
      'Reference tempo feel: fast thrash, slow doom, mid-tempo groove',
      'Include atmosphere: dark, epic, atmospheric, raw, cinematic',
    ],
  },
};
