import type { GenreGuide } from './types';

export const POP_GUIDE: GenreGuide = {
  id: 'pop',
  name: 'Pop',
  language: 'English',

  sonicPalette: {
    overview: 'Bright, polished, and immediately accessible. Pop prioritizes clarity and catchiness above all — every element serves the hook. Modern pop production is maximalist in impact but minimalist in arrangement, using carefully chosen synths, processed vocals, and tight percussion to create an immersive, radio-ready sound.',
    timbre: [
      'Crisp, breathy, pitch-corrected vocals front and center',
      'Bright supersaw synth pads and plucks',
      'Punchy, compressed drum machines (808s, LinnDrum, or modern kits)',
      'Warm sub-bass or deep 808 sine-wave bass',
      'Shimmering reverb tails and delay throws on vocals',
      'Clean electric guitar with chorus or tremolo effects',
      'Processed piano or Rhodes with saturation',
    ],
    texture: 'Layered but uncluttered — production uses stacking and widening techniques but maintains a clear center image. Builds from sparse verses to full-frequency choruses. Sidechain compression creates rhythmic pumping. The mix feels loud, wide, and present.',
    tonality: 'Major keys dominate (C, G, D, F, Bb). Minor keys used for emotional/dark pop. Bright EQ with boosted highs (air) and controlled low-mids. The overall tone is optimistic, energetic, or bittersweet.',
    signatureSounds: [
      'Vocal chops and pitched vocal samples',
      'Snap claps layered with electronic snares',
      'Tropical marimba or steel drum plucks',
      'Filtered risers and white noise sweeps for transitions',
      'Post-chorus instrumental drops',
      'Whistle hooks or melodic synth leads',
    ],
  },

  rhythmAndGroove: {
    overview: 'Four-on-the-floor or syncopated trap-influenced patterns. Pop rhythm is designed for instant physical response — head-nodding, dancing, or swaying. The groove is tight and quantized, with occasional humanized swing on hi-hats.',
    bpmRange: { min: 95, max: 135, sweet: 120 },
    feel: 'Driving and energetic for uptempo tracks, laid-back and bouncy for mid-tempo. The beat should feel effortless and inevitable.',
    swing: 'Minimal to moderate — modern pop tends toward straight 16th-note quantization. Some lo-fi or R&B-influenced pop uses subtle swing.',
    syncopation: 'Moderate — vocal melodies often syncopate against a straight beat. Instrumental hooks use anticipation and off-beat accents.',
    grooveArchetype: 'Four-on-the-floor dance pulse, half-time trap bounce, or two-step swing',
    rhythmicSignatures: [
      'Boom-clap pattern (kick on 1 and 3, snare on 2 and 4)',
      'Trap hi-hat rolls with 16th and 32nd note variations',
      'Finger snaps on beats 2 and 4',
      'Syncopated bass patterns locking with kick drum',
      'Half-time feel in verses, full-time in choruses',
      'Percussion drops in pre-chorus for dynamic contrast',
    ],
  },

  harmonicLanguage: {
    overview: 'Accessible and memorable. Pop harmony uses a small vocabulary of chords to maximum emotional effect. The four-chord progression reigns supreme, but modern pop also embraces modal interchange and borrowed chords for color.',
    scales: ['Major (Ionian)', 'Natural Minor (Aeolian)', 'Mixolydian', 'Dorian'],
    chordProgressions: [
      'I – V – vi – IV (the "pop progression")',
      'vi – IV – I – V (emotional variant)',
      'I – IV – vi – V',
      'I – V – IV (rock-pop)',
      'vi – IV – V – I (anthemic)',
      'I – iii – IV – V (ascending emotional)',
      'I – vi – IV – V (classic doo-wop pop)',
    ],
    harmonyNotes: 'Chord inversions add smoothness. Bass movement is often stepwise. Suspended chords (sus2, sus4) create tension before resolution. Add9 and major7 chords add sophistication. Pre-choruses often use chromatic movement or secondary dominants to build tension.',
    modality: 'Primarily major. Minor keys used for darker emotional content. Modal mixture (borrowing from parallel minor) is common — the bVII chord in a major key is a pop staple.',
  },

  songStructure: {
    overview: 'Highly formulaic by design — pop structures are optimized for repeated listening and radio/streaming consumption. The hook must arrive quickly (within 30-60 seconds) and recur frequently.',
    form: 'Verse – Pre-Chorus – Chorus – Verse – Pre-Chorus – Chorus – Bridge – Chorus (with variations)',
    sections: ['Intro', 'Verse 1', 'Pre-Chorus', 'Chorus', 'Post-Chorus', 'Verse 2', 'Pre-Chorus', 'Chorus', 'Bridge', 'Final Chorus', 'Outro'],
    arrangement: 'Additive arrangement: start sparse and build. Each section should add or change at least one element. The final chorus is often the fullest arrangement. Drop sections (removing elements suddenly) create dynamic contrast.',
    introOutro: 'Intros are short (4-8 bars) — often a vocal hook, signature riff, or stripped beat. Outros fade out, loop the hook, or end with a final vocal ad-lib. Modern streaming pop starts with the hook or chorus immediately.',
    barLengths: 'Verses: 8-16 bars. Pre-chorus: 4-8 bars. Chorus: 8-16 bars. Bridge: 4-8 bars. Total song length: 2:30-3:30 for streaming optimization.',
    hookPlacement: 'The chorus IS the hook. Additional hooks in the intro, post-chorus, and instrumental sections. The title/hook phrase should appear within the first 30 seconds for streaming retention.',
  },

  vocalDelivery: {
    overview: 'The voice is the centerpiece of pop. Delivery ranges from intimate whisper to belt, but always prioritizes clarity of melody and lyric. Modern pop vocals are heavily processed but should feel emotionally genuine.',
    phrasing: 'Conversational in verses, expansive in choruses. Phrases are short and rhythmically catchy. Repetition of melodic motifs across sections creates memorability.',
    affect: 'Emotionally direct — joy, heartbreak, empowerment, longing. The vocal should make the listener feel the emotion immediately without ambiguity.',
    techniques: [
      'Pitch-perfect tuning (Auto-Tune or Melodyne as standard)',
      'Breathy tone in verses, full belt in choruses',
      'Vocal layering and doubling for thickness',
      'Falsetto breaks and runs for emotional peaks',
      'Talk-singing in verses (Billie Eilish style)',
      'Vocal fry on phrase endings',
      'Harmony stacks (3rds and 5ths) in choruses',
    ],
    adlibStyle: 'Oh, yeah, hey, come on, whoa — used as transitions and fills. Background vocal chants (hey! ho!) in choruses. Whispered or spoken interjections for intimacy.',
    harmony: 'Tight harmony vocals in choruses, often in 3rds or 5ths above the lead. Unison doubling for power. Background "ooh" and "aah" pads. Gospel-style stacked harmonies for emotional climax.',
    grit: 'Minimal — pop vocals are clean and polished. Some grit allowed in emotional peaks (belt notes) or rock-influenced pop. Vocal distortion used as a stylistic effect, not default.',
  },

  lyricalConventions: {
    overview: 'Universal, relatable, and emotionally direct. Pop lyrics use everyday language to express feelings that everyone can connect with. Simplicity is a feature, not a limitation — the best pop lyrics distill complex emotions into singable phrases.',
    themes: [
      'Romantic love (falling in, heartbreak, desire)',
      'Self-empowerment and confidence',
      'Dancing and celebration',
      'Nostalgia and memory',
      'Freedom and escape',
      'Friendship and solidarity',
      'Self-discovery and identity',
      'Heartbreak and moving on',
    ],
    perspective: 'First person (I/me) or second person (you) direct address. The listener should feel spoken to personally. Third person rarely used except in storytelling pop.',
    figurativeLanguage: 'Metaphors that are instantly understood — fire for passion, rain for sadness, flying for freedom. Similes over extended metaphors. The figurative language should enhance, not obscure, the emotional message.',
    vocabulary: 'Conversational, accessible, grade-school reading level. Short words, common phrases. Slang is genre-appropriate and era-specific. Avoid jargon, obscure references, or overly literary language.',
    storytellingApproach: 'Emotional snapshots rather than full narratives. Each verse captures a moment or feeling. The chorus distills the emotional thesis. Bridge offers perspective shift or emotional escalation.',
    cliches: [
      'Baby/babe as terms of address',
      'Dancing in the dark/rain',
      'Setting hearts on fire',
      'Can\'t stop this feeling',
      'Tonight is the night',
      'We are young/invincible',
      'Hands in the air',
    ],
  },

  productionFingerprint: {
    overview: 'Maximum polish, minimum friction. Pop production serves one goal: make every listen feel satisfying. The mix is loud, clear, and frequency-balanced. Every sound is intentional.',
    mixAesthetic: 'Loud and present. Heavy compression and limiting for consistent volume. Vocals sit prominently above the mix. Sub-bass and kick are powerful but controlled. Stereo width is maximized in choruses.',
    era: 'Current era (2020s): blend of organic and electronic, trap-influenced drums, lo-fi textures mixed with pristine vocals, genre-blending (pop-country, pop-rap, pop-rock).',
    signalChain: 'Vocals: condenser mic → preamp → Auto-Tune/Melodyne → compression → EQ → de-esser → reverb/delay sends. Synths: soft synths (Serum, Omnisphere) → saturation → sidechain compression. Drums: sample-based with layered acoustic hits.',
    modernTrends: 'Bedroom pop aesthetics bleeding into mainstream. Retro 80s synth sounds. Minimalist drops instead of EDM-style builds. Pitched vocal samples. Genre fusion (Latin-pop, Afro-pop, K-pop influence). Short song lengths for streaming.',
  },

  instrumentation: {
    coreInstruments: [
      'Synthesizers (pads, leads, plucks, arps)',
      'Drum machine / programmed drums',
      'Bass synth or 808',
      'Piano / electric piano',
      'Acoustic guitar (strummed or fingerpicked)',
      'Electric guitar (clean or mildly overdriven)',
      'Strings (real or sampled, for emotional sections)',
    ],
    signatureSounds: [
      'Supersaw synth stabs',
      'Tropical pluck synths',
      'Snap and clap layers',
      'Vocal chop melodic hooks',
      'Filtered piano riffs',
      'Reverse reverb vocal swells',
    ],
    layering: 'Dense but organized — each element occupies a specific frequency range and stereo position. Verses: 3-5 elements. Choruses: 8-12 elements. Use of automation to bring elements in and out for dynamic movement.',
    avoidInstruments: [
      'Heavy distorted guitars (unless pop-rock)',
      'Unprocessed acoustic instruments (too raw)',
      'Extended jazz harmony instruments',
      'Overly ethnic/traditional instruments (unless fusion)',
      'Harsh industrial synths',
    ],
  },

  culturalContext: {
    overview: 'Pop is the mainstream — it reflects and shapes popular culture simultaneously. It is commercial by nature, designed to reach the widest possible audience across demographics.',
    origin: 'Evolved from 1950s rock and roll, Tin Pan Alley songwriting, and Motown. The term "pop" emerged in the UK in the mid-1950s to describe music with popular appeal.',
    identity: 'Pop is defined by its audience, not its sound. It absorbs and repackages elements from every genre. Pop artists are brands — image, persona, and narrative are as important as the music.',
    community: 'Global — pop transcends geographic and cultural boundaries. Fandoms (Swifties, BTS Army, Beyhive) are powerful cultural forces. Social media and streaming platforms are the primary community spaces.',
    socialFunction: 'Soundtrack to everyday life — driving, parties, workouts, emotional processing. Pop music marks cultural moments and generational identity. It provides shared cultural references.',
    authenticityMarkers: [
      'Emotional sincerity over technical complexity',
      'Personal storytelling that feels genuine',
      'Visual identity that reinforces musical message',
      'Consistent artistic evolution across releases',
      'Connection to current cultural moment',
    ],
  },

  historicalLineage: {
    overview: 'Pop is the great absorber — it has continuously evolved by incorporating elements from whatever genres are culturally ascendant, from rock to disco to hip-hop to Latin music.',
    roots: ['Tin Pan Alley', 'Rock and Roll', 'Motown/Soul', 'Disco', 'New Wave'],
    evolution: 'From singles-driven 50s/60s pop through the album era, MTV-driven 80s visual pop, boy/girl band era of the 90s, digital revolution of the 2000s, to the streaming-optimized genre-fluid pop of today.',
    keyEras: [
      '1960s: British Invasion and Motown',
      '1980s: Synth-pop and MTV era',
      '1990s: Teen pop and boy bands',
      '2000s: Pop-R&B fusion and Auto-Tune era',
      '2010s: EDM-pop and streaming era',
      '2020s: Genre-fluid, bedroom pop meets mainstream',
    ],
    influencedBy: ['Rock and Roll', 'R&B', 'Disco', 'Hip-Hop', 'EDM', 'Latin', 'K-Pop'],
    influenced: ['Every genre — pop absorbs and redistributes'],
  },

  subGenres: [
    {
      name: 'Synth-Pop',
      description: 'Electronic-driven pop built around synthesizers, drum machines, and sequencers. Melodic and hook-focused with a retro-futuristic aesthetic.',
      distinguishingFeatures: ['Analog or analog-modeled synths as primary instruments', 'Arpeggiated sequences', 'Gated reverb on drums', 'New Wave vocal style'],
      bpmRange: { min: 110, max: 135 },
      keyArtists: ['Depeche Mode', 'The 1975', 'CHVRCHES', 'Dua Lipa', 'The Weeknd'],
      productionNotes: 'Layer vintage synth sounds (Juno, Prophet, DX7) with modern production clarity. Use sidechain pumping. Gated reverb snares. Bright, cutting lead synths.',
      lyricNotes: 'Themes of technology, alienation, desire, and neon-lit nightlife. Slightly detached emotional delivery.',
      sunoPromptKeywords: ['synth-pop', '80s synths', 'electronic pop', 'new wave', 'retro synth', 'arpeggiated', 'gated reverb'],
    },
    {
      name: 'Dance-Pop',
      description: 'Uptempo pop designed for the dance floor. Combines pop song structures with electronic dance music production.',
      distinguishingFeatures: ['Four-on-the-floor kick pattern', 'High energy throughout', 'Euphoric choruses', 'Build-drop dynamics'],
      bpmRange: { min: 118, max: 132 },
      keyArtists: ['Lady Gaga', 'Dua Lipa', 'Kylie Minogue', 'Robyn', 'Carly Rae Jepsen'],
      productionNotes: 'Driving four-on-the-floor beat. Big synth hooks. Vocal processing with reverb and delay. EDM-influenced builds and drops adapted for pop structure.',
      lyricNotes: 'Dancing, nightlife, freedom, attraction, living in the moment. Empowering and escapist.',
      sunoPromptKeywords: ['dance-pop', 'club pop', 'uptempo', 'four-on-the-floor', 'euphoric', 'dance floor', 'electronic pop'],
    },
    {
      name: 'Electropop',
      description: 'A fusion of electronic music aesthetics with pop songwriting. More experimental than dance-pop, with prominent electronic textures and processing.',
      distinguishingFeatures: ['Heavy use of vocoders and vocal effects', 'Glitchy digital textures', 'Futuristic sound design', 'Electronic beats with pop melodies'],
      bpmRange: { min: 100, max: 130 },
      keyArtists: ['Grimes', 'Charli XCX', 'Passion Pit', 'M83', 'Imogen Heap'],
      productionNotes: 'Experimental sound design married to catchy melodies. Vocoder and Auto-Tune as artistic choices. Glitch effects, bitcrushing, and granular synthesis.',
      lyricNotes: 'Futurism, digital culture, love in the modern age, identity. More abstract than standard pop.',
      sunoPromptKeywords: ['electropop', 'futuristic pop', 'vocoder', 'glitch pop', 'electronic', 'digital pop'],
    },
    {
      name: 'Indie Pop',
      description: 'Pop music with an independent, lo-fi, or alternative sensibility. Prioritizes authenticity and quirky charm over mainstream polish.',
      distinguishingFeatures: ['Lo-fi or DIY production aesthetic', 'Jangly guitars', 'Understated vocals', 'Quirky instrumentation (ukulele, glockenspiel, toy instruments)'],
      bpmRange: { min: 95, max: 130 },
      keyArtists: ['Vampire Weekend', 'Clairo', 'Mac DeMarco', 'Alvvays', 'boy pablo'],
      productionNotes: 'Embrace imperfection — slight tape hiss, lo-fi drums, room reverb. Jangly clean guitars, simple synths, organic-feeling even when electronic.',
      lyricNotes: 'Introspective, witty, self-deprecating. Mundane details elevated to poetry. Romantic but not saccharine.',
      sunoPromptKeywords: ['indie pop', 'lo-fi pop', 'jangly', 'bedroom pop', 'dreamy', 'DIY pop', 'chill indie'],
    },
    {
      name: 'Dream Pop',
      description: 'Ethereal, atmospheric pop characterized by reverb-drenched vocals and shimmering guitar textures. Emphasizes mood over structure.',
      distinguishingFeatures: ['Heavy reverb and delay on all elements', 'Breathy, distant vocals', 'Shimmer reverb guitars', 'Slow-building dynamics'],
      bpmRange: { min: 80, max: 120 },
      keyArtists: ['Cocteau Twins', 'Beach House', 'Mazzy Star', 'Cigarettes After Sex', 'Slowdive'],
      productionNotes: 'Drown everything in reverb. Long delay tails. Chorus-effect guitars. Soft, pillowy drums. The mix should feel like looking through frosted glass.',
      lyricNotes: 'Abstract, impressionistic, romantic. Focus on sensory imagery over narrative. Words chosen for sound as much as meaning.',
      sunoPromptKeywords: ['dream pop', 'ethereal', 'shoegaze pop', 'atmospheric', 'reverb-drenched', 'dreamy', 'hazy'],
    },
    {
      name: 'Art Pop',
      description: 'Pop music that pushes boundaries through avant-garde, conceptual, or experimental approaches while maintaining pop accessibility.',
      distinguishingFeatures: ['Unconventional song structures', 'High-concept visual identity', 'Genre-bending production', 'Intellectual or provocative themes'],
      bpmRange: { min: 85, max: 140 },
      keyArtists: ['Bjork', 'Kate Bush', 'FKA twigs', 'St. Vincent', 'Janelle Monae'],
      productionNotes: 'Blend organic and electronic fearlessly. Use unconventional sounds and structures while maintaining a hook. High production value with experimental choices.',
      lyricNotes: 'Conceptual, literary, provocative. Explores identity, society, gender, technology. More poetic and layered than mainstream pop.',
      sunoPromptKeywords: ['art pop', 'avant-garde pop', 'experimental pop', 'conceptual', 'eccentric', 'boundary-pushing'],
    },
    {
      name: 'Bubblegum Pop',
      description: 'Ultra-catchy, upbeat, and sweet pop aimed at the broadest possible appeal. Pure sugar-rush energy.',
      distinguishingFeatures: ['Extremely catchy hooks', 'Bright, major-key tonality', 'Simple chord progressions', 'High energy and positivity'],
      bpmRange: { min: 115, max: 135 },
      keyArtists: ['NSYNC', 'Britney Spears', 'Aqua', 'Carly Rae Jepsen', 'TWICE'],
      productionNotes: 'Maximum brightness and energy. Layered vocal hooks. Bouncy basslines. Handclaps and percussion. Everything should sparkle.',
      lyricNotes: 'Love, fun, friendship, parties. Uncomplicated positivity. Repetitive, singalong-friendly choruses.',
      sunoPromptKeywords: ['bubblegum pop', 'sugary pop', 'teen pop', 'upbeat', 'catchy', 'bright pop', 'feel-good'],
    },
    {
      name: 'Power Pop',
      description: 'Guitar-driven pop with rock energy. Emphasizes strong melodies, crunchy guitars, and tight song structures inspired by 60s pop and 70s rock.',
      distinguishingFeatures: ['Prominent electric guitars with crunch', 'Strong vocal harmonies', 'Fast tempos', 'Concise, hook-laden songs'],
      bpmRange: { min: 120, max: 160 },
      keyArtists: ['Cheap Trick', 'Big Star', 'Weezer', 'Fountains of Wayne', 'The Posies'],
      productionNotes: 'Crunchy rhythm guitars doubled and panned. Prominent vocal harmonies (Beatles-influenced). Punchy drums. Keep songs tight and under 4 minutes.',
      lyricNotes: 'Romantic longing, youthful energy, girl/boy-next-door themes. Clever wordplay. Earnest emotional delivery.',
      sunoPromptKeywords: ['power pop', 'guitar pop', 'hook-driven', 'melodic rock', 'jangly guitars', 'vocal harmonies'],
    },
    {
      name: 'Teen Pop',
      description: 'Pop specifically targeting teenage audiences with themes of first love, growing up, and youthful rebellion. High production value with choreography-friendly beats.',
      distinguishingFeatures: ['Polished production targeting youth demographic', 'Dance-oriented beats', 'Coming-of-age themes', 'Strong visual/brand identity'],
      bpmRange: { min: 100, max: 130 },
      keyArtists: ['Justin Bieber', 'Olivia Rodrigo', 'Billie Eilish', 'One Direction', 'Ariana Grande'],
      productionNotes: 'Current production trends with a youthful energy. Mix of electronic and organic elements. Emotional dynamics — quiet introspection to explosive choruses.',
      lyricNotes: 'First love, heartbreak, self-discovery, fitting in, growing up. Authentic teenage perspective. Social media and modern life references.',
      sunoPromptKeywords: ['teen pop', 'young pop', 'coming-of-age', 'youthful', 'emotional pop', 'modern pop'],
    },
    {
      name: 'Chamber Pop',
      description: 'Pop music incorporating orchestral and classical instrumentation. Lush, cinematic arrangements with pop song structures.',
      distinguishingFeatures: ['String quartets and orchestral arrangements', 'Complex harmonic language', 'Cinematic dynamics', 'Baroque or classical influences'],
      bpmRange: { min: 70, max: 120 },
      keyArtists: ['Rufus Wainwright', 'Belle and Sebastian', 'Fleet Foxes', 'Sufjan Stevens', 'Arcade Fire'],
      productionNotes: 'Real or high-quality sampled strings, brass, woodwinds. Lush reverb. Dynamic range — allow quiet moments. Layer acoustic instruments organically.',
      lyricNotes: 'Literary, poetic, introspective. Longer narratives allowed. References to literature, art, history. Emotionally complex.',
      sunoPromptKeywords: ['chamber pop', 'orchestral pop', 'baroque pop', 'lush', 'cinematic', 'strings', 'orchestrated'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Pop is mainstream culture. Its audience is the broadest of any genre — cross-demographic, cross-cultural, cross-generational. Pop fans engage through streaming, social media, concerts, and cultural conversation.',
    fanExpectations: [
      'Catchy, singable hooks',
      'Polished production quality',
      'Strong visual identity and music videos',
      'Regular release cadence (singles-driven)',
      'Social media presence and accessibility',
      'Evolution without alienation',
    ],
    gatekeeping: 'Minimal — pop is deliberately inclusive. Some snobbery from "serious" music fans who dismiss pop as formulaic. The main gatekeeping is commercial: chart performance and streaming numbers.',
    livePerformance: 'Spectacle-driven — choreography, staging, visuals, costume changes. Audience singalongs are essential. The live show should feel like an event. Smaller indie-pop acts can be more intimate.',
    fashionAndAesthetic: 'Trend-setting and aspirational. Pop artists define fashion moments. Aesthetic shifts with each album era. Visual branding is inseparable from the music.',
    crossoverPotential: 'Maximum — pop is the crossover destination for every genre. Pop artists regularly incorporate hip-hop, Latin, country, rock, and EDM elements.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Pop production is quantized to a grid — precision is the default. The "human" feel comes from programmed micro-variations in velocity and timing on hi-hats, from slightly pushing vocal phrases ahead of the beat for urgency, or laying them back for intimacy.',
    quantizationDeviation: 'Very tight — most elements are locked to a 1/16th grid. Deliberate deviation is rare and subtle: a slightly early snare ghost note, hi-hat velocity variation, or syncopated bass anticipation.',
    aheadBehindBeat: 'Vocals often sit slightly ahead of the beat in energetic pop (creates urgency and forward motion) and slightly behind in ballads or R&B-influenced pop (creates intimacy and weight).',
    humanizationMarkers: [
      'Vocal breath sounds left in the mix for intimacy',
      'Hi-hat velocity randomization (±5-10%)',
      'Slightly early vocal attacks on downbeats in uptempo tracks',
      'Natural vocal pitch micro-variations even with tuning',
      'Finger-snaps and claps with minor timing scatter',
    ],
    genreSpecificFeel: 'The "pop feel" is polished inevitability — every element arrives exactly when expected, creating a sense of effortless momentum. The groove should feel like a conveyor belt: smooth, predictable, impossible to resist.',
  },

  silenceAndSpace: {
    overview: 'Pop uses silence surgically — the drop-out before a chorus, the breakdown before the final hook. Space is a dramatic device, not a default state. When pop goes quiet, it is always building toward something louder.',
    negativeSpaceRole: 'Contrast tool — silence makes the full arrangement hit harder. Pre-chorus strip-downs, beat drops, vocal-only moments, and breakdowns all use silence to amplify the payoff.',
    breathingPatterns: 'Verses breathe more (fewer layers, sparser arrangement). Choruses fill all frequency space. Post-choruses often strip back to a single hook element. The push-pull between sparse and full drives the emotional arc.',
    dynamicContrast: 'High — the contrast between verse and chorus is the engine of pop. Verse at 60% energy, pre-chorus ramps to 80%, chorus explodes to 100%. The bridge resets to 40-50% before the final chorus payoff.',
    whatIsDeliberatelyAbsent: [
      'Extended instrumental solos (everything serves the vocal/hook)',
      'Unresolved harmonic tension that does not pay off',
      'Prolonged ambient passages without rhythmic pulse',
      'Silence longer than 2 bars mid-song (kills streaming retention)',
      'Frequencies left empty — pop fills the spectrum edge to edge in choruses',
    ],
  },

  callAndResponse: {
    overview: 'Pop call-and-response is vocal-centric: lead vocal poses a phrase, background vocals answer. It also operates between sections — the verse "calls" with a question or setup, the chorus "responds" with the emotional thesis.',
    vocalInstrumentalDialogue: 'Minimal true dialogue — the vocal dominates and instruments support. Instrumental hooks may echo or answer vocal phrases in post-choruses. Synth riffs sometimes trade with the vocal melody in transitions.',
    sectionInternal: 'Lead vocal line followed by background vocal echo ("I got that feeling" / "feeling!"). Antiphonal chanting in choruses. Question-answer phrasing within verses.',
    audienceParticipation: 'High — pop choruses are designed for audience singalong. "Oh-oh-oh" and "na-na-na" sections exist specifically for crowd participation. Live shows use call-and-response with the audience on hook phrases.',
    patterns: [
      'Lead vocal + background vocal echo on hook phrases',
      'Verse setup / chorus payoff (macro call-and-response)',
      'Chant sections designed for audience singalong (oh-oh-oh)',
      'Instrumental hook answering the vocal hook in post-choruses',
      'Spoken/whispered verse followed by belted chorus',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Pop aims for a "global neutral" accent — typically a softened American or mid-Atlantic English that maximizes international accessibility. Regional identity is deliberately sanded down in mainstream pop, though indie and alternative pop embrace accent.',
    phoneticMarkers: [
      'Softened American vowels as the default vocal accent',
      'British pop retains some native vowel sounds (Adele, Dua Lipa) but flattens others',
      'Scandinavian pop (Robyn, ABBA) uses precise, slightly clipped English',
      'Australian pop leans toward British vocal placement',
    ],
    accentInfluence: 'Minimal regional accent in mainstream pop — the "pop accent" is its own construct: slightly nasal, forward-placed, with elongated vowels for singability. Regional accent emerges mainly in indie pop and singer-songwriter pop.',
    dialectVocabulary: [
      'Universal English vocabulary — avoids region-specific slang',
      'American cultural references dominate (prom, highway, downtown)',
      'UK pop may use "mate," "rubbish," "proper" but sparingly',
      'Australian/NZ pop occasionally uses local slang for authenticity',
    ],
    regionWithinCulture: 'Pop is placeless by design — it could be from anywhere, which is the point. Sub-genres like Scandi-pop, Brit-pop, and J-pop reintroduce regional identity as a distinguishing feature.',
  },

  performancePractice: {
    overview: 'Pop live performance is about spectacle, precision, and connection. The show is choreographed, rehearsed, and visually produced. Improvisation is rare — the live version should match or exceed the studio version.',
    improvisationConventions: 'Minimal — the arrangement is fixed. Vocal ad-libs at the end of the final chorus are the main improvisational space. Guitar solos may extend slightly. Some artists add between-song banter or acoustic breakdowns.',
    crowdInteraction: 'Essential — pointing to sections of the audience, encouraging singalongs, call-and-response on hooks, asking the crowd to scream or clap. The performer must make every audience member feel seen.',
    stagePresence: 'Choreography for dance-pop, emotional authenticity for ballad-driven pop. Costume changes between setlist sections. Energy management across a 90-minute set.',
    livVsRecordedDifferences: 'Live pop uses backing tracks and in-ear monitors. Vocals are live but supported by pre-recorded harmonies and effects. The arrangement may be simplified or given a "live band" arrangement with real drums/guitar.',
    whatMakesAGoodShow: 'The audience leaves feeling emotionally full — every hit was played, the singalong moments landed, the visual production matched the music, and there was at least one "special moment" (surprise guest, extended outro, acoustic version).',
  },

  socioeconomicSubtext: {
    overview: 'Pop is aspirational by default — it sells the dream of love, freedom, beauty, and youth. Its material conditions are the commercial music industry itself: label deals, streaming economics, brand partnerships, and global touring.',
    materialConditions: 'Pop is the product of the music industry\'s commercial machinery. Production budgets, A&R development, marketing spend, and touring infrastructure all shape what pop sounds like. Bedroom pop disrupted this by lowering the barrier.',
    classIdentity: 'Pop transcends class — it is consumed across all economic strata. However, pop production historically required expensive studios, which favored artists with label backing. The democratization of production tools has shifted this.',
    politicalUndercurrent: 'Pop is generally apolitical, but individual artists bring political messaging (Lady Gaga on LGBTQ+ rights, Beyoncé on Black identity). Pop absorbs social movements into anthems (empowerment, pride, resilience).',
    implicitReferences: [
      'Consumer culture and brand-name luxury as aspiration',
      'Youth and beauty as currency',
      'Freedom as individual choice (driving, dancing, leaving)',
      'Love as the central human experience worth singing about',
      'Social media validation and digital connection',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Pop constantly references itself — interpolating classic melodies, sampling iconic tracks, and quoting hooks from previous eras. Nostalgia is a primary currency. The best pop music makes the listener feel they have always known the song.',
    canonKnowledge: 'Pop songwriters study the Great American Songbook, Motown, ABBA, Michael Jackson, Madonna, Prince, Whitney Houston. Knowledge of what hooks have already worked is essential to writing new ones that feel both fresh and familiar.',
    samplingTradition: 'Moderate — pop samples classic tracks for instant nostalgia (Dua Lipa sampling INXS, The Weeknd sampling a-ha). Interpolation (re-singing a melodic phrase) is more common than direct sampling.',
    quotationPractice: 'Melodic quotation and harmonic homage are widespread. Chord progressions are freely shared. The four-chord progression (I–V–vi–IV) is communal property. Lyrical quotation of iconic lines happens but is rarer.',
    expectedReferences: [
      'The Beatles (melodic invention, song structure)',
      'Michael Jackson (groove, vocal delivery, production ambition)',
      'ABBA (harmonic movement, chorus construction)',
      'Madonna (reinvention, cultural positioning)',
      'Prince (genre fusion, vocal range)',
    ],
    lineageSignifiers: [
      'Four-chord harmonic loops',
      'Verse-prechorus-chorus architecture',
      'Vocal-forward mix with polished production',
      'Hook repetition and earworm construction',
      'Singalong-ready melodic contours',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Pop encodes gender through vocal register, lyrical perspective, and visual presentation. Female pop tends toward vulnerability-as-strength and empowerment narratives. Male pop leans toward romantic devotion or party energy. Non-binary and queer pop is expanding these codes.',
    vocalGenderCodes: 'Female pop vocals: breathy intimacy, power belts, vocal runs. Male pop vocals: falsetto, smooth mid-range, gentle delivery. The boundaries are blurring — male falsetto (The Weeknd), female lower-register power (Billie Eilish).',
    physicalityInPerformance: 'Choreography-heavy for dance-pop (gender-specific movement vocabularies). Emotional authenticity conveyed through facial expression and gesture for ballad artists. The body is a performance instrument in pop.',
    genderNarratives: 'Female artists: empowerment, reclaiming agency, emotional complexity, heartbreak as growth. Male artists: romantic pursuit, vulnerability, party hosting. These conventions are increasingly fluid and subverted.',
    subversionExamples: [
      'Billie Eilish — rejecting the sexualized female pop body',
      'Harry Styles — embracing traditionally feminine aesthetics',
      'Lil Nas X — openly queer Black male pop/rap',
      'FKA twigs — avant-garde physicality beyond gender norms',
      'Sam Smith — non-binary pop stardom',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'A 120 BPM pop track feels completely different from a 120 BPM punk track or a 120 BPM house track. Pop at 120 BPM feels moderate and groovy — the four-on-the-floor is a platform for the vocal, not a driver of urgency.',
    psychologicalTempo: 'Pop feels "right in the pocket" — never rushed, never dragging. Even uptempo pop (128-135 BPM) feels like a comfortable cruise speed rather than an adrenaline rush. The groove carries you without demanding physical effort.',
    weightAndMomentum: 'Light to medium — pop beats are buoyant, not heavy. The kick and bass provide foundation but don\'t dominate the way they do in hip-hop or EDM. Momentum builds through arrangement rather than raw rhythmic force.',
    urgencyScale: 'Low to moderate. Pop\'s emotional urgency comes from the vocal delivery and lyrical content, not the tempo. A heartbreak ballad at 75 BPM can feel more urgent than a dance track at 128 BPM.',
    comparisonToSameBPM: 'At 120 BPM: pop feels like a confident walk. House feels like a pulsing club. Rock feels like a driving force. Afrobeats feels like a body-rolling wave. The difference is weight, accent, and subdivision.',
  },

  mistakeConventions: {
    overview: 'Pop tolerates very few mistakes — the genre\'s identity is built on polish and precision. However, the current trend toward "authentic" pop (bedroom pop, lo-fi pop) has expanded what imperfections are acceptable.',
    toleratedImperfections: [
      'Vocal breath sounds (now considered intimate rather than flawed)',
      'Slight pitch imperfection in emotional delivery (adds "realness")',
      'Lo-fi recording texture in indie/bedroom pop (aesthetic choice)',
      'Minor rhythmic looseness in acoustic/stripped versions (Clairo, Mac DeMarco bedroom-pop aesthetic)',
    ],
    celebratedFlaws: [
      'Vocal cracks on emotional notes — Olivia Rodrigo\'s "drivers license" quaver became a defining moment',
      'Audible room tone in bedroom pop (Billie Eilish\'s debut recorded in a small bedroom, and that intimacy sold the emotion)',
      'Analog warmth and subtle distortion recalling 80s synth-pop tape saturation (The Weeknd\'s "Blinding Lights" aesthetic)',
      'Unpolished demo quality that "captured the magic" — Robyn\'s "Dancing On My Own" kept the original vocal energy over technical perfection',
    ],
    overproductionRisks: [
      'Over-tuning vocals until they sound robotic and lifeless',
      'Too many layers — filling every frequency gap kills dynamics',
      'Over-compressing until the track has zero dynamic range',
      'Auto-Tune artifacts that distract from emotional delivery',
      'Excessive reverb that pushes the vocal too far back in the mix',
    ],
    authenticRoughness: 'In mainstream pop, roughness is almost never authentic — it is carefully curated. The "raw" vocal take was selected from 50 options. The lo-fi texture was added in mastering. The "mistake" was left in because it tested well. This curated imperfection is itself a pop convention.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['pop', 'catchy', 'radio-ready', 'hook-driven', 'polished', 'mainstream', 'melodic', 'vocal-driven'],
    avoidKeywords: ['experimental', 'noise', 'avant-garde', 'drone', 'atonal', 'free-form', 'harsh', 'lo-fi recording quality'],
    promptTemplate: '[sub-genre] pop, [tempo] BPM, [mood] mood, catchy hook, polished production, [vocal style] vocals, [key instruments]',
    tips: [
      'Specify the sub-genre for more accurate results (synth-pop, indie pop, etc.)',
      'Include mood descriptors: euphoric, melancholic, empowering, dreamy',
      'Reference a specific era if desired: 80s synth-pop, 2020s bedroom pop',
      'Describe the energy level: high-energy dance, mid-tempo groove, slow ballad',
      'Mention specific instruments or sounds you want featured',
      'Use "radio-ready" or "streaming-friendly" for mainstream polish',
    ],
  },
};
