import type { GenreGuide } from './types';

export const REGGAE_GUIDE: GenreGuide = {
  id: 'reggae',
  name: 'Reggae',
  language: 'English',

  sonicPalette: {
    overview: 'Laid-back, bass-heavy, and rhythmically distinctive. Reggae is defined by its off-beat rhythm guitar ("skank"), deep bass lines, and spacious production. The sound is warm, organic, and deeply grooved — music designed to move your body and mind.',
    timbre: [
      'Off-beat rhythm guitar (clean, staccato "skank")',
      'Deep, round bass guitar (prominent in mix)',
      'One-drop drum pattern',
      'Organ bubbling (rhythmic organ stabs)',
      'Brass section (trombone, trumpet, saxophone)',
      'Clean, natural vocals',
      'Melodica and keyboards',
      'Percussion (bongo, shaker, tambourine)',
    ],
    texture: 'Spacious and bass-heavy — the mix is dominated by bass and drums with everything else creating space around them. Reverb and delay create dub-influenced depth. The texture is warm, organic, and uncluttered.',
    tonality: 'Mix of major and minor. Major for celebratory, upful tracks. Minor for roots, protest, and reflective material. Warm tonality with prominent bass frequencies.',
    signatureSounds: [
      'Off-beat guitar skank',
      'One-drop kick-snare pattern',
      'Deep, melodic bass lines',
      'Organ bubble (rhythmic stabs)',
      'Dub echo and delay effects',
      'Spring reverb on snare',
      'Horn section stabs',
    ],
  },

  rhythmAndGroove: {
    overview: 'The off-beat is everything — reggae\'s distinctive rhythm places emphasis on beats 2 and 4 while the bass and drums create a deep pocket. The one-drop drum pattern is the genre\'s signature.',
    bpmRange: { min: 65, max: 100, sweet: 80 },
    feel: 'Laid-back and heavy — the groove sits deep in the pocket, slightly behind the beat. The music should feel relaxed but powerful, like a slow wave pulling you in.',
    swing: 'Subtle — reggae has its own rhythmic feel that isn\'t swing in the jazz sense. The off-beat skank creates a lilting quality. Some dancehall uses more pronounced rhythmic variation.',
    syncopation: 'Essential — the off-beat guitar is inherently syncopated. Bass lines play syncopated patterns against the one-drop. The entire rhythmic framework is built on off-beat emphasis.',
    grooveArchetype: 'One-drop reggae, rockers rhythm, steppers beat, or dancehall riddim',
    rhythmicSignatures: [
      'One-drop: kick and snare together on beat 3 (nothing on beat 1)',
      'Rockers: kick on every beat, snare on 3',
      'Steppers: four-on-the-floor kick, snare on 3',
      'Off-beat guitar skank (beats 2 and 4, and all off-beats)',
      'Organ bubble (rhythmic stabs on off-beats)',
      'Bass playing on beats 1 and 3 or syncopated patterns',
      'Rim click or cross-stick on off-beats',
    ],
  },

  harmonicLanguage: {
    overview: 'Simple and effective — reggae harmony uses basic chords in service of the groove and message. The chord progression is often a short loop that repeats throughout, allowing the bass, vocals, and arrangement to provide variation.',
    scales: ['Major', 'Natural Minor', 'Pentatonic Minor', 'Dorian', 'Mixolydian'],
    chordProgressions: [
      'I – IV – V – I (roots reggae)',
      'i – bVII – bVI – V (minor reggae)',
      'I – V – vi – IV (pop reggae)',
      'i – iv – i – V (minor groove)',
      'I – IV – I – IV (two-chord vamp)',
      'i – bIII – bVII – IV (roots minor)',
    ],
    harmonyNotes: 'Chords are played as staccato stabs on the off-beat. The bass provides harmonic movement while chords provide rhythmic color. Seventh chords and minor chords add depth. Keep harmonic rhythm simple.',
    modality: 'Major for joy and praise. Minor for struggle and protest. Mixolydian and Dorian for roots flavor. The harmony serves the message and groove.',
  },

  songStructure: {
    overview: 'Groove-based and message-driven — reggae songs establish a rhythm and ride it. Structure supports the lyrical message and allows for dub treatment. Verses carry the message; choruses are communal hooks.',
    form: 'Intro – Verse – Chorus – Verse – Chorus – Dub/Instrumental – Verse – Chorus – Outro',
    sections: ['Intro (rhythm establishment)', 'Verse 1', 'Chorus', 'Verse 2', 'Chorus', 'Instrumental/Dub Section', 'Verse 3', 'Final Chorus', 'Outro'],
    arrangement: 'The groove is established in the intro and maintained throughout. Arrangement changes are subtle — instruments drop in and out. Dub sections strip back to bass and drums. Horn sections enter for emphasis.',
    introOutro: 'Intros: bass and drums establishing the groove, or guitar skank starting alone. Outros: groove riding out, dub effects, or fade. The groove bookends the song.',
    barLengths: 'Verses: 8-16 bars. Chorus: 4-8 bars. Instrumental: 8-16 bars. Total: 3-5 minutes.',
    hookPlacement: 'Chorus is the hook — simple, repetitive, communal. Bass lines serve as melodic hooks. The skank pattern is a rhythmic hook. Title phrase in the chorus.',
  },

  vocalDelivery: {
    overview: 'Natural, message-driven, and rhythmically sophisticated. Reggae vocals range from sweet, melodic singing (lovers rock) to powerful, prophetic chanting (roots) to rapid-fire toasting (dancehall).',
    phrasing: 'Relaxed and behind-the-beat. Phrases sit in the groove pocket. Toasting (DJ-style rapid vocal delivery) is rhythmically complex. Singing is melodic and emotionally direct.',
    affect: 'Varies by sub-genre — roots reggae: prophetic, righteous, powerful. Lovers rock: sweet, romantic, intimate. Dancehall: energetic, boastful, aggressive.',
    techniques: [
      'Melodic singing (sweet, natural tone)',
      'Toasting/DJ style (rapid rhythmic delivery)',
      'Chanting (roots, Rastafarian influence)',
      'Patois and Jamaican Creole delivery',
      'Harmony singing in thirds',
      'Call-and-response with backing vocalists',
      'Melodica playing as vocal substitute',
      'Vocal ad-libs and interjections',
    ],
    adlibStyle: 'Exclamations — "seen!", "yah man!", "one love!", "Jah!", "rastafari!", "bun dem!" Background vocal responses. Sound effects (gun shots in dancehall). DJ-style vocal interjections.',
    harmony: 'Sweet harmony singing — often in 3rds. Trio vocal harmonies (roots tradition). Call-and-response between lead and backing. Unison singing for emphasis.',
    grit: 'Minimal in roots and lovers rock — clean, natural vocal tone. More grit in dancehall and ragga styles. The voice should sound honest and unaffected.',
  },

  lyricalConventions: {
    overview: 'Reggae lyrics carry the message — from Rastafarian spiritual philosophy to social protest to romantic love. The lyric is the vehicle for consciousness-raising, celebration, and cultural identity.',
    themes: [
      'Rastafarian spirituality (Jah, Zion)',
      'Social justice and anti-oppression',
      'Love and romance',
      'African repatriation and identity',
      'Babylon system critique',
      'Peace, unity, and one love',
      'Herb/ganja culture',
      'Dancing and partying (dancehall)',
      'Resilience and overcoming struggle',
    ],
    perspective: 'First person prophetic or personal. Communal "we" for unity messages. Rasta spiritual perspective. Direct address to Babylon (the system) or Jah (God).',
    figurativeLanguage: 'Rastafarian symbolism — Babylon (oppressive system), Zion (homeland/heaven), fire (purification), lion (strength). Nature imagery. Biblical references reinterpreted through Rasta lens.',
    vocabulary: 'Jamaican Patois/Creole, Rasta vocabulary ("I and I" for we, "Ital" for natural, "overstanding" for understanding). English mixed with Patois. Cultural-specific terms.',
    storytellingApproach: 'Message-driven — each song has a clear message or story. Verses develop the theme. Chorus encapsulates the message. The lyric should inspire, educate, or celebrate.',
    cliches: [
      'One love, one heart',
      'Babylon system',
      'Jah guide/Jah provide',
      'Fire pon Babylon',
      'Roots and culture',
      'Rise up/stand up',
    ],
  },

  productionFingerprint: {
    overview: 'Bass-forward, spacious, and rhythmically precise. Reggae production is defined by its bass dominance, dub-influenced effects, and spacious mix. The bass and drums are the foundation; everything else fills the space around them.',
    mixAesthetic: 'Bass-dominant — the bass guitar is the loudest, most prominent element. Drums are punchy with spring reverb on snare. Guitar and keys sit behind, providing rhythmic texture. Vocals are clear and present. The mix is warm and spacious.',
    era: 'Classic roots reggae recording (Studio One, Tuff Gong) set the template. Dub production techniques (Lee "Scratch" Perry, King Tubby) expanded the sonic palette. Modern reggae maintains these principles.',
    signalChain: 'Bass: DI with compression for sustain and punch. Guitar: clean amp, minimal effects. Drums: close-miked, spring reverb on snare, room mics. Vocals: warm, natural recording. Dub: tape delay, spring reverb, EQ filtering.',
    modernTrends: 'Revival of roots sound. Digital production with classic aesthetic. Dancehall-pop crossover. Reggae fusion with hip-hop, R&B, and electronic. Dub techno and electronic dub.',
  },

  instrumentation: {
    coreInstruments: [
      'Bass guitar (prominent, melodic)',
      'Rhythm guitar (clean, off-beat skank)',
      'Drums (one-drop, rockers, or steppers)',
      'Organ (bubble pattern)',
      'Keyboards/synthesizer',
      'Brass section (trumpet, trombone, saxophone)',
      'Percussion (bongo, shaker, tambourine)',
      'Melodica',
    ],
    signatureSounds: [
      'Off-beat guitar skank',
      'Deep, melodic bass lines',
      'One-drop drum pattern',
      'Organ bubble',
      'Dub delay and echo',
      'Spring reverb snare',
      'Horn section stabs',
      'Melodica melodies',
    ],
    layering: 'Minimal and spacious — each instrument has its own space. Bass and drums dominate. Guitar and organ provide rhythmic texture. Horns and keys add color. Don\'t overcrowd the mix.',
    avoidInstruments: [
      'Heavy distorted guitars',
      'Electronic dance drums (unless digital reggae)',
      'Overly processed sounds',
      'Classical orchestral arrangements',
      'Auto-Tune (breaks natural feel)',
    ],
  },

  culturalContext: {
    overview: 'Reggae is Jamaica\'s gift to the world — a music born from struggle, faith, and creativity that became a global force for social justice, spiritual consciousness, and cultural identity.',
    origin: 'Kingston, Jamaica, late 1960s. Evolved from ska and rocksteady, influenced by American R&B, jazz, and African rhythmic traditions. Rastafarian movement provided spiritual foundation.',
    identity: 'Jamaican cultural identity and Rastafarian spiritual expression. Reggae represents resistance to oppression, celebration of African heritage, and the pursuit of social justice.',
    community: 'Sound system culture — mobile DJ setups that are the social hub of Jamaican communities. Dancehall culture. Rastafarian community. Global reggae festival circuit.',
    socialFunction: 'Voice of the oppressed — reggae has been the soundtrack to liberation movements worldwide. Party music (dancehall). Spiritual practice (roots/Rasta). Cultural ambassador for Jamaica.',
    authenticityMarkers: [
      'Connection to Jamaican culture and music tradition',
      'Understanding of Rastafarian philosophy (for roots)',
      'Rhythmic authenticity (proper skank, one-drop)',
      'Bass-driven production',
      'Message and consciousness in lyrics',
      'Live musicianship',
    ],
  },

  historicalLineage: {
    overview: 'From mento to ska to rocksteady to reggae to dancehall, Jamaican music has continuously evolved while maintaining its rhythmic and spiritual core.',
    roots: ['Mento', 'Ska', 'Rocksteady', 'American R&B', 'African Rhythms', 'Rastafarian Nyabinghi'],
    evolution: 'Mento (1940s-50s) → Ska (early 60s) → Rocksteady (1966-68) → Reggae (late 60s-70s) → Dub (70s) → Dancehall (80s-90s) → Modern reggae fusion (2000s-present).',
    keyEras: [
      '1960-1966: Ska era (The Skatalites, Desmond Dekker)',
      '1966-1968: Rocksteady transition',
      '1968-1983: Roots reggae golden age (Bob Marley, Peter Tosh)',
      '1970s-80s: Dub revolution (King Tubby, Lee Perry)',
      '1980s-90s: Digital dancehall era (Yellowman, Shabba Ranks)',
      '2000s-present: Modern reggae revival and fusion',
    ],
    influencedBy: ['Mento', 'Ska', 'R&B', 'Jazz', 'African Music', 'Rastafarian Nyabinghi'],
    influenced: ['Punk', 'Hip-Hop', 'EDM (Dubstep)', 'Pop', 'World Music', 'Afrobeats'],
  },

  subGenres: [
    {
      name: 'Roots Reggae',
      description: 'The classic sound — Rastafarian spirituality, social consciousness, and deep grooves. The foundation of the reggae tradition.',
      distinguishingFeatures: ['Rastafarian spiritual content', 'Deep, meditative grooves', 'One-drop rhythm', 'Conscious lyrics', 'Bass-heavy production'],
      bpmRange: { min: 65, max: 85 },
      keyArtists: ['Bob Marley', 'Peter Tosh', 'Burning Spear', 'Dennis Brown', 'Chronixx'],
      productionNotes: 'Deep bass, spacious mix. One-drop rhythm. Organic instruments. Warm, natural production. Let the groove breathe.',
      lyricNotes: 'Rastafarian philosophy, social justice, African repatriation, spiritual upliftment. Prophetic and conscious.',
      sunoPromptKeywords: ['roots reggae', 'roots', 'Rasta', 'one-drop', 'conscious reggae', 'Bob Marley', 'spiritual'],
    },
    {
      name: 'Dancehall',
      description: 'High-energy, digital, and danceable. Dancehall shifted reggae toward electronic production, faster rhythms, and MC-driven toasting.',
      distinguishingFeatures: ['Digital/electronic production', 'Fast toasting delivery', 'Riddim-based tracks', 'High energy', 'Explicit content common'],
      bpmRange: { min: 85, max: 110 },
      keyArtists: ['Vybz Kartel', 'Sean Paul', 'Beenie Man', 'Shaggy', 'Popcaan'],
      productionNotes: 'Digital production — synthesizers, drum machines. Riddim-based (one beat, multiple vocalists). High energy. Heavy bass. Clean, aggressive sound.',
      lyricNotes: 'Party, dance, sexual themes, boasting. Patois-heavy. Energetic and confrontational. Gun talk in some styles.',
      sunoPromptKeywords: ['dancehall', 'Jamaican dancehall', 'riddim', 'bashment', 'DJ style', 'toasting', 'party'],
    },
    {
      name: 'Dub',
      description: 'The production-as-art form — dub strips reggae tracks to their bass and drum essentials, then adds heavy delay, reverb, and effects. The studio is the instrument.',
      distinguishingFeatures: ['Heavy delay and reverb effects', 'Bass and drums emphasized', 'Instruments drop in and out', 'Studio manipulation as art', 'Spacious, atmospheric production'],
      bpmRange: { min: 65, max: 85 },
      keyArtists: ['King Tubby', 'Lee "Scratch" Perry', 'Scientist', 'Mad Professor', 'Adrian Sherwood'],
      productionNotes: 'Strip the mix to bass and drums. Apply heavy delay and reverb. Bring instruments in and out. Use EQ filtering. The mixer IS the musician.',
      lyricNotes: 'Often instrumental or with fragments of vocal floating through the mix. Echo and delay transform vocal phrases.',
      sunoPromptKeywords: ['dub', 'dub reggae', 'echo', 'spacious', 'bass heavy', 'reverb', 'King Tubby', 'atmospheric'],
    },
    {
      name: 'Lovers Rock',
      description: 'Sweet, romantic reggae — gentle grooves, smooth vocals, and love songs. Born in the UK Jamaican community.',
      distinguishingFeatures: ['Romantic themes', 'Smooth, gentle production', 'Sweet vocal melodies', 'UK origin', 'Lovers\' groove'],
      bpmRange: { min: 70, max: 90 },
      keyArtists: ['Gregory Isaacs', 'Janet Kay', 'Maxi Priest', 'Beres Hammond', 'Carroll Thompson'],
      productionNotes: 'Smooth, gentle production. Sweet bass lines. Clean guitar skank. Warm, romantic mix. Less dub effects, more melodic.',
      lyricNotes: 'Romantic love, desire, devotion. Sweet and sincere. Less political, more personal.',
      sunoPromptKeywords: ['lovers rock', 'romantic reggae', 'sweet reggae', 'love song reggae', 'smooth', 'gentle'],
    },
    {
      name: 'Ska',
      description: 'The upbeat, horn-driven precursor to reggae. Fast tempo, off-beat guitar, and walking bass lines with a joyful, energetic feel.',
      distinguishingFeatures: ['Fast tempo', 'Prominent horn section', 'Walking bass lines', 'Off-beat emphasis (upstroke)', 'Joyful, energetic feel'],
      bpmRange: { min: 120, max: 160 },
      keyArtists: ['The Skatalites', 'Desmond Dekker', 'The Specials', 'Madness', 'Toots & the Maytals'],
      productionNotes: 'Uptempo. Prominent horns. Walking bass. Off-beat guitar prominent. Live, energetic feel. Can be vintage or modern.',
      lyricNotes: 'Fun, social commentary, love. Energetic and positive. Can be humorous.',
      sunoPromptKeywords: ['ska', 'upbeat', 'horn section', 'two-tone', 'Jamaica ska', 'fast reggae', 'skank'],
    },
    {
      name: 'Rocksteady',
      description: 'The bridge between ska and reggae — slower tempo, bassier, more soulful. Smooth vocal harmonies over steady rhythms.',
      distinguishingFeatures: ['Slower than ska, faster than reggae', 'Smooth vocal harmonies', 'Prominent bass', 'R&B vocal influence', 'Soulful feel'],
      bpmRange: { min: 85, max: 100 },
      keyArtists: ['Alton Ellis', 'The Paragons', 'Ken Boothe', 'Phyllis Dillon'],
      productionNotes: 'Smooth, bass-heavy production. Vocal harmony focus. Steady rhythm. Clean guitar. Soulful mix.',
      lyricNotes: 'Love, dance, social themes. Smooth and soulful. Vocal harmony showcase.',
      sunoPromptKeywords: ['rocksteady', 'early reggae', 'soulful', 'smooth', 'vocal harmony', 'Jamaican R&B'],
    },
    {
      name: 'Ragga',
      description: 'Digitally-produced dancehall with heavy bass, electronic riddims, and aggressive toasting. The electronic evolution of dancehall.',
      distinguishingFeatures: ['Fully digital production', 'Heavy electronic bass', 'Aggressive toasting', 'Computerized riddims', 'High energy'],
      bpmRange: { min: 90, max: 110 },
      keyArtists: ['Shabba Ranks', 'Buju Banton (early)', 'Cutty Ranks', 'Super Cat'],
      productionNotes: 'Fully digital — synthesizers, drum machines. Heavy electronic bass. Computerized riddims. Aggressive energy.',
      lyricNotes: 'Boasting, party, cultural commentary. Aggressive delivery. Patois-heavy.',
      sunoPromptKeywords: ['ragga', 'digital dancehall', 'electronic reggae', 'heavy bass', 'computerized', 'aggressive'],
    },
    {
      name: 'Reggae Fusion',
      description: 'Reggae blended with pop, rock, hip-hop, or electronic elements for mainstream crossover appeal.',
      distinguishingFeatures: ['Genre-blending approach', 'Pop accessibility', 'Mainstream crossover appeal', 'Modern production', 'Reggae rhythms with other genre elements'],
      bpmRange: { min: 70, max: 110 },
      keyArtists: ['Protoje', 'Koffee', 'Skip Marley', 'Major Lazer (reggae tracks)', 'Shaggy'],
      productionNotes: 'Blend reggae rhythms with pop, hip-hop, or electronic production. Modern, accessible sound. Radio-friendly while maintaining reggae roots.',
      lyricNotes: 'Accessible themes — love, positivity, empowerment. Less Rasta-specific, more universal. English with some Patois.',
      sunoPromptKeywords: ['reggae fusion', 'modern reggae', 'pop reggae', 'reggae crossover', 'tropical', 'island pop'],
    },
    {
      name: 'Digital Reggae',
      description: 'Modern, electronically-produced reggae using digital tools to create new takes on classic rhythms.',
      distinguishingFeatures: ['Electronic production', 'Digital riddims', 'Modern sound design', 'Classic rhythms with new sounds', 'Computer-based production'],
      bpmRange: { min: 70, max: 100 },
      keyArtists: ['King Jammy', 'Bobby Digital', 'Stephen Marley', 'Damian Marley'],
      productionNotes: 'Digital production maintaining reggae rhythmic identity. Modern synths and samples. Can be roots-influenced or dancehall-influenced. Clean, contemporary sound.',
      lyricNotes: 'Full range — conscious, romantic, party. Modern perspectives on classic themes.',
      sunoPromptKeywords: ['digital reggae', 'modern roots', 'electronic dub', 'contemporary reggae', 'new roots'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Reggae audiences span from Rastafarian devotees to mainstream music fans. The culture values peace, unity, and social consciousness. Sound system culture remains central to the Jamaican experience.',
    fanExpectations: [
      'Authentic Jamaican rhythms',
      'Deep, heavy bass',
      'Meaningful lyrics (for roots)',
      'Danceable grooves',
      'Cultural respect and awareness',
      'Live musicianship',
    ],
    gatekeeping: 'Moderate — respect for Jamaican origin expected. Debates about commercialization. Rasta vs. secular reggae. Traditional vs. modern. Cultural appropriation discussions.',
    livePerformance: 'Sound system culture — massive speaker stacks and DJ/selector-led events. Band performances for roots and revival acts. Dance-focused events for dancehall. Festival appearances globally.',
    fashionAndAesthetic: 'Roots: Rastafarian colors (red, gold, green), dreadlocks, natural fashion. Dancehall: flashy, bold, colorful, fashion-forward. Varies widely by sub-genre.',
    crossoverPotential: 'Moderate to high — reggae rhythms and bass culture have influenced punk, hip-hop, EDM (dubstep), and pop. Specific songs cross over regularly. The genre\'s influence exceeds its chart presence.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'The one-drop is a study in deliberate absence — the kick drum\'s silence on beat 1 creates the reggae feel more than any note played. Everything in reggae sits behind the beat, creating a gravitational pull that makes the music feel heavier and slower than its BPM.',
    quantizationDeviation: 'Moderate but consistent. Reggae timing is not sloppy — it is precisely behind the grid. The entire band agrees to sit in the same pocket behind the beat, creating a unified laid-back feel that would collapse if any one element snapped to the grid.',
    aheadBehindBeat: 'Behind — constitutionally, definitionally behind. The bass drags slightly, the skank lands a hair late, and the vocals float above with relaxed phrasing. Playing on top of the beat in reggae sounds wrong. The "pocket" is behind, and the depth of that pocket defines the sub-genre.',
    humanizationMarkers: [
      'Bass notes that bloom slightly after the theoretical downbeat, creating weight',
      'Guitar skank with micro-variations in muting pressure and attack on each off-beat',
      'Rim clicks that drift organically around the off-beat rather than snapping to it',
      'Organ bubble stabs with slightly uneven spacing that breathes with the groove',
      'Vocal phrases that stretch and compress behind the rhythmic framework',
    ],
    genreSpecificFeel: 'Reggae\'s behind-the-beat feel is not laziness — it is precise intention. The one-drop drummer plays beat 3\'s combined kick-snare hit slightly late, and this micro-delay cascades through the entire band. The result is music that feels like it\'s pulling you into the earth.',
  },

  silenceAndSpace: {
    overview: 'The one-drop itself IS silence — the absence of the kick drum on beat 1 is reggae\'s most radical rhythmic invention. Silence defines the genre more than any sound it makes.',
    negativeSpaceRole: 'Foundational. The empty beat 1 creates a gravitational vacuum that pulls the listener into the groove. Dub takes this further, stripping entire tracks to bass and drums, letting delay trails fill the void. Space is structural, not decorative.',
    breathingPatterns: 'The groove breathes in two-bar cycles — the one-drop leaves beat 1 empty, the skank fills the off-beats, and the bass anchors the downbeats of the next bar. Dub breakdowns strip everything away, letting the listener float in space before the groove returns.',
    dynamicContrast: 'Dramatic in dub, subtle in roots. Dub uses extreme contrast — full band to solo bass in an instant. Roots reggae maintains a steady dynamic bed but varies intensity through instrumental layering. The contrast between the heavy bass and the delicate skank is itself a dynamic device.',
    whatIsDeliberatelyAbsent: [
      'Kick drum on beat 1 — the defining absence that creates the one-drop',
      'Busy fills and drum solos — the groove is sacred and unbroken',
      'Dense harmonic layering — the mix stays spacious with room around each element',
      'Continuous guitar sustain — the skank is staccato, creating rhythmic silence between strums',
      'Vocal melisma and overembellishment — delivery is direct and unadorned',
    ],
  },

  callAndResponse: {
    overview: 'Reggae\'s call-and-response operates at multiple levels — the lead singer calls and the harmony vocalists answer, the verse calls and the chorus responds communally, and the entire sound system culture is built on selector-crowd dialogue.',
    vocalInstrumentalDialogue: 'The bass line responds to the vocal melody — when the singer holds a note, the bass fills with a melodic run. Horn sections punctuate vocal phrases with answering stabs. The melodica provides instrumental commentary between vocal lines.',
    sectionInternal: 'The skank guitar and organ bubble exist in constant rhythmic call-and-response, alternating off-beat placements. The bass and drums carry on their own dialogue — the kick drops, the bass responds, the rim click punctuates.',
    audienceParticipation: 'Sound system culture makes audience participation foundational — the selector calls out, the crowd responds. In roots settings, chorus refrains are designed for communal singing. Dancehall events feature constant crowd interaction with DJs/MCs.',
    patterns: [
      'Lead vocal call answered by harmony trio singing response phrases',
      'Sound system selector calling "pull up!" and the crowd responding by demand for track restart',
      'Verse as prophetic statement, chorus as congregational response',
      'Horn section stabs answering vocal phrases in the spaces between lines',
      'Toasting MC calling out instructions that the dancing crowd physically answers',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Jamaican Patois is not broken English — it is a complete creole language with its own grammar, phonetics, and vocabulary that defines reggae\'s verbal identity and resists translation into standard English.',
    phoneticMarkers: [
      '"Th" sounds become "d" or "t" — "the" becomes "de," "thing" becomes "ting"',
      'Dropped final consonants — "just" becomes "jus," "respect" becomes "respec"',
      '"H" dropping at word beginnings — "him" becomes "im"',
      'Vowel shifts — "beer" sounds like "bia," "there" sounds like "deh"',
      'Rhythmic speech patterns with tonal emphasis on unexpected syllables',
    ],
    accentInfluence: 'Patois rhythm directly shapes reggae vocal melody — the speech pattern\'s natural syncopation maps onto the off-beat skank. Toasters and DJs ride the riddim using Patois cadences that are rhythmically inseparable from the music.',
    dialectVocabulary: [
      '"I and I" — Rastafarian pronoun meaning "we/us," reflecting divine unity',
      '"Irie" — feeling good, at peace, positive vibrations',
      '"Bumbaclaat" — strong exclamation, taboo but ubiquitous in dancehall',
      '"Yard" — Jamaica, home ("back a yard" means back home)',
      '"Ital" — natural, pure, unprocessed (Rasta dietary and lifestyle concept)',
      '"Overstanding" — Rasta replacement for "understanding," emphasizing rising above',
    ],
    regionWithinCulture: 'Kingston (Trenchtown as roots reggae birthplace, downtown dancehall culture), Montego Bay (tourist-facing reggae), rural Jamaica (Nyabinghi drumming and Rasta community), UK (lovers rock originated in London\'s Jamaican diaspora), Japan and Germany (surprisingly dedicated reggae scenes).',
  },

  performancePractice: {
    overview: 'Sound system culture is reggae\'s native performance context — massive speaker stacks in outdoor spaces where the selector, the MC, and the crowd create the event together. This is communal music-making where the boundaries between performer and audience blur.',
    improvisationConventions: 'Limited instrumental improvisation — the groove is composed and maintained. Improvisation lives in the selector\'s track choices, the MC\'s freestyle toasting over riddims, and the dub engineer\'s live mixing of effects. The riddim is a platform, not a departure point.',
    crowdInteraction: 'Constant and essential. "Pull up!" (rewind the track) is audience-directed. The selector reads the crowd to choose riddims. MCs direct the crowd — "put your lighters up," "wine your waist." The event is co-created.',
    stagePresence: 'Band performances (roots, revival): musicians stand steady, letting the groove do the work, with vocalist as focal point. Sound system events: the selector and MC are behind the decks, visible but secondary to the sound and the crowd. Dancehall: energetic, dance-focused, visually commanding.',
    livVsRecordedDifferences: 'Sound system performances are fundamentally different from recordings — tracks are played through massive bass-heavy speaker stacks that physically vibrate the body. Dub plates (exclusive recordings) exist only for live play. The live context adds bass weight and communal energy no recording can capture.',
    whatMakesAGoodShow: 'A sound system session where the bass is felt in the chest, the selector reads the crowd perfectly, every "pull up" is earned, and the dance continues until sunrise. For bands: a locked-in groove that makes the entire venue move as one organism.',
  },

  socioeconomicSubtext: {
    overview: 'Reggae was born in the yards and tenements of Kingston\'s poorest neighborhoods — the music carries the weight of Jamaican poverty, colonial exploitation, and Rastafarian resistance in every bass note and lyric.',
    materialConditions: 'Trenchtown and West Kingston\'s government yards — shared concrete housing projects — were reggae\'s incubator. Sound systems arose because communities couldn\'t afford live bands. Riddim culture (one backing track, many vocalists) maximized limited studio resources.',
    classIdentity: 'Reggae is working-class music that became intellectual through Rastafarian philosophy. The "sufferer" identity — someone who endures poverty with dignity and spiritual awareness — is reggae\'s central class narrative. Wealth in reggae lyrics is usually spiritual, not material.',
    politicalUndercurrent: 'Explicitly anti-colonial, anti-Babylon, and pro-liberation. Bob Marley\'s music directly addressed Jamaican political violence. Burning Spear\'s work centers African repatriation. Peter Tosh demanded equal rights. Reggae has soundtracked liberation movements from South Africa to Indigenous Australia.',
    implicitReferences: [
      'Babylon — the entire Western colonial-capitalist system, not just police or government',
      'Repatriation — the Rastafarian call to return to Africa, encoding centuries of displacement',
      'Sufferer narratives — "trenchtown rock" and "concrete jungle" as literal poverty description',
      'Ganja as both spiritual sacrament and economic survival crop for rural Jamaicans',
      'IMF structural adjustment programs of the 1980s — economic devastation coded into dancehall\'s rawness',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Riddim culture is reggae\'s most radical intertextual innovation — hundreds of different songs share the same backing track, creating a web of reference where every new vocal is in dialogue with every previous version.',
    canonKnowledge: 'Knowing the classic riddims is essential: Sleng Teng, Real Rock, Stalag, Answer, Diseases. A reggae musician must recognize these backing tracks and understand which vocalists recorded over them. The riddim is the shared text that connects the community.',
    samplingTradition: 'Riddim reuse IS reggae\'s sampling tradition — it predates hip-hop sampling by a decade. A producer builds a riddim, then multiple artists voice (record) over it. The same bass line and drum pattern appears under dozens of different songs, each adding new meaning.',
    quotationPractice: 'Vocalists reference previous versions of a riddim through melodic callbacks, lyrical responses to earlier voicings, and deliberate contrast with the most famous version. A new voicing of the Real Rock riddim is automatically in conversation with every previous version.',
    expectedReferences: [
      'Studio One riddims — the foundational backing tracks of reggae\'s golden age',
      'Bob Marley\'s catalog — the universal reggae reference point for melody and message',
      'Sleng Teng riddim — the digital revolution that transformed dancehall in 1985',
      'King Tubby\'s dub mixes — the production reference for space and effects treatment',
      'Lee "Scratch" Perry\'s Black Ark recordings — the template for experimental reggae production',
    ],
    lineageSignifiers: [
      'Voicing over a classic riddim signals respect for the tradition and confidence in your craft',
      'Using a one-drop pattern signals roots reggae alignment',
      'Referencing Selassie or Marcus Garvey signals Rastafarian consciousness',
      'Dub plate culture — exclusive recordings signal sound system credibility',
      'Nyabinghi drumming patterns signal deep Rastafarian spiritual connection',
      'Steppers rhythm signals the militant, marching roots tradition',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Reggae and dancehall performance cultures encode distinct physical vocabularies — roots reggae\'s meditative sway contrasts with dancehall\'s explicit, athletic movement, and both contexts carry gendered expectations about how bodies should move and be seen.',
    vocalGenderCodes: 'Male vocalists dominate roots reggae (prophetic, authoritative delivery) and dancehall (boastful, aggressive toasting). Female vocalists in roots occupy harmony roles or sweet-toned lead positions. In dancehall, female artists like Lady Saw and Spice claim space through explicit lyrical content and commanding vocal presence.',
    physicalityInPerformance: 'Dancehall\'s physical vocabulary is its defining feature — wine (circular hip movement), dutty wine (head rotation), daggering (simulated partner dancing) are codified movements. Roots reggae movement is subtler — a deep sway, locked knees, head nodding with the one-drop.',
    genderNarratives: 'Roots reggae frequently centers male spiritual authority and female idealization ("Rasta queen" archetype). Dancehall inverts this with female sexual agency (wine, skin-out) alongside male sexual boasting. Both frameworks carry assumptions about gender roles that contemporary artists navigate and challenge.',
    subversionExamples: [
      'Sister Nancy\'s "Bam Bam" — one of the most sampled reggae tracks, by a female DJ in a male-dominated field',
      'Lady Saw\'s explicit dancehall lyrics claiming sexual agency equal to male counterparts in the 1990s',
      'Koffee\'s emergence as a female roots-dancehall artist without relying on sexualized performance',
      'Spice\'s deliberate provocations challenging colorism and respectability politics simultaneously',
      'Etana\'s "The Strong One" positioning feminine strength within roots reggae\'s spiritual framework',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Reggae at 70-80 BPM feels slower than its numbers suggest — the heavy backbeat, deep bass weight, and behind-the-beat placement conspire to make the music feel like it\'s moving through warm honey.',
    psychologicalTempo: 'The perceived tempo of reggae is approximately 15-20% slower than its actual BPM because the one-drop emphasizes beat 3 rather than every beat, effectively halving the felt pulse. The bass weight adds gravitational drag that slows perception further.',
    weightAndMomentum: 'Reggae\'s momentum is downward — the music pulls toward the earth rather than driving forward. The bass frequencies are physically felt in the body, creating a sensation of sinking into the groove. This weight is what makes reggae uniquely physical despite its moderate tempo.',
    urgencyScale: 'Roots reggae (65-80 BPM): meditative, heavy, each bass note lands like a heartbeat. Mid-tempo (80-90 BPM): walking pace, the groove sweet spot where the body naturally rocks. Ska-tempo (120+ BPM): joyful urgency, the feet take over from the hips.',
    comparisonToSameBPM: 'Reggae at 75 BPM feels nothing like R&B ballad at 75 BPM — the reggae version is heavier, more spacious, and more physically grounding. The bass weight, the empty beat 1, and the behind-the-beat placement create a completely different relationship between body and rhythm.',
  },

  mistakeConventions: {
    overview: 'Reggae tolerates and even celebrates the organic roughness of human performance — the genre\'s greatest recordings were made in modest studios with limited equipment, and that rawness became an aesthetic standard.',
    toleratedImperfections: [
      'Bass notes with slightly uneven sustain and finger noise — the physical instrument is audible',
      'Guitar skank with variable muting pressure — each strum is unique',
      'Drum fills that disrupt the one-drop pocket momentarily before settling back',
      'Vocal trio harmonies slightly out of tune — the Wailers, Mighty Diamonds, and Culture traditions where human warmth outweighs mechanical precision',
      'Tape hiss and analog noise on classic recordings — accepted as part of the sonic texture',
    ],
    celebratedFlaws: [
      'Lee "Scratch" Perry\'s chaotic, overdriven Black Ark productions — distortion as spiritual expression',
      'King Tubby\'s accidental echo effects that defined dub — mistakes becoming techniques',
      'Bob Marley\'s imperfect vocal takes that conveyed emotional truth over technical polish',
      'Studio One\'s one-take recording approach where the energy mattered more than perfection',
      'Instrument bleed between microphones that created the warm, live-in-the-room sound',
    ],
    overproductionRisks: [
      'Quantizing the one-drop kills the behind-the-beat feel that defines reggae',
      'Cleaning up bass tone removes the finger noise and string rattle that grounds the sound',
      'Over-compressing the mix eliminates the dynamic relationship between bass and silence',
      'Digital reverb replacing spring reverb loses the mechanical character essential to the skank sound',
      'Auto-tuning Patois vocals strips the tonal speech melody from the language',
    ],
    authenticRoughness: 'The Studio One and Channel One sound — direct, unpolished, bass-heavy, with audible room ambience and the occasional studio noise — is the gold standard. Reggae recordings that are too clean sound sterile and disconnected from the genre\'s Kingston roots.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['reggae', 'off-beat', 'skank', 'bass-heavy', 'one-drop', 'Jamaican', 'groove'],
    avoidKeywords: ['heavy metal', 'EDM drop', 'auto-tune', 'country twang', 'industrial', 'harsh'],
    promptTemplate: '[sub-genre] reggae, [tempo] BPM, [mood] mood, [rhythm pattern], [vocal style], [instruments]',
    tips: [
      'Specify the sub-genre: roots, dancehall, dub, lovers rock, ska',
      'Describe the rhythm: one-drop, rockers, steppers, ska upbeat',
      'Mention the bass style: deep, melodic, heavy, sub-bass',
      'Reference the mood: conscious, romantic, party, meditative',
      'Include "off-beat" or "skank" for authentic reggae guitar',
      'Describe the vocal approach: singing, toasting, chanting',
    ],
  },
};
