import type { GenreGuide } from './types';

export const RNB_GUIDE: GenreGuide = {
  id: 'rnb',
  name: 'R&B',
  language: 'English',

  sonicPalette: {
    overview: 'Warm, sensual, and groove-driven. R&B centers the human voice over lush harmonic beds of keys, bass, and drums. Modern R&B blends organic warmth with electronic sheen — analog synths meet digital precision. The sound is intimate, like a late-night conversation.',
    timbre: [
      'Warm, breathy vocals with natural vibrato',
      'Rhodes/Wurlitzer electric piano with tremolo',
      'Smooth, round bass (fingerstyle or synth)',
      'Soft drum machine patterns (LinnDrum, SP-1200, modern kits)',
      'Lush string pads (real or synthesized)',
      'Warm analog synth pads',
      'Guitar with chorus and light overdrive',
      'Subtle vinyl warmth and saturation',
    ],
    texture: 'Rich and layered but never cluttered. Each instrument occupies its own frequency space around the vocal. The mix is warm — rolled-off highs, boosted low-mids for body. Depth created through reverb and space rather than distortion.',
    tonality: 'Mix of major and minor — major 7ths and 9ths for warmth, minor keys for longing. Flat keys common (Eb, Ab, Bb, Db). Rich harmonic content with extended chords (7ths, 9ths, 11ths, 13ths).',
    signatureSounds: [
      'Rhodes electric piano chords with tremolo',
      'Finger snaps on beats 2 and 4',
      'Moog bass or deep synth bass',
      'Vocal runs and melismatic embellishments',
      'Talk box or vocoder accents',
      'Wah-wah guitar licks',
    ],
  },

  rhythmAndGroove: {
    overview: 'The groove is everything. R&B rhythm is body-moving but not aggressive — it sways, bounces, and pulses. The pocket between the bass and drums creates a groove that makes you move without thinking.',
    bpmRange: { min: 60, max: 110, sweet: 85 },
    feel: 'Smooth and laid-back. The beat should feel like it\'s behind the pulse — slightly lazy, relaxed, sensual. Even uptempo R&B maintains a cool, unhurried feel.',
    swing: 'Moderate to heavy — R&B grooves typically have significant swing, especially in neo-soul and classic styles. The hi-hat and snare ghost notes create a swinging, organic feel.',
    syncopation: 'Essential — bass lines syncopate heavily, anticipating chord changes. Vocal melodies float across bar lines. Guitar and keys play off-beat rhythms. The interplay creates infectious groove.',
    grooveArchetype: 'Two-step bounce, head-nod groove, or slow-wind sway. The groove should inspire subtle physical movement — shoulder rolls, head nods, or slow dancing.',
    rhythmicSignatures: [
      'Snare on 2 and 4 with ghost notes on 16th subdivisions',
      'Syncopated bass lines locking with kick drum',
      'Finger snaps or rim clicks as primary percussion',
      'Open hi-hat on off-beats for swing',
      'Kick patterns that complement bass syncopation',
      'Programmed drums with humanized velocity',
      'Half-time feel in ballads',
    ],
  },

  harmonicLanguage: {
    overview: 'R&B has the richest harmonic language in popular music. Extended chords (7ths, 9ths, 11ths, 13ths), chromatic movement, and jazz-influenced substitutions create the sophisticated, emotional sound that defines the genre.',
    scales: ['Major', 'Natural Minor', 'Dorian', 'Mixolydian', 'Pentatonic Minor', 'Blues Scale'],
    chordProgressions: [
      'IΔ7 – iii7 – vi7 – V7 (smooth R&B)',
      'IΔ7 – IV7 – iii7 – vi7 (neo-soul)',
      'ii7 – V7 – IΔ7 (jazz-R&B turnaround)',
      'i7 – iv7 – bVII7 – bIII (minor R&B)',
      'IΔ7 – vi9 – ii9 – V13 (sophisticated major)',
      'i9 – bVIΔ7 – bVII9 – i9 (modern R&B minor)',
      'IV – iii – vi – I (Motown-influenced)',
    ],
    harmonyNotes: 'Extended chords are standard, not optional. Major 7th, minor 7th, dominant 9th, and add9 chords are the basic R&B vocabulary. Chromatic bass movement adds sophistication. Voice leading should be smooth — common tones between chords.',
    modality: 'Balanced between major and minor. Major for joy and celebration, minor for longing and desire. Dorian mode common in neo-soul (minor with a natural 6th for warmth). Modal interchange frequent.',
  },

  songStructure: {
    overview: 'R&B structure serves the emotional arc — slow builds from intimate verses to soaring choruses. Bridges are moments of peak emotion. Outros are often extended, allowing vocal improvisation and ad-libs.',
    form: 'Intro – Verse – Pre-Chorus – Chorus – Verse – Pre-Chorus – Chorus – Bridge – Chorus – Outro/Vamp',
    sections: ['Intro', 'Verse 1', 'Pre-Chorus', 'Chorus', 'Verse 2', 'Pre-Chorus', 'Chorus', 'Bridge', 'Final Chorus', 'Outro/Vamp'],
    arrangement: 'Progressive build — verses are intimate and sparse, choruses open up with fuller production. The bridge is the emotional peak. Outros allow the vocalist to improvise runs and ad-libs over the vamp.',
    introOutro: 'Intros: often atmospheric — a chord, a vocal sample, or a stripped-down version of the groove. Outros: extended vamps where the singer improvisations freely. Can fade out or end with a final vocal moment.',
    barLengths: 'Verses: 8-16 bars. Pre-chorus: 4-8 bars. Chorus: 8 bars. Bridge: 4-8 bars. Outro/vamp: 8-16 bars (extended for vocal improv).',
    hookPlacement: 'Chorus is the primary hook, often with a memorable melodic phrase. Pre-chorus builds anticipation. Title phrase usually in the chorus. Melodic hooks can also appear in the intro or post-chorus.',
  },

  vocalDelivery: {
    overview: 'The voice is the soul of R&B. Vocal delivery ranges from intimate whispers to powerful belts, always with emotional authenticity. Melismatic runs, falsetto breaks, and dynamic control are hallmarks of R&B vocal mastery.',
    phrasing: 'Fluid and flowing — phrases glide over bar lines. Rubato (stretching and compressing time) is natural. The singer plays with the beat rather than sitting rigidly on it. Conversational in verses, soaring in choruses.',
    affect: 'Deeply emotional — love, desire, heartbreak, ecstasy, vulnerability. The voice conveys genuine feeling. Intimacy is key — the listener should feel like the singer is performing just for them.',
    techniques: [
      'Melismatic vocal runs (multiple notes per syllable)',
      'Falsetto and head voice for emotional peaks',
      'Breathy, intimate tone for verses',
      'Full belt for chorus climaxes',
      'Vibrato control — natural, expressive vibrato',
      'Vocal riffs and embellishments',
      'Scatting and melodic improvisation',
      'Dynamic range — from whisper to scream',
    ],
    adlibStyle: 'Vocal improvisation is central — "oh", "yeah", "baby", "come on". Runs and riffs between phrases. Background vocal responses ("ooh", "ahh"). The outro vamp is the ad-lib showcase.',
    harmony: 'Rich vocal harmonies — 3rds, 5ths, 7ths above and below the lead. Background vocal stacks creating chord voicings. Call-and-response between lead and backgrounds. Unison singing for power moments.',
    grit: 'Subtle — some rasp on emotional peaks is authentic. Clean tone is preferred for most passages. Grit serves the emotion, never overpowering the melody.',
  },

  lyricalConventions: {
    overview: 'R&B lyrics explore the full spectrum of romantic and emotional experience with poetic sensibility. From sensual desire to heartbreak, R&B lyrics are personal, intimate, and emotionally honest.',
    themes: [
      'Romantic love and desire',
      'Sexual intimacy and attraction',
      'Heartbreak and betrayal',
      'Self-worth and empowerment',
      'Late-night moods and atmosphere',
      'Nostalgia and memory',
      'Commitment and devotion',
      'Emotional vulnerability',
    ],
    perspective: 'First and second person intimate address — "I" speaking directly to "you." The listener becomes the object of desire, love, or heartbreak.',
    figurativeLanguage: 'Sensory metaphors — touch, taste, sight, scent. Water and fire imagery for passion. Night and darkness for intimacy. Nature metaphors for beauty. The figurative language serves emotional truth.',
    vocabulary: 'Intimate, sensual, emotionally articulate. Mix of poetic language and conversational directness. "Baby," "girl/boy," "tonight" as recurring terms. Modern R&B incorporates hip-hop slang.',
    storytellingApproach: 'Emotional vignettes — capturing a feeling, a moment, a situation. Less narrative structure, more emotional exploration. Each verse deepens the emotional theme.',
    cliches: [
      'Making love in the rain',
      'All night long',
      'Body/skin/touch imagery',
      'Can\'t live without you',
      'Nobody else compares',
      'Late night calls',
      'Candles and silk sheets',
    ],
  },

  productionFingerprint: {
    overview: 'R&B production balances warmth and clarity — the mix should feel like a warm embrace. Modern R&B blends organic instruments with electronic production, maintaining the genre\'s soulful core while embracing contemporary sounds.',
    mixAesthetic: 'Warm, full, and intimate. Vocals are prominent but not harsh — present without being in-your-face. Bass is round and full. Drums are smooth with punch. The overall frequency balance leans warm (slightly boosted low-mids, smooth highs).',
    era: 'Current era: genre-fluid R&B blending with hip-hop, electronic, and alternative influences. Minimal production with atmospheric textures. Vulnerability and authenticity valued over vocal gymnastics.',
    signalChain: 'Vocals: large-diaphragm condenser → tube preamp → gentle compression → EQ (warm, not bright) → plate or hall reverb. Keys: Rhodes/Wurlitzer through amp or direct with saturation. Bass: DI with compression and warmth. Drums: programmed with humanized velocity and timing.',
    modernTrends: 'Alternative R&B blending with electronic and indie. Lo-fi R&B aesthetics. Trapsoul (R&B vocals over trap beats). Afro-R&B fusion. Vulnerability and emotional honesty. Gender-fluid vocal styles.',
  },

  instrumentation: {
    coreInstruments: [
      'Electric piano (Rhodes, Wurlitzer)',
      'Synthesizer (pads, bass, leads)',
      'Bass guitar or synth bass',
      'Drum machine / programmed drums',
      'Electric guitar (clean, chorus, wah)',
      'Strings (real or synthesized)',
      'Acoustic piano',
    ],
    signatureSounds: [
      'Rhodes with tremolo and chorus',
      'Moog bass slides',
      'Finger snaps',
      'Talk box vocals',
      'Wah-wah guitar',
      'String sweeps for emotional moments',
      'Vinyl crackle for warmth',
    ],
    layering: 'Lush but transparent — instruments are layered for harmonic richness while maintaining clarity. The vocal sits in a clear pocket. Background instruments create a bed of harmony without competing.',
    avoidInstruments: [
      'Heavy distortion guitars',
      'Aggressive electronic sounds',
      'Banjo, mandolin (too country)',
      'Harsh synth leads',
      'Overly processed/robotic drums',
    ],
  },

  culturalContext: {
    overview: 'R&B is rooted in Black American musical tradition, evolving from the blues, gospel, and soul. It represents the emotional heartbeat of Black culture — love, desire, struggle, and joy expressed through sophisticated musicianship and vocal mastery.',
    origin: 'Emerged in the 1940s as a marketing term for Black popular music. Evolved through doo-wop (50s), Motown (60s), funk-soul (70s), new jack swing (late 80s), and into contemporary R&B.',
    identity: 'Black cultural expression — emotional authenticity, musical virtuosity, and style. R&B artists are expected to be complete musicians: singers, performers, and style icons.',
    community: 'Urban, culturally sophisticated audience. Strong overlap with hip-hop audience. Gospel church roots still evident in vocal style and community values. Social media and streaming-driven discovery.',
    socialFunction: 'Soundtrack to romance, intimacy, and emotional life. Wedding songs, date-night music, heartbreak processing. R&B provides the emotional vocabulary for relationships.',
    authenticityMarkers: [
      'Vocal ability and emotional delivery',
      'Musical sophistication (harmony, arrangement)',
      'Connection to R&B history and lineage',
      'Emotional honesty and vulnerability',
      'Style and visual presentation',
      'Live performance capability',
    ],
  },

  historicalLineage: {
    overview: 'From the blues to Motown to Prince to Frank Ocean, R&B has continuously evolved while maintaining its core identity: the Black voice expressing the full range of human emotion over sophisticated grooves.',
    roots: ['Blues', 'Gospel', 'Jazz', 'Doo-Wop', 'Soul'],
    evolution: 'Blues-influenced vocal groups (40s-50s) → Motown polish (60s) → Funk-soul fusion (70s) → Synth-driven quiet storm (80s) → New Jack Swing (late 80s-early 90s) → Hip-hop soul (90s) → Neo-soul revival (late 90s-2000s) → Alternative R&B (2010s-present).',
    keyEras: [
      '1950s-60s: Doo-wop and Motown',
      '1970s: Funk-soul fusion (Stevie Wonder, Marvin Gaye)',
      '1980s: Synth R&B and quiet storm (Luther Vandross, Whitney)',
      '1990s: New Jack Swing to hip-hop soul (Mary J. Blige, TLC)',
      '2000s: Neo-soul revival (D\'Angelo, Erykah Badu)',
      '2010s-present: Alternative R&B (Frank Ocean, SZA, The Weeknd)',
    ],
    influencedBy: ['Blues', 'Gospel', 'Jazz', 'Funk', 'Hip-Hop', 'Electronic Music'],
    influenced: ['Pop', 'Hip-Hop', 'Neo-Soul', 'K-Pop', 'Latin Pop', 'Afrobeats'],
  },

  subGenres: [
    {
      name: 'Contemporary R&B',
      description: 'Modern mainstream R&B blending traditional vocal soul with hip-hop production, electronic elements, and pop accessibility.',
      distinguishingFeatures: ['Polished, radio-ready production', 'Hip-hop influenced beats', 'Strong vocal performances', 'Pop-accessible hooks', 'Electronic production elements'],
      bpmRange: { min: 70, max: 110 },
      keyArtists: ['Beyoncé', 'Chris Brown', 'Usher', 'Rihanna', 'Bruno Mars'],
      productionNotes: 'Clean, polished production. Blend organic instruments with electronic beats. Strong hooks. Dance-oriented grooves. High production value.',
      lyricNotes: 'Love, relationships, empowerment, celebration. Accessible and relatable. Catchy, singable choruses.',
      sunoPromptKeywords: ['contemporary R&B', 'modern R&B', 'smooth R&B', 'urban pop', 'R&B pop', 'polished'],
    },
    {
      name: 'Neo-Soul',
      description: 'Organic, jazz-influenced R&B that prioritizes live instrumentation, natural vocals, and spiritual/conscious lyrics. A return to soul music roots with modern sensibility.',
      distinguishingFeatures: ['Live instrumentation emphasis', 'Jazz harmonies and chord voicings', 'Natural, unprocessed vocals', 'Afrocentric spirituality and consciousness', 'Organic, warm production'],
      bpmRange: { min: 65, max: 100 },
      keyArtists: ['Erykah Badu', 'D\'Angelo', 'Lauryn Hill', 'Jill Scott', 'Anderson .Paak'],
      productionNotes: 'Live instruments: Rhodes, upright bass, live drums. Minimal electronic processing. Warm, analog-feeling mix. Jazz-influenced harmonies. Room reverb over digital.',
      lyricNotes: 'Spiritual, conscious, introspective. African diaspora identity. Natural beauty. Love as spiritual connection. Poetry and spoken word influences.',
      sunoPromptKeywords: ['neo-soul', 'organic soul', 'jazzy R&B', 'live instruments', 'Afrocentric', 'conscious soul', 'warm'],
    },
    {
      name: 'Alternative R&B',
      description: 'Experimental, genre-bending R&B that incorporates electronic, indie, and avant-garde elements. Moody, atmospheric, and boundary-pushing.',
      distinguishingFeatures: ['Electronic and experimental production', 'Dark, moody atmospheres', 'Genre-blending (indie, electronic, hip-hop)', 'Vulnerable, introspective lyrics', 'Non-traditional song structures'],
      bpmRange: { min: 60, max: 120 },
      keyArtists: ['Frank Ocean', 'The Weeknd', 'SZA', 'FKA twigs', 'Daniel Caesar'],
      productionNotes: 'Atmospheric, spacious production. Electronic textures with organic elements. Dark reverb and delay. Minimalist arrangements. Experimental sound design.',
      lyricNotes: 'Introspective, vulnerable, confessional. Mental health, identity, sexuality. Poetic and literary. Emotionally complex.',
      sunoPromptKeywords: ['alternative R&B', 'dark R&B', 'moody R&B', 'atmospheric', 'experimental soul', 'indie R&B'],
    },
    {
      name: 'Quiet Storm',
      description: 'Slow, sensual, late-night R&B designed for intimacy. Smooth vocals over lush, minimal arrangements. Named after Smokey Robinson\'s 1975 album and the radio format it inspired.',
      distinguishingFeatures: ['Slow tempo', 'Sensual, intimate mood', 'Lush, minimal arrangements', 'Smooth, controlled vocals', 'Late-night atmosphere'],
      bpmRange: { min: 55, max: 75 },
      keyArtists: ['Luther Vandross', 'Anita Baker', 'Sade', 'Maxwell', 'Toni Braxton'],
      productionNotes: 'Minimalist, spacious arrangements. Soft drums or no drums. Electric piano and strings. Warm, enveloping reverb. Everything serves the vocal intimacy.',
      lyricNotes: 'Romantic, sensual, intimate. Slow seduction. Devotion and desire. Poetic and tasteful — suggestive rather than explicit.',
      sunoPromptKeywords: ['quiet storm', 'slow jam', 'smooth R&B', 'sensual', 'late-night', 'intimate', 'romantic R&B'],
    },
    {
      name: 'New Jack Swing',
      description: 'The bridge between R&B and hip-hop — uptempo, dance-oriented R&B with hip-hop beats, drum machines, and attitude. Created by Teddy Riley in the late 1980s.',
      distinguishingFeatures: ['Drum machine-driven uptempo grooves', 'Hip-hop swagger with R&B vocals', 'Synth stabs and brass hits', 'Dance-oriented energy', 'Syncopated, funky bass lines'],
      bpmRange: { min: 100, max: 120 },
      keyArtists: ['Bobby Brown', 'Guy', 'Bell Biv DeVoe', 'SWV', 'Teddy Riley'],
      productionNotes: 'Drum machine grooves (LinnDrum, SP-1200). Funky synth bass. Brass stabs. Synth pads. Heavy swing. Dance-floor energy with R&B sophistication.',
      lyricNotes: 'Confident, playful, dance-oriented. Romantic pursuit with swagger. Party anthems. Youthful energy.',
      sunoPromptKeywords: ['new jack swing', 'NJS', '90s R&B', 'uptempo R&B', 'dance R&B', 'funky', 'swing beat'],
    },
    {
      name: 'Trapsoul',
      description: 'R&B vocals and emotional content over trap-influenced production. Moody, atmospheric, and introspective. Defined by Bryson Tiller\'s debut album that named the sub-genre.',
      distinguishingFeatures: ['Trap drums (808s, hi-hat rolls) under R&B vocals', 'Moody, dark atmosphere', 'Introspective, vulnerable lyrics', 'Sing-rap vocal delivery', 'Minimalist, spacious beats'],
      bpmRange: { min: 65, max: 85 },
      keyArtists: ['Bryson Tiller', 'PartyNextDoor', '6LACK', 'Summer Walker', 'Brent Faiyaz'],
      productionNotes: 'Trap drum patterns (808s, hi-hat rolls) with R&B melodic sensibility. Dark, atmospheric pads. Minimal arrangement. Spacious mix with heavy reverb. Sub-bass focused.',
      lyricNotes: 'Heartbreak, late-night thoughts, desire, insecurity. Vulnerable masculinity. Instagram-era relationship dynamics. Confessional.',
      sunoPromptKeywords: ['trapsoul', 'R&B trap', 'moody R&B', 'dark R&B', '808 R&B', 'atmospheric', 'vulnerable'],
    },
    {
      name: 'PBR&B',
      description: 'Hipster-influenced alternative R&B blending indie aesthetics with R&B vocal traditions. Lo-fi, atmospheric, and artistically ambitious.',
      distinguishingFeatures: ['Lo-fi production aesthetic', 'Indie/alternative influence', 'Atmospheric textures', 'Experimental vocal processing', 'Art-school sensibility'],
      bpmRange: { min: 60, max: 100 },
      keyArtists: ['How to Dress Well', 'Blood Orange', 'Kelela', 'Solange', 'Sampha'],
      productionNotes: 'Lo-fi textures with indie production values. Electronic elements (glitch, ambient). Reverb-heavy. Experimental but accessible. Art-film aesthetic.',
      lyricNotes: 'Abstract, poetic, introspective. Identity and belonging. Cultural commentary. Literary references.',
      sunoPromptKeywords: ['PBR&B', 'indie R&B', 'art R&B', 'lo-fi soul', 'experimental R&B', 'atmospheric soul'],
    },
    {
      name: 'Classic Soul-R&B',
      description: 'The original sound — gospel-rooted vocals over rhythmic arrangements featuring horn sections, rhythm guitar, bass, and drums. The foundation everything else builds on.',
      distinguishingFeatures: ['Gospel-rooted vocal power', 'Horn section arrangements', 'Rhythm guitar (clean, rhythmic strumming)', 'Walking or syncopated bass lines', 'Live band energy'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Aretha Franklin', 'Stevie Wonder', 'Marvin Gaye', 'Al Green', 'Otis Redding'],
      productionNotes: 'Live band recording — drums, bass, keys, guitar, horns. Analog recording warmth. Simple but effective arrangements. The vocal is the star. Room reverb and natural ambience.',
      lyricNotes: 'Love, heartbreak, social justice, spiritual devotion. Emotionally direct and powerful. Gospel-influenced intensity.',
      sunoPromptKeywords: ['classic soul', 'Motown', '60s soul', '70s soul', 'vintage R&B', 'gospel soul', 'retro soul'],
    },
    {
      name: 'UK R&B',
      description: 'British take on R&B incorporating UK garage, grime, and Afrobeats influences. Distinctive for its blend of American R&B vocal traditions with UK production aesthetics.',
      distinguishingFeatures: ['UK garage and grime production influence', 'British vocal accent and slang', 'Afrobeats rhythmic elements', 'Two-step and broken beat rhythms', 'London street culture'],
      bpmRange: { min: 70, max: 140 },
      keyArtists: ['Jorja Smith', 'FKA twigs', 'Craig David', 'MNEK', 'NAO'],
      productionNotes: 'Blend UK garage/two-step rhythms with R&B vocals. Afrobeats influence in drum patterns. Electronic production with organic touches. British sensibility in arrangement.',
      lyricNotes: 'British perspective on love and relationships. London culture and slang. Multicultural influences. Emotionally honest with UK understatement.',
      sunoPromptKeywords: ['UK R&B', 'British R&B', 'UK soul', 'garage R&B', 'London R&B', 'two-step soul'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'R&B audiences value vocal talent, emotional authenticity, and musical sophistication. The core audience is Black and urban, spanning ages 18-45, with significant crossover to all demographics.',
    fanExpectations: [
      'Exceptional vocal ability',
      'Emotional authenticity and vulnerability',
      'Musical sophistication in production and arrangement',
      'Smooth, polished presentation',
      'Connection to R&B history and tradition',
      'Sexual confidence without vulgarity (generally)',
    ],
    gatekeeping: 'Moderate — debates about "real R&B" vs. pop-R&B. Generational divides between classic soul fans and modern alternative R&B listeners. Vocal ability is the primary gatekeeper.',
    livePerformance: 'Vocal showcase — the live performance must demonstrate real singing ability. Intimate venues and concert halls preferred over festivals (though festivals are growing). Band-backed performances valued. Choreography for some, pure vocal performance for others.',
    fashionAndAesthetic: 'Sleek, stylish, and aspirational. R&B artists are style icons — fashion-forward, elegant, sensual. Visual aesthetic ranges from luxury (Beyoncé) to bohemian (Erykah Badu) to streetwear (The Weeknd).',
    crossoverPotential: 'High — R&B vocals and production techniques permeate pop, hip-hop, and global music. K-Pop heavily borrows from R&B. The genre\'s emotional language is universal.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'R&B lives and dies by the groove pocket — the micro-timing relationship between bass, drums, and the vocal. The vocal sits behind the beat in a "lazy" placement that creates sensuality. The rhythm section plays slightly behind the grid, creating a warm, enveloping feel that contrasts with pop\'s metronomic precision.',
    quantizationDeviation: 'Classic R&B: live musicians playing with natural human deviation, ghost notes on snare and hi-hat slightly rushed or dragged. Neo-soul: deliberately unquantized, Dilla-influenced pocket. Modern R&B: programmed drums with humanized velocity curves and micro-timing shifts, often 10-20ms behind strict grid.',
    aheadBehindBeat: 'The vocal almost always sits behind the beat — this is the defining R&B micro-timing signature. Singers like D\'Angelo, Erykah Badu, and SZA place syllables fractionally after the rhythmic pulse, creating intimacy and languid sensuality. Uptempo R&B (new jack swing) pushes the vocal slightly ahead for energy.',
    humanizationMarkers: [
      'Ghost notes on snare creating a "whispered" groove underneath — the SP-1200 and LinnDrum ghost patterns that defined 80s and 90s R&B',
      'Moog or synth bass notes arriving a fraction after the kick drum, creating the signature R&B "sway" pocket',
      'Vocal phrases that drift behind the harmonic rhythm — D\'Angelo and Erykah Badu sitting so far behind the beat the groove feels suspended',
      'Finger-snaps and rim clicks with natural velocity variation, not quantized to identical loudness',
      'Rhodes chord anticipations landing just before the downbeat, pulling the listener forward into the next bar — a Babyface and Jam & Lewis production hallmark',
    ],
    genreSpecificFeel: 'The R&B "pocket" is warmer and deeper than pop or hip-hop — it\'s designed to make the body sway rather than bounce. The groove invites you in rather than hitting you. Producers like The Neptunes achieved this through radical minimalism, while Babyface achieved it through lush, swung arrangements. The micro-timing is what separates R&B groove from a pop song with R&B chords.',
  },

  silenceAndSpace: {
    overview: 'Space in R&B serves intimacy. The Neptunes\' production for Kelis and N.E.R.D. proved that a kick, snare, and single synth line could be more seductive than a full arrangement. The silence between notes is where the listener leans in — R&B production creates space specifically so the voice can fill it.',
    negativeSpaceRole: 'Negative space in R&B is erotic architecture — the gaps between notes create tension and anticipation. A sparse verse beat with just a kick and a vocal creates the feeling of a whispered conversation. The Weeknd\'s early production (House of Balloons) used cavernous reverb tails as spatial texture, making emptiness itself an instrument.',
    breathingPatterns: 'The breath between vocal phrases is rhythmically significant — audible inhales before a phrase add intimacy. Production breathes in 4-bar cycles: instruments drop away, re-enter, create ebbs and flows. The pre-chorus often strips down to create space before the chorus fills it.',
    dynamicContrast: 'Intimate verses versus expansive choruses define R&B dynamic architecture. Quiet storm tracks maintain consistent low-level dynamics throughout for sustained mood. Contemporary R&B (SZA, Daniel Caesar) uses sudden dynamic drops — full production cutting to bare voice — as emotional punctuation.',
    whatIsDeliberatelyAbsent: [
      'Aggressive compression — R&B preserves dynamics for the whisper-to-belt emotional arc that defines the genre',
      'Constant harmonic motion — Rhodes pads and synth washes sustain and breathe rather than changing every bar',
      'Crash cymbals and dramatic drum fills between sections — R&B transitions through filter sweeps, vocal ad-libs, or bass note changes, not rock-style fills',
      'High-frequency brightness — treble is rolled off for the warm, late-night frequency balance that separates R&B from pop',
      'Vocal processing that obscures breath and lip sounds — the intimate sounds of the singer\'s body (inhales, mouth sounds) are kept as closeness markers',
    ],
  },

  callAndResponse: {
    overview: 'R&B call-and-response descends directly from gospel tradition but redirects the conversation from God to the beloved. The lead singer calls, the background vocals respond, and the listener is drawn into a three-way emotional exchange.',
    vocalInstrumentalDialogue: 'The vocal and the Rhodes piano are the classic R&B dialogue partners — the singer phrases, the keys respond with a fill. Guitar licks answer vocal lines (Prince\'s self-accompaniment is the pinnacle). Bass lines walk underneath the vocal, sometimes mimicking the melody, creating a subconscious conversation.',
    sectionInternal: 'Lead and background vocals maintain constant dialogue: the lead states, the backgrounds affirm ("ooh," "yeah," "mmhmm"). In the outro vamp, this becomes fully improvised — the lead singer riffs freely while backgrounds maintain the harmonic and rhythmic response.',
    audienceParticipation: 'Subtler than hip-hop or gospel — R&B crowd participation is singing along, slow dancing, and vocal affirmation. At concerts, audiences sing choruses back. The intimacy of R&B creates a different participation dynamic: communal swaying rather than call-and-response shouting.',
    patterns: [
      'Lead vocal phrase → background "ooh/ahh" response',
      'Vocal line → Rhodes or guitar fill in the gap',
      'Verse intimacy → chorus collective singing',
      'Singer\'s ad-lib → audience singing the hook back',
      'Spoken aside → melodic return',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'R&B is less regionally fragmented than hip-hop, but distinct regional traditions exist. The music\'s roots in different Black American communities created local vocal and production styles that persist today.',
    phoneticMarkers: [
      'Motown/Detroit: crisp diction, polished enunciation, pop-accessible clarity',
      'Memphis/Southern: drawled vowels, melismatic phrasing influenced by church singing',
      'Philadelphia: warm, rounded vowels, sophisticated harmonic sense in phrasing',
      'UK R&B: British vowels and London slang blended with American R&B vocal technique',
      'Toronto: Drake\'s influence — clipped Canadian vowels with Caribbean inflections',
    ],
    accentInfluence: 'R&B vocal style tends to smooth out regional accents more than hip-hop — the genre\'s emphasis on melodic beauty creates a somewhat standardized vocal approach. However, Southern R&B (K-Ci & JoJo, Anthony Hamilton) retains regional warmth, and UK R&B (Jorja Smith, FKA twigs) is defined by British inflection over American forms.',
    dialectVocabulary: [
      '"Shorty/shawty" (R&B term of address with Southern origin, bridging hip-hop and R&B registers)',
      '"Boo/bae" (intimate address — R&B\'s vocabulary for romantic subjects, distinct from hip-hop\'s harder language)',
      '"Feelin\' some type of way" (emotional ambiguity central to modern R&B — SZA, Summer Walker territory)',
      '"On my mind / on my body" (R&B\'s recurring dual address to emotional and physical desire)',
      '"Take it slow" / "all night" (tempo-of-intimacy language unique to R&B\'s slow-jam tradition from Luther Vandross to Bryson Tiller)',
    ],
    regionWithinCulture: 'While hip-hop is hyper-regional, R&B\'s identity is more about vocal lineage than geography. An R&B singer is placed in a tradition (Stevie → D\'Angelo → Frank Ocean) rather than a city. However, production aesthetics carry regional DNA: Toronto\'s moody atmospherics, Atlanta\'s trap-soul bounce, London\'s garage-influenced rhythms.',
  },

  performancePractice: {
    overview: 'R&B live performance is a showcase of vocal ability, emotional connection, and sensual charisma. The performer must demonstrate real singing talent — there is no hiding behind production in an R&B live show. The best R&B concerts feel like intimate conversations between artist and audience.',
    improvisationConventions: 'Vocal improvisation is expected — the outro vamp is the showcase. Singers riff, run, and ad-lib over the repeated vamp, demonstrating technical ability and emotional depth. Melismatic runs are improvised, never performed identically twice. Band musicians take instrumental solos, especially on keys and guitar.',
    crowdInteraction: 'Intimate and seductive. R&B artists pull audience members on stage, sing directly to individuals, and create moments of personal connection. Slow dancing in the crowd is encouraged. Concert energy builds from intimate to euphoric. The artist maintains eye contact and emotional vulnerability.',
    stagePresence: 'Smooth, controlled, and magnetic. Choreography ranges from sophisticated (Usher, Chris Brown) to understated (Frank Ocean, Daniel Caesar). Fashion is a core element — R&B artists are style icons. The stage presence communicates confidence, sensuality, and emotional availability.',
    livVsRecordedDifferences: 'Live R&B adds vocal improvisation and extended outros that don\'t exist on the record. Singers demonstrate vocal ability by adding runs, riffs, and modulations beyond the studio version. Band arrangements may differ from recorded tracks. The emotional intensity is heightened by the live moment.',
    whatMakesAGoodShow: 'Vocal ability is the non-negotiable — the singer must be able to sing live with power and nuance. Beyond that, emotional connection with the audience, tasteful band musicianship, and the ability to create an intimate atmosphere even in large venues. The best R&B shows leave the audience feeling like they were serenaded personally.',
  },

  socioeconomicSubtext: {
    overview: 'R&B\'s socioeconomic encoding is more aspirational and intimate than hip-hop\'s explicit class narration. The genre articulates Black middle-class aspiration, upward mobility, and the emotional life that economic stability (or instability) enables. Luxury in R&B is about setting — the candlelit apartment, the weekend getaway — rather than conspicuous consumption.',
    materialConditions: 'R&B narratives often assume a baseline of economic stability — the concerns are romantic and emotional rather than survival-oriented. However, artists like Mary J. Blige brought working-class Black female experience to the forefront. Contemporary R&B (SZA, Summer Walker) narrates the emotional toll of hustle culture and economic precarity.',
    classIdentity: 'R&B has historically served as the soundtrack to Black upward mobility — the music of the Black professional class, date nights, and aspirational living. Neo-soul complicated this by embracing bohemian anti-materialism. Trapsoul bridges R&B\'s middle-class aesthetic with hip-hop\'s street consciousness.',
    politicalUndercurrent: 'Less explicitly political than hip-hop, but politics permeate: Marvin Gaye\'s "What\'s Going On," D\'Angelo\'s "Black Messiah," Solange\'s "A Seat at the Table" all address racial politics through R&B\'s emotional framework. The genre\'s politics are often felt through the body rather than stated through the mind.',
    implicitReferences: [
      'Luxury signifiers (champagne, silk, designer sheets) as class markers',
      'Late-night settings encoding urban professional lifestyle',
      'Natural hair and Afrocentric aesthetics in neo-soul as political identity',
      'Uber/rideshare references in modern R&B as contemporary class markers',
      'Therapy and mental health language reflecting educated middle-class norms',
    ],
  },

  intertextualityAndSampling: {
    overview: 'R&B maintains a deep relationship with its own history — artists constantly reference, interpolate, and build upon their predecessors. Unlike hip-hop\'s sample-chop approach, R&B intertextuality tends toward interpolation (re-singing melodies) and stylistic homage (adopting a predecessor\'s vocal approach).',
    canonKnowledge: 'Every R&B singer is expected to know the lineage: Sam Cooke → Otis Redding → Stevie Wonder → Luther Vandross → D\'Angelo → Frank Ocean. Vocal technique is inherited — Beyoncé\'s runs reference Whitney\'s, who referenced Aretha\'s, who referenced Clara Ward\'s. This vocal genealogy is actively discussed by fans and artists.',
    samplingTradition: 'R&B borrows from hip-hop\'s sampling culture but applies it differently — samples are often used as harmonic foundations rather than chopped rhythmically. The Neptunes sampled for texture, not groove. Timbaland built beats around R&B vocal samples. Modern R&B producers sample 90s R&B, creating recursive loops of influence.',
    quotationPractice: 'Interpolation is R&B\'s primary intertextual method — re-singing a classic melody with new lyrics (Beyoncé interpolating Aaliyah, SZA interpolating Brandy). Cover versions are also important: performing a predecessor\'s song demonstrates respect and vocal lineage. Flipping a classic groove into a modern context shows creative mastery.',
    expectedReferences: [
      'Stevie Wonder\'s harmonic language as foundational vocabulary',
      'Prince\'s genre-blending as permission structure',
      'Whitney Houston\'s vocal technique as benchmark',
      'D\'Angelo\'s "Voodoo" as neo-soul production template',
      'Frank Ocean\'s "Blonde" as alternative R&B touchstone',
    ],
    lineageSignifiers: [
      'Vocal runs that quote specific classic performances',
      'Production that recreates a specific era\'s sonic palette',
      'Album concepts that reference classic R&B albums',
      'Collaborations that span generations (elder/younger pairings)',
      'Music video aesthetics that homage classic R&B visuals',
      'Live covers of canonical songs as credential markers',
    ],
  },

  genderAndBodyConventions: {
    overview: 'R&B has the most elaborated gender conventions of any contemporary genre. The music encodes specific expectations around masculine and feminine expression — vocal technique, lyrical content, visual presentation, and physical performance all carry gendered meanings that have evolved significantly across eras.',
    vocalGenderCodes: 'Male R&B vocals occupy a wide spectrum: deep, masculine chest voice (Barry White, Keith Sweat) to high falsetto (Prince, The Weeknd). Falsetto in male R&B signals emotional vulnerability, not femininity. Female R&B vocals range from powerful belt (Whitney, Beyoncé) to breathy intimacy (Aaliyah, Jhené Aiko). Both genders are expected to demonstrate melismatic ability.',
    physicalityInPerformance: 'Male R&B performance ranges from athletic choreography (Usher, Chris Brown) to still, emotionally-intense singing (Luther Vandross, Frank Ocean). Female performers navigate between powerful vocal performance and choreographed sensuality. The body in R&B is an instrument of seduction and emotional expression, not aggression.',
    genderNarratives: 'Traditional R&B gender narratives center heterosexual desire: male artists pursuing/worshipping women, female artists navigating desire and heartbreak. Contemporary R&B has expanded: Frank Ocean\'s queerness, SZA\'s complex female desire, The Weeknd\'s morally ambiguous masculine narratives. The genre increasingly accommodates gender complexity.',
    subversionExamples: [
      'Frank Ocean\'s bisexual love narratives normalizing queerness in R&B',
      'Prince\'s androgynous presentation challenging masculine norms',
      'Aaliyah\'s tomboy aesthetic creating space for non-hyperfeminine women in R&B',
      'Brent Faiyaz\'s toxic masculinity performed as self-aware critique',
      'Janelle Monáe\'s non-binary expression within R&B/soul tradition',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'R&B tempo is almost always perceived as slower than the actual BPM suggests. The behind-the-beat groove, sustained chord voicings, and languid vocal placement all create a psychological tempo that drags below the metronome. Even uptempo R&B (100+ BPM) feels unhurried.',
    psychologicalTempo: 'A quiet storm ballad at 65 BPM feels meditative and suspended in time. Mid-tempo R&B at 85 BPM feels like a slow groove — the sweet spot for body movement. Uptempo R&B at 110 BPM still feels relaxed because the swing and behind-the-beat placement create a "cool" sensation. New Jack Swing at 115 BPM is the only R&B that feels genuinely fast.',
    weightAndMomentum: 'R&B weight is warm and enveloping rather than heavy and impactful (like hip-hop). The low end is round, not punchy. Momentum builds through harmonic progression rather than rhythmic acceleration — chord changes carry the song forward. The Moog bass provides a pillowy weight that supports rather than dominates.',
    urgencyScale: '1-10 urgency: Quiet storm at 60 BPM = 1 (suspended time), slow jam at 70 BPM = 2, neo-soul at 85 BPM = 3, mid-tempo at 90 BPM = 4, contemporary R&B at 95 BPM = 5, new jack swing at 115 BPM = 7, uptempo dance R&B at 120 BPM = 8.',
    comparisonToSameBPM: 'R&B at 90 BPM feels completely different from hip-hop at 90 BPM. The R&B version is swaying, warm, and languid — you slow dance to it. The hip-hop version is head-nodding and rhythmically driven — you bounce to it. Same tempo, different weight distribution: R&B emphasizes the spaces between beats, hip-hop emphasizes the beats themselves.',
  },

  mistakeConventions: {
    overview: 'R&B has a nuanced relationship with imperfection. The genre values vocal ability and production polish, but the best R&B maintains an organic humanity — a breath, a slight pitch drift, a vocal crack — that prevents sterility. The line between "polished" and "overproduced" is R&B\'s central quality tension.',
    toleratedImperfections: [
      'Vocal pitch drift on sustained falsetto notes — The Weeknd and Frank Ocean let notes waver rather than correcting to sterile perfection',
      'Audible breaths between phrases functioning as intimacy markers — Aaliyah and Jhené Aiko made the breath part of the rhythm',
      'Rhodes or Wurlitzer key-release mechanical noise bleeding through the mix, adding analog warmth',
      'Bass notes from a Moog or fingerstyle player arriving slightly after the kick, creating the behind-the-beat R&B pocket',
      'Background vocal blend revealing individual singers\' timbres rather than a single homogeneous wall — Destiny\'s Child harmonies where you hear each voice',
    ],
    celebratedFlaws: [
      'D\'Angelo\'s deliberately under-articulated vocal delivery',
      'Vocal cracks on emotional high notes (vulnerability marker)',
      'Neo-soul\'s intentionally "rough" live-to-tape recording aesthetic',
      'The Weeknd\'s early vocal imperfections conveying emotional rawness',
      'Amy Winehouse\'s vocal roughness as emotional authenticity',
    ],
    overproductionRisks: [
      'Excessive Auto-Tune removing vocal character and emotion',
      'Over-compressed dynamics eliminating the whisper-to-belt range',
      'Too many vocal layers obscuring the lead singer\'s intimacy',
      'Quantized drums losing the organic groove pocket',
      'Studio perfection that makes the recording feel cold and clinical',
    ],
    authenticRoughness: 'The best R&B balances polish and humanity. D\'Angelo\'s "Voodoo" sounds simultaneously sophisticated and raw — instruments bleed into each other, vocals sit slightly off-center, the groove breathes organically. This is the ideal: technically excellent musicians playing with enough looseness to sound human, not programmed.',
  },

  referenceTracks: [
    {
      title: 'Kill Bill',
      artist: 'SZA',
      year: 2022,
      whyExemplary: 'Number-one hit that proved narrative R&B can dominate pop charts. Uses a revenge-fantasy film reference as emotional framework rather than generic heartbreak language.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Deceptively upbeat production against dark lyrics. Short song (2:33) — no fat, every second earns its place.',
      craftHighlight: 'Tonal dissonance as technique — cheerful melody delivers murderous lyrics. The gap between sound and content creates the emotional complexity.',
    },
    {
      title: 'Snooze',
      artist: 'SZA',
      year: 2022,
      whyExemplary: 'Alternative R&B that builds a love declaration around the mundane act of hitting snooze — transforms a daily ritual into devotion metaphor.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Layered vocal production with whispered and belted vocals coexisting. Guitar-driven R&B arrangement.',
      craftHighlight: 'The "snooze" metaphor carries multiple meanings: choosing to stay in bed (choosing the relationship), hitting pause on reality, refusing to wake up from the dream of love.',
    },
    {
      title: 'Essence',
      artist: 'Wizkid ft. Tems',
      year: 2021,
      whyExemplary: 'Afro-R&B crossover that became the template for how African and American R&B traditions can merge. Tems\' verse rewrote the rules for female features.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Stripped production: log drum, light percussion, bass. Wizkid and Tems trade sections rather than harmonizing. Under 4 minutes.',
      craftHighlight: 'Minimalism as seduction — the production leaves so much space that every vocal inflection becomes magnified. The restraint IS the sensuality.',
    },
    {
      title: 'Good Days',
      artist: 'SZA',
      year: 2021,
      whyExemplary: 'Alternative R&B meditation on mental health recovery that avoids both toxic positivity and wallowing. The writing holds hope and pain simultaneously.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus-outro. Psychedelic R&B production with layered synths and strings. Extended outro lets the emotion linger.',
      craftHighlight: 'The title "Good Days" is an aspiration, not a statement — each verse acknowledges the struggle while the chorus reaches toward hope. Honest without being heavy.',
    },
    {
      title: 'Best Part',
      artist: 'Daniel Caesar ft. H.E.R.',
      year: 2021,
      whyExemplary: 'Neo-soul duet that became a modern standard. The two voices create a conversation that feels genuinely intimate rather than performed.',
      structuralNotes: 'Verse (him)-verse (her)-chorus-verse (him)-verse (her)-chorus-outro. Guitar-and-voice arrangement. Harmonies only on the chorus — verses are separate confessions.',
      craftHighlight: 'The vocal arrangement tells the story — they sing separately in verses (individual perspectives) and together only on the chorus (shared feeling). Structure as narrative.',
    },
    {
      title: 'Shirt',
      artist: 'SZA',
      year: 2022,
      whyExemplary: 'Alternative R&B that uses a blood-stained shirt as central image — visceral, specific, and emotionally loaded without needing to explain why.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Dark, bass-heavy production. SZA\'s vocal switches between sung and spoken delivery within sections.',
      craftHighlight: 'Object-anchored storytelling — the shirt carries the entire emotional weight. Instead of describing feelings, the song describes an object that contains feelings.',
    },
    {
      title: 'Creepin\'',
      artist: 'Metro Boomin ft. The Weeknd & 21 Savage',
      year: 2022,
      whyExemplary: 'Hip-hop soul that interpolates Mario Winans\' classic with modern trap production. Proves R&B\'s melodic DNA persists even in hip-hop contexts.',
      structuralNotes: 'Verse (Weeknd)-chorus-verse (21 Savage)-chorus-bridge-chorus. The Weeknd sings, 21 Savage raps — contrasting deliveries over the same production create tension.',
      craftHighlight: 'Interpolation as recontextualization — the familiar melody triggers nostalgia while the new lyrics and production update the emotional context for a new generation.',
    },
    {
      title: 'Natural Brown Prom Queen',
      artist: 'Sudan Archives',
      year: 2022,
      whyExemplary: 'Experimental R&B that uses violin, electronic production, and spoken-word to explore Black girlhood. Pitchfork\'s best R&B album of 2022.',
      structuralNotes: 'Non-standard: spoken intro-verse-chorus-verse-chorus-extended instrumental. Violin leads the arrangement. Rhythm shifts between electronic beats and acoustic grooves.',
      craftHighlight: 'Genre-defiance as authentic expression — the combination of violin, electronic production, and confessional lyrics creates an R&B that only Sudan Archives could make.',
    },
    {
      title: 'Persuasive',
      artist: 'Doechii',
      year: 2022,
      whyExemplary: 'Hip-hop soul that showcases Doechii\'s ability to shift between singing and rapping with a confidence that makes both feel equally natural.',
      structuralNotes: 'Verse (rapped)-chorus (sung)-verse (rapped)-chorus (sung)-bridge (sung)-outro. The genre shifts within the song mirror the persuasion the lyrics describe.',
      craftHighlight: 'Register-switching as compositional tool — moving between rap and R&B vocals isn\'t just stylistic, it mirrors the push-pull dynamic the lyrics describe.',
    },
    {
      title: 'Midnight River',
      artist: 'Babyface ft. Ella Mai',
      year: 2022,
      whyExemplary: 'Classic R&B from a master songwriter pairing generational vocal talent. Proves the traditional ballad format still has power when written with craft.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Classic quiet storm arrangement: electric piano, strings, light drums. Babyface\'s signature melodic construction.',
      craftHighlight: 'Melody-first writing — Babyface\'s compositional approach prioritizes singable, memorable melody lines that carry emotion independent of the lyric.',
    },
    {
      title: 'Blind',
      artist: 'SZA',
      year: 2022,
      whyExemplary: 'Alternative R&B confessional that opens SOS with raw vulnerability — sets the album\'s emotional stakes in under three minutes.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Stripped production with acoustic guitar and minimal drums. SZA\'s voice is exposed and unprocessed.',
      craftHighlight: 'Vulnerability through vocal production — the lack of effects on the voice creates intimacy. You can hear breath, strain, and emotional breaks.',
    },
    {
      title: 'Here With Me',
      artist: 'd4vd',
      year: 2023,
      whyExemplary: 'Bedroom R&B breakthrough from a teenager recording in a closet — proved that emotional authenticity matters more than production budget.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Lo-fi production with reverbed guitar and programmed drums. Short and direct — 2:40 runtime.',
      craftHighlight: 'Lo-fi aesthetic as emotional signifier — the bedroom production quality signals vulnerability and privacy. The "imperfect" sound IS the point.',
    },
    {
      title: 'Daylight',
      artist: 'Victoria Monét',
      year: 2023,
      whyExemplary: 'Grammy Best R&B Song — masterclass in feel-good R&B that\'s musically sophisticated without being heavy. Monét\'s songwriter craft on full display.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Funky bassline drives the groove. Horn stabs and synth pads create warmth. Dance break section.',
      craftHighlight: 'Groove as emotion — the bassline carries the joy before a single word is sung. Monét writes from the rhythm up, building lyrics around how the body wants to move.',
    },
    {
      title: 'How Does It Make You Feel',
      artist: 'Victoria Monét',
      year: 2023,
      whyExemplary: 'Quiet storm revival that proves slow-burn seduction R&B thrives when written with patience. Seven minutes of escalating intimacy.',
      structuralNotes: 'Extended form: intro-verse-chorus-verse-chorus-instrumental break-verse-chorus-outro. Seven-minute runtime allows the groove to hypnotize. Minimal arrangement grows slowly.',
      craftHighlight: 'Patience as seduction — the song takes its time, mirroring the emotional dynamic it describes. The extended runtime is a compositional choice, not indulgence.',
    },
    {
      title: 'Telepatía',
      artist: 'Kali Uchis',
      year: 2021,
      whyExemplary: 'Bilingual R&B sung entirely in Spanish that crossed over globally — proved language is no barrier when the melody and feeling are universal.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Dreamy synth-R&B production. Spanish lyrics with universal melodic phrasing. Simple chord progression looped hypnotically.',
      craftHighlight: 'Melody as universal language — the hook transcends the Spanish lyrics because the melodic contour itself communicates the emotion. Uchis proved crossover doesn\'t require English.',
    },
    {
      title: 'Saturn',
      artist: 'SZA',
      year: 2024,
      whyExemplary: 'Existential R&B that asks cosmic questions ("are there better places to be?") over an acoustic groove — philosophy dressed as pop.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Acoustic guitar-driven with minimal production. Folksy R&B arrangement unusual for the genre.',
      craftHighlight: 'Cosmic scale applied to personal dissatisfaction — using Saturn and space as metaphors for wanting to escape your life elevates a simple feeling into something grand.',
    },
    {
      title: 'Residuals',
      artist: 'Chris Brown',
      year: 2023,
      whyExemplary: 'Contemporary R&B that demonstrates pure vocal and melodic craft — the kind of effortless-sounding melody writing that only comes from mastery.',
      structuralNotes: 'Verse-prechorus-chorus-verse-prechorus-chorus-bridge-chorus. Classic R&B production with modern trap-influenced percussion. Vocal runs in the bridge.',
      craftHighlight: 'Melodic craft at the highest level — the vocal melody is complex enough to impress musicians yet intuitive enough for anyone to sing along on first listen.',
    },
    {
      title: 'Drunk Text',
      artist: 'Henry Moodie',
      year: 2024,
      whyExemplary: 'Bedroom R&B that captures the specific modern anxiety of late-night phone regret — updates classic heartbreak with digital-age specificity.',
      structuralNotes: 'Verse-chorus-verse-chorus-bridge-chorus. Minimal production: piano, light drums, reverbed vocal. Under 3 minutes. Gen-Z pop-R&B hybrid.',
      craftHighlight: 'Temporal specificity — "drunk text" is a 2020s experience that updates the R&B tradition of late-night longing (quiet storm) for the smartphone era.',
    },
    {
      title: 'On My Knees',
      artist: 'RUFUS DU SOL ft. Labrinth',
      year: 2021,
      whyExemplary: 'Electronic R&B crossover that fuses dance music\'s build-and-release structure with R&B\'s vocal emotion. Labrinth\'s voice carries the human element over synths.',
      structuralNotes: 'Verse-build-chorus/drop-verse-build-chorus/drop-breakdown-chorus. Electronic dance structure with R&B vocal delivery. The "chorus" is both melodic and a production drop.',
      craftHighlight: 'Tension between human voice and electronic production — Labrinth\'s raw vocal emotion against synthetic textures creates a push-pull that neither genre achieves alone.',
    },
    {
      title: 'Used To Be Young',
      artist: 'Miley Cyrus',
      year: 2023,
      whyExemplary: 'Pop-R&B ballad that uses Cyrus\'s public biography as lyrical material — the listener\'s knowledge of her life adds layers the words alone don\'t carry.',
      structuralNotes: 'Verse-chorus-verse-chorus-outro. Piano ballad, minimal arrangement. Short and direct. The outro trails off rather than resolving — the story isn\'t finished.',
      craftHighlight: 'Autobiography as universal metaphor — "I used to be young" works for everyone, but knowing Cyrus\'s specific journey from Disney to here adds biographical weight.',
    },
  ],

  sunoPromptGuide: {
    essentialKeywords: ['R&B', 'soul', 'smooth', 'groovy', 'sensual', 'vocal', 'rhythm and blues'],
    avoidKeywords: ['heavy metal', 'punk', 'noise', 'harsh', 'aggressive', 'screaming', 'distorted'],
    promptTemplate: '[sub-genre] R&B, [tempo] BPM, [mood] mood, [vocal style] vocals, smooth [instruments], [era influence]',
    tips: [
      'Specify the R&B sub-genre: neo-soul, trapsoul, quiet storm, etc.',
      'Describe the vocal quality: breathy, powerful, falsetto, melismatic',
      'Mention key instruments: Rhodes, bass, live drums, synths',
      'Reference the mood: sensual, late-night, empowering, heartbroken',
      'Include era references if desired: 90s R&B, 2000s R&B, modern alternative',
      'Use "smooth" and "groove" as key descriptors',
    ],
  },
};
