import type { GenreGuide } from './types';

export const ROCK_GUIDE: GenreGuide = {
  id: 'rock',
  name: 'Rock',
  language: 'English',

  sonicPalette: {
    overview: 'Guitar-driven, raw, and dynamic. Rock is built on the electric guitar — its crunch, sustain, and power define the genre. From clean jangle to full distortion, the guitar is the voice of rock. Drums hit hard, bass locks the groove, and the vocal cuts through with conviction.',
    timbre: [
      'Overdriven/distorted electric guitar (tube amp saturation)',
      'Punchy, dynamic acoustic or close-miked drums',
      'Round, driving bass guitar (fingerstyle or pick)',
      'Raw, powerful vocals with natural grit',
      'Clean guitar with chorus/delay for contrast',
      'Power chords with palm muting',
      'Feedback and sustain as expressive tools',
    ],
    texture: 'Thick and layered in choruses — doubled guitars panned hard left and right. Verses can strip back to single guitar and vocal. The rhythm section (bass + drums) provides a solid, physical foundation. Dynamic contrast between quiet and loud is essential.',
    tonality: 'Mix of major and minor. Open keys with guitar-friendly voicings (E, A, G, D, C). Minor keys for darker rock. Power chords (root + fifth) are tonally ambiguous, lending flexibility.',
    signatureSounds: [
      'Power chord crunch through Marshall/Fender/Vox amps',
      'Guitar feedback',
      'Wah-wah pedal solos',
      'Crash cymbal accents',
      'Tom fills',
      'Distortion pedal (Tube Screamer, Big Muff, RAT)',
      'Guitar harmonics (natural and pinch)',
    ],
  },

  rhythmAndGroove: {
    overview: 'Driving and physical — rock rhythm is felt in the body. The kick and snare provide the backbone, the bass locks in, and the guitar provides rhythmic texture through strumming, palm muting, or riffing.',
    bpmRange: { min: 80, max: 180, sweet: 120 },
    feel: 'Driving, powerful, and physical. The beat should make you want to move — headbanging, air guitar, jumping. Even slower rock has an undeniable physical presence.',
    swing: 'Generally straight — rock uses straight 8th and 16th note feels. Blues-rock and classic rock may use shuffle (swung 8ths). Punk is aggressively straight.',
    syncopation: 'Moderate — guitar riffs often syncopate against the straight beat. Bass can play syncopated lines. Vocal melodies have freedom in phrasing. The push-pull between tight rhythm section and free vocal is a rock hallmark.',
    grooveArchetype: 'Straight-ahead rock drive, blues shuffle, punk thrash, or half-time stomp',
    rhythmicSignatures: [
      'Standard rock beat: kick on 1 and 3, snare on 2 and 4',
      'Driving 8th-note guitar strumming',
      'Tom-heavy fills between sections',
      'Palm-muted chugging on low strings',
      'Double-time feel in choruses',
      'Half-time breakdown sections',
      'Ride cymbal groove for intensity',
    ],
  },

  harmonicLanguage: {
    overview: 'Rock harmony is direct and powerful. Power chords and open chords dominate, with occasional chromatic or blues-inflected movements. The harmonic language is simpler than jazz or R&B but uses dynamics and arrangement to create emotional impact.',
    scales: ['Major (Ionian)', 'Natural Minor (Aeolian)', 'Pentatonic Minor', 'Blues Scale', 'Mixolydian', 'Dorian'],
    chordProgressions: [
      'I – IV – V (classic rock)',
      'I – bVII – IV (rock anthem)',
      'i – bVII – bVI – V (minor rock)',
      'I – V – vi – IV (pop-rock)',
      'I – IV – I – V (blues-rock)',
      'i – bIII – bVII – IV (grunge/alternative)',
      'I – bVII – IV – I (Mixolydian rock)',
    ],
    harmonyNotes: 'Power chords (root + 5th) are the building blocks. Suspended chords add tension. Open chord voicings ring out beautifully on acoustic. Barre chords provide mobility up the neck. Guitar-friendly keys with open strings are preferred.',
    modality: 'Mixolydian mode is the "rock sound" — major with a flat 7th. Minor pentatonic for riffs and solos. Aeolian for darker material. Dorian for a warmer minor sound. Blues scale for solos.',
  },

  songStructure: {
    overview: 'Rock structure is riff-driven — the main guitar riff often defines the song as much as the chorus melody. Dynamic contrast between sections is essential. The build from verse to chorus should feel like an escalation.',
    form: 'Intro (riff) – Verse – Chorus – Verse – Chorus – Solo/Bridge – Chorus – Outro',
    sections: ['Intro/Riff', 'Verse', 'Pre-Chorus', 'Chorus', 'Guitar Solo', 'Bridge', 'Final Chorus', 'Outro'],
    arrangement: 'Dynamic — quiet verses explode into loud choruses (loud-quiet-loud). Guitar layers increase in choruses. Drums intensify with crashes and fills. The guitar solo provides a climactic instrumental moment.',
    introOutro: 'Intros: often the main riff or a building groove. Can start with clean guitar before distortion kicks in. Outros: extended jam, riff repetition, or dramatic ending (big final chord, feedback).',
    barLengths: 'Verses: 8-16 bars. Chorus: 8-16 bars. Solo: 8-16 bars. Bridge: 4-8 bars. Total: 3-5 minutes (punk: 2-3 mins, prog rock: 5-20 mins).',
    hookPlacement: 'The riff IS a hook. Chorus melody is the vocal hook. Guitar riff hooks in intros and transitions. Title phrase usually in the chorus. Some rock songs are riff-defined rather than chorus-defined.',
  },

  vocalDelivery: {
    overview: 'Rock vocals are raw, powerful, and emotionally charged. From melodic singing to aggressive screaming, the voice cuts through distorted guitars with conviction and attitude. Imperfection is a virtue — grit, rasp, and edge convey authenticity.',
    phrasing: 'Rhythmically locked to the riff or playing against it. Phrases are punchy and declarative in choruses, more flowing in verses. Vocal melody often follows or contrasts the guitar riff.',
    affect: 'Confident, defiant, passionate, or anguished — rock vocals convey strong emotions without restraint. Anger, joy, rebellion, heartache — all delivered with intensity.',
    techniques: [
      'Belt singing with natural distortion',
      'Raspy, gritty tone (natural vocal fry)',
      'Screaming and yelling for intensity',
      'Melodic singing in verses, power in choruses',
      'Vocal growl and snarl',
      'Falsetto for contrast or climax',
      'Talk-singing (Lou Reed, Julian Casablancas)',
      'Harmonized vocals (Beatles, Queen influence)',
    ],
    adlibStyle: 'Yeah!, Woah!, Come on!, Alright! — exclamatory and energetic. Screams and howls. Minimal compared to R&B — rock ad-libs are punctuation, not decoration.',
    harmony: 'Unison and octave harmonies for power. 3rd and 5th harmonies in choruses (classic rock). Background "ooh" and "aah" vocals. Gang vocals (multiple voices shouting together). Queen-style multi-tracked vocal arrangements.',
    grit: 'Essential — grit and rasp are valued as signs of authenticity and emotion. Clean, perfect vocals can sound out of place in rock. The level of grit varies by sub-genre (pop-rock = less, punk/grunge = more).',
  },

  lyricalConventions: {
    overview: 'Rock lyrics range from the deeply personal to the anthemically universal. Rebellion, freedom, love, and existential questioning are core themes. The best rock lyrics balance specificity with universality.',
    themes: [
      'Rebellion and anti-establishment',
      'Freedom and escape',
      'Love and heartbreak',
      'Existential questioning',
      'Social commentary',
      'Youthful energy and recklessness',
      'Road and travel imagery',
      'Alienation and outsider identity',
      'Rock and roll itself',
    ],
    perspective: 'First person confessional or anthemic second person ("we"). Some third-person storytelling. The perspective can shift between personal and universal within a song.',
    figurativeLanguage: 'Vivid imagery — fire, road, night, storm. Extended metaphors for internal states. Some sub-genres (prog, art rock) use literary and mythological references. Punk uses direct, blunt language.',
    vocabulary: 'Varies wildly — from poetic (Radiohead) to profane (punk). Conversational language is common. Slang is era-appropriate. Technical musical jargon sometimes referenced.',
    storytellingApproach: 'Character sketches, confessional narratives, or mood pieces. Choruses distill the emotional thesis. Verses build the story or deepen the mood. Guitar solos "speak" where words can\'t.',
    cliches: [
      'Born to run/ride/be wild',
      'Rock and roll will never die',
      'Highway/road metaphors',
      'Fire and flames',
      'Breaking free/chains',
      'Living on the edge',
      'Night/darkness/shadows',
    ],
  },

  productionFingerprint: {
    overview: 'Rock production ranges from raw and live-sounding to carefully constructed walls of sound. The key is maintaining energy and dynamics — rock should feel alive and physical, not sterile.',
    mixAesthetic: 'Guitars: doubled, panned hard L/R, mid-frequency dominant. Bass: locked with kick drum, felt more than heard. Drums: dynamic with room sound. Vocals: present but competing with instruments for attention (unlike pop). Overall: louder choruses, quieter verses.',
    era: 'Current era: genre-blending (pop-rock, rap-rock, synth-rock), vintage revival sounds, bedroom/indie production alongside major-label polish.',
    signalChain: 'Guitar: guitar → pedalboard (tuner, drive, modulation, delay, reverb) → tube amp → mic (SM57). Bass: DI + amp. Drums: close-miked + room mics. Vocals: dynamic mic (SM58/SM7B) for live feel, condenser for studio.',
    modernTrends: 'Synth integration in rock arrangements. Post-punk revival sounds. Shoegaze texture influence. DIY/bedroom production aesthetic. Genre fusion with hip-hop, electronic, pop. Vinyl and analog revival.',
  },

  instrumentation: {
    coreInstruments: [
      'Electric guitar (rhythm and lead)',
      'Bass guitar',
      'Drum kit (kick, snare, hi-hat, toms, cymbals)',
      'Vocals',
      'Acoustic guitar (for dynamics and contrast)',
    ],
    signatureSounds: [
      'Marshall stack crunch',
      'Fender clean with chorus',
      'Les Paul sustain through tube amp',
      'Wah-wah solo tone',
      'Acoustic-to-electric dynamic shift',
      'Ride cymbal drive',
    ],
    layering: 'Doubled rhythm guitars panned hard L/R for width. Lead guitar on top for solos and hooks. Bass follows root notes or creates countermelody. Drums provide the dynamic engine.',
    avoidInstruments: [
      'Auto-Tune (antithetical to rock ethos)',
      'Heavy electronic drums (unless synth-rock)',
      'Tropical pop sounds',
      'R&B-style finger snaps',
      'EDM drops and builds',
    ],
  },

  culturalContext: {
    overview: 'Rock is rebellion, freedom, and youth culture codified in music. Born from the collision of Black blues/R&B and white country/folk, rock has defined generational identity for over 70 years.',
    origin: 'Mid-1950s America — Chuck Berry, Little Richard, Elvis Presley, Buddy Holly. A fusion of rhythm and blues with country and western, electrified and amplified.',
    identity: 'Countercultural — rock has historically positioned itself against mainstream conformity. From the 60s counterculture to punk to grunge, rock represents artistic independence and authentic expression.',
    community: 'Band culture — rock is about groups of musicians creating together. Scene-based: local venues, record stores, zines (now blogs/social media). Festival culture (Glastonbury, Coachella, Reading).',
    socialFunction: 'Generational identity marker, rebellion soundtrack, communal catharsis at live shows. Rock concerts create collective emotional experiences through volume and energy.',
    authenticityMarkers: [
      'Playing your own instruments',
      'Writing your own songs',
      'Live performance energy',
      'Artistic integrity over commercial success',
      'Band chemistry and dynamic',
      'Genuine emotional expression',
    ],
  },

  historicalLineage: {
    overview: 'Rock\'s story is one of continuous reinvention — each generation reacts against the last while building on its foundations. From Chuck Berry to Radiohead, the thread is electric guitars, drums, and attitude.',
    roots: ['Blues', 'R&B', 'Country/Western', 'Gospel', 'Folk'],
    evolution: 'Rock and roll (50s) → British Invasion and psychedelia (60s) → Hard rock and prog (70s) → Punk and new wave (late 70s-80s) → Alternative and grunge (90s) → Indie and post-punk revival (2000s) → Genre fusion (2010s-present).',
    keyEras: [
      '1955-1964: Rock and roll birth and early evolution',
      '1964-1969: British Invasion and psychedelia',
      '1969-1979: Hard rock, prog, and punk emergence',
      '1980-1991: Post-punk, new wave, hair metal, alternative',
      '1991-1999: Grunge, Britpop, and alternative dominance',
      '2000-present: Indie rock, post-punk revival, genre fusion',
    ],
    influencedBy: ['Blues', 'R&B', 'Country', 'Folk', 'Jazz', 'Classical'],
    influenced: ['Punk', 'Metal', 'Alternative', 'Pop', 'Hip-Hop (sampling)', 'Electronic'],
  },

  subGenres: [
    {
      name: 'Classic Rock',
      description: 'The canonical rock sound — guitar-driven, riff-based, and built on blues foundations. Stadium-ready anthems with powerful vocals, memorable riffs, and guitar solos.',
      distinguishingFeatures: ['Blues-based guitar riffs', 'Extended guitar solos', 'Powerful vocal delivery', 'Stadium-ready dynamics', 'Organ and piano accompaniment'],
      bpmRange: { min: 100, max: 140 },
      keyArtists: ['Led Zeppelin', 'The Rolling Stones', 'AC/DC', 'Aerosmith', 'Fleetwood Mac'],
      productionNotes: 'Big, room-filling guitar tones. Live, dynamic drums with room sound. Warm analog production. Let the instruments breathe. Guitar solos are essential.',
      lyricNotes: 'Love, freedom, rock lifestyle, road stories. Blues-influenced themes. Mythological and mystical references. Anthemic choruses.',
      sunoPromptKeywords: ['classic rock', '70s rock', 'blues rock', 'guitar solo', 'arena rock', 'stadium rock', 'riff-driven'],
    },
    {
      name: 'Alternative Rock',
      description: 'Emerged as an alternative to mainstream rock — more experimental, emotionally complex, and sonically adventurous than classic rock.',
      distinguishingFeatures: ['Non-traditional song structures', 'Emotional complexity', 'Mix of distortion and clean tones', 'Unconventional melodies', 'Introspective lyrics'],
      bpmRange: { min: 90, max: 150 },
      keyArtists: ['Radiohead', 'The Smashing Pumpkins', 'Foo Fighters', 'Muse', 'Arctic Monkeys'],
      productionNotes: 'Dynamic contrast — quiet verses, loud choruses. Layer clean and distorted guitars. Electronic elements welcome. Production can be polished or raw depending on intent.',
      lyricNotes: 'Introspective, abstract, emotionally complex. Social alienation, personal struggle, existential themes. Poetic and non-literal.',
      sunoPromptKeywords: ['alternative rock', 'alt-rock', 'modern rock', '90s alternative', 'indie rock', 'dynamic'],
    },
    {
      name: 'Indie Rock',
      description: 'DIY-ethos rock that values artistic independence and authenticity. Lo-fi to polished, always prioritizing creative vision over commercial calculation.',
      distinguishingFeatures: ['DIY production aesthetic', 'Artistic independence', 'Jangly or noisy guitars', 'Understated vocals', 'Anti-commercial ethos'],
      bpmRange: { min: 100, max: 160 },
      keyArtists: ['The Strokes', 'Tame Impala', 'Arcade Fire', 'Vampire Weekend', 'The National'],
      productionNotes: 'Can be lo-fi or polished, but always serves the song. Jangly guitars, interesting textures. Room for experimentation. Reverb and delay as aesthetic tools.',
      lyricNotes: 'Literary, clever, self-aware. Mundane details elevated. Emotional intelligence. Cultural references. Wit and vulnerability.',
      sunoPromptKeywords: ['indie rock', 'indie', 'jangly', 'lo-fi rock', 'DIY', 'college rock', 'bedroom rock'],
      embodiedDelta: {
        mistakeConventions: {
          authenticRoughness: 'Curated roughness — the imperfections sound effortless but are actually deliberate aesthetic choices',
          toleratedImperfections: ['Slightly out-of-tune guitars (lo-fi charm)', 'Room noise and ambient bleed', 'Vocal cracks from genuine emotion'],
          overproductionRisks: ['Radio-ready polish', 'Auto-tuned vocals', 'Stadium-sized reverb', 'Anything that sounds like money was spent'],
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Asymmetric breathing — space appears unexpectedly within songs; sections end abruptly or start late',
          dynamicContrast: 'Moderate — contrast comes from instrumentation changes (dropping to single guitar) rather than volume',
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Relaxed, behind-beat cool — the groove is casual and unhurried; trying too hard is the cardinal sin',
          aheadBehindBeat: 'Behind — everything sits back with studied nonchalance',
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Deep referential canon — Velvet Underground, Pavement, Guided by Voices, Pixies; knowing obscure bands signals credibility',
          lineageSignifiers: ['Velvet Underground drone', 'Pavement slackness', 'Pixies quiet-loud (without grunge heaviness)', 'Wire economy'],
        },
      },
    },
    {
      name: 'Punk Rock',
      description: 'Fast, loud, and short. Punk strips rock to its essentials — three chords, raw energy, and attitude. Anti-establishment, DIY ethos, and raw emotional delivery.',
      distinguishingFeatures: ['Fast tempo', 'Short songs (1-3 minutes)', 'Simple chord progressions', 'Raw, aggressive delivery', 'Anti-establishment lyrics', 'DIY production'],
      bpmRange: { min: 150, max: 220 },
      keyArtists: ['Ramones', 'The Clash', 'Sex Pistols', 'Bad Religion', 'Green Day'],
      productionNotes: 'Raw and fast. Minimal overdubs. Aggressive guitar tone. Fast, driving drums. Keep it simple and energetic. Production can be polished (pop-punk) or deliberately rough.',
      lyricNotes: 'Anti-authority, social criticism, personal frustration, nihilism. Direct and confrontational. Humor and sarcasm. Short, punchy phrases.',
      sunoPromptKeywords: ['punk rock', 'punk', 'fast', 'aggressive', 'DIY', 'three-chord', 'raw energy', 'rebellious'],
      embodiedDelta: {
        microTimingAndFeel: {
          aheadBehindBeat: 'Ahead of the beat — everything rushes forward; the drummer pushes tempo and the band chases',
          genreSpecificFeel: 'Controlled recklessness — the groove is about barely holding together at speed, not precision',
          quantizationDeviation: 'High — but always rushing forward, never dragging; the imprecision is directional',
        },
        silenceAndSpace: {
          negativeSpaceRole: 'No space by design — songs are packed wall-to-wall; silence only exists between songs',
          whatIsDeliberatelyAbsent: ['Solos longer than 8 bars', 'Gradual builds', 'Ambient passages', 'Dynamic subtlety'],
        },
        mistakeConventions: {
          toleratedImperfections: ['Pitch accuracy irrelevant', 'Wrong notes at speed', 'Feedback squeal', 'Out-of-tune guitars'],
          celebratedFlaws: ['Vocal strain and cracking from screaming', 'Amp buzz and hum', 'Songs falling apart at the end'],
          overproductionRisks: ['Any audible click track', 'Pitch correction', 'Multiple guitar overdubs', 'Polished vocal takes'],
          authenticRoughness: 'Amateurism is the point — technical skill is viewed with suspicion; anyone can (and should) start a band',
        },
        performancePractice: {
          improvisationConventions: 'Zero — play the song fast, play it loud, get off stage; the setlist is sacred',
          crowdInteraction: 'Physical chaos — moshing, stage diving, crowd surfing are expected; the barrier between band and audience collapses',
        },
      },
    },
    {
      name: 'Garage Rock',
      description: 'Raw, unpolished rock with a lo-fi aesthetic — sounds like it was recorded in a garage (and often was). Energetic, fuzzy, and unpretentious.',
      distinguishingFeatures: ['Lo-fi, raw recording quality', 'Fuzzy, overdriven guitar tone', 'Simple, energetic songs', 'Garage reverb and room sound', 'Unpretentious attitude'],
      bpmRange: { min: 120, max: 170 },
      keyArtists: ['The White Stripes', 'The Black Keys', 'The Hives', 'The Sonics', 'Ty Segall'],
      productionNotes: 'Embrace lo-fi. Fuzzy guitar tone. Room reverb. Minimal overdubbing. Mono or narrow stereo. Raw drum sound. Everything a bit messy and alive.',
      lyricNotes: 'Simple, direct, urgent. Love, frustration, fun. Not overthought. Raw emotional expression.',
      sunoPromptKeywords: ['garage rock', 'lo-fi rock', 'fuzzy', 'raw', 'garage', 'gritty', 'unpolished'],
    },
    {
      name: 'Post-Punk',
      description: 'The art-school offspring of punk — angular guitars, driving bass lines, and intellectual intensity. Dark, atmospheric, and rhythmically inventive.',
      distinguishingFeatures: ['Angular, trebly guitar tones', 'Prominent, driving bass lines', 'Dark, atmospheric mood', 'Baritone or deadpan vocals', 'Rhythmic complexity'],
      bpmRange: { min: 110, max: 150 },
      keyArtists: ['Joy Division', 'Interpol', 'Fontaines D.C.', 'IDLES', 'Protomartyr'],
      productionNotes: 'Prominent bass (often the melodic lead). Angular, chorus-effect guitars. Tight, motorik or driving drums. Dark reverb. Cold, sparse production.',
      lyricNotes: 'Intellectual, dark, existential. Social commentary. Literary references. Deadpan or intense delivery. Urban imagery.',
      sunoPromptKeywords: ['post-punk', 'angular', 'dark rock', 'driving bass', 'cold wave', 'gothic', 'new wave rock'],
      embodiedDelta: {
        silenceAndSpace: {
          negativeSpaceRole: 'Emptiness as architecture — space between bass notes and angular guitar stabs is deliberate and load-bearing',
          dynamicContrast: 'Moderate — tension comes from sparse-to-dense shifts rather than quiet-to-loud',
          whatIsDeliberatelyAbsent: ['Guitar solos', 'Warm tones', 'Comfortable resolution', 'Blues licks'],
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Motorik precision (Krautrock lineage) vs. angular human tension — the rhythm section is mechanical while guitars stab unpredictably',
          aheadBehindBeat: 'Bass and drums locked to grid; guitar and vocals exist in their own rhythmic world',
        },
        performancePractice: {
          stagePresence: 'Controlled intensity — Ian Curtis seizure-dancing, not rock-star posing; physicality is internal and tortured',
          crowdInteraction: 'Minimal — the band performs inward; audience watches rather than participates',
        },
        socioeconomicSubtext: {
          materialConditions: 'Post-industrial British cities — Manchester, Leeds, Sheffield; the music sounds like concrete and rain',
          classIdentity: 'Working-class art school — intellectualism without pretension; reading Camus but living on benefits',
        },
      },
    },
    {
      name: 'Psychedelic Rock',
      description: 'Mind-expanding rock that uses studio effects, unusual instruments, and extended compositions to create altered-consciousness experiences.',
      distinguishingFeatures: ['Heavy use of effects (reverb, delay, phaser, flanger)', 'Extended improvisations', 'Unusual instruments and sounds', 'Trippy, non-linear lyrics', 'Studio experimentation'],
      bpmRange: { min: 80, max: 140 },
      keyArtists: ['Pink Floyd', 'Tame Impala', 'King Gizzard', 'The Flaming Lips', 'Jimi Hendrix'],
      productionNotes: 'Heavy effects processing — reverb, delay, phaser, tape manipulation. Layered textures. Stereo panning effects. Extended sections. Experimental production techniques.',
      lyricNotes: 'Abstract, surreal, dreamlike. Stream of consciousness. Nature and cosmic imagery. Sensory descriptions. Non-linear narratives.',
      sunoPromptKeywords: ['psychedelic rock', 'psych rock', 'trippy', 'mind-bending', 'effects-heavy', 'acid rock', 'space rock'],
    },
    {
      name: 'Progressive Rock',
      description: 'Ambitious, technically complex rock that incorporates classical, jazz, and electronic influences. Extended compositions, concept albums, and virtuoso musicianship.',
      distinguishingFeatures: ['Complex time signatures and meter changes', 'Extended compositions (10+ minutes)', 'Virtuoso instrumental performances', 'Concept albums', 'Classical and jazz influences'],
      bpmRange: { min: 60, max: 180 },
      keyArtists: ['Pink Floyd', 'Rush', 'Yes', 'Tool', 'Porcupine Tree'],
      productionNotes: 'High production value. Complex arrangements. Multiple sections and movements within songs. Keyboards and synths prominent. Dynamic range emphasized.',
      lyricNotes: 'Conceptual, literary, philosophical. Science fiction, mythology, social commentary. Extended narratives. Can be abstract or highly detailed.',
      sunoPromptKeywords: ['progressive rock', 'prog rock', 'complex', 'epic', 'technical', 'concept', 'art rock'],
      embodiedDelta: {
        microTimingAndFeel: {
          genreSpecificFeel: 'Metronomic precision for odd meters — 7/8, 5/4, metric modulations demand rehearsed accuracy over feel',
          quantizationDeviation: 'Low — prog musicians aim for tight ensemble precision even in complex time signatures',
          humanizationMarkers: ['Precise unison hits across instruments', 'Tempo changes executed as composed', 'Polyrhythmic passages requiring mathematical precision'],
        },
        silenceAndSpace: {
          negativeSpaceRole: 'Composed silences — fermatas and dramatic pauses are written, not improvised; space serves the narrative arc',
          dynamicContrast: 'Classical-level dynamic range — whisper-quiet acoustic passages to full-band fortissimo within a single piece',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Tempo as compositional variable — a single piece may visit 5 different tempos; BPM is not a fixed identity but a narrative tool',
          urgencyScale: 'Variable within a single piece — from meditative 0/10 to frantic 10/10',
        },
        performancePractice: {
          stagePresence: 'Craftsman stance — musicians sit or stand still, focused on execution; the music IS the spectacle, not the bodies',
          improvisationConventions: 'Limited to designated solo sections within composed frameworks — free improvisation is rare',
        },
        intertextualityAndSampling: {
          canonKnowledge: 'Classical and jazz canon expected — quoting Stravinsky or Coltrane signals compositional ambition',
          lineageSignifiers: ['Classical orchestration references', 'Jazz harmony borrowings', 'Electronic experimentation (Tangerine Dream, Kraftwerk)'],
        },
      },
    },
    {
      name: 'Grunge',
      description: 'Raw, heavy, and emotionally honest — the Seattle sound that defined the early 90s. Combines punk attitude with metal heaviness and pop melody.',
      distinguishingFeatures: ['Heavy, sludgy guitar tone', 'Quiet verse / loud chorus dynamics', 'Angst-filled, honest lyrics', 'Flannel and anti-fashion aesthetic', 'Emotional rawness'],
      bpmRange: { min: 90, max: 140 },
      keyArtists: ['Nirvana', 'Pearl Jam', 'Soundgarden', 'Alice in Chains', 'Stone Temple Pilots'],
      productionNotes: 'Heavy, fuzzy guitar tone (Big Muff or similar). Dramatic quiet-loud dynamics. Raw vocal recording. Sludgy bass. Aggressive drums with room sound.',
      lyricNotes: 'Self-loathing, depression, alienation, irony. Emotional honesty. Anti-corporate, anti-superficial. Cryptic but deeply personal.',
      sunoPromptKeywords: ['grunge', 'Seattle sound', '90s rock', 'heavy', 'angsty', 'raw', 'sludgy', 'alternative'],
      embodiedDelta: {
        silenceAndSpace: {
          negativeSpaceRole: 'Quiet-loud as coiled tension — whispered verses are a spring compressed before the chorus detonates',
          dynamicContrast: 'Extreme — the gap between verse and chorus volume is the defining structural device',
        },
        regionalDialectSpecificity: {
          accentInfluence: 'Seattle mumble — anti-articulation as aesthetic; words are felt not heard clearly',
          phoneticMarkers: ['Slurred consonants', 'Vowel-heavy delivery', 'Vocal fry and strain', 'Mumbled verses exploding into screamed choruses'],
          regionWithinCulture: 'Pacific Northwest — Seattle, Olympia, Portland; rain-soaked introspection and isolation',
        },
        genderAndBodyConventions: {
          physicalityInPerformance: 'Anti-performative — musicians look at their shoes, slouch, wear thrift-store clothes; deliberate rejection of rock-star physicality',
          genderNarratives: 'Vulnerable masculinity — men expressing pain, confusion, self-loathing without macho posturing',
          subversionExamples: ['Kurt Cobain wearing dresses', 'Eddie Vedder\'s emotional fragility on stage', 'Layne Staley\'s unflinching addiction narratives'],
        },
        mistakeConventions: {
          authenticRoughness: 'Anti-80s reaction — roughness is a political statement against hair-metal polish and corporate rock production',
          overproductionRisks: ['Slick guitar tones', 'Visible studio polish', 'Backing vocals that sound "arranged"', 'Any hint of 80s production sheen'],
          celebratedFlaws: ['Feedback between songs', 'Vocal strain to the point of cracking', 'Bass distortion bleeding into everything'],
        },
      },
    },
    {
      name: 'Shoegaze',
      description: 'Wall-of-sound guitar rock characterized by layers of distortion, reverb, and feedback creating an immersive, dreamlike sonic landscape.',
      distinguishingFeatures: ['Walls of guitar noise and feedback', 'Buried, ethereal vocals', 'Heavy use of guitar pedals', 'Dreamy, transcendent mood', 'Dense, layered textures'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['My Bloody Valentine', 'Slowdive', 'Ride', 'Nothing', 'Deafheaven'],
      productionNotes: 'Layer multiple guitar tracks with different effects. Bury vocals in the mix. Heavy reverb and delay. Tremolo bar and pitch bending. The guitar noise IS the sound.',
      lyricNotes: 'Impressionistic, abstract, whispered. Words as texture rather than narrative. Sensory imagery. Romantic but obscured.',
      sunoPromptKeywords: ['shoegaze', 'dreamy rock', 'wall of sound', 'reverb-drenched', 'ethereal', 'noise pop', 'hazy guitars'],
      embodiedDelta: {
        silenceAndSpace: {
          negativeSpaceRole: 'No negative space — total sonic immersion; every frequency is filled with reverb trails, feedback, and layered guitars',
          whatIsDeliberatelyAbsent: ['Silence', 'Clean tones', 'Vocal clarity', 'Discrete instrument separation'],
          dynamicContrast: 'Low — the wall of sound maintains a consistent density; dynamics come from textural shifts, not volume changes',
        },
        microTimingAndFeel: {
          genreSpecificFeel: 'Obscured attack points — reverb and delay smear note onsets so timing becomes ambiguous and dreamlike',
          aheadBehindBeat: 'Irrelevant — the wash of sound dissolves the concept of "the beat" as a fixed point',
        },
        tempoFeelVsNumber: {
          psychologicalTempo: 'Temporal dilation — reverb and sustain make moderate tempos feel slower and more expansive than they are',
          weightAndMomentum: 'Weightless — the music floats rather than drives; forward momentum comes from harmonic movement, not rhythmic pulse',
        },
        genderAndBodyConventions: {
          vocalGenderCodes: 'De-gendered — vocals are buried so deep in the mix that gender becomes ambiguous; the voice is texture, not identity',
          physicalityInPerformance: 'Staring at pedals — the name "shoegaze" describes the performance stance; anti-spectacle by definition',
        },
        mistakeConventions: {
          toleratedImperfections: ['Feedback is essential, not accidental', 'Detuning is texture', 'Buried wrong notes invisible in the wash'],
          celebratedFlaws: ['Guitar noise and squeal', 'Mic feedback', 'Tremolo bar abuse', 'Strings buzzing against frets'],
          authenticRoughness: 'The noise IS the instrument — what sounds like mistakes is the core technique',
        },
      },
    },
    {
      name: 'Brit-Rock',
      description: 'British guitar rock with emphasis on melody, swagger, and working-class identity. From the Beatles through Britpop to modern UK rock.',
      distinguishingFeatures: ['Strong melodic focus', 'British vocal accent', 'Jangly to crunchy guitars', 'Working-class lyrics and identity', 'Anthemic choruses'],
      bpmRange: { min: 100, max: 150 },
      keyArtists: ['Oasis', 'Blur', 'Arctic Monkeys', 'The Libertines', 'Kasabian'],
      productionNotes: 'Melodic guitar hooks. British vocal delivery. Anthemic chorus production. Jangly verses, full choruses. Piano and organ accents.',
      lyricNotes: 'British life, working-class experience, nights out, relationships. Witty, observational. Regional slang and references.',
      sunoPromptKeywords: ['Britpop', 'British rock', 'UK rock', 'anthemic', 'melodic rock', 'indie British', 'Brit-rock'],
    },
    {
      name: 'Southern Rock',
      description: 'Rock rooted in the American South — blues-based, bourbon-soaked, and prideful. Dual lead guitars, boogie rhythms, and Southern identity.',
      distinguishingFeatures: ['Dual lead guitar harmonies', 'Blues-based riffs and solos', 'Southern accent and pride', 'Boogie and shuffle rhythms', 'Extended jam sections'],
      bpmRange: { min: 90, max: 140 },
      keyArtists: ['Lynyrd Skynyrd', 'The Allman Brothers', 'ZZ Top', 'Black Crowes', 'Blackberry Smoke'],
      productionNotes: 'Twin lead guitars harmonized in 3rds. Blues-rock tone. Shuffled boogie rhythms. Organ/piano accents. Live, room-filling sound.',
      lyricNotes: 'Southern pride, road life, whiskey, women, freedom. Blues storytelling influence. Regional identity. Celebratory and defiant.',
      sunoPromptKeywords: ['Southern rock', 'blues rock', 'boogie rock', 'dual guitars', 'Southern', 'Americana rock', 'swamp rock'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Rock audiences value authenticity, musicianship, and live performance. The audience is broad but skews older than hip-hop/pop — core fans are 25-55, though indie and alternative attract younger listeners.',
    fanExpectations: [
      'Real instruments and live musicianship',
      'Emotional authenticity',
      'Powerful live performances',
      'Artistic integrity',
      'Album-oriented artistry',
      'Band identity and chemistry',
    ],
    gatekeeping: 'Significant — "real rock" debates are constant. Guitar purists vs. experimentalists. Classic vs. modern. Indie vs. mainstream. Accusations of selling out.',
    livePerformance: 'The defining rock experience — loud, physical, communal. Mosh pits, crowd surfing, singalongs. Guitar solos and extended jams. The live show should surpass the recording.',
    fashionAndAesthetic: 'Band t-shirts, jeans, leather jackets. Each sub-genre has its own code: punk (DIY, patches), indie (thrift store, ironic), metal (black, band merch), classic rock (denim, vintage).',
    crossoverPotential: 'Moderate — rock elements blend into pop, hip-hop, and electronic music. But "pure" rock has become more niche in the streaming era. Crossover successes often blend rock with other genres.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Rock feel lives in the push-pull between drummer and guitarist — the slight tension between a drummer who sits right on the beat and a guitarist who pushes ahead creates the "driving" quality. When those roles reverse, you get a laid-back swagger. This micro-tension IS rock feel.',
    quantizationDeviation: 'Moderate to significant — rock is played by humans, and the deviations from the grid give it life. Punk pushes hard ahead of the beat. Blues-rock drags behind. The drummer and bass player lock together, but the guitar often floats slightly ahead or behind.',
    aheadBehindBeat: 'Punk sits aggressively ahead — the snare rushes, the guitars push. Blues-rock and classic rock lay behind — the groove has a lazy confidence. Indie rock varies by intent. The relationship between drummer and guitarist defines the sub-genre feel more than tempo.',
    humanizationMarkers: [
      'Slight flamming between kick drum and bass guitar attacks',
      'Guitar strumming that drifts ahead of the click on choruses',
      'Fill-ins where the drummer briefly rushes then settles back',
      'Vocal entries that land just after the downbeat for drama',
      'Hi-hat velocity inconsistencies that breathe with the song',
    ],
    genreSpecificFeel: 'The "Bonham feel" — slightly behind the beat with massive weight. The "Ramones rush" — everything pushing forward urgently. The "Keith Moon chaos" — fills that disrupt the grid and create controlled turbulence. Each sub-genre has a distinct timing signature that fans recognize instinctively.',
  },

  silenceAndSpace: {
    overview: 'Rock uses silence as a weapon — the quiet verse makes the loud chorus devastating. Space is earned, not given. The most powerful moments in rock are often the sudden absence of sound before a riff kicks back in.',
    negativeSpaceRole: 'Critical for dynamics — the quiet-loud-quiet-loud architecture of rock depends on space. A single clean guitar ringing in a verse makes the wall of distortion in the chorus feel enormous. Without space, everything is loud and nothing is heavy.',
    breathingPatterns: 'Verse breathing: stripped instrumentation, space between phrases. Pre-chorus: gradual filling of space, building tension. Chorus: full frequency occupation. Bridge: often returns to space before the final explosion.',
    dynamicContrast: 'Extreme in the best rock — Nirvana codified this as quiet-verse/loud-chorus but the Pixies invented it. The dynamic range between the quietest and loudest moments defines a rock song\'s emotional impact. Compression wars have reduced this, but great rock still uses it.',
    whatIsDeliberatelyAbsent: [
      'Bass dropping out during guitar solos to create lift',
      'Drums stopping before a big re-entry (the "drop")',
      'Clean guitar alone after a wall of distortion',
      'Vocal a cappella moments before the full band hits',
      'Complete silence before the final chorus crashes in',
    ],
  },

  callAndResponse: {
    overview: 'Rock call-and-response has deep blues roots — the guitar "answers" the vocal, and the audience completes the circuit at live shows. The interplay between voice and instrument is conversational, not decorative.',
    vocalInstrumentalDialogue: 'Guitar fills answer vocal phrases — a classic rock convention from blues tradition. The lead guitar "speaks" in the spaces where the vocal pauses. In the guitar solo section, the instrument takes over the vocal role entirely.',
    sectionInternal: 'Verse-chorus itself is a call-and-response: verses pose questions or build tension, choruses answer with resolution. Within verses, guitar riff and vocal trade prominence bar by bar.',
    audienceParticipation: 'Central to live rock — singalong choruses, call-and-response shouts ("hey!" / crowd response), clap patterns, and the shared experience of screaming lyrics back at the performer.',
    patterns: [
      'Vocal phrase → guitar fill (blues-rock tradition)',
      'Band stops → audience sings the hook a cappella',
      'Lead guitar call → rhythm guitar response',
      'Verse vocal question → chorus vocal answer',
      'Drum fill call → full band crash response',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Rock accent is tied to place and era — British rock sounds distinctly different from American rock, and regional specificity within each tradition carries meaning. The Clash sound like London; Nirvana sounds like the Pacific Northwest; AC/DC sound like working-class Australia.',
    phoneticMarkers: [
      'British rock: flattened vowels, clipped consonants, working-class regional accents preserved (Arctic Monkeys\' Sheffield, Oasis\' Manchester)',
      'American punk: nasal, clipped, fast diction (Ramones\' Queens accent)',
      'Grunge: slurred, mumbled delivery as anti-articulation statement',
      'Southern rock: drawled vowels, relaxed diction, regional idiom',
      'Indie rock: understated, slightly affected disinterest in diction',
    ],
    accentInfluence: 'Rock singing originally borrowed from Black American blues phrasing regardless of the singer\'s origin. British Invasion artists sang in American-influenced accent; punk reclaimed native accents. Post-punk and Britpop made British accent a badge of identity.',
    dialectVocabulary: [
      'Britpop: "mate," "innit," "rubbish," "brilliant" — class-specific British slang',
      'Punk: "anarchy," "destroy," "bored" — deliberately confrontational lexicon',
      'Grunge: "whatever," "nevermind" — Gen-X disaffection vocabulary',
      'Southern rock: "y\'all," "fixin\' to," "down home" — regional Southern idiom',
      'Garage rock: stripped, monosyllabic, urgent — no wasted words',
    ],
    regionWithinCulture: 'Manchester vs. London vs. Sheffield in UK rock each carry distinct class and cultural meaning. In the US, Seattle grunge, NYC punk, LA glam, and Southern rock are all rock — but the regional identity shapes everything from lyrical concerns to vocal delivery to fashion.',
  },

  performancePractice: {
    overview: 'Rock performance is about rawness, energy, and the communal experience of volume. The live show should feel dangerous, unpredictable, and more intense than the recording. Controlled chaos is the ideal.',
    improvisationConventions: 'Guitar solos are the primary improvisation space — extended in concert, sometimes completely reimagined. Jam bands (Grateful Dead tradition) improvise extensively. Punk has zero improvisation by design. Most rock falls between: structured songs with improvised solo sections.',
    crowdInteraction: 'Direct and physical — crowd surfing, mosh pits, singalongs, call-and-response. The barrier between performer and audience is meant to be thin. Stage diving. Guitar picks and drumsticks thrown to fans. Eye contact from the stage.',
    stagePresence: 'Physical and commanding — the frontperson owns the stage with movement, attitude, and charisma. Guitarists have signature stances (power stance, guitar slung low). Drummers are the engine visible behind the kit. Stage presence is learned but must look effortless.',
    livVsRecordedDifferences: 'Live rock should be louder, more intense, and less polished than the recording. Extended solos, faster tempos, heavier arrangements. The crowd energy feeds the performance. Songs are often played differently live — the recording is a blueprint, not a script.',
    whatMakesAGoodShow: 'Volume, energy, and the feeling that the band is giving everything. Moments of genuine danger or unpredictability. A setlist that builds. Encores that feel earned. The sense that this particular show is unique and unrepeatable.',
  },

  socioeconomicSubtext: {
    overview: 'Rock has historically functioned as the sound of working-class and middle-class white youth, though its roots are in Black American music. Class identity runs through rock — from punk\'s explicit working-class rebellion to grunge\'s suburban alienation to Britpop\'s council-estate pride.',
    materialConditions: 'Punk emerged from economic stagnation (1970s UK unemployment, NYC urban decay). Grunge from post-industrial Pacific Northwest malaise. Brit-rock from Northern English working-class towns. The economic conditions that produce rock are typically those of downward mobility or stagnation.',
    classIdentity: 'Punk is explicitly working-class and anti-bourgeois. Classic rock often romanticizes blue-collar life. Indie rock is associated with educated middle-class audiences. Grunge expressed the disillusionment of suburban kids who expected middle-class comfort and found emptiness.',
    politicalUndercurrent: 'Rock carries anti-establishment DNA — from 1960s counterculture to punk\'s anarchism to grunge\'s anti-corporate stance to indie\'s rejection of major labels. Even apolitical rock implicitly rejects conformity through volume and attitude.',
    implicitReferences: [
      'Dead-end jobs and factory work (Springsteen, punk)',
      'Suburban boredom and the desire to escape (Green Day, Blink-182)',
      'Urban decay and gentrification (post-punk, NYC rock)',
      'The cost of artistic integrity vs. commercial success ("selling out")',
      'DIY culture as economic necessity turned into aesthetic choice',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Rock is deeply self-referential — bands build on riffs, tones, and attitudes from previous generations. Unlike hip-hop\'s literal sampling, rock intertextuality works through influence, homage, and the shared vocabulary of the guitar riff.',
    canonKnowledge: 'Fans and musicians are expected to know the lineage — Led Zeppelin borrowed from Willie Dixon, Nirvana borrowed from the Pixies, Arctic Monkeys borrowed from The Strokes. Acknowledging your influences is authentic; hiding them is suspect.',
    samplingTradition: 'Rare in rock compared to hip-hop — rock bands play their own instruments. When sampling occurs (DJ Shadow, Beck), it signals genre-crossing. The rock equivalent of sampling is the "influenced-by" riff or the cover song.',
    quotationPractice: 'Cover songs are a primary form of homage. Guitar tone itself is a quotation — choosing a Les Paul through Marshall references a lineage. Deliberate musical quotation (a riff that echoes another) can be tribute or theft depending on context.',
    expectedReferences: [
      'Blues riffs and progressions (the I-IV-V framework)',
      'Beatles and Stones as foundational reference points',
      'Punk\'s three-chord simplicity as deliberate anti-virtuosity statement',
      'Nirvana\'s quiet-loud dynamic as post-grunge template',
      'Radiohead as the benchmark for experimental ambition',
    ],
    lineageSignifiers: [
      'Guitar tone choice signals era and sub-genre (fuzz = 60s, high-gain = 80s metal, jangly = indie)',
      'Drum sound references (gated reverb = 80s, room mics = 70s, tight and dry = punk)',
      'Production style as lineage marker (lo-fi = indie credibility, polished = mainstream aspiration)',
      'Band format itself (trio = punk economy, five-piece = classic rock fullness)',
      'Cover song selection in live sets signals allegiance to a tradition',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Rock has historically centered male performance conventions — the guitar hero, the frontman, the physical aggression of punk — while women have consistently challenged and expanded these conventions from within, from Janis Joplin to PJ Harvey to St. Vincent.',
    vocalGenderCodes: 'Male rock vocals range from baritone growl to tenor belt to falsetto. Female rock vocals have carved space from powerful belting (Heart, Paramore) to understated delivery (Mazzy Star, Snail Mail). The "rock voice" was historically coded masculine — raspy, aggressive, loud — but this has been consistently subverted.',
    physicalityInPerformance: 'Rock performance is physical — headbanging, jumping, guitar windmills, crowd surfing. The body is an instrument of intensity. Power stance with guitar at hip level. Drum performance as athletic endurance. Stage movement signals energy and commitment.',
    genderNarratives: 'Rock lyrics have traditionally centered male perspectives — rebellion as masculine freedom, heartbreak from male viewpoint, road and escape narratives. Women in rock have introduced different narrative concerns while also inhabiting traditional rock archetypes on their own terms.',
    subversionExamples: [
      'Riot grrrl movement explicitly confronting rock\'s gender dynamics (Bikini Kill, Sleater-Kinney)',
      'Joan Jett claiming the "rock and roll" identity for women',
      'St. Vincent reimagining the guitar hero as avant-garde art performance',
      'Japanese rock scene (X Japan, Boris) challenging Western masculinity codes',
      'Non-binary and queer artists (Against Me!, G.L.O.S.S.) redefining who rock belongs to',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'A rock song at 120 BPM can feel urgently fast (punk energy, short notes, aggressive delivery) or languidly slow (half-time feel, sustained chords, spacious arrangement). The number means almost nothing without knowing the subdivision, energy, and density.',
    psychologicalTempo: 'Rock tempo perception is driven by note density and attack, not BPM. A doom metal song at 60 BPM with sustained power chords feels glacially heavy. A punk song at 180 BPM with 8th-note strumming feels breathless and urgent. Classic rock at 120 BPM with a shuffle feels relaxed and swinging.',
    weightAndMomentum: 'Weight comes from low-end, sustain, and space between attacks. Momentum comes from repetition, note density, and forward-leaning timing. A heavy riff has weight; a driving beat has momentum. The best rock songs have both.',
    urgencyScale: '1 (doom crawl) through 5 (mid-tempo groove) to 10 (thrash sprint). Most rock lives at 5-7: enough drive to feel energetic, enough groove to headbang. Punk lives at 8-10. Stoner rock at 3-4. The sweet spot for anthemic rock is 6-7.',
    comparisonToSameBPM: 'Rock at 128 BPM feels completely different from house at 128 BPM — rock has weight, attack transients, dynamic variance. At 140 BPM, rock feels fast and driving; techno at 140 feels relentless and hypnotic. The instruments and production context transform the same number into entirely different physical experiences.',
  },

  mistakeConventions: {
    overview: 'Rock celebrates imperfection — a cracked vocal, a slightly out-of-tune guitar bend, a drum fill that almost falls apart. These "mistakes" are markers of authenticity and emotional commitment. Punk elevated the mistake to an ideology: if you can play too well, you\'re not punk.',
    toleratedImperfections: [
      'Slightly out-of-tune guitar bends that add emotional urgency',
      'Vocal pitch wobble during emotionally intense passages',
      'Drums speeding up during exciting sections (natural adrenaline)',
      'Feedback and amp noise between songs',
      'Visible effort in vocal delivery — strain as evidence of commitment',
    ],
    celebratedFlaws: [
      'Punk\'s deliberate amateurism — three chords and the truth',
      'Garage rock\'s lo-fi recording quality as aesthetic choice',
      'Neil Young\'s ragged guitar solos that prioritize feeling over precision',
      'Kurt Cobain\'s cracked, breaking vocal as emotional authenticity',
      'The Stooges\' chaotic, barely-controlled live performances',
    ],
    overproductionRisks: [
      'Auto-Tuned vocals that kill emotional credibility',
      'Drum quantization that removes the human push-pull',
      'Guitar tones so processed they lose organic character',
      'Mix so clean it sounds sterile and lifeless',
      'Removing string noise and fret buzz that give acoustic guitars life',
    ],
    authenticRoughness: 'The line between "authentic rough" and "incompetent" is felt, not measured. A band that plays slightly loose but together has feel. A band that plays tight but sterile sounds like a product. Rock audiences can tell the difference instinctively — it\'s the reason live albums outsell studio albums for some bands.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['rock', 'guitar', 'drums', 'electric', 'riff', 'band', 'driving'],
    avoidKeywords: ['Auto-Tune', 'trap beats', '808', 'tropical', 'smooth', 'quiet', 'ambient only'],
    promptTemplate: '[sub-genre] rock, [tempo] BPM, [mood] mood, [guitar tone] guitar, [vocal style] vocals, [energy level] energy',
    tips: [
      'Specify sub-genre precisely: classic rock, punk, grunge, indie, post-punk',
      'Describe the guitar tone: clean, crunchy, distorted, fuzzy, jangly',
      'Mention the energy level: driving, explosive, laid-back, intense',
      'Reference a specific era or sound: 70s classic, 90s grunge, modern indie',
      'Describe the vocal style: raw, melodic, aggressive, breathy',
      'Include dynamic descriptors: quiet verse/loud chorus, building, explosive',
    ],
  },
};
