import type { GenreGuide } from './types';

export const SOUL_GUIDE: GenreGuide = {
  id: 'soul',
  name: 'Soul',
  language: 'English',

  sonicPalette: {
    overview: 'Raw, emotive, and deeply human. Soul music strips away artifice to reveal pure vocal emotion over groove-based arrangements. Horn sections, rhythm guitar, organ, and a locked-in rhythm section create the bed for some of the most powerful vocal performances in music history.',
    timbre: [
      'Powerful, expressive vocals with gospel influence',
      'Horn section (trumpet, saxophone, trombone)',
      'Hammond B3 organ with Leslie speaker',
      'Rhythm guitar (clean Telecaster or semi-hollow)',
      'Upright or electric bass with warm tone',
      'Drums with room ambience and feel',
      'Piano (acoustic, warm)',
      'Strings (lush, arranged sections)',
    ],
    texture: 'Warm, full, and organic. Live band feel with every instrument playing off each other. The horn section adds brightness and punch. The rhythm section grooves as one unit. Space is left for the vocal to breathe.',
    tonality: 'Mix of major and minor — major for celebration and joy, minor for heartache and longing. Flat keys (Eb, Ab, Bb) common due to horn sections. Warm, full-bodied frequency spectrum.',
    signatureSounds: [
      'Horn stabs and riffs',
      'Hammond organ swells',
      'Guitar scratches and rhythmic strumming',
      'Gospel-style vocal melisma',
      'Call-and-response between lead and background vocals',
      'String section sweeps',
      'Funky bass lines',
    ],
  },

  rhythmAndGroove: {
    overview: 'The groove is sacred — every musician serves the pocket. Soul rhythm is deeply felt, not mechanically precise. The interplay between bass and drums creates a groove that moves the body and the spirit.',
    bpmRange: { min: 60, max: 130, sweet: 100 },
    feel: 'Deep, grooving, and soulful. The beat should feel like a heartbeat — steady, organic, and alive. Even uptempo soul maintains a relaxed, confident groove.',
    swing: 'Moderate to heavy — soul inherits swing from jazz and gospel. The hi-hat and snare ghost notes create a swinging, human feel. Nothing is rigidly quantized.',
    syncopation: 'Essential — bass lines syncopate against the beat. Guitar scratches play on off-beats. Horn accents land between beats. The vocal floats freely over the groove.',
    grooveArchetype: 'Deep pocket groove, gospel clap-and-stomp, or funky strut',
    rhythmicSignatures: [
      'Snare on 2 and 4 with ghost notes',
      'Syncopated bass lines following guitar',
      'Gospel handclaps and tambourine',
      'Hi-hat patterns with swing feel',
      'Rhythmic guitar scratches (16th notes)',
      'Horn section rhythmic accents',
      'Organ pedal point holding the bottom',
    ],
  },

  harmonicLanguage: {
    overview: 'Gospel-rooted with jazz sophistication. Soul harmony is rich but functional — chords serve the emotion and the vocal melody. 7th chords, gospel turns, and chromatic movement create warmth and depth.',
    scales: ['Major', 'Pentatonic Major', 'Blues Scale', 'Mixolydian', 'Dorian', 'Natural Minor'],
    chordProgressions: [
      'I – IV – I – V (classic gospel-soul)',
      'I – vi – ii – V (turnaround)',
      'I – iii – IV – iv (ascending with minor IV)',
      'I – I7 – IV – iv (gospel turn)',
      'vi – V – IV – V (minor soul)',
      'I – IV – V – IV (rock-soul)',
      'ii7 – V7 – IΔ7 – vi7 (jazz-soul)',
    ],
    harmonyNotes: 'Gospel chord movement is the foundation — the IV to iv (major to minor) turn is quintessential soul. Dominant 7th chords on every degree. Chromatic bass movement. Passing chords and secondary dominants.',
    modality: 'Major for joy and celebration. Minor for pain and longing. The gospel tradition of moving between light and dark (major and minor) within a single song is a soul hallmark.',
  },

  songStructure: {
    overview: 'Emotion-driven structure — soul songs build toward emotional peaks. The arrangement serves the singer\'s journey from restraint to release. Call-and-response between lead and background vocals is structural.',
    form: 'Intro – Verse – Chorus – Verse – Chorus – Bridge – Chorus/Vamp',
    sections: ['Intro', 'Verse 1', 'Chorus', 'Verse 2', 'Chorus', 'Bridge', 'Final Chorus', 'Outro/Vamp'],
    arrangement: 'Progressive emotional build — start restrained, end powerful. Horns enter for choruses. Strings swell for emotional peaks. The final chorus/vamp allows the singer to fully unleash.',
    introOutro: 'Intros: horn riff, guitar lick, or organ setting the mood. Outros: extended vamp with vocal improvisation, horn solos, and band interplay. The outro is often the emotional climax.',
    barLengths: 'Verses: 8-12 bars. Chorus: 8 bars. Bridge: 4-8 bars. Outro/vamp: extended (8-16+ bars). Total: 3-5 minutes.',
    hookPlacement: 'Chorus melody is the hook — memorable, singable, emotionally powerful. Horn riffs serve as instrumental hooks. Title phrase placed prominently in chorus.',
  },

  vocalDelivery: {
    overview: 'The voice is everything in soul music. Gospel-trained power, emotional authenticity, and dynamic control define the soul vocal. The singer channels genuine emotion — joy, pain, ecstasy, anguish — through a technically commanding instrument.',
    phrasing: 'Emotionally responsive — phrasing stretches and contracts with feeling. Behind-the-beat phrasing for laid-back grooves. Pushing ahead for urgency. Each phrase is delivered as if the singer\'s life depends on it.',
    affect: 'Raw emotional truth — soul singing is about feeling, not showing off. Joy, heartbreak, devotion, desperation. The listener must believe the singer means every word.',
    techniques: [
      'Gospel-rooted belt singing',
      'Melismatic runs and vocal ornaments',
      'Falsetto for emotional peaks',
      'Scream-singing (Sam Cooke, James Brown)',
      'Vibrato control — wide for emotion, tight for control',
      'Call-and-response with background vocals',
      'Dynamic range — whisper to scream',
      'Vocal grit and rasp from emotional intensity',
    ],
    adlibStyle: 'Gospel-influenced — "Oh Lord!", "Have mercy!", "Yeah!", "Come on!". Vocal improvisations in the vamp. Spoken asides and testimonials. Background vocal responses and affirmations.',
    harmony: 'Rich background harmonies — gospel choir influence. Call-and-response between lead and backgrounds. Unison power moments. Harmony stacks on key emotional phrases.',
    grit: 'Natural and earned — the grit comes from emotional intensity, not affectation. A catch in the voice, a crack on a high note, a rasp from screaming — all authentic expressions of feeling.',
  },

  lyricalConventions: {
    overview: 'Soul lyrics speak directly from the heart — love, pain, celebration, and spiritual transcendence. The best soul lyrics are simple enough to be universal but specific enough to be genuine.',
    themes: [
      'Romantic love and devotion',
      'Heartbreak and loss',
      'Joy and celebration',
      'Spiritual transcendence',
      'Social justice and civil rights',
      'Empowerment and self-worth',
      'Desire and longing',
      'Community and togetherness',
    ],
    perspective: 'First person emotional confession. Direct address to a lover. Gospel-style testimony. Community-inclusive "we."',
    figurativeLanguage: 'Earthy, sensory metaphors. Fire and water for passion. Light and darkness for emotional states. Natural imagery. Gospel metaphors (salvation, redemption, freedom).',
    vocabulary: 'Conversational, emotionally articulate, rooted in Black American vernacular. Church and gospel language bleeds through. Simple words for complex emotions.',
    storytellingApproach: 'Emotional testimony — the singer confesses, celebrates, or mourns. The story is the emotion itself. Specific details ground abstract feelings.',
    cliches: [
      'My heart/my soul',
      'Can\'t live without you',
      'Set me free',
      'Oh my Lord/heaven',
      'Down on my knees',
      'Give me the strength',
    ],
  },

  productionFingerprint: {
    overview: 'Live, warm, and human. Soul production captures musicians playing together in a room. The sound is warm (analog tape, tube amps) and present. Modern neo-soul blends this vintage warmth with contemporary production.',
    mixAesthetic: 'Vocal-dominant — the voice sits above everything. Warm, round low end from bass and kick. Horns bright and punchy. Room ambience on drums. Strings lush but not overwhelming.',
    era: 'Classic soul (60s-70s) recording techniques remain the gold standard. Modern soul/neo-soul adds electronic elements while maintaining organic warmth.',
    signalChain: 'Vocals: ribbon or condenser mic → tube preamp → gentle compression. Instruments: live recording, minimal isolation. Drums: room mics + close mics. Horns: ribbon mics, natural blending. Tape saturation on the master.',
    modernTrends: 'Neo-soul revival. Vintage gear fetishism. Lo-fi soul aesthetics. Hip-hop sampling culture honoring source material. Live-to-tape recording sessions.',
  },

  instrumentation: {
    coreInstruments: [
      'Vocals (lead and background choir)',
      'Horn section (trumpet, tenor sax, trombone)',
      'Hammond B3 organ',
      'Electric guitar (rhythm, clean tone)',
      'Bass guitar or upright bass',
      'Drums',
      'Piano',
      'Strings (violin, viola, cello)',
    ],
    signatureSounds: [
      'Horn section stabs',
      'Hammond organ with Leslie rotation',
      'Guitar scratches (rhythmic strumming)',
      'Gospel piano runs',
      'Walking bass lines',
      'String section arrangements',
      'Tambourine and handclaps',
    ],
    layering: 'Full but clear — each instrument has its role and space. Rhythm section (bass, drums, guitar, keys) provides the foundation. Horns and strings add color. Vocals sit on top.',
    avoidInstruments: [
      'Heavy distortion',
      'Electronic drums (for vintage soul)',
      'Synthesizers (for classic soul)',
      'Processed/Auto-Tuned vocals',
      'Modern EDM elements',
    ],
  },

  culturalContext: {
    overview: 'Soul music is the sound of Black American experience — born from the collision of sacred gospel and secular R&B, it became a vehicle for civil rights, cultural pride, and emotional truth.',
    origin: 'Mid-1950s America — gospel singers like Ray Charles and Sam Cooke brought the emotional intensity of church music to secular subjects. Motown and Stax became the institutional homes.',
    identity: 'Black cultural expression at its most emotionally raw. Soul represents authenticity, feeling, and community. The church and the street meet in soul music.',
    community: 'Black church tradition, juke joints, and Chitlin\' Circuit. Modern soul communities exist online and in neo-soul live music scenes. Deep reverence for the music\'s history.',
    socialFunction: 'Emotional catharsis, spiritual expression, social commentary, and community bonding. Soul music provided the soundtrack to the Civil Rights Movement and continues to speak to Black experience.',
    authenticityMarkers: [
      'Vocal power and emotional honesty',
      'Connection to gospel and church tradition',
      'Live musicianship and ensemble playing',
      'Emotional vulnerability',
      'Cultural and historical awareness',
    ],
  },

  historicalLineage: {
    overview: 'From gospel church to Motown to neo-soul, soul music represents the continuous tradition of Black American emotional expression through music.',
    roots: ['Gospel', 'Blues', 'R&B', 'Jazz', 'Doo-Wop'],
    evolution: 'Gospel-secular fusion (Ray Charles, Sam Cooke, 50s) → Motown pop-soul (60s) → Southern soul/Stax (60s-70s) → Philly soul (70s) → Funk-soul (70s) → Quiet storm (80s) → Neo-soul revival (late 90s-2000s) → Modern soul (2010s-present).',
    keyEras: [
      '1954-1960: Gospel-to-secular crossover (Ray Charles, Sam Cooke)',
      '1960-1968: Motown era (Supremes, Temptations, Marvin Gaye)',
      '1965-1975: Southern soul/Stax (Otis Redding, Al Green)',
      '1971-1979: Philly soul and funk-soul fusion',
      '1997-2005: Neo-soul revival (D\'Angelo, Erykah Badu)',
      '2010-present: Modern soul and retro-soul revival',
    ],
    influencedBy: ['Gospel', 'Blues', 'Jazz', 'R&B', 'Doo-Wop'],
    influenced: ['Funk', 'R&B', 'Hip-Hop (sampling)', 'Pop', 'Rock', 'Neo-Soul'],
  },

  subGenres: [
    {
      name: 'Classic Soul',
      description: 'The original form — gospel-powered vocals over horn-driven arrangements. The sound of Motown, Stax, and Atlantic Records.',
      distinguishingFeatures: ['Gospel-rooted vocal power', 'Horn section arrangements', 'Live band groove', 'Emotional directness', 'Vintage analog sound'],
      bpmRange: { min: 80, max: 130 },
      keyArtists: ['Aretha Franklin', 'Otis Redding', 'Sam Cooke', 'Stevie Wonder', 'Al Green'],
      productionNotes: 'Live band recording. Horn arrangements. Warm, analog sound. Vocal-forward mix. Natural room ambience. Minimal processing.',
      lyricNotes: 'Love, heartbreak, social justice, celebration. Direct emotional expression. Gospel-influenced testimony.',
      sunoPromptKeywords: ['classic soul', '60s soul', 'Motown', 'Stax', 'vintage soul', 'horn section', 'retro soul'],
    },
    {
      name: 'Northern Soul',
      description: 'Uptempo, dance-oriented soul music popular in Northern England. Fast tempos, driving beats, and passionate vocals designed for all-night dancing.',
      distinguishingFeatures: ['Fast tempo', 'Dance-oriented energy', 'Driving drums', 'Passionate vocals', 'Obscure/rare records valued'],
      bpmRange: { min: 115, max: 140 },
      keyArtists: ['Frank Wilson', 'Gloria Jones', 'Dobie Gray', 'Tobi Legend', 'Edwin Starr'],
      productionNotes: 'Fast, driving drums. Prominent bass. Energetic horn arrangements. Uptempo groove. Clean, punchy production.',
      lyricNotes: 'Love, dancing, desire. Uptempo and energetic. Emotional but celebratory.',
      sunoPromptKeywords: ['Northern soul', 'uptempo soul', 'dance soul', 'driving', 'energetic', 'rare soul', 'floor filler'],
    },
    {
      name: 'Southern Soul',
      description: 'Raw, earthy soul from Memphis, Muscle Shoals, and the American South. Grittier and more blues-influenced than Motown, with emotional rawness.',
      distinguishingFeatures: ['Blues-influenced rawness', 'Horn-driven arrangements', 'Earthy, gritty production', 'Raw vocal emotion', 'Memphis/Muscle Shoals sound'],
      bpmRange: { min: 70, max: 110 },
      keyArtists: ['Otis Redding', 'Wilson Pickett', 'Sam & Dave', 'Percy Sledge', 'Johnnie Taylor'],
      productionNotes: 'Raw, live-sounding recording. Prominent horns. Earthy guitar tone. Organic drums. Less polished than Motown — grittier and more authentic.',
      lyricNotes: 'Heartbreak, desire, pain. Raw emotional delivery. Blues storytelling influence. Southern imagery and vernacular.',
      sunoPromptKeywords: ['Southern soul', 'Memphis soul', 'Stax sound', 'raw soul', 'gritty', 'blues soul', 'deep soul'],
    },
    {
      name: 'Philly Soul',
      description: 'Lush, orchestral soul from Philadelphia. Sweeping strings, sophisticated arrangements, and polished production — the bridge between soul and disco.',
      distinguishingFeatures: ['Lush string arrangements', 'Sophisticated orchestration', 'Polished production', 'Romantic themes', 'Dance-oriented grooves'],
      bpmRange: { min: 100, max: 125 },
      keyArtists: ['The O\'Jays', 'Harold Melvin & the Blue Notes', 'The Stylistics', 'Teddy Pendergrass'],
      productionNotes: 'Full string section. Polished, sophisticated production. Prominent bass lines. Lush arrangements. Clean, wide stereo mix.',
      lyricNotes: 'Romantic love, social commentary. Sophisticated and mature. Dance-floor friendly.',
      sunoPromptKeywords: ['Philly soul', 'Philadelphia soul', 'orchestral soul', 'lush', 'strings', 'sophisticated', 'disco soul'],
    },
    {
      name: 'Psychedelic Soul',
      description: 'Soul infused with psychedelic rock influences — extended jams, studio experimentation, and mind-expanding production.',
      distinguishingFeatures: ['Psychedelic production effects', 'Extended compositions', 'Experimental arrangements', 'Funk-influenced grooves', 'Studio experimentation'],
      bpmRange: { min: 80, max: 120 },
      keyArtists: ['Sly & the Family Stone', 'Stevie Wonder (Innervisions era)', 'Funkadelic', 'The Temptations (psychedelic era)'],
      productionNotes: 'Studio effects — reverb, phasing, wah-wah. Extended arrangements. Funk grooves with psychedelic textures. Experimental mixing techniques.',
      lyricNotes: 'Consciousness, social commentary, love, spirituality. Abstract and poetic. Mind-expanding themes.',
      sunoPromptKeywords: ['psychedelic soul', 'funky soul', 'experimental soul', 'trippy', 'groovy', '70s soul', 'space soul'],
    },
    {
      name: 'Blue-Eyed Soul',
      description: 'Soul music performed by white artists who authentically embrace the soul tradition. The sound is genuine soul with diverse cultural perspective.',
      distinguishingFeatures: ['Soul authenticity from non-Black artists', 'Strong vocal delivery', 'Respect for soul traditions', 'Cross-cultural appeal', 'Often pop-accessible'],
      bpmRange: { min: 70, max: 120 },
      keyArtists: ['Hall & Oates', 'Michael McDonald', 'Amy Winehouse', 'Adele', 'Sam Smith'],
      productionNotes: 'Authentic soul production values. Live instrumentation. Strong vocal presence. Can lean toward pop accessibility while maintaining soul roots.',
      lyricNotes: 'Universal emotional themes. Love, heartbreak, longing. Accessible but emotionally honest.',
      sunoPromptKeywords: ['blue-eyed soul', 'white soul', 'soul pop', 'retro soul', 'vocal-driven', 'emotional'],
    },
    {
      name: 'Neo-Soul',
      description: 'Late 90s/2000s soul revival blending classic soul warmth with hip-hop, jazz, and electronic influences. Organic, conscious, and artistically ambitious.',
      distinguishingFeatures: ['Live instrumentation with hip-hop influence', 'Jazz harmonies', 'Afrocentric consciousness', 'Organic production', 'Artist-driven (not label-manufactured)'],
      bpmRange: { min: 65, max: 100 },
      keyArtists: ['D\'Angelo', 'Erykah Badu', 'Lauryn Hill', 'Jill Scott', 'Maxwell'],
      productionNotes: 'Live instruments — Rhodes, bass, drums. Hip-hop influenced grooves. Jazz harmonies. Warm, analog production. Minimal electronic processing.',
      lyricNotes: 'Consciousness, spirituality, love, identity. Afrocentric themes. Poetic and introspective. Natural beauty and self-love.',
      sunoPromptKeywords: ['neo-soul', 'new soul', 'organic soul', 'jazzy soul', 'conscious', 'warm', 'live instruments'],
    },
    {
      name: 'Nu-Soul',
      description: 'Contemporary reinterpretation of soul combining electronic production with soulful vocals. More experimental than neo-soul, embracing technology while honoring tradition.',
      distinguishingFeatures: ['Electronic production with soul vocals', 'Experimental sound design', 'Contemporary production techniques', 'Genre-blending', 'Digital meets analog'],
      bpmRange: { min: 60, max: 110 },
      keyArtists: ['Solange', 'Blood Orange', 'Sampha', 'Jamila Woods', 'Moses Sumney'],
      productionNotes: 'Electronic textures with soulful vocals. Experimental production. Ambient and atmospheric elements. Genre-blending approach.',
      lyricNotes: 'Identity, race, gender, belonging. Introspective and political. Art-school sensibility with soul heart.',
      sunoPromptKeywords: ['nu-soul', 'modern soul', 'experimental soul', 'art soul', 'electronic soul', 'contemporary'],
    },
    {
      name: 'Deep Soul',
      description: 'The most emotionally intense form of soul — slow, anguished, and devastatingly honest. Deep soul ballads are confessional outpourings of raw emotion.',
      distinguishingFeatures: ['Extreme emotional intensity', 'Slow tempo', 'Minimal arrangements', 'Devastating vocal performances', 'Blues-influenced'],
      bpmRange: { min: 55, max: 80 },
      keyArtists: ['Percy Sledge', 'O.V. Wright', 'James Carr', 'Otis Clay', 'Bobby Bland'],
      productionNotes: 'Minimal, sparse arrangements. Focus entirely on the vocal. Gentle accompaniment — organ, guitar, bass. Let the emotion breathe. Don\'t over-produce.',
      lyricNotes: 'Heartbreak, desperation, longing, loss. Raw emotional honesty. Confessional and devastating. Less is more.',
      sunoPromptKeywords: ['deep soul', 'soul ballad', 'slow soul', 'emotional', 'anguished', 'heartbreak', 'raw'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'Soul audiences value vocal ability, emotional authenticity, and musical heritage above all. The audience spans generations, united by appreciation for genuine emotional expression.',
    fanExpectations: [
      'Exceptional vocal ability',
      'Emotional authenticity',
      'Live band musicianship',
      'Connection to soul/gospel tradition',
      'Genuine feeling over technical showmanship',
      'Cultural awareness and respect',
    ],
    gatekeeping: 'Moderate — respect for the tradition is expected. Debates about authenticity and cultural ownership. Vocal ability is the primary qualifier. Knowledge of soul history valued.',
    livePerformance: 'Emotionally intense — the live show should be a spiritual experience. Full band with horns if possible. Vocal improvisation and emotional peaks. Intimate venues preferred for deep connection.',
    fashionAndAesthetic: 'Elegant and stylish — soul artists are style icons. Sharp suits, natural hair, Afrocentric fashion. Modern soul embraces diverse aesthetics. Classic sophistication valued.',
    crossoverPotential: 'High — soul vocal techniques and grooves permeate pop, R&B, hip-hop, and global music. Soul sampling is foundational to hip-hop. The emotional language is universal.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'Soul micro-timing is the sound of musicians breathing together. The rhythm section locks into a deep, communal pocket where every player\'s timing relationships define the groove. Unlike programmed music, soul timing is negotiated in real time — the bassist pushes, the drummer pulls, and the pocket emerges from that tension.',
    quantizationDeviation: 'Soul music is pre-quantization — recorded live with musicians responding to each other in real time. Ghost notes on the snare fall where the drummer\'s body puts them. Bass notes anticipate chord changes by feel, not by click track. The "Stax sound" is partly the result of the house band\'s collective timing — slightly behind the beat, creating weight.',
    aheadBehindBeat: 'The soul rhythm section generally sits behind the beat, creating a heavy, grounded feel. The lead vocalist floats — sometimes ahead for urgency ("I Got You" by James Brown) and sometimes behind for emotion (Al Green\'s languorous phrasing). Horn accents land slightly ahead of the beat for punch, creating push-pull tension.',
    humanizationMarkers: [
      'Drummer\'s hi-hat hand slightly rushing on 16th notes',
      'Bass player landing a split-second after the kick drum',
      'Horn section entrance with slight stagger between players',
      'Guitar scratches varying in attack intensity phrase to phrase',
      'Piano comping with natural velocity variation from chord to chord',
    ],
    genreSpecificFeel: 'The soul "pocket" is the deepest in popular music — it\'s what hip-hop producers tried to capture by sampling soul records. The feel comes from musicians who played together daily: Booker T. & the M.G.\'s, the Funk Brothers, the MFSB rhythm section. Their micro-timing relationships were developed over thousands of sessions and cannot be programmed.',
  },

  silenceAndSpace: {
    overview: 'Soul music uses silence for dramatic effect — stop-time breaks where the band drops out for a vocal cry, the moment before a horn section entrance, the breath before a scream. Space in soul is theatrical, creating anticipation for emotional peaks.',
    negativeSpaceRole: 'Space in soul serves the vocal. The arrangement clears a path for the singer — instruments drop away during the most emotionally intense moments, leaving the voice naked and exposed. Al Green\'s records use vast empty space around the vocal, making every word feel enormous. Otis Redding\'s "Try a Little Tenderness" uses the quiet section to set up the explosive finale.',
    breathingPatterns: 'Soul arrangements breathe in call-and-response cycles: the horn section plays a phrase, then rests while the singer responds. Verses are sparser, choruses fill out. The arrangement progressively adds instruments through the song, with the final section at maximum density. Extended outros thin back down for vocal improvisation.',
    dynamicContrast: 'Extreme and theatrical. Soul music moves from whispered confession to full-band ecstasy within a single song. The dynamic arc mirrors the gospel tradition of building from prayer to praise. Stop-time breaks (full band to silence) are signature soul dynamics, creating maximum contrast.',
    whatIsDeliberatelyAbsent: [
      'Continuous rhythmic activity (stop-time breaks are structural)',
      'Electronic processing on vocals (rawness is the point)',
      'Busy arrangements during vocal peaks (space for the singer)',
      'Consistent volume level (dynamics serve the emotional arc)',
      'Production trickery (the recording captures, not creates, the performance)',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response is structural to soul — inherited directly from the Black church, it defines the relationship between lead singer and background vocalists, between vocalist and instrumentalists, and between performer and audience. This is not a decorative element; it is the genre\'s conversational architecture.',
    vocalInstrumentalDialogue: 'The horn section "talks" to the singer — a vocal phrase ends, the horns respond with a riff or stab. The guitar answers the voice with a lick. The organ sustains underneath as the congregation\'s communal hum. Otis Redding\'s "sitting on the dock of the bay" is answered by Steve Cropper\'s guitar — they are having a conversation.',
    sectionInternal: 'Lead vocalist states, background singers affirm: "Yes Lord!" / "Tell it!" / "Sing!" The backgrounds are the congregation, the lead is the preacher. This dynamic structures entire songs — the lead pushes further emotionally, the backgrounds urge them on. In the vamp, roles become fluid, with backgrounds taking melodic turns.',
    audienceParticipation: 'Soul audiences participate vocally — shouting encouragement, singing choruses back, clapping on 2 and 4. The live soul show is a church service: the performer testifies, the audience responds. James Brown would command his audience ("Can I get a witness?") and the response was expected and genuine.',
    patterns: [
      'Lead sings line → backgrounds repeat or harmonize response',
      'Vocal phrase → horn section answer',
      'Singer\'s emotional peak → audience shout of affirmation',
      'Verse builds tension → chorus releases with collective singing',
      'Guitar lick → vocal imitation of the lick',
      'Band stop-time → solo vocal cry in the silence',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Soul music\'s regional identity is defined by two poles: the polished, pop-accessible sound of Northern cities (Detroit, Philadelphia, Chicago) and the raw, gospel-drenched sound of the South (Memphis, Muscle Shoals). These regional distinctions are audible in vocal delivery, production style, and emotional temperature.',
    phoneticMarkers: [
      'Detroit/Motown: clear diction, pop-accessible enunciation, measured vibrato',
      'Memphis/Stax: raw Southern vowels, gospel growl, unpolished intensity',
      'Philadelphia: warm, rounded delivery, sophisticated phrasing',
      'Chicago: soul-blues hybrid vowels, Curtis Mayfield\'s high falsetto',
      'Muscle Shoals: earthy Southern inflection, gritty consonants',
    ],
    accentInfluence: 'Southern soul voices carry the church — vowels are open and round, consonants are softened, and the delivery has a preacher\'s rhythmic cadence. Northern soul (Motown) polished the accent for crossover appeal — Berry Gordy trained artists in elocution. This North-South divide mirrors the Great Migration\'s cultural tension between Southern roots and Northern aspiration.',
    dialectVocabulary: [
      '"Testify" (declare emotional/spiritual truth)',
      '"Have mercy" (exclamation of overwhelm)',
      '"Shout" (ecstatic physical response to music, church origin)',
      '"In the pocket" (rhythmically locked-in, musicians\' term)',
      '"Take it to church" (escalate emotional intensity)',
    ],
    regionWithinCulture: 'The Motown vs. Stax divide maps onto broader cultural dynamics: Motown sought white crossover acceptance with polish and charm; Stax embraced raw Black expression without apology. Both are authentic; they represent different strategies for Black cultural expression in America. This tension — assimilation vs. assertion — runs through all of soul music.',
  },

  performancePractice: {
    overview: 'Soul performance is the live moment — the studio recording is a document, but the live show is the art form. Soul performers are expected to "leave it all on the stage," channeling genuine emotion that transforms the concert into a communal cathartic event. The best soul performances are unrepeatable.',
    improvisationConventions: 'Vocal improvisation in the vamp/outro is mandatory — this is where the singer demonstrates mastery and emotional depth. Instrumentalists improvise fills and solos (guitar, organ, horn solos). The band may extend or shorten sections in real time based on audience energy. James Brown\'s band famously followed his hand signals for tempo and section changes.',
    crowdInteraction: 'The performer is a preacher and the audience is the congregation. Soul artists testify — speak directly to the audience about the emotion behind the song, then deliver it with everything they have. Call-and-response with the crowd is expected. The artist reads the room and adjusts intensity accordingly.',
    stagePresence: 'Physical and theatrical. James Brown\'s capes and splits. Otis Redding\'s raw intensity. Aretha Franklin\'s regal composure. The body expresses what the voice is singing — sweat, tears, and physical exhaustion are marks of a great performance. Standing still and singing is acceptable if the vocal alone is overwhelming.',
    livVsRecordedDifferences: 'Live soul often surpasses the studio version. Extended vamps, vocal ad-libs, and spontaneous emotional moments make each performance unique. The Otis Redding "Live in Europe" recordings are considered superior to his studio work. Band interplay intensifies in live settings — musicians push each other further.',
    whatMakesAGoodShow: 'Total emotional commitment. The singer must convince the audience that every word is personally felt in that moment. Technical vocal ability demonstrated through improvisation. Band tightness that allows for spontaneous changes. The audience should leave feeling emotionally transformed — they came to a concert and experienced a church service.',
  },

  socioeconomicSubtext: {
    overview: 'Soul music emerged directly from the Black American experience of the mid-20th century — the Civil Rights Movement, the Great Migration, urban life, and the tension between aspiration and oppression. The music carries this history whether the lyrics address it explicitly or not.',
    materialConditions: 'Soul artists came from working-class and impoverished Black communities — church choirs, juke joints, and the Chitlin\' Circuit. Motown represented the possibility of Black economic success within the system (Berry Gordy\'s assembly line). Stax represented Black creative ownership (until the label\'s financial collapse). The music\'s emotional intensity reflects lives lived under economic and racial pressure.',
    classIdentity: 'Soul bridges Black working-class experience and middle-class aspiration. Motown\'s polish (charm school, choreography, matching suits) represented upward mobility and respectability. Southern soul\'s rawness represented authenticity and refusal to code-switch. Neo-soul revived bohemian, Afrocentric identity outside the class hierarchy.',
    politicalUndercurrent: 'Soul was the soundtrack of the Civil Rights Movement. Sam Cooke\'s "A Change Is Gonna Come," Curtis Mayfield\'s "People Get Ready," Marvin Gaye\'s "What\'s Going On" — these were anthems of liberation. Even love songs carried political weight: Black joy, desire, and tenderness in a society that denied Black humanity.',
    implicitReferences: [
      'Motown\'s visual polish as racial uplift strategy',
      'Southern soul\'s rawness as refusal to assimilate',
      'Horn section arrangements echoing parade and marching band traditions',
      'Gospel-secular crossover reflecting migration from church to stage',
      'Dancing as embodied freedom in a constrained society',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Soul music is the most sampled genre in history — its grooves, vocal snippets, and horn riffs form the raw material of hip-hop, electronic music, and pop. Within soul itself, artists constantly reference the gospel tradition they came from and the blues that preceded them.',
    canonKnowledge: 'Soul\'s canon is deeply felt: Ray Charles\'s gospel-secular fusion, Sam Cooke\'s vocal perfection, James Brown\'s rhythmic revolution, Aretha\'s vocal power, Stevie\'s harmonic genius, Marvin\'s conceptual ambition. Every soul artist is measured against this lineage. Knowledge of these artists is assumed, not optional.',
    samplingTradition: 'Soul records are hip-hop\'s primary source material. James Brown is the most sampled artist in history. Kanye West built "My Beautiful Dark Twisted Fantasy" on soul samples. The Roots bridge live soul performance and hip-hop. This sampling relationship has made soul grooves immortal — younger listeners encounter them through hip-hop first.',
    quotationPractice: 'Soul artists quote gospel — a vocal run from a church recording, a chord change from a hymn, a call-and-response pattern from a Sunday service. Modern soul artists quote classic soul: Leon Bridges channels Sam Cooke, Anderson .Paak channels Marvin Gaye. The quotation is an act of reverence and continuity.',
    expectedReferences: [
      'James Brown\'s rhythmic innovations as foundational vocabulary',
      'Aretha Franklin\'s vocal approach as the female soul benchmark',
      'Marvin Gaye\'s "What\'s Going On" as conceptual soul template',
      'Stevie Wonder\'s "Innervisions" era as harmonic peak',
      'Al Green\'s vocal intimacy as emotional reference point',
    ],
    lineageSignifiers: [
      'Gospel vocal techniques signaling church roots',
      'Horn arrangements referencing Stax or Motown house bands',
      'Live band performances demonstrating musical lineage',
      'Cover versions of classic soul songs as credential markers',
      'Analog recording techniques honoring vintage production',
      'Afrocentric visual aesthetics connecting to 70s soul identity',
    ],
  },

  genderAndBodyConventions: {
    overview: 'Soul music encodes distinct masculine and feminine performance traditions rooted in the Black church, where gender roles in worship (lead preacher vs. choir, deacon vs. mother of the church) translated into secular performance conventions.',
    vocalGenderCodes: 'Male soul singers span from bass-baritone authority (Barry White, Isaac Hayes) to high tenor vulnerability (Smokey Robinson, Curtis Mayfield). Falsetto in male soul signals emotional transcendence, not weakness. Female soul singers are expected to demonstrate gospel-level power (Aretha, Mavis Staples) — the "diva" tradition demands technical dominance.',
    physicalityInPerformance: 'Male soul performance ranges from James Brown\'s athletic showmanship to Al Green\'s intimate stillness. The male body expresses emotional effort — sweat and physical intensity signal genuineness. Female soul performance centers vocal command — Aretha could transform a room while seated at a piano. Physical expression is about channeling emotion, not choreography.',
    genderNarratives: 'Traditional soul divides along gender lines: male artists sing about desire, devotion, and heartbreak from a pursuing perspective; female artists sing about love, empowerment, and demanding respect. Aretha\'s "Respect" reclaimed a male-authored song as a feminist anthem — a founding moment of Black feminist expression in popular music.',
    subversionExamples: [
      'Sylvester\'s falsetto and gender-fluid performance in disco-soul',
      'Curtis Mayfield\'s high voice challenging masculine vocal norms',
      'Mavis Staples\'s deep, powerful voice occupying traditionally masculine sonic space',
      'Prince inheriting soul tradition while dissolving gender categories entirely',
      'Meshell Ndegeocello\'s androgynous bass-playing soul musician persona',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'Soul tempo is deeply connected to the body — the groove should match natural physical rhythms like walking, swaying, or clapping. The actual BPM matters less than whether the body responds correctly. A soul groove at 100 BPM should feel effortless, like breathing.',
    psychologicalTempo: 'Slow soul at 65 BPM feels heavy and deliberate — each beat has weight. Mid-tempo soul at 95-105 BPM feels like walking with purpose — the sweet spot for head-nodding and shoulder movement. Uptempo Northern soul at 130 BPM feels like joyful dancing. The psychological tempo is always body-mapped.',
    weightAndMomentum: 'Soul\'s weight comes from the rhythm section\'s collective mass — bass, drums, guitar, and organ all contributing to a gravitational pull. Motown\'s driving bass lines (James Jamerson) create forward momentum even at moderate tempos. Stax\'s heavier, sparser grooves create weight through density rather than speed.',
    urgencyScale: '1-10 urgency: Deep soul ballad at 55 BPM = 2 (anguished), Al Green slow groove at 75 BPM = 3 (sensual), Motown mid-tempo at 100 BPM = 5 (grooving), James Brown funk-soul at 110 BPM = 7 (driving), Northern soul at 130 BPM = 9 (ecstatic), Sam & Dave at 120 BPM = 8 (explosive).',
    comparisonToSameBPM: 'Soul at 100 BPM feels grounded and earthy — the groove is in the body, not the head. Pop at 100 BPM feels lighter and more cerebral. Rock at 100 BPM feels more aggressive and forward-leaning. Soul\'s behind-the-beat placement makes the same tempo feel heavier and more deliberate than any other genre.',
  },

  mistakeConventions: {
    overview: 'Soul music celebrates imperfection as evidence of genuine emotion. A cracked note, a catch in the voice, a slightly ragged horn entrance — these are not failures but proof that the performance is real. The entire genre was built on the premise that raw feeling matters more than technical perfection.',
    toleratedImperfections: [
      'Slight pitch variations on sustained vocal notes',
      'Horn section blend that reveals individual players',
      'Drum fills that sit slightly off-grid',
      'Bass notes that arrive fractionally early or late',
      'Vocal fatigue audible in later takes or live recordings',
    ],
    celebratedFlaws: [
      'Otis Redding\'s vocal cracks as peak emotional expression',
      'Al Green\'s voice breaking on high notes — the sound of a man overwhelmed',
      'James Brown\'s screams — technically "wrong" but emotionally perfect',
      'Aretha\'s piano playing (technically limited but soulfully authoritative)',
      'Live recordings with bleed, room noise, and audience sounds',
    ],
    overproductionRisks: [
      'Pitch-correcting vocal emotion out of the performance',
      'Quantizing live drums until the groove becomes mechanical',
      'Over-arranging until there\'s no space for vocal spontaneity',
      'Multi-tracking vocals until the lead sounds like a choir (losing intimacy)',
      'Mixing away room sound and live ambience',
    ],
    authenticRoughness: 'Soul\'s authenticity IS its roughness. The genre exists precisely because gospel-trained singers brought raw church intensity to secular music, unpolished and unapologetic. Otis Redding didn\'t need pitch correction; his emotional truth was the tuning. The best soul recordings sound like they could fall apart at any moment but never quite do — that tension is the art.',
  },

  sunoPromptGuide: {
    essentialKeywords: ['soul', 'soulful', 'gospel', 'horn section', 'groovy', 'emotional', 'vintage'],
    avoidKeywords: ['electronic', 'auto-tune', 'dubstep', 'metal', 'harsh', 'distorted', 'industrial'],
    promptTemplate: '[sub-genre] soul, [tempo] BPM, [mood] mood, [vocal style] vocals, [instruments], [era]',
    tips: [
      'Specify the sub-genre: classic soul, neo-soul, Southern soul, etc.',
      'Describe the vocal quality: powerful, breathy, raw, gospel-tinged',
      'Mention key instruments: horn section, organ, Rhodes, strings',
      'Reference the era: 60s Motown, 70s Philly, 90s neo-soul',
      'Describe the emotional intensity: celebratory, heartbroken, spiritual',
      'Use "warm," "organic," and "live" as key production descriptors',
    ],
  },
};
