import type { GenreGuide } from './types';

export const SWAHILI_GUIDE: GenreGuide = {
  id: 'swahili',
  name: 'Swahili & East African Music',
  language: 'Swahili',

  sonicPalette: {
    overview: 'Warm, melodic, and rhythmically rich — anchored by the interplay of Indian Ocean coastal tradition and modern urban production. Bongo Flava blends hip-hop, R&B, reggae, and taarab melodicism into a sound that is cosmopolitan yet distinctly East African.',
    timbre: [
      'warm melodic synth leads with tropical character',
      'taarab-influenced violin or violin-synth patches',
      'oud or oud-like plucked string timbres',
      'djembe, dumbek, and frame drum (tari) textures',
      'sub-bass with round, full-bodied quality',
      'clean electric guitar with chorus or light reverb',
    ],
    texture: 'Layered but not dense — rhythm tracks are tight and present, melodic elements breathe. Taarab adds lush string tapestry; singeli contrasts with chaotic hyperactive drums.',
    tonality: 'Predominantly minor and maqam-adjacent from coastal taarab inheritance. Pentatonic vocal runs common. Arabic maqam scales (Hijaz, Rast) appear in taarab-influenced tracks.',
    signatureSounds: [
      'taarab violin ornaments and melismatic phrases',
      'oud or oud-synth riffs as melodic hooks',
      'singeli ultra-fast chaotic drum machine snare rolls',
      'benga clean interlocking melodic guitar lines',
      'call-and-response vocal patterns in Swahili',
    ],
  },

  rhythmAndGroove: {
    overview: 'Diverse internal rhythm landscape. Bongo Flava operates at mid-tempo dancehall-adjacent groove; taarab is slower and swaying; singeli is extremely fast and frenetic; benga is bright and driving.',
    bpmRange: { min: 70, max: 200, sweet: 95 },
    feel: 'Relaxed and swaying at mid-tempo (Bongo Flava), punchy and syncopated in benga, frenetic in singeli. A slight forward lean on beats two and four creates gentle propulsion.',
    swing: 'Moderate swing in benga and taarab; straight grid with syncopated hi-hats in Bongo Flava; deliberately mechanical 16th-note grid in singeli.',
    syncopation: 'High overall. Benga guitar lines displace the perceived downbeat. Taarab vocal melody phrases land ornamented on unexpected beats.',
    grooveArchetype: 'Benga two-guitar interlock — two clean electric guitar parts weaving around each other while bass anchors the downbeat. In Bongo Flava this becomes programmed groove mimicking the interlock feel.',
    rhythmicSignatures: [
      'benga guitar interlock: two-part melodic weave',
      'taarab chakacha: swaying 6/8-adjacent coastal dance feel',
      'singeli drum machine: 180-200 BPM rapid-fire patterns',
      'Bongo Flava dancehall one-drop: kick on beat 3',
      'kidumbak 3+3+2 Zanzibar percussion pattern',
    ],
  },

  harmonicLanguage: {
    overview: 'Shaped by Arabic maqam (via taarab), Western diatonic harmony (via colonial-era music), and indigenous pentatonic frameworks (via benga). The result avoids strong functional cadences in favour of sustained modal vamps.',
    scales: [
      'natural minor (Aeolian)',
      'Dorian mode',
      'maqam Hijaz',
      'maqam Rast',
      'pentatonic minor and major',
    ],
    chordProgressions: [
      'i – bVI – bVII – i (minor loop, ubiquitous in Bongo Flava)',
      'i – iv – i – V (minor vamp with dominant pull)',
      'I – IV – I – V (major loop for celebratory songs)',
      'maqam Hijaz vamp: i – bII (coastal Swahili heritage)',
    ],
    harmonyNotes: 'The same chord loop repeats throughout; variation comes from melodic ornament and arrangement density rather than harmonic movement. Basslines add harmonic color via passing tones.',
    modality: 'Strongly modal. Coastal taarab imposes Arabic modal sensibility even on modern tracks. Songs avoid clear dominant-to-tonic cadences, resting in floating modal suspension.',
  },

  songStructure: {
    overview: 'Bongo Flava adopts hip-hop/R&B structure shaped by East African taste for extended grooves and repetition. Taarab uses longer through-composed form. Benga is cyclical over continuous groove.',
    form: 'Intro – Verse 1 – Chorus – Verse 2 – Chorus – Bridge/Guest Verse – Chorus – Outro',
    sections: [
      'Intro (groove establishment, 4-8 bars)',
      'Verse (narrative content, lower energy)',
      'Chorus/Hook (melodic Swahili hook, highest energy)',
      'Bridge or feature verse (perspective shift, guest artist)',
      'Outro (groove fade or repeated hook)',
    ],
    arrangement: 'Arrangements build incrementally. Breakdowns before final chorus strip to bass and drums or vocal alone. Guest features coincide with slight production shifts.',
    introOutro: 'Intros begin with signature melodic phrase (oud riff, guitar line, synth melody) over the groove. Outros ride out on the chorus hook, fading with groove still active.',
    barLengths: 'Verse: 8-16 bars. Chorus: 4-8 bars. Bridge: 4-8 bars. Total: 3.5-5 minutes. Taarab extends to 6-8 minutes live.',
    hookPlacement: 'Melodic Swahili hook appears early and repeats 3-4 times. Short (1-2 lines), intensely melodic, often contains the song title.',
  },

  vocalDelivery: {
    overview: 'Melodically ornamented, rhythmically fluid, and deeply expressive. Taarab vocals derive from Arabic tarab (emotional enchantment). Bongo Flava blends hip-hop flow with melodic Swahili phrasing, often code-switching between rapping and singing.',
    phrasing: 'Long arcing melodic phrases in taarab; choppy rhythmic precision in rap-forward Bongo Flava. Phrases often end with descending ornament or drawn-out vowel.',
    affect: 'Romantic longing, pride and swagger, celebration, and social commentary. Even boastful tracks carry warmth and community orientation.',
    techniques: [
      'melismatic ornament (taarab influence)',
      'code-switching between Swahili, English, and Sheng',
      'melodic rapping with consistent pitch contour',
      'call-and-response with backing vocalists',
    ],
    adlibStyle: 'Echoed repetitions, breathy exhales, short Swahili exclamations ("Aaah!", "Ndiyo!", "Bongo!"), producer call-outs.',
    harmony: 'Tight two-to-three-part vocal harmony in choruses. Thirds and fifths favoured. Background vocals double melody in octaves for richness.',
    grit: 'Minimal grit in mainstream Bongo Flava — clean smooth vocals are the standard. Singeli uses deliberately harsh, shouted delivery. Gengetone carries more gravel.',
  },

  lyricalConventions: {
    overview: 'Swahili is a language of proverbs, formality, and poetic beauty. Bongo Flava balances street credibility with linguistic elegance. Love (mapenzi) dominates, alongside social commentary, religion, and everyday urban life.',
    themes: [
      'romantic love and longing (mapenzi)',
      'youth hustle and urban poverty (maisha magumu)',
      'success and ambition',
      'Tanzanian and East African national pride',
      'God, gratitude, and spiritual humility',
      'dance, celebration, and nightlife',
    ],
    perspective: 'First person dominant, often addressing a love interest directly. Community perspective ("sisi") in patriotic anthems.',
    figurativeLanguage: 'Proverbs (methali) signal lyrical intelligence. Extended metaphors (love as ocean, life as journey). Natural imagery (wildlife, Indian Ocean, savanna). Islamic poetic imagery in coastal tracks.',
    vocabulary: 'Core Swahili with heavy borrowing from Arabic, English, Sheng (Nairobi youth slang), and Hindi/Urdu (historic trade). Slang shifts rapidly.',
    storytellingApproach: 'Narrative-first — verses tell mini-stories, chorus provides emotional summary. Taarab uses extended metaphor and oblique suggestion. Singeli uses minimal narrative.',
    cliches: [
      '"Nakupenda sana" as undeveloped hook',
      'diamonds and Rolex as success shorthand',
      '"Bongo" as automatic national ID',
      'beloved compared to stars, moon, or Indian Ocean',
    ],
  },

  productionFingerprint: {
    overview: 'Mature Bongo Flava production is glossy, bass-forward, and melodically driven. Dar es Salaam studios established a continental identity blending Afrobeats influence with Swahili melodic sensibility.',
    mixAesthetic: 'Bass-prominent with warm mid-range. Vocals sit high — clearly intelligible Swahili is non-negotiable. Heavy but musical compression.',
    era: 'Contemporary (2015-present): streaming-era, influenced by Nigerian Afrobeats and American trap/R&B. Classic (1990s-2000s): raw hip-hop influence. Taarab: timeless, acoustic ensemble.',
    signalChain: 'FL Studio dominant; programmed drums blending African percussion with trap kits; soft synths (Nexus, Omnisphere); condenser mic → compression → light autotune → stereo reverb.',
    modernTrends: 'Afrobeats crossover production; amapiano log drum influence; trap hi-hat rolls; pan-African fusion with Congolese and South African sounds.',
  },

  instrumentation: {
    coreInstruments: [
      'programmed drum kit with African percussion samples',
      'sub-bass or 808 bass',
      'melodic synth lead (warm, tropical)',
      'clean electric guitar with chorus/reverb',
      'oud or oud-synth',
      'taarab violin (live or sampled)',
    ],
    signatureSounds: [
      'oud riff as intro or recurring hook',
      'taarab violin ornament',
      'singeli relentless 16th-note snare at 180+ BPM',
      'benga interlocking electric guitar pattern',
    ],
    layering: 'Percussion layered but purposeful. Melodic layers thin during verses, thicken in chorus. Bass and kick tightly sidechained. Taarab layers multiple string voices almost orchestrally.',
    avoidInstruments: [
      'heavy distorted rock guitars',
      'banjo or steel guitar',
      'classical European orchestration without East African melodic content',
      'aggressively detuned 808 bass',
    ],
  },

  culturalContext: {
    overview: 'Swahili music is the cultural expression of the East African coast and interior, rooted in one of Africa\'s oldest cosmopolitan cultures formed over centuries of Indian Ocean trade linking Bantu Africa, Arabia, Persia, and India.',
    origin: 'Dar es Salaam (Tanzania) is the Bongo Flava centre. Zanzibar and Mombasa are historic taarab centres. Nairobi is the origin of gengetone and benga.',
    identity: 'Bongo Flava represents Tanzanian urban youth identity — hustle culture and pan-African aspiration within a Swahili-speaking framework. Using Swahili itself is a cultural statement of East African unity.',
    community: 'Spans Tanzania, Kenya, Uganda, Rwanda, Burundi, eastern DRC, and the Swahili diaspora. Radio, WhatsApp groups, and community listening at barbershops and matatus remain central.',
    socialFunction: 'Taarab: weddings and ceremonies. Bongo Flava: youth entertainment and aspirational soundtrack. Benga: communal dance at funerals and celebrations. Singeli: underground dance culture.',
    authenticityMarkers: [
      'lyrics in Swahili (not primarily English)',
      'Swahili proverbs correctly used',
      'production referencing East African rhythmic traditions',
      'cultural specificity — Dar, Nairobi, Zanzibar references',
      'melodic style reflecting Swahili vocal tradition',
    ],
  },

  historicalLineage: {
    overview: 'One of Africa\'s richest musical lineages, shaped by millennia of Indian Ocean trade and over a century of recording history. From taarab through dansi through benga to Bongo Flava\'s global ambition.',
    roots: [
      'Swahili classical poetry (utenzi traditions)',
      'Arabic tarab music',
      'taarab (19th-20th century coastal ensemble music)',
      'dansi (Tanzanian big band, 1940s-70s)',
      'benga (Kenyan guitar music, 1960s-80s)',
      'Congolese rumba and soukous',
    ],
    evolution: 'Taarab (19th century Zanzibar) → Dansi big bands (1940s-60s) → Benga emergence (Kenya, 1960s) → Hip-hop arrives (1990s) → Bongo Flava crystallizes (late 1990s) → Global streaming era (2010s-present, Diamond Platnumz).',
    keyEras: [
      '19th century: Taarab golden age in Zanzibar',
      '1940s-70s: Tanzanian dansi era',
      '1960s-80s: Benga peak in Kenya',
      '1990s-2000s: Bongo Flava birth and mainstream',
      '2010s-present: East African pop going global',
    ],
    influencedBy: [
      'Arabic tarab and maqam music',
      'Indian film music (Bollywood)',
      'Congolese rumba and soukous',
      'American hip-hop and R&B',
      'Jamaican reggae and dancehall',
    ],
    influenced: [
      'pan-African pop via Diamond Platnumz',
      'East African diaspora music',
      'Afrobeats (via collaborative exchange)',
      'singeli as next-gen subcultural music',
    ],
  },

  subGenres: [
    {
      name: 'Bongo Flava',
      description: 'Tanzania\'s flagship genre — a fusion of hip-hop, R&B, reggae, and taarab sung in Swahili. The dominant commercial sound of East Africa, centred in Dar es Salaam.',
      distinguishingFeatures: ['Swahili lyrics primary', 'hip-hop/R&B framework with East African melodic character', 'bass-heavy groove-centred production', 'heavy commercial crossover'],
      bpmRange: { min: 80, max: 115 },
      keyArtists: ['Diamond Platnumz', 'Harmonize', 'Lady Jaydee', 'Professor Jay'],
      productionNotes: 'FL Studio, Afrobeats-influenced drums, warm synth pads, 808 bass with sidechain, light autotune.',
      lyricNotes: 'Swahili dominant with English phrases. Love, aspiration, hustle, and street wisdom.',
      sunoPromptKeywords: ['Bongo Flava', 'Tanzanian pop', 'Swahili hip-hop', 'East African R&B', 'tropical African pop'],
    },
    {
      name: 'Taarab',
      description: 'Ancient classical music of the Swahili coast, rooted in 19th-century Zanzibar. Ensemble of strings, oud, accordion, and percussion supporting highly ornamented lead vocals.',
      distinguishingFeatures: ['violin, oud, accordion ensemble', 'melismatic vocals', 'Arabic maqam scales', 'slow swaying chakacha groove'],
      bpmRange: { min: 60, max: 85 },
      keyArtists: ['Siti binti Saad', 'Bi Kidude', 'Culture Musical Club'],
      productionNotes: 'Live ensemble recording preferred. Minimal processing — acoustic timbres are the palette.',
      lyricNotes: 'Swahili classical poetry — high literary register. Extended metaphor and coded social commentary.',
      sunoPromptKeywords: ['taarab', 'Zanzibar music', 'Swahili classical', 'oud and violin', 'Arabic African fusion'],
    },
    {
      name: 'Gengetone',
      description: 'Nairobi\'s raucous street-rap genre (2018-2020). Blends trap production with Sheng slang, deliberately crude energy and DIY aesthetic.',
      distinguishingFeatures: ['Sheng-heavy lyrics', 'trap-influenced production', 'crude humour', 'crew/group format'],
      bpmRange: { min: 75, max: 95 },
      keyArtists: ['Ethic Entertainment', 'Sailors Gang', 'Boondocks Gang'],
      productionNotes: 'Trap hi-hats and 808 kicks with East African percussion layered in. Autotune on hooks.',
      lyricNotes: 'Sheng essential — Swahili mixed with English and ethnic languages. Explicit content expected.',
      sunoPromptKeywords: ['gengetone', 'Nairobi street rap', 'Sheng music', 'Kenyan trap', 'urban Nairobi'],
    },
    {
      name: 'Benga',
      description: 'Kenya\'s foundational guitar music, developed by the Luo people in the 1950s-60s. Two interlocking clean electric guitars over bass and percussion with vocals in Dholuo or Swahili.',
      distinguishingFeatures: ['two-guitar interlock signature', 'bright clean electric tone', 'driving upbeat tempo', 'live band format'],
      bpmRange: { min: 110, max: 145 },
      keyArtists: ['D.O. Misiani', 'Ochieng Kabasele', 'George Ramogi'],
      productionNotes: 'Live recording. Bright unprocessed guitar tones. The interlock pattern must be precise.',
      lyricNotes: 'Dholuo or Swahili narrative with sung refrains. Proverbs and moral wisdom.',
      sunoPromptKeywords: ['benga', 'Kenyan guitar music', 'interlocking guitar', 'East African folk guitar'],
    },
    {
      name: 'Singeli',
      description: 'Hyperfast subcultural street music from Dar es Salaam\'s Manzese neighborhood. 180-200 BPM drum machines, frenetic energy, and deliberately raw chaotic aesthetic.',
      distinguishingFeatures: ['extreme BPM (180-200)', 'rapid-fire drum machine rolls', 'raw lo-fi production', 'shouted vocals'],
      bpmRange: { min: 170, max: 210 },
      keyArtists: ['Dully Sykes', 'Mzee Wa Bwax', 'Stamina Daddy'],
      productionNotes: 'Low-cost software, raw drum programming, minimal melody. The chaos is the aesthetic — don\'t clean it up.',
      lyricNotes: 'Street Swahili, rapid-fire delivery. Neighbourhood pride, dance battles, survival.',
      sunoPromptKeywords: ['singeli', 'Tanzanian singeli', 'hyperfast African', '180 BPM', 'frenetic East African'],
    },
    {
      name: 'East African Hip-Hop',
      description: 'Nairobi and Dar es Salaam hip-hop with distinctly East African identity — multilingual (Swahili, English, Sheng), socially conscious, and rooted in specific urban geography.',
      distinguishingFeatures: ['multilingual verses', 'sophisticated wordplay', 'social and political commentary', 'boom-bap with East African melodic sensibility'],
      bpmRange: { min: 80, max: 100 },
      keyArtists: ['Khaligraph Jones', 'Octopizzo', 'Juliani', 'Juma Nature'],
      productionNotes: 'Boom-bap and trap-influenced beats with African percussion. Some incorporate benga guitar samples.',
      lyricNotes: 'Wordplay and lyrical density as primary values. Social commentary — class, inequality, corruption.',
      sunoPromptKeywords: ['East African hip-hop', 'Swahili rap', 'Nairobi rap', 'conscious African rap'],
    },
    {
      name: 'Muziki wa Injili',
      description: 'East African gospel music blending Christian worship with local rhythmic traditions and Swahili lyrics. Ranges from acoustic church praise to fully produced contemporary gospel pop.',
      distinguishingFeatures: ['Swahili worship lyrics', 'choir harmonies', 'blend of Western gospel and East African rhythm', 'uplifting energy'],
      bpmRange: { min: 75, max: 130 },
      keyArtists: ['Rose Muhando', 'Christina Shusho', 'Mercy Masika'],
      productionNotes: 'Clean production with prominent vocals and choir. Keyboards and percussion prominent. Modern gospel adds pop production.',
      lyricNotes: 'Swahili praise and testimony. Personal faith journeys, gratitude, spiritual warfare.',
      sunoPromptKeywords: ['East African gospel', 'Swahili worship', 'Bongo gospel', 'African praise music'],
    },
    {
      name: 'Zilipendwa',
      description: 'The golden era of Tanzanian dansi big band music (1960s-80s). Lush horn arrangements, acoustic bass, live drums, and Swahili romantic lyrics in the high literary tradition.',
      distinguishingFeatures: ['big band ensemble with horns', 'high literary Swahili', 'Cuban son and rumba influence', 'long-form songs with instrumental sections'],
      bpmRange: { min: 90, max: 120 },
      keyArtists: ['DDC Mlimani Park Orchestra', 'Mbaraka Mwinshehe', 'Vijana Jazz Band'],
      productionNotes: 'Live ensemble recording, 1960s-80s aesthetic. Warm compressed sound with horns prominent.',
      lyricNotes: 'Classical Swahili — highest literary register. Extended metaphors and proverbs. Romantic love primary.',
      sunoPromptKeywords: ['zilipendwa', 'Tanzanian dansi', 'East African big band', 'classic Swahili music'],
    },
    {
      name: 'Kenyan Pop',
      description: 'Modern Nairobi-based pop music blending international pop production with Swahili and English lyrics. Artists like Sauti Sol bridged East African pop with global audiences.',
      distinguishingFeatures: ['polished international production', 'Swahili-English bilingual', 'Afrobeats and R&B influence', 'melodic accessibility'],
      bpmRange: { min: 85, max: 120 },
      keyArtists: ['Sauti Sol', 'Nyashinski', 'Otile Brown', 'Nikita Kering'],
      productionNotes: 'Internationally competitive production quality. Afrobeats drum patterns, warm guitars, layered vocals.',
      lyricNotes: 'Love, aspiration, modern life. Bilingual Swahili-English. Accessible and melodic.',
      sunoPromptKeywords: ['Kenyan pop', 'Nairobi pop', 'East African pop', 'Sauti Sol style'],
    },
    {
      name: 'Afro-Bongo',
      description: 'The emerging fusion of Nigerian Afrobeats production with Bongo Flava melodic and lyrical sensibility. Represents the pan-African streaming-era convergence.',
      distinguishingFeatures: ['Afrobeats production templates', 'Swahili vocals over Afrobeats grooves', 'collaborative East-West African features', 'streaming-optimized length and hooks'],
      bpmRange: { min: 90, max: 115 },
      keyArtists: ['Diamond Platnumz (crossover work)', 'Zuchu', 'Mbosso', 'Nandy'],
      productionNotes: 'Afrobeats log drums and guitar patterns combined with Bongo Flava synth warmth. Polished for international streaming.',
      lyricNotes: 'Swahili with more English than traditional Bongo Flava. Love and celebration themes optimized for broad appeal.',
      sunoPromptKeywords: ['Afro-Bongo', 'East African Afrobeats', 'Tanzanian Afrobeats fusion', 'pan-African pop'],
    },
  ],

  sceneAndAudienceCodes: {
    overview: 'The East African music audience is large, young, multilingual, and increasingly globally connected. Centred on Dar es Salaam but radiating across Tanzania, Kenya, Uganda, and Rwanda.',
    fanExpectations: [
      'authentic Swahili lyrics — fans reject poorly constructed Swahili',
      'production quality matching international standards',
      'cultural specificity — East African references, not generic Africa',
      'melodic hooks — singable chorus is non-negotiable',
      'dance potential — the groove must move the body',
    ],
    gatekeeping: 'Moderate. Authentic Swahili speakers immediately identify clumsy Swahili. Cultural knowledge of East African geography, food, and social norms must be correct. Foreign collaborators receive scrutiny.',
    livePerformance: 'Concerts are major events — Diamond Platnumz sells out across East and Central Africa. Strong vocal delivery expected live. Taarab is slower and ceremonial. Singeli events are intensely physical.',
    fashionAndAesthetic: 'Bongo Flava fashion blends global luxury with African prints (kitenge, ankara) — confident cosmopolitan-African identity. Taarab is more formal (kanga, bui-bui). Singeli adopts street wear.',
    crossoverPotential: 'Growing rapidly via streaming. Diamond Platnumz collaborates internationally. Swahili-language barrier limits Western mainstream, but pan-African pop ecosystem creates growing pathways.',
  },

  // ── Relational & Embodied Dimensions ──────────────────────────────

  microTimingAndFeel: {
    overview: 'East African music operates with polyrhythmic timing inherited from African rhythmic traditions — multiple rhythmic layers interlock to create a composite groove where no single element carries the "correct" timing. Benga\'s two-guitar interlock is the purest expression of this principle.',
    quantizationDeviation: 'Moderate to high in live-played genres (benga, taarab, dansi). Low in modern Bongo Flava (programmed drums on grid). Singeli uses extreme grid-locked precision at 180+ BPM where deviation would cause chaos.',
    aheadBehindBeat: 'Benga guitar parts deliberately displace the perceived downbeat — each guitar part feels "ahead" or "behind" relative to the other, but together they lock into a composite groove. Bongo Flava vocals often sit slightly behind the beat for relaxed swagger.',
    humanizationMarkers: [
      'benga two-guitar interlock timing creating composite groove through displacement',
      'taarab ensemble heterophonic timing variation from Arabic musical inheritance',
      'kidumbak Zanzibar percussion with natural hand-drum micro-timing',
      'live bass guitar playing with slight timing push in dansi big band style',
      'vocal timing floating over the groove in Bongo Flava melodic delivery',
    ],
    genreSpecificFeel: 'The East African feel is warm, forward-leaning, and interpersonally relational — the groove is created by the relationship between parts, not by any single part\'s precision. Even programmed Bongo Flava aims to recreate this relational timing quality.',
  },

  silenceAndSpace: {
    overview: 'Swahili music uses space to let the groove breathe and to frame the melodic Swahili hook. The breakdown before the final chorus — stripping to bass and voice — is a signature Bongo Flava production technique.',
    negativeSpaceRole: 'In benga, the spaces between guitar notes are as important as the notes themselves — the interlock pattern is defined by where each guitar is silent. In Bongo Flava, breakdowns create anticipation for the hook\'s return.',
    breathingPatterns: 'Taarab breathes with the singer — the ensemble pauses when the vocalist pauses, creating a conversational temporal flow. Bongo Flava uses programmed breakdowns as structural breathing. Singeli barely breathes — the relentless energy is the point.',
    dynamicContrast: 'Moderate in Bongo Flava (verse-chorus contrast). Low in singeli (uniformly intense). High in taarab (intimate whisper to full ensemble power). Benga maintains consistent energy with variation through guitar pattern changes rather than dynamic shifts.',
    whatIsDeliberatelyAbsent: [
      'heavy sub-bass in taarab — the acoustic ensemble carries the low end naturally',
      'electronic elements in classic benga — clean guitar and acoustic drums only',
      'vocal processing in taarab — the natural voice is paramount',
      'Western harmony in traditional coastal music — maqam modal framework instead',
      'polish in singeli production — raw chaotic energy is the aesthetic',
    ],
  },

  callAndResponse: {
    overview: 'Call-and-response is foundational to East African musical culture — from Swahili work songs and communal celebrations to benga\'s guitar dialogues and Bongo Flava\'s verse-hook relationship.',
    vocalInstrumentalDialogue: 'In benga, the two guitars converse with each other — one calls, the other responds, creating the interlock pattern. In taarab, the oud or violin responds to vocal phrases. In Bongo Flava, synth hooks answer vocal lines.',
    sectionInternal: 'Verses in Bongo Flava frequently feature call-and-response between lead vocalist and backing singers. Taarab builds intensity through soloist-chorus exchanges. Gospel (muziki wa injili) relies heavily on lead-congregation response.',
    audienceParticipation: 'Concert crowds sing the hook and dance. Wedding taarab audiences respond to coded lyrics with ululation and dancing. Church music is fully participatory. Singeli events involve the crowd matching the frenetic energy with dance.',
    patterns: [
      'lead vocalist singing a phrase and backing vocalists echoing or completing it',
      'benga two-guitar call-and-response interlock as the genre\'s DNA',
      'wedding crowd ululating in response to taarab performance highlights',
      'gospel congregation singing the chorus after the worship leader\'s verse',
      'MC/hypeman energizing the crowd between artist verses at live shows',
    ],
  },

  regionalDialectSpecificity: {
    overview: 'Swahili varies significantly across East Africa — Tanzanian Swahili, Kenyan Swahili, Congolese Swahili, and coastal archaic Swahili each carry distinct musical identities. The choice of Swahili register signals cultural allegiance and target audience.',
    phoneticMarkers: [
      'Tanzanian standard Swahili — clearest and most "textbook" pronunciation',
      'Kenyan Swahili mixed with Sheng (Nairobi youth slang) in gengetone',
      'coastal Zanzibari Swahili with Arabic-influenced phonology in taarab',
      'Congolese Swahili (Kingwana) with Lingala influence in eastern DRC music',
      'Luo-accented Swahili in Kenyan benga from western Kenya',
    ],
    accentInfluence: 'Tanzanian Swahili is considered the most "pure" and is the default for Bongo Flava. Kenyan Sheng creates a distinctly Nairobi sonic identity. Coastal Swahili\'s Arabic phonological influence shapes taarab vocal delivery.',
    dialectVocabulary: [
      'Sheng terms ("manze", "maze", "sawa") marking Nairobi youth identity',
      'Arabic-Swahili vocabulary ("habibi", "mashallah") in coastal music',
      'Tanzanian slang ("bongo", "mchizi", "fundi") in Bongo Flava',
      'Lingala vocabulary crossing into Congolese Swahili music',
      'Zanzibari archaic Swahili ("harusi", "tafrija") in taarab preserving historical vocabulary',
    ],
    regionWithinCulture: 'Dar es Salaam is the Bongo Flava centre and the commercial heart of Swahili music. Nairobi is the gengetone and Kenyan pop hub. Zanzibar and Mombasa are the taarab heartlands. Kampala contributes to the broader East African pop ecosystem. Each city has a distinct musical identity.',
  },

  performancePractice: {
    overview: 'East African performance spans outdoor festival spectacles, taarab wedding ceremonies, church worship gatherings, political rally music, and the intense physicality of singeli underground dance events.',
    improvisationConventions: 'Taarab allows vocal ornamental improvisation within the maqam framework. Benga guitarists improvise solos within the interlock structure. Bongo Flava concerts are largely pre-planned. Singeli MCs freestyle over beats.',
    crowdInteraction: 'East African concert crowds are physically expressive — dancing is expected, not optional. Taarab wedding audiences place money on the performer as appreciation. Radio and WhatsApp create distributed "audience" communities.',
    stagePresence: 'Bongo Flava artists project confident charisma — flashy clothing, energetic movement, swagger. Taarab performers are more formal and ceremonial. Benga bands perform in matching outfits with coordinated movement. Singeli performers channel chaotic street energy.',
    livVsRecordedDifferences: 'Bongo Flava live performances add crowd interaction, extended intros, and DJ segues. Taarab can extend dramatically in live wedding settings. Benga live shows feature extended instrumental interlock jams. Recorded versions are tighter and more produced.',
    whatMakesAGoodShow: 'Energy, crowd connection, and physical engagement. The artist must make the audience dance. Strong vocal delivery is expected. Guest appearances create excitement. The sound system quality matters enormously — bass must be felt physically.',
  },

  socioeconomicSubtext: {
    overview: 'Swahili music reflects East Africa\'s post-independence nation-building, urban migration, coastal trade heritage, and the economic realities of young populations in rapidly urbanizing societies.',
    materialConditions: 'Music production operates on limited budgets compared to global standards — FL Studio and affordable equipment are standard. Revenue comes from live performance, ringtone sales, and increasingly streaming. Diamond Platnumz built an independent label as an economic model.',
    classIdentity: 'Bongo Flava celebrates hustle and aspiration — from street survival to success. Taarab carries associations with educated coastal Swahili culture. Singeli is explicitly working-class Manzese neighbourhood music. Gengetone reflects Nairobi\'s informal economy youth culture.',
    politicalUndercurrent: 'Tanzanian music has a legacy of post-independence cultural nationalism (Julius Nyerere\'s promotion of Swahili music as nation-building). Kenyan music engages with tribal politics and corruption. Political rally music remains a live tradition across East Africa.',
    implicitReferences: [
      'urban migration from rural areas reflected in songs about city hustle',
      'Tanzanian national pride and Nyerere\'s ujamaa legacy in patriotic themes',
      'coastal trade culture heritage in taarab\'s Indian Ocean cosmopolitanism',
      'economic inequality between Dar es Salaam\'s neighborhoods referenced in Bongo Flava',
      'pan-African aspiration expressed through collaboration with Nigerian and South African artists',
    ],
  },

  intertextualityAndSampling: {
    overview: 'Swahili music\'s intertextual web connects taarab\'s 19th-century Zanzibari roots, dansi big band era classics, benga\'s Kenyan guitar tradition, Congolese rumba influence, and the modern Bongo Flava-Afrobeats convergence.',
    canonKnowledge: 'Siti binti Saad is the foundational taarab recording artist. Bi Kidude is the living-memory taarab legend. Mlimani Park Orchestra represents the dansi golden age. Diamond Platnumz defined modern Bongo Flava\'s global ambition.',
    samplingTradition: 'Direct sampling is uncommon due to limited catalog digitization. Melodic interpolation of taarab phrases in Bongo Flava is common. Congolese rumba guitar patterns are absorbed into the East African guitar vocabulary. Afrobeats production templates are adapted.',
    quotationPractice: 'Classic dansi (zilipendwa) songs are re-performed at events as cultural continuity. Taarab poetry is quoted in modern Swahili songs. Benga guitar interlock patterns from canonical recordings are replicated as genre identity markers.',
    expectedReferences: [
      'Diamond Platnumz as the modern Bongo Flava benchmark',
      'Mlimani Park Orchestra as the dansi-era reference point',
      'Bi Kidude as the taarab living legend',
      'Sauti Sol as East African pop crossover pioneers',
      'D.O. Misiani as the benga guitar master',
    ],
    lineageSignifiers: [
      'benga two-guitar interlock pattern as Kenyan musical DNA',
      'taarab oud presence as Indian Ocean trade culture heritage',
      'Congolese rumba guitar influence as pan-African connection',
      'dansi horn arrangements as Tanzanian big band lineage',
      'Swahili proverb usage in lyrics as literary continuity',
      'maqam melodic vocabulary as coastal Arabic-African fusion marker',
    ],
  },

  genderAndBodyConventions: {
    overview: 'East African music has distinct gender traditions shaped by coastal Swahili culture, Christian and Islamic influences, and contemporary urban youth culture. Taarab has historically provided women significant artistic authority, while modern Bongo Flava navigates between traditional expectations and global pop influence.',
    vocalGenderCodes: 'Female taarab singers command through ornamental vocal mastery and poetic sophistication. Male Bongo Flava artists emphasize confident, swagger-laden delivery. Female Bongo Flava artists blend melodic sweetness with assertive lyrical content. Gospel music features powerful female vocalists in leadership roles.',
    physicalityInPerformance: 'Bongo Flava performance involves confident physical movement for both genders, with increasing global pop choreography influence. Taarab performance is more restrained and ceremonial. Singeli involves intense, athletic physical movement regardless of gender.',
    genderNarratives: 'Male Bongo Flava lyrics often address romantic pursuit, success, and social commentary. Female artists increasingly assert independence and romantic agency. Taarab\'s coded lyrics allowed women to address social issues and romantic dissatisfaction through metaphor.',
    subversionExamples: [
      'Bi Kidude performing taarab into her 90s with uncompromising artistic authority',
      'Lady Jaydee pioneering female Bongo Flava in a male-dominated industry',
      'Zuchu achieving commercial dominance in Tanzanian music',
      'female gengetone artists in Nairobi claiming space in aggressive street-rap',
      'taarab\'s historical role as a space for women\'s social commentary through coded lyrics',
    ],
  },

  tempoFeelVsNumber: {
    overview: 'East African music spans an enormous tempo range — from taarab\'s swaying 70 BPM to singeli\'s frenetic 200 BPM — and the felt experience varies even more than the numbers suggest due to polyrhythmic complexity and cultural movement context.',
    psychologicalTempo: 'Bongo Flava at 95 BPM feels warm, relaxed, and body-moving — designed for social dancing. Benga at 130 BPM feels bright and propulsive despite the moderate tempo because the interlocking guitars create an exciting perceptual complexity. Singeli at 190 BPM feels chaotic and physically overwhelming.',
    weightAndMomentum: 'Bongo Flava carries warm weight through sub-bass and round synth tones. Benga is lighter and more nimble — the clean guitar tones create buoyancy. Singeli is weightless and chaotic — speed replaces gravity. Taarab has the weight of ceremony and tradition.',
    urgencyScale: 'Taarab creates emotional urgency through vocal intensity, not tempo. Bongo Flava creates groove urgency — the need to move the body. Singeli is maximum physical urgency — the tempo demands response. Benga creates joyful urgency through guitar interplay.',
    comparisonToSameBPM: 'East African music at 95 BPM feels more physically engaging than Western pop at 95 BPM because the polyrhythmic layering and bass-forward mix create a groove that demands bodily response. The music is designed for movement, not just listening.',
  },

  mistakeConventions: {
    overview: 'East African music has a pragmatic relationship with imperfection — resource constraints have made lo-fi production an accepted norm, and the groove\'s relational quality means that "mistakes" can become part of the feel.',
    toleratedImperfections: [
      'benga guitar timing variation within the interlock — adds human warmth',
      'taarab ensemble heterophonic timing differences — traditional texture',
      'Bongo Flava vocal pitch variation — melodic delivery valued over pitch precision',
      'live recording ambient noise — captures the environment authentically',
    ],
    celebratedFlaws: [
      'singeli\'s deliberately chaotic, lo-fi production as genre identity',
      'gengetone\'s rough, unpolished aesthetic as street authenticity',
      'vintage dansi recordings\' tape warmth and compression as nostalgic quality',
      'live benga recordings capturing the energy of the performance environment',
    ],
    overproductionRisks: [
      'polishing Bongo Flava to Western pop standards and losing its warmth',
      'quantizing benga guitar interlock to a grid — destroying the relational timing',
      'auto-tuning taarab vocals — removing the ornamental microtonal character',
      'replacing live percussion with programmed samples in genres where hand-drum texture matters',
      'Afrobeats production templates erasing specifically East African sonic identity',
    ],
    authenticRoughness: 'Expected in singeli and gengetone — polish would strip identity. Tolerated in Bongo Flava (production is improving but warmth matters more than sterility). Unacceptable in taarab (vocal mastery is non-negotiable). The East African market increasingly demands higher production quality while maintaining cultural specificity.',
  },

  sunoPromptGuide: {
    essentialKeywords: [
      'Bongo Flava',
      'Swahili vocals',
      'East African',
      'Tanzanian',
      'taarab influence',
      'melodic African',
      'Dar es Salaam',
      'warm tropical',
    ],
    avoidKeywords: [
      'West African (as primary descriptor)',
      'Pidgin English (Nigerian — use Swahili)',
      'Yoruba',
      'Lagos',
      'heavy metal',
      'country',
    ],
    promptTemplate: '[sub-genre] Bongo Flava / [taarab/benga/singeli], [BPM] BPM, [mood], Swahili vocals, [oud/benga guitar/808 bass], [warm/frenetic/lush] production',
    tips: [
      'Always specify sub-genre — Bongo Flava, taarab, singeli, and benga sound completely different.',
      'Specify "Swahili vocals" explicitly to steer away from generic Afrobeats English.',
      'Use "oud" or "taarab influence" to invoke Indian Ocean coastal heritage.',
      'For singeli, specify 180-200 BPM and describe as "frenetic" and "hyperfast".',
    ],
  },
};
